module.exports = [
{id:"chorrillana", c:"Chile", r:"latin-america", m:"main", t:40, s:4,
 i:[[1,"kg","potato","structure","papas","potatoes","en bastones","in batons"],
    [1,"l","oil","fat","aceite para freír","oil for frying"],
    [500,"g","beef","protein","carne de res","beef steak","en tiras","in strips"],
    [2,"","onion","aromatic","cebollas","onions","en pluma","sliced"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [4,"","egg","protein","huevos","eggs"],
    [2,"tsp","salt","salt","sal","salt"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"]],
 es:{n:"Chorrillana", b:"Una montaña de papas fritas con carne salteada, cebolla y huevos fritos encima. Para compartir en Valparaíso.",
  st:["Fríe las papas a 160 °C durante 8 minutos. Sube a 190 °C y fríe 3 minutos más, hasta que estén doradas. Sala.",
      "Saltea la cebolla en 1 cucharada de aceite 10 minutos, hasta que esté blanda y dorada.",
      "Saltea la carne con el comino y 1 cucharadita de sal en el resto del aceite a fuego fuerte 3 minutos. Mezcla con la cebolla.",
      "Fríe los huevos.",
      "Pon las papas en una fuente grande, la carne y la cebolla encima y los huevos al final."],
  tp:["Sirve de inmediato: las papas pierden lo crujiente bajo la carne.",
      "Corta la carne en tiras finas para que se saltee en poco tiempo."],
  v:"chorrillana chilena receta"},
 en:{n:"Chorrillana (Chilean Loaded Fries)", b:"A mountain of chips with stir-fried beef, onion and fried eggs on top. For sharing in Valparaíso.",
  st:["Fry the potatoes at 160 °C for 8 minutes. Raise to 190 °C and fry 3 minutes more, until golden. Salt.",
      "Cook the onion in 1 tablespoon of oil for 10 minutes, until soft and golden.",
      "Stir-fry the beef with the cumin and 1 teaspoon of salt in the rest of the oil over high heat for 3 minutes. Mix with the onion.",
      "Fry the eggs.",
      "Pile the chips on a large platter, the beef and onion on top and the eggs last."],
  tp:["Serve at once: the chips lose their crunch under the meat.",
      "Cut the beef in thin strips so it stir-fries quickly."],
  v:"chorrillana recipe"}},

{id:"machas-a-la-parmesana", c:"Chile", r:"latin-america", m:"starter", t:20, s:4, o:220,
 i:[[24,"","clam","protein","machas o almejas grandes en su concha","razor clams or large clams on the half shell"],
    [100,"ml","winewhite","liquid","vino blanco","white wine"],
    [40,"g","butter","fat","mantequilla","butter","en trocitos","in small pieces"],
    [100,"g","parmesan","glaze","queso parmesano rallado","grated parmesan"],
    [1,"","citrus","acid","limón","lemon","en jugo","juiced"],
    [1,"pinch","pepper","aromatic","pimienta blanca","white pepper"]],
 es:{n:"Machas a la parmesana", b:"Machas en su concha con vino blanco, mantequilla y parmesano, gratinadas. Aperitivo chileno de costa.",
  st:["Pon las machas en su media concha sobre una bandeja.",
      "Echa unas gotas de limón y un chorrito de vino en cada una.",
      "Añade un trocito de mantequilla y una pizca de pimienta.",
      "Cubre con el parmesano.",
      "Gratina a 220 °C durante 5 minutos, hasta que el queso esté dorado."],
  tp:["No las dejes más de 5 minutos o se endurecen.",
      "Asienta las conchas sobre sal gruesa para que no se vuelquen."],
  v:"machas a la parmesana receta"},
 en:{n:"Machas a la Parmesana (Clams with Parmesan)", b:"Clams on the half shell with white wine, butter and parmesan, grilled. A Chilean coastal starter.",
  st:["Arrange the clams on their half shells on a tray.",
      "Add a few drops of lemon and a splash of wine to each.",
      "Add a small piece of butter and a pinch of pepper.",
      "Cover with the parmesan.",
      "Bake at 220 °C for 5 minutes, until the cheese is golden."],
  tp:["Don't leave them more than 5 minutes or they toughen.",
      "Sit the shells on coarse salt so they don't tip over."],
  v:"machas a la parmesana recipe"}},

{id:"paila-marina", c:"Chile", r:"latin-america", m:"soup", t:45, s:4,
 i:[[2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"","bellpepper","aromatic","pimiento rojo","red bell pepper","picado","chopped"],
    [1,"tsp","paprika","aromatic","ají de color (pimentón)","sweet paprika (ají de color)"],
    [150,"ml","winewhite","liquid","vino blanco","white wine"],
    [1,"l","fishstock","liquid","caldo de pescado","fish stock"],
    [400,"g","whitefish","protein","congrio o pescado blanco","conger eel or white fish","en trozos","in chunks"],
    [500,"g","mussel","protein","choritos (mejillones)","mussels","limpios","cleaned"],
    [500,"g","clam","protein","almejas","clams","purgadas","purged"],
    [200,"g","shrimp","protein","camarones","shrimp","pelados","peeled"],
    [1,"handful","herb","garnish","cilantro o perejil","cilantro or parsley","picado","chopped"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Paila marina", b:"Sopa de mariscos y pescado servida en paila de greda, hirviendo. El plato de los mercados de Chile.",
  st:["Sofríe la cebolla, el ajo y el pimiento en el aceite 8 minutos. Añade el ají de color.",
      "Añade el vino y cuece 2 minutos. Añade el caldo y la sal y hierve.",
      "Añade el pescado y cuece 4 minutos.",
      "Añade los choritos, las almejas y los camarones, tapa y cuece 4 minutos, hasta que se abran.",
      "Sirve de inmediato con la hierba picada. Tira los mariscos que no se abran."],
  tp:["Cada marisco entra en su momento: el pescado primero, lo delicado al final.",
      "Si tienes paila de barro, caliéntala en el horno y sirve en ella hirviendo."],
  v:"paila marina chilena receta"},
 en:{n:"Paila Marina (Chilean Seafood Soup)", b:"A seafood and fish soup served boiling in a clay dish. The dish of Chile's markets.",
  st:["Cook the onion, garlic and pepper in the oil for 8 minutes. Add the paprika.",
      "Add the wine and cook 2 minutes. Add the stock and salt and bring to a boil.",
      "Add the fish and cook 4 minutes.",
      "Add the mussels, clams and shrimp, cover and cook 4 minutes, until open.",
      "Serve at once with the chopped herb. Discard any shellfish that stay closed."],
  tp:["Each seafood goes in at its moment: fish first, the delicate ones last.",
      "If you have a clay dish, heat it in the oven and serve in it boiling."],
  v:"paila marina recipe"}},

{id:"kuchen-de-manzana", c:"Chile", r:"latin-america", m:"sweet", t:75, s:10, o:180,
 i:[[250,"g","apflour","structure","harina de trigo","plain flour"],
    [1,"tsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [80,"g","sugar","sweet","azúcar","sugar"],
    [120,"g","butter","fat","mantequilla fría","cold butter","en dados","diced"],
    [1,"","egg","binder","huevo","egg"],
    [4,"","fruit","structure","manzanas","apples","en láminas finas","thinly sliced"],
    [200,"ml","cream","enrich","crema de leche","cream"],
    [2,"","egg","set","huevos","eggs"],
    [80,"g","sugar","sweet","azúcar para el relleno","sugar for the filling"],
    [1,"tsp","spice","aromatic","canela molida","ground cinnamon"]],
 es:{n:"Kuchen de manzana", b:"Tarta de masa quebrada con manzanas y crema, herencia alemana del sur de Chile.",
  st:["Mezcla la harina, el polvo de hornear y 80 g de azúcar. Frota la mantequilla hasta tener migas. Añade 1 huevo y junta la masa. Refrigera 20 minutos.",
      "Forra un molde de 26 cm con la masa, presionando con los dedos.",
      "Coloca las manzanas en círculos superpuestos.",
      "Bate la crema con 2 huevos, el azúcar del relleno y la canela y viértelo sobre las manzanas.",
      "Hornea a 180 °C durante 45 minutos, hasta que la crema cuaje y esté dorada."],
  tp:["Usa manzanas ácidas que aguanten el horno sin deshacerse.",
      "Se sirve a la hora de once con té."],
  v:"kuchen de manzana chileno"},
 en:{n:"Chilean Apple Kuchen", b:"A shortcrust tart with apples and cream, a German legacy from southern Chile.",
  st:["Mix the flour, baking powder and 80 g of sugar. Rub in the butter to crumbs. Add 1 egg and bring together. Chill 20 minutes.",
      "Line a 26 cm tin with the dough, pressing with your fingers.",
      "Arrange the apples in overlapping circles.",
      "Whisk the cream with 2 eggs, the filling sugar and the cinnamon and pour over the apples.",
      "Bake at 180 °C for 45 minutes, until the custard is set and golden."],
  tp:["Use tart apples that hold their shape in the oven.",
      "Served at teatime (once) with tea."],
  v:"chilean apple kuchen recipe"}},

{id:"pan-amasado", c:"Chile", r:"latin-america", m:"bread", t:150, s:12, o:200,
 i:[[1,"kg","apflour","structure","harina de trigo","plain flour"],
    [10,"g","yeast","leaven","levadura seca","dried yeast"],
    [1,"tsp","sugar","sweet","azúcar","sugar"],
    [15,"g","salt","salt","sal","salt"],
    [100,"g","lard","fat","manteca de cerdo derretida","melted lard"],
    [500,"ml","water","liquid","agua tibia","warm water"]],
 es:{n:"Pan amasado", b:"Pan chileno redondo y denso, hecho con manteca y pinchado con tenedor. El pan del campo y de la once.",
  st:["Mezcla la harina, la levadura, el azúcar y la sal. Añade la manteca y el agua y amasa 15 minutos, hasta que esté lisa.",
      "Tapa y deja reposar 30 minutos.",
      "Divide en 12 bollos, aplánalos a 2 cm y pínchalos con un tenedor.",
      "Deja crecer 40 minutos en la bandeja.",
      "Hornea a 200 °C durante 20 minutos, hasta que estén dorados."],
  tp:["El amasado largo es lo que le da su miga apretada.",
      "Pínchalos bien: evita que se inflen como globos."],
  v:"pan amasado chileno receta"},
 en:{n:"Pan Amasado (Chilean Lard Bread)", b:"A round, dense Chilean bread made with lard and pricked with a fork. Country bread for teatime.",
  st:["Mix the flour, yeast, sugar and salt. Add the lard and water and knead 15 minutes, until smooth.",
      "Cover and rest 30 minutes.",
      "Divide into 12 rolls, flatten to 2 cm and prick with a fork.",
      "Rise 40 minutes on the tray.",
      "Bake at 200 °C for 20 minutes, until golden."],
  tp:["The long kneading gives its tight crumb.",
      "Prick them well: it stops them puffing like balloons."],
  v:"pan amasado recipe"}},

{id:"ensalada-chilena", c:"Chile", r:"latin-america", m:"side", t:15, s:4,
 i:[[4,"","tomato","structure","tomates","tomatoes","pelados, en gajos finos","peeled, in thin wedges"],
    [1,"","onion","aromatic","cebolla","onion","en pluma muy fina","very thinly sliced"],
    [1,"handful","herb","aromatic","cilantro","cilantro","picado","chopped"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Ensalada chilena", b:"Tomate pelado con cebolla en pluma desflemada y cilantro. Acompaña el asado y las empanadas.",
  st:["Remoja la cebolla en agua fría con sal 15 minutos para quitarle el picor. Escurre.",
      "Pela los tomates y córtalos en gajos finos.",
      "Mezcla el tomate con la cebolla.",
      "Aliña con el aceite y la sal.",
      "Termina con el cilantro."],
  tp:["Desflemar la cebolla es lo que la hace suave y crujiente.",
      "Para pelar los tomates, sumérgelos 20 segundos en agua hirviendo."],
  v:"ensalada chilena receta"},
 en:{n:"Ensalada Chilena (Tomato and Onion Salad)", b:"Peeled tomato with soaked sliced onion and cilantro. Served with barbecue and empanadas.",
  st:["Soak the onion in cold salted water for 15 minutes to tame it. Drain.",
      "Peel the tomatoes and cut into thin wedges.",
      "Mix the tomato with the onion.",
      "Dress with the oil and salt.",
      "Finish with the cilantro."],
  tp:["Soaking the onion makes it mild and crunchy.",
      "To peel the tomatoes, dip them in boiling water for 20 seconds."],
  v:"chilean salad recipe"}},

{id:"humitas-chilenas", c:"Chile", r:"latin-america", m:"main", t:90, s:6,
 i:[[8,"","corn","structure","choclos (mazorcas frescas) con sus hojas","fresh corn cobs with their husks"],
    [1,"","onion","aromatic","cebolla","onion","picada fina","finely chopped"],
    [40,"g","butter","fat","mantequilla","butter"],
    [1,"handful","herb","aromatic","albahaca","basil","picada","chopped"],
    [100,"ml","milk","moisture","leche","milk"],
    [2,"tsp","salt","salt","sal","salt"],
    [1,"tsp","paprika","aromatic","ají de color","sweet paprika (ají de color)"]],
 es:{n:"Humitas chilenas", b:"Pasta de choclo fresco con cebolla y albahaca, envuelta en sus hojas y hervida. Plato de verano.",
  st:["Corta la base de los choclos y saca las hojas con cuidado. Guarda las más grandes.",
      "Ralla o muele los granos de choclo.",
      "Sofríe la cebolla en la mantequilla con el ají de color 5 minutos. Mezcla con el choclo, la albahaca, la leche y la sal.",
      "Pon 2 hojas cruzadas, añade 3 cucharadas de pasta, dobla en paquete y ata con tiras de hoja.",
      "Cuece en agua hirviendo con sal 40 minutos."],
  tp:["Si la pasta queda muy líquida, añade menos leche; depende de lo tierno del choclo.",
      "Se comen calientes, recién sacadas del agua."],
  v:"humitas chilenas receta"},
 en:{n:"Chilean Humitas (Fresh Corn Parcels)", b:"A paste of fresh corn with onion and basil, wrapped in its husks and boiled. A summer dish.",
  st:["Cut the base off the cobs and carefully remove the husks. Keep the largest.",
      "Grate or grind the corn kernels.",
      "Cook the onion in the butter with the paprika for 5 minutes. Mix with the corn, basil, milk and salt.",
      "Cross 2 husks, add 3 tablespoons of paste, fold into a parcel and tie with strips of husk.",
      "Boil in salted water for 40 minutes."],
  tp:["If the paste is very runny, add less milk; it depends on how young the corn is.",
      "Eat them hot, straight from the water."],
  v:"chilean humitas recipe"}},

{id:"majadito", c:"Bolivia", r:"latin-america", m:"main", t:60, s:4,
 i:[[400,"g","driedmeat","protein","charque de res","beef charque (dried beef)","desalado y desmenuzado","desalted and shredded"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"","tomato","sauce","tomates","tomatoes","picados","chopped"],
    [1,"","bellpepper","aromatic","pimiento verde","green bell pepper","picado","chopped"],
    [1,"tsp","achiote","aromatic","urucú (achiote)","annatto (urucú)"],
    [300,"g","rice","structure","arroz","rice"],
    [800,"ml","water","liquid","agua","water"],
    [4,"","egg","protein","huevos","eggs"],
    [2,"","plantain","serve","plátanos maduros","ripe plantains","en rodajas, fritos","sliced, fried"]],
 es:{n:"Majadito de charque", b:"Arroz amarillo de urucú con charque desmenuzado, huevo frito y plátano. De Santa Cruz, Bolivia.",
  st:["Fríe el charque en el aceite 5 minutos, hasta que esté dorado.",
      "Añade la cebolla, el tomate, el pimiento y el urucú y cuece 5 minutos.",
      "Añade el arroz y el agua, tapa y cuece 20 minutos a fuego bajo. Debe quedar húmedo.",
      "Fríe los huevos.",
      "Sirve el majadito con un huevo encima y el plátano frito al lado."],
  tp:["Prueba el charque antes de salar; normalmente no hace falta sal.",
      "El majadito queda más húmedo que un arroz normal; remuévelo al final."],
  v:"majadito de charque receta"},
 en:{n:"Majadito (Bolivian Charque Rice)", b:"Annatto-yellow rice with shredded dried beef, fried egg and plantain. From Santa Cruz, Bolivia.",
  st:["Fry the charque in the oil for 5 minutes, until golden.",
      "Add the onion, tomato, pepper and annatto and cook 5 minutes.",
      "Add the rice and water, cover and cook 20 minutes on low. It should stay moist.",
      "Fry the eggs.",
      "Serve the majadito with an egg on top and the fried plantain alongside."],
  tp:["Taste the charque before salting; usually none is needed.",
      "Majadito is moister than ordinary rice; stir it at the end."],
  v:"majadito recipe"}},

{id:"api-morado", c:"Bolivia", r:"latin-america", m:"drink", t:40, s:6,
 i:[[200,"g","cornmeal","structure","harina de maíz morado","purple corn flour"],
    [1.5,"l","water","liquid","agua","water"],
    [2,"","spice","aromatic","ramas de canela","cinnamon sticks"],
    [4,"","spice","aromatic","clavos de olor","whole cloves"],
    [1,"","fruit","aromatic","cáscara de piña","pineapple peel"],
    [150,"g","sugar","sweet","azúcar","sugar"]],
 es:{n:"Api morado", b:"Bebida caliente y espesa de maíz morado con canela y clavo. Se toma con pasteles de queso en las mañanas frías.",
  st:["Hierve 1 l del agua con la canela, los clavos y la cáscara de piña 15 minutos. Cuela.",
      "Disuelve la harina de maíz en el resto del agua fría.",
      "Añade la mezcla al agua caliente, batiendo.",
      "Cuece a fuego bajo 15 minutos, sin dejar de remover, hasta que espese.",
      "Añade el azúcar y sirve caliente."],
  tp:["Remueve siempre o se forman grumos.",
      "Si espesa demasiado, añade agua caliente."],
  v:"api morado boliviano receta"},
 en:{n:"Api Morado (Hot Purple Corn Drink)", b:"A thick hot drink of purple corn with cinnamon and clove. Drunk with cheese pastries on cold mornings.",
  st:["Boil 1 l of the water with the cinnamon, cloves and pineapple peel for 15 minutes. Strain.",
      "Dissolve the corn flour in the rest of the cold water.",
      "Add it to the hot water, whisking.",
      "Cook on low for 15 minutes, stirring constantly, until thick.",
      "Add the sugar and serve hot."],
  tp:["Keep stirring or lumps form.",
      "If it gets too thick, add hot water."],
  v:"api morado recipe"}},

{id:"fricase-paceno", c:"Bolivia", r:"latin-america", m:"soup", t:150, s:6,
 i:[[1.2,"kg","pork","protein","costilla o pierna de cerdo","pork ribs or leg","en trozos","in pieces"],
    [2.5,"l","water","liquid","agua","water"],
    [3,"tbsp","ajipaste","aromatic","ají amarillo molido","ground ají amarillo"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [4,"clove","garlic","aromatic","ajo","garlic","molido","crushed"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [2,"tsp","salt","salt","sal","salt"],
    [60,"g","breadcrumbs","thicken","pan molido","breadcrumbs"],
    [6,"","potato","structure","papas","potatoes","cocidas","boiled"],
    [500,"g","hominy","structure","mote de maíz blanco","white hominy (mote)","cocido","cooked"]],
 es:{n:"Fricasé paceño", b:"Sopa picante de cerdo con ají amarillo, comino y mote. El levantamuertos de La Paz.",
  st:["Cuece el cerdo en el agua con la sal 60 minutos, quitando la espuma.",
      "Sofríe la cebolla, el ajo, el ají, el comino y el orégano en un poco de la grasa del cerdo 10 minutos.",
      "Añade el sofrito a la olla y cuece 40 minutos más.",
      "Añade el pan molido para espesar y cuece 10 minutos.",
      "Sirve con una papa y mote en cada plato."],
  tp:["Añade el pan molido poco a poco hasta la espesura que te guste.",
      "Es mejor recalentado."],
  v:"fricasé paceño receta"},
 en:{n:"Fricasé Paceño (La Paz Pork and Chilli Soup)", b:"A spicy pork soup with ají amarillo, cumin and hominy. La Paz's hangover cure.",
  st:["Simmer the pork in the water with the salt for 60 minutes, skimming.",
      "Cook the onion, garlic, ají, cumin and oregano in a little of the pork fat for 10 minutes.",
      "Add to the pot and cook 40 minutes more.",
      "Add the breadcrumbs to thicken and cook 10 minutes.",
      "Serve with a potato and hominy in each bowl."],
  tp:["Add the breadcrumbs a little at a time until it's as thick as you like.",
      "It's better reheated."],
  v:"fricase paceno recipe"}}
];
