module.exports = [
{id:"guiso-de-arroz", c:"Argentina", r:"latin-america", m:"main", t:60, s:4,
 i:[[3,"tbsp","oil","fat","aceite","oil"],
    [500,"g","beef","protein","carne de res para guiso en dados","beef stewing meat, diced"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","pimiento rojo","red bell pepper","picado","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"","veg","aromatic","zanahoria","carrot","en dados","diced"],
    [2,"","tomato","liquid","tomates","tomatoes","rallados","grated"],
    [1,"tsp","paprika","aromatic","pimentón dulce","sweet paprika"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [300,"g","rice","structure","arroz de grano largo","long-grain rice"],
    [1,"l","water","liquid","agua caliente","hot water"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Guiso de arroz", b:"El guiso de todos los inviernos en Argentina: arroz cocido en el jugo de la carne con pimiento y tomate.",
  st:["Dora la carne en el aceite a fuego fuerte 6 minutos. Sácala.",
      "Sofríe la cebolla, el pimiento, el ajo y la zanahoria 8 minutos.",
      "Vuelve a poner la carne, añade el tomate, el pimentón, el orégano y la sal, y cuece 20 minutos tapado con la mitad del agua.",
      "Añade el arroz y el resto del agua, y cuece 18 minutos a fuego medio, removiendo de vez en cuando.",
      "Apaga y deja reposar 5 minutos: debe quedar caldoso."],
  tp:["Añade el agua siempre caliente para no cortar la cocción del arroz.",
      "Queda mejor un poco caldoso: el arroz sigue absorbiendo al reposar."],
  v:"guiso de arroz argentino"},
 en:{n:"Guiso de Arroz (Argentine Rice Stew)", b:"Argentina's winter staple: rice cooked in the meat's juices with pepper and tomato.",
  st:["Brown the beef in the oil over high heat for 6 minutes. Remove.",
      "Cook the onion, pepper, garlic and carrot for 8 minutes.",
      "Return the beef, add the tomato, paprika, oregano and salt, and simmer covered for 20 minutes with half the water.",
      "Add the rice and the rest of the water, and cook 18 minutes over medium heat, stirring now and then.",
      "Turn off and rest 5 minutes: it should stay soupy."],
  tp:["Always add hot water so the rice keeps cooking evenly.",
      "It's best a little loose: the rice keeps absorbing as it rests."],
  v:"argentine guiso de arroz"}},

{id:"bizcochitos-de-grasa", c:"Argentina", r:"latin-america", m:"bread", t:90, s:40,
 i:[[500,"g","apflour","structure","harina de trigo","plain flour"],
    [10,"g","yeast","leaven","levadura seca","dried yeast"],
    [250,"ml","water","liquid","agua tibia","warm water"],
    [150,"g","lard","fat","grasa de cerdo","lard"],
    [10,"g","salt","salt","sal","salt"]],
 es:{n:"Bizcochitos de grasa", b:"Galletitas saladas hojaldradas que acompañan el mate en toda Argentina.",
  st:["Mezcla la harina, la levadura, la sal, el agua y 50 g de grasa. Amasa 8 minutos y deja reposar 30 minutos.",
      "Estira en un rectángulo, unta con 50 g de grasa, dobla en tres y vuelve a estirar.",
      "Repite con los 50 g restantes de grasa y dobla en tres otra vez.",
      "Estira a 1 cm, corta círculos de 4 cm y pincha cada uno con un tenedor.",
      "Deja levar 20 minutos y hornea a 200 °C 20 minutos, hasta que estén dorados."],
  tp:["Guárdalos en lata: duran crujientes varios días.",
      "Pincharlos evita que se inflen como bollos."],
  v:"bizcochitos de grasa caseros"},
 en:{n:"Bizcochitos de Grasa (Lard Biscuits)", b:"Flaky savoury little biscuits that go with mate all over Argentina.",
  st:["Mix the flour, yeast, salt, water and 50 g of lard. Knead 8 minutes and rest 30 minutes.",
      "Roll into a rectangle, spread with 50 g of lard, fold in three and roll again.",
      "Repeat with the remaining 50 g of lard and fold in three again.",
      "Roll to 1 cm, cut 4 cm rounds and prick each with a fork.",
      "Prove 20 minutes and bake at 200 °C for 20 minutes, until golden."],
  tp:["Keep them in a tin: they stay crisp for days.",
      "Pricking stops them puffing up like rolls."],
  v:"argentine bizcochitos de grasa"}},

{id:"zapallitos-rellenos", c:"Argentina", r:"latin-america", m:"main", t:60, s:4,
 i:[[8,"","veg","structure","zapallitos redondos","round courgettes"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [300,"g","beef","protein","carne picada de res","minced beef"],
    [1,"","egg","binder","huevo","egg"],
    [40,"g","breadcrumbs","binder","pan rallado","breadcrumbs"],
    [60,"g","parmesan","garnish","queso rallado","grated parmesan"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"pinch","pepper","aromatic","pimienta","pepper"]],
 es:{n:"Zapallitos rellenos", b:"Zapallitos redondos rellenos de carne y gratinados con queso. Comida de casa argentina.",
  st:["Hierve los zapallitos enteros 8 minutos. Córtales una tapa y vacíalos con una cuchara.",
      "Pica la pulpa y sofríela con la cebolla en el aceite 5 minutos. Añade la carne y cocina 8 minutos.",
      "Retira del fuego, añade el huevo, la mitad del pan rallado, la sal y la pimienta.",
      "Rellena los zapallitos y cubre con el queso y el resto del pan rallado.",
      "Hornea a 200 °C 20 minutos, hasta que estén gratinados."],
  tp:["Pon los zapallitos boca abajo 5 minutos tras hervirlos para que suelten el agua.",
      "Si no hay zapallitos redondos, usa calabacines largos cortados a lo largo."],
  v:"zapallitos rellenos de carne"},
 en:{n:"Zapallitos Rellenos (Stuffed Round Courgettes)", b:"Round courgettes stuffed with beef and gratinéed with cheese. Argentine home cooking.",
  st:["Boil the courgettes whole for 8 minutes. Cut off a lid and scoop them out.",
      "Chop the flesh and cook it with the onion in the oil for 5 minutes. Add the beef and cook 8 minutes.",
      "Off the heat, add the egg, half the breadcrumbs, the salt and pepper.",
      "Fill the courgettes and top with the cheese and remaining breadcrumbs.",
      "Bake at 200 °C for 20 minutes, until browned."],
  tp:["Stand the courgettes upside down for 5 minutes after boiling so they drain.",
      "No round ones? Use long courgettes halved lengthways."],
  v:"stuffed round zucchini argentina"}},

{id:"pionono", c:"Argentina", r:"latin-america", m:"sweet", t:40, s:8,
 i:[[4,"","egg","structure","huevos","eggs"],
    [100,"g","sugar","sweet","azúcar","sugar"],
    [80,"g","apflour","structure","harina de trigo","plain flour"],
    [1,"tsp","vanilla","aromatic","esencia de vainilla","vanilla extract"],
    [400,"g","dulcedeleche","spread","dulce de leche","dulce de leche"],
    [2,"tbsp","icingsugar","garnish","azúcar glas","icing sugar"]],
 es:{n:"Pionono con dulce de leche", b:"Bizcochuelo finísimo enrollado con dulce de leche. Un clásico de cumpleaños argentino.",
  st:["Bate los huevos con el azúcar 8 minutos, hasta que tripliquen el volumen. Añade la vainilla.",
      "Incorpora la harina tamizada con movimientos envolventes.",
      "Extiende en una bandeja de 30 x 40 cm con papel y hornea a 200 °C 8 minutos.",
      "Vuelca sobre un paño con azúcar glas, retira el papel y enrolla en caliente con el paño. Deja enfriar.",
      "Desenrolla, unta con el dulce de leche y vuelve a enrollar. Espolvorea azúcar glas."],
  tp:["Enrollarlo caliente evita que se agriete después.",
      "No lo hornees de más: debe quedar flexible."],
  v:"pionono dulce de leche"},
 en:{n:"Pionono (Dulce de Leche Roll)", b:"A paper-thin sponge rolled up with dulce de leche. A classic Argentine birthday cake.",
  st:["Whisk the eggs with the sugar for 8 minutes, until tripled in volume. Add the vanilla.",
      "Fold in the sifted flour.",
      "Spread in a 30 x 40 cm lined tray and bake at 200 °C for 8 minutes.",
      "Turn onto a tea towel dusted with icing sugar, peel off the paper and roll up warm in the towel. Cool.",
      "Unroll, spread with the dulce de leche and roll up again. Dust with icing sugar."],
  tp:["Rolling it warm stops it cracking later.",
      "Don't overbake: it needs to stay flexible."],
  v:"pionono argentine sponge roll"}},

{id:"submarino", c:"Argentina", r:"latin-america", m:"drink", t:5, s:1,
 i:[[250,"ml","milk","liquid","leche entera","whole milk"],
    [30,"g","milkchocolate","sweet","chocolate con leche en barrita","milk chocolate bar"],
    [1,"tsp","sugar","sweet","azúcar","sugar"]],
 es:{n:"Submarino", b:"Leche bien caliente con una barrita de chocolate que se hunde y se derrite en el vaso. La merienda de los chicos argentinos.",
  st:["Calienta la leche con el azúcar hasta que humee, sin que hierva.",
      "Sírvela en un vaso alto.",
      "Hunde la barrita de chocolate y remueve hasta que se derrita."],
  tp:["Remueve bien el fondo: el chocolate se asienta.",
      "No dejes hervir la leche o se forma nata."],
  v:"submarino argentino"},
 en:{n:"Submarino (Argentine Hot Chocolate)", b:"Steaming milk with a chocolate bar that sinks and melts in the glass. The Argentine kids' afternoon treat.",
  st:["Heat the milk with the sugar until steaming, without boiling.",
      "Pour into a tall glass.",
      "Sink the chocolate bar and stir until it melts."],
  tp:["Stir the bottom well: the chocolate settles.",
      "Don't let the milk boil or a skin forms."],
  v:"submarino argentine hot chocolate"}},

{id:"bife-a-caballo", c:"Argentina", r:"latin-america", m:"main", t:20, s:2,
 i:[[2,"piece","beef","protein","bifes de lomo alto de 2 cm","sirloin steaks, 2 cm thick"],
    [1,"tsp","salt","salt","sal gruesa","coarse salt"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [2,"","egg","protein","huevos","eggs"],
    [1,"pinch","pepper","aromatic","pimienta","pepper"]],
 es:{n:"Bife a caballo", b:"Un bife jugoso con un huevo frito encima. Plato de bodegón porteño.",
  st:["Saca los bifes de la nevera 20 minutos antes. Sécalos y sálalos.",
      "Calienta una sartén de hierro con 1 cucharada de aceite hasta que humee.",
      "Cocina los bifes 3 minutos por lado para que queden jugosos. Deja reposar 5 minutos.",
      "Fríe los huevos en el aceite restante con la yema líquida.",
      "Pon un huevo sobre cada bife y termina con pimienta."],
  tp:["Sala la carne justo antes de cocinarla para que forme costra.",
      "La yema líquida hace de salsa: no la cocines de más."],
  v:"bife a caballo"},
 en:{n:"Bife a Caballo (Steak with Fried Egg)", b:"A juicy steak topped with a fried egg. A Buenos Aires tavern classic.",
  st:["Take the steaks out of the fridge 20 minutes ahead. Pat dry and salt them.",
      "Heat a cast-iron pan with 1 tablespoon of oil until smoking.",
      "Cook the steaks 3 minutes per side for medium-rare. Rest 5 minutes.",
      "Fry the eggs in the remaining oil, keeping the yolks runny.",
      "Put an egg on each steak and finish with pepper."],
  tp:["Salt the steak just before cooking so it forms a crust.",
      "The runny yolk is the sauce: don't overcook it."],
  v:"bife a caballo steak and egg"}},

{id:"estofado-argentino", c:"Argentina", r:"latin-america", m:"main", t:120, s:6,
 i:[[1,"kg","beef","protein","carne de res para estofar (roast beef o nalga)","beef braising cut"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [2,"","onion","aromatic","cebollas","onions","picadas","chopped"],
    [1,"","bellpepper","aromatic","pimiento rojo","red bell pepper","picado","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"","veg","aromatic","zanahorias","carrots","en rodajas","sliced"],
    [250,"ml","winered","liquid","vino tinto","red wine"],
    [400,"g","tomato","liquid","tomate triturado","crushed tomatoes"],
    [2,"leaf","herb","aromatic","laurel","bay leaves"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [200,"g","mushroom","umami","champiñones","mushrooms","en láminas","sliced"],
    [2,"tsp","salt","salt","sal","salt"],
    [500,"g","pasta","serve","fideos secos para servir","dried pasta to serve"]],
 es:{n:"Estofado argentino", b:"Carne cocida despacio en vino tinto y tomate, servida sobre fideos. El almuerzo de domingo en muchas casas argentinas.",
  st:["Corta la carne en trozos de 5 cm y dórala en el aceite en tandas. Sácala.",
      "Sofríe la cebolla, el pimiento, el ajo y la zanahoria 10 minutos.",
      "Añade el vino y deja reducir 3 minutos.",
      "Vuelve a poner la carne con el tomate, el laurel, el orégano y la sal. Tapa y cuece 90 minutos a fuego bajo.",
      "Añade los champiñones los últimos 15 minutos.",
      "Cuece los fideos y sírvelos con el estofado por encima."],
  tp:["Queda aún mejor al día siguiente.",
      "Si espesa demasiado, añade un poco de agua caliente."],
  v:"estofado argentino con fideos"},
 en:{n:"Estofado (Argentine Beef Stew)", b:"Beef braised slowly in red wine and tomato, served over pasta. Sunday lunch in many Argentine homes.",
  st:["Cut the beef into 5 cm pieces and brown it in the oil in batches. Remove.",
      "Cook the onion, pepper, garlic and carrot for 10 minutes.",
      "Add the wine and reduce for 3 minutes.",
      "Return the beef with the tomato, bay, oregano and salt. Cover and simmer 90 minutes on low.",
      "Add the mushrooms for the last 15 minutes.",
      "Cook the pasta and serve with the stew on top."],
  tp:["It's even better the next day.",
      "If it gets too thick, add a little hot water."],
  v:"argentine estofado with pasta"}},

{id:"faina", c:"Uruguay", ce:"Argentina", r:"latin-america", m:"bread", t:180, s:8,
 i:[[250,"g","legume","structure","harina de garbanzo","chickpea flour"],
    [750,"ml","water","liquid","agua","water"],
    [80,"ml","oliveoil","fat","aceite de oliva","olive oil"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"pinch","pepper","aromatic","pimienta negra","black pepper"]],
 es:{n:"Fainá", b:"Torta finísima de harina de garbanzo, crujiente por fuera. En Uruguay y Argentina se come sobre la pizza.",
  st:["Bate la harina de garbanzo con el agua y la sal hasta que no queden grumos. Deja reposar 2 horas.",
      "Retira la espuma de la superficie y añade 3 cucharadas de aceite.",
      "Calienta una bandeja de 30 cm con el resto del aceite en el horno a 250 °C 5 minutos.",
      "Vierte la mezcla y hornea 20 minutos, hasta que esté dorada y con bordes crujientes.",
      "Termina con pimienta y corta en porciones."],
  tp:["La capa debe tener menos de 1 cm para que quede crujiente.",
      "El reposo evita que quede arenosa."],
  v:"fainá de garbanzo"},
 en:{n:"Fainá (Chickpea Flatbread)", b:"A very thin chickpea-flour flatbread, crisp at the edges. In Uruguay and Argentina it's eaten on top of pizza.",
  st:["Whisk the chickpea flour with the water and salt until smooth. Rest 2 hours.",
      "Skim the foam off the top and add 3 tablespoons of oil.",
      "Heat a 30 cm tray with the rest of the oil in the oven at 250 °C for 5 minutes.",
      "Pour in the batter and bake 20 minutes, until golden with crisp edges.",
      "Finish with pepper and cut into pieces."],
  tp:["Keep it under 1 cm deep so it crisps.",
      "Resting the batter stops it tasting gritty."],
  v:"faina chickpea flatbread uruguay"}},

{id:"mazamorra-argentina", c:"Argentina", r:"latin-america", m:"sweet", t:180, s:6,
 i:[[250,"g","hominy","structure","maíz blanco partido (maíz pisado)","dried cracked white hominy"],
    [2,"l","water","liquid","agua","water"],
    [500,"ml","milk","liquid","leche","milk"],
    [150,"g","sugar","sweet","azúcar","sugar"],
    [1,"tsp","vanilla","aromatic","esencia de vainilla","vanilla extract"],
    [1,"piece","spice","aromatic","rama de canela","cinnamon stick"]],
 es:{n:"Mazamorra argentina", b:"Maíz blanco cocido despacio con leche y azúcar. Postre criollo que se toma caliente o frío.",
  st:["Remoja el maíz 12 horas en agua fría y escúrrelo.",
      "Cuécelo en el agua con la canela 2 horas a fuego bajo, hasta que esté tierno.",
      "Añade la leche y el azúcar, y cuece 20 minutos más removiendo.",
      "Retira la canela, añade la vainilla y sirve caliente o frío."],
  tp:["Si se espesa al enfriar, añade un poco de leche.",
      "Remueve a menudo al final para que no se pegue."],
  v:"mazamorra criolla argentina"},
 en:{n:"Mazamorra (Argentine Hominy Pudding)", b:"White hominy simmered slowly with milk and sugar. A creole dessert eaten warm or cold.",
  st:["Soak the hominy for 12 hours in cold water and drain.",
      "Simmer it in the water with the cinnamon for 2 hours on low, until tender.",
      "Add the milk and sugar and cook 20 minutes more, stirring.",
      "Remove the cinnamon, add the vanilla and serve warm or cold."],
  tp:["If it thickens as it cools, add a little milk.",
      "Stir often at the end so it doesn't catch."],
  v:"argentine mazamorra hominy dessert"}},

{id:"tarta-de-choclo", c:"Argentina", r:"latin-america", m:"main", t:70, s:6,
 i:[[250,"g","apflour","structure","harina de trigo","plain flour"],
    [100,"g","butter","fat","mantequilla fría","cold butter"],
    [80,"ml","water","liquid","agua fría","cold water"],
    [1,"tsp","salt","salt","sal","salt"],
    [30,"g","butter","fat","mantequilla (para el relleno)","butter (for the filling)"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [30,"g","apflour","thicken","harina de trigo (para el relleno)","plain flour (for the filling)"],
    [300,"ml","milk","liquid","leche","milk"],
    [400,"g","corn","structure","granos de choclo","sweetcorn kernels"],
    [2,"","egg","binder","huevos","eggs"],
    [150,"g","mozzarella","enrich","mozzarella en cubos","mozzarella, cubed"],
    [1,"pinch","spice","aromatic","nuez moscada","nutmeg"]],
 es:{n:"Tarta de choclo", b:"Tarta de masa casera con relleno cremoso de choclo y queso. Infaltable en las rotiserías argentinas.",
  st:["Frota la harina, la sal y la mantequilla fría hasta que parezca arena. Añade el agua, une la masa y refrigera 20 minutos.",
      "Sofríe la cebolla en la mantequilla del relleno 5 minutos. Añade la harina, cuece 1 minuto y agrega la leche batiendo hasta espesar.",
      "Añade el choclo y la nuez moscada. Deja entibiar y agrega los huevos y la mozzarella.",
      "Forra un molde de 24 cm con la masa, rellena y hornea a 190 °C 35 minutos, hasta que esté dorada."],
  tp:["Tritura la mitad del choclo para un relleno más cremoso.",
      "Déjala reposar 10 minutos antes de cortar."],
  v:"tarta de choclo argentina"},
 en:{n:"Tarta de Choclo (Sweetcorn Pie)", b:"A homemade pastry case with a creamy corn and cheese filling. A fixture of Argentine deli counters.",
  st:["Rub the flour, salt and cold butter together until sandy. Add the water, bring the dough together and chill 20 minutes.",
      "Cook the onion in the filling butter for 5 minutes. Add the flour, cook 1 minute and whisk in the milk until thick.",
      "Add the corn and nutmeg. Let it cool slightly, then add the eggs and mozzarella.",
      "Line a 24 cm tin with the pastry, fill and bake at 190 °C for 35 minutes, until golden."],
  tp:["Blend half the corn for a creamier filling.",
      "Rest 10 minutes before slicing."],
  v:"argentine sweetcorn pie"}}
];
