module.exports = [
{id:"dulce-de-leche-casero", c:"Argentina", r:"latin-america", m:"sauce", t:180, s:12,
 i:[[2,"l","milk","liquid","leche entera","whole milk"],
    [500,"g","sugar","sweet","azúcar","sugar"],
    [0.5,"tsp","bakingsoda","set","bicarbonato de sodio","baking soda"],
    [1,"","vanillabean","aromatic","vaina de vainilla","vanilla pod","abierta","split"]],
 es:{n:"Dulce de leche casero", b:"Leche y azúcar reducidas despacio hasta volverse una crema color caramelo. El sabor nacional de Argentina.",
  st:["Pon la leche, el azúcar y la vainilla en una olla grande y ancha. Calienta moviendo hasta que el azúcar se disuelva.",
      "Cuando hierva, añade el bicarbonato. Hará espuma: baja el fuego.",
      "Cuece a fuego bajo 2 horas y media, moviendo cada 10 minutos al principio y seguido al final.",
      "Está listo cuando una gota en un plato frío no se corre y la cuchara deja un surco en el fondo.",
      "Saca la vainilla y pasa a frascos limpios. Espesa al enfriar."],
  tp:["El bicarbonato ayuda al color y evita que se corte.",
      "Si queda grumoso, pásalo por la licuadora tibio."],
  v:"dulce de leche casero receta"},
 en:{n:"Homemade Dulce de Leche", b:"Milk and sugar reduced slowly into a caramel-coloured cream. Argentina's national flavour.",
  st:["Put the milk, sugar and vanilla in a large, wide pot. Heat, stirring, until the sugar dissolves.",
      "When it boils, add the baking soda. It will foam: lower the heat.",
      "Cook on low for 2 and a half hours, stirring every 10 minutes at first and constantly at the end.",
      "It's ready when a drop on a cold plate doesn't run and the spoon leaves a trail on the bottom.",
      "Remove the vanilla and pour into clean jars. It thickens as it cools."],
  tp:["The baking soda helps the colour and stops it curdling.",
      "If it turns grainy, blend it while warm."],
  v:"homemade dulce de leche recipe"}},

{id:"chocotorta", c:"Argentina", r:"latin-america", m:"sweet", t:30, s:10,
 i:[[500,"g","chocolatecookies","structure","galletas de chocolate","chocolate biscuits"],
    [400,"g","dulcedeleche","spread","dulce de leche repostero","thick dulce de leche"],
    [400,"g","creamcheese","spread","queso crema","cream cheese"],
    [300,"ml","coffee","liquid","café","coffee","frío","cold"],
    [1,"tbsp","cocoa","garnish","cacao en polvo","cocoa powder","opcional","optional"]],
 es:{n:"Chocotorta", b:"La torta sin horno de los cumpleaños argentinos: galletas de chocolate mojadas en café con crema de dulce de leche y queso.",
  st:["Bate el dulce de leche con el queso crema hasta que quede liso.",
      "Moja cada galleta 2 segundos en el café y ponla en una fuente, formando una capa.",
      "Cubre con una capa de crema. Repite hasta tener 4 capas de galletas, terminando con crema.",
      "Espolvorea cacao y refrigera al menos 4 horas, mejor toda la noche."],
  tp:["Solo 2 segundos en el café: más y se deshacen.",
      "Para niños, moja las galletas en leche con chocolate en vez de café."],
  v:"chocotorta receta"},
 en:{n:"Chocotorta", b:"The no-bake cake of Argentine birthdays: chocolate biscuits dipped in coffee, layered with dulce de leche and cream cheese.",
  st:["Beat the dulce de leche with the cream cheese until smooth.",
      "Dip each biscuit in the coffee for 2 seconds and lay it in a dish to form a layer.",
      "Cover with a layer of cream. Repeat until you have 4 layers of biscuits, ending with cream.",
      "Dust with cocoa and chill at least 4 hours, better overnight."],
  tp:["Just 2 seconds in the coffee: longer and they fall apart.",
      "For kids, dip the biscuits in chocolate milk instead of coffee."],
  v:"chocotorta recipe"}},

{id:"pastafrola", c:"Argentina", r:"latin-america", m:"sweet", t:75, s:10, o:180,
 i:[[300,"g","apflour","structure","harina de trigo","all-purpose flour"],
    [150,"g","butter","fat","mantequilla","butter","fría","cold"],
    [120,"g","sugar","sweet","azúcar","sugar"],
    [1,"","egg","binder","huevo","egg"],
    [1,"","eggyolk","binder","yema de huevo","egg yolk"],
    [1,"tsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [1,"","citrus","aromatic","ralladura de limón","lemon zest"],
    [500,"g","quincepaste","spread","dulce de membrillo","quince paste"],
    [60,"ml","water","liquid","agua caliente","hot water"]],
 es:{n:"Pastafrola", b:"Tarta de masa dulce rellena de dulce de membrillo con enrejado encima. La merienda con mate de toda Argentina.",
  st:["Bate la mantequilla con el azúcar. Añade el huevo, la yema y la ralladura.",
      "Añade la harina y el polvo de hornear y une sin amasar de más. Envuelve y refrigera 30 minutos.",
      "Deshaz el membrillo con el agua caliente con un tenedor hasta que se pueda untar.",
      "Calienta el horno a 180 °C. Estira dos tercios de la masa y forra un molde de 24 centímetros.",
      "Rellena con el membrillo. Con el resto de la masa haz tiras y forma un enrejado encima.",
      "Hornea 35 minutos, hasta que la masa esté dorada. Enfría antes de cortar."],
  tp:["El dulce de batata es la otra versión clásica.",
      "La masa se rompe fácil: estírala entre 2 hojas de papel."],
  v:"pastafrola receta"},
 en:{n:"Pastafrola (Quince Lattice Tart)", b:"A sweet pastry tart filled with quince paste under a lattice. Argentina's afternoon snack with mate.",
  st:["Beat the butter with the sugar. Add the egg, yolk and zest.",
      "Add the flour and baking powder and bring together without overworking. Wrap and chill 30 minutes.",
      "Mash the quince paste with the hot water using a fork until spreadable.",
      "Heat the oven to 180 °C. Roll out two thirds of the dough and line a 24 centimetre tin.",
      "Fill with the quince. Cut the rest of the dough into strips and form a lattice on top.",
      "Bake 35 minutes, until golden. Cool before cutting."],
  tp:["Sweet potato paste is the other classic version.",
      "The dough breaks easily: roll it between 2 sheets of paper."],
  v:"pastafrola recipe"}},

{id:"medialunas", c:"Argentina", r:"latin-america", m:"bread", t:300, s:16, o:200,
 i:[[500,"g","breadflour","structure","harina de trigo de fuerza","bread flour"],
    [10,"g","yeast","leaven","levadura seca","instant yeast"],
    [80,"g","sugar","sweet","azúcar","sugar"],
    [1,"tsp","salt","salt","sal","salt"],
    [2,"","egg","binder","huevos","eggs"],
    [200,"ml","milk","liquid","leche tibia","warm milk"],
    [250,"g","butter","fat","mantequilla","butter","fría, para laminar","cold, for laminating"],
    [100,"g","sugar","glaze","azúcar","sugar","para el almíbar","for the syrup"],
    [100,"ml","water","glaze","agua","water","para el almíbar","for the syrup"]],
 es:{n:"Medialunas de manteca", b:"Las medialunas de confitería: masa hojaldrada con levadura, dulce, brillante de almíbar. Con café con leche.",
  st:["Mezcla la harina, la levadura, el azúcar, la sal, 1 huevo y la leche. Amasa 8 minutos. Refrigera tapada 60 minutos.",
      "Aplana la mantequilla fría entre papel en un cuadrado de 15 centímetros.",
      "Estira la masa en un rectángulo, pon la mantequilla en el centro y cierra. Estira a lo largo y dobla en tres. Refrigera 30 minutos. Repite 2 veces más.",
      "Estira a medio centímetro, corta triángulos de 10 centímetros de base y enrolla desde la base, curvando las puntas.",
      "Deja crecer 90 minutos en un lugar tibio, hasta que casi doblen. Calienta el horno a 200 °C.",
      "Pinta con el huevo batido y hornea 15 minutos, hasta que estén doradas.",
      "Hierve el azúcar con el agua 3 minutos y pinta las medialunas calientes con el almíbar."],
  tp:["Si la mantequilla se asoma o se derrite, refrigera 15 minutos más antes de seguir.",
      "Crecen mejor en el horno apagado con un recipiente de agua caliente."],
  v:"medialunas de manteca receta"},
 en:{n:"Medialunas (Argentine Croissants)", b:"Café-style medialunas: sweet, flaky yeast dough, glossy with syrup. With milky coffee.",
  st:["Mix the flour, yeast, sugar, salt, 1 egg and the milk. Knead 8 minutes. Chill covered 60 minutes.",
      "Flatten the cold butter between paper into a 15 centimetre square.",
      "Roll the dough into a rectangle, put the butter in the centre and enclose it. Roll out lengthwise and fold in three. Chill 30 minutes. Repeat 2 more times.",
      "Roll to half a centimetre, cut triangles with a 10 centimetre base and roll up from the base, curving the tips.",
      "Let rise 90 minutes somewhere warm, until nearly doubled. Heat the oven to 200 °C.",
      "Brush with the beaten egg and bake 15 minutes, until golden.",
      "Boil the sugar with the water for 3 minutes and brush the hot medialunas with the syrup."],
  tp:["If the butter breaks through or melts, chill 15 minutes more before carrying on.",
      "They rise best in the switched-off oven with a dish of hot water."],
  v:"medialunas recipe"}},

{id:"fugazzeta", c:"Argentina", r:"latin-america", m:"main", t:180, s:6, o:250,
 i:[[500,"g","breadflour","structure","harina de trigo de fuerza","bread flour"],
    [7,"g","yeast","leaven","levadura seca","instant yeast"],
    [320,"ml","water","liquid","agua tibia","warm water"],
    [1.5,"tsp","salt","salt","sal","salt"],
    [4,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [500,"g","mozzarella","protein","mozzarella","mozzarella","en cubos","cubed"],
    [3,"","onion","aromatic","cebollas blancas","white onions","en pluma fina","thinly sliced"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"]],
 es:{n:"Fugazzeta rellena", b:"La pizza porteña de dos capas de masa rellena de mozzarella y cubierta de cebolla. Herencia genovesa en Buenos Aires.",
  st:["Mezcla la harina, la levadura, el agua, la sal y 2 cucharadas de aceite. Amasa 10 minutos. Deja crecer 90 minutos.",
      "Mezcla la cebolla con 1 cucharadita de sal, deja 20 minutos y escúrrela apretando.",
      "Divide la masa en 2. Estira una y forra un molde aceitado de 30 centímetros. Cubre con la mozzarella dejando 2 centímetros de borde.",
      "Estira la otra mitad, tapa y sella los bordes. Deja crecer 30 minutos. Calienta el horno a 250 °C.",
      "Cubre con la cebolla, el orégano y el resto del aceite. Hornea 20 minutos, hasta que la base suene hueca y la cebolla dore."],
  tp:["Salar y escurrir la cebolla evita que moje la masa.",
      "Se come con fainá encima en las pizzerías de Buenos Aires."],
  v:"fugazzeta rellena receta"},
 en:{n:"Fugazzeta (Stuffed Onion Pizza)", b:"Buenos Aires's double-crust pizza stuffed with mozzarella and topped with onion. A Genoese legacy in the city.",
  st:["Mix the flour, yeast, water, salt and 2 tablespoons of oil. Knead 10 minutes. Let rise 90 minutes.",
      "Toss the onion with 1 teaspoon of salt, leave 20 minutes and squeeze dry.",
      "Divide the dough in 2. Roll out one piece and line an oiled 30 centimetre pan. Cover with the mozzarella, leaving a 2 centimetre border.",
      "Roll out the other half, cover and seal the edges. Let rise 30 minutes. Heat the oven to 250 °C.",
      "Top with the onion, oregano and the rest of the oil. Bake 20 minutes, until the base sounds hollow and the onion browns."],
  tp:["Salting and squeezing the onion keeps it from soaking the dough.",
      "In Buenos Aires pizzerias it's eaten with fainá on top."],
  v:"fugazzeta recipe"}},

{id:"carbonada", c:"Argentina", r:"latin-america", m:"main", t:120, s:6,
 i:[[800,"g","beef","protein","carne de res para guisar","stewing beef","en cubos","cubed"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","morrón rojo","red bell pepper","picado","chopped"],
    [2,"","tomato","aromatic","tomates","tomatoes","picados","chopped"],
    [1,"l","stock","liquid","caldo de carne","beef stock"],
    [400,"g","veg","structure","zapallo","winter squash","en cubos","cubed"],
    [300,"g","veg","structure","batata","sweet potato","en cubos","cubed"],
    [300,"g","potato","structure","papa","potato","en cubos","cubed"],
    [2,"","corn","protein","choclos","ears of corn","en rodajas","in rounds"],
    [2,"","fruit","sweet","duraznos","peaches","en cubos","diced"],
    [80,"g","driedfruit","sweet","orejones de durazno","dried peaches or apricots"],
    [1.5,"tsp","salt","salt","sal","salt"]],
 es:{n:"Carbonada criolla", b:"Guiso de carne con zapallo, batata, choclo y durazno. Dulce y salado, y en las fiestas se sirve dentro de un zapallo.",
  st:["Dora la carne en el aceite en tandas. Sácala.",
      "Sofríe la cebolla y el morrón 8 minutos. Añade el tomate y cuece 5 minutos.",
      "Regresa la carne con el caldo y la sal. Tapa y cuece 60 minutos a fuego bajo.",
      "Añade la papa, la batata, el zapallo y el choclo y cuece 20 minutos.",
      "Añade los duraznos y los orejones y cuece 10 minutos más. Sirve caliente."],
  tp:["Para servir en zapallo, hornea un zapallo entero ahuecado 40 minutos y llénalo con la carbonada.",
      "El durazno va al final para que no se deshaga."],
  v:"carbonada criolla receta"},
 en:{n:"Carbonada Criolla (Beef and Peach Stew)", b:"A beef stew with squash, sweet potato, corn and peach. Sweet and savoury, and at festivals it's served inside a pumpkin.",
  st:["Brown the beef in the oil in batches. Remove.",
      "Cook the onion and bell pepper for 8 minutes. Add the tomato and cook 5 minutes.",
      "Return the beef with the stock and salt. Cover and simmer 60 minutes on low.",
      "Add the potato, sweet potato, squash and corn and cook 20 minutes.",
      "Add the peaches and dried fruit and cook 10 minutes more. Serve hot."],
  tp:["To serve in a pumpkin, bake a whole hollowed pumpkin for 40 minutes and fill it with the stew.",
      "The peach goes in last so it doesn't fall apart."],
  v:"carbonada criolla recipe"}},

{id:"pastel-de-papa", c:"Argentina", r:"latin-america", m:"main", t:75, s:6, o:200,
 i:[[1.2,"kg","potato","structure","papas","potatoes","peladas","peeled"],
    [50,"g","butter","fat","mantequilla","butter"],
    [150,"ml","milk","liquid","leche","milk"],
    [0.25,"tsp","spice","aromatic","nuez moscada","nutmeg"],
    [2,"tsp","salt","salt","sal","salt"],
    [600,"g","beef","protein","carne molida de res","ground beef"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","morrón rojo","red bell pepper","picado","chopped"],
    [1,"tsp","paprika","aromatic","pimentón dulce","sweet paprika"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [2,"","egg","protein","huevos duros","hard-boiled eggs","picados","chopped"],
    [12,"","olives","garnish","aceitunas verdes","green olives","picadas","chopped"],
    [1,"","eggyolk","glaze","yema de huevo","egg yolk"]],
 es:{n:"Pastel de papa", b:"Carne picada con huevo y aceitunas bajo una capa de puré gratinado. La comida casera argentina por excelencia.",
  st:["Hierve las papas en agua con sal 20 minutos. Haz puré con la mantequilla, la leche, la nuez moscada y 1 cucharadita de sal.",
      "Sofríe la cebolla y el morrón en el aceite 8 minutos. Añade la carne, el pimentón, el comino y el resto de la sal y cuece 10 minutos.",
      "Apaga y mezcla con el huevo y las aceitunas.",
      "Calienta el horno a 200 °C. Pon la carne en una fuente y cubre con el puré. Marca rayas con un tenedor.",
      "Pinta con la yema y hornea 25 minutos, hasta que esté dorado."],
  tp:["Se puede armar el día antes y hornear al momento.",
      "Las rayas del tenedor se doran y hacen la costra."],
  v:"pastel de papa argentino receta"},
 en:{n:"Pastel de Papa (Argentine Cottage Pie)", b:"Minced beef with egg and olives under a layer of browned mash. Argentine home cooking at its most typical.",
  st:["Boil the potatoes in salted water for 20 minutes. Mash with the butter, milk, nutmeg and 1 teaspoon of salt.",
      "Cook the onion and bell pepper in the oil for 8 minutes. Add the beef, paprika, cumin and the rest of the salt and cook 10 minutes.",
      "Turn off and mix in the egg and olives.",
      "Heat the oven to 200 °C. Put the beef in a dish and cover with the mash. Score lines with a fork.",
      "Brush with the yolk and bake 25 minutes, until golden."],
  tp:["It can be assembled the day before and baked when needed.",
      "The fork lines brown and make the crust."],
  v:"argentine pastel de papa recipe"}},

{id:"flan-casero", c:"Argentina", r:"latin-america", m:"sweet", t:90, s:8, o:170,
 i:[[200,"g","sugar","caramel","azúcar","sugar","para el caramelo","for the caramel"],
    [1,"l","milk","liquid","leche","milk"],
    [150,"g","sugar","sweet","azúcar","sugar","para el flan","for the custard"],
    [6,"","egg","set","huevos","eggs"],
    [1,"tsp","vanilla","aromatic","extracto de vainilla","vanilla extract"],
    [250,"g","dulcedeleche","garnish","dulce de leche","dulce de leche","para servir","to serve"]],
 es:{n:"Flan casero con dulce de leche", b:"El flan de huevo de la abuela, con caramelo oscuro, servido con una cucharada grande de dulce de leche. Mixto, si lleva crema también.",
  st:["Derrite el azúcar del caramelo en el molde a fuego medio hasta que esté ámbar. Cubre el fondo y deja enfriar.",
      "Calienta la leche con la vainilla hasta que humee.",
      "Bate los huevos con el azúcar sin hacer espuma. Añade la leche caliente poco a poco, batiendo. Cuela sobre el caramelo.",
      "Calienta el horno a 170 °C. Pon el molde en una bandeja con agua caliente y hornea 60 minutos, hasta que el centro apenas tiemble.",
      "Enfría y refrigera 4 horas. Desmolda y sirve con dulce de leche."],
  tp:["Si el agua del baño hierve, el flan sale con agujeros: añade agua fría si hace falta.",
      "El caramelo se derrite solo en la heladera y queda como salsa."],
  v:"flan casero con dulce de leche"},
 en:{n:"Flan with Dulce de Leche", b:"Grandma's egg flan with dark caramel, served with a big spoonful of dulce de leche. Called mixto if cream comes too.",
  st:["Melt the caramel sugar in the mould over medium heat until amber. Coat the bottom and let it cool.",
      "Heat the milk with the vanilla until steaming.",
      "Whisk the eggs with the sugar without making foam. Add the hot milk slowly, whisking. Strain over the caramel.",
      "Heat the oven to 170 °C. Set the mould in a tray of hot water and bake 60 minutes, until the centre barely wobbles.",
      "Cool and chill 4 hours. Turn out and serve with dulce de leche."],
  tp:["If the water bath boils, the flan comes out full of holes: add cold water if needed.",
      "The caramel melts in the fridge and becomes a sauce."],
  v:"flan with dulce de leche recipe"}},

{id:"tarta-de-acelga", c:"Argentina", r:"latin-america", m:"main", t:75, s:6, o:190,
 i:[[300,"g","apflour","structure","harina de trigo","all-purpose flour"],
    [80,"ml","oil","fat","aceite","oil","para la masa","for the dough"],
    [120,"ml","water","liquid","agua tibia","warm water"],
    [1.5,"tsp","salt","salt","sal","salt"],
    [1,"kg","veg","structure","acelga","Swiss chard","sin tallos gruesos","thick stems removed"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"tbsp","oil","fat","aceite","oil","para el relleno","for the filling"],
    [4,"","egg","binder","huevos","eggs"],
    [100,"g","parmesan","umami","queso rallado","grated hard cheese"],
    [0.25,"tsp","spice","aromatic","nuez moscada","nutmeg"]],
 es:{n:"Tarta de acelga", b:"Tarta salada de acelga, cebolla, huevo y queso rallado en una masa de aceite. La cena liviana de las casas argentinas.",
  st:["Mezcla la harina, el aceite de la masa, el agua y 1 cucharadita de sal. Amasa 3 minutos y reposa 20 minutos.",
      "Hierve la acelga 3 minutos, escúrrela, apriétala bien y pícala.",
      "Sofríe la cebolla en el aceite 8 minutos. Mezcla con la acelga, los huevos batidos, el queso, la nuez moscada y el resto de la sal.",
      "Calienta el horno a 190 °C. Estira dos tercios de la masa y forra un molde de 26 centímetros. Rellena y cubre con el resto de la masa. Pincha la tapa.",
      "Hornea 40 minutos, hasta que esté dorada."],
  tp:["Aprieta bien la acelga o la tarta sale aguada.",
      "Se come tibia o fría; aguanta 2 días en la heladera."],
  v:"tarta de acelga receta"},
 en:{n:"Swiss Chard Pie (Tarta de Acelga)", b:"A savoury pie of chard, onion, egg and grated cheese in an olive-oil pastry. The light supper of Argentine homes.",
  st:["Mix the flour, the dough oil, water and 1 teaspoon of salt. Knead 3 minutes and rest 20 minutes.",
      "Boil the chard 3 minutes, drain, squeeze hard and chop.",
      "Cook the onion in the oil for 8 minutes. Mix with the chard, beaten eggs, cheese, nutmeg and the rest of the salt.",
      "Heat the oven to 190 °C. Roll out two thirds of the dough and line a 26 centimetre tin. Fill and cover with the rest of the dough. Prick the top.",
      "Bake 40 minutes, until golden."],
  tp:["Squeeze the chard hard or the pie comes out watery.",
      "Eat warm or cold; keeps 2 days in the fridge."],
  v:"swiss chard pie recipe"}},

{id:"revuelto-gramajo", c:"Argentina", r:"latin-america", m:"main", t:30, s:2,
 i:[[400,"g","potato","structure","papas","potatoes","en bastones muy finos","in very thin matchsticks"],
    [500,"ml","oil","fat","aceite","oil","para freír","for frying"],
    [20,"g","butter","fat","mantequilla","butter"],
    [0.5,"","onion","aromatic","cebolla","onion","en pluma","sliced"],
    [150,"g","ham","protein","jamón cocido","cooked ham","en tiras","in strips"],
    [4,"","egg","protein","huevos","eggs"],
    [100,"g","legume","protein","arvejas","peas","cocidas","cooked"],
    [0.5,"tsp","salt","salt","sal","salt"]],
 es:{n:"Revuelto gramajo", b:"Papas pay fritas, jamón, cebolla y arvejas revueltos con huevo. Invento de bodegón porteño, rápido y contundente.",
  st:["Fríe las papas en el aceite a 170 °C 5 minutos, hasta que estén doradas y crujientes. Escurre y sala.",
      "Derrite la mantequilla en un sartén y sofríe la cebolla 5 minutos. Añade el jamón y las arvejas 2 minutos.",
      "Bate los huevos, viértelos y mueve a fuego bajo 1 minuto.",
      "Añade las papas y mezcla hasta que el huevo cuaje suave. Sirve enseguida."],
  tp:["Las papas se añaden al final para que no pierdan el crujiente.",
      "El huevo debe quedar cremoso, no seco."],
  v:"revuelto gramajo receta"},
 en:{n:"Revuelto Gramajo (Potato, Ham and Egg Scramble)", b:"Crisp shoestring potatoes, ham, onion and peas scrambled with egg. A Buenos Aires bistro invention, quick and hearty.",
  st:["Fry the potatoes in the oil at 170 °C for 5 minutes, until golden and crisp. Drain and salt.",
      "Melt the butter in a pan and cook the onion 5 minutes. Add the ham and peas for 2 minutes.",
      "Beat the eggs, pour them in and stir on low for 1 minute.",
      "Add the potatoes and toss until the egg is softly set. Serve right away."],
  tp:["The potatoes go in last so they stay crisp.",
      "The egg should be creamy, not dry."],
  v:"revuelto gramajo recipe"}}
];
