module.exports = [
{id:"sorrentinos", c:"Argentina", r:"latin-america", m:"main", t:120, s:4,
 i:[[400,"g","apflour","structure","harina de trigo","plain flour"],
    [4,"","egg","structure","huevos","eggs"],
    [1,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [150,"g","ham","protein","jamón cocido","cooked ham","picado fino","finely chopped"],
    [250,"g","mozzarella","protein","mozzarella","mozzarella","rallada","grated"],
    [200,"g","ricottacheese","protein","ricota","ricotta"],
    [40,"g","parmesan","enrich","queso parmesano rallado","grated parmesan"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [800,"g","tomato","sauce","tomate triturado","crushed tomatoes"],
    [2,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [1,"handful","herb","garnish","albahaca","basil"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Sorrentinos de jamón y queso", b:"Pasta rellena redonda y generosa con jamón, mozzarella y ricota, en salsa fileto. Invento de Mar del Plata.",
  st:["Forma una corona con la harina, pon en el centro 3 huevos, el aceite y media cucharadita de sal y amasa 10 minutos. Tapa y deja reposar 30 minutos.",
      "Mezcla el jamón, la mozzarella, la ricota, el parmesano y el huevo restante.",
      "Estira la masa muy fina, pon bolitas de relleno cada 8 cm, cubre con otra lámina, presiona alrededor y corta con un aro de 7 cm.",
      "Para la salsa, rehoga la cebolla y el ajo en el aceite 6 minutos, añade el tomate y media cucharadita de sal y cuece 20 minutos. Termina con la albahaca.",
      "Hierve los sorrentinos en agua con el resto de la sal 5 minutos y sírvelos con la salsa."],
  tp:["Se congelan crudos en una bandeja y luego en bolsa; se hierven sin descongelar, 7 minutos.",
      "Sella bien los bordes para que el relleno no se escape."],
  v:"sorrentinos caseros"},
 en:{n:"Sorrentinos (Argentine Ham and Cheese Ravioli)", b:"Large round filled pasta with ham, mozzarella and ricotta in a simple tomato sauce. Invented in Mar del Plata.",
  st:["Make a well in the flour, add 3 eggs, the oil and half a teaspoon of salt and knead 10 minutes. Cover and rest 30 minutes.",
      "Mix the ham, mozzarella, ricotta, parmesan and the remaining egg.",
      "Roll the dough very thin, place balls of filling 8 cm apart, cover with a second sheet, press around them and cut with a 7 cm ring.",
      "For the sauce, soften the onion and garlic in the oil for 6 minutes, add the tomato and half a teaspoon of salt and simmer 20 minutes. Finish with the basil.",
      "Boil the sorrentinos in water with the rest of the salt for 5 minutes and serve with the sauce."],
  tp:["Freeze them raw on a tray, then bag them; boil from frozen for 7 minutes.",
      "Seal the edges well so the filling doesn't leak."],
  v:"homemade sorrentinos"}},

{id:"bizcochuelo", c:"Argentina", r:"latin-america", m:"sweet", t:60, s:10,
 i:[[6,"","egg","structure","huevos","eggs","a temperatura ambiente","at room temperature"],
    [200,"g","sugar","sweet","azúcar","sugar"],
    [200,"g","apflour","structure","harina de trigo","plain flour","tamizada","sifted"],
    [1,"","citrus","aromatic","ralladura de limón","lemon zest"],
    [1,"pinch","salt","salt","sal","salt"],
    [10,"g","butter","fat","mantequilla","butter","para el molde","for the tin"]],
 es:{n:"Bizcochuelo", b:"Bizcocho esponjoso solo con huevos, azúcar y harina. La base de las tortas de cumpleaños argentinas.",
  st:["Unta con mantequilla y enharina un molde de 24 cm y calienta el horno a 180 °C.",
      "Bate los huevos con el azúcar y la sal a velocidad alta 10 minutos, hasta que la mezcla triplique su volumen y forme cintas.",
      "Añade la ralladura e incorpora la harina en tres veces con movimientos envolventes, sin batir.",
      "Vierte en el molde y hornea 35 minutos sin abrir el horno. Está listo cuando un palillo sale seco.",
      "Desmolda y deja enfriar sobre una rejilla."],
  tp:["El secreto es el batido largo: sin él no sube.",
      "Se corta en tres capas para rellenar."],
  v:"bizcochuelo argentino"},
 en:{n:"Bizcochuelo (Argentine Sponge Cake)", b:"A light sponge made with just eggs, sugar and flour. The base of every Argentine birthday cake.",
  st:["Butter and flour a 24 cm tin and heat the oven to 180 °C.",
      "Whisk the eggs with the sugar and salt on high speed for 10 minutes, until tripled in volume and ribbony.",
      "Add the zest and fold in the flour in three additions, without beating.",
      "Pour into the tin and bake 35 minutes without opening the oven. It's done when a skewer comes out dry.",
      "Unmould and cool on a rack."],
  tp:["The long whisking is the secret: without it the cake won't rise.",
      "Slice it into three layers to fill."],
  v:"argentine sponge cake"}},

{id:"matambre-a-la-pizza", c:"Argentina", r:"latin-america", m:"main", t:120, s:4,
 i:[[1.2,"kg","beef","protein","matambre de res","beef flank matambre","sin exceso de grasa","trimmed"],
    [1,"l","milk","liquid","leche","milk"],
    [300,"ml","tomato","sauce","tomate triturado","crushed tomatoes"],
    [1,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [300,"g","mozzarella","enrich","mozzarella","mozzarella","en fetas","sliced"],
    [1,"","bellpepper","garnish","pimiento morrón rojo asado","roasted red pepper","en tiras","in strips"],
    [12,"","olives","garnish","aceitunas verdes","green olives"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Matambre a la pizza", b:"Matambre tiernizado en leche y gratinado con salsa, mozzarella y orégano. Clásico de parrilla y de horno.",
  st:["Cuece el matambre cubierto con la leche y 1 cucharadita de sal a fuego bajo 60 minutos, hasta que esté tierno.",
      "Escúrrelo y dóralo en la parrilla o en el horno a 220 °C 10 minutos por lado.",
      "Mezcla el tomate con el ajo y el resto de la sal y úntalo sobre la carne.",
      "Cubre con la mozzarella, el morrón y las aceitunas y gratina 8 minutos. Espolvorea el orégano y sirve."],
  tp:["Pide el matambre de novillo, que es más tierno.",
      "La leche de la cocción se desecha."],
  v:"matambre a la pizza"},
 en:{n:"Matambre a la Pizza (Pizza-Topped Flank)", b:"Flank tenderised in milk and grilled with tomato, mozzarella and oregano. A steakhouse and home-oven classic.",
  st:["Simmer the matambre covered in the milk with 1 teaspoon of salt on low heat for 60 minutes, until tender.",
      "Drain and brown it on the grill or in the oven at 220 °C, 10 minutes a side.",
      "Mix the tomato with the garlic and the rest of the salt and spread it over the meat.",
      "Top with the mozzarella, pepper and olives and grill 8 minutes. Sprinkle with oregano and serve."],
  tp:["Ask for steer matambre, which is more tender.",
      "Discard the cooking milk."],
  v:"pizza-style matambre"}},

{id:"tomates-rellenos", c:"Argentina", r:"latin-america", m:"starter", t:40, s:4,
 i:[[8,"","tomato","structure","tomates redondos firmes","firm round tomatoes"],
    [340,"g","tuna","protein","atún en lata","canned tuna","escurrido","drained"],
    [150,"g","rice","structure","arroz blanco","white rice","cocido y frío","cooked and cold"],
    [2,"","egg","enrich","huevos duros","hard-boiled eggs","picados","chopped"],
    [5,"tbsp","mayo","sauce","mayonesa","mayonnaise"],
    [1,"handful","herb","garnish","perejil","parsley","picado","chopped"],
    [1,"tsp","salt","salt","sal","salt"],
    [0.5,"tsp","pepper","aromatic","pimienta negra","black pepper"]],
 es:{n:"Tomates rellenos con atún", b:"Tomates frescos rellenos de atún, arroz, huevo y mayonesa. Entrada fría de las fiestas y del verano.",
  st:["Corta una tapa a cada tomate, vacíalos con una cucharita y sálalos por dentro. Déjalos boca abajo 10 minutos.",
      "Mezcla el atún, el arroz, el huevo, la mayonesa, el perejil y la pimienta.",
      "Rellena los tomates, coloca la tapa y enfría 20 minutos antes de servir."],
  tp:["La pulpa que sacas sirve para una salsa.",
      "Rellenos se conservan en la heladera hasta 1 día."],
  v:"tomates rellenos"},
 en:{n:"Tomates Rellenos (Tuna-Stuffed Tomatoes)", b:"Fresh tomatoes stuffed with tuna, rice, egg and mayonnaise. A cold starter for holidays and summer.",
  st:["Cut a lid off each tomato, scoop them out with a teaspoon and salt the insides. Leave upside down for 10 minutes.",
      "Mix the tuna, rice, egg, mayonnaise, parsley and pepper.",
      "Fill the tomatoes, replace the lids and chill 20 minutes before serving."],
  tp:["Use the scooped-out pulp for a sauce.",
      "Filled, they keep in the fridge for up to 1 day."],
  v:"stuffed tomatoes"}},

{id:"buseca", c:"Argentina", r:"latin-america", m:"main", t:180, s:6,
 i:[[800,"g","beef","protein","mondongo limpio","cleaned beef tripe"],
    [2,"","citrus","acid","limones","lemons"],
    [250,"g","legume","protein","porotos blancos","white beans","remojados toda la noche","soaked overnight"],
    [2,"","chorizo","protein","chorizos colorados","cured paprika chorizos","en rodajas","sliced"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","pimiento morrón rojo","red pepper","picado","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"","veg","structure","zanahorias","carrots","en rodajas","sliced"],
    [400,"g","tomato","sauce","tomate triturado","crushed tomatoes"],
    [2,"tsp","paprika","aromatic","pimentón dulce","sweet paprika"],
    [2,"","herb","aromatic","hojas de laurel","bay leaves"],
    [2.5,"l","water","liquid","agua","water"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Buseca", b:"Guiso de mondongo con porotos blancos y chorizo colorado. Herencia italiana de los bodegones porteños.",
  st:["Frota el mondongo con el limón, enjuágalo y cuécelo en 2 litros de agua 2 horas. Córtalo en tiras.",
      "Aparte, cuece los porotos en el resto del agua 60 minutos.",
      "Sofríe la cebolla, el morrón y el ajo en el aceite 8 minutos. Añade el chorizo y la zanahoria y cocina 5 minutos más.",
      "Añade el pimentón, el tomate, el laurel, la sal, el mondongo y los porotos con parte de su agua.",
      "Cuece a fuego bajo 30 minutos, hasta que espese."],
  tp:["En olla a presión el mondongo tarda 45 minutos.",
      "Es mejor al día siguiente."],
  v:"buseca porteña"},
 en:{n:"Buseca (Argentine Tripe and Bean Stew)", b:"Beef tripe stewed with white beans and paprika chorizo. An Italian legacy of Buenos Aires taverns.",
  st:["Rub the tripe with the lemon, rinse and simmer in 2 litres of water for 2 hours. Cut into strips.",
      "Separately, simmer the beans in the rest of the water for 60 minutes.",
      "Cook the onion, pepper and garlic in the oil for 8 minutes. Add the chorizo and carrot and cook 5 minutes more.",
      "Add the paprika, tomato, bay, salt, tripe and beans with some of their water.",
      "Simmer on low heat for 30 minutes, until thick."],
  tp:["In a pressure cooker the tripe takes 45 minutes.",
      "It's better the next day."],
  v:"argentine buseca"}},

{id:"pollo-al-disco", c:"Argentina", r:"latin-america", m:"main", t:90, s:6,
 i:[[1.8,"kg","chicken","protein","presas de pollo","chicken pieces"],
    [4,"tbsp","oil","fat","aceite","oil"],
    [2,"","onion","aromatic","cebollas","onions","en pluma","sliced"],
    [2,"","bellpepper","aromatic","pimientos morrones","peppers","en tiras","in strips"],
    [4,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"tsp","paprika","aromatic","pimentón dulce","sweet paprika"],
    [300,"ml","winewhite","liquid","vino blanco","white wine"],
    [400,"g","tomato","sauce","tomate triturado","crushed tomatoes"],
    [800,"g","potato","structure","papas","potatoes","en cubos","cubed"],
    [2,"tsp","salt","salt","sal","salt"],
    [1,"handful","herb","garnish","perejil","parsley","picado","chopped"]],
 es:{n:"Pollo al disco", b:"Pollo guisado con vino, morrones y papas en el disco de arado, al fuego de leña. Comida de reunión en el campo.",
  st:["Dora el pollo con la sal en el aceite, en el disco o en una olla ancha, 10 minutos. Retíralo.",
      "Rehoga la cebolla, los morrones y el ajo en la misma grasa 10 minutos.",
      "Añade el pimentón, el vino y deja reducir 5 minutos. Añade el tomate y el pollo.",
      "Cuece 25 minutos, añade las papas y cocina 25 minutos más, hasta que estén tiernas. Termina con el perejil."],
  tp:["En casa sale igual en una sartén grande o una paellera.",
      "Mantén el fuego parejo y bajo después de dorar."],
  v:"pollo al disco de arado"},
 en:{n:"Pollo al Disco (Ploughshare Chicken Stew)", b:"Chicken stewed with wine, peppers and potatoes in a ploughshare disc over a wood fire. A countryside gathering meal.",
  st:["Brown the chicken with the salt in the oil, in the disc or a wide pot, for 10 minutes. Remove.",
      "Soften the onion, peppers and garlic in the same fat for 10 minutes.",
      "Add the paprika and wine and reduce 5 minutes. Add the tomato and the chicken.",
      "Simmer 25 minutes, add the potatoes and cook 25 minutes more, until tender. Finish with the parsley."],
  tp:["At home it works just as well in a large frying pan or paella pan.",
      "Keep the heat low and steady after browning."],
  v:"argentine disc chicken"}},

{id:"ninos-envueltos", c:"Argentina", r:"latin-america", m:"main", t:100, s:6,
 i:[[1,"","veg","structure","repollo","white cabbage","en hojas enteras","leaves separated"],
    [600,"g","beef","protein","carne picada de res","minced beef"],
    [100,"g","rice","structure","arroz","rice","crudo","uncooked"],
    [1,"","egg","binder","huevo","egg"],
    [2,"","onion","aromatic","cebollas","onions","picadas","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [800,"g","tomato","sauce","tomate triturado","crushed tomatoes"],
    [300,"ml","water","liquid","agua","water"],
    [1,"tsp","paprika","aromatic","pimentón dulce","sweet paprika"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Niños envueltos", b:"Hojas de repollo rellenas de carne y arroz, cocidas en salsa de tomate. Receta de las abuelas con raíz de Europa del Este y Medio Oriente.",
  st:["Blanquea las hojas de repollo 3 minutos en agua hirviendo y escúrrelas.",
      "Mezcla la carne, el arroz, el huevo, la mitad de la cebolla y del ajo y 1 cucharadita de sal.",
      "Pon una cucharada de relleno en cada hoja, dobla los lados y enrolla.",
      "Sofríe el resto de la cebolla y del ajo en el aceite 6 minutos, añade el pimentón, el tomate, el agua y el resto de la sal.",
      "Acomoda los rollitos en la salsa, tapa y cuece a fuego bajo 50 minutos."],
  tp:["Acomódalos apretados y con la unión hacia abajo para que no se abran.",
      "Se congelan bien con su salsa."],
  v:"niños envueltos de repollo"},
 en:{n:"Niños Envueltos (Stuffed Cabbage Rolls)", b:"Cabbage leaves filled with beef and rice, cooked in tomato sauce. A grandmother's recipe with Eastern European and Middle Eastern roots.",
  st:["Blanch the cabbage leaves for 3 minutes in boiling water and drain.",
      "Mix the beef, rice, egg, half the onion and garlic and 1 teaspoon of salt.",
      "Put a spoonful of filling on each leaf, fold in the sides and roll up.",
      "Cook the rest of the onion and garlic in the oil for 6 minutes, add the paprika, tomato, water and remaining salt.",
      "Arrange the rolls in the sauce, cover and simmer on low heat for 50 minutes."],
  tp:["Pack them tightly, seam side down, so they don't open.",
      "They freeze well in their sauce."],
  v:"argentine cabbage rolls"}},

{id:"bolas-de-fraile", c:"Argentina", r:"latin-america", m:"sweet", t:150, s:16,
 i:[[500,"g","apflour","structure","harina de trigo","plain flour"],
    [10,"g","yeast","leaven","levadura seca","dried yeast"],
    [200,"ml","milk","liquid","leche tibia","warm milk"],
    [2,"","egg","structure","huevos","eggs"],
    [60,"g","butter","fat","mantequilla","butter","blanda","softened"],
    [80,"g","sugar","sweet","azúcar","sugar"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"l","oil","fat","aceite","oil","para freír","for frying"],
    [400,"g","dulcedeleche","sweet","dulce de leche repostero","thick dulce de leche"]],
 es:{n:"Bolas de fraile", b:"Bollitos de masa dulce fritos, pasados por azúcar y rellenos de dulce de leche. Las facturas de las panaderías.",
  st:["Mezcla la harina, la levadura, 30 g de azúcar y la sal. Añade la leche y los huevos y amasa 8 minutos. Incorpora la mantequilla y amasa 5 minutos más.",
      "Deja levar tapado 60 minutos, hasta que doble.",
      "Divide en 16 bollos, colócalos sobre papel y deja levar 30 minutos más.",
      "Fríe en el aceite a 170 °C 2 minutos por lado. Escúrrelos y pásalos por el resto del azúcar.",
      "Ábrelos por un costado y rellénalos con el dulce de leche con una manga."],
  tp:["El aceite muy caliente los dora por fuera y los deja crudos por dentro.",
      "Son mejores el mismo día."],
  v:"bolas de fraile de panadería"},
 en:{n:"Bolas de Fraile (Dulce de Leche Doughnuts)", b:"Fried sweet dough balls rolled in sugar and filled with dulce de leche. A bakery pastry favourite.",
  st:["Mix the flour, yeast, 30 g of the sugar and salt. Add the milk and eggs and knead 8 minutes. Work in the butter and knead 5 minutes more.",
      "Cover and let rise 60 minutes, until doubled.",
      "Divide into 16 balls, set them on paper and let rise 30 minutes more.",
      "Fry in the oil at 170 °C for 2 minutes a side. Drain and roll in the remaining sugar.",
      "Cut a slit in the side and pipe in the dulce de leche."],
  tp:["Oil that's too hot browns the outside and leaves the inside raw.",
      "They're best the same day."],
  v:"argentine bolas de fraile"}},

{id:"lomito", c:"Argentina", r:"latin-america", m:"main", t:30, s:4,
 i:[[600,"g","beef","protein","lomo de res","beef tenderloin","en bifes finos","in thin steaks"],
    [4,"","bread","structure","panes de lomito o pan francés","long crusty rolls"],
    [4,"slice","ham","protein","jamón cocido","cooked ham"],
    [4,"slice","queso","protein","queso de máquina","mild sliced cheese"],
    [4,"","egg","protein","huevos","eggs"],
    [4,"leaf","veg","garnish","lechuga","lettuce"],
    [2,"","tomato","garnish","tomates","tomatoes","en rodajas","sliced"],
    [4,"tbsp","mayo","sauce","mayonesa","mayonnaise"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Lomito completo", b:"Sándwich de bife de lomo con jamón, queso, huevo frito, lechuga y tomate. El gran sándwich de Córdoba.",
  st:["Sala los bifes y cocínalos en la plancha caliente con la mitad del aceite 2 minutos por lado.",
      "Pon encima el jamón y el queso y tapa 1 minuto para que se funda.",
      "Fríe los huevos en el resto del aceite.",
      "Abre y tuesta los panes, úntalos con la mayonesa y arma con la lechuga, el tomate, la carne y el huevo."],
  tp:["Aplasta los bifes con un golpe para que queden parejos.",
      "Sírvelo enseguida, cortado al medio."],
  v:"lomito cordobés"},
 en:{n:"Lomito Completo (Argentine Steak Sandwich)", b:"A tenderloin steak sandwich with ham, cheese, fried egg, lettuce and tomato. Córdoba's great sandwich.",
  st:["Salt the steaks and cook on a hot griddle with half the oil, 2 minutes a side.",
      "Top with the ham and cheese and cover for 1 minute to melt.",
      "Fry the eggs in the remaining oil.",
      "Split and toast the rolls, spread with mayonnaise and build with lettuce, tomato, steak and egg."],
  tp:["Pound the steaks once so they're even.",
      "Serve at once, cut in half."],
  v:"argentine lomito"}},

{id:"pan-de-carne", c:"Argentina", r:"latin-america", m:"main", t:80, s:6,
 i:[[800,"g","beef","protein","carne picada de res","minced beef"],
    [60,"g","breadcrumbs","binder","pan rallado","dried breadcrumbs"],
    [100,"ml","milk","liquid","leche","milk"],
    [2,"","egg","binder","huevos","eggs"],
    [1,"","onion","aromatic","cebolla","onion","picada fina","finely chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"handful","herb","aromatic","perejil","parsley","picado","chopped"],
    [3,"","egg","protein","huevos duros","hard-boiled eggs","pelados","peeled"],
    [0.25,"tsp","spice","aromatic","nuez moscada","nutmeg"],
    [2,"tsp","salt","salt","sal","salt"],
    [0.5,"tsp","pepper","aromatic","pimienta negra","black pepper"]],
 es:{n:"Pan de carne", b:"Rollo de carne picada horneado con huevos duros en el centro. Se come caliente o frío, en rodajas.",
  st:["Calienta el horno a 180 °C. Remoja el pan rallado en la leche 5 minutos.",
      "Mezcla la carne, el pan remojado, los huevos crudos, la cebolla, el ajo, el perejil, la nuez moscada, la sal y la pimienta.",
      "Extiende la mezcla en un rectángulo, pon los huevos duros en fila y enrolla formando un pan.",
      "Hornea en una fuente 60 minutos. Deja reposar 10 minutos antes de cortar."],
  tp:["Frío se corta más limpio y rinde para sándwiches.",
      "Se congela bien en rodajas."],
  v:"pan de carne con huevo"},
 en:{n:"Pan de Carne (Argentine Meatloaf)", b:"A baked minced beef loaf with hard-boiled eggs in the centre. Eaten warm or cold, in slices.",
  st:["Heat the oven to 180 °C. Soak the breadcrumbs in the milk for 5 minutes.",
      "Mix the beef, soaked crumbs, raw eggs, onion, garlic, parsley, nutmeg, salt and pepper.",
      "Spread the mixture into a rectangle, lay the boiled eggs in a row and roll into a loaf.",
      "Bake in a dish for 60 minutes. Rest 10 minutes before slicing."],
  tp:["Cold, it slices more cleanly and makes good sandwiches.",
      "It freezes well in slices."],
  v:"argentine meatloaf"}}
];
