module.exports = [
{id:"asado", c:"Argentina", r:"latin-america", m:"main", t:180, s:8,
 i:[[1.5,"kg","beef","protein","tira de asado","beef short ribs, cross-cut (tira de asado)"],
    [1.2,"kg","beef","protein","vacío","flank steak (vacío)"],
    [8,"","sausage","protein","chorizos parrilleros","fresh grilling sausages"],
    [3,"tbsp","salt","salt","sal gruesa","coarse salt"]],
 es:{n:"Asado a la parrilla", b:"El ritual del domingo argentino: tira y vacío asados lentos a las brasas, solo con sal gruesa, con chorizos para empezar.",
  st:["Enciende el carbón y espera 40 minutos, hasta que esté cubierto de ceniza blanca. Arma una cama de brasas pareja.",
      "Pon la parrilla a unos 20 centímetros de las brasas. Debes poder tener la mano encima 8 segundos.",
      "Pon los chorizos primero y ásalos 25 minutos, girando. Sirve como entrada.",
      "Sala la carne con sal gruesa justo antes de ponerla. Pon el vacío con la grasa hacia abajo y la tira con el hueso hacia abajo.",
      "Asa 60 a 75 minutos sin tocar, añadiendo brasas por los lados. Voltea una vez y asa 20 minutos más.",
      "Corta y sirve con chimichurri y salsa criolla."],
  tp:["Fuego bajo y tiempo: el asado no se apura. Si las llamas tocan la carne, está muy cerca.",
      "Los chorizos comerciales llevan especias variadas: revisa la etiqueta si hay alergias."],
  v:"asado argentino a la parrilla"},
 en:{n:"Argentine Asado", b:"The Argentine Sunday ritual: short ribs and flank grilled slowly over embers with only coarse salt, and sausages to start.",
  st:["Light the charcoal and wait 40 minutes, until covered in white ash. Spread an even bed of embers.",
      "Set the grill about 20 centimetres above the embers. You should be able to hold your hand over it for 8 seconds.",
      "Put the sausages on first and grill 25 minutes, turning. Serve as a starter.",
      "Salt the beef with coarse salt just before it goes on. Lay the flank fat-side down and the ribs bone-side down.",
      "Grill 60 to 75 minutes without touching, adding embers at the sides. Turn once and grill 20 minutes more.",
      "Slice and serve with chimichurri and salsa criolla."],
  tp:["Low heat and time: asado can't be rushed. If flames touch the meat, it's too close.",
      "Store-bought sausages carry varied seasonings: check the label with allergies."],
  v:"argentine asado"}},

{id:"milanesa", c:"Argentina", r:"latin-america", m:"main", t:40, s:4,
 i:[[800,"g","beef","protein","nalga o bola de lomo en bifes finos","thin beef cutlets (top round)"],
    [3,"","egg","binder","huevos","eggs"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado fino","finely chopped"],
    [2,"tbsp","herb","aromatic","perejil","parsley","picado","chopped"],
    [1,"tsp","salt","salt","sal","salt"],
    [200,"g","breadcrumbs","dredge","pan rallado","breadcrumbs"],
    [250,"ml","oil","fat","aceite","oil","para freír","for frying"],
    [1,"","citrus","garnish","limón","lemon","en gajos","in wedges"]],
 es:{n:"Milanesas de carne", b:"Bifes finos pasados por huevo con ajo y perejil y pan rallado, fritos hasta dorar. El plato de todos los días en Argentina.",
  st:["Aplana los bifes con un mazo a medio centímetro de grueso.",
      "Bate los huevos con el ajo, el perejil y la sal. Deja los bifes en la mezcla 30 minutos.",
      "Pasa cada bife por pan rallado, apretando con la mano para que se pegue.",
      "Calienta el aceite en un sartén a fuego medio-alto. Fríe 3 minutos por lado, hasta que estén dorados.",
      "Escurre en papel y sirve con limón y puré o papas fritas."],
  tp:["Un doble empanado (huevo, pan, huevo, pan) da una costra más gruesa.",
      "Al horno a 200 °C con un poco de aceite, 20 minutos, quedan menos grasosas."],
  v:"milanesas de carne receta"},
 en:{n:"Argentine Milanesa", b:"Thin steaks dipped in egg with garlic and parsley and breadcrumbs, fried until golden. Argentina's everyday dish.",
  st:["Pound the steaks with a mallet to half a centimetre thick.",
      "Beat the eggs with the garlic, parsley and salt. Leave the steaks in the mixture for 30 minutes.",
      "Coat each steak in breadcrumbs, pressing with your hand so they stick.",
      "Heat the oil in a pan over medium-high heat. Fry 3 minutes per side, until golden.",
      "Drain on paper and serve with lemon and mash or fries."],
  tp:["A double coat (egg, crumbs, egg, crumbs) gives a thicker crust.",
      "Baked at 200 °C with a little oil for 20 minutes, they're less greasy."],
  v:"milanesa recipe"}},

{id:"milanesa-napolitana", c:"Argentina", r:"latin-america", m:"main", t:60, s:4, o:220,
 i:[[4,"","beef","protein","milanesas de carne fritas","fried beef milanesas","ver receta de milanesa","see milanesa recipe"],
    [3,"","egg","binder","huevos (para las milanesas)","eggs (for the milanesas)"],
    [200,"g","breadcrumbs","dredge","pan rallado (para las milanesas)","breadcrumbs (for the milanesas)"],
    [400,"g","tomato","sauce","tomate triturado","crushed tomatoes"],
    [1,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [0.5,"tsp","salt","salt","sal","salt"],
    [1,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [4,"slice","ham","protein","jamón cocido","cooked ham"],
    [250,"g","mozzarella","protein","mozzarella","mozzarella","en tajadas","sliced"]],
 es:{n:"Milanesa a la napolitana", b:"Milanesa cubierta de salsa de tomate, jamón y mozzarella gratinada. Nació en una cantina de Buenos Aires, no en Nápoles.",
  st:["Sofríe el ajo en el aceite 1 minuto. Añade el tomate, el orégano y la sal y cuece 10 minutos.",
      "Calienta el horno a 220 °C.",
      "Pon las milanesas fritas en una bandeja. Cubre cada una con 2 cucharadas de salsa, 1 tajada de jamón y mozzarella.",
      "Hornea 8 minutos, hasta que el queso se funda y dore en partes.",
      "Sirve con papas fritas."],
  tp:["La salsa debe estar espesa o la milanesa se ablanda.",
      "Añade orégano encima al sacarla del horno."],
  v:"milanesa napolitana receta"},
 en:{n:"Milanesa Napolitana", b:"A milanesa topped with tomato sauce, ham and melted mozzarella. Born in a Buenos Aires canteen, not in Naples.",
  st:["Cook the garlic in the oil for 1 minute. Add the tomato, oregano and salt and cook 10 minutes.",
      "Heat the oven to 220 °C.",
      "Set the fried milanesas on a tray. Top each with 2 tablespoons of sauce, 1 slice of ham and mozzarella.",
      "Bake 8 minutes, until the cheese melts and browns in spots.",
      "Serve with fries."],
  tp:["The sauce must be thick or the milanesa goes soggy.",
      "Sprinkle oregano on top as it comes out of the oven."],
  v:"milanesa napolitana recipe"}},

{id:"locro", c:"Argentina", r:"latin-america", m:"soup", t:240, s:8,
 i:[[500,"g","hominy","structure","maíz blanco pisado","dried white hominy","remojado toda la noche","soaked overnight"],
    [250,"g","legume","protein","porotos blancos","white beans","remojados toda la noche","soaked overnight"],
    [500,"g","beef","protein","falda de res","beef flank","en cubos","cubed"],
    [300,"g","porkbelly","protein","panceta","pork belly","en cubos","cubed"],
    [2,"","chorizo","protein","chorizos colorados","cured red chorizos","en rodajas","sliced"],
    [800,"g","veg","structure","zapallo","winter squash","en cubos","cubed"],
    [3,"l","water","liquid","agua","water"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"tsp","paprika","aromatic","pimentón dulce","sweet paprika"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [3,"tsp","salt","salt","sal","salt"],
    [60,"ml","oil","fat","aceite","oil","para la salsa","for the sauce"],
    [4,"","scallion","garnish","cebollas de verdeo","green onions","picadas","chopped"],
    [1,"tsp","chilli","garnish","ají molido","chilli flakes"]],
 es:{n:"Locro argentino", b:"El guiso patrio del 25 de Mayo: maíz blanco, porotos, zapallo y carnes cocidos hasta volverse crema, con salsa roja de verdeo.",
  st:["Escurre el maíz y los porotos. Cuécelos en el agua 90 minutos a fuego bajo.",
      "Añade la carne, la panceta y los chorizos y cuece 60 minutos, moviendo cada tanto.",
      "Sofríe la cebolla en 2 cucharadas de aceite 8 minutos. Añade 1 cucharadita de pimentón y el comino. Échalo a la olla con el zapallo y la sal.",
      "Cuece 60 minutos más, moviendo seguido, hasta que el zapallo se deshaga y el guiso esté espeso.",
      "Para la salsa, calienta el resto del aceite con el pimentón restante, el ají y el verdeo 1 minuto.",
      "Sirve el locro con una cucharada de salsa encima."],
  tp:["Mueve seguido en la última hora: se pega al fondo.",
      "Es más rico al día siguiente."],
  v:"locro argentino receta"},
 en:{n:"Argentine Locro", b:"The patriotic stew of May 25th: white hominy, beans, squash and meats cooked until creamy, with a red green-onion sauce.",
  st:["Drain the hominy and beans. Cook them in the water for 90 minutes on low.",
      "Add the beef, pork belly and chorizos and cook 60 minutes, stirring now and then.",
      "Cook the onion in 2 tablespoons of oil for 8 minutes. Add 1 teaspoon of paprika and the cumin. Add it to the pot with the squash and salt.",
      "Cook 60 minutes more, stirring often, until the squash dissolves and the stew is thick.",
      "For the sauce, heat the rest of the oil with the remaining paprika, chilli and green onion for 1 minute.",
      "Serve the locro with a spoonful of sauce on top."],
  tp:["Stir often in the last hour: it sticks to the bottom.",
      "It's better the next day."],
  v:"argentine locro recipe"}},

{id:"provoleta", c:"Argentina", r:"latin-america", m:"starter", t:15, s:4,
 i:[[400,"g","cheese","protein","provolone en rueda de 2 cm","provolone in a 2 cm round"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [0.5,"tsp","chilli","aromatic","ají molido","chilli flakes"],
    [2,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [1,"","bread","serve","pan","bread","en rebanadas","sliced"]],
 es:{n:"Provoleta", b:"Una rueda de provolone a la parrilla, dorada por fuera y derretida por dentro, con orégano y ají. La entrada del asado.",
  st:["Deja el queso en el congelador 20 minutos para que aguante el calor.",
      "Calienta una sartén de hierro o la parrilla a fuego fuerte.",
      "Cocina el queso 2 minutos, hasta que tenga costra, voltéalo con espátula y cocina 2 minutos más.",
      "Espolvorea orégano y ají, rocía el aceite y sirve de inmediato con pan."],
  tp:["El frío previo evita que se derrita antes de dorarse.",
      "Se come caliente: frío se vuelve de goma."],
  v:"provoleta a la parrilla"},
 en:{n:"Provoleta (Grilled Provolone)", b:"A round of provolone grilled golden outside and molten inside, with oregano and chilli. The asado starter.",
  st:["Put the cheese in the freezer for 20 minutes so it holds up to the heat.",
      "Heat a cast-iron pan or the grill over high heat.",
      "Cook the cheese 2 minutes, until crusted, flip with a spatula and cook 2 minutes more.",
      "Sprinkle with oregano and chilli, drizzle with the oil and serve right away with bread."],
  tp:["The chill first keeps it from melting before it browns.",
      "Eat it hot: cold, it turns rubbery."],
  v:"provoleta recipe"}},

{id:"choripan", c:"Argentina", r:"latin-america", m:"main", t:40, s:4,
 i:[[4,"","sausage","protein","chorizos parrilleros","fresh grilling sausages"],
    [4,"","bread","structure","panes franceses o baguette","crusty rolls or baguette pieces"],
    [1,"bunch","herb","aromatic","perejil","parsley","picado fino","finely chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado fino","finely chopped"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [0.5,"tsp","chilli","aromatic","ají molido","chilli flakes"],
    [2,"tbsp","winevinegar","acid","vinagre de vino tinto","red wine vinegar"],
    [80,"ml","oil","fat","aceite","oil"],
    [0.5,"tsp","salt","salt","sal","salt"]],
 es:{n:"Choripán", b:"Chorizo a la parrilla abierto en mariposa dentro de pan crujiente, con chimichurri. La comida de cancha y de esquina.",
  st:["Mezcla el perejil, el ajo, el orégano, el ají, el vinagre, el aceite y la sal. Deja reposar 30 minutos: es el chimichurri.",
      "Asa los chorizos a fuego medio 20 minutos, girándolos.",
      "Ábrelos a lo largo en mariposa y dóralos 2 minutos del lado del corte.",
      "Tuesta los panes abiertos en la parrilla.",
      "Pon el chorizo en el pan y báñalo con chimichurri."],
  tp:["No pinches los chorizos al asarlos: pierden el jugo.",
      "El chimichurri mejora de un día para otro."],
  v:"choripan receta"},
 en:{n:"Choripán", b:"A grilled sausage split butterfly-style in crusty bread with chimichurri. Stadium and street-corner food.",
  st:["Mix the parsley, garlic, oregano, chilli, vinegar, oil and salt. Leave 30 minutes: that's the chimichurri.",
      "Grill the sausages over medium heat for 20 minutes, turning.",
      "Split them lengthwise butterfly-style and brown the cut side for 2 minutes.",
      "Toast the opened rolls on the grill.",
      "Put the sausage in the bread and spoon over the chimichurri."],
  tp:["Don't prick the sausages while grilling: they lose their juices.",
      "Chimichurri is better the next day."],
  v:"choripan recipe"}},

{id:"salsa-criolla-ar", c:"Argentina", r:"latin-america", m:"sauce", t:15, s:8,
 i:[[1,"","onion","aromatic","cebolla","onion","picada fina","finely chopped"],
    [2,"","tomato","aromatic","tomates","tomatoes","sin semillas, picados","seeded, chopped"],
    [1,"","bellpepper","aromatic","morrón rojo","red bell pepper","picado fino","finely chopped"],
    [1,"","bellpepper","aromatic","morrón verde","green bell pepper","picado fino","finely chopped"],
    [60,"ml","winevinegar","acid","vinagre de vino","wine vinegar"],
    [120,"ml","oil","fat","aceite","oil"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [0.5,"tsp","salt","salt","sal","salt"]],
 es:{n:"Salsa criolla argentina", b:"Cebolla, tomate y morrones picados finos en vinagre y aceite. La otra salsa del asado, fresca y crujiente.",
  st:["Pica todas las verduras en cubos pequeños y parejos.",
      "Mezcla con el vinagre, el aceite, el orégano y la sal.",
      "Deja reposar 1 hora antes de servir."],
  tp:["Pica a cuchillo: con procesadora queda aguada.",
      "Dura 3 días en el refrigerador."],
  v:"salsa criolla argentina receta"},
 en:{n:"Argentine Salsa Criolla", b:"Onion, tomato and bell peppers finely chopped in vinegar and oil. The other asado sauce, fresh and crunchy.",
  st:["Chop all the vegetables into small, even dice.",
      "Mix with the vinegar, oil, oregano and salt.",
      "Leave 1 hour before serving."],
  tp:["Chop by hand: a food processor makes it watery.",
      "Keeps 3 days in the fridge."],
  v:"argentine salsa criolla recipe"}},

{id:"matambre-arrollado", c:"Argentina", r:"latin-america", m:"main", t:180, s:8,
 i:[[1.5,"kg","beef","protein","matambre de res","beef matambre (flank skirt)","desgrasado","trimmed"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"bunch","herb","aromatic","perejil","parsley","picado","chopped"],
    [2,"tsp","salt","salt","sal","salt"],
    [2,"","veg","structure","zanahorias","carrots","en bastones","in sticks"],
    [4,"","egg","protein","huevos duros","hard-boiled eggs"],
    [1,"","bellpepper","aromatic","morrón rojo","red bell pepper","en tiras","in strips"],
    [3,"l","water","liquid","agua","water"],
    [1,"","onion","aromatic","cebolla","onion","para el hervido","for the poaching water"],
    [2,"leaf","herb","aromatic","hojas de laurel","bay leaves"]],
 es:{n:"Matambre arrollado", b:"Una lámina de carne rellena de zanahoria, huevo y morrón, enrollada, hervida y prensada. Se come frío en rodajas, en picadas y fiestas.",
  st:["Extiende la carne con la grasa hacia abajo. Úntala con el ajo, el perejil y la sal.",
      "Pon filas de zanahoria, huevo entero y morrón a lo ancho.",
      "Enrolla bien apretado a lo largo de la fibra y amarra con hilo cada 3 centímetros.",
      "Hierve en el agua con la cebolla, el laurel y un poco de sal 2 horas a fuego bajo.",
      "Sácalo, ponlo entre 2 bandejas con peso encima y refrigera toda la noche.",
      "Quita el hilo y corta en rodajas finas."],
  tp:["El prensado es lo que hace que las rodajas salgan firmes.",
      "Con ensalada rusa es el clásico de las fiestas de fin de año."],
  v:"matambre arrollado receta"},
 en:{n:"Rolled Matambre", b:"A sheet of beef filled with carrot, egg and bell pepper, rolled, poached and pressed. Eaten cold in slices, at parties and snack boards.",
  st:["Lay the beef fat-side down. Rub it with the garlic, parsley and salt.",
      "Lay rows of carrot, whole egg and bell pepper across it.",
      "Roll up tightly along the grain and tie with string every 3 centimetres.",
      "Simmer in the water with the onion, bay and a little salt for 2 hours on low.",
      "Lift it out, set it between 2 trays with a weight on top and chill overnight.",
      "Remove the string and slice thinly."],
  tp:["Pressing is what makes the slices firm.",
      "With potato salad it's the classic of the year-end holidays."],
  v:"matambre arrollado recipe"}},

{id:"humita-en-olla", c:"Argentina", r:"latin-america", m:"main", t:50, s:4,
 i:[[6,"","corn","structure","choclos frescos","fresh ears of corn","rallados","grated"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","morrón rojo","red bell pepper","picado","chopped"],
    [1,"tsp","paprika","aromatic","pimentón dulce","sweet paprika"],
    [250,"ml","milk","liquid","leche","milk"],
    [1,"tsp","salt","salt","sal","salt"],
    [150,"g","cheese","protein","queso fresco o cremoso","fresh melting cheese","en cubos","cubed"],
    [6,"leaf","herb","garnish","hojas de albahaca","basil leaves"]],
 es:{n:"Humita en olla", b:"Choclo rallado cocido con cebolla, morrón y leche hasta volverse crema, con queso que se funde. Comida del norte argentino.",
  st:["Ralla los choclos por el lado grueso del rallador y guarda todo el jugo.",
      "Sofríe la cebolla y el morrón en el aceite 10 minutos. Añade el pimentón.",
      "Añade el choclo rallado y la sal y cuece 10 minutos, moviendo.",
      "Añade la leche poco a poco y cuece 15 minutos más a fuego bajo, moviendo, hasta que espese como polenta blanda.",
      "Añade el queso, apaga y sirve con albahaca."],
  tp:["Si el choclo está muy tierno y dulce, no hace falta más; si está duro, añade un poco más de leche.",
      "Se sirve en cazuela de barro con más queso encima."],
  v:"humita en olla receta"},
 en:{n:"Humita en Olla (Creamy Corn Stew)", b:"Grated fresh corn cooked with onion, bell pepper and milk until creamy, with melting cheese. Food of northern Argentina.",
  st:["Grate the corn on the coarse side of a grater, keeping all the juice.",
      "Cook the onion and bell pepper in the oil for 10 minutes. Add the paprika.",
      "Add the grated corn and salt and cook 10 minutes, stirring.",
      "Add the milk little by little and cook 15 minutes more on low, stirring, until thick like soft polenta.",
      "Add the cheese, turn off and serve with basil."],
  tp:["If the corn is young and sweet, nothing more is needed; if it's starchy, add a little more milk.",
      "It's served in a clay pot with more cheese on top."],
  v:"humita en olla recipe"}},

{id:"empanadas-tucumanas", c:"Argentina", r:"latin-america", m:"snack", t:120, s:6, o:220,
 i:[[500,"g","apflour","structure","harina de trigo","all-purpose flour"],
    [120,"g","lard","fat","grasa de pella o manteca de cerdo","lard"],
    [1.5,"tsp","salt","salt","sal","salt"],
    [220,"ml","water","liquid","agua tibia","warm water"],
    [600,"g","beef","protein","matambre o nalga de res","beef flank or top round","cortado a cuchillo en cubitos","hand-cut into small dice"],
    [2,"","onion","aromatic","cebollas","onions","picadas","chopped"],
    [4,"","scallion","aromatic","cebollas de verdeo","green onions","picadas","chopped"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [2,"tsp","paprika","aromatic","pimentón dulce","sweet paprika"],
    [0.5,"tsp","chilli","aromatic","ají molido","chilli flakes"],
    [3,"","egg","protein","huevos duros","hard-boiled eggs","picados","chopped"],
    [2,"tbsp","oil","fat","aceite","oil"]],
 es:{n:"Empanadas tucumanas", b:"Las empanadas de carne cortada a cuchillo de Tucumán: jugosas, con comino y verdeo, en masa de grasa. Se comen con la mano.",
  st:["Mezcla la harina y 1 cucharadita de sal. Añade la grasa derretida tibia y el agua y amasa 5 minutos. Reposa tapada 30 minutos.",
      "Sofríe la cebolla en el aceite 10 minutos. Añade la carne y cocina solo 3 minutos, hasta que cambie de color. Añade el comino, el pimentón, el ají y el resto de la sal.",
      "Apaga, añade el verdeo y enfría por completo. Mezcla con el huevo.",
      "Estira la masa fina y corta 18 discos de 12 centímetros.",
      "Pon 2 cucharadas de relleno, cierra y haz el repulgue doblando el borde.",
      "Calienta el horno a 220 °C. Hornea 15 minutos, hasta que estén doradas."],
  tp:["La carne cortada a cuchillo y apenas cocida es lo que las hace jugosas.",
      "El relleno debe estar frío o la masa se rompe."],
  v:"empanadas tucumanas receta"},
 en:{n:"Tucumán Empanadas", b:"Tucumán's empanadas of hand-cut beef: juicy, with cumin and green onion, in a lard pastry. Eaten by hand.",
  st:["Mix the flour and 1 teaspoon of salt. Add the warm melted lard and the water and knead 5 minutes. Rest covered 30 minutes.",
      "Cook the onion in the oil for 10 minutes. Add the beef and cook just 3 minutes, until it changes colour. Add the cumin, paprika, chilli and the rest of the salt.",
      "Turn off, add the green onion and cool completely. Mix in the egg.",
      "Roll the dough thin and cut 18 discs of 12 centimetres.",
      "Put in 2 tablespoons of filling, close and crimp the edge by folding.",
      "Heat the oven to 220 °C. Bake 15 minutes, until golden."],
  tp:["Hand-cut beef, barely cooked, is what makes them juicy.",
      "The filling must be cold or the dough tears."],
  v:"empanadas tucumanas recipe"}}
];
