module.exports = [
{id:"saltenas", c:"Bolivia", r:"latin-america", m:"snack", t:300, s:12, o:220,
 i:[[500,"g","apflour","structure","harina de trigo","all-purpose flour"],
    [120,"g","butter","fat","mantequilla","butter","derretida","melted"],
    [60,"g","sugar","sweet","azúcar","sugar","para la masa","for the dough"],
    [1,"","eggyolk","binder","yema de huevo","egg yolk"],
    [200,"ml","water","liquid","agua tibia","warm water"],
    [1,"tsp","achiote","aromatic","achiote en polvo","ground annatto"],
    [2,"tsp","salt","salt","sal","salt"],
    [500,"g","beef","protein","carne de res","beef","en cubos pequeños","in small dice"],
    [400,"ml","stock","liquid","caldo de res","beef stock"],
    [15,"g","gelatin","set","gelatina sin sabor","unflavoured gelatin"],
    [2,"","onion","aromatic","cebollas","onions","picadas","chopped"],
    [4,"","scallion","aromatic","cebollas verdes","green onions","picadas","chopped"],
    [2,"tbsp","ajipaste","aromatic","pasta de ají amarillo","ají amarillo paste"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [1,"tbsp","sugar","sweet","azúcar","sugar","para el relleno","for the filling"],
    [300,"g","potato","structure","papa","potato","en cubos pequeños, cocida","small dice, cooked"],
    [100,"g","legume","protein","arvejas","peas","cocidas","cooked"],
    [3,"","egg","garnish","huevos duros","hard-boiled eggs","picados","chopped"],
    [12,"","olives","garnish","aceitunas negras","black olives"],
    [40,"g","driedfruit","sweet","pasas","raisins"],
    [2,"tbsp","oil","fat","aceite","oil"]],
 es:{n:"Salteñas bolivianas", b:"Empanadas horneadas con un jigote jugoso casi líquido por dentro. Se comen a media mañana, de pie y sin derramar.",
  st:["Disuelve la gelatina en el caldo caliente. Sofríe la cebolla, el ají, el comino y el orégano en el aceite 10 minutos. Añade la carne, el caldo, el azúcar del relleno y 1 cucharadita de sal y cuece 15 minutos.",
      "Añade la papa, las arvejas y el cebollín. Enfría y refrigera toda la noche, hasta que cuaje.",
      "Mezcla la harina, el azúcar, el achiote y el resto de la sal. Añade la mantequilla, la yema y el agua y amasa 5 minutos. Reposa 30 minutos.",
      "Divide en 12 bolas y estira cada una en un círculo de 14 centímetros.",
      "Pon 2 cucharadas de jigote frío, un trozo de huevo, 1 aceituna y 2 pasas. Cierra por arriba y haz un repulgue trenzado.",
      "Calienta el horno a 220 °C. Hornea de pie 20 minutos, hasta que estén doradas."],
  tp:["El relleno debe estar cuajado y frío: si no, se escapa al cerrar.",
      "Se come de pie, mordiendo una punta y sorbiendo el jugo."],
  v:"salteñas bolivianas receta"},
 en:{n:"Bolivian Salteñas", b:"Baked empanadas with a juicy, almost soupy filling. Eaten mid-morning, standing up, without spilling a drop.",
  st:["Dissolve the gelatin in the hot stock. Cook the onion, ají, cumin and oregano in the oil for 10 minutes. Add the beef, the stock, the filling sugar and 1 teaspoon of salt and cook 15 minutes.",
      "Add the potato, peas and green onion. Cool and chill overnight, until set.",
      "Mix the flour, sugar, annatto and the rest of the salt. Add the butter, yolk and water and knead 5 minutes. Rest 30 minutes.",
      "Divide into 12 balls and roll each into a 14 centimetre circle.",
      "Add 2 tablespoons of cold filling, a piece of egg, 1 olive and 2 raisins. Close over the top and crimp into a braid.",
      "Heat the oven to 220 °C. Bake standing upright for 20 minutes, until golden."],
  tp:["The filling must be set and cold: otherwise it escapes as you close them.",
      "Eat standing, biting one corner and sipping the juice."],
  v:"saltenas recipe"}},

{id:"silpancho", c:"Bolivia", r:"latin-america", m:"main", t:45, s:4,
 i:[[500,"g","beef","protein","carne de res","beef top round","en filetes","in steaks"],
    [100,"g","breadcrumbs","dredge","pan rallado","breadcrumbs"],
    [1,"tsp","salt","salt","sal","salt"],
    [250,"g","rice","structure","arroz blanco cocido","cooked white rice"],
    [500,"g","potato","structure","papas","potatoes","en rodajas, cocidas","sliced, boiled"],
    [100,"ml","oil","fat","aceite","oil"],
    [4,"","egg","protein","huevos","eggs"],
    [2,"","tomato","garnish","tomates","tomatoes","en cubos","diced"],
    [1,"","onion","garnish","cebolla","onion","en cubos","diced"],
    [1,"","chilli","garnish","locoto","locoto chile","picado","chopped"],
    [1,"handful","herb","garnish","perejil","parsley","picado","chopped"]],
 es:{n:"Silpancho", b:"El plato de Cochabamba en capas: arroz, papas doradas, un bife finísimo empanizado, huevo frito y ensalada de tomate con locoto.",
  st:["Pon cada filete sobre pan rallado y golpéalo con un mazo hasta que quede finísimo, del tamaño de un plato. Voltea y repite. Sala.",
      "Dora las papas en 2 cucharadas de aceite.",
      "Fríe cada bife en aceite caliente 1 minuto por lado.",
      "Fríe los huevos.",
      "Mezcla el tomate, la cebolla, el locoto y el perejil con una pizca de sal.",
      "Arma en el plato: arroz, papas, bife, huevo y ensalada encima."],
  tp:["El pan rallado se incrusta al golpear: por eso no hace falta huevo para empanizar.",
      "El bife debe cubrir casi todo el plato."],
  v:"silpancho receta"},
 en:{n:"Silpancho (Bolivian Layered Steak Plate)", b:"Cochabamba's layered plate: rice, browned potatoes, a paper-thin breaded steak, fried egg and tomato-locoto salad.",
  st:["Lay each steak on breadcrumbs and pound with a mallet until very thin, the size of a plate. Flip and repeat. Salt.",
      "Brown the potatoes in 2 tablespoons of oil.",
      "Fry each steak in hot oil for 1 minute per side.",
      "Fry the eggs.",
      "Mix the tomato, onion, locoto and parsley with a pinch of salt.",
      "Build on the plate: rice, potatoes, steak, egg and salad on top."],
  tp:["The crumbs press into the meat as you pound: that's why no egg is needed.",
      "The steak should cover almost the whole plate."],
  v:"silpancho recipe"}},

{id:"sopa-de-mani", c:"Bolivia", r:"latin-america", m:"soup", t:90, s:6,
 i:[[150,"g","peanut","thicken","maní crudo pelado","raw skinned peanuts"],
    [500,"ml","water","liquid","agua","water","para licuar el maní","to blend the peanuts"],
    [600,"g","beef","protein","costilla de res","beef ribs","en trozos","in pieces"],
    [2,"l","water","liquid","agua","water"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"","veg","protein","zanahoria","carrot","en cubos","diced"],
    [100,"g","legume","protein","arvejas","peas"],
    [60,"g","pasta","structure","coditos","macaroni"],
    [2,"tsp","salt","salt","sal","salt"],
    [400,"g","potato","garnish","papas","potatoes","en bastones, fritas","cut in sticks, fried"],
    [1,"handful","herb","garnish","perejil","parsley","picado","chopped"]],
 es:{n:"Sopa de maní", b:"La sopa cremosa de maní de Bolivia, con costilla, verduras y papas fritas encima que se ablandan en el plato.",
  st:["Cuece la costilla en el agua con la sal 60 minutos.",
      "Licúa el maní con 500 ml de agua hasta que esté muy liso.",
      "Sofríe la cebolla y el ajo en el aceite 5 minutos y añádelos a la olla con la zanahoria.",
      "Añade el maní licuado colándolo y cuece 15 minutos, moviendo seguido: se pega.",
      "Añade las arvejas y los coditos y cuece 10 minutos más.",
      "Sirve con papas fritas y perejil encima."],
  tp:["Mueve seguido después del maní: se pega y se quema en el fondo.",
      "Con maní crudo queda más blanca y suave que con maní tostado."],
  v:"sopa de mani boliviana receta"},
 en:{n:"Bolivian Peanut Soup", b:"Bolivia's creamy peanut soup with beef ribs, vegetables and fries on top that soften in the bowl.",
  st:["Simmer the ribs in the water with the salt for 60 minutes.",
      "Blend the peanuts with 500 ml of water until very smooth.",
      "Cook the onion and garlic in the oil for 5 minutes and add them to the pot with the carrot.",
      "Strain in the blended peanuts and cook 15 minutes, stirring often: it sticks.",
      "Add the peas and macaroni and cook 10 minutes more.",
      "Serve with fries and parsley on top."],
  tp:["Stir often after the peanuts go in: they stick and burn on the bottom.",
      "Raw peanuts make it paler and milder than roasted ones."],
  v:"bolivian peanut soup recipe"}},

{id:"pique-macho", c:"Bolivia", r:"latin-america", m:"main", t:45, s:4,
 i:[[600,"g","beef","protein","lomo o cuadril de res","beef sirloin","en tiras","in strips"],
    [4,"","sausage","protein","salchichas","sausages","en rodajas","sliced"],
    [800,"g","potato","structure","papas","potatoes","en bastones","in sticks"],
    [500,"ml","oil","fat","aceite","oil","para freír","for frying"],
    [1,"","onion","aromatic","cebolla","onion","en gajos","in wedges"],
    [2,"","tomato","aromatic","tomates","tomatoes","en gajos","in wedges"],
    [2,"","chilli","aromatic","locotos","locoto chiles","en tiras","in strips"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"tsp","pepper","aromatic","pimienta negra","black pepper"],
    [3,"","egg","garnish","huevos duros","hard-boiled eggs","en rodajas","sliced"]],
 es:{n:"Pique macho", b:"Una montaña de papas fritas con tiras de carne, salchicha, tomate, cebolla y locoto picante. Para compartir de noche en Cochabamba.",
  st:["Fríe las papas en el aceite a 170 °C 8 minutos, hasta que estén doradas. Escurre y sala.",
      "En un sartén grande con 2 cucharadas de aceite, dora la carne a fuego fuerte 3 minutos con la sal y la pimienta.",
      "Añade las salchichas y dóralas 2 minutos.",
      "Añade la cebolla, el tomate y el locoto y saltea 2 minutos: deben quedar crujientes.",
      "Pon las papas en una fuente, cubre con la carne y las verduras y termina con el huevo."],
  tp:["El locoto es muy picante: quítale semillas y venas para suavizarlo.",
      "Se come del centro de la mesa, con tenedores y sin platos."],
  v:"pique macho receta"},
 en:{n:"Pique Macho (Bolivian Loaded Fries)", b:"A mountain of fries under strips of beef, sausage, tomato, onion and hot locoto. For sharing late at night in Cochabamba.",
  st:["Fry the potatoes in the oil at 170 °C for 8 minutes, until golden. Drain and salt.",
      "In a large pan with 2 tablespoons of oil, sear the beef over high heat for 3 minutes with the salt and pepper.",
      "Add the sausages and brown 2 minutes.",
      "Add the onion, tomato and locoto and toss 2 minutes: they should stay crisp.",
      "Pile the potatoes on a platter, cover with the beef and vegetables and finish with the egg."],
  tp:["Locoto is very hot: remove the seeds and veins to tame it.",
      "It's eaten from the middle of the table, with forks and no plates."],
  v:"pique macho recipe"}},

{id:"llajua", c:"Bolivia", r:"latin-america", m:"sauce", t:10, s:6,
 i:[[3,"","tomato","aromatic","tomates","tomatoes"],
    [1,"","chilli","aromatic","locoto","locoto chile","sin semillas","seeded"],
    [1,"handful","herb","aromatic","quirquiña o cilantro","quirquiña or cilantro"],
    [0.5,"tsp","salt","salt","sal","salt"]],
 es:{n:"Llajua", b:"La salsa picante de Bolivia, molida en batán: tomate, locoto y quirquiña. Va con todo.",
  st:["Muele el locoto con la sal en un mortero hasta hacer pasta.",
      "Añade los tomates en trozos y muele hasta que estén deshechos pero con textura.",
      "Añade la quirquiña picada y mezcla."],
  tp:["En licuadora, solo unos pulsos: debe quedar rústica.",
      "Se come el mismo día."],
  v:"llajua boliviana receta"},
 en:{n:"Llajua (Bolivian Hot Sauce)", b:"Bolivia's hot sauce, ground on a grinding stone: tomato, locoto and quirquiña. It goes with everything.",
  st:["Grind the locoto with the salt in a mortar into a paste.",
      "Add the tomatoes in pieces and grind until broken down but still textured.",
      "Add the chopped quirquiña and mix."],
  tp:["In a blender, just a few pulses: it should stay rustic.",
      "Eat it the same day."],
  v:"llajua recipe"}},

{id:"encebollado", c:"Ecuador", r:"latin-america", m:"soup", t:75, s:6,
 i:[[800,"g","tuna","protein","albacora o atún fresco","fresh albacore or tuna","en trozos","in pieces"],
    [2.5,"l","water","liquid","agua","water"],
    [800,"g","cassava","structure","yuca","cassava","pelada, en trozos","peeled, in chunks"],
    [2,"","tomato","aromatic","tomates","tomatoes","picados","chopped"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [1,"tbsp","oil","fat","aceite","oil"],
    [2,"tsp","salt","salt","sal","salt"],
    [1,"bunch","herb","aromatic","cilantro","cilantro"],
    [2,"","onion","garnish","cebollas moradas","red onions","en pluma, curtidas en limón","sliced, cured in lime"],
    [4,"","citrus","acid","limones","limes","en jugo","juiced"],
    [1,"handful","plantain","serve","chifles (chips de plátano verde)","green plantain chips (chifles)"]],
 es:{n:"Encebollado", b:"La sopa de pescado de Guayaquil con yuca y mucha cebolla morada curtida en limón. El desayuno para después de la fiesta.",
  st:["Sofríe el tomate, la cebolla, el ajo y el comino en el aceite 8 minutos. Añade el agua, la sal y los tallos de cilantro.",
      "Hierve 10 minutos. Añade el pescado y cuece 12 minutos. Sácalo y desmenúzalo.",
      "Añade la yuca al líquido y cuece 25 minutos, hasta que esté blanda. Saca la mitad, licúala con un poco de líquido y regrésala para espesar.",
      "Mezcla la cebolla morada con el limón y una pizca de sal 15 minutos.",
      "Regresa el pescado. Sirve con la cebolla curtida encima, cilantro y chifles."],
  tp:["La yuca debe cocerse del todo; quita la fibra dura del centro.",
      "La cebolla curtida va generosa: es lo que le da nombre."],
  v:"encebollado ecuatoriano receta"},
 en:{n:"Encebollado (Ecuadorian Fish Soup)", b:"Guayaquil's fish soup with cassava and lots of red onion cured in lime. The breakfast for after the party.",
  st:["Cook the tomato, onion, garlic and cumin in the oil for 8 minutes. Add the water, salt and cilantro stems.",
      "Boil 10 minutes. Add the fish and cook 12 minutes. Lift it out and flake it.",
      "Add the cassava to the liquid and cook 25 minutes, until soft. Take out half, blend it with a little liquid and return it to thicken.",
      "Mix the red onion with the lime and a pinch of salt for 15 minutes.",
      "Return the fish. Serve with the cured onion on top, cilantro and plantain chips."],
  tp:["Cassava must be fully cooked; remove the woody core.",
      "Be generous with the cured onion: it gives the soup its name."],
  v:"encebollado recipe"}},

{id:"locro-de-papa", c:"Ecuador", r:"latin-america", m:"soup", t:45, s:6,
 i:[[1.2,"kg","potato","structure","papas","potatoes","peladas, en cubos","peeled, cubed"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"tsp","achiote","aromatic","achiote en polvo","ground annatto"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [1.5,"l","water","liquid","agua","water"],
    [250,"ml","milk","liquid","leche","milk"],
    [150,"g","queso","protein","queso fresco","queso fresco","desmoronado","crumbled"],
    [1.5,"tsp","salt","salt","sal","salt"],
    [2,"","avocado","garnish","aguacates","avocados","en rebanadas","sliced"],
    [1,"handful","herb","garnish","cilantro","cilantro","picado","chopped"]],
 es:{n:"Locro de papa", b:"La sopa de papa de la sierra ecuatoriana: espesa, amarilla de achiote, con queso fresco que se funde y aguacate encima.",
  st:["Sofríe la cebolla, el ajo, el achiote y el comino en el aceite 5 minutos.",
      "Añade la papa y el agua y cuece 25 minutos, hasta que la papa esté muy blanda.",
      "Aplasta parte de la papa contra la olla para espesar.",
      "Añade la leche, el queso y la sal y calienta 5 minutos sin hervir.",
      "Sirve con aguacate y cilantro."],
  tp:["Usa papas harinosas: se deshacen y espesan solas.",
      "Se espesa al día siguiente; añade agua al recalentar."],
  v:"locro de papa ecuatoriano receta"},
 en:{n:"Ecuadorian Potato Soup (Locro de Papa)", b:"The potato soup of the Ecuadorian highlands: thick, yellow with annatto, with melting queso fresco and avocado on top.",
  st:["Cook the onion, garlic, annatto and cumin in the oil for 5 minutes.",
      "Add the potato and water and cook 25 minutes, until very soft.",
      "Mash some of the potato against the pot to thicken.",
      "Add the milk, cheese and salt and heat 5 minutes without boiling.",
      "Serve with avocado and cilantro."],
  tp:["Use floury potatoes: they break down and thicken on their own.",
      "It thickens overnight; add water when reheating."],
  v:"ecuadorian locro de papa recipe"}},

{id:"llapingachos", c:"Ecuador", r:"latin-america", m:"main", t:60, s:4,
 i:[[1,"kg","potato","structure","papas","potatoes","peladas","peeled"],
    [1,"tsp","achiote","aromatic","achiote en polvo","ground annatto"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [0.5,"","onion","aromatic","cebolla blanca","white onion","picada fina","finely chopped"],
    [1.5,"tsp","salt","salt","sal","salt"],
    [150,"g","queso","protein","queso fresco o mozzarella","queso fresco or mozzarella","desmenuzado","crumbled"],
    [80,"g","peanut","sauce","maní tostado","roasted peanuts","para la salsa","for the sauce"],
    [200,"ml","milk","liquid","leche","milk","para la salsa","for the sauce"],
    [4,"","egg","garnish","huevos","eggs","fritos","fried"],
    [2,"","avocado","garnish","aguacates","avocados","en rebanadas","sliced"]],
 es:{n:"Llapingachos", b:"Tortillas de papa con achiote rellenas de queso, doradas en plancha, con salsa de maní, huevo frito y aguacate.",
  st:["Hierve las papas en agua con 1 cucharadita de sal 20 minutos. Haz puré.",
      "Sofríe la cebolla con el achiote en 1 cucharada de aceite 3 minutos y mézclala con el puré.",
      "Forma 12 bolas, hunde el pulgar, rellena con queso y cierra. Aplana a 2 centímetros.",
      "Dóralas en un sartén con el resto del aceite 4 minutos por lado.",
      "Licúa el maní con la leche y el resto de la sal y calienta 5 minutos, hasta que espese.",
      "Sirve los llapingachos con la salsa de maní, el huevo y el aguacate."],
  tp:["Refrigera las tortillas 30 minutos antes de dorar para que no se rompan.",
      "Con curtido de cebolla y tomate al lado es el plato completo."],
  v:"llapingachos receta"},
 en:{n:"Llapingachos (Cheese-Stuffed Potato Cakes)", b:"Annatto potato cakes stuffed with cheese, browned on a griddle, with peanut sauce, fried egg and avocado.",
  st:["Boil the potatoes in water with 1 teaspoon of salt for 20 minutes. Mash.",
      "Cook the onion with the annatto in 1 tablespoon of oil for 3 minutes and mix into the mash.",
      "Shape 12 balls, press in your thumb, fill with cheese and close. Flatten to 2 centimetres.",
      "Brown them in a pan with the rest of the oil for 4 minutes per side.",
      "Blend the peanuts with the milk and the rest of the salt and heat 5 minutes, until thick.",
      "Serve the cakes with the peanut sauce, egg and avocado."],
  tp:["Chill the cakes 30 minutes before browning so they don't break.",
      "With an onion and tomato salad on the side it's the full plate."],
  v:"llapingachos recipe"}},

{id:"bolon-de-verde", c:"Ecuador", r:"latin-america", m:"breakfast", t:40, s:4,
 i:[[4,"","plantain","structure","plátanos verdes","green plantains","pelados, en trozos","peeled, in chunks"],
    [2,"tbsp","butter","fat","mantequilla","butter"],
    [1,"tsp","salt","salt","sal","salt"],
    [200,"g","queso","protein","queso fresco","queso fresco","desmenuzado","crumbled"],
    [2,"tbsp","oil","fat","aceite","oil"]],
 es:{n:"Bolón de verde", b:"Bolas de plátano verde majado con queso, doradas en sartén. El desayuno de la costa ecuatoriana con café.",
  st:["Hierve el plátano 20 minutos, hasta que esté blando. También puedes freírlo en trozos 8 minutos.",
      "Aplasta caliente con la mantequilla y la sal hasta tener una masa gruesa.",
      "Mezcla con el queso y forma 4 bolas grandes apretando bien.",
      "Dóralas en el aceite a fuego medio 8 minutos, girándolas.",
      "Sirve calientes con huevo frito o café."],
  tp:["Aplasta el plátano caliente: frío no se une.",
      "Se pueden formar y congelar crudos."],
  v:"bolon de verde receta"},
 en:{n:"Bolón de Verde (Green Plantain Balls)", b:"Balls of mashed green plantain with cheese, browned in a pan. Breakfast on the Ecuadorian coast, with coffee.",
  st:["Boil the plantain for 20 minutes, until soft. You can also fry it in chunks for 8 minutes.",
      "Mash while hot with the butter and salt into a coarse dough.",
      "Mix in the cheese and shape 4 large balls, pressing firmly.",
      "Brown them in the oil over medium heat for 8 minutes, turning.",
      "Serve hot with fried egg or coffee."],
  tp:["Mash the plantain hot: cold, it won't hold.",
      "They can be shaped and frozen raw."],
  v:"bolon de verde recipe"}},

{id:"encocado", c:"Ecuador", r:"latin-america", m:"main", t:40, s:4,
 i:[[700,"g","whitefish","protein","pescado blanco firme","firm white fish","en trozos","in pieces"],
    [1,"","citrus","acid","limón","lime","en jugo","juiced"],
    [1.5,"tsp","salt","salt","sal","salt"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla morada","red onion","picada","chopped"],
    [1,"","bellpepper","aromatic","pimiento verde","green bell pepper","picado","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"","tomato","aromatic","tomates","tomatoes","picados","chopped"],
    [1,"tsp","achiote","aromatic","achiote en polvo","ground annatto"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [400,"ml","coconutmilk","liquid","leche de coco","coconut milk"],
    [1,"handful","herb","garnish","cilantro","cilantro","picado","chopped"]],
 es:{n:"Encocado de pescado", b:"Pescado cocido en una salsa de leche de coco con sofrito y achiote. La cocina afro de Esmeraldas.",
  st:["Marina el pescado con el limón y 1 cucharadita de sal 15 minutos.",
      "Sofríe la cebolla, el pimiento y el ajo en el aceite 8 minutos. Añade el tomate, el achiote y el comino y cuece 5 minutos.",
      "Añade la leche de coco y el resto de la sal y hierve suave 10 minutos.",
      "Añade el pescado y cuece 6 minutos, sin mover mucho, hasta que se separe en lajas.",
      "Termina con cilantro y sirve con arroz y patacones."],
  tp:["Con pescado de carne firme, como corvina o dorado, no se deshace.",
      "La salsa debe quedar espesa: si está aguada, redúcela antes de añadir el pescado."],
  v:"encocado de pescado receta"},
 en:{n:"Encocado (Ecuadorian Coconut Fish)", b:"Fish cooked in a coconut milk sauce with sofrito and annatto. The Afro-Ecuadorian cooking of Esmeraldas.",
  st:["Marinate the fish with the lime and 1 teaspoon of salt for 15 minutes.",
      "Cook the onion, bell pepper and garlic in the oil for 8 minutes. Add the tomato, annatto and cumin and cook 5 minutes.",
      "Add the coconut milk and the rest of the salt and simmer 10 minutes.",
      "Add the fish and cook 6 minutes, stirring little, until it flakes.",
      "Finish with cilantro and serve with rice and patacones."],
  tp:["Firm-fleshed fish such as corvina or mahi-mahi won't fall apart.",
      "The sauce should be thick: if thin, reduce it before adding the fish."],
  v:"encocado recipe"}}
];
