module.exports = [
{id:"sonso-de-yuca", c:"Bolivia", r:"latin-america", m:"side", t:60, s:6,
 i:[[1,"kg","cassava","structure","yuca","cassava","pelada y en trozos","peeled, in chunks"],
    [250,"g","queso","enrich","queso fresco menonita","fresh white cheese","rallado","grated"],
    [50,"g","butter","fat","mantequilla","butter"],
    [60,"ml","milk","liquid","leche","milk"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Sonso de yuca", b:"Masa de yuca con mucho queso, asada en la sartén hasta dorar. Acompañante oriental de Santa Cruz.",
  st:["Cuece la yuca en agua con sal 25 minutos, hasta que esté muy tierna. Retira las fibras.",
      "Aplástala en caliente con la mantequilla, la leche y la sal hasta tener una masa lisa.",
      "Añade el queso y amasa.",
      "Extiende en una sartén aceitada de 1 cm de grosor y dora 6 minutos por lado a fuego medio."],
  tp:["Aplasta la yuca en caliente: fría se pone chiclosa.",
      "También se hace en brochetas, asado sobre brasas."],
  v:"sonso de yuca cruceño"},
 en:{n:"Sonso de Yuca (Bolivian Cassava Cheese Cake)", b:"Cassava mash loaded with cheese, pan-fried until golden. An eastern Bolivian side from Santa Cruz.",
  st:["Boil the cassava in salted water for 25 minutes, until very soft. Remove the fibres.",
      "Mash it hot with the butter, milk and salt into a smooth dough.",
      "Add the cheese and knead.",
      "Spread 1 cm thick in an oiled pan and brown 6 minutes per side over medium heat."],
  tp:["Mash the cassava hot: cold, it turns gummy.",
      "It's also shaped on skewers and grilled over embers."],
  v:"bolivian sonso de yuca"}},

{id:"picante-de-pollo", c:"Bolivia", r:"latin-america", m:"main", t:80, s:4,
 i:[[1,"kg","chicken","protein","pollo en presas","chicken pieces"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [2,"","onion","aromatic","cebollas","onions","en juliana","sliced"],
    [4,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [4,"tbsp","ajipaste","aromatic","ají colorado molido","ground red ají paste"],
    [1,"tsp","spice","aromatic","comino","cumin"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [1,"l","water","liquid","agua","water"],
    [150,"g","legume","structure","arvejas","green peas"],
    [2,"tsp","salt","salt","sal","salt"],
    [2,"","tomato","garnish","tomates","tomatoes","en rodajas","sliced"],
    [1,"","onion","garnish","cebolla (para la ensalada)","onion (for the salad)","en aros","in rings"],
    [1,"","chilli","garnish","locoto","locoto chilli","en tiras","in strips"]],
 es:{n:"Picante de pollo", b:"Pollo cocido en una salsa roja de ají, con ensalada de tomate y locoto. Plato de fiesta en La Paz y Cochabamba.",
  st:["Cuece el pollo en el agua con la sal 30 minutos. Guarda el caldo.",
      "Sofríe la cebolla, el ajo, el ají, el comino y el orégano en el aceite 10 minutos.",
      "Añade el pollo y 500 ml del caldo y cuece 25 minutos a fuego bajo.",
      "Añade las arvejas y cuece 5 minutos.",
      "Sirve con la ensalada de tomate, cebolla y locoto por encima."],
  tp:["Tradicionalmente se sirve con arroz blanco.",
      "El locoto es muy picante: quita las venas si lo quieres suave."],
  v:"picante de pollo boliviano"},
 en:{n:"Picante de Pollo (Bolivian Spicy Chicken)", b:"Chicken simmered in a red ají sauce, topped with a tomato and locoto salad. A festive dish in La Paz and Cochabamba.",
  st:["Simmer the chicken in the water with the salt for 30 minutes. Keep the broth.",
      "Cook the onion, garlic, ají, cumin and oregano in the oil for 10 minutes.",
      "Add the chicken and 500 ml of the broth and simmer 25 minutes on low.",
      "Add the peas and cook 5 minutes.",
      "Serve with the tomato, onion and locoto salad on top."],
  tp:["It's traditionally eaten with white rice.",
      "Locoto is very hot: remove the veins for a milder dish."],
  v:"bolivian picante de pollo"}},

{id:"pastel-de-queso-bo", c:"Bolivia", r:"latin-america", m:"snack", t:60, s:12,
 i:[[400,"g","apflour","structure","harina de trigo","plain flour"],
    [1,"tsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [60,"g","lard","fat","manteca de cerdo","lard"],
    [200,"ml","water","liquid","agua tibia","warm water"],
    [0.5,"tsp","salt","salt","sal","salt"],
    [250,"g","queso","enrich","queso fresco","fresh white cheese","desmenuzado","crumbled"],
    [750,"ml","oil","fat","aceite para freír","oil for frying"],
    [60,"g","icingsugar","garnish","azúcar glas","icing sugar"]],
 es:{n:"Pasteles de queso", b:"Empanadas fritas de queso que se inflan en el aceite, con azúcar glas. Se toman con api en las mañanas de La Paz.",
  st:["Mezcla la harina, el polvo de hornear, la sal y la manteca. Añade el agua y amasa 5 minutos. Reposa 20 minutos.",
      "Divide en 12 bolas y estíralas muy finas, de 15 cm.",
      "Pon queso en el centro, dobla y cierra con los dedos.",
      "Fríe a 180 °C 2 minutos por lado, bañándolos con aceite para que se inflen.",
      "Escurre y espolvorea con el azúcar glas."],
  tp:["Cuanto más fina la masa, más se inflan.",
      "Sírvelos recién fritos."],
  v:"pasteles de queso bolivianos"},
 en:{n:"Bolivian Cheese Pasteles", b:"Fried cheese turnovers that puff up in the oil, dusted with icing sugar. Eaten with api on La Paz mornings.",
  st:["Mix the flour, baking powder, salt and lard. Add the water and knead 5 minutes. Rest 20 minutes.",
      "Divide into 12 balls and roll very thin, to 15 cm.",
      "Put cheese in the centre, fold over and seal with your fingers.",
      "Fry at 180 °C for 2 minutes per side, basting with oil so they puff.",
      "Drain and dust with the icing sugar."],
  tp:["The thinner the dough, the more they puff.",
      "Serve straight from the fryer."],
  v:"bolivian cheese pastel"}},

{id:"mocochinchi", c:"Bolivia", r:"latin-america", m:"drink", t:60, s:8,
 i:[[200,"g","driedfruit","structure","mocochinchi (duraznos deshidratados)","dried whole peaches"],
    [2.5,"l","water","liquid","agua","water"],
    [150,"g","sugar","sweet","azúcar","sugar"],
    [2,"piece","spice","aromatic","ramas de canela","cinnamon sticks"],
    [4,"piece","spice","aromatic","clavos de olor","cloves"],
    [300,"g","ice","liquid","hielo","ice"]],
 es:{n:"Mocochinchi", b:"Refresco de durazno deshidratado con canela. Se vende en todas las plazas de Bolivia, con el durazno en el vaso.",
  st:["Lava los duraznos y remójalos en 1 l de agua 2 horas.",
      "Hiérvelos en esa agua con el resto del agua, la canela y el clavo 40 minutos.",
      "Añade el azúcar y deja enfriar.",
      "Sirve frío con hielo y un durazno en cada vaso."],
  tp:["El durazno se come al final: es parte del refresco.",
      "Se conserva 3 días en la nevera."],
  v:"mocochinchi boliviano"},
 en:{n:"Mocochinchi (Bolivian Dried Peach Drink)", b:"A dried-peach cooler with cinnamon. Sold in every Bolivian plaza, with a peach in the glass.",
  st:["Rinse the peaches and soak them in 1 l of the water for 2 hours.",
      "Boil them in that water with the rest of the water, the cinnamon and cloves for 40 minutes.",
      "Add the sugar and cool.",
      "Serve cold with ice and a peach in each glass."],
  tp:["You eat the peach at the end: it's part of the drink.",
      "It keeps 3 days in the fridge."],
  v:"bolivian mocochinchi"}},

{id:"soo-yosopy", c:"Paraguay", r:"latin-america", m:"soup", t:40, s:6,
 i:[[600,"g","beef","protein","carne de res molida muy fina","very finely minced beef"],
    [1.5,"l","water","liquid","agua fría","cold water"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","pimiento","bell pepper","picado","chopped"],
    [2,"","tomato","aromatic","tomates","tomatoes","picados","chopped"],
    [50,"g","rice","structure","arroz","rice"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"So'o yosopy", b:"Sopa de carne molida finísima deshecha en agua fría, que se cuaja al hervir. Receta guaraní de Paraguay.",
  st:["Mezcla la carne con el agua fría deshaciéndola con las manos. Deja reposar 10 minutos.",
      "Sofríe la cebolla, el pimiento y el tomate en el aceite 8 minutos.",
      "Añade la carne con su agua, el arroz, el orégano y la sal.",
      "Cuece a fuego medio 20 minutos, removiendo sin parar para que la carne no forme grumos."],
  tp:["Pide al carnicero que muela la carne dos veces.",
      "Remueve siempre: si no, la carne se apelmaza."],
  v:"so'o yosopy paraguayo"},
 en:{n:"So'o Yosopy (Paraguayan Beef Soup)", b:"A soup of very finely minced beef broken up in cold water, which sets as it boils. A Guaraní recipe from Paraguay.",
  st:["Mix the beef with the cold water, breaking it up with your hands. Rest 10 minutes.",
      "Cook the onion, pepper and tomato in the oil for 8 minutes.",
      "Add the beef with its water, the rice, oregano and salt.",
      "Simmer over medium heat for 20 minutes, stirring constantly so the beef doesn't clump."],
  tp:["Ask the butcher to mince the beef twice.",
      "Keep stirring or the meat will clump."],
  v:"paraguayan soo yosopy"}},

{id:"pastel-mandio", c:"Paraguay", r:"latin-america", m:"snack", t:70, s:12,
 i:[[1,"kg","cassava","structure","mandioca","cassava","pelada","peeled"],
    [100,"g","cassavastarch","binder","almidón de mandioca","cassava starch"],
    [1,"","egg","binder","huevo","egg"],
    [1,"tsp","salt","salt","sal","salt"],
    [2,"tbsp","oil","fat","aceite (para el relleno)","oil (for the filling)"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [300,"g","beef","protein","carne molida de res","minced beef"],
    [1,"tsp","spice","aromatic","comino","cumin"],
    [750,"ml","oil","fat","aceite para freír","oil for frying"]],
 es:{n:"Pastel mandi'o", b:"Empanadas de masa de mandioca rellenas de carne y fritas. Merienda paraguaya.",
  st:["Cuece la mandioca 25 minutos, retira las fibras y hazla puré en caliente.",
      "Mezcla con el almidón, el huevo y la sal hasta tener una masa.",
      "Sofríe la cebolla en el aceite del relleno 5 minutos. Añade la carne y el comino y cocina 8 minutos.",
      "Forma discos de masa, rellena, dobla y cierra.",
      "Fríe a 180 °C 3 minutos por lado, hasta que estén dorados."],
  tp:["Trabaja la masa con las manos húmedas.",
      "Si la masa se agrieta, añade un poco más de puré caliente."],
  v:"pastel mandio paraguayo"},
 en:{n:"Pastel Mandi'o (Paraguayan Cassava Empanadas)", b:"Cassava-dough turnovers filled with beef and fried. A Paraguayan afternoon snack.",
  st:["Boil the cassava 25 minutes, remove the fibres and mash it hot.",
      "Mix with the starch, egg and salt into a dough.",
      "Cook the onion in the filling oil for 5 minutes. Add the beef and cumin and cook 8 minutes.",
      "Shape discs of dough, fill, fold and seal.",
      "Fry at 180 °C for 3 minutes per side, until golden."],
  tp:["Work the dough with wet hands.",
      "If the dough cracks, add a little more hot mash."],
  v:"paraguayan cassava empanadas"}},

{id:"payagua-mascada", c:"Paraguay", r:"latin-america", m:"main", t:60, s:6,
 i:[[500,"g","cassava","structure","mandioca","cassava","pelada","peeled"],
    [400,"g","beef","protein","carne molida de res","minced beef"],
    [1,"","onion","aromatic","cebolla","onion","picada fina","finely chopped"],
    [1,"","egg","binder","huevo","egg"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [1.5,"tsp","salt","salt","sal","salt"],
    [500,"ml","oil","fat","aceite para freír","oil for frying"]],
 es:{n:"Payagua mascada", b:"Tortitas de mandioca y carne molida, fritas. Comida rápida de casa en Paraguay.",
  st:["Cuece la mandioca 25 minutos, retira las fibras y hazla puré.",
      "Mezcla con la carne cruda, la cebolla, el huevo, el orégano y la sal.",
      "Forma 12 tortitas de 2 cm.",
      "Fríe a 170 °C 4 minutos por lado, hasta que estén doradas y la carne cocida."],
  tp:["No las frías muy calientes: la carne debe cocerse por dentro.",
      "Escúrrelas en papel antes de servir."],
  v:"payagua mascada"},
 en:{n:"Payagua Mascada (Cassava Beef Patties)", b:"Fried patties of cassava and minced beef. Quick home food in Paraguay.",
  st:["Boil the cassava 25 minutes, remove the fibres and mash.",
      "Mix with the raw beef, onion, egg, oregano and salt.",
      "Shape 12 patties 2 cm thick.",
      "Fry at 170 °C for 4 minutes per side, until golden and cooked through."],
  tp:["Don't fry too hot: the beef must cook inside.",
      "Drain on paper before serving."],
  v:"paraguayan payagua mascada"}},

{id:"cocido-quemado", c:"Paraguay", r:"latin-america", m:"drink", t:15, s:4,
 i:[[4,"tbsp","sugar","caramel","azúcar","sugar"],
    [4,"tbsp","herb","aromatic","yerba mate","yerba mate"],
    [1,"l","water","liquid","agua","water"]],
 es:{n:"Cocido quemado", b:"Yerba mate tostada con azúcar caramelizada y hervida en agua. El desayuno de los paraguayos.",
  st:["Pon el azúcar y la yerba en una olla a fuego medio.",
      "Remueve 3 minutos, hasta que el azúcar se funda y caramelice con la yerba.",
      "Añade el agua con cuidado: salpica.",
      "Hierve 3 minutos, cuela y sirve caliente."],
  tp:["Algunos meten una brasa en la olla para quemar el azúcar, que es la forma tradicional.",
      "No dejes que el azúcar se ponga negro o amarga."],
  v:"cocido quemado paraguayo"},
 en:{n:"Cocido Quemado (Burnt-Sugar Yerba Mate)", b:"Yerba mate toasted with caramelised sugar and boiled in water. Paraguay's breakfast drink.",
  st:["Put the sugar and yerba in a pan over medium heat.",
      "Stir 3 minutes, until the sugar melts and caramelises with the yerba.",
      "Add the water carefully: it spits.",
      "Boil 3 minutes, strain and serve hot."],
  tp:["Traditionally a hot ember is dropped in the pot to burn the sugar.",
      "Don't let the sugar go black or it turns bitter."],
  v:"paraguayan cocido quemado"}},

{id:"bunuelos-de-acelga", c:"Uruguay", r:"latin-america", m:"side", t:30, s:4,
 i:[[400,"g","veg","structure","acelga","chard","hervida y picada","blanched and chopped"],
    [2,"","egg","binder","huevos","eggs"],
    [100,"g","apflour","structure","harina de trigo","plain flour"],
    [1,"tsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [80,"ml","milk","liquid","leche","milk"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [30,"g","parmesan","enrich","queso rallado","grated parmesan"],
    [1,"tsp","salt","salt","sal","salt"],
    [500,"ml","oil","fat","aceite para freír","oil for frying"]],
 es:{n:"Buñuelos de acelga", b:"Buñuelos esponjosos de acelga con ajo y queso. Acompañante clásico de la cocina uruguaya.",
  st:["Escurre muy bien la acelga apretándola con las manos.",
      "Bate los huevos con la leche, el ajo, el queso y la sal.",
      "Añade la harina y el polvo de hornear y luego la acelga.",
      "Fríe cucharadas a 175 °C 3 minutos, dándoles la vuelta, hasta que estén dorados.",
      "Escurre en papel."],
  tp:["Si la acelga está húmeda, los buñuelos se deshacen.",
      "También se hacen con espinaca."],
  v:"buñuelos de acelga uruguayos"},
 en:{n:"Buñuelos de Acelga (Chard Fritters)", b:"Fluffy chard fritters with garlic and cheese. A classic Uruguayan side.",
  st:["Squeeze the chard very dry with your hands.",
      "Whisk the eggs with the milk, garlic, cheese and salt.",
      "Add the flour and baking powder, then the chard.",
      "Fry spoonfuls at 175 °C for 3 minutes, turning, until golden.",
      "Drain on paper."],
  tp:["Wet chard makes the fritters fall apart.",
      "Spinach works too."],
  v:"uruguayan chard fritters"}},

{id:"capeletis-a-la-caruso", c:"Uruguay", r:"latin-america", m:"main", t:30, s:4,
 i:[[500,"g","stuffedpasta","structure","capeletis rellenos","cappelletti"],
    [40,"g","butter","fat","mantequilla","butter"],
    [1,"","onion","aromatic","cebolla","onion","picada fina","finely chopped"],
    [200,"g","mushroom","umami","champiñones","mushrooms","en láminas","sliced"],
    [150,"g","ham","protein","jamón cocido","cooked ham","en tiras","in strips"],
    [300,"ml","heavycream","sauce","crema de leche","double cream"],
    [60,"g","parmesan","enrich","queso parmesano rallado","grated parmesan"],
    [1,"pinch","spice","aromatic","nuez moscada","nutmeg"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Capeletis a la Caruso", b:"Pasta rellena en salsa de crema, jamón, champiñones y queso. Inventada en Montevideo en honor al tenor Caruso.",
  st:["Derrite la mantequilla y sofríe la cebolla 5 minutos.",
      "Añade los champiñones y saltea 5 minutos. Añade el jamón.",
      "Añade la crema y la nuez moscada y cuece 5 minutos, hasta que espese un poco. Añade el queso.",
      "Cuece los capeletis en agua con sal según el paquete.",
      "Escúrrelos y mézclalos con la salsa."],
  tp:["Guarda un poco de agua de la pasta por si la salsa espesa demasiado.",
      "Revisa la etiqueta de los capeletis: el relleno varía."],
  v:"capeletis a la caruso uruguayos"},
 en:{n:"Capeletis a la Caruso", b:"Filled pasta in a sauce of cream, ham, mushrooms and cheese. Created in Montevideo in honour of the tenor Caruso.",
  st:["Melt the butter and cook the onion for 5 minutes.",
      "Add the mushrooms and sauté 5 minutes. Add the ham.",
      "Add the cream and nutmeg and simmer 5 minutes, until slightly thickened. Stir in the cheese.",
      "Cook the cappelletti in salted water as the packet says.",
      "Drain and toss with the sauce."],
  tp:["Keep some pasta water in case the sauce gets too thick.",
      "Check the cappelletti label: fillings vary."],
  v:"uruguayan capeletis caruso"}}
];
