module.exports = [
{id:"feijao-caseiro", c:"Brazil", r:"latin-america", m:"side", t:120, s:8,
 i:[[500,"g","legume","protein","frijoles carioca o pintos","carioca or pinto beans","remojados 8 horas","soaked 8 hours"],
    [2,"l","water","liquid","agua","water"],
    [2,"leaf","herb","aromatic","hojas de laurel","bay leaves"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [4,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Feijão caseiro", b:"El frijol de todos los días en Brasil, con ajo frito y laurel. Va con arroz blanco en cada almuerzo.",
  st:["Cuece los frijoles en el agua con el laurel 90 minutos, hasta que estén tiernos.",
      "Fríe la cebolla y el ajo en el aceite 5 minutos, hasta que estén dorados.",
      "Añade 2 cucharones de frijoles al sofrito, aplástalos y devuelve todo a la olla.",
      "Añade la sal y cuece 15 minutos más, hasta que el caldo espese.",
      "Retira el laurel y sirve con arroz."],
  tp:["Aplastar parte de los frijoles es lo que espesa el caldo.",
      "En olla a presión, 30 minutos bastan en el primer paso."],
  v:"feijão caseiro receita"},
 en:{n:"Feijão (Everyday Brazilian Beans)", b:"The everyday bean of Brazil, with fried garlic and bay. Served with white rice at every lunch.",
  st:["Cook the beans in the water with the bay for 90 minutes, until tender.",
      "Fry the onion and garlic in the oil for 5 minutes, until golden.",
      "Add 2 ladles of beans to the pan, mash them and tip everything back into the pot.",
      "Add the salt and cook 15 minutes more, until the liquid thickens.",
      "Remove the bay and serve with rice."],
  tp:["Mashing some of the beans is what thickens the liquid.",
      "In a pressure cooker, 30 minutes is enough for the first step."],
  v:"brazilian beans recipe"}},

{id:"galinhada", c:"Brazil", r:"latin-america", m:"main", t:60, s:6,
 i:[[1.2,"kg","chicken","protein","muslos y contramuslos de pollo","chicken thighs and drumsticks"],
    [3,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [1,"","citrus","acid","limón","lime","en jugo","juiced"],
    [2,"tsp","salt","salt","sal","salt"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"tsp","spice","aromatic","cúrcuma","turmeric"],
    [2,"","tomato","sauce","tomates","tomatoes","picados","chopped"],
    [400,"g","rice","structure","arroz","rice"],
    [1,"l","water","liquid","agua caliente","hot water"],
    [150,"g","corn","structure","granos de maíz","sweetcorn kernels"],
    [1,"handful","herb","garnish","perejil","parsley","picados","chopped"]],
 es:{n:"Galinhada", b:"Arroz amarillo cocido con pollo en una sola olla. Plato de Goiás, para domingos y fiestas.",
  st:["Adoba el pollo con el ajo, el limón y la sal 30 minutos.",
      "Dora el pollo en el aceite 10 minutos. Añade la cebolla y la cúrcuma y cuece 3 minutos.",
      "Añade el tomate y cuece 5 minutos.",
      "Añade el arroz, mezcla y añade el agua caliente. Tapa y cuece 20 minutos a fuego bajo.",
      "Añade el maíz, tapa 5 minutos y termina con las hierbas."],
  tp:["Debe quedar húmedo; si se seca, añade un poco de agua caliente.",
      "En Goiás se usa azafrán de la tierra, que es cúrcuma."],
  v:"galinhada goiana receita"},
 en:{n:"Galinhada (Brazilian Chicken and Rice)", b:"Yellow rice cooked with chicken in one pot. A dish from Goiás for Sundays and parties.",
  st:["Season the chicken with the garlic, lime and salt for 30 minutes.",
      "Brown the chicken in the oil for 10 minutes. Add the onion and turmeric and cook 3 minutes.",
      "Add the tomato and cook 5 minutes.",
      "Add the rice, stir and add the hot water. Cover and cook 20 minutes on low.",
      "Add the corn, cover for 5 minutes and finish with the herbs."],
  tp:["It should stay moist; if it dries, add a little hot water.",
      "In Goiás they use 'saffron of the land', which is turmeric."],
  v:"galinhada recipe"}},

{id:"virado-a-paulista", c:"Brazil", r:"latin-america", m:"main", t:60, s:4,
 i:[[400,"g","legume","protein","frijoles cocidos","cooked beans","con su caldo","with their liquid"],
    [100,"g","cassava","structure","harina de mandioca","cassava flour"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [4,"","pork","protein","chuletas de cerdo","pork chops"],
    [200,"g","sausage","protein","linguiça (salchicha de cerdo)","linguiça (pork sausage)"],
    [300,"g","veg","structure","col rizada (couve)","collard greens (couve)","en tiras finas","finely shredded"],
    [4,"","egg","protein","huevos","eggs"],
    [2,"","plantain","serve","plátanos (bananas)","bananas","fritas en rodajas","sliced and fried"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Virado à paulista", b:"Tutu de frijol con chuleta, linguiça, col, huevo frito y banana. El plato de los lunes en São Paulo.",
  st:["Sofríe la cebolla y el ajo en el aceite 4 minutos. Añade los frijoles con su caldo y aplasta ligeramente.",
      "Añade la harina de mandioca poco a poco, removiendo, hasta que espese como un puré. Sala.",
      "Asa las chuletas y la linguiça en una sartén 10 minutos, hasta que estén doradas.",
      "Saltea la col en la misma sartén 2 minutos y fríe los huevos.",
      "Sirve el tutu con la chuleta, la linguiça, la col, el huevo y la banana frita."],
  tp:["Fríe las bananas en el aceite de las chuletas: toman sabor.",
      "Es un plato contundente: con arroz blanco al lado queda completo."],
  v:"virado à paulista receita"},
 en:{n:"Virado à Paulista (São Paulo Monday Plate)", b:"Bean tutu with pork chop, linguiça, greens, fried egg and banana. São Paulo's Monday dish.",
  st:["Cook the onion and garlic in the oil for 4 minutes. Add the beans with their liquid and mash lightly.",
      "Add the cassava flour a little at a time, stirring, until as thick as mash. Salt.",
      "Fry the chops and linguiça in a frying pan for 10 minutes, until browned.",
      "Toss the greens in the same pan for 2 minutes and fry the eggs.",
      "Serve the tutu with the chop, linguiça, greens, egg and fried banana."],
  tp:["Fry the bananas in the fat left from the chops: they pick up flavour.",
      "It's a hearty plate: with white rice on the side it's complete."],
  v:"virado a paulista recipe"}},

{id:"cuscuz-nordestino", c:"Brazil", r:"latin-america", m:"breakfast", t:25, s:4,
 i:[[250,"g","cornmeal","structure","flocão de maíz (harina de maíz en copos)","flaked cornmeal (flocão)"],
    [200,"ml","water","liquid","agua","water"],
    [1,"tsp","salt","salt","sal","salt"],
    [30,"g","butter","fat","mantequilla","butter"]],
 es:{n:"Cuscuz nordestino", b:"Copos de maíz humedecidos y cocidos al vapor en cuscuzera, con mantequilla. El desayuno del nordeste de Brasil.",
  st:["Mezcla el flocão con la sal y el agua poco a poco, hasta que parezca arena húmeda.",
      "Deja reposar 10 minutos.",
      "Pon agua en la base de la cuscuzera o de una olla vaporera y llena la parte de arriba con el maíz sin apretar.",
      "Tapa y cuece al vapor 10 minutos, hasta que suba el aroma a maíz.",
      "Desmolda y sirve caliente con la mantequilla por encima."],
  tp:["No aprietes el maíz en la cuscuzera o queda pesado.",
      "Se acompaña con huevo frito, queso coalho o carne seca."],
  v:"cuscuz nordestino receita"},
 en:{n:"Cuscuz Nordestino (Steamed Corn Cake)", b:"Flaked corn moistened and steamed in a cuscuzeira, with butter. Breakfast in northeastern Brazil.",
  st:["Mix the flocão with the salt and add the water gradually until it looks like damp sand.",
      "Leave 10 minutes.",
      "Put water in the base of the cuscuzeira or a steamer and loosely fill the top with the corn.",
      "Cover and steam 10 minutes, until it smells of corn.",
      "Turn out and serve hot with the butter on top."],
  tp:["Don't pack the corn in the steamer or it turns heavy.",
      "Served with fried egg, coalho cheese or dried beef."],
  v:"cuscuz nordestino recipe"}},

{id:"canjica", c:"Brazil", r:"latin-america", m:"sweet", t:180, s:8,
 i:[[500,"g","hominy","structure","canjica (maíz blanco pelado)","white hominy corn (canjica)","remojada 12 horas","soaked 12 hours"],
    [2,"l","water","liquid","agua","water"],
    [1,"l","milk","liquid","leche","milk"],
    [395,"g","condensedmilk","sweet","leche condensada","condensed milk"],
    [200,"ml","coconutmilk","liquid","leche de coco","coconut milk"],
    [2,"","spice","aromatic","ramas de canela","cinnamon sticks"],
    [100,"g","peanut","garnish","maní tostado","roasted peanuts","picado","chopped"]],
 es:{n:"Canjica", b:"Maíz blanco cocido en leche con coco, canela y maní. Postre de las fiestas juninas en Brasil.",
  st:["Cuece la canjica en el agua 2 horas, hasta que esté tierna. Añade agua si baja.",
      "Escurre la mayor parte del agua.",
      "Añade la leche, la leche condensada, la leche de coco y la canela y cuece 30 minutos, removiendo, hasta que espese.",
      "Añade la mitad del maní.",
      "Sirve caliente o fría con el resto del maní por encima."],
  tp:["En olla a presión el primer paso tarda 40 minutos.",
      "Espesa al enfriar; aligérala con leche."],
  v:"canjica festa junina receita"},
 en:{n:"Canjica (Hominy Pudding)", b:"White hominy cooked in milk with coconut, cinnamon and peanuts. A dessert of Brazil's June festivals.",
  st:["Boil the hominy in the water for 2 hours, until tender. Top up the water if needed.",
      "Drain off most of the water.",
      "Add the milk, condensed milk, coconut milk and cinnamon and cook 30 minutes, stirring, until thick.",
      "Stir in half the peanuts.",
      "Serve hot or cold with the rest of the peanuts on top."],
  tp:["In a pressure cooker the first step takes 40 minutes.",
      "It thickens as it cools; loosen with milk."],
  v:"canjica recipe"}},

{id:"pamonha", c:"Brazil", r:"latin-america", m:"snack", t:90, s:12,
 i:[[10,"","corn","structure","mazorcas de maíz tierno con sus hojas","young corn cobs with their husks"],
    [200,"ml","coconutmilk","liquid","leche de coco","coconut milk"],
    [120,"g","sugar","sweet","azúcar","sugar"],
    [1,"pinch","salt","salt","sal","salt"]],
 es:{n:"Pamonha dulce", b:"Pasta de maíz tierno con coco y azúcar, envuelta en su hoja y hervida. Merienda de las fiestas de junio.",
  st:["Saca las hojas con cuidado y guarda las mejores. Desgrana el maíz.",
      "Licúa los granos con la leche de coco hasta tener una pasta espesa.",
      "Mezcla con el azúcar y la sal.",
      "Dobla dos hojas en forma de bolsa, rellena con 4 cucharadas de pasta y ata con tiras de hoja.",
      "Cuece en agua hirviendo 40 minutos."],
  tp:["El agua debe estar hirviendo al meter las pamonhas o se deshacen.",
      "Se comen calientes o frías."],
  v:"pamonha doce receita"},
 en:{n:"Pamonha (Sweet Corn Parcels)", b:"A paste of young corn with coconut and sugar, wrapped in husk and boiled. A June-festival snack.",
  st:["Carefully remove the husks and keep the best. Cut off the kernels.",
      "Blend the kernels with the coconut milk to a thick paste.",
      "Mix with the sugar and salt.",
      "Fold two husks into a pouch, fill with 4 tablespoons of paste and tie with strips of husk.",
      "Boil in water for 40 minutes."],
  tp:["The water must be boiling when the pamonhas go in or they fall apart.",
      "Eat them warm or cold."],
  v:"pamonha recipe"}},

{id:"bolinho-de-chuva", c:"Brazil", r:"latin-america", m:"sweet", t:30, s:6,
 i:[[250,"g","apflour","structure","harina de trigo","plain flour"],
    [2,"","egg","binder","huevos","eggs"],
    [100,"g","sugar","sweet","azúcar","sugar"],
    [200,"ml","milk","liquid","leche","milk"],
    [1,"tbsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [1,"pinch","salt","salt","sal","salt"],
    [1,"l","oil","fat","aceite para freír","oil for frying"],
    [100,"g","sugar","garnish","azúcar para rebozar","sugar for coating"],
    [2,"tsp","spice","garnish","canela molida","ground cinnamon"]],
 es:{n:"Bolinho de chuva", b:"Buñuelos de masa simple fritos y rebozados en azúcar con canela. Lo que se hace en casa en las tardes de lluvia.",
  st:["Bate los huevos con 100 g de azúcar. Añade la leche.",
      "Añade la harina, el polvo de hornear y la sal y mezcla hasta tener una masa espesa.",
      "Calienta el aceite a 170 °C.",
      "Deja caer cucharadas de masa en el aceite y fríe 3 minutos, hasta que estén dorados.",
      "Escurre y reboza en el azúcar mezclado con la canela."],
  tp:["El aceite no debe estar muy caliente o se queman por fuera y quedan crudos dentro.",
      "Usa dos cucharas para que caigan redondos."],
  v:"bolinho de chuva receita"},
 en:{n:"Bolinho de Chuva (Brazilian Rainy-Day Doughnuts)", b:"Simple fried dough balls rolled in cinnamon sugar. What gets made at home on rainy afternoons.",
  st:["Whisk the eggs with 100 g of sugar. Add the milk.",
      "Add the flour, baking powder and salt and mix to a thick batter.",
      "Heat the oil to 170 °C.",
      "Drop spoonfuls of batter into the oil and fry 3 minutes, until golden.",
      "Drain and roll in the sugar mixed with the cinnamon."],
  tp:["The oil shouldn't be too hot or they burn outside and stay raw inside.",
      "Use two spoons so they drop in round."],
  v:"bolinho de chuva recipe"}},

{id:"mousse-de-maracuja", c:"Brazil", r:"latin-america", m:"sweet", t:15, s:8,
 i:[[395,"g","condensedmilk","sweet","leche condensada","condensed milk"],
    [300,"ml","cream","aerate","crema de leche","cream"],
    [200,"ml","fruit","acid","jugo concentrado de maracuyá","concentrated passion fruit juice"],
    [2,"","fruit","garnish","maracuyás","passion fruits","la pulpa","the pulp"]],
 es:{n:"Mousse de maracuyá", b:"Mousse de tres ingredientes que cuaja con la acidez del maracuyá. El postre rápido de Brasil.",
  st:["Licúa la leche condensada, la crema y el jugo de maracuyá 3 minutos, hasta que espese.",
      "Reparte en 8 copas.",
      "Refrigera al menos 3 horas.",
      "Cubre con la pulpa de maracuyá con sus semillas.",
      "Sirve frío."],
  tp:["El jugo debe ser concentrado, sin agua añadida, o no cuaja.",
      "Si queda líquido tras licuar, bate 1 minuto más."],
  v:"mousse de maracujá receita"},
 en:{n:"Mousse de Maracujá (Passion Fruit Mousse)", b:"A three-ingredient mousse that sets with the acidity of passion fruit. Brazil's quick dessert.",
  st:["Blend the condensed milk, cream and passion fruit juice for 3 minutes, until thick.",
      "Divide between 8 glasses.",
      "Refrigerate at least 3 hours.",
      "Top with the passion fruit pulp and seeds.",
      "Serve cold."],
  tp:["The juice must be concentrated, with no added water, or it won't set.",
      "If it's still runny after blending, blend 1 minute more."],
  v:"passion fruit mousse recipe"}},

{id:"tutu-de-feijao", c:"Brazil", r:"latin-america", m:"side", t:30, s:6,
 i:[[100,"g","bacon","protein","tocino ahumado","smoked bacon","en dados","diced"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [600,"g","legume","protein","frijoles cocidos","cooked beans","con 300 ml de su caldo","with 300 ml of their liquid"],
    [120,"g","cassava","structure","harina de mandioca","cassava flour"],
    [1,"tsp","salt","salt","sal","salt"],
    [2,"","scallion","garnish","cebolletas","scallions","picadas","chopped"]],
 es:{n:"Tutu de feijão", b:"Frijoles licuados espesados con harina de mandioca y tocino frito. De Minas Gerais.",
  st:["Fríe el tocino 5 minutos en una olla. Añade la cebolla y el ajo y cuece 4 minutos.",
      "Licúa los frijoles con su caldo.",
      "Añade el puré de frijoles a la olla y calienta.",
      "Añade la harina de mandioca poco a poco, removiendo, hasta que espese como un puré firme. Sala.",
      "Termina con las cebolletas."],
  tp:["Añade la harina despacio: espesa rápido.",
      "Se sirve con chuleta, col salteada y huevo."],
  v:"tutu de feijão mineiro"},
 en:{n:"Tutu de Feijão (Brazilian Bean Mash)", b:"Blended beans thickened with cassava flour and crisp bacon. From Minas Gerais.",
  st:["Fry the bacon for 5 minutes in a pot. Add the onion and garlic and cook 4 minutes.",
      "Blend the beans with their liquid.",
      "Add the bean purée to the pot and heat.",
      "Add the cassava flour a little at a time, stirring, until as thick as a firm mash. Salt.",
      "Finish with the scallions."],
  tp:["Add the flour slowly: it thickens fast.",
      "Served with pork chop, sautéed greens and egg."],
  v:"tutu de feijao recipe"}},

{id:"romeu-e-julieta", c:"Brazil", r:"latin-america", m:"sweet", t:5, s:4,
 i:[[200,"g","guavapaste","sweet","goiabada (pasta de guayaba)","goiabada (guava paste)","en lonchas de 1 cm","in 1 cm slices"],
    [200,"g","cheese","protein","queso Minas fresco o queso blanco","Minas or fresh white cheese","en lonchas de 1 cm","in 1 cm slices"]],
 es:{n:"Romeu e Julieta", b:"Queso blanco fresco con goiabada. El postre más simple y querido de Brasil.",
  st:["Corta la goiabada y el queso en lonchas del mismo tamaño.",
      "Pon una loncha de goiabada sobre cada loncha de queso.",
      "Sirve a temperatura ambiente.",
      "Si quieres, calienta 1 minuto en una sartén para que el queso se ablande.",
      "Sirve enseguida."],
  tp:["El contraste salado y dulce es la gracia; usa un queso suave.",
      "Con goiabada cascão, más rústica, queda aún mejor."],
  v:"romeu e julieta sobremesa"},
 en:{n:"Romeu e Julieta (Cheese and Guava Paste)", b:"Fresh white cheese with guava paste. Brazil's simplest, best-loved dessert.",
  st:["Cut the guava paste and cheese into slices of the same size.",
      "Lay a slice of guava paste on each slice of cheese.",
      "Serve at room temperature.",
      "If you like, warm 1 minute in a frying pan to soften the cheese.",
      "Serve at once."],
  tp:["The salty-sweet contrast is the point; use a mild cheese.",
      "With rustic goiabada cascão it's even better."],
  v:"romeu e julieta dessert"}}
];
