module.exports = [
{id:"coxinha", c:"Brazil", r:"latin-america", m:"snack", t:120, s:24,
 i:[[500,"g","chicken","protein","pechuga de pollo","chicken breast"],
    [1,"l","water","liquid","agua","water"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"tbsp","tomatopaste","umami","pasta de tomate","tomato paste"],
    [150,"g","creamcheese","enrich","requesón cremoso (requeijão)","requeijão (Brazilian cream cheese)"],
    [1,"handful","herb","aromatic","perejil","parsley","picado","chopped"],
    [2,"tsp","salt","salt","sal","salt"],
    [30,"g","butter","fat","mantequilla","butter"],
    [300,"g","apflour","structure","harina de trigo","plain flour"],
    [150,"g","breadcrumbs","dredge","pan rallado","breadcrumbs"],
    [1,"l","oil","fat","aceite para freír","oil for frying"]],
 es:{n:"Coxinhas", b:"Croquetas brasileñas con forma de muslo, masa de harina cocida y relleno de pollo con requeijão.",
  st:["Cuece el pollo en el agua con 1 cucharadita de sal 20 minutos. Sácalo, desmenúzalo y guarda 500 ml del agua de cocción.",
      "Sofríe la cebolla y el ajo en el aceite 5 minutos. Añade el pollo, la pasta de tomate y las hierbas y cuece 5 minutos. Enfría y mezcla con el requeijão.",
      "Hierve el agua reservada con la mantequilla y el resto de la sal. Echa la harina de golpe y remueve 3 minutos, hasta que la masa se despegue de la olla. Enfría 15 minutos.",
      "Amasa hasta que esté lisa. Toma bolitas de 40 g, ahuécalas, rellena con una cucharada de pollo y cierra en forma de gota.",
      "Moja cada coxinha en agua, pásala por el pan rallado y fríe a 180 °C durante 4 minutos, hasta que esté dorada."],
  tp:["Amasa la masa todavía tibia; fría se agrieta.",
      "Se pueden congelar crudas ya empanizadas y freír sin descongelar, 1 minuto más."],
  v:"coxinha receta brasileña"},
 en:{n:"Coxinhas (Brazilian Chicken Croquettes)", b:"Brazilian croquettes shaped like a drumstick, with a cooked-flour dough and a chicken and requeijão filling.",
  st:["Simmer the chicken in the water with 1 teaspoon of salt for 20 minutes. Lift out, shred and keep 500 ml of the cooking water.",
      "Cook the onion and garlic in the oil for 5 minutes. Add the chicken, tomato paste and herbs and cook 5 minutes. Cool and mix with the requeijão.",
      "Boil the reserved water with the butter and the rest of the salt. Tip in the flour all at once and stir 3 minutes, until the dough leaves the pot. Cool 15 minutes.",
      "Knead until smooth. Take 40 g balls, hollow them, fill with a spoonful of chicken and close into a teardrop.",
      "Dip each coxinha in water, roll in the breadcrumbs and fry at 180 °C for 4 minutes, until golden."],
  tp:["Knead the dough while still warm; cold, it cracks.",
      "They freeze raw once crumbed; fry from frozen, 1 minute longer."],
  v:"coxinha recipe"}},

{id:"farofa", c:"Brazil", r:"latin-america", m:"side", t:15, s:6,
 i:[[40,"g","butter","fat","mantequilla","butter"],
    [100,"g","bacon","protein","tocino ahumado","smoked bacon","en dados","diced"],
    [1,"","onion","aromatic","cebolla","onion","picada fina","finely chopped"],
    [250,"g","cassava","structure","harina de mandioca tostada","toasted cassava flour (farinha de mandioca)"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"handful","herb","garnish","perejil","parsley","picado","chopped"]],
 es:{n:"Farofa", b:"Harina de mandioca tostada en mantequilla con tocino y cebolla. Crujiente, salada, va con todo en Brasil.",
  st:["Fríe el tocino en una sartén 5 minutos, hasta que suelte la grasa.",
      "Añade la mantequilla y la cebolla y cuece 4 minutos.",
      "Añade la harina de mandioca poco a poco, removiendo, y tuesta 4 minutos a fuego medio hasta que huela a nuez.",
      "Sala, termina con el perejil y sirve."],
  tp:["Remueve sin parar: la harina de mandioca pasa de dorada a quemada muy rápido.",
      "Se sirve espolvoreada sobre frijoles o carne asada."],
  v:"farofa receta"},
 en:{n:"Farofa (Toasted Cassava Flour)", b:"Cassava flour toasted in butter with bacon and onion. Crunchy, salty, served with everything in Brazil.",
  st:["Fry the bacon in a frying pan for 5 minutes, until it renders its fat.",
      "Add the butter and onion and cook 4 minutes.",
      "Add the cassava flour a little at a time, stirring, and toast 4 minutes over medium heat until it smells nutty.",
      "Salt, finish with the parsley and serve."],
  tp:["Stir constantly: cassava flour goes from golden to burnt very fast.",
      "It is sprinkled over beans or grilled meat."],
  v:"brazilian farofa recipe"}},

{id:"vinagrete", c:"Brazil", r:"latin-america", m:"sauce", t:15, s:6,
 i:[[3,"","tomato","structure","tomates firmes","firm tomatoes","sin semillas, en dados pequeños","seeded, finely diced"],
    [1,"","onion","aromatic","cebolla","onion","en dados pequeños","finely diced"],
    [1,"","bellpepper","structure","pimiento verde","green bell pepper","en dados pequeños","finely diced"],
    [1,"handful","herb","aromatic","perejil","parsley","picado","chopped"],
    [3,"tbsp","whitevinegar","acid","vinagre blanco","white vinegar"],
    [4,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Vinagrete brasileño", b:"Tomate, cebolla y pimiento picados en vinagre y aceite. El acompañante obligado del churrasco.",
  st:["Mezcla el tomate, la cebolla, el pimiento y el perejil en un bol.",
      "Añade el vinagre, el aceite y la sal y mezcla.",
      "Deja reposar 10 minutos antes de servir."],
  tp:["Pica todo del mismo tamaño pequeño; así cada cucharada lleva de todo.",
      "Se come el mismo día; al día siguiente el tomate se ablanda."],
  v:"vinagrete para churrasco receta"},
 en:{n:"Brazilian Vinagrete", b:"Diced tomato, onion and pepper in vinegar and oil. The must-have partner for churrasco.",
  st:["Mix the tomato, onion, pepper and parsley in a bowl.",
      "Add the vinegar, oil and salt and mix.",
      "Leave 10 minutes before serving."],
  tp:["Dice everything the same small size so each spoonful has a bit of all of it.",
      "Eat it the same day; by the next day the tomato goes soft."],
  v:"brazilian vinagrete recipe"}},

{id:"feijao-tropeiro", c:"Brazil", r:"latin-america", m:"main", t:40, s:6,
 i:[[150,"g","bacon","protein","tocino ahumado","smoked bacon","en dados","diced"],
    [200,"g","sausage","protein","linguiça (salchicha de cerdo)","linguiça (pork sausage)","en rodajas","sliced"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [3,"","egg","protein","huevos","eggs"],
    [600,"g","legume","protein","frijoles pintos cocidos","cooked pinto beans","escurridos","drained"],
    [150,"g","cassava","structure","harina de mandioca","cassava flour (farinha de mandioca)"],
    [150,"g","veg","structure","col rizada (couve)","collard greens (couve)","en tiras finas","finely shredded"],
    [3,"","scallion","garnish","cebolletas","scallions","picadas","chopped"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Feijão tropeiro", b:"Frijoles salteados con tocino, linguiça, huevo y harina de mandioca. El plato de los arrieros de Minas Gerais.",
  st:["Fríe el tocino 5 minutos en una sartén grande. Añade la linguiça y dora 5 minutos.",
      "Añade la cebolla y el ajo y cuece 4 minutos. Empuja a un lado, rompe los huevos en el hueco y revuélvelos 2 minutos.",
      "Añade los frijoles y saltea 3 minutos.",
      "Añade la harina de mandioca poco a poco, mezclando, hasta que absorba la grasa y quede suelto.",
      "Saltea la col en la misma sartén 2 minutos, sala y termina con las cebolletas."],
  tp:["Los frijoles deben estar bien escurridos; si están mojados, la harina se apelmaza.",
      "La col se añade al final para que quede verde y crujiente."],
  v:"feijão tropeiro receita"},
 en:{n:"Feijão Tropeiro (Drover's Beans)", b:"Beans tossed with bacon, linguiça, egg and cassava flour. The dish of the mule drivers of Minas Gerais.",
  st:["Fry the bacon for 5 minutes in a large frying pan. Add the linguiça and brown 5 minutes.",
      "Add the onion and garlic and cook 4 minutes. Push to one side, crack the eggs into the space and scramble 2 minutes.",
      "Add the beans and toss 3 minutes.",
      "Add the cassava flour a little at a time, mixing, until it soaks up the fat and turns loose.",
      "Toss the greens in the same pan for 2 minutes, salt and finish with the scallions."],
  tp:["The beans must be well drained; if wet, the flour goes lumpy.",
      "The greens go in last so they stay green and crisp."],
  v:"feijao tropeiro recipe"}},

{id:"bobo-de-camarao", c:"Brazil", r:"latin-america", m:"main", t:60, s:6,
 i:[[600,"g","cassava","structure","yuca","cassava","pelada, en trozos","peeled, in chunks"],
    [1,"l","water","liquid","agua","water"],
    [800,"g","shrimp","protein","camarones","shrimp","pelados y limpios","peeled and deveined"],
    [2,"","citrus","acid","limones","limes","en jugo","juiced"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"tsp","salt","salt","sal","salt"],
    [3,"tbsp","oil","fat","aceite de palma (dendê)","palm oil (dendê)"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","pimiento rojo","red bell pepper","picado","chopped"],
    [2,"","tomato","sauce","tomates","tomatoes","picados","chopped"],
    [400,"ml","coconutmilk","liquid","leche de coco","coconut milk"],
    [1,"handful","herb","garnish","cilantro","cilantro","picado","chopped"]],
 es:{n:"Bobó de camarão", b:"Camarones en una crema de yuca, leche de coco y aceite de dendê. Un clásico de Bahía.",
  st:["Cuece la yuca en el agua 25 minutos, hasta que esté muy tierna. Quita la fibra central y lícuala con 250 ml del agua de cocción.",
      "Mezcla los camarones con el jugo de limón, el ajo y 1 cucharadita de sal. Deja 15 minutos.",
      "Calienta el dendê y sofríe la cebolla, el pimiento y el tomate 8 minutos.",
      "Añade la crema de yuca y la leche de coco y cuece 5 minutos a fuego bajo, removiendo.",
      "Añade los camarones con su marinada y cuece 4 minutos, hasta que estén rosados. Sala y termina con el cilantro."],
  tp:["No cuezas los camarones más de 4 minutos o se endurecen.",
      "El dendê da el color naranja y el sabor bahiano; con aceite neutro sale más pálido pero bueno."],
  v:"bobó de camarão receita"},
 en:{n:"Bobó de Camarão (Shrimp in Cassava Cream)", b:"Shrimp in a cream of cassava, coconut milk and dendê oil. A classic from Bahia.",
  st:["Boil the cassava in the water for 25 minutes, until very tender. Remove the woody core and blend with 250 ml of the cooking water.",
      "Mix the shrimp with the lime juice, garlic and 1 teaspoon of salt. Leave 15 minutes.",
      "Heat the dendê and cook the onion, pepper and tomato for 8 minutes.",
      "Add the cassava cream and coconut milk and cook 5 minutes over low heat, stirring.",
      "Add the shrimp with their marinade and cook 4 minutes, until pink. Salt and finish with the cilantro."],
  tp:["Don't cook the shrimp more than 4 minutes or they toughen.",
      "Dendê gives the orange colour and Bahian flavour; with neutral oil it's paler but still good."],
  v:"bobo de camarao recipe"}},

{id:"picanha", c:"Brazil", r:"latin-america", m:"main", t:40, s:6,
 i:[[1.2,"kg","beef","protein","picaña con su capa de grasa","picanha (rump cap) with its fat cap"],
    [2,"tbsp","salt","salt","sal gruesa","coarse salt"],
    [1,"tsp","pepper","aromatic","pimienta negra molida","ground black pepper"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado fino","finely chopped"],
    [4,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [1,"handful","herb","garnish","perejil","parsley","picado","chopped"]],
 es:{n:"Picaña a la brasa", b:"El corte estrella del churrasco: rodajas gruesas con su grasa, solo sal gruesa y fuego fuerte.",
  st:["Corta la picaña a favor de la veta en filetes de 3 cm y dóblalos en forma de C con la grasa por fuera.",
      "Cubre con la sal gruesa y ensártalos en brochetas.",
      "Asa a fuego fuerte con la grasa hacia el fuego 5 minutos, luego 4 minutos por cada lado para término medio.",
      "Mezcla el ajo, el aceite, el perejil y la pimienta.",
      "Deja reposar la carne 5 minutos, córtala en láminas finas contra la veta y rocía con el aceite de ajo."],
  tp:["Sacude el exceso de sal antes de cortar.",
      "Sirve con vinagrete brasileño."],
  v:"picanha na brasa"},
 en:{n:"Grilled Picanha", b:"The star cut of churrasco: thick slices with their fat cap, just coarse salt and strong fire.",
  st:["Cut the picanha with the grain into 3 cm steaks and curl them into a C with the fat on the outside.",
      "Cover with the coarse salt and thread onto skewers.",
      "Grill over high heat with the fat facing the fire for 5 minutes, then 4 minutes each side for medium.",
      "Mix the garlic, oil, parsley and pepper.",
      "Rest the meat 5 minutes, slice thinly against the grain and drizzle with the garlic oil."],
  tp:["Shake off the excess salt before slicing.",
      "Serve with Brazilian vinagrete."],
  v:"picanha recipe"}},

{id:"escondidinho", c:"Brazil", r:"latin-america", m:"main", t:90, s:6, o:200,
 i:[[500,"g","driedmeat","protein","carne seca (tasajo)","carne seca (salted dried beef)","desalada 24 horas","desalted for 24 hours"],
    [1,"kg","cassava","structure","yuca","cassava","pelada, en trozos","peeled, in chunks"],
    [50,"g","butter","fat","mantequilla","butter"],
    [200,"ml","milk","moisture","leche","milk"],
    [150,"g","creamcheese","enrich","requesón cremoso (requeijão)","requeijão (Brazilian cream cheese)"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"","tomato","sauce","tomates","tomatoes","picados","chopped"],
    [80,"g","cheese","glaze","queso rallado (parmesano o coalho)","grated cheese (parmesan or coalho)"],
    [3,"","scallion","garnish","cebolletas","scallions","picadas","chopped"]],
 es:{n:"Escondidinho de carne seca", b:"Carne seca desmenuzada escondida bajo un puré de yuca cremoso y gratinado. Comida de domingo del nordeste.",
  st:["Cuece la carne desalada en agua 40 minutos. Escúrrela y desmenúzala.",
      "Cuece la yuca en agua 25 minutos, quita la fibra central y haz un puré con la mantequilla, la leche y el requeijão.",
      "Sofríe la cebolla y el ajo en el aceite 5 minutos. Añade el tomate y la carne y cuece 8 minutos.",
      "En una fuente, pon la carne, cubre con el puré y espolvorea el queso.",
      "Hornea a 200 °C durante 20 minutos, hasta que esté dorado. Termina con las cebolletas."],
  tp:["Prueba la carne después de cocerla; si sigue muy salada, hiérvela 10 minutos más en agua limpia.",
      "No hace falta sal extra: la carne seca ya la aporta."],
  v:"escondidinho de carne seca receita"},
 en:{n:"Escondidinho (Dried Beef and Cassava Bake)", b:"Shredded dried beef hidden under a creamy, gratinéed cassava mash. Northeastern Sunday food.",
  st:["Simmer the desalted meat in water for 40 minutes. Drain and shred.",
      "Boil the cassava in water for 25 minutes, remove the woody core and mash with the butter, milk and requeijão.",
      "Cook the onion and garlic in the oil for 5 minutes. Add the tomato and the meat and cook 8 minutes.",
      "In a dish, spread the meat, cover with the mash and sprinkle with the cheese.",
      "Bake at 200 °C for 20 minutes, until golden. Finish with the scallions."],
  tp:["Taste the meat after simmering; if still very salty, boil it 10 minutes more in fresh water.",
      "No extra salt needed: the dried beef brings it."],
  v:"escondidinho de carne seca recipe"}},

{id:"pudim", c:"Brazil", r:"latin-america", m:"sweet", t:80, s:10, o:160,
 i:[[150,"g","sugar","caramel","azúcar para el caramelo","sugar for the caramel"],
    [60,"ml","water","liquid","agua","water"],
    [395,"g","condensedmilk","sweet","leche condensada","condensed milk"],
    [395,"ml","milk","liquid","leche","milk"],
    [3,"","egg","set","huevos","eggs"]],
 es:{n:"Pudim de leite", b:"El flan brasileño de leche condensada: denso, liso y bañado en caramelo.",
  st:["Cuece el azúcar con el agua sin remover hasta tener un caramelo ámbar. Viértelo en un molde de corona de 22 cm y gíralo para cubrir.",
      "Licúa la leche condensada, la leche y los huevos 1 minuto. Deja reposar 5 minutos para que baje la espuma.",
      "Vierte en el molde y cubre con papel de aluminio.",
      "Hornea al baño María a 160 °C durante 60 minutos, hasta que cuaje con un temblor en el centro.",
      "Enfría y refrigera al menos 6 horas. Desmolda pasando un cuchillo por el borde."],
  tp:["Usa la lata de leche condensada vacía para medir la leche.",
      "Los agujeritos salen si el horno está demasiado fuerte; baja 10 grados la próxima vez."],
  v:"pudim de leite condensado receita"},
 en:{n:"Pudim (Brazilian Flan)", b:"Brazil's condensed-milk flan: dense, smooth and bathed in caramel.",
  st:["Cook the sugar with the water without stirring to an amber caramel. Pour into a 22 cm ring mould and swirl to coat.",
      "Blend the condensed milk, milk and eggs for 1 minute. Leave 5 minutes for the foam to settle.",
      "Pour into the mould and cover with foil.",
      "Bake in a water bath at 160 °C for 60 minutes, until set with a wobble in the centre.",
      "Cool and refrigerate at least 6 hours. Turn out after running a knife round the edge."],
  tp:["Use the empty condensed-milk can to measure the milk.",
      "Little holes mean the oven was too hot; drop it 10 degrees next time."],
  v:"brazilian pudim recipe"}},

{id:"bolo-de-cenoura", c:"Brazil", r:"latin-america", m:"sweet", t:60, s:12, o:180,
 i:[[300,"g","veg","structure","zanahorias","carrots","peladas, en trozos","peeled, in chunks"],
    [3,"","egg","binder","huevos","eggs"],
    [200,"ml","oil","fat","aceite","oil"],
    [300,"g","sugar","sweet","azúcar","sugar"],
    [250,"g","apflour","structure","harina de trigo","plain flour"],
    [1,"tbsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [1,"pinch","salt","salt","sal","salt"],
    [40,"g","cocoa","glaze","cacao en polvo","cocoa powder"],
    [100,"g","sugar","glaze","azúcar para la cobertura","sugar for the topping"],
    [30,"g","butter","glaze","mantequilla","butter"],
    [100,"ml","milk","glaze","leche","milk"]],
 es:{n:"Bolo de cenoura", b:"Bizcocho naranja de zanahoria licuada con una capa de chocolate brillante. La merienda brasileña.",
  st:["Licúa la zanahoria, los huevos y el aceite hasta que esté liso. Pasa a un bol.",
      "Añade 300 g de azúcar y mezcla. Añade la harina, el polvo de hornear y la sal y mezcla solo hasta integrar.",
      "Vierte en un molde de 22 x 33 cm engrasado y hornea a 180 °C durante 40 minutos.",
      "Para la cobertura, cuece el cacao, 100 g de azúcar, la mantequilla y la leche 5 minutos a fuego medio, removiendo, hasta que espese un poco.",
      "Vierte la cobertura caliente sobre el bizcocho caliente y deja enfriar."],
  tp:["Pincha el bizcocho con un tenedor antes de cubrirlo para que la cobertura penetre.",
      "El color naranja intenso viene de licuar la zanahoria cruda, no rallada."],
  v:"bolo de cenoura com cobertura de chocolate"},
 en:{n:"Bolo de Cenoura (Brazilian Carrot Cake)", b:"An orange cake of blended carrot under a glossy chocolate layer. The Brazilian afternoon snack.",
  st:["Blend the carrot, eggs and oil until smooth. Transfer to a bowl.",
      "Add 300 g of sugar and mix. Add the flour, baking powder and salt and mix just until combined.",
      "Pour into a greased 22 x 33 cm tin and bake at 180 °C for 40 minutes.",
      "For the topping, cook the cocoa, 100 g of sugar, the butter and milk for 5 minutes over medium heat, stirring, until slightly thickened.",
      "Pour the hot topping over the hot cake and let cool."],
  tp:["Prick the cake with a fork before topping so the chocolate soaks in.",
      "The bright orange comes from blending raw carrot, not grating it."],
  v:"brazilian carrot cake recipe"}},

{id:"quindim", c:"Brazil", r:"latin-america", m:"sweet", t:60, s:12, o:180,
 i:[[12,"","eggyolk","set","yemas de huevo","egg yolks"],
    [250,"g","sugar","sweet","azúcar","sugar"],
    [100,"g","desiccatedcoconut","structure","coco rallado","desiccated coconut"],
    [30,"g","butter","fat","mantequilla derretida","melted butter"],
    [100,"ml","coconutmilk","liquid","leche de coco","coconut milk"]],
 es:{n:"Quindim", b:"Pequeños flanes amarillos de yema y coco, brillantes arriba y con base de coco. Herencia de los conventos portugueses en Bahía.",
  st:["Mezcla las yemas con el azúcar sin batir, solo hasta integrar. Pásalas por un colador.",
      "Añade el coco, la mantequilla y la leche de coco y mezcla. Deja reposar 30 minutos.",
      "Engrasa 12 moldes pequeños y espolvorea con azúcar. Reparte la mezcla.",
      "Hornea al baño María a 180 °C durante 40 minutos, hasta que estén firmes y dorados arriba.",
      "Enfría y desmolda. El coco queda abajo y la yema brillante arriba al darles la vuelta."],
  tp:["No batas las yemas: si entra aire pierden el brillo.",
      "Guarda las claras para merengues o una tortilla."],
  v:"quindim receita"},
 en:{n:"Quindim (Coconut Yolk Custards)", b:"Small yellow custards of yolk and coconut, glossy on top with a coconut base. A legacy of Portuguese convents in Bahia.",
  st:["Mix the yolks with the sugar without whisking, just until combined. Pass through a sieve.",
      "Add the coconut, butter and coconut milk and mix. Leave 30 minutes.",
      "Grease 12 small moulds and dust with sugar. Divide the mixture between them.",
      "Bake in a water bath at 180 °C for 40 minutes, until firm and golden on top.",
      "Cool and turn out. The coconut sits at the bottom and the glossy yolk on top once inverted."],
  tp:["Don't whisk the yolks: air takes away the shine.",
      "Keep the whites for meringues or an omelette."],
  v:"quindim recipe"}}
];
