module.exports = [
{id:"caipirinha", c:"Brazil", r:"latin-america", m:"drink", t:5, s:1,
 i:[[1,"","citrus","acid","lima","lime","en 8 gajos, sin el centro blanco","cut in 8 wedges, pith removed"],
    [2,"tsp","sugar","sweet","azúcar","sugar"],
    [60,"ml","spirit","liquid","cachaça","cachaça"],
    [1,"handful","ice","structure","hielo picado","crushed ice"]],
 es:{n:"Caipirinha", b:"Lima machacada con azúcar, cachaça y hielo picado. El cóctel nacional de Brasil.",
  st:["Pon la lima y el azúcar en un vaso bajo y machaca 10 veces para sacar el jugo y el aceite de la cáscara.",
      "Llena el vaso de hielo picado.",
      "Añade la cachaça y remueve con la cuchara del fondo hacia arriba."],
  tp:["Quita el centro blanco de la lima: es lo que amarga.",
      "No machaques de más; la cáscara rota suelta amargor."],
  v:"caipirinha receita original"},
 en:{n:"Caipirinha", b:"Lime muddled with sugar, cachaça and crushed ice. Brazil's national cocktail.",
  st:["Put the lime and sugar in a short glass and muddle 10 times to release the juice and the oil in the peel.",
      "Fill the glass with crushed ice.",
      "Add the cachaça and stir from the bottom up."],
  tp:["Remove the white core of the lime: that's what turns it bitter.",
      "Don't over-muddle; torn peel releases bitterness."],
  v:"caipirinha recipe"}},

{id:"acai-na-tigela", c:"Brazil", r:"latin-america", m:"breakfast", t:10, s:2,
 i:[[400,"g","fruit","structure","pulpa de açaí congelada sin azúcar","unsweetened frozen açaí pulp"],
    [2,"","fruit","sweet","plátanos maduros congelados","frozen ripe bananas","en rodajas","sliced"],
    [60,"ml","water","liquid","agua","water"],
    [1,"","fruit","garnish","plátano","banana","en rodajas","sliced"],
    [150,"g","fruit","garnish","fresas","strawberries","en láminas","sliced"],
    [2,"tbsp","desiccatedcoconut","crunch","coco rallado tostado","toasted desiccated coconut"]],
 es:{n:"Açaí na tigela", b:"Açaí congelado batido espeso con plátano y servido en bol con fruta fresca. Desayuno de playa en Río.",
  st:["Deja la pulpa de açaí 5 minutos fuera del congelador y pártela en trozos.",
      "Licúa el açaí, el plátano congelado y el agua a velocidad baja, empujando con el mazo, hasta que tenga textura de helado suave.",
      "Sirve en dos boles.",
      "Cubre con el plátano fresco, las fresas y el coco."],
  tp:["Añade el agua de cucharada en cucharada: debe quedar espeso, para comer con cuchara.",
      "El plátano maduro endulza sin azúcar añadido."],
  v:"açaí na tigela receita"},
 en:{n:"Açaí Bowl", b:"Frozen açaí blended thick with banana and served in a bowl with fresh fruit. A Rio beach breakfast.",
  st:["Leave the açaí pulp out of the freezer for 5 minutes and break it into pieces.",
      "Blend the açaí, frozen banana and water on low, pushing down with the tamper, until it has the texture of soft ice cream.",
      "Divide between two bowls.",
      "Top with the fresh banana, strawberries and coconut."],
  tp:["Add the water a spoonful at a time: it should be thick enough to eat with a spoon.",
      "Ripe banana sweetens it with no added sugar."],
  v:"acai bowl recipe"}},

{id:"tapioca-recheada", c:"Brazil", r:"latin-america", m:"breakfast", t:15, s:2,
 i:[[120,"g","cassavastarch","structure","almidón de yuca hidratado (goma de tapioca)","hydrated cassava starch (tapioca goma)"],
    [1,"pinch","salt","salt","sal","salt"],
    [100,"g","cheese","protein","queso coalho o queso de freír","coalho or frying cheese","rallado","grated"],
    [2,"tbsp","desiccatedcoconut","enrich","coco rallado","desiccated coconut"],
    [10,"g","butter","fat","mantequilla","butter"]],
 es:{n:"Tapioca de queso y coco", b:"Crepe de almidón de yuca que se cuaja sola en la sartén, rellena de queso y coco. Desayuno del nordeste.",
  st:["Pasa el almidón por un colador para dejarlo como arena fina y añade la sal.",
      "Calienta una sartén antiadherente de 20 cm a fuego medio, sin grasa.",
      "Espolvorea la mitad del almidón en una capa pareja y aplánalo con una cuchara. Cuece 1 minuto, hasta que se una en un disco.",
      "Pon la mitad del queso y del coco en una mitad, dobla y cuece 1 minuto por lado.",
      "Pinta con la mitad de la mantequilla y sirve. Repite con el resto."],
  tp:["Si compras almidón seco, mézclalo con agua hasta que parezca arena húmeda, cuélalo y deja secar 10 minutos.",
      "No muevas la tapioca hasta que se despegue sola."],
  v:"tapioca de queijo coalho receita"},
 en:{n:"Tapioca Crêpe with Cheese and Coconut", b:"A cassava-starch crêpe that sets by itself in the pan, filled with cheese and coconut. A northeastern breakfast.",
  st:["Push the starch through a sieve so it's like fine sand and add the salt.",
      "Heat a 20 cm non-stick frying pan over medium heat, without fat.",
      "Sprinkle half the starch in an even layer and flatten with a spoon. Cook 1 minute, until it fuses into a disc.",
      "Put half the cheese and coconut on one half, fold and cook 1 minute each side.",
      "Brush with half the butter and serve. Repeat with the rest."],
  tp:["If you buy dry starch, mix it with water until it looks like damp sand, sieve it and leave 10 minutes to dry.",
      "Don't move the tapioca until it releases on its own."],
  v:"brazilian tapioca crepe recipe"}},

{id:"pastel-de-feira", c:"Brazil", r:"latin-america", m:"snack", t:75, s:12,
 i:[[500,"g","apflour","structure","harina de trigo","plain flour"],
    [1,"tsp","salt","salt","sal","salt"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [2,"tbsp","spirit","aerate","cachaça","cachaça"],
    [250,"ml","water","liquid","agua tibia","warm water"],
    [400,"g","beef","protein","carne molida de res","ground beef"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [60,"g","olives","umami","aceitunas verdes","green olives","picadas","chopped"],
    [2,"","egg","protein","huevos duros","hard-boiled eggs","picados","chopped"],
    [1,"handful","herb","aromatic","perejil","parsley","picado","chopped"],
    [1,"l","oil","fat","aceite para freír","oil for frying"]],
 es:{n:"Pastel de feria", b:"Empanada rectangular de masa fina que se infla en burbujas al freír. El clásico del mercado callejero de São Paulo.",
  st:["Mezcla la harina, la sal, el aceite, la cachaça y el agua y amasa 5 minutos. Tapa y deja 30 minutos.",
      "Dora la carne con la cebolla y el ajo 10 minutos. Sala al gusto, añade las aceitunas y el perejil y deja enfriar. Mezcla con el huevo.",
      "Estira la masa muy fina, de 1 mm, y corta rectángulos de 12 x 20 cm.",
      "Pon relleno en una mitad, dobla, sella con un tenedor y quita el aire.",
      "Fríe a 190 °C durante 2 minutos por lado, hasta que se infle y dore."],
  tp:["La cachaça hace las burbujas crujientes; se evapora al freír.",
      "El aceite debe estar muy caliente o el pastel absorbe grasa."],
  v:"pastel de feira receita"},
 en:{n:"Pastel de Feira (Market Pastry)", b:"A thin rectangular turnover that blisters as it fries. The street-market classic of São Paulo.",
  st:["Mix the flour, salt, oil, cachaça and water and knead 5 minutes. Cover and leave 30 minutes.",
      "Brown the beef with the onion and garlic for 10 minutes. Salt to taste, add the olives and parsley and let cool. Mix in the egg.",
      "Roll the dough very thin, to 1 mm, and cut 12 x 20 cm rectangles.",
      "Put filling on one half, fold, seal with a fork and press out the air.",
      "Fry at 190 °C for 2 minutes a side, until puffed and golden."],
  tp:["The cachaça makes the crisp blisters; it evaporates in the fryer.",
      "The oil must be very hot or the pastry soaks up fat."],
  v:"pastel de feira recipe"}},

{id:"vatapa", c:"Brazil", r:"latin-america", m:"main", t:45, s:6,
 i:[[200,"g","bread","thicken","pan blanco del día anterior","day-old white bread","sin corteza","crusts removed"],
    [400,"ml","coconutmilk","liquid","leche de coco","coconut milk"],
    [300,"ml","water","liquid","agua","water"],
    [100,"g","shrimp","umami","camarones secos","dried shrimp","remojados 20 minutos","soaked 20 minutes"],
    [60,"g","peanut","thicken","maní tostado sin sal","unsalted roasted peanuts"],
    [60,"g","cashew","thicken","anacardos tostados","roasted cashews"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"tbsp","spice","aromatic","jengibre fresco","fresh ginger","rallado","grated"],
    [3,"tbsp","oil","fat","aceite de palma (dendê)","palm oil (dendê)"],
    [1,"","citrus","acid","limón","lime","en jugo","juiced"],
    [1,"handful","herb","garnish","cilantro","cilantro","picado","chopped"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Vatapá", b:"Crema espesa de pan, leche de coco, camarón seco, maní y anacardo con dendê. Plato de Bahía de raíz africana.",
  st:["Remoja el pan en la leche de coco y el agua 10 minutos.",
      "Licúa el pan con su líquido, los camarones escurridos, el maní, los anacardos, la cebolla y el jengibre hasta que esté liso.",
      "Pasa a una olla con el dendê y cuece a fuego bajo 20 minutos, removiendo sin parar, hasta que se despegue del fondo.",
      "Añade el jugo de limón y la sal y mezcla.",
      "Termina con el cilantro. Sirve caliente con arroz blanco."],
  tp:["Remueve con cuchara de madera todo el tiempo; se pega con facilidad.",
      "Los camarones secos ya son salados: prueba antes de salar."],
  v:"vatapá baiano receita"},
 en:{n:"Vatapá (Bahian Bread and Coconut Cream)", b:"A thick cream of bread, coconut milk, dried shrimp, peanuts and cashews with dendê. A Bahian dish with African roots.",
  st:["Soak the bread in the coconut milk and water for 10 minutes.",
      "Blend the bread and its liquid with the drained shrimp, peanuts, cashews, onion and ginger until smooth.",
      "Transfer to a pot with the dendê and cook over low heat for 20 minutes, stirring constantly, until it pulls from the bottom.",
      "Add the lime juice and salt and mix.",
      "Finish with the cilantro. Serve hot with white rice."],
  tp:["Stir with a wooden spoon the whole time; it catches easily.",
      "Dried shrimp are already salty: taste before salting."],
  v:"vatapa recipe"}},

{id:"acaraje", c:"Brazil", r:"latin-america", m:"snack", t:60, s:6,
 i:[[500,"g","legume","structure","frijoles de ojo negro","black-eyed peas","remojados 12 horas","soaked 12 hours"],
    [1,"","onion","aromatic","cebolla","onion","en trozos","in chunks"],
    [1,"tsp","salt","salt","sal","salt"],
    [750,"ml","oil","fat","aceite de palma (dendê) para freír","palm oil (dendê) for frying"]],
 es:{n:"Acarajé", b:"Buñuelos de frijol de ojo negro fritos en dendê. Comida de las baianas en las calles de Salvador.",
  st:["Frota los frijoles remojados entre las manos en agua para soltar la piel. Deja que las pieles floten y retíralas. Repite hasta que estén limpios.",
      "Muele los frijoles con la cebolla en el procesador hasta tener una pasta espesa, sin agua o con muy poca.",
      "Añade la sal y bate la pasta con una cuchara de madera 5 minutos, hasta que esté aireada y más clara.",
      "Calienta el dendê a 175 °C. Forma bollos con dos cucharas y fríe 5 minutos, volteando, hasta que estén dorados oscuros.",
      "Escúrrelos sobre papel y sirve calientes."],
  tp:["El batido final es lo que los hace ligeros por dentro; no te lo saltes.",
      "Pelar los frijoles lleva tiempo pero es necesario: con piel quedan duros."],
  v:"acarajé receita baiana"},
 en:{n:"Acarajé (Black-Eyed Pea Fritters)", b:"Black-eyed pea fritters fried in dendê. Street food of the baianas in Salvador.",
  st:["Rub the soaked peas between your hands in water to loosen the skins. Let the skins float and skim them off. Repeat until clean.",
      "Grind the peas with the onion in a food processor to a thick paste, with no water or very little.",
      "Add the salt and beat the paste with a wooden spoon for 5 minutes, until airy and paler.",
      "Heat the dendê to 175 °C. Shape dumplings with two spoons and fry 5 minutes, turning, until deep golden.",
      "Drain on paper and serve hot."],
  tp:["The final beating is what makes them light inside; don't skip it.",
      "Skinning the peas takes time but is necessary: with skins they're tough."],
  v:"acaraje recipe"}},

{id:"arroz-carreteiro", c:"Brazil", r:"latin-america", m:"main", t:50, s:6,
 i:[[400,"g","driedmeat","protein","charque (carne seca)","charque (salted dried beef)","desalado 12 horas, en dados","desalted 12 hours, diced"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"","tomato","sauce","tomates","tomatoes","picados","chopped"],
    [1,"","bellpepper","aromatic","pimiento verde","green bell pepper","picado","chopped"],
    [400,"g","rice","structure","arroz de grano largo","long-grain rice"],
    [900,"ml","water","liquid","agua caliente","hot water"],
    [1,"handful","herb","garnish","perejil","parsley","picado","chopped"]],
 es:{n:"Arroz carreteiro", b:"Arroz con charque dorado, cocido en una sola olla. La comida de los carreteros gauchos del sur de Brasil.",
  st:["Cuece el charque desalado en agua 20 minutos y escúrrelo.",
      "Dora el charque en el aceite 8 minutos, hasta que tenga bordes tostados.",
      "Añade la cebolla, el ajo, el pimiento y el tomate y cuece 5 minutos.",
      "Añade el arroz y mezcla 2 minutos. Añade el agua, tapa y cuece 18 minutos a fuego bajo.",
      "Deja reposar 5 minutos, suelta con un tenedor y termina con el perejil."],
  tp:["Prueba el charque tras cocerlo antes de añadir sal; normalmente no hace falta.",
      "Se hace también con restos de churrasco en lugar de charque."],
  v:"arroz carreteiro receita"},
 en:{n:"Arroz Carreteiro (Cart-Driver's Rice)", b:"Rice with browned charque, cooked in one pot. The food of the gaucho cart drivers of southern Brazil.",
  st:["Simmer the desalted charque in water for 20 minutes and drain.",
      "Brown the charque in the oil for 8 minutes, until the edges crisp.",
      "Add the onion, garlic, pepper and tomato and cook 5 minutes.",
      "Add the rice and stir 2 minutes. Add the water, cover and cook 18 minutes on low.",
      "Rest 5 minutes, fluff with a fork and finish with the parsley."],
  tp:["Taste the charque after simmering before adding salt; it usually needs none.",
      "It is also made with leftover grilled beef instead of charque."],
  v:"arroz carreteiro recipe"}},

{id:"frango-com-quiabo", c:"Brazil", r:"latin-america", m:"main", t:60, s:6,
 i:[[1.2,"kg","chicken","protein","pollo en presas","chicken pieces"],
    [1,"","citrus","acid","limón","lime","en jugo","juiced"],
    [3,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [2,"tsp","salt","salt","sal","salt"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"","tomato","sauce","tomates","tomatoes","picados","chopped"],
    [500,"ml","water","liquid","agua","water"],
    [400,"g","veg","structure","quimbombó (quiabo)","okra (quiabo)","en rodajas de 2 cm","in 2 cm slices"],
    [1,"tbsp","whitevinegar","acid","vinagre blanco","white vinegar"],
    [1,"handful","herb","garnish","perejil y cilantro","parsley and cilantro","picados","chopped"]],
 es:{n:"Frango com quiabo", b:"Pollo guisado con quimbombó dorado aparte para que no quede baboso. Plato de domingo en Minas Gerais.",
  st:["Adoba el pollo con el limón, el ajo y la sal 20 minutos.",
      "Dora el pollo en 2 cucharadas de aceite 10 minutos. Añade la cebolla y el tomate y cuece 5 minutos.",
      "Añade el agua, tapa y cuece 30 minutos.",
      "Mientras, saltea el quimbombó con el vinagre en el resto del aceite a fuego fuerte 8 minutos, hasta que deje de soltar baba.",
      "Añade el quimbombó al pollo, cuece 5 minutos y termina con las hierbas."],
  tp:["Seca bien el quimbombó antes de cortarlo; mojado suelta más baba.",
      "Se sirve con arroz blanco."],
  v:"frango com quiabo mineiro"},
 en:{n:"Frango com Quiabo (Chicken with Okra)", b:"Chicken stew with okra browned separately so it isn't slimy. Sunday food in Minas Gerais.",
  st:["Season the chicken with the lime, garlic and salt for 20 minutes.",
      "Brown the chicken in 2 tablespoons of oil for 10 minutes. Add the onion and tomato and cook 5 minutes.",
      "Add the water, cover and cook 30 minutes.",
      "Meanwhile, fry the okra with the vinegar in the rest of the oil over high heat for 8 minutes, until it stops releasing slime.",
      "Add the okra to the chicken, cook 5 minutes and finish with the herbs."],
  tp:["Dry the okra well before slicing; wet, it gets slimier.",
      "It is served with white rice."],
  v:"frango com quiabo recipe"}},

{id:"baiao-de-dois", c:"Brazil", r:"latin-america", m:"main", t:60, s:6,
 i:[[250,"g","legume","protein","frijoles de ojo negro","black-eyed peas","remojados 4 horas","soaked 4 hours"],
    [1.5,"l","water","liquid","agua","water"],
    [150,"g","bacon","protein","tocino ahumado","smoked bacon","en dados","diced"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [300,"g","rice","structure","arroz de grano largo","long-grain rice"],
    [2,"tsp","salt","salt","sal","salt"],
    [200,"g","cheese","protein","queso coalho o queso de freír","coalho or frying cheese","en dados","diced"],
    [2,"tbsp","ghee","fat","mantequilla clarificada (manteiga de garrafa)","clarified butter (manteiga de garrafa)"],
    [1,"handful","herb","garnish","cilantro","cilantro","picado","chopped"]],
 es:{n:"Baião de dois", b:"Arroz y frijol de ojo negro cocidos juntos con tocino y queso coalho. El plato del sertón de Ceará.",
  st:["Cuece los frijoles en el agua 25 minutos, hasta que estén tiernos pero enteros. Guarda 700 ml del agua de cocción.",
      "Fríe el tocino 5 minutos en una olla. Añade la cebolla y el ajo y cuece 4 minutos.",
      "Añade el arroz y mezcla 1 minuto. Añade los frijoles, el agua reservada y la sal. Tapa y cuece 18 minutos a fuego bajo.",
      "Dora el queso en una sartén 3 minutos.",
      "Mezcla el queso y la mantequilla clarificada con el arroz y termina con el cilantro."],
  tp:["Los frijoles deben quedar enteros: vigílalos a partir de los 20 minutos.",
      "El queso coalho no se derrite; por eso se puede dorar."],
  v:"baião de dois receita cearense"},
 en:{n:"Baião de Dois (Rice and Black-Eyed Peas)", b:"Rice and black-eyed peas cooked together with bacon and coalho cheese. The dish of the Ceará backlands.",
  st:["Cook the peas in the water for 25 minutes, until tender but whole. Keep 700 ml of the cooking water.",
      "Fry the bacon for 5 minutes in a pot. Add the onion and garlic and cook 4 minutes.",
      "Add the rice and stir 1 minute. Add the peas, the reserved water and the salt. Cover and cook 18 minutes on low.",
      "Brown the cheese in a frying pan for 3 minutes.",
      "Stir the cheese and clarified butter into the rice and finish with the cilantro."],
  tp:["The peas should stay whole: watch them from 20 minutes on.",
      "Coalho cheese doesn't melt; that's why it can be browned."],
  v:"baiao de dois recipe"}},

{id:"beijinho", c:"Brazil", r:"latin-america", m:"sweet", t:30, s:25,
 i:[[395,"g","condensedmilk","structure","leche condensada","condensed milk"],
    [15,"g","butter","fat","mantequilla","butter"],
    [80,"g","desiccatedcoconut","structure","coco rallado","desiccated coconut"],
    [40,"g","desiccatedcoconut","garnish","coco rallado para rebozar","desiccated coconut for rolling"],
    [25,"","spice","garnish","clavos de olor","whole cloves"]],
 es:{n:"Beijinho", b:"Bolitas de leche condensada y coco con un clavo encima. El compañero blanco del brigadeiro en toda fiesta brasileña.",
  st:["Cuece la leche condensada, la mantequilla y 80 g de coco a fuego bajo, removiendo sin parar, 12 minutos, hasta que se despegue del fondo.",
      "Pasa a un plato engrasado y deja enfriar por completo.",
      "Con las manos engrasadas, forma bolitas de 15 g.",
      "Rebózalas en el resto del coco.",
      "Pon un clavo encima de cada una y sírvelas en cápsulas de papel."],
  tp:["El punto está cuando al inclinar la olla la masa se mueve entera.",
      "El clavo es decorativo; avisa que no se come."],
  v:"beijinho de coco receita"},
 en:{n:"Beijinho (Coconut Kisses)", b:"Condensed milk and coconut balls topped with a clove. The white partner to the brigadeiro at every Brazilian party.",
  st:["Cook the condensed milk, butter and 80 g of coconut over low heat, stirring constantly, for 12 minutes, until it pulls from the bottom.",
      "Transfer to a greased plate and let cool completely.",
      "With greased hands, roll into 15 g balls.",
      "Roll them in the rest of the coconut.",
      "Press a clove on top of each and serve in paper cases."],
  tp:["It's ready when tilting the pan moves the mass in one piece.",
      "The clove is decorative; let people know it isn't eaten."],
  v:"beijinho recipe"}}
];
