module.exports = [
{id:"quibe", c:"Brazil", r:"latin-america", m:"snack", t:60, s:20,
 i:[[250,"g","bulgur","structure","trigo para quibe (bulgur fino)","fine bulgur"],
    [500,"g","beef","protein","carne molida de res magra","lean minced beef"],
    [1,"","onion","aromatic","cebolla","onion","rallada","grated"],
    [1,"handful","herb","aromatic","hierbabuena","mint","picada","chopped"],
    [1,"tsp","spice","aromatic","pimienta de Jamaica molida","ground allspice"],
    [1.5,"tsp","salt","salt","sal","salt"],
    [750,"ml","oil","fat","aceite para freír","oil for frying"],
    [2,"","citrus","acid","limones","lemons"]],
 es:{n:"Quibe frito", b:"Croquetas alargadas de trigo y carne con hierbabuena. Herencia libanesa infaltable en las fiestas brasileñas.",
  st:["Remoja el trigo en agua 30 minutos y escúrrelo apretando bien.",
      "Mezcla con la carne, la cebolla, la hierbabuena, la especia y la sal. Amasa 5 minutos.",
      "Con las manos húmedas, forma croquetas alargadas con puntas.",
      "Fríe a 175 °C 4 minutos, hasta que estén doradas.",
      "Sirve con limón."],
  tp:["Exprime bien el trigo para que no se deshagan al freír.",
      "Amasar mucho da una textura fina."],
  v:"quibe frito brasileño"},
 en:{n:"Quibe (Brazilian Fried Kibbeh)", b:"Torpedo-shaped croquettes of bulgur and beef with mint. A Lebanese legacy at every Brazilian party.",
  st:["Soak the bulgur in water for 30 minutes and squeeze it very dry.",
      "Mix with the beef, onion, mint, spice and salt. Knead 5 minutes.",
      "With wet hands, shape pointed croquettes.",
      "Fry at 175 °C for 4 minutes, until golden.",
      "Serve with lemon."],
  tp:["Squeeze the bulgur well so they don't fall apart when frying.",
      "Kneading well gives a fine texture."],
  v:"brazilian quibe"}},

{id:"esfiha", c:"Brazil", r:"latin-america", m:"snack", t:120, s:20,
 i:[[500,"g","apflour","structure","harina de trigo","plain flour"],
    [7,"g","yeast","leaven","levadura seca","dried yeast"],
    [1,"tsp","sugar","sweet","azúcar","sugar"],
    [1,"tsp","salt","salt","sal","salt"],
    [250,"ml","milk","liquid","leche tibia","warm milk"],
    [60,"ml","oil","fat","aceite","oil"],
    [400,"g","beef","protein","carne molida de res","minced beef"],
    [1,"","onion","aromatic","cebolla","onion","picada fina","finely chopped"],
    [2,"","tomato","aromatic","tomates","tomatoes","sin semillas, picados","seeded, chopped"],
    [1,"handful","herb","aromatic","hierbabuena","mint","picada","chopped"],
    [1,"","citrus","acid","limón","lemon","exprimido","juiced"],
    [1,"tsp","salt","salt","sal (para el relleno)","salt (for the filling)"]],
 es:{n:"Esfiha abierta", b:"Panecitos abiertos cubiertos de carne con tomate y limón. De origen árabe y vendidos en todas las esquinas de São Paulo.",
  st:["Mezcla la harina, la levadura, el azúcar, la sal, la leche y el aceite. Amasa 8 minutos y deja levar 1 hora.",
      "Mezcla la carne cruda con la cebolla, el tomate, la hierbabuena, el limón y la sal del relleno.",
      "Divide la masa en 20 bolas y aplánalas en discos de 10 cm.",
      "Cubre cada disco con relleno dejando un borde.",
      "Hornea a 200 °C 15 minutos, hasta que los bordes estén dorados."],
  tp:["Escurre el tomate para que la masa no se moje.",
      "La carne se cuece en el horno: extiéndela fina."],
  v:"esfiha aberta de carne"},
 en:{n:"Esfiha (Brazilian Open Meat Pies)", b:"Open flatbreads topped with beef, tomato and lemon. Arab in origin and sold on every corner of São Paulo.",
  st:["Mix the flour, yeast, sugar, salt, milk and oil. Knead 8 minutes and rise 1 hour.",
      "Mix the raw beef with the onion, tomato, mint, lemon and filling salt.",
      "Divide the dough into 20 balls and flatten into 10 cm discs.",
      "Top each disc with filling, leaving a border.",
      "Bake at 200 °C for 15 minutes, until the edges are golden."],
  tp:["Drain the tomato so the dough doesn't get soggy.",
      "The beef cooks in the oven: spread it thin."],
  v:"brazilian esfiha"}},

{id:"cuscuz-paulista", c:"Brazil", r:"latin-america", m:"main", t:60, s:8,
 i:[[3,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [4,"","tomato","liquid","tomates","tomatoes","picados","chopped"],
    [250,"g","whitefish","protein","sardinas en conserva","canned sardines","escurridas","drained"],
    [150,"g","legume","structure","arvejas","green peas"],
    [200,"g","veg","structure","palmitos","hearts of palm","en rodajas","sliced"],
    [60,"g","olives","umami","aceitunas verdes","green olives"],
    [600,"ml","water","liquid","agua","water"],
    [300,"g","cornmeal","structure","harina de maíz en copos (flocão)","flaked cornmeal"],
    [2,"","egg","garnish","huevos duros","hard-boiled eggs","en rodajas","sliced"],
    [1,"handful","herb","garnish","perejil","parsley","picado","chopped"],
    [1.5,"tsp","salt","salt","sal","salt"]],
 es:{n:"Cuscuz paulista", b:"Pastel moldeado de harina de maíz con sardinas, palmito y tomate, decorado con huevo. Clásico de São Paulo.",
  st:["Sofríe la cebolla y el ajo en el aceite 5 minutos. Añade el tomate y cocina 8 minutos.",
      "Añade las sardinas, las arvejas, los palmitos, las aceitunas, el agua y la sal y hierve.",
      "Añade la harina de maíz poco a poco, removiendo, y cocina 5 minutos hasta que se despegue.",
      "Decora el fondo de un molde de rosca con huevo, perejil y sardina. Rellena apretando.",
      "Deja enfriar 30 minutos y desmolda."],
  tp:["Aprieta bien la masa en el molde para que se sostenga.",
      "Se come tibio o frío."],
  v:"cuscuz paulista"},
 en:{n:"Cuscuz Paulista (São Paulo Cornmeal Mould)", b:"A moulded cornmeal cake with sardines, hearts of palm and tomato, decorated with egg. A São Paulo classic.",
  st:["Cook the onion and garlic in the oil for 5 minutes. Add the tomato and cook 8 minutes.",
      "Add the sardines, peas, palm hearts, olives, water and salt and bring to the boil.",
      "Add the cornmeal gradually, stirring, and cook 5 minutes until it pulls away.",
      "Decorate the base of a ring mould with egg, parsley and sardine. Pack in the mixture.",
      "Cool 30 minutes and turn out."],
  tp:["Pack it firmly into the mould so it holds.",
      "Eat it warm or cold."],
  v:"brazilian cuscuz paulista"}},

{id:"bolo-de-milho", c:"Brazil", r:"latin-america", m:"sweet", t:60, s:10,
 i:[[4,"","corn","structure","mazorcas de maíz tierno","young corn cobs","desgranadas","kernels cut off"],
    [3,"","egg","structure","huevos","eggs"],
    [200,"ml","milk","liquid","leche","milk"],
    [100,"ml","oil","fat","aceite","oil"],
    [200,"g","sugar","sweet","azúcar","sugar"],
    [100,"g","cornmeal","structure","harina de maíz fina","fine cornmeal"],
    [1,"tbsp","bakingpowder","leaven","polvo de hornear","baking powder"]],
 es:{n:"Bolo de milho verde", b:"Bizcocho húmedo de maíz tierno licuado. El sabor de las fiestas juninas.",
  st:["Licúa los granos de maíz, los huevos, la leche, el aceite y el azúcar 3 minutos.",
      "Añade la harina de maíz y licúa 30 segundos.",
      "Añade el polvo de hornear y mezcla con una cuchara.",
      "Vierte en un molde de 22 cm engrasado.",
      "Hornea a 180 °C 45 minutos, hasta que esté dorado."],
  tp:["Queda cremoso por dentro: es así.",
      "Deja enfriar antes de desmoldar."],
  v:"bolo de milho verde"},
 en:{n:"Bolo de Milho (Brazilian Fresh Corn Cake)", b:"A moist cake of blended fresh corn. The taste of June festivals.",
  st:["Blend the corn kernels, eggs, milk, oil and sugar for 3 minutes.",
      "Add the cornmeal and blend 30 seconds.",
      "Add the baking powder and stir in with a spoon.",
      "Pour into a greased 22 cm tin.",
      "Bake at 180 °C for 45 minutes, until golden."],
  tp:["It's meant to be creamy inside.",
      "Cool before turning out."],
  v:"brazilian fresh corn cake"}},

{id:"caruru", c:"Brazil", r:"latin-america", m:"side", t:50, s:6,
 i:[[500,"g","veg","structure","quiabo (okra)","okra","en rodajas finas","thinly sliced"],
    [80,"g","shrimp","umami","camarón seco molido","ground dried shrimp"],
    [60,"g","peanut","thicken","maní tostado","roasted peanuts"],
    [60,"g","cashew","thicken","castañas de cajú tostadas","roasted cashews"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"piece","spice","aromatic","trozo de jengibre","piece of ginger"],
    [3,"tbsp","oil","fat","aceite de dendê (palma)","red palm oil"],
    [500,"ml","water","liquid","agua","water"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Caruru", b:"Guiso de okra con camarón seco, maní y castaña de cajú en aceite de dendê. Plato sagrado de la cocina bahiana.",
  st:["Muele el maní, las castañas, la cebolla y el jengibre hasta tener una pasta.",
      "Sofríe la pasta y el camarón en el aceite 5 minutos.",
      "Añade la okra y el agua y cuece 25 minutos, removiendo, hasta que la okra se deshaga.",
      "Sala y sirve."],
  tp:["Remueve a menudo: la okra suelta baba que espesa el guiso.",
      "El dendê le da el color y sabor bahiano."],
  v:"caruru baiano"},
 en:{n:"Caruru (Bahian Okra Stew)", b:"Okra stewed with dried shrimp, peanuts and cashews in red palm oil. A sacred dish of Bahian cooking.",
  st:["Grind the peanuts, cashews, onion and ginger into a paste.",
      "Fry the paste and shrimp in the oil for 5 minutes.",
      "Add the okra and water and simmer 25 minutes, stirring, until the okra breaks down.",
      "Salt and serve."],
  tp:["Stir often: the okra releases a slime that thickens the stew.",
      "The palm oil gives the Bahian colour and flavour."],
  v:"brazilian caruru"}},

{id:"cajuzinho", c:"Brazil", r:"latin-america", m:"sweet", t:40, s:30,
 i:[[395,"g","condensedmilk","sweet","leche condensada","condensed milk"],
    [200,"g","peanut","structure","maní tostado sin sal","unsalted roasted peanuts","molido","ground"],
    [1,"tbsp","cocoa","aromatic","cacao en polvo","cocoa powder"],
    [1,"tbsp","butter","fat","mantequilla","butter"],
    [60,"g","sugar","garnish","azúcar","sugar"],
    [30,"","peanut","garnish","maníes enteros para decorar","whole peanuts to decorate"]],
 es:{n:"Cajuzinho", b:"Dulces de maní con forma de fruto de cajú. Infaltables en los cumpleaños brasileños.",
  st:["Cocina la leche condensada, el maní molido, el cacao y la mantequilla 10 minutos, removiendo, hasta que se despegue de la olla.",
      "Deja enfriar por completo.",
      "Con las manos untadas de mantequilla, forma bolitas alargadas con forma de cajú.",
      "Pásalas por el azúcar y pon un maní en la punta."],
  tp:["La masa debe estar fría para modelarla.",
      "Sírvelos en capacillos de papel."],
  v:"cajuzinho de amendoim"},
 en:{n:"Cajuzinho (Brazilian Peanut Sweets)", b:"Peanut sweets shaped like cashew fruit. A must at Brazilian birthday parties.",
  st:["Cook the condensed milk, ground peanuts, cocoa and butter for 10 minutes, stirring, until it pulls away from the pan.",
      "Cool completely.",
      "With buttered hands, shape small cashew-shaped balls.",
      "Roll in the sugar and press a peanut into the tip."],
  tp:["The mixture must be cold to shape.",
      "Serve in paper cases."],
  v:"brazilian peanut cajuzinho"}},

{id:"salpicao", c:"Brazil", r:"latin-america", m:"main", t:40, s:6,
 i:[[600,"g","chicken","protein","pechuga de pollo cocida","cooked chicken breast","desmenuzada","shredded"],
    [2,"","veg","structure","zanahorias","carrots","ralladas","grated"],
    [150,"g","corn","structure","granos de maíz cocidos","cooked corn kernels"],
    [150,"g","legume","structure","arvejas cocidas","cooked peas"],
    [1,"","fruit","structure","manzana verde","green apple","en cubos","diced"],
    [50,"g","driedfruit","sweet","pasas","raisins"],
    [200,"g","mayo","sauce","mayonesa","mayonnaise"],
    [1,"handful","herb","garnish","perejil","parsley","picado","chopped"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Salpicão de frango", b:"Ensalada fría de pollo con zanahoria, maíz, manzana y mayonesa. La ensalada de las fiestas de fin de año en Brasil.",
  st:["Mezcla el pollo, la zanahoria, el maíz, las arvejas, la manzana y las pasas.",
      "Añade la mayonesa y la sal y mezcla.",
      "Refrigera 1 hora.",
      "Termina con el perejil."],
  tp:["Revisa la etiqueta de la mayonesa: puede llevar mostaza o soja.",
      "Se conserva 1 día en la nevera."],
  v:"salpicão de frango"},
 en:{n:"Salpicão (Brazilian Chicken Salad)", b:"A cold chicken salad with carrot, corn, apple and mayonnaise. The year-end party salad in Brazil.",
  st:["Mix the chicken, carrot, corn, peas, apple and raisins.",
      "Add the mayonnaise and salt and mix.",
      "Chill 1 hour.",
      "Finish with the parsley."],
  tp:["Check the mayonnaise label: it may contain mustard or soy.",
      "It keeps 1 day in the fridge."],
  v:"brazilian chicken salpicao"}},

{id:"couve-refogada", c:"Brazil", r:"latin-america", m:"side", t:15, s:4,
 i:[[1,"bunch","veg","structure","col rizada (couve)","collard greens","en tiras muy finas","in very thin strips"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [0.5,"tsp","salt","salt","sal","salt"]],
 es:{n:"Couve refogada", b:"Col rizada en tiras finísimas salteada con ajo. Acompaña la feijoada y el tutu en Brasil.",
  st:["Enrolla las hojas y córtalas en tiras muy finas.",
      "Dora el ajo en el aceite 1 minuto.",
      "Añade la col y la sal y saltea 2 minutos a fuego fuerte, hasta que brille.",
      "Sirve de inmediato."],
  tp:["No la cocines de más: debe seguir verde intenso.",
      "Cuanto más finas las tiras, mejor."],
  v:"couve refogada"},
 en:{n:"Couve Refogada (Brazilian Garlic Collards)", b:"Collard greens cut into very thin ribbons and sautéed with garlic. Served with feijoada and tutu in Brazil.",
  st:["Roll the leaves and slice into very thin ribbons.",
      "Fry the garlic in the oil for 1 minute.",
      "Add the greens and salt and stir-fry 2 minutes over high heat, until glossy.",
      "Serve at once."],
  tp:["Don't overcook: it should stay bright green.",
      "The thinner the ribbons, the better."],
  v:"brazilian garlic collard greens"}},

{id:"torta-de-palmito", c:"Brazil", r:"latin-america", m:"main", t:60, s:8,
 i:[[3,"","egg","structure","huevos","eggs"],
    [300,"ml","milk","liquid","leche","milk"],
    [120,"ml","oil","fat","aceite","oil"],
    [200,"g","apflour","structure","harina de trigo","plain flour"],
    [50,"g","parmesan","enrich","queso parmesano rallado","grated parmesan"],
    [1,"tbsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"tbsp","oil","fat","aceite (para el relleno)","oil (for the filling)"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"","tomato","aromatic","tomates","tomatoes","picados","chopped"],
    [300,"g","veg","structure","palmitos","hearts of palm","en rodajas","sliced"],
    [100,"g","legume","structure","arvejas","peas"],
    [1,"handful","herb","aromatic","perejil","parsley","picado","chopped"]],
 es:{n:"Torta de palmito", b:"Tarta salada de masa de licuadora con relleno de palmito, tomate y arvejas. Merienda brasileña.",
  st:["Sofríe la cebolla en el aceite del relleno 5 minutos. Añade el tomate, los palmitos, las arvejas y el perejil y cocina 5 minutos.",
      "Licúa los huevos, la leche, el aceite, la harina, el queso y la sal. Añade el polvo de hornear.",
      "Vierte la mitad de la masa en un molde de 22 x 30 cm engrasado, cubre con el relleno y luego con el resto de la masa.",
      "Hornea a 180 °C 40 minutos, hasta que esté dorada."],
  tp:["Escurre bien el relleno para que la masa no quede húmeda.",
      "Se come tibia o fría."],
  v:"torta de palmito de liquidificador"},
 en:{n:"Torta de Palmito (Brazilian Heart of Palm Pie)", b:"A savoury blender-batter pie filled with hearts of palm, tomato and peas. A Brazilian afternoon snack.",
  st:["Cook the onion in the filling oil for 5 minutes. Add the tomato, palm hearts, peas and parsley and cook 5 minutes.",
      "Blend the eggs, milk, oil, flour, cheese and salt. Add the baking powder.",
      "Pour half the batter into a greased 22 x 30 cm tin, add the filling, then the rest of the batter.",
      "Bake at 180 °C for 40 minutes, until golden."],
  tp:["Drain the filling well so the batter doesn't go soggy.",
      "Eat it warm or cold."],
  v:"brazilian heart of palm pie"}},

{id:"pao-de-mel", c:"Brazil", r:"latin-america", m:"sweet", t:60, s:16,
 i:[[120,"g","honey","sweet","miel","honey"],
    [100,"g","brownsugar","sweet","azúcar moreno","brown sugar"],
    [200,"ml","milk","liquid","leche","milk"],
    [1,"","egg","binder","huevo","egg"],
    [250,"g","apflour","structure","harina de trigo","plain flour"],
    [2,"tbsp","cocoa","aromatic","cacao en polvo","cocoa powder"],
    [1,"tsp","spice","aromatic","canela, clavo y nuez moscada molidos","ground cinnamon, clove and nutmeg"],
    [1,"tsp","bakingsoda","aerate","bicarbonato de sodio","bicarbonate of soda"],
    [300,"g","dulcedeleche","spread","doce de leite","dulce de leche"],
    [300,"g","darkchocolate","glaze","chocolate semiamargo","dark chocolate","derretido","melted"]],
 es:{n:"Pão de mel", b:"Bizcochitos de miel y especias rellenos de dulce de leche y bañados en chocolate. Regalo clásico brasileño.",
  st:["Mezcla la miel, el azúcar, la leche y el huevo. Añade la harina, el cacao, las especias y el bicarbonato.",
      "Vierte en un molde de 25 x 35 cm con papel y hornea a 180 °C 25 minutos. Deja enfriar.",
      "Corta 16 círculos de 6 cm y ábrelos por la mitad.",
      "Rellena con el doce de leite.",
      "Baña en el chocolate y deja secar sobre papel."],
  tp:["Se conservan 1 semana envueltos en papel de aluminio.",
      "Los recortes sirven para hacer trufas."],
  v:"pão de mel recheado"},
 en:{n:"Pão de Mel (Brazilian Honey Spice Cakes)", b:"Little honey spice cakes filled with dulce de leche and dipped in chocolate. A classic Brazilian gift.",
  st:["Mix the honey, sugar, milk and egg. Add the flour, cocoa, spices and bicarbonate.",
      "Pour into a lined 25 x 35 cm tin and bake at 180 °C for 25 minutes. Cool.",
      "Cut 16 circles of 6 cm and split them in half.",
      "Fill with the dulce de leche.",
      "Dip in the chocolate and let set on paper."],
  tp:["They keep 1 week wrapped in foil.",
      "Use the offcuts to make truffles."],
  v:"brazilian pao de mel"}}
];
