module.exports = [
{id:"strogonoff-de-frango", c:"Brazil", r:"latin-america", m:"main", t:35, s:4,
 i:[[700,"g","chicken","protein","pechuga de pollo","chicken breast","en cubos","cubed"],
    [2,"tbsp","butter","fat","mantequilla","butter"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [200,"g","mushroom","umami","champiñones","mushrooms","en láminas","sliced"],
    [3,"tbsp","ketchup","sauce","kétchup","ketchup"],
    [1,"tbsp","mustard","sauce","mostaza","mustard"],
    [200,"ml","heavycream","sauce","crema de leche","double cream"],
    [1,"tsp","salt","salt","sal","salt"],
    [300,"g","rice","serve","arroz blanco para servir","white rice to serve"]],
 es:{n:"Strogonoff de frango", b:"Pollo en salsa cremosa de kétchup, mostaza y champiñones. El plato favorito de los cumpleaños en Brasil.",
  st:["Sala el pollo y dóralo en la mantequilla 6 minutos.",
      "Añade la cebolla y el ajo y cocina 4 minutos.",
      "Añade los champiñones y cocina 4 minutos.",
      "Añade el kétchup y la mostaza, baja el fuego y añade la crema. Calienta 3 minutos sin hervir.",
      "Sirve con el arroz blanco."],
  tp:["No dejes hervir tras añadir la crema o se corta.",
      "Sírvelo recién hecho: la salsa espesa al reposar."],
  v:"strogonoff de frango brasileño"},
 en:{n:"Strogonoff de Frango (Brazilian Chicken Stroganoff)", b:"Chicken in a creamy ketchup, mustard and mushroom sauce. Brazil's favourite birthday-party dish.",
  st:["Salt the chicken and brown it in the butter for 6 minutes.",
      "Add the onion and garlic and cook 4 minutes.",
      "Add the mushrooms and cook 4 minutes.",
      "Add the ketchup and mustard, lower the heat and add the cream. Heat 3 minutes without boiling.",
      "Serve with the white rice."],
  tp:["Don't boil once the cream is in or it may split.",
      "Serve it straight away: the sauce thickens as it sits."],
  v:"brazilian chicken stroganoff"}},

{id:"bolinho-de-arroz", c:"Brazil", r:"latin-america", m:"snack", t:30, s:20,
 i:[[400,"g","rice","structure","arroz cocido frío","cold cooked rice"],
    [2,"","egg","binder","huevos","eggs"],
    [80,"g","apflour","binder","harina de trigo","plain flour"],
    [60,"g","parmesan","enrich","queso parmesano rallado","grated parmesan"],
    [1,"handful","herb","aromatic","perejil","parsley","picada","chopped"],
    [1,"tsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [0.5,"tsp","salt","salt","sal","salt"],
    [750,"ml","oil","fat","aceite para freír","oil for frying"]],
 es:{n:"Bolinho de arroz", b:"Bolitas fritas de arroz sobrante con queso y perejil. La forma brasileña de no tirar el arroz de ayer.",
  st:["Mezcla el arroz, los huevos, el queso, el perejil y la sal.",
      "Añade la harina y el polvo de hornear y mezcla hasta tener una masa pegajosa.",
      "Forma bolitas con dos cucharas.",
      "Fríe a 175 °C 3 minutos, hasta que estén doradas.",
      "Escurre en papel."],
  tp:["El arroz frío de la víspera funciona mejor.",
      "Si la masa está muy blanda, añade una cucharada más de harina."],
  v:"bolinho de arroz"},
 en:{n:"Bolinho de Arroz (Brazilian Rice Fritters)", b:"Fried balls of leftover rice with cheese and parsley. Brazil's way of not wasting yesterday's rice.",
  st:["Mix the rice, eggs, cheese, parsley and salt.",
      "Add the flour and baking powder and mix to a sticky batter.",
      "Shape balls with two spoons.",
      "Fry at 175 °C for 3 minutes, until golden.",
      "Drain on paper."],
  tp:["Day-old cold rice works best.",
      "If the batter is too loose, add another spoon of flour."],
  v:"brazilian rice fritters"}},

{id:"carne-de-sol-com-mandioca", c:"Brazil", r:"latin-america", m:"main", t:60, s:4,
 i:[[800,"g","driedmeat","protein","carne de sol (carne de res salada y secada al sol)","carne de sol (salted sun-dried beef)","en cubos","cubed"],
    [800,"g","cassava","structure","yuca","cassava","pelada, en trozos","peeled, in chunks"],
    [3,"tbsp","butter","fat","mantequilla clarificada o mantequilla","clarified or regular butter"],
    [2,"","onion","aromatic","cebollas","onions","en aros","in rings"],
    [1,"handful","herb","garnish","cilantro","coriander","picado","chopped"]],
 es:{n:"Carne de sol com mandioca", b:"Carne salada y secada al sol, dorada en mantequilla con cebolla, con yuca cocida. Plato del Nordeste brasileño.",
  st:["Remoja la carne de sol en agua 2 horas, cambiando el agua 2 veces, para quitar sal.",
      "Cuece la yuca en agua 25 minutos, hasta que esté tierna. Escurre.",
      "Dora la carne en la mitad de la mantequilla a fuego fuerte 8 minutos.",
      "Añade la cebolla y cocina 5 minutos.",
      "Saltea la yuca en el resto de la mantequilla 5 minutos y sirve con la carne y el cilantro."],
  tp:["Prueba un trozo tras el remojo: si sigue muy salada, remoja más.",
      "La mantequilla de botella del Nordeste le da el sabor típico."],
  v:"carne de sol com mandioca"},
 en:{n:"Carne de Sol com Mandioca (Sun-Dried Beef with Cassava)", b:"Salted, sun-dried beef browned in butter with onions, served with boiled cassava. A dish from Brazil's Northeast.",
  st:["Soak the beef in water for 2 hours, changing the water 2 times, to remove salt.",
      "Boil the cassava for 25 minutes, until tender. Drain.",
      "Brown the beef in half the butter over high heat for 8 minutes.",
      "Add the onion and cook 5 minutes.",
      "Sauté the cassava in the rest of the butter for 5 minutes and serve with the beef and coriander."],
  tp:["Taste a piece after soaking: if still very salty, soak longer.",
      "The Northeast's bottled clarified butter gives it the typical flavour."],
  v:"brazilian carne de sol cassava"}},

{id:"caldinho-de-feijao", c:"Brazil", r:"latin-america", m:"soup", t:40, s:6,
 i:[[600,"g","legume","structure","frijoles negros cocidos con su líquido de cocción","cooked black beans with their cooking liquid"],
    [100,"g","bacon","protein","tocino","bacon","en daditos","diced"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [500,"ml","water","liquid","agua","water"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"handful","herb","garnish","perejil","parsley","picado","chopped"]],
 es:{n:"Caldinho de feijão", b:"Crema de frijol negro con tocino, servida en vasitos. Entrante de los bares brasileños.",
  st:["Fríe el tocino 5 minutos hasta que esté crujiente. Saca la mitad para decorar.",
      "Sofríe la cebolla y el ajo en la grasa 5 minutos.",
      "Añade los frijoles y el agua y cuece 10 minutos.",
      "Tritura hasta que esté liso, sala y cuece 5 minutos más.",
      "Sirve en vasitos con el tocino reservado y el perejil."],
  tp:["Debe quedar como una crema espesa pero bebible.",
      "Si espesa al reposar, añade un poco de agua."],
  v:"caldinho de feijão"},
 en:{n:"Caldinho de Feijão (Brazilian Black Bean Shots)", b:"A smooth black bean soup with bacon, served in small cups. A Brazilian bar starter.",
  st:["Fry the bacon for 5 minutes until crisp. Set half aside for topping.",
      "Cook the onion and garlic in the fat for 5 minutes.",
      "Add the beans and water and simmer 10 minutes.",
      "Blend until smooth, salt and simmer 5 minutes more.",
      "Serve in small cups with the reserved bacon and parsley."],
  tp:["It should be thick but drinkable.",
      "Add water if it gets too thick as it sits."],
  v:"brazilian black bean caldinho"}},

{id:"bolo-de-fuba", c:"Brazil", r:"latin-america", m:"sweet", t:60, s:10,
 i:[[3,"","egg","structure","huevos","eggs"],
    [240,"ml","milk","liquid","leche","milk"],
    [120,"ml","oil","fat","aceite","oil"],
    [250,"g","sugar","sweet","azúcar","sugar"],
    [200,"g","cornmeal","structure","harina de maíz fina (fubá)","fine cornmeal"],
    [100,"g","apflour","structure","harina de trigo","plain flour"],
    [1,"tbsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [1,"tsp","spice","aromatic","anís en grano","aniseed"]],
 es:{n:"Bolo de fubá", b:"Bizcocho sencillo de harina de maíz con anís. Se toma con café en las tardes del campo brasileño.",
  st:["Licúa los huevos, la leche, el aceite y el azúcar 2 minutos.",
      "Añade el fubá y la harina y licúa 1 minuto.",
      "Añade el polvo de hornear y el anís y mezcla con una cuchara.",
      "Vierte en un molde de 22 cm engrasado.",
      "Hornea a 180 °C 40 minutos, hasta que un palillo salga limpio."],
  tp:["No abras el horno los primeros 30 minutos.",
      "El anís es opcional, pero es el sabor de la versión de la abuela."],
  v:"bolo de fubá"},
 en:{n:"Bolo de Fubá (Brazilian Cornmeal Cake)", b:"A simple cornmeal cake with aniseed. Eaten with coffee on Brazilian country afternoons.",
  st:["Blend the eggs, milk, oil and sugar for 2 minutes.",
      "Add the cornmeal and flour and blend 1 minute.",
      "Add the baking powder and aniseed and stir in with a spoon.",
      "Pour into a greased 22 cm tin.",
      "Bake at 180 °C for 40 minutes, until a skewer comes out clean."],
  tp:["Don't open the oven for the first 30 minutes.",
      "The aniseed is optional, but it's the flavour of grandma's version."],
  v:"brazilian cornmeal cake"}},

{id:"curau", c:"Brazil", r:"latin-america", m:"sweet", t:40, s:6,
 i:[[5,"","corn","structure","mazorcas de maíz tierno","corn cobs","desgranadas","kernels cut off"],
    [750,"ml","milk","liquid","leche","milk"],
    [150,"g","sugar","sweet","azúcar","sugar"],
    [1,"pinch","salt","salt","sal","salt"],
    [1,"tsp","spice","garnish","canela molida","ground cinnamon"]],
 es:{n:"Curau", b:"Crema de maíz tierno con leche y azúcar, espolvoreada con canela. Dulce de las fiestas juninas.",
  st:["Licúa el maíz con la leche 3 minutos.",
      "Cuela apretando bien para sacar todo el líquido.",
      "Cuece el líquido con el azúcar y la sal 20 minutos a fuego bajo, removiendo sin parar, hasta que espese.",
      "Reparte en cuencos, deja enfriar y espolvorea con canela."],
  tp:["Usa maíz tierno y lechoso: el maíz duro no espesa igual.",
      "Remueve siempre: se pega muy fácil."],
  v:"curau de milho"},
 en:{n:"Curau (Brazilian Sweet Corn Pudding)", b:"A pudding of fresh corn, milk and sugar, dusted with cinnamon. A June festival favourite.",
  st:["Blend the corn with the milk for 3 minutes.",
      "Strain, pressing hard to get all the liquid.",
      "Cook the liquid with the sugar and salt for 20 minutes on low, stirring constantly, until thick.",
      "Pour into bowls, cool and dust with cinnamon."],
  tp:["Use young, milky corn: starchy corn won't thicken the same way.",
      "Keep stirring: it catches very easily."],
  v:"brazilian curau corn pudding"}},

{id:"sagu-de-vinho", c:"Brazil", r:"latin-america", m:"sweet", t:60, s:6,
 i:[[150,"g","cassavastarch","structure","perlas de tapioca (sagú)","tapioca pearls"],
    [1,"l","water","liquid","agua","water"],
    [500,"ml","winered","liquid","vino tinto","red wine"],
    [200,"g","sugar","sweet","azúcar","sugar"],
    [1,"piece","spice","aromatic","rama de canela","cinnamon stick"],
    [4,"piece","spice","aromatic","clavos de olor","cloves"]],
 es:{n:"Sagu de vinho", b:"Perlas de tapioca cocidas en vino tinto con canela y clavo. Postre gaúcho del sur de Brasil.",
  st:["Remoja las perlas en el agua 30 minutos.",
      "Añade el vino, el azúcar, la canela y el clavo y lleva a hervor.",
      "Cuece 25 minutos a fuego bajo, removiendo, hasta que las perlas estén transparentes.",
      "Retira la canela y el clavo y deja enfriar. Sirve frío."],
  tp:["Si queda alguna perla con centro blanco, cuece unos minutos más.",
      "Espesa al enfriar: si queda muy firme, añade un poco de agua."],
  v:"sagu de vinho gaúcho"},
 en:{n:"Sagu de Vinho (Tapioca Pearls in Red Wine)", b:"Tapioca pearls cooked in red wine with cinnamon and clove. A gaúcho dessert from southern Brazil.",
  st:["Soak the pearls in the water for 30 minutes.",
      "Add the wine, sugar, cinnamon and cloves and bring to the boil.",
      "Simmer 25 minutes on low, stirring, until the pearls are clear.",
      "Remove the cinnamon and cloves and cool. Serve cold."],
  tp:["If any pearls still have a white centre, cook a few minutes more.",
      "It thickens as it cools: if too firm, add a little water."],
  v:"brazilian sagu red wine"}},

{id:"manjar-branco", c:"Brazil", r:"latin-america", m:"sweet", t:60, s:8,
 i:[[500,"ml","milk","liquid","leche","milk"],
    [200,"ml","coconutmilk","liquid","leche de coco","coconut milk"],
    [395,"g","condensedmilk","sweet","leche condensada","condensed milk"],
    [60,"g","cornstarch","set","maicena","cornflour"],
    [200,"g","driedfruit","sauce","ciruelas pasas sin hueso","pitted prunes"],
    [150,"g","sugar","sweet","azúcar","sugar"],
    [250,"ml","water","liquid","agua","water"]],
 es:{n:"Manjar branco com calda de ameixa", b:"Flan de coco firme cubierto de salsa de ciruelas pasas. El postre de las comidas de domingo en Brasil.",
  st:["Mezcla la leche, la leche de coco, la condensada y la maicena en frío.",
      "Cuece removiendo 10 minutos, hasta que espese mucho.",
      "Vierte en un molde de flan mojado y refrigera 4 horas.",
      "Cuece las ciruelas con el azúcar y el agua 15 minutos, hasta tener un almíbar. Deja enfriar.",
      "Desmolda el manjar y cubre con la salsa de ciruelas."],
  tp:["Moja el molde con agua para que se desmolde fácil.",
      "Remueve sin parar mientras espesa para evitar grumos."],
  v:"manjar branco com calda de ameixa"},
 en:{n:"Manjar Branco (Coconut Pudding with Prune Sauce)", b:"A firm coconut pudding topped with prune syrup. Brazil's Sunday lunch dessert.",
  st:["Mix the milk, coconut milk, condensed milk and cornflour cold.",
      "Cook, stirring, for 10 minutes, until very thick.",
      "Pour into a wet ring mould and chill 4 hours.",
      "Simmer the prunes with the sugar and water for 15 minutes, into a syrup. Cool.",
      "Turn out the pudding and top with the prune sauce."],
  tp:["Wet the mould so it turns out easily.",
      "Stir constantly as it thickens to avoid lumps."],
  v:"brazilian coconut pudding prunes"}},

{id:"pe-de-moleque", c:"Brazil", r:"latin-america", m:"sweet", t:30, s:20,
 i:[[300,"g","peanut","structure","maní tostado sin piel","roasted skinned peanuts"],
    [300,"g","brownsugar","sweet","rapadura o azúcar mascabado","rapadura or dark brown sugar"],
    [100,"ml","water","liquid","agua","water"],
    [1,"tbsp","butter","fat","mantequilla","butter"],
    [0.5,"tsp","bakingsoda","aerate","bicarbonato de sodio","bicarbonate of soda"]],
 es:{n:"Pé de moleque", b:"Crocante de maní con rapadura. Dulce de las fiestas juninas brasileñas.",
  st:["Cuece la rapadura con el agua 8 minutos, hasta que forme un caramelo espeso.",
      "Añade los maníes y la mantequilla y cocina 5 minutos, removiendo.",
      "Añade el bicarbonato y mezcla rápido: espumará.",
      "Extiende sobre una superficie engrasada a 1 cm y corta en cuadrados antes de que endurezca."],
  tp:["Trabaja rápido: endurece en pocos minutos.",
      "Guárdalo en un frasco cerrado para que no se ablande."],
  v:"pé de moleque de amendoim"},
 en:{n:"Pé de Moleque (Brazilian Peanut Brittle)", b:"Peanut brittle made with unrefined cane sugar. A Brazilian June festival sweet.",
  st:["Boil the sugar with the water for 8 minutes, into a thick caramel.",
      "Add the peanuts and butter and cook 5 minutes, stirring.",
      "Add the bicarbonate and stir fast: it will foam.",
      "Spread 1 cm thick on a greased surface and cut into squares before it sets."],
  tp:["Work fast: it sets in minutes.",
      "Store in a closed jar so it doesn't go soft."],
  v:"brazilian peanut brittle"}},

{id:"frango-a-passarinho", c:"Brazil", r:"latin-america", m:"snack", t:60, s:4,
 i:[[1,"kg","chicken","protein","pollo en trozos pequeños","chicken in small pieces"],
    [6,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [2,"","citrus","acid","limones","limes","exprimidos","juiced"],
    [1.5,"tsp","salt","salt","sal","salt"],
    [60,"g","cornstarch","dredge","maicena","cornflour"],
    [750,"ml","oil","fat","aceite para freír","oil for frying"],
    [4,"clove","garlic","garnish","ajo (para dorar)","garlic (for frying)","laminado","sliced"],
    [1,"handful","herb","garnish","perejil","parsley","picada","chopped"]],
 es:{n:"Frango à passarinho", b:"Trocitos de pollo con hueso marinados en ajo y limón, fritos y cubiertos de ajo dorado. Tapa de bar brasileña.",
  st:["Marina el pollo con el ajo machacado, el limón y la sal 1 hora.",
      "Escurre y pasa por la maicena.",
      "Fríe a 170 °C en tandas 10 minutos, hasta que esté dorado y cocido.",
      "Fríe el ajo laminado en el mismo aceite 1 minuto, hasta que dore.",
      "Cubre el pollo con el ajo y el perejil."],
  tp:["Pide al carnicero que corte el pollo en trozos de 4 cm con hueso.",
      "No frías el ajo laminado demasiado: amarga en segundos."],
  v:"frango a passarinho"},
 en:{n:"Frango à Passarinho (Brazilian Garlic Fried Chicken Bites)", b:"Small bone-in chicken pieces marinated in garlic and lime, fried and topped with golden garlic. A Brazilian bar snack.",
  st:["Marinate the chicken with the crushed garlic, lime and salt for 1 hour.",
      "Drain and dredge in the cornflour.",
      "Fry at 170 °C in batches for 10 minutes, until golden and cooked through.",
      "Fry the sliced garlic in the same oil for 1 minute, until golden.",
      "Top the chicken with the garlic and parsley."],
  tp:["Ask the butcher to chop the chicken into 4 cm bone-in pieces.",
      "Don't overfry the sliced garlic: it turns bitter in seconds."],
  v:"brazilian garlic chicken bites"}}
];
