module.exports = [
{id:"congri", c:"Cuba", r:"caribbean", m:"side", t:120, s:6,
 i:[[250,"g","legume","structure","frijoles colorados secos","dried red kidney beans"],
    [1.5,"l","water","liquid","agua","water"],
    [100,"g","bacon","protein","tocino","bacon","en daditos","diced"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","ají pimiento","bell pepper","picado","chopped"],
    [4,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"tsp","spice","aromatic","comino","cumin"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [400,"g","rice","structure","arroz","rice"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Congrí", b:"Arroz cocido junto con frijoles colorados y tocino. El arroz de Oriente en Cuba.",
  st:["Remoja los frijoles 8 horas. Cuécelos en el agua 60 minutos. Guarda 800 ml del caldo.",
      "Fríe el tocino en el aceite 5 minutos. Añade la cebolla, el ají, el ajo, el comino y el orégano y cocina 6 minutos.",
      "Añade el arroz y remueve 2 minutos.",
      "Añade los frijoles, el caldo reservado y la sal. Cuece destapado hasta que se seque la superficie.",
      "Tapa y cuece 20 minutos a fuego bajo."],
  tp:["El caldo de los frijoles da el color al arroz.",
      "No destapes durante los últimos 20 minutos."],
  v:"congrí cubano"},
 en:{n:"Congrí (Cuban Red Beans and Rice)", b:"Rice cooked with red beans and bacon. The rice of eastern Cuba.",
  st:["Soak the beans 8 hours. Simmer them in the water for 60 minutes. Keep 800 ml of the liquid.",
      "Fry the bacon in the oil for 5 minutes. Add the onion, pepper, garlic, cumin and oregano and cook 6 minutes.",
      "Add the rice and stir 2 minutes.",
      "Add the beans, reserved liquid and salt. Cook uncovered until the surface dries.",
      "Cover and cook 20 minutes on low."],
  tp:["The bean liquid gives the rice its colour.",
      "Don't lift the lid for the last 20 minutes."],
  v:"cuban congri"}},

{id:"potaje-de-garbanzos", c:"Cuba", r:"caribbean", m:"soup", t:120, s:6,
 i:[[400,"g","legume","structure","garbanzos secos","dried chickpeas"],
    [2,"l","water","liquid","agua","water"],
    [150,"g","chorizo","protein","chorizo","chorizo","en rodajas","sliced"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","ají pimiento","bell pepper","picado","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [150,"g","tomato","liquid","salsa de tomate natural","tomato passata"],
    [300,"g","potato","structure","papas","potatoes","en cubos","cubed"],
    [300,"g","veg","structure","calabaza","pumpkin","en cubos","cubed"],
    [1,"tsp","paprika","aromatic","pimentón","paprika"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Potaje de garbanzos", b:"Garbanzos guisados con chorizo, papa y calabaza. Plato de herencia española en la mesa cubana.",
  st:["Remoja los garbanzos 12 horas. Cuécelos en el agua 80 minutos.",
      "Fríe el chorizo en el aceite 3 minutos. Añade la cebolla, el ají y el ajo y cocina 6 minutos.",
      "Añade el tomate y el pimentón y cocina 5 minutos.",
      "Añade el sofrito, la papa, la calabaza y la sal a los garbanzos y cuece 25 minutos."],
  tp:["La calabaza se deshace y espesa el potaje.",
      "Mejor al día siguiente."],
  v:"potaje de garbanzos cubano"},
 en:{n:"Potaje de Garbanzos (Cuban Chickpea Stew)", b:"Chickpeas stewed with chorizo, potato and pumpkin. A dish of Spanish heritage on the Cuban table.",
  st:["Soak the chickpeas 12 hours. Simmer them in the water for 80 minutes.",
      "Fry the chorizo in the oil for 3 minutes. Add the onion, pepper and garlic and cook 6 minutes.",
      "Add the tomato and paprika and cook 5 minutes.",
      "Add this, the potato, pumpkin and salt to the chickpeas and simmer 25 minutes."],
  tp:["The pumpkin melts in and thickens the stew.",
      "Better the next day."],
  v:"cuban chickpea stew"}},

{id:"cafecito-cubano", c:"Cuba", r:"caribbean", m:"drink", t:10, s:4,
 i:[[25,"g","coffee","aromatic","café molido fino oscuro","finely ground dark-roast coffee"],
    [200,"ml","water","liquid","agua","water"],
    [4,"tbsp","sugar","sweet","azúcar","sugar"]],
 es:{n:"Cafecito cubano", b:"Café fuerte con una espumita de azúcar batida. El ritual de todas las horas en Cuba y Miami.",
  st:["Prepara el café en una cafetera italiana con el agua.",
      "Cuando salgan las primeras gotas, viértelas sobre el azúcar en una taza.",
      "Bate el azúcar con esas gotas 1 minuto, hasta que forme una crema clara.",
      "Añade el resto del café y remueve: la espumita sube a la superficie.",
      "Sirve en tacitas pequeñas."],
  tp:["Las primeras gotas son las más concentradas: son las que hacen la espuma.",
      "Bate con fuerza: la espumita es la marca del buen cafecito."],
  v:"cafecito cubano con espumita"},
 en:{n:"Cafecito (Cuban Coffee)", b:"Strong coffee topped with whipped sugar foam. An all-day ritual in Cuba and Miami.",
  st:["Brew the coffee in a stovetop espresso pot with the water.",
      "When the first drops come out, pour them over the sugar in a cup.",
      "Whisk the sugar with those drops for 1 minute, into a pale cream.",
      "Add the rest of the coffee and stir: the foam rises to the top.",
      "Serve in small cups."],
  tp:["The first drops are the strongest: they make the foam.",
      "Whisk hard: the foam is the mark of a good cafecito."],
  v:"cuban cafecito"}},

{id:"batido-de-mamey", c:"Cuba", r:"caribbean", m:"drink", t:5, s:2,
 i:[[300,"g","fruit","structure","pulpa de mamey","mamey pulp"],
    [300,"ml","milk","liquid","leche fría","cold milk"],
    [2,"tbsp","sugar","sweet","azúcar","sugar"],
    [150,"g","ice","liquid","hielo","ice"]],
 es:{n:"Batido de mamey", b:"Batido espeso y anaranjado de mamey con leche. El batido favorito de las cafeterías cubanas.",
  st:["Pon el mamey, la leche, el azúcar y el hielo en la licuadora.",
      "Licúa 1 minuto, hasta que quede espeso y liso.",
      "Sirve de inmediato."],
  tp:["El mamey congelado funciona igual de bien.",
      "Si queda muy espeso, añade un poco más de leche."],
  v:"batido de mamey cubano"},
 en:{n:"Batido de Mamey (Mamey Milkshake)", b:"A thick, orange mamey and milk shake. The favourite shake of Cuban cafés.",
  st:["Put the mamey, milk, sugar and ice in the blender.",
      "Blend 1 minute, until thick and smooth.",
      "Serve at once."],
  tp:["Frozen mamey works just as well.",
      "If too thick, add a little more milk."],
  v:"cuban mamey shake"}},

{id:"carne-guisada-boricua", c:"Puerto Rico", r:"caribbean", m:"main", t:120, s:6,
 i:[[1,"kg","beef","protein","carne de res para guisar","beef stewing meat","en cubos","cubed"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","pimiento verde","green bell pepper","picado","chopped"],
    [4,"","bellpepper","aromatic","ajíes dulces","sweet ají peppers","picados","chopped"],
    [4,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"handful","herb","aromatic","recao (culantro)","culantro","picado","chopped"],
    [200,"g","tomato","liquid","salsa de tomate natural","tomato passata"],
    [1,"tsp","achiote","aromatic","achiote molido","ground annatto"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [500,"ml","water","liquid","agua","water"],
    [3,"","potato","structure","papas","potatoes","en cubos","cubed"],
    [2,"","veg","structure","zanahorias","carrots","en rodajas","sliced"],
    [60,"g","olives","umami","aceitunas","olives"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Carne guisada", b:"Carne de res guisada con papas, zanahoria y aceitunas en salsa de tomate. Comida de casa boricua.",
  st:["Sala la carne y dórala en el aceite 8 minutos.",
      "Añade la cebolla, los pimientos, los ajíes, el ajo y el recao y cocina 6 minutos.",
      "Añade el tomate, el achiote, el orégano y el agua. Tapa y cuece 60 minutos.",
      "Añade las papas, la zanahoria y las aceitunas y cuece 30 minutos más."],
  tp:["Sírvela con arroz blanco.",
      "Si espesa demasiado, añade agua caliente."],
  v:"carne guisada puertorriqueña"},
 en:{n:"Carne Guisada (Puerto Rican Beef Stew)", b:"Beef stewed with potatoes, carrots and olives in tomato sauce. Puerto Rican home cooking.",
  st:["Salt the beef and brown it in the oil for 8 minutes.",
      "Add the onion, peppers, ají, garlic and culantro and cook 6 minutes.",
      "Add the tomato, annatto, oregano and water. Cover and simmer 60 minutes.",
      "Add the potatoes, carrots and olives and cook 30 minutes more."],
  tp:["Serve with white rice.",
      "If it thickens too much, add hot water."],
  v:"puerto rican carne guisada"}},

{id:"mallorcas", c:"Puerto Rico", r:"caribbean", m:"bread", t:180, s:12,
 i:[[500,"g","apflour","structure","harina de trigo","plain flour"],
    [7,"g","yeast","leaven","levadura seca","dried yeast"],
    [100,"g","sugar","sweet","azúcar","sugar"],
    [0.5,"tsp","salt","salt","sal","salt"],
    [200,"ml","milk","liquid","leche tibia","warm milk"],
    [4,"","eggyolk","enrich","yemas de huevo","egg yolks"],
    [120,"g","butter","fat","mantequilla blanda","soft butter"],
    [30,"g","butter","glaze","mantequilla derretida (para pintar)","melted butter (for brushing)"],
    [60,"g","icingsugar","garnish","azúcar glas","icing sugar"]],
 es:{n:"Mallorcas", b:"Panes dulces en espiral cubiertos de azúcar glas. El desayuno de las panaderías de San Juan.",
  st:["Mezcla la harina, la levadura, el azúcar y la sal. Añade la leche y las yemas y amasa 5 minutos.",
      "Añade la mantequilla blanda poco a poco y amasa 10 minutos, hasta que la masa esté lisa. Deja levar 90 minutos.",
      "Divide en 12, estira cada porción en un cordón de 30 cm, pinta con mantequilla derretida y enrolla en espiral.",
      "Deja levar 45 minutos y hornea a 180 °C 18 minutos.",
      "Pinta con el resto de la mantequilla y cubre con el azúcar glas."],
  tp:["La masa es blanda y pegajosa: no añadas más harina de la necesaria.",
      "Se comen tibias."],
  v:"mallorcas puertorriqueñas"},
 en:{n:"Mallorcas (Puerto Rican Sweet Rolls)", b:"Spiral sweet rolls dusted with icing sugar. Breakfast at San Juan's bakeries.",
  st:["Mix the flour, yeast, sugar and salt. Add the milk and yolks and knead 5 minutes.",
      "Add the soft butter gradually and knead 10 minutes, until smooth. Rise 90 minutes.",
      "Divide into 12, roll each into a 30 cm rope, brush with melted butter and coil into a spiral.",
      "Rise 45 minutes and bake at 180 °C for 18 minutes.",
      "Brush with the rest of the butter and cover with the icing sugar."],
  tp:["The dough is soft and sticky: don't add more flour than needed.",
      "Eat them warm."],
  v:"puerto rican mallorcas"}},

{id:"sorullitos", c:"Puerto Rico", r:"caribbean", m:"snack", t:40, s:20,
 i:[[500,"ml","water","liquid","agua","water"],
    [1,"tsp","salt","salt","sal","salt"],
    [2,"tbsp","sugar","sweet","azúcar","sugar"],
    [250,"g","cornmeal","structure","harina de maíz fina","fine cornmeal"],
    [150,"g","cheese","enrich","queso Edam o cheddar rallado","grated Edam or cheddar"],
    [750,"ml","oil","fat","aceite para freír","oil for frying"]],
 es:{n:"Sorullitos de maíz", b:"Deditos fritos de harina de maíz con queso. Botana de los chinchorros de Puerto Rico.",
  st:["Hierve el agua con la sal y el azúcar.",
      "Añade la harina de maíz de golpe y remueve 3 minutos a fuego bajo, hasta que se despegue.",
      "Añade el queso y mezcla. Deja entibiar.",
      "Forma cilindros de 8 cm.",
      "Fríe a 180 °C 3 minutos, hasta que estén dorados."],
  tp:["Forma los sorullitos con la masa tibia: fría se agrieta.",
      "Sírvelos recién hechos."],
  v:"sorullitos de maíz con queso"},
 en:{n:"Sorullitos (Puerto Rican Corn Fritters)", b:"Fried cornmeal fingers with cheese. A snack from Puerto Rico's roadside stands.",
  st:["Bring the water to the boil with the salt and sugar.",
      "Tip in the cornmeal and stir 3 minutes on low, until it pulls away.",
      "Add the cheese and mix. Let it cool slightly.",
      "Roll into 8 cm logs.",
      "Fry at 180 °C for 3 minutes, until golden."],
  tp:["Shape them while the dough is warm: cold, it cracks.",
      "Serve them fresh."],
  v:"puerto rican sorullitos"}},

{id:"chivo-guisado", c:"Dominican Republic", r:"caribbean", m:"main", t:150, s:6,
 i:[[1.2,"kg","goat","protein","chivo en trozos","goat, in pieces"],
    [3,"","citrus","acid","naranjas agrias o limones","sour oranges or limes","exprimidos","juiced"],
    [4,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [1,"tsp","herb","aromatic","orégano dominicano seco","dried oregano"],
    [2,"tsp","salt","salt","sal","salt"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"tbsp","sugar","caramel","azúcar","sugar"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","ají cubanela","cubanelle pepper","picado","chopped"],
    [2,"tbsp","tomatopaste","aromatic","pasta de tomate","tomato paste"],
    [750,"ml","water","liquid","agua","water"],
    [1,"handful","herb","garnish","cilantro","coriander","picado","chopped"]],
 es:{n:"Chivo guisado", b:"Chivo marinado en naranja agria y orégano y guisado despacio. Especialidad de Montecristi, en la República Dominicana.",
  st:["Marina el chivo con el jugo, el ajo, el orégano y la sal 4 horas.",
      "Calienta el aceite con el azúcar hasta que se ponga oscuro. Dora el chivo escurrido 10 minutos.",
      "Añade la cebolla, el ají y la pasta de tomate y cocina 5 minutos.",
      "Añade la marinada y el agua, tapa y cuece 90 minutos a fuego bajo, hasta que esté tierno.",
      "Termina con el cilantro."],
  tp:["Marinado toda la noche queda más suave.",
      "Sírvelo con arroz blanco."],
  v:"chivo guisado dominicano"},
 en:{n:"Chivo Guisado (Dominican Goat Stew)", b:"Goat marinated in sour orange and oregano and stewed slowly. A speciality of Montecristi, Dominican Republic.",
  st:["Marinate the goat with the juice, garlic, oregano and salt for 4 hours.",
      "Heat the oil with the sugar until dark. Brown the drained goat for 10 minutes.",
      "Add the onion, pepper and tomato paste and cook 5 minutes.",
      "Add the marinade and water, cover and simmer 90 minutes on low, until tender.",
      "Finish with the coriander."],
  tp:["Marinated overnight it's more tender.",
      "Serve with white rice."],
  v:"dominican goat stew"}},

{id:"yaniqueques", c:"Dominican Republic", r:"caribbean", m:"snack", t:40, s:12,
 i:[[300,"g","apflour","structure","harina de trigo","plain flour"],
    [2,"tsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [1,"tsp","salt","salt","sal","salt"],
    [30,"g","butter","fat","mantequilla","butter"],
    [180,"ml","water","liquid","agua","water"],
    [750,"ml","oil","fat","aceite para freír","oil for frying"]],
 es:{n:"Yaniqueques", b:"Discos finos de masa frita, crujientes y salados. Se venden en las playas de Boca Chica.",
  st:["Mezcla la harina, el polvo de hornear y la sal. Frota la mantequilla.",
      "Añade el agua y amasa 5 minutos. Deja reposar 30 minutos.",
      "Divide en 12 bolas y estíralas muy finas, de 15 cm. Haz un corte en el centro de cada una.",
      "Fríe a 180 °C 1 minuto por lado, hasta que estén dorados y crujientes."],
  tp:["El corte en el centro evita que se inflen.",
      "Espolvorea con sal gruesa al sacarlos."],
  v:"yaniqueques dominicanos"},
 en:{n:"Yaniqueques (Dominican Johnny Cakes)", b:"Thin fried dough discs, crisp and salty. Sold on the beaches of Boca Chica.",
  st:["Mix the flour, baking powder and salt. Rub in the butter.",
      "Add the water and knead 5 minutes. Rest 30 minutes.",
      "Divide into 12 balls and roll very thin, to 15 cm. Cut a slit in the centre of each.",
      "Fry at 180 °C for 1 minute per side, until golden and crisp."],
  tp:["The slit stops them puffing up.",
      "Sprinkle with coarse salt as they come out."],
  v:"dominican yaniqueques"}},

{id:"arepa-dominicana", c:"Dominican Republic", r:"caribbean", m:"sweet", t:90, s:10,
 i:[[300,"g","cornmeal","structure","harina de maíz","cornmeal"],
    [400,"ml","coconutmilk","liquid","leche de coco","coconut milk"],
    [400,"ml","milk","liquid","leche","milk"],
    [200,"g","sugar","sweet","azúcar","sugar"],
    [60,"g","butter","fat","mantequilla derretida","melted butter"],
    [60,"g","driedfruit","sweet","pasas","raisins"],
    [1,"tsp","spice","aromatic","canela molida","ground cinnamon"],
    [1,"tsp","vanilla","aromatic","esencia de vainilla","vanilla extract"],
    [0.5,"tsp","salt","salt","sal","salt"]],
 es:{n:"Arepa dominicana", b:"No es la arepa venezolana: es un bizcocho húmedo de maíz con coco, pasas y canela. Merienda dominicana.",
  st:["Mezcla la harina de maíz con la leche de coco y la leche y deja reposar 15 minutos.",
      "Añade el azúcar, la mantequilla, las pasas, la canela, la vainilla y la sal.",
      "Cuece a fuego medio 8 minutos, removiendo, hasta que espese.",
      "Vierte en un molde de 22 cm engrasado.",
      "Hornea a 180 °C 50 minutos, hasta que esté dorada."],
  tp:["Deja enfriar antes de cortar para que se asiente.",
      "Tradicionalmente se hacía en caldero con brasas encima."],
  v:"arepa dominicana de maíz y coco"},
 en:{n:"Arepa Dominicana (Dominican Coconut Cornmeal Cake)", b:"Not the Venezuelan arepa: a moist cornmeal cake with coconut, raisins and cinnamon. A Dominican afternoon treat.",
  st:["Mix the cornmeal with the coconut milk and milk and rest 15 minutes.",
      "Add the sugar, butter, raisins, cinnamon, vanilla and salt.",
      "Cook over medium heat for 8 minutes, stirring, until thick.",
      "Pour into a greased 22 cm tin.",
      "Bake at 180 °C for 50 minutes, until golden."],
  tp:["Let it cool before slicing so it sets.",
      "It was traditionally made in a pot with embers on the lid."],
  v:"dominican arepa cake"}}
];
