module.exports = [
{id:"sofrito-boricua", c:"Puerto Rico", r:"caribbean", m:"sauce", t:15, s:16,
 i:[[2,"","onion","aromatic","cebollas","onions","en trozos","in chunks"],
    [1,"","bellpepper","aromatic","pimiento verde cubanela","cubanelle pepper","en trozos","in chunks"],
    [10,"","bellpepper","aromatic","ajíes dulces","ajíes dulces (sweet peppers)"],
    [1,"","garlic","aromatic","cabeza de ajo","head of garlic","pelada","peeled"],
    [1,"bunch","herb","aromatic","recao (culantro)","culantro (recao)"],
    [1,"bunch","herb","aromatic","cilantro","cilantro"],
    [2,"tbsp","oliveoil","fat","aceite de oliva","olive oil"]],
 es:{n:"Sofrito boricua", b:"La base verde de la cocina puertorriqueña: ajíes dulces, recao, cilantro, cebolla y ajo molidos.",
  st:["Lava y seca bien las hierbas.",
      "Pon la cebolla, los pimientos y el ajo en el procesador y tritura 30 segundos.",
      "Añade el recao, el cilantro y el aceite y tritura hasta tener una pasta gruesa.",
      "Pasa a frascos limpios.",
      "Guarda en la nevera hasta 1 semana o congela en cubiteras."],
  tp:["Congelado en cubitos, cada cubo equivale a 2 cucharadas para un guiso.",
      "El recao es más intenso que el cilantro; si no lo encuentras, usa doble de cilantro."],
  v:"sofrito puertorriqueño receta"},
 en:{n:"Puerto Rican Sofrito", b:"The green base of Puerto Rican cooking: sweet peppers, recao, cilantro, onion and garlic, ground together.",
  st:["Wash and dry the herbs well.",
      "Put the onion, peppers and garlic in a food processor and blitz 30 seconds.",
      "Add the recao, cilantro and oil and blitz to a coarse paste.",
      "Transfer to clean jars.",
      "Keep in the fridge up to 1 week or freeze in ice-cube trays."],
  tp:["Frozen in cubes, each cube is 2 tablespoons for a stew.",
      "Recao is stronger than cilantro; if you can't find it, use double the cilantro."],
  v:"puerto rican sofrito recipe"}},

{id:"alcapurrias", c:"Puerto Rico", r:"caribbean", m:"snack", t:90, s:12,
 i:[[500,"g","veg","structure","yautía (malanga)","yautía (taro root)","pelada y rallada fina","peeled and finely grated"],
    [2,"","plantain","structure","guineos verdes (bananas verdes)","green bananas","pelados y rallados finos","peeled and finely grated"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"tsp","achiote","aromatic","achiote en polvo","ground annatto"],
    [2,"tsp","salt","salt","sal","salt"],
    [400,"g","beef","protein","carne molida de res","ground beef"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","pimiento verde","green bell pepper","picado","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [60,"g","olives","umami","aceitunas verdes","green olives","picadas","chopped"],
    [100,"g","tomato","sauce","salsa de tomate natural","plain tomato sauce"],
    [1,"l","oil","fat","aceite para freír","oil for frying"]],
 es:{n:"Alcapurrias", b:"Frituras de masa de yautía y guineo verde rellenas de carne guisada. De los kioscos de Piñones.",
  st:["Sofríe la cebolla, el pimiento y el ajo en 1 cucharada de aceite 5 minutos. Añade la carne, la salsa de tomate, las aceitunas y 1 cucharadita de sal y cuece 15 minutos. Enfría.",
      "Mezcla la yautía y el guineo rallados con el resto del aceite, el achiote y el resto de la sal. Refrigera 30 minutos.",
      "Extiende 3 cucharadas de masa sobre un papel encerado mojado, pon relleno en el centro y dobla para cubrirlo.",
      "Dale forma alargada y deslízala al aceite caliente.",
      "Fríe a 175 °C durante 6 minutos, hasta que estén doradas."],
  tp:["Refrigerar la masa la hace más fácil de manejar.",
      "Usa guantes al rallar el guineo verde: su savia mancha."],
  v:"alcapurrias puertorriqueñas receta"},
 en:{n:"Alcapurrias (Taro and Green Banana Fritters)", b:"Fritters of taro and green banana dough filled with stewed beef. From the beach kiosks of Piñones.",
  st:["Cook the onion, pepper and garlic in 1 tablespoon of oil for 5 minutes. Add the beef, tomato sauce, olives and 1 teaspoon of salt and cook 15 minutes. Cool.",
      "Mix the grated taro and banana with the rest of the oil, the annatto and the rest of the salt. Chill 30 minutes.",
      "Spread 3 tablespoons of dough on wet waxed paper, put filling in the centre and fold to cover.",
      "Shape into a log and slide into the hot oil.",
      "Fry at 175 °C for 6 minutes, until golden."],
  tp:["Chilling the dough makes it easier to handle.",
      "Wear gloves to grate green banana: its sap stains."],
  v:"alcapurrias recipe"}},

{id:"pastelon", c:"Puerto Rico", r:"caribbean", m:"main", t:75, s:8, o:180,
 i:[[5,"","plantain","structure","plátanos maduros","ripe plantains","en tiras a lo largo","in lengthwise strips"],
    [500,"ml","oil","fat","aceite para freír","oil for frying"],
    [600,"g","beef","protein","carne molida de res","ground beef"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","pimiento verde","green bell pepper","picado","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [150,"g","tomato","sauce","salsa de tomate natural","plain tomato sauce"],
    [60,"g","olives","umami","aceitunas verdes","green olives","picadas","chopped"],
    [1,"tsp","salt","salt","sal","salt"],
    [150,"g","cheese","glaze","queso mozzarella o cheddar","mozzarella or cheddar","rallado","grated"],
    [3,"","egg","binder","huevos batidos","beaten eggs"]],
 es:{n:"Pastelón de amarillos", b:"Lasaña boricua de plátano maduro frito con carne guisada y queso. Dulce y salada.",
  st:["Fríe las tiras de plátano a 170 °C durante 4 minutos, hasta que estén doradas. Escurre.",
      "Sofríe la cebolla, el pimiento y el ajo 5 minutos. Añade la carne, la salsa de tomate, las aceitunas y la sal y cuece 15 minutos.",
      "Engrasa un molde de 22 x 30 cm y vierte la mitad del huevo. Pon una capa de plátano, la carne y la mitad del queso.",
      "Cubre con otra capa de plátano, el resto del huevo y el resto del queso.",
      "Hornea a 180 °C durante 30 minutos, hasta que esté dorado. Reposa 10 minutos antes de cortar."],
  tp:["Usa plátanos muy maduros, con la cáscara negra.",
      "El huevo une las capas para cortar porciones limpias."],
  v:"pastelón de amarillos receta"},
 en:{n:"Pastelón (Puerto Rican Plantain Lasagna)", b:"A Puerto Rican lasagna of fried ripe plantain with stewed beef and cheese. Sweet and savoury.",
  st:["Fry the plantain strips at 170 °C for 4 minutes, until golden. Drain.",
      "Cook the onion, pepper and garlic 5 minutes. Add the beef, tomato sauce, olives and salt and cook 15 minutes.",
      "Grease a 22 x 30 cm dish and pour in half the egg. Layer plantain, the beef and half the cheese.",
      "Top with another layer of plantain, the rest of the egg and the rest of the cheese.",
      "Bake at 180 °C for 30 minutes, until golden. Rest 10 minutes before cutting."],
  tp:["Use very ripe plantains, with black skins.",
      "The egg binds the layers so you can cut clean portions."],
  v:"pastelon recipe"}},

{id:"coquito", c:"Puerto Rico", r:"caribbean", m:"drink", t:15, s:12,
 i:[[400,"ml","creamofcoconut","structure","crema de coco endulzada (tipo Coco López)","sweetened coconut cream (Coco López style)"],
    [400,"ml","coconutmilk","liquid","leche de coco","coconut milk"],
    [395,"g","condensedmilk","sweet","leche condensada","condensed milk"],
    [350,"ml","evaporatedmilk","liquid","leche evaporada","evaporated milk"],
    [250,"ml","spirit","liquid","ron blanco","white rum"],
    [1,"tsp","spice","aromatic","canela molida","ground cinnamon"],
    [1,"pinch","spice","aromatic","nuez moscada","nutmeg"],
    [4,"","spice","garnish","ramas de canela","cinnamon sticks"]],
 es:{n:"Coquito", b:"Bebida navideña de coco, leches y ron con canela. El ponche de Navidad de Puerto Rico, bien frío.",
  st:["Licúa la crema de coco, la leche de coco, la leche condensada y la leche evaporada 1 minuto.",
      "Añade el ron, la canela y la nuez moscada y licúa 30 segundos.",
      "Pasa a botellas con una rama de canela en cada una.",
      "Refrigera al menos 4 horas.",
      "Agita antes de servir en vasitos pequeños."],
  tp:["Sin ron queda un coquito para toda la familia.",
      "Se guarda 2 semanas en la nevera."],
  v:"coquito receta puertorriqueña"},
 en:{n:"Coquito (Puerto Rican Coconut Eggnog)", b:"A Christmas drink of coconut, milks and rum with cinnamon. Puerto Rico's holiday punch, served cold.",
  st:["Blend the sweetened coconut cream, coconut milk, condensed milk and evaporated milk for 1 minute.",
      "Add the rum, cinnamon and nutmeg and blend 30 seconds.",
      "Pour into bottles with a cinnamon stick in each.",
      "Refrigerate at least 4 hours.",
      "Shake before serving in small glasses."],
  tp:["Without rum it's a coquito for the whole family.",
      "Keeps 2 weeks in the fridge."],
  v:"coquito recipe"}},

{id:"chimi-dominicano", c:"Dominican Republic", r:"caribbean", m:"main", t:40, s:4,
 i:[[500,"g","beef","protein","carne molida de res","ground beef"],
    [0.5,"","onion","aromatic","cebolla","onion","picada fina","finely chopped"],
    [1,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [1,"tsp","salt","salt","sal","salt"],
    [4,"","bread","structure","panes de agua o de hamburguesa","soft rolls"],
    [200,"g","veg","structure","repollo","cabbage","en tiras finas","finely shredded"],
    [1,"","onion","aromatic","cebolla roja","red onion","en aros","in rings"],
    [2,"","tomato","structure","tomates","tomatoes","en rodajas","sliced"],
    [4,"tbsp","ketchup","sauce","kétchup","ketchup"],
    [4,"tbsp","mayo","sauce","mayonesa","mayonnaise"]],
 es:{n:"Chimi dominicano", b:"La hamburguesa de la calle dominicana: carne sazonada, repollo, cebolla y salsa de kétchup y mayonesa.",
  st:["Mezcla la carne con la cebolla picada, el ajo, el orégano y la sal. Forma 4 hamburguesas delgadas.",
      "Cocina en una plancha caliente 3 minutos por lado.",
      "Mezcla el kétchup con la mayonesa.",
      "Tuesta los panes.",
      "Arma con la carne, el repollo, la cebolla roja, el tomate y la salsa."],
  tp:["El repollo va crudo y en abundancia; es parte del chimi.",
      "Aplana bien la carne para que quede fina como en los carritos."],
  v:"chimi dominicano receta"},
 en:{n:"Chimi (Dominican Street Burger)", b:"The Dominican street burger: seasoned beef, cabbage, onion and a ketchup-mayonnaise sauce.",
  st:["Mix the beef with the chopped onion, garlic, oregano and salt. Shape 4 thin patties.",
      "Cook on a hot griddle for 3 minutes a side.",
      "Mix the ketchup with the mayonnaise.",
      "Toast the rolls.",
      "Build with the beef, cabbage, red onion, tomato and sauce."],
  tp:["The cabbage goes in raw and plentiful; it's part of the chimi.",
      "Press the patties thin, like the street carts do."],
  v:"dominican chimi recipe"}},

{id:"moro-de-guandules", c:"Dominican Republic", r:"caribbean", m:"main", t:50, s:6,
 i:[[3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","ají morrón","bell pepper","picado","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"tbsp","tomatopaste","umami","pasta de tomate","tomato paste"],
    [1,"handful","herb","aromatic","cilantro","cilantro","picado","chopped"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [450,"g","legume","protein","guandules cocidos","cooked pigeon peas","escurridos","drained"],
    [400,"ml","coconutmilk","liquid","leche de coco","coconut milk"],
    [400,"ml","water","liquid","agua","water"],
    [400,"g","rice","structure","arroz","rice"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Moro de guandules con coco", b:"Arroz dominicano cocido con guandules y leche de coco. Plato de Navidad y de domingo.",
  st:["Sofríe la cebolla, el ají y el ajo en el aceite 5 minutos. Añade la pasta de tomate, el cilantro y el orégano.",
      "Añade los guandules y cuece 3 minutos.",
      "Añade la leche de coco, el agua y la sal y hierve.",
      "Añade el arroz y cuece sin tapar hasta que el líquido baje al nivel del arroz.",
      "Voltea, tapa y cuece 20 minutos a fuego bajo."],
  tp:["El concón, la capa tostada del fondo, es muy apreciado.",
      "Sin leche de coco, usa todo agua: queda un moro clásico."],
  v:"moro de guandules con coco receta"},
 en:{n:"Moro de Guandules (Rice with Pigeon Peas and Coconut)", b:"Dominican rice cooked with pigeon peas and coconut milk. A Christmas and Sunday dish.",
  st:["Cook the onion, pepper and garlic in the oil for 5 minutes. Add the tomato paste, cilantro and oregano.",
      "Add the pigeon peas and cook 3 minutes.",
      "Add the coconut milk, water and salt and bring to a boil.",
      "Add the rice and cook uncovered until the liquid drops to the level of the rice.",
      "Stir once, cover and cook 20 minutes on low."],
  tp:["The concón, the toasted crust on the bottom, is prized.",
      "Without coconut milk, use all water: it becomes a classic moro."],
  v:"moro de guandules recipe"}},

{id:"griot", c:"Haiti", r:"caribbean", m:"main", t:150, s:6,
 i:[[1.5,"kg","pork","protein","paleta de cerdo","pork shoulder","en dados de 4 cm","in 4 cm cubes"],
    [2,"","citrus","acid","naranjas agrias (o 1 naranja y 2 limas)","sour oranges (or 1 orange and 2 limes)","en jugo","juiced"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [4,"","scallion","aromatic","cebolletas","scallions","picadas","chopped"],
    [4,"clove","garlic","aromatic","ajo","garlic"],
    [1,"","bellpepper","aromatic","pimiento","bell pepper","picado","chopped"],
    [1,"","chilli","aromatic","chile scotch bonnet","scotch bonnet chilli"],
    [1,"handful","herb","aromatic","perejil y tomillo","parsley and thyme"],
    [2,"tsp","salt","salt","sal","salt"],
    [500,"ml","water","liquid","agua","water"],
    [500,"ml","oil","fat","aceite para freír","oil for frying"]],
 es:{n:"Griot", b:"Cerdo marinado en naranja agria y epis, cocido y luego frito hasta dorar. El plato de fiesta de Haití.",
  st:["Licúa la cebolla, las cebolletas, el ajo, el pimiento, el chile, las hierbas, el jugo de naranja y la sal para hacer el epis.",
      "Marina el cerdo en el epis al menos 4 horas.",
      "Cuece el cerdo con su marinada y el agua a fuego medio 60 minutos, hasta que esté tierno y el líquido casi se evapore.",
      "Escurre la carne.",
      "Fríe a 180 °C durante 5 minutos, hasta que esté dorada y crujiente."],
  tp:["Guarda el líquido de cocción para mojar la carne o el arroz.",
      "Se sirve con pikliz y bananos fritos."],
  v:"griot haitiano receta"},
 en:{n:"Griot (Haitian Fried Pork)", b:"Pork marinated in sour orange and epis, simmered then fried until golden. Haiti's party dish.",
  st:["Blend the onion, scallions, garlic, pepper, chilli, herbs, orange juice and salt to make the epis.",
      "Marinate the pork in the epis at least 4 hours.",
      "Cook the pork with its marinade and the water over medium heat for 60 minutes, until tender and the liquid has almost evaporated.",
      "Drain the meat.",
      "Fry at 180 °C for 5 minutes, until golden and crisp."],
  tp:["Keep the cooking liquid to spoon over the meat or rice.",
      "Served with pikliz and fried plantains."],
  v:"haitian griot recipe"}},

{id:"pikliz", c:"Haiti", r:"caribbean", m:"sauce", t:20, s:12,
 i:[[300,"g","veg","structure","repollo","cabbage","en tiras finas","finely shredded"],
    [2,"","veg","structure","zanahorias","carrots","en tiras finas","in fine strips"],
    [1,"","onion","aromatic","cebolla","onion","en pluma fina","thinly sliced"],
    [1,"","bellpepper","structure","pimiento","bell pepper","en tiras finas","in fine strips"],
    [4,"","chilli","aromatic","chiles scotch bonnet","scotch bonnet chillies","en rodajas","sliced"],
    [4,"clove","garlic","aromatic","ajo","garlic","en láminas","sliced"],
    [6,"","pepper","aromatic","granos de pimienta negra","black peppercorns"],
    [1,"tsp","salt","salt","sal","salt"],
    [500,"ml","whitevinegar","acid","vinagre blanco","white vinegar"],
    [1,"","citrus","acid","lima","lime","en jugo","juiced"]],
 es:{n:"Pikliz", b:"Encurtido picante de repollo, zanahoria y chile scotch bonnet en vinagre. Acompaña el griot y todo lo frito en Haití.",
  st:["Mezcla el repollo, la zanahoria, la cebolla, el pimiento, los chiles y el ajo.",
      "Pásalos a un frasco grande, apretando.",
      "Añade la pimienta y la sal.",
      "Cubre con el vinagre y el jugo de lima.",
      "Tapa y deja reposar al menos 24 horas en la nevera."],
  tp:["Usa guantes para cortar los scotch bonnet.",
      "Dura semanas en la nevera y cada día pica más."],
  v:"pikliz haitiano receta"},
 en:{n:"Pikliz (Haitian Spicy Pickled Slaw)", b:"A fiery pickle of cabbage, carrot and scotch bonnet in vinegar. Served with griot and anything fried in Haiti.",
  st:["Mix the cabbage, carrot, onion, pepper, chillies and garlic.",
      "Pack into a large jar.",
      "Add the peppercorns and salt.",
      "Cover with the vinegar and lime juice.",
      "Close and leave at least 24 hours in the fridge."],
  tp:["Wear gloves to cut the scotch bonnets.",
      "It keeps for weeks in the fridge and gets hotter each day."],
  v:"pikliz recipe"}},

{id:"rice-and-peas", c:"Jamaica", r:"caribbean", m:"side", t:45, s:6,
 i:[[400,"g","legume","protein","frijoles rojos cocidos","cooked kidney beans","escurridos","drained"],
    [400,"ml","coconutmilk","liquid","leche de coco","coconut milk"],
    [350,"ml","water","liquid","agua","water"],
    [3,"","scallion","aromatic","cebolletas","scallions","aplastadas","bruised"],
    [2,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [4,"sprig","herb","aromatic","tomillo","thyme"],
    [1,"","chilli","aromatic","chile scotch bonnet entero","whole scotch bonnet chilli"],
    [6,"","pepper","aromatic","pimienta de Jamaica en grano","allspice berries"],
    [400,"g","rice","structure","arroz de grano largo","long-grain rice","lavado","rinsed"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Rice and peas jamaicano", b:"Arroz cocido en leche de coco con frijoles rojos, tomillo y un scotch bonnet entero. El acompañante del domingo en Jamaica.",
  st:["Hierve los frijoles con la leche de coco, el agua, las cebolletas, el ajo, el tomillo, la pimienta de Jamaica y la sal.",
      "Pon el chile entero encima, sin romperlo.",
      "Añade el arroz y remueve una vez.",
      "Tapa y cuece a fuego bajo 20 minutos, hasta que el arroz absorba el líquido.",
      "Retira el chile, las cebolletas y el tomillo, y suelta el arroz con un tenedor."],
  tp:["El chile entero da aroma sin mucho picante; si se rompe, el arroz pica.",
      "En Jamaica los peas son frijoles rojos, no guisantes."],
  v:"jamaican rice and peas recipe"},
 en:{n:"Jamaican Rice and Peas", b:"Rice cooked in coconut milk with kidney beans, thyme and a whole scotch bonnet. Jamaica's Sunday side.",
  st:["Bring the beans to a boil with the coconut milk, water, scallions, garlic, thyme, allspice and salt.",
      "Lay the whole chilli on top without breaking it.",
      "Add the rice and stir once.",
      "Cover and cook on low for 20 minutes, until the rice absorbs the liquid.",
      "Remove the chilli, scallions and thyme and fluff with a fork."],
  tp:["The whole chilli adds aroma without much heat; if it bursts, the rice gets hot.",
      "In Jamaica the peas are kidney beans, not green peas."],
  v:"rice and peas recipe"}},

{id:"ackee-and-saltfish", c:"Jamaica", r:"caribbean", m:"breakfast", t:40, s:4,
 i:[[250,"g","whitefish","protein","bacalao salado","salt cod","desalado 12 horas","desalted 12 hours"],
    [540,"g","fruit","structure","ackee en lata","canned ackee","escurrido","drained"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","en pluma","sliced"],
    [3,"","scallion","aromatic","cebolletas","scallions","picadas","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"","bellpepper","aromatic","pimiento","bell pepper","en tiras","in strips"],
    [1,"","tomato","structure","tomate","tomato","picado","chopped"],
    [0.5,"","chilli","aromatic","chile scotch bonnet","scotch bonnet chilli","picado","chopped"],
    [2,"sprig","herb","aromatic","tomillo","thyme"],
    [0.5,"tsp","pepper","aromatic","pimienta negra","black pepper"]],
 es:{n:"Ackee and saltfish", b:"El plato nacional de Jamaica: fruta de ackee salteada con bacalao, cebolla, tomate y scotch bonnet.",
  st:["Cuece el bacalao desalado en agua 10 minutos. Escurre y desmenuza, quitando piel y espinas.",
      "Sofríe la cebolla, las cebolletas, el ajo, el pimiento, el chile y el tomillo en el aceite 5 minutos.",
      "Añade el tomate y el bacalao y cuece 3 minutos.",
      "Añade el ackee con cuidado y mezcla suavemente para no deshacerlo. Calienta 3 minutos.",
      "Espolvorea la pimienta y sirve."],
  tp:["Usa ackee en lata: el ackee fresco sin madurar del todo es tóxico.",
      "No añadas sal: el bacalao ya la aporta."],
  v:"ackee and saltfish recipe"},
 en:{n:"Ackee and Saltfish", b:"Jamaica's national dish: ackee fruit sautéed with salt cod, onion, tomato and scotch bonnet.",
  st:["Simmer the desalted cod in water for 10 minutes. Drain and flake, removing skin and bones.",
      "Cook the onion, scallions, garlic, pepper, chilli and thyme in the oil for 5 minutes.",
      "Add the tomato and cod and cook 3 minutes.",
      "Add the ackee carefully and fold gently so it doesn't break. Heat 3 minutes.",
      "Sprinkle with the pepper and serve."],
  tp:["Use canned ackee: fresh ackee that isn't fully ripe is toxic.",
      "Don't add salt: the cod brings it."],
  v:"ackee and saltfish recipe"}}
];
