module.exports = [
{id:"fricase-de-pollo", c:"Cuba", r:"caribbean", m:"main", t:75, s:4,
 i:[[1.2,"kg","chicken","protein","pollo en presas","chicken pieces"],
    [3,"","citrus","acid","naranjas agrias (o 2 naranjas y 1 limón)","sour oranges (or 2 oranges and 1 lime)","exprimidas","juiced"],
    [4,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","ají pimiento verde","green bell pepper","picado","chopped"],
    [200,"g","tomato","liquid","salsa de tomate natural","tomato passata"],
    [120,"ml","winewhite","liquid","vino seco","dry white wine"],
    [250,"ml","water","liquid","agua","water"],
    [3,"","potato","structure","papas","potatoes","en trozos","in chunks"],
    [60,"g","olives","umami","aceitunas verdes","green olives"],
    [40,"g","driedfruit","sweet","pasas","raisins"],
    [1,"tsp","spice","aromatic","comino","cumin"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Fricasé de pollo", b:"Pollo marinado en naranja agria y guisado con papas, aceitunas y pasas. Almuerzo de domingo cubano.",
  st:["Marina el pollo con el jugo de naranja, el ajo y la sal 1 hora.",
      "Escurre el pollo y dóralo en el aceite 8 minutos. Sácalo.",
      "Sofríe la cebolla y el ají 6 minutos. Añade el comino y el orégano.",
      "Añade el tomate, el vino, el agua, la marinada y el pollo. Tapa y cuece 25 minutos.",
      "Añade las papas, las aceitunas y las pasas y cuece 20 minutos más, hasta que las papas estén tiernas."],
  tp:["Sírvelo con arroz blanco.",
      "Si la salsa queda muy líquida, destapa los últimos 10 minutos."],
  v:"fricasé de pollo cubano"},
 en:{n:"Fricasé de Pollo (Cuban Chicken Fricassee)", b:"Chicken marinated in sour orange and stewed with potatoes, olives and raisins. Cuban Sunday lunch.",
  st:["Marinate the chicken with the orange juice, garlic and salt for 1 hour.",
      "Drain the chicken and brown it in the oil for 8 minutes. Remove.",
      "Cook the onion and pepper for 6 minutes. Add the cumin and oregano.",
      "Add the tomato, wine, water, marinade and chicken. Cover and simmer 25 minutes.",
      "Add the potatoes, olives and raisins and cook 20 minutes more, until the potatoes are tender."],
  tp:["Serve with white rice.",
      "If the sauce is thin, uncover for the last 10 minutes."],
  v:"cuban chicken fricassee"}},

{id:"bistec-de-palomilla", c:"Cuba", r:"caribbean", m:"main", t:30, s:4,
 i:[[4,"slice","beef","protein","bistecs finos de palomilla (tapa de cadera)","thin top sirloin steaks"],
    [4,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [3,"","citrus","acid","limones","limes","exprimidos","juiced"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"pinch","pepper","aromatic","pimienta","pepper"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","en aros finos","in thin rings"],
    [1,"handful","herb","garnish","perejil","parsley","picado","chopped"]],
 es:{n:"Bistec de palomilla", b:"Bistec finísimo marinado en ajo y limón, con cebolla por encima. El bistec de todas las cafeterías cubanas.",
  st:["Marina los bistecs con el ajo, el limón, la sal y la pimienta 30 minutos.",
      "Calienta el aceite a fuego fuerte y cocina los bistecs 1 minuto por lado. Sácalos.",
      "Saltea la cebolla en la misma sartén 3 minutos con la marinada.",
      "Pon la cebolla sobre los bistecs y termina con el perejil."],
  tp:["Aplana los bistecs con un mazo si no son finos.",
      "No lo marines más de 1 hora: el limón endurece la carne."],
  v:"bistec de palomilla cubano"},
 en:{n:"Bistec de Palomilla (Cuban Steak)", b:"A very thin steak marinated in garlic and lime, topped with onions. The steak of every Cuban café.",
  st:["Marinate the steaks with the garlic, lime, salt and pepper for 30 minutes.",
      "Heat the oil over high heat and cook the steaks 1 minute per side. Remove.",
      "Sauté the onion in the same pan for 3 minutes with the marinade.",
      "Pile the onion on the steaks and finish with the parsley."],
  tp:["Pound the steaks with a mallet if they aren't thin.",
      "Don't marinate over 1 hour: the lime toughens the meat."],
  v:"cuban palomilla steak"}},

{id:"masitas-de-puerco", c:"Cuba", r:"caribbean", m:"main", t:120, s:4,
 i:[[1,"kg","pork","protein","paleta de cerdo","pork shoulder","en cubos de 4 cm","in 4 cm cubes"],
    [3,"","citrus","acid","naranjas agrias (o 2 naranjas y 1 limón)","sour oranges (or 2 oranges and 1 lime)","exprimidas","juiced"],
    [6,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [1,"tsp","spice","aromatic","comino","cumin"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [2,"tsp","salt","salt","sal","salt"],
    [250,"ml","water","liquid","agua","water"],
    [500,"ml","oil","fat","aceite para freír","oil for frying"],
    [1,"","onion","garnish","cebolla","onion","en aros finos","in thin rings"]],
 es:{n:"Masitas de puerco fritas", b:"Trozos de cerdo marinados en mojo, cocidos y luego fritos hasta quedar crujientes. Infaltables en la mesa cubana.",
  st:["Marina el cerdo con la naranja, el ajo, el comino, el orégano y la sal 2 horas.",
      "Pon el cerdo con la marinada y el agua en una olla. Cuece tapado 60 minutos.",
      "Destapa y cuece hasta que se evapore el líquido.",
      "Fríe las masitas en el aceite a 180 °C 4 minutos, hasta que estén doradas.",
      "Sirve con la cebolla cruda por encima."],
  tp:["Sécalas bien antes de freír para que no salpiquen.",
      "Guarda un poco de marinada para rociarlas al servir."],
  v:"masitas de puerco fritas cubanas"},
 en:{n:"Masitas de Puerco (Cuban Fried Pork Chunks)", b:"Pork chunks marinated in mojo, braised, then fried until crisp. A must on the Cuban table.",
  st:["Marinate the pork with the orange, garlic, cumin, oregano and salt for 2 hours.",
      "Put the pork with the marinade and water in a pot. Simmer covered for 60 minutes.",
      "Uncover and cook until the liquid has evaporated.",
      "Fry the chunks in the oil at 180 °C for 4 minutes, until golden.",
      "Serve with the raw onion on top."],
  tp:["Pat them dry before frying so they don't spit.",
      "Keep back some marinade to drizzle over when serving."],
  v:"cuban fried pork chunks masitas"}},

{id:"ajiaco-cubano", c:"Cuba", r:"caribbean", m:"soup", t:150, s:8,
 i:[[500,"g","pork","protein","carne de cerdo","pork shoulder","en trozos","in pieces"],
    [500,"g","beef","protein","falda de res","beef flank","en trozos","in pieces"],
    [3,"l","water","liquid","agua","water"],
    [300,"g","cassava","structure","yuca","cassava","en trozos","in chunks"],
    [300,"g","veg","structure","malanga","malanga (taro)","en trozos","in chunks"],
    [300,"g","veg","structure","boniato","white sweet potato","en trozos","in chunks"],
    [300,"g","veg","structure","calabaza","pumpkin","en trozos","in chunks"],
    [1,"","plantain","structure","plátano verde","green plantain","en rodajas","sliced"],
    [2,"","corn","structure","mazorcas de maíz","corn cobs","en rodajas de 3 cm","in 3 cm rounds"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","ají pimiento","bell pepper","picado","chopped"],
    [4,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [200,"g","tomato","liquid","salsa de tomate natural","tomato passata"],
    [1,"tsp","spice","aromatic","comino","cumin"],
    [3,"tsp","salt","salt","sal","salt"],
    [1,"","citrus","acid","limón","lime"]],
 es:{n:"Ajiaco cubano", b:"El gran caldo campesino de Cuba: carnes y todas las viandas de la tierra, cocidas hasta que espesan el caldo.",
  st:["Cuece las carnes en el agua 60 minutos, espumando.",
      "Añade la yuca, la malanga y el maíz y cuece 20 minutos.",
      "Añade el boniato, la calabaza y el plátano y cuece 20 minutos más.",
      "Sofríe la cebolla, el ají y el ajo en el aceite 6 minutos. Añade el tomate y el comino y cocina 5 minutos.",
      "Añade el sofrito al caldo con la sal y cuece 15 minutos. Aplasta algunas viandas para espesar.",
      "Sirve con unas gotas de limón."],
  tp:["La calabaza se deshace y le da color y cuerpo al caldo.",
      "Mejor al día siguiente, como todo guiso."],
  v:"ajiaco cubano tradicional"},
 en:{n:"Ajiaco Cubano (Cuban Root Vegetable Stew)", b:"Cuba's great country stew: meats and every root vegetable, cooked until they thicken the broth.",
  st:["Simmer the meats in the water for 60 minutes, skimming.",
      "Add the cassava, malanga and corn and cook 20 minutes.",
      "Add the sweet potato, pumpkin and plantain and cook 20 minutes more.",
      "Cook the onion, pepper and garlic in the oil for 6 minutes. Add the tomato and cumin and cook 5 minutes.",
      "Stir this into the pot with the salt and cook 15 minutes. Crush some vegetables to thicken.",
      "Serve with a squeeze of lime."],
  tp:["The pumpkin melts in and gives the broth colour and body.",
      "Better the next day, like any stew."],
  v:"cuban ajiaco stew"}},

{id:"bacalaitos", c:"Puerto Rico", r:"caribbean", m:"snack", t:40, s:16,
 i:[[250,"g","whitefish","protein","bacalao salado desalado","desalted salt cod","desmenuzado","flaked"],
    [250,"g","apflour","structure","harina de trigo","plain flour"],
    [2,"tsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [300,"ml","water","liquid","agua","water"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"handful","herb","aromatic","culantro o cilantro","culantro or coriander","picado","chopped"],
    [1,"tsp","achiote","aromatic","achiote molido","ground annatto"],
    [750,"ml","oil","fat","aceite para freír","oil for frying"]],
 es:{n:"Bacalaítos", b:"Frituras finas y crujientes de bacalao. Se compran en los kioskos de la playa de Piñones en Puerto Rico.",
  st:["Desala el bacalao 24 horas en agua fría, cambiando el agua 3 veces. Desmenúzalo.",
      "Mezcla la harina, el polvo de hornear y el achiote. Añade el agua y bate hasta tener una masa líquida.",
      "Añade el bacalao, el ajo y el culantro.",
      "Fríe cucharones de masa a 180 °C 2 minutos por lado, extendiéndolos finos.",
      "Escurre en papel y sirve caliente."],
  tp:["Prueba el bacalao antes de mezclar: si está salado, remójalo más.",
      "Deben quedar finos y con bordes crujientes."],
  v:"bacalaítos puertorriqueños"},
 en:{n:"Bacalaítos (Salt Cod Fritters)", b:"Thin, crisp salt cod fritters. Sold at the beach kiosks of Piñones, Puerto Rico.",
  st:["Soak the cod for 24 hours in cold water, changing the water 3 times. Flake it.",
      "Mix the flour, baking powder and annatto. Add the water and whisk to a runny batter.",
      "Add the cod, garlic and culantro.",
      "Fry ladlefuls of batter at 180 °C for 2 minutes per side, spreading them thin.",
      "Drain on paper and serve hot."],
  tp:["Taste the cod before mixing: if it's salty, soak it longer.",
      "They should be thin with crisp edges."],
  v:"puerto rican bacalaitos"}},

{id:"asopao-de-pollo", c:"Puerto Rico", r:"caribbean", m:"soup", t:70, s:6,
 i:[[1,"kg","chicken","protein","muslos de pollo","chicken thighs"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","pimiento verde","green bell pepper","picado","chopped"],
    [4,"","bellpepper","aromatic","ajíes dulces","sweet ají peppers","picados","chopped"],
    [4,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"handful","herb","aromatic","culantro y cilantro","culantro and coriander","picados","chopped"],
    [2,"tbsp","tomatopaste","aromatic","pasta de tomate","tomato paste"],
    [1,"tsp","achiote","aromatic","achiote molido","ground annatto"],
    [2,"l","water","liquid","agua","water"],
    [250,"g","rice","structure","arroz de grano medio","medium-grain rice"],
    [60,"g","olives","umami","aceitunas","olives"],
    [1,"tbsp","capers","umami","alcaparras","capers"],
    [150,"g","legume","garnish","guisantes","green peas"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Asopao de pollo", b:"Arroz caldoso con pollo, aceitunas y alcaparras. La sopa de los días de lluvia en Puerto Rico.",
  st:["Sala el pollo y dóralo en el aceite 8 minutos.",
      "Añade la cebolla, los pimientos, los ajíes, el ajo y las hierbas y sofríe 6 minutos.",
      "Añade la pasta de tomate, el achiote y el agua. Cuece 30 minutos.",
      "Saca el pollo, desmenúzalo y devuélvelo a la olla sin huesos.",
      "Añade el arroz, las aceitunas y las alcaparras y cuece 18 minutos. Añade los guisantes los últimos 3 minutos."],
  tp:["Debe quedar entre sopa y arroz: añade agua si espesa demasiado.",
      "Sírvelo en cuanto esté, porque el arroz sigue absorbiendo."],
  v:"asopao de pollo puertorriqueño"},
 en:{n:"Asopao de Pollo (Puerto Rican Chicken and Rice Soup)", b:"Soupy rice with chicken, olives and capers. Puerto Rico's rainy-day soup.",
  st:["Salt the chicken and brown it in the oil for 8 minutes.",
      "Add the onion, peppers, ají, garlic and herbs and cook 6 minutes.",
      "Add the tomato paste, annatto and water. Simmer 30 minutes.",
      "Lift out the chicken, shred it and return it to the pot without the bones.",
      "Add the rice, olives and capers and cook 18 minutes. Add the peas for the last 3 minutes."],
  tp:["It should sit between soup and rice: add water if it gets too thick.",
      "Serve straight away, as the rice keeps absorbing."],
  v:"puerto rican asopao de pollo"}},

{id:"arroz-con-dulce", c:"Puerto Rico", r:"caribbean", m:"sweet", t:90, s:8,
 i:[[250,"g","rice","structure","arroz de grano corto","short-grain rice"],
    [750,"ml","water","liquid","agua","water"],
    [1,"piece","spice","aromatic","trozo de jengibre","piece of ginger","en rodajas","sliced"],
    [4,"piece","spice","aromatic","clavos de olor","cloves"],
    [2,"piece","spice","aromatic","ramas de canela","cinnamon sticks"],
    [800,"ml","coconutmilk","liquid","leche de coco","coconut milk"],
    [150,"g","sugar","sweet","azúcar","sugar"],
    [60,"g","driedfruit","sweet","pasas","raisins"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"tsp","spice","garnish","canela molida","ground cinnamon"]],
 es:{n:"Arroz con dulce", b:"Arroz cocido en leche de coco con jengibre, canela y clavo. El postre navideño de Puerto Rico.",
  st:["Remoja el arroz 1 hora y escúrrelo.",
      "Hierve el agua con el jengibre, el clavo y la canela 10 minutos. Cuela.",
      "Cuece el arroz en esa agua con la leche de coco y la sal 25 minutos, removiendo.",
      "Añade el azúcar y las pasas y cuece 10 minutos más, hasta que espese.",
      "Pasa a una fuente, deja enfriar y espolvorea la canela molida."],
  tp:["Remueve a menudo al final: el coco se pega fácil.",
      "Se come frío, en cuadritos."],
  v:"arroz con dulce boricua"},
 en:{n:"Arroz con Dulce (Coconut Rice Pudding)", b:"Rice cooked in coconut milk with ginger, cinnamon and clove. Puerto Rico's Christmas dessert.",
  st:["Soak the rice 1 hour and drain.",
      "Boil the water with the ginger, cloves and cinnamon for 10 minutes. Strain.",
      "Cook the rice in that water with the coconut milk and salt for 25 minutes, stirring.",
      "Add the sugar and raisins and cook 10 minutes more, until thick.",
      "Spread in a dish, cool and dust with the ground cinnamon."],
  tp:["Stir often at the end: coconut catches easily.",
      "It's eaten cold, in squares."],
  v:"puerto rican arroz con dulce"}},

{id:"locrio-de-pollo", c:"Dominican Republic", r:"caribbean", m:"main", t:60, s:6,
 i:[[1,"kg","chicken","protein","pollo en presas pequeñas","chicken in small pieces"],
    [2,"","citrus","acid","limones","limes","exprimidos","juiced"],
    [3,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"tbsp","sugar","caramel","azúcar","sugar"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","ají morrón","bell pepper","picado","chopped"],
    [2,"tbsp","tomatopaste","aromatic","pasta de tomate","tomato paste"],
    [400,"g","rice","structure","arroz","rice"],
    [900,"ml","water","liquid","agua","water"],
    [60,"g","olives","umami","aceitunas","olives"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Locrio de pollo", b:"Arroz con pollo dominicano, con el pollo dorado en azúcar quemada para darle color.",
  st:["Marina el pollo con el limón, el ajo, el orégano y la sal 30 minutos.",
      "Calienta el aceite con el azúcar hasta que se ponga caramelo oscuro. Dora el pollo 8 minutos.",
      "Añade la cebolla, el ají y la pasta de tomate y cocina 5 minutos.",
      "Añade el agua y las aceitunas y hierve. Añade el arroz y cuece destapado hasta que se seque la superficie.",
      "Tapa y cuece 20 minutos a fuego bajo."],
  tp:["Cuidado con el azúcar: si se quema de más amarga.",
      "El concón del fondo es lo más buscado."],
  v:"locrio de pollo dominicano"},
 en:{n:"Locrio de Pollo (Dominican Chicken and Rice)", b:"Dominican chicken and rice, with the chicken browned in burnt sugar for colour.",
  st:["Marinate the chicken with the lime, garlic, oregano and salt for 30 minutes.",
      "Heat the oil with the sugar until it turns dark caramel. Brown the chicken 8 minutes.",
      "Add the onion, pepper and tomato paste and cook 5 minutes.",
      "Add the water and olives and boil. Add the rice and cook uncovered until the surface dries.",
      "Cover and cook 20 minutes on low."],
  tp:["Watch the sugar: if it burns too far it turns bitter.",
      "The crust at the bottom, the concón, is the best part."],
  v:"dominican locrio de pollo"}},

{id:"morir-sonando", c:"Dominican Republic", r:"caribbean", m:"drink", t:10, s:4,
 i:[[500,"ml","milk","liquid","leche fría","cold milk"],
    [400,"ml","fruit","liquid","jugo de naranja","orange juice"],
    [60,"g","sugar","sweet","azúcar","sugar"],
    [1,"tsp","vanilla","aromatic","esencia de vainilla","vanilla extract"],
    [300,"g","ice","liquid","hielo","ice"]],
 es:{n:"Morir soñando", b:"Leche con jugo de naranja, bien fría. La bebida más querida de la República Dominicana.",
  st:["Mezcla la leche con el azúcar y la vainilla hasta que se disuelva.",
      "Pon el hielo en una jarra y añade la leche.",
      "Añade el jugo de naranja poco a poco, removiendo sin parar.",
      "Sirve de inmediato."],
  tp:["Todo debe estar muy frío y el jugo se añade a la leche, no al revés: así no se corta.",
      "Hazlo justo antes de servir."],
  v:"morir soñando dominicano"},
 en:{n:"Morir Soñando (Orange Milk Cooler)", b:"Ice-cold milk with orange juice. The Dominican Republic's best-loved drink.",
  st:["Mix the milk with the sugar and vanilla until dissolved.",
      "Put the ice in a jug and add the milk.",
      "Pour in the orange juice gradually, stirring constantly.",
      "Serve at once."],
  tp:["Keep everything very cold and add the juice to the milk, not the other way round, so it doesn't curdle.",
      "Make it just before serving."],
  v:"dominican morir sonando"}},

{id:"piononos-boricuas", c:"Puerto Rico", r:"caribbean", m:"starter", t:60, s:8,
 i:[[3,"","plantain","structure","plátanos maduros","ripe plantains"],
    [500,"ml","oil","fat","aceite para freír","oil for frying"],
    [1,"tbsp","oil","fat","aceite (para el relleno)","oil (for the filling)"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","pimiento verde","green bell pepper","picado","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [300,"g","beef","protein","carne molida de res","minced beef"],
    [100,"g","tomato","liquid","salsa de tomate natural","tomato passata"],
    [30,"g","olives","umami","aceitunas","olives","picadas","chopped"],
    [1,"tsp","salt","salt","sal","salt"],
    [3,"","egg","binder","huevos batidos","beaten eggs"]],
 es:{n:"Piononos boricuas", b:"Tiras de plátano maduro enrolladas en círculo, rellenas de picadillo y fritas con huevo. Fritura puertorriqueña.",
  st:["Corta los plátanos a lo largo en 4 tiras cada uno y fríelas 2 minutos, sin dorar. Escurre.",
      "Sofríe la cebolla, el pimiento y el ajo en el aceite del relleno 5 minutos. Añade la carne, el tomate, las aceitunas y la sal y cocina 12 minutos.",
      "Forma un aro con cada tira de plátano, sujeta con un palillo y rellena con la carne.",
      "Pasa cada pionono por el huevo por ambos lados.",
      "Fríelos 2 minutos por lado hasta que estén dorados. Quita los palillos."],
  tp:["Los plátanos deben estar amarillos con manchas negras: así se doblan sin romperse.",
      "Pon un poco de huevo en la sartén y apoya el pionono encima para sellar la base."],
  v:"piononos de plátano maduro"},
 en:{n:"Piononos (Stuffed Plantain Rings)", b:"Ripe plantain strips curled into rings, filled with picadillo and fried in egg. A Puerto Rican fritter.",
  st:["Cut each plantain lengthways into 4 strips and fry them 2 minutes, without browning. Drain.",
      "Cook the onion, pepper and garlic in the filling oil for 5 minutes. Add the beef, tomato, olives and salt and cook 12 minutes.",
      "Curl each plantain strip into a ring, pin with a toothpick and fill with the beef.",
      "Dip each pionono in the egg on both sides.",
      "Fry 2 minutes per side until golden. Remove the toothpicks."],
  tp:["The plantains should be yellow with black spots: that way they bend without breaking.",
      "Pour a little egg into the pan and set the pionono on it to seal the base."],
  v:"puerto rican piononos"}}
];
