module.exports = [
{id:"doubles", c:"Trinidad and Tobago", r:"caribbean", m:"snack", t:120, s:8,
 i:[[300,"g","apflour","structure","harina de trigo","plain flour"],
    [1,"tsp","yeast","leaven","levadura seca","dried yeast"],
    [1,"tsp","spice","aromatic","cúrcuma","turmeric"],
    [1,"tsp","sugar","sweet","azúcar","sugar"],
    [0.5,"tsp","salt","salt","sal","salt"],
    [200,"ml","water","liquid","agua tibia","warm water"],
    [500,"g","legume","structure","garbanzos cocidos","cooked chickpeas"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"tbsp","currypowder","aromatic","curry en polvo","curry powder"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [400,"ml","water","liquid","agua (segunda parte)","water (second part)"],
    [1,"tsp","salt","salt","sal (para los garbanzos)","salt (for the chickpeas)"],
    [750,"ml","oil","fat","aceite para freír","oil for frying"],
    [1,"","chilli","garnish","chile Scotch bonnet","Scotch bonnet chilli","picado","chopped"]],
 es:{n:"Doubles", b:"Dos panes fritos y suaves con curry de garbanzos. El desayuno callejero de Trinidad.",
  st:["Mezcla la harina, la levadura, la cúrcuma, el azúcar, la sal y el agua tibia. Amasa 5 minutos y deja levar 1 hora.",
      "Sofríe la cebolla y el ajo en el aceite 5 minutos. Añade el curry y el comino y cocina 1 minuto.",
      "Añade los garbanzos, el agua de la segunda parte y la sal. Cuece 20 minutos, aplastando algunos, hasta que espese.",
      "Divide la masa en 16 bolitas y aplánalas a 10 cm con las manos aceitadas.",
      "Fríe a 180 °C 30 segundos por lado. Pon garbanzos entre dos panes y sirve con el chile."],
  tp:["Los panes, llamados bara, deben quedar suaves, no crujientes.",
      "El chile va aparte para cada quien."],
  v:"doubles de trinidad"},
 en:{n:"Doubles (Trinidad Curried Chickpea Flatbreads)", b:"Two soft fried breads with curried chickpeas. Trinidad's street breakfast.",
  st:["Mix the flour, yeast, turmeric, sugar, salt and warm water. Knead 5 minutes and rise 1 hour.",
      "Cook the onion and garlic in the oil for 5 minutes. Add the curry and cumin and cook 1 minute.",
      "Add the chickpeas, the second part of the water and the salt. Simmer 20 minutes, crushing some, until thick.",
      "Divide the dough into 16 balls and flatten to 10 cm with oiled hands.",
      "Fry at 180 °C for 30 seconds per side. Sandwich chickpeas between two breads and serve with the chilli."],
  tp:["The breads, called bara, should be soft, not crisp.",
      "Serve the chilli on the side."],
  v:"trinidad doubles"}},

{id:"pelau", c:"Trinidad and Tobago", r:"caribbean", m:"main", t:75, s:6,
 i:[[1,"kg","chicken","protein","muslos de pollo","chicken thighs","en trozos","in pieces"],
    [4,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [1,"bunch","herb","aromatic","cilantro, tomillo y culantro","coriander, thyme and culantro","picados","chopped"],
    [3,"","scallion","aromatic","cebolletas","spring onions","picadas","chopped"],
    [2,"tsp","salt","salt","sal","salt"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [3,"tbsp","brownsugar","caramel","azúcar moreno","brown sugar"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [400,"g","rice","structure","arroz de grano largo","long-grain rice"],
    [400,"g","legume","structure","gandules cocidos","cooked pigeon peas"],
    [400,"ml","coconutmilk","liquid","leche de coco","coconut milk"],
    [400,"ml","water","liquid","agua","water"],
    [1,"","veg","structure","zanahoria","carrot","en dados","diced"],
    [1,"","chilli","aromatic","chile Scotch bonnet entero","whole Scotch bonnet chilli"]],
 es:{n:"Pelau", b:"Arroz con pollo caramelizado en azúcar, gandules y leche de coco. El plato de los domingos y las playas de Trinidad.",
  st:["Marina el pollo con el ajo, las hierbas, las cebolletas y la sal 1 hora.",
      "Calienta el aceite con el azúcar hasta que esté casi negro y humee. Añade el pollo y dóralo 8 minutos.",
      "Añade la cebolla y el arroz y remueve 2 minutos.",
      "Añade los gandules, la leche de coco, el agua, la zanahoria y el chile entero.",
      "Tapa y cuece 25 minutos a fuego bajo. Retira el chile y sirve."],
  tp:["El azúcar quemado da el color marrón: no te asustes cuando humee, pero no dejes que se queme del todo.",
      "El chile entero perfuma sin picar mucho: no lo rompas."],
  v:"pelau trinitense"},
 en:{n:"Pelau (Trinidad Caramelised Chicken and Rice)", b:"Chicken caramelised in sugar, cooked with rice, pigeon peas and coconut milk. Trinidad's Sunday and beach-day dish.",
  st:["Marinate the chicken with the garlic, herbs, spring onions and salt for 1 hour.",
      "Heat the oil with the sugar until almost black and smoking. Add the chicken and brown 8 minutes.",
      "Add the onion and rice and stir 2 minutes.",
      "Add the pigeon peas, coconut milk, water, carrot and whole chilli.",
      "Cover and cook 25 minutes on low. Remove the chilli and serve."],
  tp:["The burnt sugar gives the brown colour: don't panic when it smokes, but don't let it burn through.",
      "The whole chilli perfumes without much heat: don't let it burst."],
  v:"trinidad pelau"}},

{id:"callaloo-tt", c:"Trinidad and Tobago", r:"caribbean", m:"soup", t:50, s:6,
 i:[[500,"g","veg","structure","hojas de dasheen o espinaca","dasheen leaves or spinach"],
    [200,"g","veg","structure","okra (quimbombó)","okra","en rodajas","sliced"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"","scallion","aromatic","cebolletas","spring onions","picadas","chopped"],
    [2,"sprig","herb","aromatic","tomillo","thyme"],
    [400,"ml","coconutmilk","liquid","leche de coco","coconut milk"],
    [500,"ml","water","liquid","agua","water"],
    [1,"","chilli","aromatic","chile Scotch bonnet entero","whole Scotch bonnet chilli"],
    [30,"g","butter","fat","mantequilla","butter"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Callaloo", b:"Sopa espesa y verde de hojas de dasheen, okra y leche de coco. Acompaña el almuerzo del domingo en Trinidad.",
  st:["Pon las hojas, la okra, la cebolla, el ajo, las cebolletas y el tomillo en una olla.",
      "Añade la leche de coco, el agua y el chile entero.",
      "Cuece tapado 30 minutos, hasta que todo esté muy tierno.",
      "Retira el chile y el tomillo. Añade la mantequilla y la sal.",
      "Bate con una batidora de mano hasta que quede liso."],
  tp:["Si usas hojas de dasheen, cuécelas bien: crudas irritan la garganta.",
      "No rompas el chile o picará mucho."],
  v:"callaloo trinitense"},
 en:{n:"Callaloo (Trinidad Greens and Coconut Soup)", b:"A thick green soup of dasheen leaves, okra and coconut milk. Part of Sunday lunch in Trinidad.",
  st:["Put the leaves, okra, onion, garlic, spring onions and thyme in a pot.",
      "Add the coconut milk, water and whole chilli.",
      "Cover and simmer 30 minutes, until everything is very soft.",
      "Remove the chilli and thyme. Add the butter and salt.",
      "Blend smooth with a stick blender."],
  tp:["If using dasheen leaves, cook them thoroughly: raw, they irritate the throat.",
      "Don't burst the chilli or it'll be very hot."],
  v:"trinidad callaloo"}},

{id:"sorrel-drink", c:"Jamaica", ce:"Trinidad and Tobago", r:"caribbean", m:"drink", t:30, s:8,
 i:[[100,"g","herb","structure","flor de jamaica seca","dried sorrel (hibiscus)"],
    [2,"l","water","liquid","agua","water"],
    [50,"g","spice","aromatic","jengibre fresco","fresh ginger","en rodajas","sliced"],
    [6,"piece","spice","aromatic","clavos de olor","cloves"],
    [1,"piece","spice","aromatic","rama de canela","cinnamon stick"],
    [1,"piece","citrus","aromatic","cáscara de naranja","orange peel strip"],
    [200,"g","sugar","sweet","azúcar","sugar"],
    [300,"g","ice","liquid","hielo","ice"]],
 es:{n:"Sorrel", b:"Bebida roja de flor de jamaica con jengibre y clavo. La bebida navideña de Jamaica y Trinidad.",
  st:["Hierve el agua con el jengibre, el clavo, la canela y la cáscara 5 minutos.",
      "Añade la flor de jamaica, apaga y deja reposar tapado 4 horas o toda la noche.",
      "Cuela y endulza con el azúcar.",
      "Sirve muy frío con hielo."],
  tp:["Cuanto más reposa, más intenso queda el jengibre.",
      "Se conserva 5 días en la nevera."],
  v:"sorrel jamaiquino"},
 en:{n:"Sorrel (Caribbean Hibiscus Ginger Drink)", b:"A red drink of hibiscus with ginger and clove. The Christmas drink of Jamaica and Trinidad.",
  st:["Boil the water with the ginger, cloves, cinnamon and peel for 5 minutes.",
      "Add the sorrel, turn off and steep, covered, for 4 hours or overnight.",
      "Strain and sweeten with the sugar.",
      "Serve very cold over ice."],
  tp:["The longer it steeps, the stronger the ginger.",
      "It keeps 5 days in the fridge."],
  v:"jamaican sorrel drink"}},

{id:"buljol", c:"Trinidad and Tobago", r:"caribbean", m:"breakfast", t:30, s:4,
 i:[[250,"g","whitefish","protein","bacalao salado desalado","desalted salt cod","desmenuzado","flaked"],
    [1,"","onion","aromatic","cebolla","onion","picada fina","finely chopped"],
    [2,"","tomato","aromatic","tomates","tomatoes","picados","chopped"],
    [0.5,"","bellpepper","aromatic","pimiento verde","green bell pepper","picado","chopped"],
    [0.5,"","chilli","aromatic","chile Scotch bonnet","Scotch bonnet chilli","picado fino","finely chopped"],
    [1,"handful","herb","aromatic","culantro o cilantro","culantro or coriander","picado","chopped"],
    [4,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [1,"","citrus","acid","limón","lime","exprimido","juiced"]],
 es:{n:"Buljol", b:"Ensalada de bacalao desmenuzado con tomate, cebolla y chile. Desayuno criollo de Trinidad.",
  st:["Desala el bacalao 24 horas en agua fría, cambiando el agua 3 veces.",
      "Hierve el bacalao 5 minutos, escurre y desmenúzalo muy fino.",
      "Mezcla con la cebolla, el tomate, el pimiento, el chile y la hierba.",
      "Aliña con el aceite y el limón.",
      "Sirve a temperatura ambiente."],
  tp:["Prueba el bacalao: si sigue muy salado, hiérvelo de nuevo en agua limpia.",
      "Déjalo reposar 15 minutos para que se mezclen los sabores."],
  v:"buljol trinitense"},
 en:{n:"Buljol (Trinidad Salt Fish Salad)", b:"Flaked salt cod with tomato, onion and chilli. A creole breakfast in Trinidad.",
  st:["Soak the cod for 24 hours in cold water, changing the water 3 times.",
      "Boil the cod 5 minutes, drain and flake it very finely.",
      "Mix with the onion, tomato, pepper, chilli and herb.",
      "Dress with the oil and lime.",
      "Serve at room temperature."],
  tp:["Taste the cod: if still very salty, boil it again in fresh water.",
      "Rest it 15 minutes so the flavours mingle."],
  v:"trinidad buljol"}},

{id:"festival", c:"Jamaica", r:"caribbean", m:"side", t:30, s:12,
 i:[[250,"g","apflour","structure","harina de trigo","plain flour"],
    [100,"g","cornmeal","structure","harina de maíz amarilla fina","fine yellow cornmeal"],
    [2,"tsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [3,"tbsp","sugar","sweet","azúcar","sugar"],
    [0.5,"tsp","salt","salt","sal","salt"],
    [1,"tsp","vanilla","aromatic","esencia de vainilla","vanilla extract"],
    [200,"ml","water","liquid","agua","water"],
    [750,"ml","oil","fat","aceite para freír","oil for frying"]],
 es:{n:"Festival", b:"Bollos fritos alargados de maíz, ligeramente dulces. Acompañan el pescado frito y el jerk en Jamaica.",
  st:["Mezcla la harina, la harina de maíz, el polvo de hornear, el azúcar y la sal.",
      "Añade la vainilla y el agua y amasa hasta tener una masa firme.",
      "Divide en 12 porciones y forma cilindros de 10 cm.",
      "Fríe a 170 °C 6 minutos, girándolos, hasta que estén dorados."],
  tp:["No los frías muy calientes o quedan crudos por dentro.",
      "Sírvelos recién hechos."],
  v:"festival jamaiquino"},
 en:{n:"Festival (Jamaican Fried Dumplings)", b:"Slightly sweet fried cornmeal dumplings. Served with fried fish and jerk in Jamaica.",
  st:["Mix the flour, cornmeal, baking powder, sugar and salt.",
      "Add the vanilla and water and knead into a firm dough.",
      "Divide into 12 and roll into 10 cm logs.",
      "Fry at 170 °C for 6 minutes, turning, until golden."],
  tp:["Don't fry too hot or they'll be raw inside.",
      "Serve them fresh."],
  v:"jamaican festival dumplings"}},

{id:"escovitch-fish", c:"Jamaica", r:"caribbean", m:"main", t:45, s:4,
 i:[[4,"fillet","whitefish","protein","pescados enteros pequeños o filetes (pargo)","small whole fish or fillets (snapper)"],
    [2,"","citrus","acid","limones","limes"],
    [2,"tsp","salt","salt","sal","salt"],
    [1,"tsp","pepper","aromatic","pimienta negra","black pepper"],
    [250,"ml","oil","fat","aceite para freír","oil for frying"],
    [1,"","onion","aromatic","cebolla","onion","en aros","in rings"],
    [1,"","veg","aromatic","zanahoria","carrot","en juliana","in matchsticks"],
    [1,"","bellpepper","aromatic","pimiento","bell pepper","en tiras","in strips"],
    [1,"","chilli","aromatic","chile Scotch bonnet","Scotch bonnet chilli","en rodajas","sliced"],
    [8,"piece","spice","aromatic","pimienta de Jamaica en grano","allspice berries"],
    [200,"ml","whitevinegar","acid","vinagre blanco","white vinegar"],
    [1,"tsp","sugar","sweet","azúcar","sugar"]],
 es:{n:"Pescado escovitch", b:"Pescado frito cubierto de verduras encurtidas en vinagre con chile y pimienta de Jamaica. Tradición del Viernes Santo jamaiquino.",
  st:["Frota el pescado con el limón, sécalo y sazónalo con la sal y la pimienta.",
      "Fríelo en el aceite 4 minutos por lado, hasta que esté crujiente. Escurre.",
      "Hierve el vinagre con el azúcar y la pimienta de Jamaica 2 minutos.",
      "Añade la cebolla, la zanahoria, el pimiento y el chile y cuece 1 minuto.",
      "Vierte las verduras y el vinagre caliente sobre el pescado. Deja reposar 30 minutos."],
  tp:["Está aún mejor al día siguiente.",
      "Seca muy bien el pescado para que no salpique."],
  v:"escovitch fish jamaiquino"},
 en:{n:"Escovitch Fish (Jamaican Pickled Fried Fish)", b:"Fried fish topped with vegetables pickled in vinegar with chilli and allspice. A Jamaican Good Friday tradition.",
  st:["Rub the fish with the lime, pat dry and season with the salt and pepper.",
      "Fry in the oil for 4 minutes per side, until crisp. Drain.",
      "Boil the vinegar with the sugar and allspice for 2 minutes.",
      "Add the onion, carrot, pepper and chilli and cook 1 minute.",
      "Pour the hot vegetables and vinegar over the fish. Rest 30 minutes."],
  tp:["It's even better the next day.",
      "Dry the fish well so it doesn't spit."],
  v:"jamaican escovitch fish"}},

{id:"curry-goat", c:"Jamaica", r:"caribbean", m:"main", t:180, s:6,
 i:[[1.2,"kg","goat","protein","carne de chivo con hueso","bone-in goat meat","en trozos","in pieces"],
    [3,"tbsp","currypowder","aromatic","curry jamaiquino en polvo","Jamaican curry powder"],
    [4,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [3,"","scallion","aromatic","cebolletas","spring onions","picadas","chopped"],
    [4,"sprig","herb","aromatic","tomillo","thyme"],
    [1,"tsp","spice","aromatic","pimienta de Jamaica molida","ground allspice"],
    [2,"tsp","salt","salt","sal","salt"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"l","water","liquid","agua","water"],
    [3,"","potato","structure","papas","potatoes","en trozos","in chunks"],
    [1,"","chilli","aromatic","chile Scotch bonnet entero","whole Scotch bonnet chilli"]],
 es:{n:"Curry de chivo", b:"Chivo marinado en curry y cocido despacio hasta deshacerse, con papas. El plato de fiesta de Jamaica.",
  st:["Marina el chivo con 2 cucharadas de curry, el ajo, la cebolla, las cebolletas, el tomillo, la pimienta de Jamaica y la sal toda la noche.",
      "Tuesta el resto del curry en el aceite 1 minuto.",
      "Añade el chivo y dora 10 minutos.",
      "Añade el agua y el chile entero, tapa y cuece 2 horas a fuego bajo.",
      "Añade las papas y cuece 25 minutos más, hasta que la salsa espese."],
  tp:["Tostar el curry en el aceite quita el sabor a crudo.",
      "Las papas se deshacen un poco y espesan la salsa."],
  v:"curry goat jamaiquino"},
 en:{n:"Curry Goat (Jamaican)", b:"Goat marinated in curry and cooked slowly until falling apart, with potatoes. Jamaica's party dish.",
  st:["Marinate the goat with 2 tablespoons of curry, the garlic, onion, spring onions, thyme, allspice and salt overnight.",
      "Toast the rest of the curry in the oil for 1 minute.",
      "Add the goat and brown 10 minutes.",
      "Add the water and whole chilli, cover and simmer 2 hours on low.",
      "Add the potatoes and cook 25 minutes more, until the sauce thickens."],
  tp:["Toasting the curry in oil takes away the raw taste.",
      "The potatoes break down a little and thicken the sauce."],
  v:"jamaican curry goat"}},

{id:"brown-stew-chicken", c:"Jamaica", r:"caribbean", m:"main", t:75, s:4,
 i:[[1.2,"kg","chicken","protein","pollo en presas","chicken pieces"],
    [3,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [3,"","scallion","aromatic","cebolletas","spring onions","picadas","chopped"],
    [3,"sprig","herb","aromatic","tomillo","thyme"],
    [1,"tsp","spice","aromatic","pimienta de Jamaica molida","ground allspice"],
    [2,"tsp","salt","salt","sal","salt"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [2,"tbsp","brownsugar","caramel","azúcar moreno","brown sugar"],
    [1,"","onion","aromatic","cebolla","onion","en tiras","in strips"],
    [1,"","bellpepper","aromatic","pimiento","bell pepper","en tiras","in strips"],
    [2,"","tomato","liquid","tomates","tomatoes","picados","chopped"],
    [2,"tbsp","ketchup","sauce","kétchup","ketchup"],
    [300,"ml","water","liquid","agua","water"],
    [1,"","chilli","aromatic","chile Scotch bonnet entero","whole Scotch bonnet chilli"]],
 es:{n:"Brown stew chicken", b:"Pollo dorado en azúcar quemada y guisado con tomate, pimiento y tomillo. Comida de casa jamaiquina.",
  st:["Marina el pollo con el ajo, las cebolletas, el tomillo, la pimienta de Jamaica y la sal 2 horas.",
      "Calienta el aceite con el azúcar hasta que esté oscuro. Dora el pollo 8 minutos.",
      "Añade la cebolla y el pimiento y cocina 3 minutos.",
      "Añade el tomate, el kétchup, el agua y el chile entero.",
      "Tapa y cuece 35 minutos, hasta que la salsa espese."],
  tp:["Retira el chile antes de servir si no lo quieres picante.",
      "Sírvelo con arroz blanco."],
  v:"brown stew chicken jamaiquino"},
 en:{n:"Brown Stew Chicken (Jamaican)", b:"Chicken browned in burnt sugar and stewed with tomato, pepper and thyme. Jamaican home cooking.",
  st:["Marinate the chicken with the garlic, spring onions, thyme, allspice and salt for 2 hours.",
      "Heat the oil with the sugar until dark. Brown the chicken 8 minutes.",
      "Add the onion and pepper and cook 3 minutes.",
      "Add the tomato, ketchup, water and whole chilli.",
      "Cover and simmer 35 minutes, until the sauce thickens."],
  tp:["Remove the chilli before serving for less heat.",
      "Serve with white rice."],
  v:"jamaican brown stew chicken"}},

{id:"macaroni-pie", c:"Trinidad and Tobago", r:"caribbean", m:"main", t:60, s:8,
 i:[[500,"g","pasta","structure","macarrones largos","long macaroni"],
    [40,"g","butter","fat","mantequilla","butter"],
    [300,"g","cheddar","enrich","queso cheddar","cheddar cheese","rallado","grated"],
    [360,"ml","evaporatedmilk","liquid","leche evaporada","evaporated milk"],
    [2,"","egg","set","huevos","eggs"],
    [0.5,"","onion","aromatic","cebolla","onion","rallada","grated"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"pinch","pepper","aromatic","pimienta","pepper"]],
 es:{n:"Macaroni pie", b:"Pastel de macarrones con queso que se corta en cuadrados. Nunca falta en el almuerzo del domingo en Trinidad y Barbados.",
  st:["Cuece los macarrones 2 minutos menos de lo que dice el paquete. Escurre y mezcla con la mantequilla.",
      "Bate la leche, los huevos, la cebolla, la sal y la pimienta.",
      "Mezcla la pasta con dos tercios del queso y la mezcla de huevo.",
      "Pasa a una fuente de 20 x 30 cm y cubre con el resto del queso.",
      "Hornea a 180 °C 35 minutos. Deja reposar 15 minutos y corta en cuadrados."],
  tp:["El reposo es clave para que se corte en porciones firmes.",
      "Un cheddar fuerte le da más sabor."],
  v:"macaroni pie trinitense"},
 en:{n:"Macaroni Pie (Caribbean Baked Mac and Cheese)", b:"A baked macaroni and cheese that slices into squares. Never missing from Sunday lunch in Trinidad and Barbados.",
  st:["Cook the macaroni 2 minutes less than the packet says. Drain and toss with the butter.",
      "Whisk the milk, eggs, onion, salt and pepper.",
      "Mix the pasta with two thirds of the cheese and the egg mixture.",
      "Tip into a 20 x 30 cm dish and top with the rest of the cheese.",
      "Bake at 180 °C for 35 minutes. Rest 15 minutes and cut into squares."],
  tp:["Resting is key so it slices into firm portions.",
      "A sharp cheddar gives more flavour."],
  v:"trinidad macaroni pie"}}
];
