module.exports = [
{id:"pastel-de-choclo", c:"Chile", r:"latin-america", m:"main", t:120, s:6, o:200,
 i:[[8,"","corn","structure","choclos frescos","fresh ears of corn","desgranados","kernels cut off"],
    [1,"handful","herb","aromatic","albahaca","basil"],
    [250,"ml","milk","liquid","leche","milk"],
    [40,"g","butter","fat","mantequilla","butter"],
    [2,"tsp","salt","salt","sal","salt"],
    [500,"g","beef","protein","carne molida de res","ground beef"],
    [3,"","onion","aromatic","cebollas","onions","picadas","chopped"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [2,"tsp","paprika","aromatic","ají de color (pimentón)","sweet paprika"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [300,"g","chicken","protein","pollo cocido","cooked chicken","en trozos","in pieces"],
    [3,"","egg","protein","huevos duros","hard-boiled eggs","en cuartos","quartered"],
    [12,"","olives","garnish","aceitunas negras","black olives"],
    [50,"g","driedfruit","sweet","pasas","raisins"],
    [2,"tbsp","sugar","caramel","azúcar","sugar","para espolvorear","to sprinkle"]],
 es:{n:"Pastel de choclo", b:"Pino de carne con pollo, huevo y aceituna bajo una pastelera de choclo con albahaca, con azúcar caramelizada encima. El verano chileno.",
  st:["Licúa el choclo con la albahaca y la leche. Cuece con la mantequilla y 1 cucharadita de sal a fuego bajo 15 minutos, moviendo, hasta que espese.",
      "Sofríe la cebolla en el aceite 15 minutos. Añade la carne, el ají de color, el comino y el resto de la sal y cuece 10 minutos: es el pino.",
      "Calienta el horno a 200 °C. Reparte el pino en 6 pailas de greda o en una fuente. Pon encima el pollo, el huevo, las aceitunas y las pasas.",
      "Cubre con la pastelera de choclo y espolvorea el azúcar.",
      "Hornea 30 minutos, hasta que la superficie esté dorada y caramelizada."],
  tp:["Si el choclo es poco lechoso, añade un poco más de leche al licuar.",
      "Se come con ensalada chilena de tomate y cebolla."],
  v:"pastel de choclo receta"},
 en:{n:"Pastel de Choclo (Chilean Corn Pie)", b:"Beef pino with chicken, egg and olive under a basil corn topping, with caramelised sugar on top. The Chilean summer.",
  st:["Blend the corn with the basil and milk. Cook with the butter and 1 teaspoon of salt on low for 15 minutes, stirring, until thick.",
      "Cook the onion in the oil for 15 minutes. Add the beef, paprika, cumin and the rest of the salt and cook 10 minutes: this is the pino.",
      "Heat the oven to 200 °C. Divide the pino among 6 clay dishes or one baking dish. Top with the chicken, egg, olives and raisins.",
      "Cover with the corn topping and sprinkle with the sugar.",
      "Bake 30 minutes, until the top is golden and caramelised."],
  tp:["If the corn isn't milky, add a little more milk when blending.",
      "Serve with Chilean tomato and onion salad."],
  v:"pastel de choclo recipe"}},

{id:"cazuela-chilena", c:"Chile", r:"latin-america", m:"soup", t:90, s:6,
 i:[[1,"kg","beef","protein","osobuco o asiento de res","beef shank or chuck","en 6 trozos","in 6 pieces"],
    [2.5,"l","water","liquid","agua","water"],
    [1,"","onion","aromatic","cebolla","onion","en cuartos","quartered"],
    [2,"clove","garlic","aromatic","ajo","garlic"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [2.5,"tsp","salt","salt","sal","salt"],
    [6,"","potato","structure","papas","potatoes","peladas","peeled"],
    [6,"","veg","structure","trozos de zapallo","pieces of winter squash"],
    [3,"","corn","protein","choclos","ears of corn","en mitades","halved"],
    [150,"g","veg","protein","porotos verdes","green beans","en tiras","sliced"],
    [60,"g","rice","thicken","arroz","rice"],
    [1,"handful","herb","garnish","cilantro","cilantro","picado","chopped"]],
 es:{n:"Cazuela chilena", b:"Caldo claro de vacuno con una papa, un trozo de zapallo y medio choclo por plato. La sopa de invierno de Chile.",
  st:["Cuece la carne con el agua, la cebolla, el ajo, el orégano y la sal 60 minutos, espumando.",
      "Añade las papas y el zapallo y cuece 15 minutos.",
      "Añade el choclo, los porotos verdes y el arroz y cuece 15 minutos más.",
      "Sirve cada plato con 1 trozo de carne, 1 papa, 1 trozo de zapallo y medio choclo, con cilantro."],
  tp:["Cada plato debe llevar una pieza de cada cosa: así se sirve la cazuela.",
      "Con pollo en vez de vacuno se cuece 35 minutos."],
  v:"cazuela chilena receta"},
 en:{n:"Chilean Cazuela", b:"A clear beef broth with one potato, one piece of squash and half an ear of corn per bowl. Chile's winter soup.",
  st:["Simmer the beef with the water, onion, garlic, oregano and salt for 60 minutes, skimming.",
      "Add the potatoes and squash and cook 15 minutes.",
      "Add the corn, green beans and rice and cook 15 minutes more.",
      "Serve each bowl with 1 piece of beef, 1 potato, 1 piece of squash and half an ear of corn, with cilantro."],
  tp:["Each bowl gets one piece of everything: that's how cazuela is served.",
      "With chicken instead of beef, simmer 35 minutes."],
  v:"cazuela chilena recipe"}},

{id:"porotos-granados", c:"Chile", r:"latin-america", m:"main", t:60, s:6,
 i:[[800,"g","legume","protein","porotos granados frescos","fresh cranberry beans","desgranados","shelled"],
    [1.5,"l","water","liquid","agua","water"],
    [500,"g","veg","structure","zapallo","winter squash","en cubos","cubed"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"tsp","paprika","aromatic","ají de color (pimentón)","sweet paprika"],
    [4,"","corn","structure","choclos","ears of corn","rallados","grated"],
    [1,"handful","herb","aromatic","albahaca","basil","picada","chopped"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Porotos granados con pilco", b:"Porotos frescos de verano con zapallo que se deshace y choclo rallado con albahaca. Vegetariano y espeso.",
  st:["Cuece los porotos en el agua 30 minutos.",
      "Añade el zapallo y cuece 15 minutos, hasta que empiece a deshacerse.",
      "Sofríe la cebolla en el aceite 8 minutos con el ají de color y añádela a la olla.",
      "Añade el choclo rallado, la albahaca y la sal y cuece 10 minutos, moviendo, hasta que espese."],
  tp:["Con porotos secos, remójalos toda la noche y cuécelos 90 minutos antes.",
      "Se sirven con pebre o ensalada de tomate."],
  v:"porotos granados receta"},
 en:{n:"Porotos Granados (Summer Bean Stew)", b:"Fresh summer beans with squash that melts away and grated corn with basil. Vegetarian and thick.",
  st:["Cook the beans in the water for 30 minutes.",
      "Add the squash and cook 15 minutes, until it starts to fall apart.",
      "Cook the onion in the oil for 8 minutes with the paprika and add it to the pot.",
      "Add the grated corn, basil and salt and cook 10 minutes, stirring, until thick."],
  tp:["With dried beans, soak overnight and cook 90 minutes first.",
      "Serve with pebre or tomato salad."],
  v:"porotos granados recipe"}},

{id:"pebre", c:"Chile", r:"latin-america", m:"sauce", t:15, s:8,
 i:[[3,"","tomato","aromatic","tomates","tomatoes","en cubos pequeños","finely diced"],
    [1,"","onion","aromatic","cebolla","onion","picada fina","finely chopped"],
    [1,"bunch","herb","aromatic","cilantro","cilantro","picado","chopped"],
    [2,"","chilli","aromatic","ajíes verdes","green chiles","picados","chopped"],
    [1,"clove","garlic","aromatic","ajo","garlic","picado fino","finely chopped"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","citrus","acid","limón","lemon","en jugo","juiced"],
    [0.5,"tsp","salt","salt","sal","salt"]],
 es:{n:"Pebre", b:"El pico de gallo chileno: tomate, cebolla, cilantro y ají con aceite y limón. En la mesa con pan amasado y sopaipillas.",
  st:["Remoja la cebolla picada en agua caliente 5 minutos y escurre.",
      "Mezcla todo.",
      "Deja reposar 20 minutos antes de servir."],
  tp:["El remojo en agua caliente le quita lo fuerte a la cebolla.",
      "Dura 2 días en el refrigerador."],
  v:"pebre chileno receta"},
 en:{n:"Pebre (Chilean Salsa)", b:"Chile's fresh salsa: tomato, onion, cilantro and chile with oil and lemon. On the table with bread and sopaipillas.",
  st:["Soak the chopped onion in hot water for 5 minutes and drain.",
      "Mix everything.",
      "Leave 20 minutes before serving."],
  tp:["The hot-water soak takes the sharpness out of the onion.",
      "Keeps 2 days in the fridge."],
  v:"pebre recipe"}},

{id:"sopaipillas", c:"Chile", r:"latin-america", m:"bread", t:60, s:8,
 i:[[300,"g","veg","moisture","zapallo cocido","cooked winter squash","hecho puré","mashed"],
    [500,"g","apflour","structure","harina de trigo","all-purpose flour"],
    [2,"tsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [1,"tsp","salt","salt","sal","salt"],
    [80,"g","shortening","fat","manteca vegetal","vegetable shortening","derretida","melted"],
    [1,"l","oil","fat","aceite","oil","para freír","for frying"]],
 es:{n:"Sopaipillas", b:"Discos fritos de masa con zapallo, dorados e inflados. Con pebre en la calle o pasadas en chancaca cuando llueve.",
  st:["Mezcla el puré de zapallo con la manteca derretida.",
      "Añade la harina, el polvo de hornear y la sal y amasa hasta que esté suave. Reposa 15 minutos.",
      "Estira a medio centímetro y corta círculos de 10 centímetros. Pincha cada uno con un tenedor.",
      "Fríe en aceite a 180 °C 2 minutos por lado, hasta que se inflen y doren.",
      "Escurre y sirve con pebre."],
  tp:["Pincharlas evita que se inflen como globos.",
      "Envueltas en un paño se mantienen tibias 30 minutos."],
  v:"sopaipillas chilenas receta"},
 en:{n:"Sopaipillas (Chilean Squash Fritters)", b:"Fried rounds of squash dough, golden and puffed. With pebre on the street, or soaked in chancaca syrup on rainy days.",
  st:["Mix the squash purée with the melted shortening.",
      "Add the flour, baking powder and salt and knead until soft. Rest 15 minutes.",
      "Roll to half a centimetre and cut 10 centimetre circles. Prick each with a fork.",
      "Fry in oil at 180 °C for 2 minutes per side, until puffed and golden.",
      "Drain and serve with pebre."],
  tp:["Pricking stops them ballooning.",
      "Wrapped in a towel they stay warm for 30 minutes."],
  v:"chilean sopaipillas recipe"}},

{id:"empanadas-de-pino", c:"Chile", r:"latin-america", m:"main", t:150, s:8, o:200,
 i:[[600,"g","apflour","structure","harina de trigo","all-purpose flour"],
    [100,"g","lard","fat","manteca","lard"],
    [250,"ml","milk","liquid","leche tibia con agua","warm milk and water"],
    [1.5,"tsp","salt","salt","sal","salt"],
    [600,"g","beef","protein","carne de res","beef","picada a cuchillo","hand-chopped"],
    [4,"","onion","aromatic","cebollas","onions","en cubos","diced"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [2,"tsp","paprika","aromatic","ají de color (pimentón)","sweet paprika"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [1,"tbsp","apflour","thicken","harina de trigo","all-purpose flour","para el pino","for the filling"],
    [2,"","egg","protein","huevos duros","hard-boiled eggs","en cuartos","quartered"],
    [8,"","olives","garnish","aceitunas negras","black olives"],
    [40,"g","driedfruit","sweet","pasas","raisins"],
    [1,"","egg","glaze","huevo","egg","batido","beaten"]],
 es:{n:"Empanadas de pino", b:"Las empanadas horneadas del 18 de septiembre: pino jugoso de carne y mucha cebolla, con huevo, aceituna y pasa.",
  st:["Sofríe la cebolla en el aceite 20 minutos a fuego bajo. Añade la carne, el ají de color, el comino y 1 cucharadita de sal. Cuece 10 minutos. Espolvorea la harina, mezcla y enfría toda la noche.",
      "Mezcla la harina con el resto de la sal, la manteca derretida tibia y la leche. Amasa 5 minutos y reposa 30 minutos.",
      "Divide en 8 bolas y estira cada una en un óvalo de 20 centímetros.",
      "Pon 3 cucharadas de pino, 1 cuarto de huevo, 1 aceituna y unas pasas. Dobla, pinta el borde con agua y cierra doblando las esquinas hacia adentro.",
      "Calienta el horno a 200 °C. Pinta con el huevo batido y hornea 30 minutos, hasta que estén doradas."],
  tp:["El pino frío de un día para otro es más fácil de manejar y más sabroso.",
      "Avisa que la aceituna lleva cuesco si no la deshuesas."],
  v:"empanadas de pino receta"},
 en:{n:"Chilean Empanadas de Pino", b:"The baked empanadas of September 18th: juicy beef and lots of onion, with egg, olive and raisin.",
  st:["Cook the onion in the oil for 20 minutes on low. Add the beef, paprika, cumin and 1 teaspoon of salt. Cook 10 minutes. Sprinkle in the flour, stir and chill overnight.",
      "Mix the flour with the rest of the salt, the warm melted lard and the milk. Knead 5 minutes and rest 30 minutes.",
      "Divide into 8 balls and roll each into a 20 centimetre oval.",
      "Add 3 tablespoons of filling, 1 quarter of egg, 1 olive and a few raisins. Fold, brush the edge with water and seal by folding the corners in.",
      "Heat the oven to 200 °C. Brush with the beaten egg and bake 30 minutes, until golden."],
  tp:["Filling chilled overnight is easier to handle and tastier.",
      "Warn people if the olive still has its stone."],
  v:"empanadas de pino recipe"}},

{id:"charquican", c:"Chile", r:"latin-america", m:"main", t:50, s:4,
 i:[[400,"g","beef","protein","carne molida de res","ground beef"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"tsp","paprika","aromatic","ají de color (pimentón)","sweet paprika"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [600,"g","potato","structure","papas","potatoes","en cubos","cubed"],
    [400,"g","veg","structure","zapallo","winter squash","en cubos","cubed"],
    [150,"g","corn","protein","granos de choclo","corn kernels"],
    [100,"g","legume","protein","arvejas","peas"],
    [500,"ml","water","liquid","agua","water"],
    [1.5,"tsp","salt","salt","sal","salt"],
    [4,"","egg","garnish","huevos","eggs","fritos","fried"]],
 es:{n:"Charquicán", b:"Guiso chileno de papa y zapallo aplastados con carne, choclo y arvejas, con un huevo frito encima.",
  st:["Sofríe la cebolla y el ajo en el aceite 5 minutos. Añade la carne, el ají de color, el comino y el orégano y cuece 8 minutos.",
      "Añade la papa, el zapallo, el agua y la sal. Tapa y cuece 20 minutos.",
      "Añade el choclo y las arvejas y cuece 5 minutos.",
      "Aplasta un poco con un tenedor para que quede un guiso grueso.",
      "Sirve con un huevo frito encima."],
  tp:["El nombre viene del charqui, carne seca; hoy se hace con carne molida.",
      "Con cebolla en escabeche al lado corta la contundencia."],
  v:"charquican receta"},
 en:{n:"Charquicán (Chilean Beef and Squash Hash)", b:"A Chilean stew of potato and squash mashed with beef, corn and peas, with a fried egg on top.",
  st:["Cook the onion and garlic in the oil for 5 minutes. Add the beef, paprika, cumin and oregano and cook 8 minutes.",
      "Add the potato, squash, water and salt. Cover and cook 20 minutes.",
      "Add the corn and peas and cook 5 minutes.",
      "Mash a little with a fork into a chunky stew.",
      "Serve with a fried egg on top."],
  tp:["The name comes from charqui, dried meat; today it's made with ground beef.",
      "Pickled onion on the side cuts the richness."],
  v:"charquican recipe"}},

{id:"completo", c:"Chile", r:"latin-america", m:"main", t:20, s:4,
 i:[[4,"","sausage","protein","vienesas (salchichas)","hot dog sausages"],
    [4,"","bread","structure","panes de completo","long hot dog buns"],
    [2,"","avocado","garnish","paltas","avocados","molidas con sal","mashed with salt"],
    [2,"","tomato","garnish","tomates","tomatoes","en cubos","diced"],
    [6,"tbsp","mayo","garnish","mayonesa","mayonnaise"],
    [4,"tbsp","pickles","garnish","chucrut","sauerkraut","opcional","optional"],
    [2,"tbsp","mustard","garnish","mostaza","mustard","opcional","optional"],
    [0.25,"tsp","salt","salt","sal","salt"]],
 es:{n:"Completo italiano", b:"El hot dog chileno: vienesa en pan largo cubierta de palta, tomate y mucha mayonesa. Los colores de la bandera italiana.",
  st:["Hierve las vienesas 5 minutos.",
      "Calienta los panes al vapor o en el horno 3 minutos.",
      "Pon una vienesa en cada pan. Cubre con tomate, luego palta y termina con mayonesa en zigzag."],
  tp:["La palta va generosa: es lo que lo hace completo.",
      "Con chucrut y mostaza se llama completo completo."],
  v:"completo italiano receta"},
 en:{n:"Completo Italiano (Chilean Hot Dog)", b:"Chile's hot dog: a sausage in a long bun piled with avocado, tomato and lots of mayonnaise. The colours of the Italian flag.",
  st:["Boil the sausages for 5 minutes.",
      "Warm the buns by steaming or in the oven for 3 minutes.",
      "Put a sausage in each bun. Top with tomato, then avocado, and finish with a zigzag of mayonnaise."],
  tp:["Be generous with the avocado: it's what makes it complete.",
      "With sauerkraut and mustard it's a completo completo."],
  v:"completo italiano recipe"}},

{id:"mote-con-huesillo", c:"Chile", r:"latin-america", m:"drink", t:60, s:6,
 i:[[12,"","driedfruit","sweet","huesillos (duraznos deshidratados)","dried whole peaches (huesillos)","remojados toda la noche","soaked overnight"],
    [2,"l","water","liquid","agua","water"],
    [150,"g","jaggery","sweet","chancaca o azúcar rubia","chancaca or light brown sugar"],
    [1,"","spice","aromatic","raja de canela","cinnamon stick"],
    [1,"","citrus","aromatic","cáscara de naranja","orange peel"],
    [250,"g","cookedwheat","structure","mote de trigo cocido","cooked husked wheat (mote)"]],
 es:{n:"Mote con huesillo", b:"La bebida de verano chilena: duraznos secos en su almíbar de chancaca con mote de trigo. Se come y se toma.",
  st:["Cuece los huesillos con su agua de remojo, el agua, la chancaca, la canela y la naranja 40 minutos a fuego bajo.",
      "Deja enfriar y refrigera.",
      "Sirve en vasos altos: 2 cucharadas de mote, 2 huesillos y el jugo frío hasta arriba."],
  tp:["Se sirve con cuchara larga para el mote.",
      "Aguanta 5 días en el refrigerador."],
  v:"mote con huesillo receta"},
 en:{n:"Mote con Huesillo (Peach and Wheat Drink)", b:"Chile's summer drink: dried peaches in their chancaca syrup with husked wheat. You eat and drink it.",
  st:["Cook the dried peaches with their soaking water, the water, chancaca, cinnamon and orange peel for 40 minutes on low.",
      "Cool and chill.",
      "Serve in tall glasses: 2 tablespoons of wheat, 2 peaches and the cold syrup to the top."],
  tp:["Serve with a long spoon for the wheat.",
      "Keeps 5 days in the fridge."],
  v:"mote con huesillo recipe"}},

{id:"leche-asada", c:"Chile", r:"latin-america", m:"sweet", t:75, s:6, o:180,
 i:[[1,"l","milk","liquid","leche","milk"],
    [5,"","egg","set","huevos","eggs"],
    [180,"g","sugar","sweet","azúcar","sugar"],
    [1,"tsp","vanilla","aromatic","extracto de vainilla","vanilla extract"],
    [1,"","citrus","aromatic","ralladura de limón","lemon zest"]],
 es:{n:"Leche asada", b:"Flan chileno sin caramelo: leche con huevo y vainilla horneada hasta que la superficie se tuesta.",
  st:["Calienta el horno a 180 °C.",
      "Bate los huevos con el azúcar. Añade la leche, la vainilla y la ralladura y mezcla sin batir de más.",
      "Vierte en 6 pocillos o una fuente.",
      "Hornea 45 minutos, hasta que la superficie esté dorada con manchas y el centro apenas tiemble.",
      "Enfría y sirve frío."],
  tp:["Sin baño María queda con la costra tostada que lo distingue.",
      "Si la superficie se oscurece antes de cuajar, cubre con aluminio."],
  v:"leche asada receta"},
 en:{n:"Leche Asada (Chilean Baked Custard)", b:"Chilean flan with no caramel: milk with egg and vanilla baked until the top browns.",
  st:["Heat the oven to 180 °C.",
      "Whisk the eggs with the sugar. Add the milk, vanilla and zest and mix without overbeating.",
      "Pour into 6 ramekins or one dish.",
      "Bake 45 minutes, until the top is spotted golden and the centre barely wobbles.",
      "Cool and serve cold."],
  tp:["Without a water bath it gets the toasted crust that sets it apart.",
      "If the top darkens before it sets, cover with foil."],
  v:"leche asada recipe"}}
];
