module.exports = [
{id:"pastel-de-jaiba", c:"Chile", r:"latin-america", m:"main", t:40, s:4,
 i:[[500,"g","crab","protein","carne de jaiba","crab meat"],
    [30,"g","butter","fat","mantequilla","butter"],
    [1,"","onion","aromatic","cebolla","onion","picada fina","finely chopped"],
    [1,"tsp","paprika","aromatic","pimentón dulce","sweet paprika"],
    [100,"g","bread","thicken","pan blanco sin corteza","white bread, crusts off"],
    [250,"ml","milk","liquid","leche","milk"],
    [100,"ml","cream","enrich","crema de leche","single cream"],
    [60,"g","parmesan","garnish","queso parmesano rallado","grated parmesan"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Pastel de jaiba", b:"Carne de jaiba en una crema de pan y leche, gratinada con queso en paila de greda. Clásico de la costa chilena.",
  st:["Remoja el pan en la leche 10 minutos y deshazlo con un tenedor.",
      "Sofríe la cebolla en la mantequilla 6 minutos. Añade el pimentón.",
      "Añade el pan con la leche, la crema, la jaiba y la sal. Cocina 5 minutos removiendo, hasta que espese.",
      "Reparte en cazuelitas y cubre con el queso.",
      "Gratina en el horno a 220 °C 10 minutos, hasta que esté dorado."],
  tp:["Revisa la jaiba con los dedos para quitar restos de caparazón.",
      "Debe quedar cremoso, no seco: si espesa mucho, añade leche."],
  v:"pastel de jaiba chileno"},
 en:{n:"Pastel de Jaiba (Chilean Crab Gratin)", b:"Crab meat in a bread-and-milk cream, gratinéed with cheese in clay dishes. A Chilean coastal classic.",
  st:["Soak the bread in the milk for 10 minutes and break it up with a fork.",
      "Cook the onion in the butter for 6 minutes. Add the paprika.",
      "Add the soaked bread and milk, the cream, crab and salt. Cook 5 minutes, stirring, until thick.",
      "Divide between small dishes and top with the cheese.",
      "Grill in the oven at 220 °C for 10 minutes, until golden."],
  tp:["Run your fingers through the crab to catch any bits of shell.",
      "It should be creamy, not dry: if it thickens too much, add milk."],
  v:"chilean crab gratin pastel de jaiba"}},

{id:"pantrucas", c:"Chile", r:"latin-america", m:"soup", t:50, s:4,
 i:[[200,"g","apflour","structure","harina de trigo","plain flour"],
    [100,"ml","water","liquid","agua tibia (para la masa)","warm water (for the dough)"],
    [1,"tbsp","oil","fat","aceite (para la masa)","oil (for the dough)"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","veg","aromatic","zanahoria","carrot","rallada","grated"],
    [1,"tsp","paprika","aromatic","pimentón dulce","sweet paprika"],
    [300,"g","beef","protein","carne picada de res","minced beef"],
    [1.5,"l","water","liquid","agua","water"],
    [2,"tsp","salt","salt","sal","salt"],
    [2,"","egg","enrich","huevos","eggs"],
    [1,"handful","herb","garnish","perejil","parsley","picado","chopped"]],
 es:{n:"Sopa de pantrucas", b:"Sopa chilena con trozos de masa fina cocidos en caldo de carne y un huevo batido al final.",
  st:["Mezcla la harina, el agua tibia, el aceite de la masa y una pizca de sal. Amasa 5 minutos y deja reposar 20 minutos.",
      "Sofríe la cebolla y la zanahoria en el aceite 6 minutos. Añade el pimentón y la carne y dora 5 minutos.",
      "Añade el agua y la sal y hierve 15 minutos.",
      "Estira la masa muy fina, córtala en trozos de 4 cm y échalos al caldo. Cuece 8 minutos.",
      "Apaga, añade los huevos batidos removiendo y termina con el perejil."],
  tp:["Enharina los trozos para que no se peguen entre sí.",
      "Echa las pantrucas de a poco para que no se aglomeren."],
  v:"sopa de pantrucas chilena"},
 en:{n:"Pantrucas (Chilean Dumpling Soup)", b:"A Chilean soup of thin dough pieces cooked in beef broth, finished with beaten egg.",
  st:["Mix the flour, warm water, dough oil and a pinch of salt. Knead 5 minutes and rest 20 minutes.",
      "Cook the onion and carrot in the oil for 6 minutes. Add the paprika and beef and brown 5 minutes.",
      "Add the water and salt and boil 15 minutes.",
      "Roll the dough very thin, cut into 4 cm pieces and drop them into the broth. Cook 8 minutes.",
      "Turn off, stir in the beaten eggs and finish with the parsley."],
  tp:["Flour the pieces so they don't stick together.",
      "Drop them in a few at a time so they don't clump."],
  v:"chilean pantrucas soup"}},

{id:"leche-nevada", c:"Chile", r:"latin-america", m:"sweet", t:40, s:6,
 i:[[1,"l","milk","liquid","leche","milk"],
    [150,"g","sugar","sweet","azúcar","sugar"],
    [4,"","egg","structure","huevos, separadas claras y yemas","eggs, separated"],
    [1,"tbsp","cornstarch","thicken","maicena","cornflour"],
    [1,"tsp","vanilla","aromatic","esencia de vainilla","vanilla extract"],
    [1,"pinch","spice","garnish","canela molida","ground cinnamon"]],
 es:{n:"Leche nevada", b:"Crema de vainilla con nubes de merengue cocidas en leche. El postre de las abuelas chilenas.",
  st:["Bate las claras a punto de nieve con 50 g de azúcar.",
      "Calienta la leche con 100 g de azúcar. Cuece cucharadas de merengue 1 minuto por lado y sácalas.",
      "Mezcla las yemas con la maicena y un poco de leche tibia.",
      "Añade a la leche y cuece 5 minutos removiendo, sin hervir, hasta que espese. Añade la vainilla.",
      "Sirve la crema fría con las nubes encima y canela."],
  tp:["No dejes hervir la crema o las yemas se cuajan.",
      "Las nubes crecen al cocerse: deja espacio en la olla."],
  v:"leche nevada chilena"},
 en:{n:"Leche Nevada (Chilean Floating Islands)", b:"Vanilla custard with meringue clouds poached in milk. A Chilean grandmother's dessert.",
  st:["Whisk the egg whites to stiff peaks with 50 g of sugar.",
      "Heat the milk with 100 g of sugar. Poach spoonfuls of meringue 1 minute per side and lift out.",
      "Mix the yolks with the cornflour and a little warm milk.",
      "Stir into the milk and cook 5 minutes without boiling, until thickened. Add the vanilla.",
      "Serve the custard cold with the clouds on top and cinnamon."],
  tp:["Don't let the custard boil or the yolks will scramble.",
      "The clouds swell as they cook: leave room in the pan."],
  v:"chilean floating islands leche nevada"}},

{id:"calzones-rotos", c:"Chile", r:"latin-america", m:"pastry", t:60, s:30,
 i:[[500,"g","apflour","structure","harina de trigo","plain flour"],
    [2,"tsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [100,"g","sugar","sweet","azúcar","sugar"],
    [60,"g","butter","fat","mantequilla derretida","melted butter"],
    [2,"","egg","binder","huevos","eggs"],
    [120,"ml","milk","liquid","leche","milk"],
    [1,"piece","citrus","aromatic","ralladura de naranja","orange zest"],
    [1,"l","oil","fat","aceite para freír","oil for frying"],
    [50,"g","icingsugar","garnish","azúcar flor","icing sugar"]],
 es:{n:"Calzones rotos", b:"Masitas fritas con un nudo en el centro, espolvoreadas con azúcar flor. Se comen con té en los días de lluvia chilenos.",
  st:["Mezcla la harina, el polvo de hornear y el azúcar. Añade la mantequilla, los huevos, la leche y la ralladura y amasa 5 minutos.",
      "Estira a 3 mm y corta rombos de 10 cm.",
      "Haz un corte en el centro de cada rombo y pasa una punta por el agujero.",
      "Fríe a 170 °C 2 minutos por lado, hasta que estén dorados.",
      "Escurre y espolvorea con el azúcar flor."],
  tp:["No los frías muy calientes o quedan crudos por dentro.",
      "Se conservan 2 días en un recipiente cerrado."],
  v:"calzones rotos chilenos"},
 en:{n:"Calzones Rotos (Chilean Twisted Fritters)", b:"Fried dough twisted through a slit in the middle, dusted with icing sugar. Eaten with tea on rainy Chilean days.",
  st:["Mix the flour, baking powder and sugar. Add the butter, eggs, milk and zest and knead 5 minutes.",
      "Roll to 3 mm and cut 10 cm diamonds.",
      "Make a slit in the centre of each diamond and pull one tip through.",
      "Fry at 170 °C for 2 minutes per side, until golden.",
      "Drain and dust with the icing sugar."],
  tp:["Don't fry them too hot or they stay raw inside.",
      "They keep 2 days in a closed tin."],
  v:"chilean calzones rotos fritters"}},

{id:"pollo-arvejado", c:"Chile", r:"latin-america", m:"main", t:60, s:4,
 i:[[4,"thigh","chicken","protein","trutros de pollo","chicken legs"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","en pluma","sliced"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"","veg","aromatic","zanahorias","carrots","en rodajas","sliced"],
    [1,"tsp","paprika","aromatic","pimentón dulce","sweet paprika"],
    [1,"tsp","spice","aromatic","comino","cumin"],
    [150,"ml","winewhite","liquid","vino blanco","white wine"],
    [300,"ml","water","liquid","agua","water"],
    [300,"g","legume","structure","arvejas","green peas"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Pollo arvejado", b:"Pollo guisado con arvejas, zanahoria y vino blanco. Almuerzo de casa en Chile.",
  st:["Sala el pollo y dóralo en el aceite 8 minutos. Sácalo.",
      "Sofríe la cebolla, el ajo y la zanahoria 8 minutos. Añade el pimentón y el comino.",
      "Añade el vino y deja reducir 2 minutos.",
      "Vuelve a poner el pollo con el agua. Tapa y cuece 30 minutos.",
      "Añade las arvejas y cuece 8 minutos más."],
  tp:["Sírvelo con arroz blanco.",
      "Las arvejas congeladas funcionan igual de bien."],
  v:"pollo arvejado chileno"},
 en:{n:"Pollo Arvejado (Chilean Chicken with Peas)", b:"Chicken stewed with peas, carrot and white wine. Home lunch in Chile.",
  st:["Salt the chicken and brown it in the oil for 8 minutes. Remove.",
      "Cook the onion, garlic and carrot for 8 minutes. Add the paprika and cumin.",
      "Add the wine and reduce 2 minutes.",
      "Return the chicken with the water. Cover and simmer 30 minutes.",
      "Add the peas and cook 8 minutes more."],
  tp:["Serve with white rice.",
      "Frozen peas work just as well."],
  v:"chilean chicken and peas stew"}},

{id:"tomatican", c:"Chile", r:"latin-america", m:"main", t:35, s:4,
 i:[[2,"tbsp","oil","fat","aceite","oil"],
    [300,"g","beef","protein","carne de res en tiritas","beef, cut in thin strips"],
    [1,"","onion","aromatic","cebolla","onion","en pluma","sliced"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"tsp","paprika","aromatic","pimentón dulce","sweet paprika"],
    [4,"","tomato","liquid","tomates maduros","ripe tomatoes","pelados y picados","peeled and chopped"],
    [300,"g","corn","structure","granos de choclo","sweetcorn kernels"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [1,"handful","herb","garnish","albahaca","basil"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Tomaticán", b:"Guiso veraniego de tomate maduro, choclo y carne. Todo el sabor del verano chileno en una olla.",
  st:["Dora la carne en el aceite a fuego fuerte 4 minutos. Sácala.",
      "Sofríe la cebolla y el ajo 6 minutos. Añade el pimentón.",
      "Añade el tomate, el orégano y la sal y cocina 10 minutos.",
      "Añade el choclo y la carne y cocina 8 minutos más.",
      "Termina con la albahaca."],
  tp:["Usa tomates muy maduros: son la base del plato.",
      "Sírvelo con arroz blanco."],
  v:"tomaticán chileno"},
 en:{n:"Tomaticán (Chilean Tomato and Corn Stew)", b:"A summer stew of ripe tomatoes, sweetcorn and beef. Chilean summer in one pot.",
  st:["Brown the beef in the oil over high heat for 4 minutes. Remove.",
      "Cook the onion and garlic for 6 minutes. Add the paprika.",
      "Add the tomato, oregano and salt and cook 10 minutes.",
      "Add the corn and beef and cook 8 minutes more.",
      "Finish with the basil."],
  tp:["Use very ripe tomatoes: they are the whole dish.",
      "Serve with white rice."],
  v:"chilean tomatican stew"}},

{id:"papelon-con-limon", c:"Venezuela", r:"latin-america", m:"drink", t:10, s:6,
 i:[[250,"g","brownsugar","sweet","papelón","papelón (unrefined cane sugar)","rallado","grated"],
    [1.5,"l","water","liquid","agua fría","cold water"],
    [5,"","citrus","acid","limones","limes","exprimidos","juiced"],
    [300,"g","ice","liquid","hielo","ice"]],
 es:{n:"Papelón con limón", b:"El refresco de todas las casas venezolanas: papelón disuelto en agua fría con mucho limón.",
  st:["Disuelve el papelón en 500 ml de agua, removiendo.",
      "Añade el resto del agua y el jugo de limón.",
      "Prueba y ajusta de limón.",
      "Sirve con el hielo."],
  tp:["Si el papelón está muy duro, disuélvelo en el agua tibia y deja enfriar.",
      "Cuélalo si el papelón trae impurezas."],
  v:"papelón con limón venezolano"},
 en:{n:"Papelón con Limón (Cane Sugar Limeade)", b:"The everyday drink of every Venezuelan home: unrefined cane sugar dissolved in cold water with lots of lime.",
  st:["Dissolve the papelón in 500 ml of the water, stirring.",
      "Add the rest of the water and the lime juice.",
      "Taste and adjust the lime.",
      "Serve over the ice."],
  tp:["If the papelón is very hard, dissolve it in warm water and let it cool.",
      "Strain it if the papelón has any grit."],
  v:"venezuelan papelon con limon"}},

{id:"mandocas", c:"Venezuela", r:"latin-america", m:"breakfast", t:45, s:12,
 i:[[1,"","plantain","sweet","plátano maduro","ripe plantain"],
    [250,"g","masa","structure","harina de maíz precocida","precooked cornmeal"],
    [100,"g","brownsugar","sweet","papelón","papelón (unrefined cane sugar)","rallado","grated"],
    [250,"ml","water","liquid","agua","water"],
    [100,"g","queso","enrich","queso blanco duro","hard white cheese","rallado","grated"],
    [1,"tsp","salt","salt","sal","salt"],
    [500,"ml","oil","fat","aceite para freír","oil for frying"]],
 es:{n:"Mandocas", b:"Rosquitas fritas de maíz, plátano maduro, papelón y queso. Desayuno típico del Zulia.",
  st:["Hierve el plátano con piel 15 minutos. Pélalo y hazlo puré.",
      "Disuelve el papelón en el agua caliente.",
      "Mezcla la harina, el puré, el agua con papelón, el queso y la sal hasta tener una masa suave.",
      "Forma cordones de 15 cm y une las puntas en forma de lágrima.",
      "Fríe a 175 °C 4 minutos, hasta que estén doradas."],
  tp:["Si la masa se pega, humedécete las manos.",
      "Cómelas recién hechas, cuando están crujientes."],
  v:"mandocas zulianas"},
 en:{n:"Mandocas (Plantain Corn Rings)", b:"Fried rings of cornmeal, ripe plantain, cane sugar and cheese. A breakfast from Zulia, Venezuela.",
  st:["Boil the plantain in its skin for 15 minutes. Peel and mash.",
      "Dissolve the papelón in the hot water.",
      "Mix the cornmeal, mash, sweetened water, cheese and salt into a soft dough.",
      "Roll 15 cm ropes and join the ends into a teardrop.",
      "Fry at 175 °C for 4 minutes, until golden."],
  tp:["If the dough sticks, wet your hands.",
      "Eat them fresh, while crisp."],
  v:"venezuelan mandocas"}},

{id:"bollitos-pelones", c:"Venezuela", r:"latin-america", m:"main", t:60, s:4,
 i:[[250,"g","masa","structure","harina de maíz precocida","precooked cornmeal"],
    [300,"ml","water","liquid","agua","water"],
    [1,"tsp","salt","salt","sal","salt"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","pimentón rojo","red bell pepper","picado","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [300,"g","beef","protein","carne molida de res","minced beef"],
    [400,"g","tomato","liquid","tomate triturado","crushed tomatoes"],
    [250,"ml","water","liquid","agua (segunda parte)","water (second part)"],
    [40,"g","queso","garnish","queso blanco duro","hard white cheese","rallado","grated"]],
 es:{n:"Bollitos pelones", b:"Bolitas de masa de maíz rellenas de carne y cocidas en salsa de tomate. Comida de casa venezolana.",
  st:["Sofríe la cebolla, el pimentón y el ajo en el aceite 6 minutos. Añade la carne y dórala 8 minutos. Sala.",
      "Amasa la harina con el agua y la sal. Forma 12 bolas.",
      "Aplana cada bola, rellena con 1 cucharada de carne y ciérrala.",
      "Calienta el tomate con el agua de la segunda parte 5 minutos.",
      "Cuece los bollitos en la salsa 20 minutos tapados. Sirve con el queso."],
  tp:["Guarda un poco de carne para añadir a la salsa.",
      "Cierra bien los bollitos para que no se abran al cocer."],
  v:"bollitos pelones venezolanos"},
 en:{n:"Bollitos Pelones (Stuffed Corn Dumplings)", b:"Cornmeal dumplings stuffed with beef and simmered in tomato sauce. Venezuelan home cooking.",
  st:["Cook the onion, pepper and garlic in the oil for 6 minutes. Add the beef and brown 8 minutes. Salt.",
      "Knead the cornmeal with the water and salt. Shape 12 balls.",
      "Flatten each ball, fill with 1 tablespoon of beef and seal.",
      "Heat the tomato with the second part of the water for 5 minutes.",
      "Simmer the dumplings in the sauce, covered, for 20 minutes. Serve with the cheese."],
  tp:["Keep a little of the beef to stir into the sauce.",
      "Seal them well so they don't open while cooking."],
  v:"venezuelan bollitos pelones"}},

{id:"tizana", c:"Venezuela", r:"latin-america", m:"drink", t:15, s:8,
 i:[[1,"","fruit","structure","manzana","apple","en dados pequeños","small dice"],
    [2,"","fruit","structure","cambures","bananas","en dados pequeños","small dice"],
    [300,"g","fruit","structure","piña","pineapple","en dados pequeños","small dice"],
    [300,"g","fruit","structure","lechosa","papaya","en dados pequeños","small dice"],
    [200,"g","fruit","structure","patilla","watermelon","en dados pequeños","small dice"],
    [1,"l","fruit","liquid","jugo de naranja","orange juice"],
    [500,"ml","fruit","liquid","jugo de patilla licuada","blended watermelon juice"],
    [50,"g","sugar","sweet","azúcar","sugar"],
    [2,"","citrus","acid","limones","limes","exprimidos","juiced"],
    [300,"g","ice","liquid","hielo","ice"]],
 es:{n:"Tizana", b:"Ponche frío de frutas picadas en jugo de naranja y patilla. Se toma en fiestas y en las tardes calurosas de Venezuela.",
  st:["Pica todas las frutas en dados pequeños.",
      "Mezcla el jugo de naranja, el jugo de patilla, el limón y el azúcar hasta que se disuelva.",
      "Añade las frutas y refrigera 1 hora.",
      "Sirve con el hielo, con cuchara para las frutas."],
  tp:["Pica el cambur al final para que no se oscurezca.",
      "Se toma el mismo día."],
  v:"tizana venezolana"},
 en:{n:"Tizana (Venezuelan Fruit Punch)", b:"A cold punch of diced fruit in orange and watermelon juice. Drunk at parties and on hot Venezuelan afternoons.",
  st:["Cut all the fruit into small dice.",
      "Mix the orange juice, watermelon juice, lime and sugar until dissolved.",
      "Add the fruit and chill 1 hour.",
      "Serve over the ice, with a spoon for the fruit."],
  tp:["Cut the banana last so it doesn't brown.",
      "Drink it the same day."],
  v:"venezuelan tizana fruit punch"}}
];
