module.exports = [
{id:"ajiaco", c:"Colombia", r:"latin-america", m:"soup", t:90, s:6,
 i:[[3,"","chicken","protein","pechugas de pollo con hueso","bone-in chicken breasts"],
    [2.5,"l","water","liquid","agua","water"],
    [3,"","scallion","aromatic","tallos de cebolla larga","green onion stalks"],
    [3,"clove","garlic","aromatic","ajo","garlic"],
    [2.5,"tsp","salt","salt","sal","salt"],
    [1,"bunch","herb","aromatic","cilantro","cilantro"],
    [500,"g","potato","structure","papa sabanera o blanca","floury white potatoes","pelada, en rodajas","peeled, sliced"],
    [500,"g","potato","structure","papa pastusa o amarilla","yellow potatoes","pelada, en rodajas","peeled, sliced"],
    [500,"g","potato","thicken","papa criolla","small yellow potatoes (papa criolla)","pelada","peeled"],
    [3,"","corn","protein","mazorcas","ears of corn","en trozos","in pieces"],
    [3,"tbsp","herb","aromatic","guascas secas","dried guascas"],
    [200,"ml","heavycream","garnish","crema de leche","heavy cream"],
    [60,"g","capers","garnish","alcaparras","capers"],
    [2,"","avocado","garnish","aguacates","avocados"]],
 es:{n:"Ajiaco santafereño", b:"La sopa de Bogotá: pollo, tres papas y mazorca con guascas, espesa porque la papa criolla se deshace. Crema y alcaparras en la mesa.",
  st:["Cuece el pollo con el agua, la cebolla larga, el ajo, la sal y el cilantro atado 35 minutos. Saca el pollo y deshébralo. Cuela el líquido.",
      "Añade la papa sabanera y la pastusa al líquido y cuece 20 minutos.",
      "Añade la papa criolla y la mazorca y cuece 25 minutos más, moviendo de vez en cuando, hasta que la papa criolla se deshaga y espese la sopa.",
      "Añade las guascas y el pollo y cuece 5 minutos.",
      "Sirve con crema, alcaparras y aguacate aparte, para que cada quien ponga lo suyo."],
  tp:["Sin guascas no es ajiaco: se consiguen secas en tiendas latinas o en línea.",
      "Si no hay papa criolla, aplasta parte de la papa amarilla contra la olla para espesar."],
  v:"ajiaco santafereño receta"},
 en:{n:"Ajiaco (Bogotá Chicken and Potato Soup)", b:"Bogotá's soup: chicken, three potatoes and corn with guascas, thick because the small yellow potatoes melt. Cream and capers at the table.",
  st:["Simmer the chicken with the water, green onion, garlic, salt and tied cilantro for 35 minutes. Lift out the chicken and shred it. Strain the liquid.",
      "Add the white and yellow potatoes to the liquid and cook 20 minutes.",
      "Add the papa criolla and corn and cook 25 minutes more, stirring now and then, until the small potatoes break down and thicken the soup.",
      "Add the guascas and the chicken and cook 5 minutes.",
      "Serve with cream, capers and avocado on the side, so everyone adds their own."],
  tp:["Without guascas it isn't ajiaco: buy them dried at Latin shops or online.",
      "No papa criolla? Mash some of the yellow potatoes against the pot to thicken."],
  v:"ajiaco recipe"}},

{id:"bandeja-paisa", c:"Colombia", r:"latin-america", m:"main", t:180, s:4,
 i:[[400,"g","legume","protein","frijoles cargamanto o rojos","cargamanto or red beans","remojados toda la noche","soaked overnight"],
    [1,"","veg","aromatic","zanahoria","carrot","en trozos","in pieces"],
    [2,"","tomato","aromatic","tomates","tomatoes","picados","chopped"],
    [4,"","scallion","aromatic","tallos de cebolla larga","green onion stalks","picados","chopped"],
    [400,"g","porkbelly","protein","tocino de cerdo con piel","skin-on pork belly","en tiras","in strips"],
    [4,"","chorizo","protein","chorizos antioqueños","Colombian chorizos"],
    [400,"g","beef","protein","carne molida de res","ground beef"],
    [300,"g","rice","structure","arroz blanco","white rice"],
    [2,"","plantain","sweet","plátanos maduros","ripe plantains","en tajadas","sliced lengthwise"],
    [4,"","egg","protein","huevos","eggs"],
    [2,"","avocado","garnish","aguacates","avocados"],
    [4,"","cornmeal","serve","arepas delgadas de maíz","thin corn arepas"],
    [3,"tsp","salt","salt","sal","salt"],
    [100,"ml","oil","fat","aceite","oil"]],
 es:{n:"Bandeja paisa", b:"El plato de Antioquia: frijoles, arroz, carne molida, chicharrón, chorizo, huevo frito, maduro, aguacate y arepa. Para compartir o para no comer en todo el día.",
  st:["Cuece los frijoles escurridos en agua nueva con la zanahoria 2 horas, hasta que estén blandos.",
      "Haz el hogao: sofríe el tomate y la cebolla larga en 2 cucharadas de aceite 10 minutos. Añade la mitad a los frijoles con 1 cucharadita de sal y cuece 20 minutos más.",
      "Cuece el arroz con 1 cucharadita de sal y 600 ml de agua.",
      "Sala el tocino y cuécelo en una olla tapada con un poco de agua 20 minutos. Destapa y fríelo en su grasa hasta que la piel se infle y cruja. Fríe los chorizos en la misma grasa.",
      "Sofríe la carne molida con el resto del hogao y la sal restante 10 minutos, hasta que esté seca y suelta.",
      "Fríe las tajadas de plátano hasta que estén doradas y los huevos con la yema líquida.",
      "Sirve todo en platos grandes con aguacate y arepa."],
  tp:["El chicharrón queda crujiente si antes se cuece en agua: la piel se ablanda y luego se infla al freír.",
      "Los frijoles saben mejor al día siguiente: hazlos antes."],
  v:"bandeja paisa receta"},
 en:{n:"Bandeja Paisa", b:"Antioquia's plate: beans, rice, ground beef, crackling pork belly, chorizo, fried egg, sweet plantain, avocado and arepa. For sharing, or for not eating again all day.",
  st:["Cook the drained beans in fresh water with the carrot for 2 hours, until soft.",
      "Make the hogao: cook the tomato and green onion in 2 tablespoons of oil for 10 minutes. Add half to the beans with 1 teaspoon of salt and cook 20 minutes more.",
      "Cook the rice with 1 teaspoon of salt and 600 ml of water.",
      "Salt the pork belly and cook it covered with a little water for 20 minutes. Uncover and fry it in its own fat until the skin puffs and crackles. Fry the chorizos in the same fat.",
      "Cook the ground beef with the rest of the hogao and the remaining salt for 10 minutes, until dry and crumbly.",
      "Fry the plantain slices until golden and the eggs with runny yolks.",
      "Serve everything on large plates with avocado and arepa."],
  tp:["The crackling crisps because it simmers first: the skin softens, then puffs in the fat.",
      "The beans taste better the next day: make them ahead."],
  v:"bandeja paisa recipe"}},

{id:"sancocho", c:"Colombia", r:"latin-america", m:"soup", t:120, s:8,
 i:[[1.5,"kg","chicken","protein","gallina o pollo en presas","hen or chicken pieces"],
    [3,"l","water","liquid","agua","water"],
    [4,"","scallion","aromatic","tallos de cebolla larga","green onion stalks"],
    [4,"clove","garlic","aromatic","ajo","garlic"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [3,"tsp","salt","salt","sal","salt"],
    [2,"","plantain","structure","plátanos verdes","green plantains","pelados, en trozos","peeled, in chunks"],
    [700,"g","cassava","structure","yuca","cassava","pelada, en trozos","peeled, in chunks"],
    [500,"g","potato","structure","papa","potatoes","pelada, en trozos","peeled, in chunks"],
    [3,"","corn","protein","mazorcas","ears of corn","en trozos","in pieces"],
    [1,"bunch","herb","aromatic","cilantro","cilantro","picado","chopped"],
    [2,"","citrus","garnish","limones","limes"],
    [2,"","avocado","garnish","aguacates","avocados"]],
 es:{n:"Sancocho de gallina", b:"La olla de domingo: gallina con plátano verde, yuca, papa y mazorca, hervidos hasta que el caldo espesa solo.",
  st:["Cuece la gallina con el agua, la cebolla larga, el ajo, el comino y la sal 60 minutos (35 si es pollo).",
      "Añade el plátano verde, partiéndolo con los dedos en vez de cortarlo, y la mazorca. Cuece 20 minutos.",
      "Añade la yuca y la papa y cuece 25 minutos más, hasta que la yuca esté blanda y empiece a deshacerse.",
      "Saca las fibras duras del centro de la yuca. Añade la mitad del cilantro.",
      "Sirve con el resto del cilantro, limón, aguacate y arroz blanco."],
  tp:["Partir el plátano con la mano deja bordes rugosos que sueltan almidón y espesan.",
      "La yuca debe cocerse del todo: nunca se come cruda."],
  v:"sancocho de gallina receta"},
 en:{n:"Colombian Hen Sancocho", b:"The Sunday pot: hen with green plantain, cassava, potato and corn, simmered until the broth thickens on its own.",
  st:["Simmer the hen with the water, green onion, garlic, cumin and salt for 60 minutes (35 if using chicken).",
      "Add the green plantain, snapping it into pieces with your fingers instead of cutting, and the corn. Cook 20 minutes.",
      "Add the cassava and potato and cook 25 minutes more, until the cassava is soft and starting to fall apart.",
      "Pull out the woody cores from the cassava. Add half the cilantro.",
      "Serve with the rest of the cilantro, lime, avocado and white rice."],
  tp:["Snapping the plantain by hand leaves rough edges that release starch and thicken.",
      "Cassava must be fully cooked: never eat it raw."],
  v:"colombian sancocho recipe"}},

{id:"arepas-de-choclo", c:"Colombia", r:"latin-america", m:"breakfast", t:30, s:4,
 i:[[500,"g","corn","structure","granos de mazorca tierna","sweet corn kernels","frescos o congelados","fresh or frozen"],
    [80,"g","cornmeal","structure","harina de maíz precocida","precooked cornmeal (masarepa)"],
    [2,"tbsp","sugar","sweet","azúcar","sugar"],
    [0.5,"tsp","salt","salt","sal","salt"],
    [40,"g","butter","fat","mantequilla","butter","derretida, y más para cocinar","melted, plus more for cooking"],
    [200,"g","queso","protein","queso blanco o mozzarella","white cheese or mozzarella","en tajadas","sliced"]],
 es:{n:"Arepas de choclo", b:"Arepas dulces de maíz tierno licuado, doradas en mantequilla y dobladas sobre una tajada de queso que se derrite.",
  st:["Licúa los granos de maíz hasta tener un puré grueso.",
      "Mezcla con la harina precocida, el azúcar, la sal y la mantequilla derretida. Deja reposar 10 minutos: debe quedar como una masa de pancakes espesa.",
      "Calienta un sartén antiadherente a fuego medio con un poco de mantequilla.",
      "Vierte 3 cucharadas de mezcla por arepa y extiende en un círculo. Cuece 3 minutos por lado, hasta que estén doradas.",
      "Pon una tajada de queso en la mitad de cada arepa caliente y dóblala."],
  tp:["Si la mezcla está muy líquida, añade 1 cucharada más de harina.",
      "Fuego medio: si está muy alto, se queman antes de cocerse por dentro."],
  v:"arepas de choclo receta"},
 en:{n:"Sweet Corn Arepas (Arepas de Choclo)", b:"Sweet arepas of blended fresh corn, browned in butter and folded over a slice of melting cheese.",
  st:["Blend the corn kernels into a coarse purée.",
      "Mix with the precooked cornmeal, sugar, salt and melted butter. Rest 10 minutes: it should look like thick pancake batter.",
      "Heat a non-stick pan over medium heat with a little butter.",
      "Pour 3 tablespoons of batter per arepa and spread into a circle. Cook 3 minutes per side, until golden.",
      "Put a slice of cheese on half of each hot arepa and fold it over."],
  tp:["If the batter is too runny, add 1 more tablespoon of cornmeal.",
      "Medium heat: too high and they burn before cooking through."],
  v:"arepas de choclo recipe"}},

{id:"arepa-de-huevo", c:"Colombia", r:"latin-america", m:"snack", t:50, s:6,
 i:[[300,"g","cornmeal","structure","harina de maíz precocida amarilla","yellow precooked cornmeal (masarepa)"],
    [400,"ml","water","liquid","agua tibia","warm water"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"tbsp","sugar","sweet","azúcar","sugar"],
    [6,"","egg","protein","huevos","eggs"],
    [1,"l","oil","fat","aceite","oil","para freír","for frying"]],
 es:{n:"Arepa de huevo", b:"La arepa frita de la costa caribe: se infla en el aceite, se abre, se le mete un huevo crudo y se fríe otra vez.",
  st:["Mezcla la harina, el agua, la sal y el azúcar y amasa hasta que esté lisa. Deja reposar 10 minutos.",
      "Forma 6 bolas y aplánalas entre plástico a 1 centímetro de grueso, de unos 12 centímetros.",
      "Calienta el aceite a 170 °C en una olla honda. Fríe cada arepa 3 minutos, volteándola, hasta que se infle.",
      "Sácala, escúrrela y haz un corte de 5 centímetros en el borde con un cuchillo para abrir un bolsillo.",
      "Rompe un huevo en una taza, viértelo dentro del bolsillo y sella el corte apretando con un poco de masa cruda.",
      "Fríe otra vez 4 minutos, hasta que esté dorada y el huevo cuajado. Escurre y sirve caliente."],
  tp:["Si no se infla, el aceite está frío o la arepa es muy gruesa.",
      "Sella bien el corte: si entra aceite, el huevo se reventará."],
  v:"arepa de huevo receta"},
 en:{n:"Egg-Stuffed Arepa (Arepa de Huevo)", b:"The fried arepa of Colombia's Caribbean coast: it puffs in the oil, gets slit open, filled with a raw egg and fried again.",
  st:["Mix the cornmeal, water, salt and sugar and knead until smooth. Rest 10 minutes.",
      "Shape 6 balls and flatten them between plastic to 1 centimetre thick, about 12 centimetres wide.",
      "Heat the oil to 170 °C in a deep pot. Fry each arepa 3 minutes, turning, until it puffs.",
      "Lift it out, drain and cut a 5 centimetre slit in the edge with a knife to open a pocket.",
      "Crack an egg into a cup, pour it into the pocket and seal the slit by pressing on a little raw dough.",
      "Fry again 4 minutes, until golden and the egg is set. Drain and serve hot."],
  tp:["If it doesn't puff, the oil is too cool or the arepa too thick.",
      "Seal the slit well: if oil gets in, the egg bursts."],
  v:"arepa de huevo recipe"}},

{id:"empanadas-colombianas", c:"Colombia", r:"latin-america", m:"snack", t:90, s:8,
 i:[[400,"g","cornmeal","structure","harina de maíz precocida amarilla","yellow precooked cornmeal (masarepa)"],
    [550,"ml","water","liquid","agua tibia","warm water"],
    [2,"tsp","salt","salt","sal","salt"],
    [1,"tsp","achiote","aromatic","achiote en polvo","ground annatto"],
    [400,"g","potato","structure","papa pastusa o amarilla","yellow potatoes","pelada, en cubos","peeled, diced"],
    [300,"g","beef","protein","carne molida de res","ground beef"],
    [2,"","tomato","aromatic","tomates","tomatoes","picados","chopped"],
    [3,"","scallion","aromatic","tallos de cebolla larga","green onion stalks","picados","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [0.5,"tsp","spice","aromatic","comino molido","ground cumin"],
    [1,"l","oil","fat","aceite","oil","para freír","for frying"],
    [8,"","citrus","garnish","limones","limes","en cuartos","quartered"]],
 es:{n:"Empanadas colombianas", b:"Empanadas de masa de maíz amarilla, crujientes, rellenas de papa y carne con hogao. Con ají y limón.",
  st:["Cuece la papa en agua con sal 12 minutos. Escurre y aplasta a medias.",
      "Sofríe el tomate, la cebolla larga y el ajo en 2 cucharadas de aceite 8 minutos. Añade la carne, el comino y 1 cucharadita de sal y cuece 10 minutos. Mezcla con la papa y deja enfriar.",
      "Mezcla la harina, el agua, el achiote y el resto de la sal. Amasa hasta que esté lisa y reposa 10 minutos.",
      "Aplana bolitas de masa entre 2 plásticos, pon 1 cucharada de relleno, dobla con el plástico y corta con un plato pequeño para sellar.",
      "Fríe en aceite a 180 °C 4 minutos, hasta que estén doradas y crujientes. Escurre.",
      "Sirve con ají colombiano y limón."],
  tp:["Usar el plástico para doblar evita que la masa se rompa.",
      "Crudas se congelan bien en una capa; se fríen sin descongelar, 6 minutos."],
  v:"empanadas colombianas receta"},
 en:{n:"Colombian Empanadas", b:"Crisp yellow corn empanadas filled with potato and beef cooked in hogao. With ají and lime.",
  st:["Boil the potato in salted water for 12 minutes. Drain and half-mash.",
      "Cook the tomato, green onion and garlic in 2 tablespoons of oil for 8 minutes. Add the beef, cumin and 1 teaspoon of salt and cook 10 minutes. Mix with the potato and cool.",
      "Mix the cornmeal, water, annatto and the rest of the salt. Knead until smooth and rest 10 minutes.",
      "Flatten small balls of dough between 2 sheets of plastic, add 1 tablespoon of filling, fold using the plastic and press with a small plate to seal.",
      "Fry in oil at 180 °C for 4 minutes, until golden and crisp. Drain.",
      "Serve with Colombian ají and lime."],
  tp:["Folding with the plastic keeps the dough from cracking.",
      "Raw, they freeze well in a single layer; fry from frozen, 6 minutes."],
  v:"colombian empanadas recipe"}},

{id:"changua", c:"Colombia", r:"latin-america", m:"breakfast", t:15, s:2,
 i:[[400,"ml","milk","liquid","leche","milk"],
    [200,"ml","water","liquid","agua","water"],
    [1,"","scallion","aromatic","tallo de cebolla larga","green onion stalk","picado fino","finely chopped"],
    [0.5,"tsp","salt","salt","sal","salt"],
    [4,"","egg","protein","huevos","eggs"],
    [1,"tbsp","herb","garnish","cilantro","cilantro","picado","chopped"],
    [2,"slice","bread","serve","calado o pan tostado","calado or toasted bread","en trozos","torn"]],
 es:{n:"Changua", b:"El desayuno de Bogotá: huevos escalfados en leche caliente con cebolla larga y cilantro, con pan para remojar.",
  st:["Calienta la leche, el agua, la cebolla y la sal hasta que empiece a hervir.",
      "Baja el fuego. Rompe los huevos uno a uno dentro del líquido, sin moverlos.",
      "Cuece 3 minutos, hasta que la clara cuaje y la yema siga suave.",
      "Pon el pan en platos hondos, sirve los huevos con la leche encima y termina con cilantro."],
  tp:["La leche no debe hervir fuerte con los huevos dentro: se corta y los huevos se deshacen.",
      "En embarazo o con defensas bajas, cuece 5 minutos, hasta que la yema cuaje."],
  v:"changua receta"},
 en:{n:"Changua (Bogotá Milk and Egg Soup)", b:"Bogotá's breakfast: eggs poached in hot milk with green onion and cilantro, with bread for dunking.",
  st:["Heat the milk, water, green onion and salt until it starts to boil.",
      "Lower the heat. Crack the eggs one at a time into the liquid, without stirring.",
      "Cook 3 minutes, until the whites set and the yolks are still soft.",
      "Put the bread in deep bowls, ladle in the eggs and milk and finish with cilantro."],
  tp:["Don't let the milk boil hard with the eggs in: it curdles and the eggs break up.",
      "If pregnant or immunocompromised, cook 5 minutes, until the yolks set."],
  v:"changua recipe"}},

{id:"patacones", c:"Colombia", r:"latin-america", m:"side", t:30, s:4,
 i:[[3,"","plantain","structure","plátanos verdes","green plantains","pelados","peeled"],
    [500,"ml","oil","fat","aceite","oil","para freír","for frying"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Patacones", b:"Plátano verde frito dos veces: primero blando, luego aplastado y otra vez al aceite hasta crujir.",
  st:["Corta los plátanos en trozos de 4 centímetros.",
      "Fríelos en aceite a 160 °C 5 minutos, hasta que estén blandos pero sin dorar. Escurre.",
      "Aplasta cada trozo con una tabla o el fondo de un plato hasta 1 centímetro de grueso.",
      "Sube el aceite a 180 °C y fríelos otra vez 3 minutos, hasta que estén dorados y crujientes.",
      "Escurre en papel y sala enseguida."],
  tp:["Para pelar plátano verde, corta las puntas, haz un corte a lo largo y saca la cáscara con el pulgar.",
      "Sírvelos con hogao o ají, o como base para carne desmechada."],
  v:"patacones receta"},
 en:{n:"Patacones (Twice-Fried Plantains)", b:"Green plantain fried twice: first until soft, then smashed and fried again until crisp.",
  st:["Cut the plantains into 4 centimetre pieces.",
      "Fry in oil at 160 °C for 5 minutes, until soft but not browned. Drain.",
      "Smash each piece with a board or the bottom of a plate to 1 centimetre thick.",
      "Raise the oil to 180 °C and fry again 3 minutes, until golden and crisp.",
      "Drain on paper and salt right away."],
  tp:["To peel a green plantain, cut off the ends, slit the skin lengthwise and push it off with your thumb.",
      "Serve with hogao or ají, or as a base for shredded beef."],
  v:"patacones recipe"}},

{id:"hogao", c:"Colombia", r:"latin-america", m:"sauce", t:25, s:6,
 i:[[4,"","tomato","aromatic","tomates maduros","ripe tomatoes","rallados o picados","grated or chopped"],
    [6,"","scallion","aromatic","tallos de cebolla larga","green onion stalks","picados","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [0.25,"tsp","spice","aromatic","comino molido","ground cumin"],
    [0.5,"tsp","salt","salt","sal","salt"]],
 es:{n:"Hogao", b:"El sofrito colombiano de tomate y cebolla larga cocidos despacio. Va sobre arepas, patacones, papas y frijoles.",
  st:["Calienta el aceite a fuego medio y sofríe la cebolla larga y el ajo 3 minutos.",
      "Añade el tomate, el comino y la sal.",
      "Cuece a fuego bajo 15 minutos, moviendo, hasta que el tomate se deshaga y el aceite se separe en los bordes."],
  tp:["Rallar el tomate por el lado grueso del rallador deja la piel en la mano y la pulpa en el plato.",
      "Dura 5 días en el refrigerador."],
  v:"hogao colombiano receta"},
 en:{n:"Hogao (Colombian Tomato and Onion Sauce)", b:"Colombia's sofrito of tomato and green onion cooked down slowly. It goes on arepas, patacones, potatoes and beans.",
  st:["Heat the oil over medium heat and cook the green onion and garlic for 3 minutes.",
      "Add the tomato, cumin and salt.",
      "Cook on low for 15 minutes, stirring, until the tomato breaks down and the oil separates at the edges."],
  tp:["Grating the tomato on the coarse side of a grater leaves the skin in your hand and the pulp in the bowl.",
      "Keeps 5 days in the fridge."],
  v:"hogao recipe"}},

{id:"aji-colombiano", c:"Colombia", r:"latin-america", m:"sauce", t:15, s:8,
 i:[[2,"","chilli","aromatic","ajíes picantes o chiles habaneros","hot chiles or habaneros","sin semillas, picados finos","seeded, finely chopped"],
    [3,"","scallion","aromatic","tallos de cebolla larga","green onion stalks","picados finos","finely chopped"],
    [1,"","tomato","aromatic","tomate","tomato","sin semillas, picado fino","seeded, finely chopped"],
    [1,"bunch","herb","aromatic","cilantro","cilantro","picado fino","finely chopped"],
    [2,"","citrus","acid","limones","limes","en jugo","juiced"],
    [60,"ml","whitevinegar","acid","vinagre blanco","white vinegar"],
    [120,"ml","water","liquid","agua","water"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Ají colombiano", b:"La salsa aguada y picante de cilantro, cebolla larga y ají que acompaña empanadas, sancocho y todo lo frito.",
  st:["Mezcla el agua, el vinagre, el jugo de limón y la sal.",
      "Añade el ají, la cebolla, el tomate y el cilantro.",
      "Deja reposar 30 minutos antes de servir para que el picante se reparta."],
  tp:["Pica todo muy fino a cuchillo: no se licúa.",
      "Dura 1 semana en el refrigerador, pero el cilantro se oscurece al tercer día."],
  v:"aji colombiano receta"},
 en:{n:"Colombian Ají (Hot Cilantro Sauce)", b:"The thin, hot sauce of cilantro, green onion and chile that goes with empanadas, sancocho and anything fried.",
  st:["Mix the water, vinegar, lime juice and salt.",
      "Add the chile, green onion, tomato and cilantro.",
      "Let it sit 30 minutes before serving so the heat spreads."],
  tp:["Chop everything very fine by hand: don't blend it.",
      "Keeps 1 week in the fridge, but the cilantro darkens by the third day."],
  v:"colombian aji recipe"}}
];
