module.exports = [
{id:"frijoles-antioquenos", c:"Colombia", ce:"Colombia", r:"latin-america", m:"main", t:150, s:8,
 i:[[500,"g","legume","protein","frijoles cargamanto o rojos","cargamanto or red beans","remojados 12 horas","soaked 12 hours"],
    [2.5,"l","water","liquid","agua","water"],
    [300,"g","porkbelly","protein","tocino de cerdo con piel","skin-on pork belly","en trozos","in pieces"],
    [1,"","plantain","thicken","plátano verde","green plantain","en trocitos","in small pieces"],
    [1,"","veg","structure","zanahoria","carrot","rallada","grated"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [4,"","scallion","aromatic","tallos de cebolla larga","long green onion stalks","picados","chopped"],
    [2,"","tomato","sauce","tomates","tomatoes","picados","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Frijoles antioqueños", b:"Frijoles espesos con tocino, plátano verde y hogao. El corazón de la bandeja paisa, también solos con arroz.",
  st:["Cuece los frijoles con el agua y el tocino 90 minutos, hasta que estén tiernos.",
      "Añade el plátano y la zanahoria y cuece 30 minutos más; el plátano se deshace y espesa.",
      "Para el hogao, sofríe la cebolla larga, el tomate y el ajo en el aceite 10 minutos con el comino.",
      "Añade el hogao y la sal a los frijoles y cuece 10 minutos.",
      "Sirve con arroz blanco."],
  tp:["Pica el plátano con los dedos en trocitos en vez de cortarlo; así suelta más almidón.",
      "No añadas sal hasta que los frijoles estén tiernos o se endurecen."],
  v:"frijoles antioqueños receta"},
 en:{n:"Frijoles Antioqueños (Colombian Red Beans)", b:"Thick beans with pork belly, green plantain and hogao. The heart of the bandeja paisa, and good on their own with rice.",
  st:["Cook the beans with the water and pork belly for 90 minutes, until tender.",
      "Add the plantain and carrot and cook 30 minutes more; the plantain breaks down and thickens.",
      "For the hogao, cook the green onion, tomato and garlic in the oil for 10 minutes with the cumin.",
      "Add the hogao and salt to the beans and cook 10 minutes.",
      "Serve with white rice."],
  tp:["Break the plantain into small pieces with your fingers instead of cutting it; it releases more starch.",
      "Don't salt until the beans are tender or they toughen."],
  v:"colombian red beans recipe"}},

{id:"sudado-de-pollo", c:"Colombia", r:"latin-america", m:"main", t:60, s:6,
 i:[[1.2,"kg","chicken","protein","pollo en presas","chicken pieces"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [4,"","scallion","aromatic","tallos de cebolla larga","long green onion stalks","picados","chopped"],
    [3,"","tomato","sauce","tomates","tomatoes","picados","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [1,"tsp","achiote","aromatic","color (achiote en polvo)","ground annatto (color)"],
    [600,"g","potato","structure","papas","potatoes","peladas, en mitades","peeled, halved"],
    [300,"g","cassava","structure","yuca","cassava","en trozos","in chunks"],
    [300,"ml","water","liquid","agua","water"],
    [2,"tsp","salt","salt","sal","salt"],
    [1,"handful","herb","garnish","cilantro","cilantro","picado","chopped"]],
 es:{n:"Sudado de pollo", b:"Pollo cocido al vapor de su propio hogao con papa y yuca. Almuerzo de todos los días en Colombia.",
  st:["Sofríe la cebolla, el tomate y el ajo en el aceite con el comino y el color 8 minutos.",
      "Añade el pollo y la sal, mezcla y tapa. Cuece 15 minutos a fuego bajo; el pollo suelta su jugo.",
      "Añade la papa, la yuca y el agua. Tapa y cuece 25 minutos, hasta que estén tiernas.",
      "Destapa y deja reducir 5 minutos si hay mucho líquido.",
      "Termina con el cilantro y sirve con arroz."],
  tp:["Mantén la olla tapada: el sudado se cocina en su vapor.",
      "La papa criolla, si la encuentras, espesa la salsa al deshacerse."],
  v:"sudado de pollo colombiano"},
 en:{n:"Sudado de Pollo (Colombian Braised Chicken)", b:"Chicken steamed in its own hogao with potato and cassava. An everyday Colombian lunch.",
  st:["Cook the green onion, tomato and garlic in the oil with the cumin and annatto for 8 minutes.",
      "Add the chicken and salt, stir and cover. Cook 15 minutes on low; the chicken releases its juices.",
      "Add the potato, cassava and water. Cover and cook 25 minutes, until tender.",
      "Uncover and reduce 5 minutes if there's a lot of liquid.",
      "Finish with the cilantro and serve with rice."],
  tp:["Keep the lid on: a sudado cooks in its own steam.",
      "Papa criolla, if you find it, thickens the sauce as it breaks down."],
  v:"colombian chicken stew recipe"}},

{id:"chocolate-santafereno", c:"Colombia", r:"latin-america", m:"drink", t:15, s:4,
 i:[[1,"l","milk","liquid","leche","milk"],
    [100,"g","tablechocolate","sweet","chocolate de mesa","table chocolate","en trozos","in pieces"],
    [1,"","spice","aromatic","rama de canela","cinnamon stick"],
    [4,"","spice","aromatic","clavos de olor","whole cloves"],
    [150,"g","cheese","serve","queso campesino o doble crema","fresh farmer's cheese","en dados","diced"]],
 es:{n:"Chocolate santafereño", b:"Chocolate caliente batido con molinillo y servido con queso que se funde dentro. Las onces de Bogotá.",
  st:["Calienta la leche con la canela y los clavos.",
      "Añade el chocolate y cuece 5 minutos a fuego bajo, removiendo, hasta que se disuelva.",
      "Bate con molinillo o batidor hasta que haga espuma.",
      "Pon los dados de queso en las tazas.",
      "Sirve el chocolate caliente encima y deja que el queso se ablande."],
  tp:["Saca la canela y los clavos antes de batir.",
      "Deja que hierva y baje tres veces, como en las casas bogotanas; así espesa."],
  v:"chocolate santafereño con queso"},
 en:{n:"Chocolate Santafereño (Hot Chocolate with Cheese)", b:"Hot chocolate frothed with a molinillo and served with cheese that melts inside. Bogotá's afternoon snack.",
  st:["Heat the milk with the cinnamon and cloves.",
      "Add the chocolate and cook 5 minutes on low, stirring, until dissolved.",
      "Froth with a molinillo or whisk.",
      "Put the cheese cubes in the cups.",
      "Pour the hot chocolate over and let the cheese soften."],
  tp:["Take out the cinnamon and cloves before frothing.",
      "Let it rise and fall three times, as Bogotá households do; it thickens."],
  v:"colombian hot chocolate with cheese"}},

{id:"aborrajados", c:"Colombia", r:"latin-america", m:"snack", t:40, s:6,
 i:[[3,"","plantain","structure","plátanos maduros","ripe plantains","pelados, en 4 trozos","peeled, in 4 pieces"],
    [1,"l","oil","fat","aceite para freír","oil for frying"],
    [200,"g","cheese","protein","queso mozzarella o costeño","mozzarella or costeño cheese","en lonchas","sliced"],
    [120,"g","guavapaste","sweet","bocadillo de guayaba","guava paste","en lonchas","sliced"],
    [120,"g","apflour","dredge","harina de trigo","plain flour"],
    [1,"","egg","binder","huevo","egg"],
    [150,"ml","milk","liquid","leche","milk"],
    [1,"tbsp","sugar","sweet","azúcar","sugar"],
    [1,"pinch","salt","salt","sal","salt"]],
 es:{n:"Aborrajados", b:"Plátano maduro frito relleno de queso y bocadillo de guayaba, rebozado y frito otra vez. Del Valle del Cauca.",
  st:["Fríe los trozos de plátano a 170 °C durante 4 minutos. Escúrrelos.",
      "Aplasta cada trozo entre dos plásticos hasta 1 cm.",
      "Pon una loncha de queso y una de bocadillo sobre un plátano y cubre con otro. Aprieta los bordes.",
      "Bate la harina, el huevo, la leche, el azúcar y la sal hasta tener una masa lisa.",
      "Pasa cada aborrajado por la masa y fríe a 180 °C durante 2 minutos por lado, hasta que estén dorados."],
  tp:["Usa plátano bien maduro, con la cáscara casi negra.",
      "Sírvelos calientes, con el queso aún fundido."],
  v:"aborrajados vallunos receta"},
 en:{n:"Aborrajados (Stuffed Fried Plantains)", b:"Fried ripe plantain stuffed with cheese and guava paste, battered and fried again. From the Cauca Valley.",
  st:["Fry the plantain pieces at 170 °C for 4 minutes. Drain.",
      "Flatten each piece between two sheets of plastic to 1 cm.",
      "Lay a slice of cheese and one of guava paste on a plantain and cover with another. Press the edges.",
      "Whisk the flour, egg, milk, sugar and salt to a smooth batter.",
      "Dip each aborrajado in the batter and fry at 180 °C for 2 minutes a side, until golden."],
  tp:["Use very ripe plantain, with almost black skin.",
      "Serve hot, with the cheese still melted."],
  v:"aborrajados recipe"}},

{id:"caldo-de-costilla", c:"Colombia", r:"latin-america", m:"soup", t:75, s:6,
 i:[[1,"kg","beef","protein","costilla de res","beef short ribs","en trozos","cut up"],
    [2.5,"l","water","liquid","agua","water"],
    [1,"","onion","aromatic","cebolla","onion","en mitades","halved"],
    [3,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [1,"kg","potato","structure","papas","potatoes","peladas, en trozos","peeled, in chunks"],
    [4,"","scallion","garnish","cebolla larga","long green onion","picada","chopped"],
    [1,"bunch","herb","garnish","cilantro","cilantro","picado","chopped"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Caldo de costilla", b:"Sopa clara de costilla de res con papa y mucho cilantro. El desayuno que levanta en Bogotá después de una noche larga.",
  st:["Cuece la costilla en el agua con la cebolla, el ajo y la sal 50 minutos, quitando la espuma.",
      "Saca la cebolla.",
      "Añade las papas y cuece 20 minutos, hasta que estén tiernas.",
      "Prueba y ajusta la sal.",
      "Sirve con la cebolla larga y el cilantro por encima."],
  tp:["Quitar la espuma al principio deja la sopa clara.",
      "Se acompaña con arepa y un chocolate caliente."],
  v:"caldo de costilla receta colombiana"},
 en:{n:"Caldo de Costilla (Beef Rib Soup)", b:"A clear beef rib soup with potato and lots of cilantro. The breakfast that revives Bogotá after a long night.",
  st:["Simmer the ribs in the water with the onion, garlic and salt for 50 minutes, skimming.",
      "Remove the onion.",
      "Add the potatoes and cook 20 minutes, until tender.",
      "Taste and adjust the salt.",
      "Serve with the green onion and cilantro on top."],
  tp:["Skimming at the start keeps the soup clear.",
      "It is served with arepa and a hot chocolate."],
  v:"colombian beef rib soup recipe"}},

{id:"arroz-atollado", c:"Colombia", r:"latin-america", m:"main", t:70, s:8,
 i:[[3,"tbsp","oil","fat","aceite","oil"],
    [500,"g","pork","protein","carne de cerdo","pork","en dados","diced"],
    [500,"g","chicken","protein","pollo","chicken","en presas pequeñas","in small pieces"],
    [200,"g","chorizo","protein","chorizo","chorizo","en rodajas","sliced"],
    [4,"","scallion","aromatic","tallos de cebolla larga","long green onion stalks","picados","chopped"],
    [3,"","tomato","sauce","tomates","tomatoes","picados","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"tsp","achiote","aromatic","color (achiote en polvo)","ground annatto (color)"],
    [400,"g","rice","structure","arroz","rice"],
    [600,"g","potato","structure","papa criolla o papas pequeñas","papa criolla or small potatoes"],
    [2,"l","water","liquid","agua","water"],
    [2,"tsp","salt","salt","sal","salt"],
    [1,"handful","herb","garnish","cilantro","cilantro","picado","chopped"]],
 es:{n:"Arroz atollado", b:"Arroz caldoso y meloso con cerdo, pollo, chorizo y papa criolla. Plato de fiesta del Valle del Cauca.",
  st:["Dora el cerdo, el pollo y el chorizo en el aceite 10 minutos.",
      "Añade la cebolla, el tomate, el ajo y el color y cuece 8 minutos.",
      "Añade el agua y la sal y cuece 20 minutos.",
      "Añade el arroz y la papa y cuece 20 minutos, removiendo de vez en cuando, hasta que el arroz esté cremoso y caldoso.",
      "Termina con el cilantro."],
  tp:["Debe quedar meloso, como un risotto suelto; añade agua caliente si se seca.",
      "La papa criolla se deshace y da el color amarillo y la cremosidad."],
  v:"arroz atollado valluno receta"},
 en:{n:"Arroz Atollado (Soupy Colombian Rice)", b:"Soupy, creamy rice with pork, chicken, chorizo and yellow potatoes. A party dish from the Cauca Valley.",
  st:["Brown the pork, chicken and chorizo in the oil for 10 minutes.",
      "Add the green onion, tomato, garlic and annatto and cook 8 minutes.",
      "Add the water and salt and cook 20 minutes.",
      "Add the rice and potatoes and cook 20 minutes, stirring now and then, until the rice is creamy and soupy.",
      "Finish with the cilantro."],
  tp:["It should be loose, like a runny risotto; add hot water if it dries.",
      "Papa criolla breaks down and gives the yellow colour and creaminess."],
  v:"arroz atollado recipe"}},

{id:"cocadas", c:"Colombia", r:"latin-america", m:"sweet", t:40, s:16,
 i:[[300,"g","desiccatedcoconut","structure","coco rallado fresco o seco","fresh or desiccated coconut"],
    [250,"g","jaggery","sweet","panela rallada","grated panela"],
    [200,"ml","water","liquid","agua","water"],
    [1,"","spice","aromatic","rama de canela","cinnamon stick"],
    [1,"","citrus","aromatic","ralladura de limón","lime zest"]],
 es:{n:"Cocadas costeñas", b:"Dulces de coco cocido en panela, en montoncitos. Las venden las palenqueras en Cartagena.",
  st:["Cuece la panela con el agua y la canela 5 minutos, hasta que se disuelva.",
      "Añade el coco y la ralladura y cuece a fuego medio 15 minutos, removiendo, hasta que se despegue del fondo.",
      "Saca la canela.",
      "Forma montoncitos con dos cucharas sobre papel de horno.",
      "Deja enfriar y endurecer 30 minutos."],
  tp:["Trabaja rápido al formar las cocadas: la mezcla se endurece al enfriarse.",
      "Con coco seco, añade 50 ml más de agua."],
  v:"cocadas de coco y panela"},
 en:{n:"Cocadas (Coconut Panela Sweets)", b:"Coconut sweets cooked in panela, dropped in little mounds. Sold by the palenqueras of Cartagena.",
  st:["Simmer the panela with the water and cinnamon for 5 minutes, until dissolved.",
      "Add the coconut and zest and cook over medium heat for 15 minutes, stirring, until it pulls from the bottom.",
      "Remove the cinnamon.",
      "Drop little mounds with two spoons onto baking paper.",
      "Leave to cool and harden for 30 minutes."],
  tp:["Work fast when shaping: the mixture hardens as it cools.",
      "With desiccated coconut, add 50 ml more water."],
  v:"cocadas recipe"}},

{id:"salpicon-de-frutas", c:"Colombia", r:"latin-america", m:"drink", t:15, s:6,
 i:[[1,"","fruit","structure","papaya pequeña","small papaya","en dados","diced"],
    [0.5,"","fruit","structure","piña","pineapple","en dados","diced"],
    [2,"","fruit","structure","plátanos (bananos)","bananas","en dados","diced"],
    [1,"","fruit","structure","manzana","apple","en dados","diced"],
    [200,"g","fruit","structure","fresas","strawberries","en dados","diced"],
    [1,"l","fruit","liquid","jugo de sandía","watermelon juice"],
    [1,"","citrus","acid","limón","lime","en jugo","juiced"]],
 es:{n:"Salpicón de frutas", b:"Fruta picada flotando en jugo de sandía. Se toma con cuchara en las calles de Cali.",
  st:["Pica todas las frutas en dados de 1 cm.",
      "Mézclalas en una jarra grande.",
      "Añade el jugo de sandía y el jugo de limón.",
      "Refrigera 30 minutos.",
      "Sirve en vasos con cuchara."],
  tp:["Para el jugo, licúa sandía sin semillas y cuélala.",
      "El limón evita que la manzana y el plátano se oscurezcan."],
  v:"salpicón de frutas colombiano"},
 en:{n:"Salpicón de Frutas (Fruit in Watermelon Juice)", b:"Diced fruit floating in watermelon juice. Eaten with a spoon on the streets of Cali.",
  st:["Dice all the fruit into 1 cm cubes.",
      "Mix in a large jug.",
      "Add the watermelon juice and lime juice.",
      "Refrigerate 30 minutes.",
      "Serve in glasses with a spoon."],
  tp:["For the juice, blend seedless watermelon and strain it.",
      "The lime stops the apple and banana browning."],
  v:"colombian salpicon recipe"}},

{id:"mazamorra-antioquena", c:"Colombia", r:"latin-america", m:"drink", t:240, s:8,
 i:[[500,"g","hominy","structure","maíz peto (maíz blanco pelado)","peeled white corn (maíz peto)","remojado 12 horas","soaked 12 hours"],
    [3,"l","water","liquid","agua","water"],
    [1,"pinch","bakingsoda","structure","bicarbonato de sodio","baking soda"],
    [500,"ml","milk","serve","leche fría","cold milk"],
    [150,"g","jaggery","serve","panela","panela","en trozos","in pieces"]],
 es:{n:"Mazamorra antioqueña", b:"Maíz blanco cocido hasta ablandarse, servido en su líquido con leche fría y un trozo de panela.",
  st:["Cuece el maíz en el agua con el bicarbonato a fuego bajo 3 horas y media, hasta que esté blando y abierto.",
      "Añade agua caliente si baja mucho; debe quedar cubierto.",
      "Deja enfriar en su líquido.",
      "Sirve en vasos con parte del líquido y la leche fría.",
      "Acompaña cada vaso con un trozo de panela para morder."],
  tp:["En olla a presión tarda 1 hora.",
      "Se guarda 3 días en la nevera con su líquido."],
  v:"mazamorra antioqueña receta"},
 en:{n:"Mazamorra Antioqueña (White Corn in Milk)", b:"White corn simmered until soft, served in its liquid with cold milk and a piece of panela.",
  st:["Simmer the corn in the water with the baking soda on low for 3 and a half hours, until soft and split.",
      "Add hot water if it drops too low; it should stay covered.",
      "Let cool in its liquid.",
      "Serve in glasses with some of the liquid and the cold milk.",
      "Give each glass a piece of panela to bite."],
  tp:["In a pressure cooker it takes 1 hour.",
      "Keeps 3 days in the fridge in its liquid."],
  v:"mazamorra antioquena recipe"}},

{id:"pescado-frito-costeno", c:"Colombia", r:"latin-america", m:"main", t:40, s:4,
 i:[[4,"","whitefish","protein","mojarras o pargos enteros","whole tilapia or snapper","limpios","cleaned"],
    [2,"","citrus","acid","limones","limes","en jugo","juiced"],
    [3,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [2,"tsp","salt","salt","sal","salt"],
    [80,"g","apflour","dredge","harina de trigo","plain flour"],
    [1,"l","oil","fat","aceite para freír","oil for frying"],
    [1,"","citrus","garnish","limón","lime","en gajos","in wedges"]],
 es:{n:"Pescado frito costeño", b:"Pescado entero frito hasta que la piel y las aletas crujen. Se come en la playa con patacones y arroz con coco.",
  st:["Haz 3 cortes diagonales a cada lado del pescado.",
      "Frota con el jugo de limón, el ajo y la sal, también por dentro. Deja 20 minutos.",
      "Seca el pescado y pásalo por la harina.",
      "Fríe a 180 °C durante 6 minutos por lado, hasta que esté dorado y crujiente.",
      "Escurre y sirve con el limón."],
  tp:["Los cortes hacen que se cocine parejo y que la piel cruja.",
      "No lo muevas en el aceite hasta que se despegue solo."],
  v:"pescado frito costeño receta"},
 en:{n:"Colombian Coastal Fried Fish", b:"Whole fish fried until the skin and fins crackle. Eaten on the beach with patacones and coconut rice.",
  st:["Make 3 diagonal cuts on each side of the fish.",
      "Rub with the lime juice, garlic and salt, inside too. Leave 20 minutes.",
      "Pat the fish dry and coat in the flour.",
      "Fry at 180 °C for 6 minutes a side, until golden and crisp.",
      "Drain and serve with the lime."],
  tp:["The cuts help it cook evenly and crisp the skin.",
      "Don't move it in the oil until it releases on its own."],
  v:"colombian fried fish recipe"}}
];
