module.exports = [
{id:"calentado", c:"Colombia", r:"latin-america", m:"breakfast", t:20, s:2,
 i:[[300,"g","legume","protein","frijoles rojos cocidos del día anterior","leftover cooked red beans"],
    [250,"g","rice","structure","arroz blanco del día anterior","leftover white rice"],
    [1,"","tomato","aromatic","tomate","tomato","picado","chopped"],
    [2,"","scallion","aromatic","tallos de cebolla larga","green onion stalks","picados","chopped"],
    [1,"tbsp","oil","fat","aceite","oil"],
    [0.5,"tsp","salt","salt","sal","salt"],
    [2,"","egg","protein","huevos","eggs"],
    [2,"","cornmeal","serve","arepas","corn arepas"],
    [0.5,"","avocado","garnish","aguacate","avocado","en rebanadas","sliced"]],
 es:{n:"Calentado", b:"Los frijoles y el arroz de ayer salteados juntos con hogao, con huevo frito y arepa. El desayuno paisa.",
  st:["Calienta el aceite en un sartén y sofríe el tomate y la cebolla larga 5 minutos, hasta tener un hogao.",
      "Añade los frijoles con un poco de su líquido y el arroz. Saltea a fuego medio 8 minutos, aplastando un poco, hasta que se pegue y dore en partes.",
      "Prueba de sal.",
      "Fríe los huevos y calienta las arepas.",
      "Sirve el calentado con el huevo encima, la arepa y el aguacate."],
  tp:["Deja que se dore en el fondo del sartén sin mover: esa costra es lo mejor.",
      "Con carne desmechada sobrante, añádela con el arroz."],
  v:"calentado paisa receta"},
 en:{n:"Calentado (Colombian Rice and Beans Hash)", b:"Yesterday's beans and rice fried together with hogao, with a fried egg and arepa. The Paisa breakfast.",
  st:["Heat the oil in a pan and cook the tomato and green onion for 5 minutes, into a hogao.",
      "Add the beans with a little of their liquid and the rice. Fry over medium heat for 8 minutes, pressing down a little, until it sticks and browns in places.",
      "Taste for salt.",
      "Fry the eggs and warm the arepas.",
      "Serve the calentado with the egg on top, the arepa and avocado."],
  tp:["Let it brown on the bottom of the pan without stirring: that crust is the best part.",
      "With leftover shredded beef, add it with the rice."],
  v:"calentado recipe"}},

{id:"posta-negra", c:"Colombia", r:"latin-america", m:"main", t:150, s:6,
 i:[[1.2,"kg","beef","protein","posta o muchacho de res","beef eye of round","en una pieza","in one piece"],
    [4,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"","tomato","aromatic","tomates","tomatoes","picados","chopped"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [1,"tsp","pepper","aromatic","pimienta negra","black pepper"],
    [2,"tsp","salt","salt","sal","salt"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [150,"g","jaggery","caramel","panela rallada","grated panela (unrefined cane sugar)"],
    [500,"ml","water","liquid","agua","water"],
    [2,"leaf","herb","aromatic","hojas de laurel","bay leaves"]],
 es:{n:"Posta negra cartagenera", b:"Res cocida en un caramelo oscuro de panela con cebolla y tomate hasta quedar negra, brillante y agridulce. Clásico de Cartagena.",
  st:["Unta la carne con el ajo, el comino, la pimienta y la sal. Déjala 1 hora o toda la noche en el refrigerador.",
      "Calienta el aceite en una olla gruesa, añade la panela y deja que se derrita y oscurezca 3 minutos, hasta color café oscuro sin quemarse.",
      "Dora la carne en el caramelo por todos lados, 8 minutos. Cuidado: salpica.",
      "Añade la cebolla, el tomate, el laurel y el agua. Tapa y cuece a fuego bajo 2 horas, volteando cada 30 minutos.",
      "Saca la carne y reduce la salsa hasta que esté espesa y brillante. Rebana la carne y báñala con la salsa."],
  tp:["El caramelo debe ser oscuro pero no negro: quemado amarga toda la olla.",
      "Con arroz con coco y patacones es la comida de la costa."],
  v:"posta negra cartagenera receta"},
 en:{n:"Cartagena Black Beef (Posta Negra)", b:"Beef cooked in a dark panela caramel with onion and tomato until black, glossy and sweet-sour. A Cartagena classic.",
  st:["Rub the beef with the garlic, cumin, pepper and salt. Leave it 1 hour or overnight in the fridge.",
      "Heat the oil in a heavy pot, add the panela and let it melt and darken for 3 minutes, to dark brown without burning.",
      "Brown the beef in the caramel on all sides, 8 minutes. Careful: it spatters.",
      "Add the onion, tomato, bay and water. Cover and cook on low for 2 hours, turning every 30 minutes.",
      "Lift out the beef and reduce the sauce until thick and glossy. Slice the beef and spoon the sauce over."],
  tp:["The caramel should be dark but not black: burned, it makes the whole pot bitter.",
      "With coconut rice and patacones it is the meal of the coast."],
  v:"posta negra recipe"}},

{id:"arroz-con-coco", c:"Colombia", r:"latin-america", m:"side", t:50, s:6,
 i:[[800,"ml","coconutmilk","liquid","leche de coco","coconut milk"],
    [2,"tbsp","jaggery","caramel","panela rallada","grated panela (unrefined cane sugar)"],
    [400,"g","rice","structure","arroz blanco","white rice","enjuagado","rinsed"],
    [1,"tsp","salt","salt","sal","salt"],
    [250,"ml","water","liquid","agua","water"],
    [50,"g","driedfruit","sweet","pasas","raisins","opcional","optional"]],
 es:{n:"Arroz con coco", b:"El arroz de la costa caribe: leche de coco reducida hasta caramelizar, que tiñe el arroz de café y lo vuelve dulce y salado a la vez.",
  st:["Hierve 400 ml de la leche de coco con la panela en una olla, moviendo, 15 minutos, hasta que el agua se evapore, la grasa se separe y queden grumos dorados en el fondo.",
      "Añade el arroz y revuelve 2 minutos en esa grasa.",
      "Añade el resto de la leche de coco, el agua, la sal y las pasas. Hierve hasta que el líquido baje al nivel del arroz.",
      "Tapa, baja el fuego al mínimo y cuece 20 minutos. Apaga y deja tapado 5 minutos antes de soltar con tenedor."],
  tp:["Los grumos tostados del coco (el titoté) son el sabor: déjalos dorar bien sin quemar.",
      "Va con pescado frito, posta negra y patacones."],
  v:"arroz con coco titote receta"},
 en:{n:"Colombian Coconut Rice", b:"Rice from the Caribbean coast: coconut milk reduced until it caramelises, turning the rice brown and both sweet and savoury.",
  st:["Boil 400 ml of the coconut milk with the panela in a pot, stirring, for 15 minutes, until the water evaporates, the fat separates and golden bits form on the bottom.",
      "Add the rice and stir it in that fat for 2 minutes.",
      "Add the rest of the coconut milk, the water, salt and raisins. Boil until the liquid drops to the level of the rice.",
      "Cover, turn the heat to the lowest and cook 20 minutes. Turn off and leave covered 5 minutes before fluffing with a fork."],
  tp:["The toasted coconut bits (titoté) are the flavour: let them brown well without burning.",
      "It goes with fried fish, posta negra and patacones."],
  v:"colombian coconut rice recipe"}},

{id:"pandebono", c:"Colombia", r:"latin-america", m:"bread", t:40, s:12, o:220,
 i:[[250,"g","queso","structure","queso costeño o feta rallado fino","finely grated queso costeño or feta"],
    [100,"g","cassavastarch","structure","almidón de yuca","tapioca starch"],
    [30,"g","cornmeal","structure","harina de maíz precocida","precooked cornmeal (masarepa)"],
    [1,"tbsp","sugar","sweet","azúcar","sugar"],
    [0.5,"tsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [1,"","egg","binder","huevo","egg"],
    [2,"tbsp","milk","liquid","leche","milk","si hace falta","if needed"]],
 es:{n:"Pandebono", b:"Panecillos del Valle del Cauca de queso y almidón de yuca: crujientes por fuera, elásticos por dentro. Sin trigo.",
  st:["Calienta el horno a 220 °C.",
      "Mezcla el queso, el almidón, la harina de maíz, el azúcar y el polvo de hornear, frotando con los dedos.",
      "Añade el huevo y amasa hasta que la masa esté lisa y no se pegue. Si está seca, añade leche de a cucharadita.",
      "Forma 12 bolas o roscas y ponlas en una charola con papel.",
      "Hornea 15 a 18 minutos, hasta que estén infladas y doradas. Cómelos tibios."],
  tp:["Frío pierden la gracia; recaliéntalos 3 minutos en el horno.",
      "El queso debe ser salado y firme: si usas uno fresco y húmedo, necesitarás más almidón."],
  v:"pandebono receta"},
 en:{n:"Pandebono (Cheese Bread)", b:"Cheese and tapioca rolls from Valle del Cauca: crisp outside, chewy inside. No wheat.",
  st:["Heat the oven to 220 °C.",
      "Mix the cheese, tapioca starch, cornmeal, sugar and baking powder, rubbing with your fingers.",
      "Add the egg and knead until the dough is smooth and not sticky. If dry, add milk a teaspoon at a time.",
      "Shape 12 balls or rings and set them on a lined tray.",
      "Bake 15 to 18 minutes, until puffed and golden. Eat them warm."],
  tp:["Cold they lose their charm; reheat 3 minutes in the oven.",
      "The cheese should be salty and firm: a fresh, moist one will need more starch."],
  v:"pandebono recipe"}},

{id:"bunuelos-colombianos", c:"Colombia", r:"latin-america", m:"snack", t:40, s:8,
 i:[[250,"g","queso","structure","queso costeño o feta rallado fino","finely grated queso costeño or feta"],
    [60,"g","cassavastarch","structure","almidón de yuca","tapioca starch"],
    [30,"g","cornstarch","structure","fécula de maíz","cornstarch"],
    [1,"tbsp","sugar","sweet","azúcar","sugar"],
    [0.5,"tsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [1,"","egg","binder","huevo","egg"],
    [1,"l","oil","fat","aceite","oil","para freír","for frying"]],
 es:{n:"Buñuelos colombianos", b:"Bolas de queso fritas que se voltean solas en el aceite, doradas y huecas por dentro. Infaltables en Navidad con natilla.",
  st:["Mezcla el queso, el almidón, la fécula, el azúcar y el polvo de hornear.",
      "Añade el huevo y amasa hasta tener una masa lisa que no se pegue.",
      "Forma 16 bolas lisas, sin grietas.",
      "Calienta el aceite a 150 °C. Fríe las bolas de a pocas 8 a 10 minutos: se hundirán, subirán y se voltearán solas. Súbelo a 170 °C los últimos 2 minutos para dorar.",
      "Escurre en papel y sirve tibios."],
  tp:["Aceite muy caliente al principio y se revientan: empieza tibio.",
      "Si se agrietan al formarlas, añade unas gotas de leche o agua."],
  v:"buñuelos colombianos receta"},
 en:{n:"Colombian Buñuelos (Cheese Fritters)", b:"Fried cheese balls that turn themselves over in the oil, golden and hollow inside. A Christmas must with natilla.",
  st:["Mix the cheese, tapioca starch, cornstarch, sugar and baking powder.",
      "Add the egg and knead into a smooth dough that doesn't stick.",
      "Shape 16 smooth balls without cracks.",
      "Heat the oil to 150 °C. Fry a few at a time for 8 to 10 minutes: they sink, rise and flip themselves. Raise it to 170 °C for the last 2 minutes to brown.",
      "Drain on paper and serve warm."],
  tp:["Oil too hot at the start and they burst: begin warm.",
      "If they crack when shaped, add a few drops of milk or water."],
  v:"colombian bunuelos recipe"}},

{id:"natilla", c:"Colombia", r:"latin-america", m:"sweet", t:40, s:8,
 i:[[1,"l","milk","liquid","leche","milk"],
    [250,"g","jaggery","sweet","panela rallada","grated panela (unrefined cane sugar)"],
    [2,"","spice","aromatic","rajas de canela","cinnamon sticks"],
    [120,"g","cornstarch","thicken","fécula de maíz","cornstarch"],
    [30,"g","butter","enrich","mantequilla","butter"],
    [50,"g","desiccatedcoconut","garnish","coco rallado","shredded coconut","opcional","optional"],
    [1,"tsp","spice","garnish","canela molida","ground cinnamon"]],
 es:{n:"Natilla colombiana", b:"El postre firme de Navidad: leche con panela y canela espesada con fécula hasta poder cortarse en cuadros.",
  st:["Disuelve la fécula en 250 ml de la leche fría.",
      "Calienta el resto de la leche con la panela y la canela hasta que la panela se disuelva.",
      "Saca la canela y añade la leche con fécula, moviendo sin parar.",
      "Cuece a fuego medio-bajo 15 minutos, moviendo con cuchara de palo, hasta que esté muy espesa y se vea el fondo de la olla al pasar la cuchara.",
      "Añade la mantequilla y el coco. Vierte en un molde engrasado, espolvorea canela y deja enfriar 2 horas antes de cortar."],
  tp:["No dejes de mover: la fécula se pega y hace grumos en segundos.",
      "Con buñuelos es la pareja de diciembre."],
  v:"natilla colombiana receta"},
 en:{n:"Colombian Natilla", b:"The firm Christmas dessert: milk with panela and cinnamon thickened with cornstarch until it can be cut into squares.",
  st:["Dissolve the cornstarch in 250 ml of the cold milk.",
      "Heat the rest of the milk with the panela and cinnamon until the panela dissolves.",
      "Remove the cinnamon and add the cornstarch milk, stirring constantly.",
      "Cook over medium-low heat for 15 minutes, stirring with a wooden spoon, until very thick and the spoon leaves a clear trail on the bottom of the pot.",
      "Stir in the butter and coconut. Pour into a greased dish, dust with cinnamon and cool 2 hours before cutting."],
  tp:["Keep stirring: cornstarch sticks and lumps in seconds.",
      "With buñuelos it is December's pair."],
  v:"natilla recipe"}},

{id:"obleas-arequipe", c:"Colombia", r:"latin-america", m:"sweet", t:10, s:4,
 i:[[8,"","wafer","structure","obleas grandes","large wafers"],
    [200,"g","dulcedeleche","spread","arequipe","arequipe (dulce de leche)"],
    [4,"tbsp","jam","spread","mermelada de mora","blackberry jam","opcional","optional"],
    [50,"g","cheese","garnish","queso blanco rallado","grated white cheese","opcional","optional"]],
 es:{n:"Obleas con arequipe", b:"Dos obleas finísimas unidas con arequipe, y si quieres, mermelada de mora y queso. El dulce de parque de Colombia.",
  st:["Unta una oblea con 2 cucharadas de arequipe.",
      "Añade 1 cucharada de mermelada y un poco de queso rallado, si quieres.",
      "Tapa con otra oblea y aprieta con suavidad.",
      "Cómelas enseguida: las obleas se ablandan en 10 minutos."],
  tp:["Se come sobre un plato: el arequipe se sale por los bordes.",
      "Con leche condensada en vez de arequipe también es clásica."],
  v:"obleas con arequipe"},
 en:{n:"Wafers with Arequipe (Obleas)", b:"Two paper-thin wafers stuck together with arequipe, plus blackberry jam and cheese if you like. Colombia's park-bench sweet.",
  st:["Spread one wafer with 2 tablespoons of arequipe.",
      "Add 1 tablespoon of jam and a little grated cheese, if you like.",
      "Cover with another wafer and press gently.",
      "Eat right away: the wafers soften within 10 minutes."],
  tp:["Eat it over a plate: the arequipe oozes out the sides.",
      "Condensed milk instead of arequipe is also classic."],
  v:"obleas colombianas"}},

{id:"lulada", c:"Colombia", r:"latin-america", m:"drink", t:10, s:2,
 i:[[4,"","fruit","acid","lulos (o naranjillas)","lulos (naranjilla)","pelados, en cuartos","peeled, quartered"],
    [1,"","citrus","acid","limón","lime","en jugo","juiced"],
    [3,"tbsp","sugar","sweet","azúcar","sugar"],
    [300,"ml","water","liquid","agua fría","cold water"],
    [1,"handful","ice","serve","hielo","ice"]],
 es:{n:"Lulada", b:"La bebida de Cali: lulo machacado con limón, azúcar y hielo, con trozos de fruta, no licuada.",
  st:["Machaca los lulos en una jarra con el azúcar hasta que suelten todo su jugo pero queden trozos.",
      "Añade el limón, el agua y el hielo.",
      "Mezcla y sirve de inmediato con cuchara larga."],
  tp:["No la licúes: las semillas molidas amargan y pierde la textura.",
      "Con lulo congelado en pulpa sale bien; usa 200 gramos."],
  v:"lulada caleña receta"},
 en:{n:"Lulada (Lulo Drink)", b:"Cali's drink: lulo muddled with lime, sugar and ice, left chunky rather than blended.",
  st:["Muddle the lulos in a jug with the sugar until they release all their juice but still have chunks.",
      "Add the lime, water and ice.",
      "Stir and serve right away with a long spoon."],
  tp:["Don't blend it: ground seeds turn it bitter and it loses its texture.",
      "Frozen lulo pulp works; use 200 grams."],
  v:"lulada recipe"}},

{id:"cazuela-de-mariscos", c:"Colombia", r:"latin-america", m:"soup", t:60, s:6,
 i:[[300,"g","shrimp","protein","camarones","shrimp","pelados","peeled"],
    [300,"g","clam","protein","almejas","clams","limpias","scrubbed"],
    [300,"g","mussel","protein","mejillones","mussels","limpios","cleaned"],
    [200,"g","squid","protein","calamar","squid","en aros","in rings"],
    [300,"g","whitefish","protein","pescado blanco firme","firm white fish","en cubos","cubed"],
    [2,"tbsp","butter","fat","mantequilla","butter"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","pimentón rojo","red bell pepper","picado","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"","tomato","aromatic","tomates","tomatoes","picados","chopped"],
    [1,"tsp","achiote","aromatic","achiote en polvo","ground annatto"],
    [150,"ml","winewhite","liquid","vino blanco","white wine"],
    [750,"ml","fishstock","liquid","caldo de pescado","fish stock"],
    [400,"ml","coconutmilk","liquid","leche de coco","coconut milk"],
    [150,"ml","heavycream","enrich","crema de leche","heavy cream"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"handful","herb","garnish","cilantro","cilantro","picado","chopped"]],
 es:{n:"Cazuela de mariscos", b:"La sopa cremosa de la costa colombiana: mariscos y pescado en leche de coco con sofrito y achiote.",
  st:["Derrite la mantequilla y sofríe la cebolla, el pimentón y el ajo 8 minutos. Añade el tomate y el achiote y cuece 5 minutos.",
      "Añade el vino y deja reducir 3 minutos.",
      "Añade el caldo y la leche de coco y hierve suave 10 minutos.",
      "Añade las almejas y los mejillones, tapa y cuece 4 minutos, hasta que se abran. Tira los que sigan cerrados.",
      "Añade el pescado, el calamar y los camarones y cuece 3 minutos.",
      "Añade la crema y la sal, calienta sin hervir y sirve con cilantro."],
  tp:["Los mariscos van en orden de cocción y al final: pasados quedan de caucho.",
      "Con arroz con coco y patacones."],
  v:"cazuela de mariscos colombiana receta"},
 en:{n:"Colombian Seafood Chowder (Cazuela de Mariscos)", b:"The creamy soup of Colombia's coast: shellfish and fish in coconut milk with a sofrito and annatto.",
  st:["Melt the butter and cook the onion, bell pepper and garlic for 8 minutes. Add the tomato and annatto and cook 5 minutes.",
      "Add the wine and reduce 3 minutes.",
      "Add the stock and coconut milk and simmer 10 minutes.",
      "Add the clams and mussels, cover and cook 4 minutes, until they open. Discard any that stay shut.",
      "Add the fish, squid and shrimp and cook 3 minutes.",
      "Add the cream and salt, heat without boiling and serve with cilantro."],
  tp:["The seafood goes in by cooking time and at the end: overcooked, it turns rubbery.",
      "Serve with coconut rice and patacones."],
  v:"cazuela de mariscos recipe"}},

{id:"sobrebarriga", c:"Colombia", r:"latin-america", m:"main", t:180, s:6,
 i:[[1.2,"kg","beef","protein","sobrebarriga de res","beef flank","en una pieza","in one piece"],
    [2,"l","water","liquid","agua","water"],
    [4,"","scallion","aromatic","tallos de cebolla larga","green onion stalks"],
    [4,"clove","garlic","aromatic","ajo","garlic"],
    [2,"leaf","herb","aromatic","hojas de laurel","bay leaves"],
    [3,"sprig","herb","aromatic","tomillo","thyme"],
    [2,"tsp","salt","salt","sal","salt"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [4,"","tomato","sauce","tomates","tomatoes","picados","chopped"],
    [0.5,"tsp","spice","aromatic","comino molido","ground cumin"]],
 es:{n:"Sobrebarriga en salsa", b:"Falda de res cocida despacio con cebolla larga y tomillo hasta ablandarse, luego dorada y bañada en salsa criolla.",
  st:["Cuece la carne con el agua, la cebolla larga, 2 dientes de ajo, el laurel, el tomillo y la sal 2 horas a fuego bajo, hasta que esté tierna.",
      "Saca la carne y guarda 250 ml del líquido.",
      "Dora la carne en el aceite 4 minutos por lado. Sácala.",
      "En la misma grasa, sofríe la cebolla y 2 dientes de ajo picados 5 minutos. Añade el tomate y el comino y cuece 10 minutos.",
      "Añade el líquido guardado y la carne, y cuece 10 minutos, bañándola. Corta en tajadas contra la fibra."],
  tp:["Corta contra la fibra: a favor, queda en hilos duros.",
      "Con papas saladas, arroz y aguacate."],
  v:"sobrebarriga en salsa receta"},
 en:{n:"Braised Flank Steak (Sobrebarriga)", b:"Beef flank simmered slowly with green onion and thyme until tender, then browned and bathed in a Creole tomato sauce.",
  st:["Simmer the beef with the water, green onion, 2 garlic cloves, bay, thyme and salt for 2 hours on low, until tender.",
      "Lift out the beef and keep 250 ml of the liquid.",
      "Brown the beef in the oil for 4 minutes per side. Remove.",
      "In the same fat, cook the onion and 2 chopped garlic cloves for 5 minutes. Add the tomato and cumin and cook 10 minutes.",
      "Add the reserved liquid and the beef and cook 10 minutes, basting. Slice against the grain."],
  tp:["Slice against the grain: with it, the beef turns into tough strings.",
      "Serve with salted potatoes, rice and avocado."],
  v:"sobrebarriga recipe"}}
];
