module.exports = [
{id:"tamales-tolimenses", c:"Colombia", r:"latin-america", m:"main", t:300, s:10,
 i:[[500,"g","masa","structure","harina de maíz precocida","pre-cooked corn flour"],
    [200,"g","rice","structure","arroz","rice","cocido a medias","parboiled"],
    [1.2,"l","stock","liquid","caldo de gallina","chicken stock"],
    [100,"g","lard","fat","manteca de cerdo","lard"],
    [2,"tsp","salt","salt","sal","salt"],
    [1,"tsp","achiote","aromatic","color (achiote en polvo)","ground annatto (color)"],
    [600,"g","pork","protein","costilla de cerdo","pork ribs","en trozos","in pieces"],
    [600,"g","chicken","protein","pollo","chicken","en presas","in pieces"],
    [300,"g","porkbelly","protein","tocino de cerdo","pork belly","en trozos","in pieces"],
    [150,"g","legume","structure","arvejas","peas"],
    [3,"","potato","structure","papas","potatoes","en rodajas","sliced"],
    [2,"","veg","structure","zanahorias","carrots","en rodajas","sliced"],
    [3,"","egg","protein","huevos duros","hard-boiled eggs","en rodajas","sliced"],
    [4,"","scallion","aromatic","tallos de cebolla larga","long green onion stalks","picados","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","molido","crushed"],
    [1,"tsp","spice","aromatic","comino","cumin"],
    [10,"","veg","structure","hojas de plátano","banana leaves","soasadas","softened over the flame"]],
 es:{n:"Tamales tolimenses", b:"Tamales grandes de masa de maíz y arroz con cerdo, pollo, tocino, huevo y verduras, envueltos en hoja de plátano. El desayuno de domingo del Tolima.",
  st:["Adoba el cerdo, el pollo y el tocino con la cebolla, el ajo, el comino y 1 cucharadita de sal toda la noche.",
      "Mezcla la harina, el arroz, el caldo, la manteca, el color y el resto de la sal hasta tener una masa suave. Añade las arvejas.",
      "En cada par de hojas pon 4 cucharadas de masa, un trozo de cada carne, una rodaja de papa, zanahoria y huevo, y cubre con más masa.",
      "Cierra en paquete cuadrado y ata con pita.",
      "Cuece en una olla grande con agua hirviendo 3 horas y media."],
  tp:["Las hojas deben pasarse por la llama o por agua caliente para que no se rompan.",
      "Se sirven con chocolate caliente y arepa."],
  v:"tamales tolimenses receta"},
 en:{n:"Tamales Tolimenses", b:"Large tamales of corn and rice dough with pork, chicken, pork belly, egg and vegetables, wrapped in banana leaf. Sunday breakfast in Tolima.",
  st:["Season the pork, chicken and pork belly with the onion, garlic, cumin and 1 teaspoon of salt overnight.",
      "Mix the flour, rice, stock, lard, annatto and the rest of the salt to a soft dough. Add the peas.",
      "On each pair of leaves put 4 tablespoons of dough, a piece of each meat, a slice of potato, carrot and egg, and cover with more dough.",
      "Close into a square parcel and tie with string.",
      "Boil in a large pot of water for 3 and a half hours."],
  tp:["Pass the leaves over a flame or through hot water so they don't tear.",
      "Served with hot chocolate and arepa."],
  v:"tamales tolimenses recipe"}},

{id:"arepa-boyacense", c:"Colombia", r:"latin-america", m:"bread", t:40, s:8,
 i:[[300,"g","corn","structure","maíz tierno desgranado","fresh corn kernels"],
    [200,"g","masa","structure","harina de maíz precocida","pre-cooked corn flour"],
    [60,"g","butter","fat","mantequilla","butter"],
    [80,"g","sugar","sweet","azúcar","sugar"],
    [100,"ml","milk","liquid","leche","milk"],
    [1,"tsp","salt","salt","sal","salt"],
    [250,"g","queso","protein","queso campesino o doble crema","fresh farmer's cheese","en lonchas","sliced"]],
 es:{n:"Arepa boyacense", b:"Arepa dulce de maíz tierno rellena de queso que se funde. De Boyacá, para el desayuno.",
  st:["Licúa el maíz con la leche hasta tener una pasta.",
      "Mezcla con la harina, la mantequilla, el azúcar y la sal hasta tener una masa suave.",
      "Haz 16 bolitas y aplánalas en discos de 1 cm.",
      "Pon queso sobre 8 discos, cubre con los otros y sella los bordes.",
      "Ásalas en un sartén con un poco de mantequilla 5 minutos por lado a fuego bajo, hasta que estén doradas."],
  tp:["El fuego bajo deja que el queso se funda sin quemar la arepa.",
      "Si la masa se agrieta, añade un poco de leche."],
  v:"arepa boyacense receta"},
 en:{n:"Arepa Boyacense (Sweet Corn Arepa with Cheese)", b:"A sweet fresh-corn arepa filled with melting cheese. From Boyacá, for breakfast.",
  st:["Blend the corn with the milk to a paste.",
      "Mix with the flour, butter, sugar and salt to a soft dough.",
      "Make 16 balls and flatten into 1 cm discs.",
      "Put cheese on 8 discs, cover with the others and seal the edges.",
      "Cook in a frying pan with a little butter for 5 minutes a side on low, until golden."],
  tp:["Low heat lets the cheese melt without burning the arepa.",
      "If the dough cracks, add a little milk."],
  v:"arepa boyacense recipe"}},

{id:"pan-de-yuca", c:"Colombia", r:"latin-america", m:"bread", t:35, s:12, o:220,
 i:[[150,"g","cassavastarch","structure","almidón de yuca","cassava starch"],
    [300,"g","queso","protein","queso costeño o feta suave","costeño or mild feta cheese","rallado","grated"],
    [1,"","egg","binder","huevo","egg"],
    [1,"tsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [2,"tbsp","milk","liquid","leche","milk"]],
 es:{n:"Pan de yuca", b:"Panecillos en forma de herradura de almidón de yuca y queso. Crujientes por fuera y elásticos por dentro, del Valle del Cauca.",
  st:["Mezcla el almidón, el queso y el polvo de hornear.",
      "Añade el huevo y la leche y amasa hasta tener una masa lisa.",
      "Forma 12 cilindros y curvalos en herradura.",
      "Colócalos en una bandeja con papel.",
      "Hornea a 220 °C durante 15 minutos, hasta que estén dorados."],
  tp:["Cómelos recién hechos; al enfriar se endurecen.",
      "Si la masa se pega, añade un poco de almidón."],
  v:"pan de yuca colombiano receta"},
 en:{n:"Pan de Yuca (Colombian Cassava Cheese Bread)", b:"Horseshoe rolls of cassava starch and cheese. Crisp outside and chewy within, from the Cauca Valley.",
  st:["Mix the starch, cheese and baking powder.",
      "Add the egg and milk and knead to a smooth dough.",
      "Shape 12 ropes and curve them into horseshoes.",
      "Place on a lined tray.",
      "Bake at 220 °C for 15 minutes, until golden."],
  tp:["Eat them fresh; they harden as they cool.",
      "If the dough is sticky, add a little starch."],
  v:"pan de yuca recipe"}},

{id:"almojabanas", c:"Colombia", r:"latin-america", m:"bread", t:40, s:12, o:200,
 i:[[250,"g","masa","structure","harina de maíz precocida","pre-cooked corn flour"],
    [400,"g","queso","protein","cuajada o queso fresco","fresh curd cheese","desmenuzado","crumbled"],
    [2,"","egg","binder","huevos","eggs"],
    [30,"g","butter","fat","mantequilla derretida","melted butter"],
    [1,"tsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [1,"tbsp","sugar","sweet","azúcar","sugar"],
    [100,"ml","milk","liquid","leche","milk"]],
 es:{n:"Almojábanas", b:"Panecillos redondos de cuajada y maíz, esponjosos y suaves. Se toman con chocolate en Bogotá y Boyacá.",
  st:["Aplasta la cuajada con un tenedor hasta que quede fina.",
      "Mezcla con la harina, el polvo de hornear y el azúcar.",
      "Añade los huevos, la mantequilla y la leche poco a poco hasta tener una masa suave.",
      "Forma 12 bolas y colócalas en una bandeja con papel.",
      "Hornea a 200 °C durante 20 minutos, hasta que estén doradas."],
  tp:["La cuajada debe estar escurrida o la masa queda aguada.",
      "Sírvelas tibias."],
  v:"almojábanas receta colombiana"},
 en:{n:"Almojábanas (Colombian Curd Cheese Rolls)", b:"Round rolls of fresh curd and corn, fluffy and soft. Eaten with hot chocolate in Bogotá and Boyacá.",
  st:["Mash the curd with a fork until fine.",
      "Mix with the flour, baking powder and sugar.",
      "Add the eggs, butter and milk gradually to a soft dough.",
      "Shape 12 balls and set on a lined tray.",
      "Bake at 200 °C for 20 minutes, until golden."],
  tp:["The curd must be well drained or the dough goes watery.",
      "Serve them warm."],
  v:"almojabanas recipe"}},

{id:"arroz-con-pollo-colombiano", c:"Colombia", r:"latin-america", m:"main", t:60, s:6,
 i:[[800,"g","chicken","protein","pechugas y muslos de pollo","chicken breasts and thighs"],
    [1.5,"l","water","liquid","agua","water"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [4,"","scallion","aromatic","tallos de cebolla larga","long green onion stalks","picados","chopped"],
    [2,"","tomato","sauce","tomates","tomatoes","picados","chopped"],
    [1,"","bellpepper","aromatic","pimentón rojo","red bell pepper","picado","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"tsp","achiote","aromatic","color (achiote en polvo)","ground annatto (color)"],
    [400,"g","rice","structure","arroz","rice"],
    [2,"","veg","structure","zanahorias","carrots","en dados","diced"],
    [150,"g","legume","structure","arvejas","peas"],
    [150,"g","veg","structure","habichuelas (judías verdes)","green beans","en trozos","in pieces"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Arroz con pollo colombiano", b:"Arroz amarillo con pollo desmechado y verduras. Plato de cumpleaños y reuniones en Colombia.",
  st:["Cuece el pollo en el agua con 1 cucharadita de sal 25 minutos. Desmecha el pollo y guarda 900 ml del caldo.",
      "Sofríe la cebolla, el tomate, el pimentón, el ajo y el color en el aceite 8 minutos.",
      "Añade el arroz, las verduras y el pollo y mezcla 2 minutos.",
      "Añade el caldo reservado y el resto de la sal. Cuece destapado hasta que el líquido baje al nivel del arroz.",
      "Tapa y cuece 20 minutos a fuego bajo."],
  tp:["Se sirve con papas a la francesa, ensalada y maduro.",
      "Si se seca antes de tiempo, añade un poco de caldo caliente."],
  v:"arroz con pollo colombiano receta"},
 en:{n:"Colombian Arroz con Pollo", b:"Yellow rice with shredded chicken and vegetables. The birthday and gathering dish in Colombia.",
  st:["Simmer the chicken in the water with 1 teaspoon of salt for 25 minutes. Shred and keep 900 ml of the broth.",
      "Cook the green onion, tomato, pepper, garlic and annatto in the oil for 8 minutes.",
      "Add the rice, vegetables and chicken and stir 2 minutes.",
      "Add the reserved broth and the rest of the salt. Cook uncovered until the liquid drops to the rice.",
      "Cover and cook 20 minutes on low."],
  tp:["It's served with chips, salad and fried ripe plantain.",
      "If it dries too soon, add a little hot broth."],
  v:"colombian chicken and rice recipe"}},

{id:"cuchuco-de-trigo", c:"Colombia", r:"latin-america", m:"soup", t:120, s:8,
 i:[[250,"g","bulgur","structure","trigo partido (cuchuco)","cracked wheat (cuchuco)","remojado 2 horas","soaked 2 hours"],
    [500,"g","pork","protein","espinazo o costilla de cerdo","pork backbone or ribs"],
    [3,"l","water","liquid","agua","water"],
    [4,"","scallion","aromatic","tallos de cebolla larga","long green onion stalks","picados","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [500,"g","potato","structure","papas","potatoes","en trozos","in chunks"],
    [150,"g","legume","structure","habas frescas","fresh fava beans"],
    [150,"g","legume","structure","arvejas","peas"],
    [200,"g","veg","structure","repollo","cabbage","en tiras","shredded"],
    [1,"handful","herb","garnish","cilantro","cilantro","picado","chopped"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Cuchuco de trigo con espinazo", b:"Sopa espesa de trigo partido con espinazo de cerdo, papa, habas y repollo. De Boyacá y Cundinamarca.",
  st:["Cuece el espinazo en el agua con la cebolla, el ajo y la sal 45 minutos.",
      "Añade el trigo escurrido y cuece 30 minutos, removiendo a menudo.",
      "Añade las papas, las habas y las arvejas y cuece 20 minutos.",
      "Añade el repollo y cuece 10 minutos más.",
      "Termina con el cilantro."],
  tp:["Remueve después de añadir el trigo: se asienta y se pega.",
      "Debe quedar espeso, casi como un guiso."],
  v:"cuchuco de trigo con espinazo"},
 en:{n:"Cuchuco de Trigo (Cracked Wheat and Pork Soup)", b:"A thick cracked-wheat soup with pork backbone, potato, fava beans and cabbage. From Boyacá and Cundinamarca.",
  st:["Simmer the pork in the water with the green onion, garlic and salt for 45 minutes.",
      "Add the drained wheat and cook 30 minutes, stirring often.",
      "Add the potatoes, fava beans and peas and cook 20 minutes.",
      "Add the cabbage and cook 10 minutes more.",
      "Finish with the cilantro."],
  tp:["Stir after adding the wheat: it settles and sticks.",
      "It should be thick, almost like a stew."],
  v:"cuchuco de trigo recipe"}},

{id:"merengon", c:"Colombia", r:"latin-america", m:"sweet", t:180, s:8, o:100,
 i:[[4,"","eggwhite","aerate","claras de huevo","egg whites"],
    [220,"g","sugar","sweet","azúcar","sugar"],
    [1,"tsp","citrus","acid","jugo de limón","lime juice"],
    [300,"ml","cream","enrich","crema de leche para batir","whipping cream"],
    [2,"tbsp","sugar","sweet","azúcar (segunda parte)","sugar (second amount)"],
    [400,"g","fruit","structure","fresas y guanábana","strawberries and soursop","en trozos","in pieces"]],
 es:{n:"Merengón", b:"Discos de merengue seco con crema batida y fruta, fresas o guanábana. Postre de carretera en Bogotá.",
  st:["Bate las claras con el limón a punto de nieve. Añade 220 g de azúcar poco a poco y bate hasta que brillen.",
      "Extiende en dos discos de 22 cm sobre papel de horno.",
      "Hornea a 100 °C durante 2 horas y deja enfriar dentro del horno apagado.",
      "Bate la crema con 2 cucharadas de azúcar.",
      "Arma alternando merengue, crema y fruta. Sirve en la hora siguiente."],
  tp:["Arma justo antes de servir: la crema ablanda el merengue.",
      "Un día seco ayuda a que el merengue quede crujiente."],
  v:"merengón colombiano receta"},
 en:{n:"Merengón (Colombian Meringue Cake)", b:"Crisp meringue discs with whipped cream and fruit, strawberries or soursop. A roadside dessert near Bogotá.",
  st:["Whisk the whites with the lime to stiff peaks. Add 220 g of sugar gradually and whisk until glossy.",
      "Spread into two 22 cm discs on baking paper.",
      "Bake at 100 °C for 2 hours and cool in the switched-off oven.",
      "Whip the cream with 2 tablespoons of sugar.",
      "Layer meringue, cream and fruit. Serve within the hour."],
  tp:["Assemble just before serving: the cream softens the meringue.",
      "A dry day helps the meringue stay crisp."],
  v:"merengon recipe"}},

{id:"avena-colombiana", c:"Colombia", r:"latin-america", m:"drink", t:20, s:6,
 i:[[100,"g","oats","structure","hojuelas de avena","rolled oats"],
    [1,"l","milk","liquid","leche","milk"],
    [500,"ml","water","liquid","agua","water"],
    [120,"g","sugar","sweet","azúcar","sugar"],
    [2,"","spice","aromatic","ramas de canela","cinnamon sticks"],
    [4,"","spice","aromatic","clavos de olor","whole cloves"]],
 es:{n:"Avena colombiana", b:"Bebida fría y espesa de avena cocida en leche con canela. Se vende en panaderías con pandebono.",
  st:["Cuece la avena en el agua con la canela y los clavos 10 minutos.",
      "Añade la leche y el azúcar y cuece 5 minutos más.",
      "Retira las especias y deja enfriar.",
      "Licúa hasta que esté lisa.",
      "Refrigera y sirve muy fría."],
  tp:["Espesa mucho en la nevera; aligera con leche fría.",
      "Una pizca de canela molida encima queda bien."],
  v:"avena colombiana receta"},
 en:{n:"Avena Colombiana (Cold Oat Drink)", b:"A thick cold drink of oats cooked in milk with cinnamon. Sold in bakeries with pandebono.",
  st:["Cook the oats in the water with the cinnamon and cloves for 10 minutes.",
      "Add the milk and sugar and cook 5 minutes more.",
      "Remove the spices and let cool.",
      "Blend until smooth.",
      "Refrigerate and serve very cold."],
  tp:["It thickens a lot in the fridge; loosen with cold milk.",
      "A pinch of ground cinnamon on top suits it."],
  v:"colombian oat drink recipe"}},

{id:"carne-en-polvo", c:"Colombia", r:"latin-america", m:"main", t:60, s:4,
 i:[[500,"g","beef","protein","carne de res magra","lean beef"],
    [1,"l","water","liquid","agua","water"],
    [1,"tsp","salt","salt","sal","salt"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [3,"","scallion","aromatic","tallos de cebolla larga","long green onion stalks","picados","chopped"],
    [2,"","tomato","sauce","tomates","tomatoes","picados","chopped"],
    [1,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [0.5,"tsp","spice","aromatic","comino","cumin"]],
 es:{n:"Carne en polvo", b:"Carne cocida, molida fina y dorada con hogao. Parte de la bandeja paisa y de los desayunos antioqueños.",
  st:["Cuece la carne en el agua con la sal 40 minutos. Escúrrela y déjala enfriar.",
      "Pica la carne y muélela en el procesador hasta que parezca polvo.",
      "Sofríe la cebolla, el tomate, el ajo y el comino en el aceite 8 minutos.",
      "Añade la carne y cuece 5 minutos, removiendo, hasta que esté seca y suelta.",
      "Sirve con arroz, frijoles y arepa."],
  tp:["La carne debe quedar seca y suelta, no apelmazada.",
      "Guarda el agua de cocción para una sopa."],
  v:"carne en polvo paisa receta"},
 en:{n:"Carne en Polvo (Colombian Ground Beef)", b:"Boiled beef ground to a fine powder and fried with hogao. Part of the bandeja paisa and Antioquian breakfasts.",
  st:["Simmer the beef in the water with the salt for 40 minutes. Drain and cool.",
      "Chop the meat and grind in a food processor until it looks like powder.",
      "Cook the green onion, tomato, garlic and cumin in the oil for 8 minutes.",
      "Add the meat and cook 5 minutes, stirring, until dry and loose.",
      "Serve with rice, beans and arepa."],
  tp:["The meat should end up dry and loose, not clumped.",
      "Keep the cooking water for a soup."],
  v:"carne en polvo recipe"}}
];
