module.exports = [
{id:"lechona-casera", c:"Colombia", r:"latin-america", m:"main", t:300, s:8,
 i:[[2,"kg","porkbelly","protein","panceta de cerdo con piel en una pieza","skin-on pork belly, in one piece"],
    [1,"kg","pork","protein","paleta de cerdo","pork shoulder","en cubos","cubed"],
    [300,"g","legume","structure","arvejas amarillas secas","dried yellow peas","remojadas 12 horas","soaked 12 hours"],
    [200,"g","rice","structure","arroz","rice"],
    [6,"","scallion","aromatic","cebollas largas","spring onions","picadas","chopped"],
    [6,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [2,"tsp","spice","aromatic","comino","cumin"],
    [4,"tsp","salt","salt","sal","salt"]],
 es:{n:"Lechona casera", b:"La lechona tolimense en versión de horno casero: panceta crujiente rellena de cerdo, arvejas y arroz.",
  st:["Cuece las arvejas 40 minutos. Cuece el arroz a medias, 8 minutos. Escurre ambos.",
      "Mezcla la paleta con la cebolla, el ajo, el comino y 2 cucharaditas de sal. Añade las arvejas y el arroz.",
      "Extiende la panceta con la piel hacia abajo, sálala y cubre con el relleno. Enróllala y átala con cordel.",
      "Pon el rollo en una bandeja con la piel hacia arriba, sala la piel y hornea a 160 °C 3 horas.",
      "Sube a 230 °C los últimos 20 minutos para que la piel se infle y cruja."],
  tp:["Seca la piel con papel antes de hornear para que quede crujiente.",
      "Deja reposar 20 minutos antes de cortar."],
  v:"lechona tolimense casera"},
 en:{n:"Lechona (Colombian Stuffed Pork Roast)", b:"Tolima's lechona adapted for a home oven: crisp pork belly stuffed with pork, yellow peas and rice.",
  st:["Simmer the peas for 40 minutes. Par-cook the rice for 8 minutes. Drain both.",
      "Mix the shoulder with the spring onion, garlic, cumin and 2 teaspoons of salt. Add the peas and rice.",
      "Lay the belly skin side down, salt it and cover with the filling. Roll up and tie with string.",
      "Set the roll skin side up in a tray, salt the skin and roast at 160 °C for 3 hours.",
      "Raise to 230 °C for the last 20 minutes so the skin puffs and crackles."],
  tp:["Pat the skin dry before roasting so it crisps.",
      "Rest 20 minutes before slicing."],
  v:"colombian lechona"}},

{id:"envueltos-de-mazorca", c:"Colombia", r:"latin-america", m:"side", t:90, s:12,
 i:[[6,"","corn","structure","mazorcas tiernas","young corn cobs","desgranadas","kernels cut off"],
    [12,"","cornhusk","structure","hojas de mazorca frescas","fresh corn husks"],
    [60,"g","butter","fat","mantequilla derretida","melted butter"],
    [60,"g","sugar","sweet","azúcar","sugar"],
    [150,"g","queso","enrich","queso campesino rallado","grated fresh white cheese"],
    [0.5,"tsp","salt","salt","sal","salt"]],
 es:{n:"Envueltos de mazorca", b:"Masa de maíz tierno con queso, envuelta en su hoja y cocida al vapor. Acompañan el chocolate en el altiplano colombiano.",
  st:["Muele los granos de maíz hasta tener una masa gruesa.",
      "Mezcla con la mantequilla, el azúcar, el queso y la sal.",
      "Pon 2 cucharadas de masa en cada hoja y envuelve, doblando las puntas.",
      "Cuécelos al vapor 60 minutos, hasta que la masa esté firme."],
  tp:["Si la masa queda muy líquida, añade un poco de harina de maíz.",
      "Se recalientan en la sartén hasta que la hoja se tueste."],
  v:"envueltos de mazorca colombianos"},
 en:{n:"Envueltos de Mazorca (Colombian Sweet Corn Parcels)", b:"Young corn dough with cheese, wrapped in its husk and steamed. Eaten with hot chocolate in the Colombian highlands.",
  st:["Grind the corn kernels into a coarse dough.",
      "Mix with the butter, sugar, cheese and salt.",
      "Put 2 tablespoons of dough in each husk and wrap, folding the ends.",
      "Steam for 60 minutes, until the dough is firm."],
  tp:["If the dough is too runny, add a little cornmeal.",
      "Reheat them in a pan until the husk toasts."],
  v:"colombian envueltos"}},

{id:"cuajada-con-melao", c:"Colombia", r:"latin-america", m:"sweet", t:30, s:4,
 i:[[500,"g","queso","structure","cuajada fresca","fresh curd cheese","en rebanadas","sliced"],
    [250,"g","brownsugar","sweet","panela","panela (unrefined cane sugar)"],
    [200,"ml","water","liquid","agua","water"],
    [1,"piece","spice","aromatic","rama de canela","cinnamon stick"]],
 es:{n:"Cuajada con melao", b:"Cuajada fresca bañada en melao de panela con canela. El postre más sencillo y querido de Boyacá y Cundinamarca.",
  st:["Hierve la panela con el agua y la canela 15 minutos, hasta tener un melao espeso.",
      "Deja entibiar y retira la canela.",
      "Sirve la cuajada en rebanadas con el melao por encima."],
  tp:["El melao espesa al enfriar: no lo reduzcas de más.",
      "Sírvelo con la cuajada bien fría y el melao tibio."],
  v:"cuajada con melao"},
 en:{n:"Cuajada con Melao (Fresh Curd with Cane Syrup)", b:"Fresh curd cheese drenched in panela syrup with cinnamon. The simplest, best-loved dessert of Boyacá and Cundinamarca.",
  st:["Boil the panela with the water and cinnamon for 15 minutes, into a thick syrup.",
      "Let it cool slightly and remove the cinnamon.",
      "Serve the curd in slices with the syrup poured over."],
  tp:["The syrup thickens as it cools: don't over-reduce it.",
      "Serve the curd well chilled and the syrup warm."],
  v:"colombian curd cane syrup"}},

{id:"masato", c:"Colombia", r:"latin-america", m:"drink", t:60, s:8,
 i:[[250,"g","rice","structure","arroz","rice"],
    [2.5,"l","water","liquid","agua","water"],
    [250,"g","sugar","sweet","azúcar","sugar"],
    [2,"piece","spice","aromatic","ramas de canela","cinnamon sticks"],
    [6,"piece","spice","aromatic","clavos de olor","cloves"]],
 es:{n:"Masato de arroz", b:"Bebida de arroz dulce y ligeramente fermentada con canela y clavo. Se toma en Bogotá con almojábanas.",
  st:["Remoja el arroz 8 horas y escúrrelo.",
      "Cuécelo en 1 l de agua con la canela y el clavo 30 minutos, hasta que esté muy blando.",
      "Licúa con el resto del agua y cuela. Añade el azúcar.",
      "Deja reposar tapado a temperatura ambiente 2 días para que fermente un poco.",
      "Refrigera y sirve frío."],
  tp:["Pruébalo cada día: debe quedar ligeramente ácido y espumoso.",
      "Una vez frío, se conserva 4 días en la nevera."],
  v:"masato de arroz colombiano"},
 en:{n:"Masato (Colombian Fermented Rice Drink)", b:"A sweet, lightly fermented rice drink with cinnamon and clove. Drunk in Bogotá with almojábanas.",
  st:["Soak the rice 8 hours and drain.",
      "Simmer it in 1 l of the water with the cinnamon and cloves for 30 minutes, until very soft.",
      "Blend with the rest of the water and strain. Add the sugar.",
      "Leave covered at room temperature for 2 days to ferment slightly.",
      "Chill and serve cold."],
  tp:["Taste it each day: it should be slightly tangy and fizzy.",
      "Once chilled, it keeps 4 days in the fridge."],
  v:"colombian masato"}},

{id:"agua-de-panela", c:"Colombia", r:"latin-america", m:"drink", t:15, s:4,
 i:[[200,"g","brownsugar","sweet","panela","panela (unrefined cane sugar)"],
    [1,"l","water","liquid","agua","water"],
    [2,"","citrus","acid","limones","limes"]],
 es:{n:"Agua de panela", b:"Panela disuelta en agua, caliente con limón o fría. La bebida de todos los días en Colombia.",
  st:["Hierve el agua con la panela 10 minutos, hasta que se disuelva.",
      "Sirve caliente con unas gotas de limón.",
      "Para tomarla fría, deja enfriar y sirve con hielo y limón."],
  tp:["Caliente es remedio para el resfriado.",
      "Fría con limón se llama limonada de panela."],
  v:"agua de panela"},
 en:{n:"Agua de Panela (Hot or Iced Cane Sugar Drink)", b:"Panela dissolved in water, hot with lime or iced. Colombia's everyday drink.",
  st:["Boil the water with the panela for 10 minutes, until dissolved.",
      "Serve hot with a squeeze of lime.",
      "To drink it cold, let it cool and serve over ice with lime."],
  tp:["Hot, it's a home remedy for colds.",
      "Iced with lime, it's called panela limeade."],
  v:"colombian agua de panela"}},

{id:"sopa-de-arroz", c:"Colombia", r:"latin-america", m:"soup", t:50, s:6,
 i:[[500,"g","beef","protein","costilla de res","beef short ribs"],
    [2,"l","water","liquid","agua","water"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [3,"","scallion","aromatic","cebollas largas","spring onions","picadas","chopped"],
    [2,"","tomato","aromatic","tomates","tomatoes","picados","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [100,"g","rice","structure","arroz","rice"],
    [3,"","potato","structure","papas","potatoes","en cubos","cubed"],
    [1,"","veg","structure","zanahoria","carrot","en dados","diced"],
    [100,"g","legume","structure","arvejas","green peas"],
    [1,"handful","herb","garnish","cilantro","coriander","picado","chopped"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Sopa de arroz", b:"Sopa de costilla con arroz, papa y verduras. El primer plato del corrientazo colombiano.",
  st:["Cuece la costilla en el agua con la sal 60 minutos.",
      "Sofríe la cebolla, el tomate y el ajo en el aceite 8 minutos y añádelo al caldo.",
      "Añade el arroz, la papa y la zanahoria y cuece 18 minutos.",
      "Añade las arvejas y cuece 5 minutos más.",
      "Termina con el cilantro."],
  tp:["Añade agua si el arroz absorbe demasiado caldo.",
      "En olla a presión la costilla tarda 25 minutos."],
  v:"sopa de arroz colombiana"},
 en:{n:"Sopa de Arroz (Colombian Rice Soup)", b:"Short rib soup with rice, potato and vegetables. The first course of Colombia's set lunch.",
  st:["Simmer the ribs in the water with the salt for 60 minutes.",
      "Cook the spring onion, tomato and garlic in the oil for 8 minutes and add to the broth.",
      "Add the rice, potato and carrot and cook 18 minutes.",
      "Add the peas and cook 5 minutes more.",
      "Finish with the coriander."],
  tp:["Add water if the rice soaks up too much broth.",
      "In a pressure cooker the ribs take 25 minutes."],
  v:"colombian rice soup"}},

{id:"empanadas-de-pipian", c:"Colombia", r:"latin-america", m:"snack", t:90, s:20,
 i:[[500,"g","potato","structure","papa colorada","red potatoes"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [3,"","scallion","aromatic","cebollas largas","spring onions","picadas","chopped"],
    [2,"","tomato","aromatic","tomates","tomatoes","picados","chopped"],
    [1,"tsp","achiote","aromatic","achiote molido","ground annatto"],
    [80,"g","peanut","structure","maní tostado","roasted peanuts","molido","ground"],
    [2,"tsp","salt","salt","sal","salt"],
    [400,"g","masa","structure","harina de maíz precocida","precooked cornmeal"],
    [500,"ml","water","liquid","agua","water"],
    [750,"ml","oil","fat","aceite para freír","oil for frying"]],
 es:{n:"Empanadas de pipián", b:"Empanaditas de maíz rellenas de papa guisada con maní y achiote. Orgullo de Popayán.",
  st:["Cuece la papa 20 minutos, pélala y aplástala en trozos.",
      "Sofríe la cebolla, el tomate y el achiote en el aceite 8 minutos. Añade la papa, el maní y 1 cucharadita de sal.",
      "Amasa la harina con el agua y el resto de la sal. Deja reposar 10 minutos.",
      "Forma discos finos, rellena, dobla y sella con un vaso.",
      "Fríe a 180 °C 4 minutos, hasta que estén doradas."],
  tp:["Sírvelas recién fritas.",
      "Aplana la masa entre dos plásticos para que quede fina."],
  v:"empanadas de pipián payanesas"},
 en:{n:"Empanadas de Pipián (Potato Peanut Empanadas)", b:"Small corn empanadas filled with potato stewed with peanut and annatto. The pride of Popayán.",
  st:["Boil the potatoes 20 minutes, peel and crush roughly.",
      "Cook the spring onion, tomato and annatto in the oil for 8 minutes. Add the potato, peanuts and 1 teaspoon of salt.",
      "Knead the cornmeal with the water and the rest of the salt. Rest 10 minutes.",
      "Shape thin discs, fill, fold and seal with a glass.",
      "Fry at 180 °C for 4 minutes, until golden."],
  tp:["Serve them straight from the fryer.",
      "Flatten the dough between two sheets of plastic so it's thin."],
  v:"colombian pipian empanadas"}},

{id:"maduro-con-bocadillo", c:"Colombia", r:"latin-america", m:"side", t:45, s:4,
 i:[[4,"","plantain","structure","plátanos muy maduros","very ripe plantains"],
    [20,"g","butter","fat","mantequilla","butter"],
    [150,"g","guavapaste","sweet","bocadillo de guayaba","guava paste","en tiras","in strips"],
    [150,"g","queso","enrich","queso campesino o mozzarella","fresh white cheese or mozzarella","en tiras","in strips"]],
 es:{n:"Maduro con bocadillo y queso", b:"Plátano maduro asado, abierto y relleno de guayaba y queso que se derriten. Acompañante dulce y salado colombiano.",
  st:["Unta los plátanos con piel con la mantequilla y hornéalos a 200 °C 30 minutos, hasta que la piel se ponga negra.",
      "Ábrelos a lo largo sin llegar al fondo.",
      "Rellena con el bocadillo y el queso.",
      "Hornea 8 minutos más, hasta que el queso se derrita."],
  tp:["Cuanto más negra la piel, más dulce el plátano.",
      "También se hacen en la parrilla, envueltos en aluminio."],
  v:"maduro con bocadillo y queso"},
 en:{n:"Baked Plantain with Guava and Cheese", b:"Ripe plantain roasted, split and stuffed with melting guava paste and cheese. A sweet-salty Colombian side.",
  st:["Rub the plantains in their skins with the butter and bake at 200 °C for 30 minutes, until the skins turn black.",
      "Slit them lengthways without cutting through.",
      "Fill with the guava paste and cheese.",
      "Bake 8 minutes more, until the cheese melts."],
  tp:["The blacker the skin, the sweeter the plantain.",
      "They also work on the grill, wrapped in foil."],
  v:"plantain guava cheese colombian"}},

{id:"arroz-con-camarones-co", c:"Colombia", r:"latin-america", m:"main", t:45, s:4,
 i:[[3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","pimentón rojo","red bell pepper","picado","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"","tomato","aromatic","tomates","tomatoes","picados","chopped"],
    [1,"tsp","achiote","aromatic","achiote molido","ground annatto"],
    [350,"g","rice","structure","arroz","rice"],
    [800,"ml","water","liquid","agua","water"],
    [400,"g","shrimp","protein","camarones pelados","peeled prawns"],
    [2,"tsp","salt","salt","sal","salt"],
    [1,"handful","herb","garnish","cilantro","coriander","picado","chopped"]],
 es:{n:"Arroz con camarones", b:"Arroz rojizo de achiote con camarones. Plato de la costa del Caribe colombiano.",
  st:["Sofríe la cebolla, el pimentón y el ajo en el aceite 6 minutos. Añade el tomate y el achiote y cocina 5 minutos.",
      "Añade el arroz y remueve 2 minutos.",
      "Añade el agua y la sal y cuece destapado hasta que se seque la superficie.",
      "Pon los camarones encima, tapa y cuece 15 minutos a fuego bajo.",
      "Mezcla y termina con el cilantro."],
  tp:["Hierve las cáscaras de los camarones en el agua para un arroz más sabroso.",
      "Sírvelo recién hecho."],
  v:"arroz con camarones costeño"},
 en:{n:"Colombian Prawn Rice", b:"Reddish annatto rice with prawns. A dish from Colombia's Caribbean coast.",
  st:["Cook the onion, pepper and garlic in the oil for 6 minutes. Add the tomato and annatto and cook 5 minutes.",
      "Add the rice and stir 2 minutes.",
      "Add the water and salt and cook uncovered until the surface dries.",
      "Lay the prawns on top, cover and cook 15 minutes on low.",
      "Stir and finish with the coriander."],
  tp:["Boil the prawn shells in the water for a tastier rice.",
      "Serve it freshly made."],
  v:"colombian prawn rice"}},

{id:"higado-encebollado", c:"Colombia", r:"latin-america", m:"main", t:30, s:4,
 i:[[600,"g","beef","protein","hígado de res","beef liver","en filetes","in slices"],
    [250,"ml","milk","liquid","leche (para remojar)","milk (for soaking)"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [2,"","onion","aromatic","cebollas","onions","en aros","in rings"],
    [2,"","tomato","aromatic","tomates","tomatoes","picados","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"tsp","spice","aromatic","comino","cumin"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Hígado encebollado", b:"Hígado de res tierno con mucha cebolla y tomate. Almuerzo económico y nutritivo en Colombia.",
  st:["Remoja el hígado en la leche 30 minutos. Escurre y seca.",
      "Dora el hígado en el aceite a fuego fuerte 2 minutos por lado. Sácalo.",
      "Sofríe la cebolla, el ajo y el comino 6 minutos. Añade el tomate y cocina 5 minutos.",
      "Vuelve a poner el hígado, sala y cocina 3 minutos."],
  tp:["No lo cocines de más: el hígado se endurece.",
      "Sala al final para que quede tierno."],
  v:"hígado encebollado colombiano"},
 en:{n:"Hígado Encebollado (Liver and Onions)", b:"Tender beef liver with lots of onion and tomato. A cheap, nourishing lunch in Colombia.",
  st:["Soak the liver in the milk for 30 minutes. Drain and pat dry.",
      "Brown the liver in the oil over high heat for 2 minutes per side. Remove.",
      "Cook the onion, garlic and cumin for 6 minutes. Add the tomato and cook 5 minutes.",
      "Return the liver, salt and cook 3 minutes."],
  tp:["Don't overcook it: liver toughens.",
      "Salt at the end so it stays tender."],
  v:"colombian liver and onions"}}
];
