module.exports = [
{id:"mote-de-queso", c:"Colombia", r:"latin-america", m:"soup", t:50, s:6,
 i:[[1,"kg","veg","structure","ñame","white yam","pelado y en trozos","peeled, in chunks"],
    [1.5,"l","water","liquid","agua","water"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [4,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [300,"g","queso","enrich","queso costeño","queso costeño (salty white cheese)","en cubos","cubed"],
    [1,"handful","herb","aromatic","cilantro","coriander","picado","chopped"],
    [1,"tsp","salt","salt","sal","salt"],
    [2,"","citrus","acid","limones","limes"]],
 es:{n:"Mote de queso", b:"Sopa espesa de ñame con queso costeño que se derrite a medias. La sopa de la costa del Caribe colombiano.",
  st:["Cuece el ñame en el agua 25 minutos, hasta que empiece a deshacerse.",
      "Sofríe la cebolla y el ajo en el aceite 5 minutos y añádelos a la olla.",
      "Aplasta parte del ñame para espesar.",
      "Añade el queso y cuece 3 minutos, hasta que se ablande sin derretirse del todo.",
      "Termina con el cilantro, prueba de sal y sirve con limón."],
  tp:["Añade la sal al final: el queso costeño es muy salado.",
      "Remueve a menudo: el ñame se pega al fondo."],
  v:"mote de queso costeño"},
 en:{n:"Mote de Queso (Colombian Yam and Cheese Soup)", b:"A thick yam soup with salty cheese that half melts. The soup of Colombia's Caribbean coast.",
  st:["Simmer the yam in the water for 25 minutes, until it starts to fall apart.",
      "Cook the onion and garlic in the oil for 5 minutes and add to the pot.",
      "Crush some of the yam to thicken.",
      "Add the cheese and cook 3 minutes, until soft but not fully melted.",
      "Finish with the coriander, taste for salt and serve with lime."],
  tp:["Salt at the end: queso costeño is very salty.",
      "Stir often: yam sticks to the bottom."],
  v:"colombian mote de queso"}},

{id:"papas-chorreadas", c:"Colombia", r:"latin-america", m:"side", t:40, s:4,
 i:[[800,"g","potato","structure","papas pequeñas","small potatoes"],
    [2,"tbsp","butter","fat","mantequilla","butter"],
    [3,"","scallion","aromatic","cebollas largas","spring onions","picadas","chopped"],
    [3,"","tomato","aromatic","tomates","tomatoes","picados","chopped"],
    [150,"ml","cream","enrich","crema de leche","single cream"],
    [150,"g","mozzarella","enrich","queso doble crema o mozzarella","Colombian melting cheese or mozzarella","rallado","grated"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"pinch","spice","aromatic","comino","cumin"]],
 es:{n:"Papas chorreadas", b:"Papas cocidas bañadas en un hogao cremoso con queso derretido. Acompañante clásico del altiplano colombiano.",
  st:["Cuece las papas con piel en agua con sal 20 minutos.",
      "Derrite la mantequilla y sofríe la cebolla larga 5 minutos.",
      "Añade el tomate y el comino y cocina 8 minutos.",
      "Añade la crema y el queso y remueve hasta que se funda.",
      "Baña las papas con la salsa."],
  tp:["La papa sabanera o criolla es la ideal.",
      "Baña las papas justo antes de servir."],
  v:"papas chorreadas colombianas"},
 en:{n:"Papas Chorreadas (Colombian Potatoes in Cheese Sauce)", b:"Boiled potatoes smothered in a creamy tomato and spring onion sauce with melted cheese. A classic side from the Colombian highlands.",
  st:["Boil the potatoes in their skins in salted water for 20 minutes.",
      "Melt the butter and cook the spring onion for 5 minutes.",
      "Add the tomato and cumin and cook 8 minutes.",
      "Add the cream and cheese and stir until melted.",
      "Pour the sauce over the potatoes."],
  tp:["Waxy yellow potatoes work best.",
      "Sauce the potatoes just before serving."],
  v:"colombian papas chorreadas"}},

{id:"sopa-de-mondongo", c:"Colombia", r:"latin-america", m:"soup", t:180, s:8,
 i:[[1,"kg","beef","protein","mondongo (callo de res) limpio","cleaned beef tripe","en tiras","in strips"],
    [500,"g","pork","protein","carne de cerdo","pork shoulder","en cubos","cubed"],
    [3,"","citrus","acid","limones","limes"],
    [3,"l","water","liquid","agua","water"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [4,"","scallion","aromatic","cebollas largas","spring onions","picadas","chopped"],
    [2,"","tomato","aromatic","tomates","tomatoes","picados","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"tsp","spice","aromatic","comino","cumin"],
    [500,"g","potato","structure","papas","potatoes","en cubos","cubed"],
    [300,"g","cassava","structure","yuca","cassava","en trozos","in chunks"],
    [2,"","veg","structure","zanahorias","carrots","en dados","diced"],
    [1,"handful","herb","garnish","cilantro","coriander","picado","chopped"],
    [3,"tsp","salt","salt","sal","salt"]],
 es:{n:"Sopa de mondongo", b:"Sopa contundente de callo y cerdo con papa y yuca. Almuerzo de fonda en Antioquia y todo Colombia.",
  st:["Frota el mondongo con el limón, enjuágalo y cuécelo en el agua 2 horas, hasta que esté tierno.",
      "Añade el cerdo y cuece 30 minutos.",
      "Sofríe la cebolla, el tomate, el ajo y el comino en el aceite 8 minutos y añádelo a la olla.",
      "Añade la papa, la yuca, la zanahoria y la sal y cuece 25 minutos.",
      "Termina con el cilantro."],
  tp:["En olla a presión el mondongo tarda 45 minutos.",
      "Sírvela con arroz blanco."],
  v:"sopa de mondongo colombiana"},
 en:{n:"Sopa de Mondongo (Colombian Tripe Soup)", b:"A hearty soup of tripe and pork with potato and cassava. Diner lunch in Antioquia and across Colombia.",
  st:["Rub the tripe with the lime, rinse and simmer it in the water for 2 hours, until tender.",
      "Add the pork and cook 30 minutes.",
      "Cook the spring onion, tomato, garlic and cumin in the oil for 8 minutes and add to the pot.",
      "Add the potato, cassava, carrot and salt and cook 25 minutes.",
      "Finish with the coriander."],
  tp:["In a pressure cooker the tripe takes 45 minutes.",
      "Serve with white rice."],
  v:"colombian mondongo soup"}},

{id:"postre-de-natas", c:"Colombia", r:"latin-america", m:"sweet", t:180, s:6,
 i:[[2,"l","milk","liquid","leche entera","whole milk"],
    [4,"","eggyolk","set","yemas de huevo","egg yolks"],
    [200,"g","sugar","sweet","azúcar","sugar"],
    [1,"piece","spice","aromatic","rama de canela","cinnamon stick"],
    [60,"g","driedfruit","garnish","uvas pasas","raisins"],
    [1,"tsp","vanilla","aromatic","esencia de vainilla","vanilla extract"]],
 es:{n:"Postre de natas", b:"Postre bogotano hecho con las natas que se forman al hervir la leche, en almíbar de leche con pasas.",
  st:["Hierve la leche y déjala enfriar sin tocar 30 minutos. Retira la nata que se forma y guárdala. Repite 3 veces.",
      "Cuece la leche restante con el azúcar y la canela 60 minutos, removiendo, hasta que se reduzca a la mitad.",
      "Bate las yemas con un poco de la leche reducida y añádelas a la olla. Cuece 5 minutos sin hervir.",
      "Añade las natas, las pasas y la vainilla y cuece 10 minutos a fuego bajo.",
      "Sirve frío."],
  tp:["Usa leche entera sin homogeneizar si la encuentras: forma más nata.",
      "No hiervas tras añadir las yemas o se cortan."],
  v:"postre de natas bogotano"},
 en:{n:"Postre de Natas (Colombian Milk Skin Pudding)", b:"A Bogotá dessert made from the skins that form on boiled milk, in a milk syrup with raisins.",
  st:["Boil the milk and leave it undisturbed for 30 minutes. Lift off the skin that forms and set aside. Repeat 3 times.",
      "Cook the remaining milk with the sugar and cinnamon for 60 minutes, stirring, until reduced by half.",
      "Whisk the yolks with a little of the reduced milk and stir into the pan. Cook 5 minutes without boiling.",
      "Add the skins, raisins and vanilla and cook 10 minutes on low.",
      "Serve cold."],
  tp:["Use unhomogenised whole milk if you can find it: it forms more skin.",
      "Don't boil once the yolks are in or they'll curdle."],
  v:"colombian postre de natas"}},

{id:"limonada-de-coco", c:"Colombia", r:"latin-america", m:"drink", t:10, s:4,
 i:[[400,"ml","coconutmilk","liquid","leche de coco","coconut milk"],
    [4,"","citrus","acid","limones","limes","exprimidos","juiced"],
    [60,"g","sugar","sweet","azúcar","sugar"],
    [500,"g","ice","liquid","hielo","ice"]],
 es:{n:"Limonada de coco", b:"Limonada frappé con leche de coco, cremosa y ácida. La bebida de Cartagena en las tardes de calor.",
  st:["Pon el hielo en la licuadora.",
      "Añade la leche de coco, el jugo de limón y el azúcar.",
      "Licúa 1 minuto, hasta que quede espumosa y granizada.",
      "Sirve de inmediato."],
  tp:["No licúes la cáscara del limón: amarga.",
      "Sirve enseguida, antes de que se derrita."],
  v:"limonada de coco cartagenera"},
 en:{n:"Limonada de Coco (Frozen Coconut Limeade)", b:"Frozen limeade blended with coconut milk, creamy and tart. Cartagena's drink on hot afternoons.",
  st:["Put the ice in the blender.",
      "Add the coconut milk, lime juice and sugar.",
      "Blend 1 minute, until frothy and slushy.",
      "Serve at once."],
  tp:["Don't blend the lime peel: it turns bitter.",
      "Serve straight away, before it melts."],
  v:"colombian coconut limeade"}},

{id:"corviche", c:"Ecuador", r:"latin-america", m:"snack", t:60, s:10,
 i:[[4,"","plantain","structure","plátanos verdes","green plantains"],
    [100,"g","peanutbutter","enrich","pasta de maní sin azúcar","unsweetened peanut butter"],
    [1,"tsp","achiote","aromatic","achiote molido","ground annatto"],
    [1,"tsp","salt","salt","sal","salt"],
    [300,"g","whitefish","protein","albacora o pescado blanco","white fish"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"handful","herb","aromatic","cilantro","coriander","picado","chopped"],
    [1,"tbsp","oil","fat","aceite (para el relleno)","oil (for the filling)"],
    [750,"ml","oil","fat","aceite para freír","oil for frying"]],
 es:{n:"Corviche", b:"Masa de verde rallado con maní, rellena de pescado y frita. Antojo de la costa de Manabí.",
  st:["Cuece el pescado en agua 8 minutos y desmenúzalo. Sofríe la cebolla en el aceite del relleno 5 minutos y mézclala con el pescado y el cilantro.",
      "Ralla los plátanos crudos y mézclalos con la pasta de maní, el achiote y la sal hasta tener una masa.",
      "Toma porciones de masa, aplánalas, rellena con el pescado y forma torpedos.",
      "Fríe a 175 °C 5 minutos, hasta que estén dorados."],
  tp:["Unta aceite en las manos para trabajar la masa.",
      "El pescado original es albacora, pero sirve cualquier pescado firme."],
  v:"corviche manabita"},
 en:{n:"Corviche (Plantain Peanut Fish Fritters)", b:"Grated green plantain dough with peanut, stuffed with fish and fried. A snack from Manabí on Ecuador's coast.",
  st:["Poach the fish in water for 8 minutes and flake it. Cook the onion in the filling oil for 5 minutes and mix with the fish and coriander.",
      "Grate the raw plantains and mix with the peanut butter, annatto and salt into a dough.",
      "Take portions of dough, flatten, fill with the fish and shape into torpedoes.",
      "Fry at 175 °C for 5 minutes, until golden."],
  tp:["Oil your hands to work the dough.",
      "The original uses albacore, but any firm fish works."],
  v:"ecuadorian corviche"}},

{id:"morocho", c:"Ecuador", r:"latin-america", m:"drink", t:150, s:8,
 i:[[250,"g","hominy","structure","maíz morocho partido","cracked white corn"],
    [1.5,"l","water","liquid","agua","water"],
    [1,"l","milk","liquid","leche","milk"],
    [150,"g","sugar","sweet","azúcar","sugar"],
    [2,"piece","spice","aromatic","ramas de canela","cinnamon sticks"],
    [4,"piece","spice","aromatic","clavos de olor","cloves"],
    [60,"g","driedfruit","garnish","pasas","raisins"],
    [1,"tsp","spice","garnish","canela molida","ground cinnamon"]],
 es:{n:"Morocho", b:"Bebida espesa y caliente de maíz blanco con leche, canela y pasas. Se toma con empanadas en las tardes de Quito.",
  st:["Remoja el morocho 12 horas y escúrrelo.",
      "Cuécelo en el agua con la canela y el clavo 90 minutos, removiendo, hasta que esté suave.",
      "Añade la leche y el azúcar y cuece 20 minutos más, removiendo.",
      "Añade las pasas los últimos 5 minutos. Sirve caliente con canela molida."],
  tp:["Si espesa demasiado, añade leche caliente.",
      "Remueve a menudo: se pega al fondo."],
  v:"morocho ecuatoriano"},
 en:{n:"Morocho (Ecuadorian Corn Milk Drink)", b:"A thick, hot drink of white corn with milk, cinnamon and raisins. An afternoon warmer in Quito.",
  st:["Soak the corn 12 hours and drain.",
      "Simmer it in the water with the cinnamon and cloves for 90 minutes, stirring, until soft.",
      "Add the milk and sugar and cook 20 minutes more, stirring.",
      "Add the raisins for the last 5 minutes. Serve hot with ground cinnamon."],
  tp:["If it gets too thick, add hot milk.",
      "Stir often: it catches on the bottom."],
  v:"ecuadorian morocho drink"}},

{id:"pristinos", c:"Ecuador", r:"latin-america", m:"sweet", t:60, s:20,
 i:[[500,"g","apflour","structure","harina de trigo","plain flour"],
    [1,"tsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [100,"g","butter","fat","mantequilla","butter"],
    [2,"","egg","binder","huevos","eggs"],
    [100,"ml","water","liquid","agua","water"],
    [0.5,"tsp","salt","salt","sal","salt"],
    [1,"l","oil","fat","aceite para freír","oil for frying"],
    [300,"g","brownsugar","sweet","panela","panela (unrefined cane sugar)"],
    [250,"ml","water","liquid","agua (segunda parte)","water (second part)"],
    [2,"piece","spice","aromatic","ramas de canela","cinnamon sticks"],
    [4,"piece","spice","aromatic","clavos de olor","cloves"]],
 es:{n:"Pristiños", b:"Aros de masa frita bañados en miel de panela con canela y clavo. Dulce navideño de Ecuador.",
  st:["Mezcla la harina, el polvo de hornear y la sal. Añade la mantequilla, los huevos y el agua y amasa 5 minutos. Reposa 20 minutos.",
      "Estira a 3 mm, corta tiras de 3 x 15 cm y une las puntas en aro.",
      "Fríe a 175 °C 2 minutos por lado, hasta que se inflen y doren.",
      "Hierve la panela con el agua de la segunda parte, la canela y el clavo 10 minutos, hasta que espese.",
      "Sirve los pristiños bañados en la miel tibia."],
  tp:["Pincha la masa antes de freír si quieres que se inflen menos.",
      "La miel se espesa al enfriar: caliéntala antes de servir."],
  v:"pristiños ecuatorianos"},
 en:{n:"Pristiños (Ecuadorian Fried Pastry Rings)", b:"Fried pastry rings drenched in cane-sugar syrup with cinnamon and clove. An Ecuadorian Christmas sweet.",
  st:["Mix the flour, baking powder and salt. Add the butter, eggs and water and knead 5 minutes. Rest 20 minutes.",
      "Roll to 3 mm, cut 3 x 15 cm strips and join the ends into rings.",
      "Fry at 175 °C for 2 minutes per side, until puffed and golden.",
      "Boil the panela with the second part of the water, the cinnamon and cloves for 10 minutes, until thick.",
      "Serve the rings drenched in the warm syrup."],
  tp:["Prick the dough before frying if you want less puff.",
      "The syrup thickens as it cools: warm it before serving."],
  v:"ecuadorian pristinos"}},

{id:"menestra-de-lentejas", c:"Ecuador", r:"latin-america", m:"side", t:50, s:6,
 i:[[400,"g","legume","structure","lentejas","lentils"],
    [1.2,"l","water","liquid","agua","water"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla colorada","red onion","picada","chopped"],
    [1,"","bellpepper","aromatic","pimiento verde","green bell pepper","picado","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"","tomato","aromatic","tomate","tomato","picado","chopped"],
    [1,"tsp","spice","aromatic","comino","cumin"],
    [1,"tsp","achiote","aromatic","achiote molido","ground annatto"],
    [1,"handful","herb","garnish","cilantro","coriander","picado","chopped"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Menestra de lentejas", b:"Lentejas espesas con refrito de achiote y comino. Acompaña el arroz y la carne asada en todo Ecuador.",
  st:["Cuece las lentejas en el agua 25 minutos.",
      "Sofríe la cebolla, el pimiento, el ajo y el tomate en el aceite 8 minutos. Añade el comino y el achiote.",
      "Añade el refrito a las lentejas con la sal y cuece 15 minutos, hasta que espesen.",
      "Termina con el cilantro."],
  tp:["Debe quedar espesa, no caldosa: machaca algunas lentejas.",
      "Sírvela con arroz blanco, como en los puestos de Guayaquil."],
  v:"menestra de lentejas ecuatoriana"},
 en:{n:"Menestra de Lentejas (Ecuadorian Lentil Stew)", b:"Thick lentils with an annatto and cumin base. Served with rice and grilled meat across Ecuador.",
  st:["Simmer the lentils in the water for 25 minutes.",
      "Cook the onion, pepper, garlic and tomato in the oil for 8 minutes. Add the cumin and annatto.",
      "Stir this into the lentils with the salt and cook 15 minutes, until thick.",
      "Finish with the coriander."],
  tp:["It should be thick, not soupy: crush some lentils.",
      "Serve with white rice, as Guayaquil's street stalls do."],
  v:"ecuadorian lentil menestra"}},

{id:"seco-de-pollo-ec", c:"Ecuador", r:"latin-america", m:"main", t:70, s:6,
 i:[[1.2,"kg","chicken","protein","pollo en presas","chicken pieces"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla colorada","red onion","picada","chopped"],
    [1,"","bellpepper","aromatic","pimiento rojo","red bell pepper","picado","chopped"],
    [4,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [3,"","tomato","liquid","tomates","tomatoes","licuados","blended"],
    [1,"tsp","spice","aromatic","comino","cumin"],
    [1,"tsp","achiote","aromatic","achiote molido","ground annatto"],
    [250,"ml","fruit","liquid","jugo de naranjilla","naranjilla (lulo) juice"],
    [100,"g","brownsugar","sweet","panela rallada","grated panela"],
    [1,"bunch","herb","aromatic","cilantro","coriander","picado","chopped"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Seco de pollo", b:"Pollo guisado en tomate, naranjilla y panela con mucho cilantro. Almuerzo de todos los días en Ecuador.",
  st:["Sala el pollo y dóralo en el aceite 8 minutos. Sácalo.",
      "Sofríe la cebolla, el pimiento y el ajo 6 minutos. Añade el comino y el achiote.",
      "Añade el tomate, el jugo de naranjilla, la panela y la mitad del cilantro. Cocina 5 minutos.",
      "Añade el pollo, tapa y cuece 40 minutos, hasta que la salsa espese.",
      "Termina con el resto del cilantro."],
  tp:["Si no hay naranjilla, usa jugo de lulo o de naranja agria.",
      "Sírvelo con arroz blanco."],
  v:"seco de pollo ecuatoriano"},
 en:{n:"Seco de Pollo (Ecuadorian Chicken Stew)", b:"Chicken stewed in tomato, naranjilla and cane sugar with lots of coriander. Everyday lunch in Ecuador.",
  st:["Salt the chicken and brown it in the oil for 8 minutes. Remove.",
      "Cook the onion, pepper and garlic for 6 minutes. Add the cumin and annatto.",
      "Add the tomato, naranjilla juice, panela and half the coriander. Cook 5 minutes.",
      "Add the chicken, cover and simmer 40 minutes, until the sauce thickens.",
      "Finish with the rest of the coriander."],
  tp:["No naranjilla? Use lulo or sour orange juice.",
      "Serve with white rice."],
  v:"ecuadorian seco de pollo"}}
];
