module.exports = [
{id:"boliche", c:"Cuba", r:"latin-america", m:"main", t:210, s:6,
 i:[[1.5,"kg","beef","protein","boliche (redondo de res)","beef eye of round"],
    [2,"","chorizo","protein","chorizos españoles curados","cured Spanish chorizos","en tiras","in strips"],
    [6,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [3,"","citrus","acid","naranjas agrias","sour oranges","en jugo","juiced"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [4,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","ají pimiento verde","green pepper","picado","chopped"],
    [250,"ml","winewhite","liquid","vino seco","dry cooking wine"],
    [500,"ml","water","liquid","agua","water"],
    [6,"","potato","structure","papas","potatoes","en mitades","halved"],
    [3,"tsp","salt","salt","sal","salt"]],
 es:{n:"Boliche mechado", b:"Redondo de res relleno de chorizo y cocido lentamente en su salsa con papas. Plato de domingo cubano.",
  st:["Abre un túnel a lo largo de la carne con un cuchillo largo y rellénalo con el chorizo.",
      "Mezcla el ajo, el jugo de naranja, el comino, el orégano y 2 cucharaditas de sal y marina la carne 4 horas.",
      "Dora la carne en el aceite por todos lados 12 minutos. Añade la cebolla y el pimiento y cocina 5 minutos.",
      "Añade la marinada, el vino y el agua, tapa y cuece a fuego bajo 2 horas y media.",
      "Añade las papas y el resto de la sal y cocina 30 minutos más. Corta en rodajas y sirve con la salsa."],
  tp:["En olla a presión tarda 50 minutos antes de añadir las papas.",
      "Se corta mejor tibio."],
  v:"boliche cubano"},
 en:{n:"Boliche (Cuban Chorizo-Stuffed Pot Roast)", b:"Eye of round stuffed with chorizo and slow-cooked in its sauce with potatoes. A Cuban Sunday dish.",
  st:["Push a long knife through the length of the beef to make a tunnel and stuff it with the chorizo.",
      "Mix the garlic, orange juice, cumin, oregano and 2 teaspoons of salt and marinate the beef 4 hours.",
      "Brown the beef in the oil on all sides for 12 minutes. Add the onion and pepper and cook 5 minutes.",
      "Add the marinade, wine and water, cover and simmer on low heat for 2½ hours.",
      "Add the potatoes and remaining salt and cook 30 minutes more. Slice and serve with the sauce."],
  tp:["In a pressure cooker it takes 50 minutes before the potatoes go in.",
      "It slices best when warm."],
  v:"cuban boliche"}},

{id:"tasajo", c:"Cuba", r:"latin-america", m:"main", t:150, s:4,
 i:[[600,"g","driedmeat","protein","tasajo (carne seca salada)","salted dried beef"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","en rodajas finas","thinly sliced"],
    [4,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"","bellpepper","aromatic","ají pimiento","pepper","en tiras","in strips"],
    [200,"ml","tomato","sauce","puré de tomate","tomato passata"],
    [1,"","citrus","acid","naranja agria","sour orange"],
    [0.5,"tsp","spice","aromatic","comino molido","ground cumin"]],
 es:{n:"Tasajo a la cubana", b:"Carne seca desalada, deshilachada y guisada con cebolla, ajo y tomate. Plato de campo cubano.",
  st:["Remoja el tasajo en agua fría 24 horas, cambiando el agua 3 veces.",
      "Hiérvelo en agua nueva 90 minutos, hasta que esté tierno. Escúrrelo y deshiláchalo.",
      "Sofríe la cebolla, el ajo y el pimiento en el aceite 8 minutos. Añade el comino, el tomate y el tasajo.",
      "Cocina 15 minutos a fuego bajo y termina con el jugo de naranja agria."],
  tp:["No lleva sal: el tasajo ya la tiene. Pruébalo antes de servir.",
      "Sírvelo con arroz blanco."],
  v:"tasajo cubano"},
 en:{n:"Tasajo (Cuban Salted Dried Beef)", b:"Desalted dried beef, shredded and stewed with onion, garlic and tomato. A Cuban country dish.",
  st:["Soak the dried beef in cold water for 24 hours, changing the water 3 times.",
      "Boil it in fresh water for 90 minutes, until tender. Drain and shred.",
      "Cook the onion, garlic and pepper in the oil for 8 minutes. Add the cumin, tomato and shredded beef.",
      "Cook 15 minutes on low heat and finish with the sour orange juice."],
  tp:["No salt needed: the beef already has it. Taste before serving.",
      "Serve with white rice."],
  v:"cuban tasajo"}},

{id:"harina-con-cangrejo", c:"Cuba", r:"latin-america", m:"main", t:45, s:4,
 i:[[200,"g","cornmeal","structure","harina de maíz amarilla","yellow cornmeal"],
    [1.2,"l","water","liquid","agua","water"],
    [400,"g","crab","protein","carne de cangrejo","crab meat"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"","bellpepper","aromatic","ají pimiento","pepper","picado","chopped"],
    [2,"tbsp","tomatopaste","sauce","pasta de tomate","tomato paste"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Harina con cangrejo", b:"Polenta cubana de maíz amarillo guisada con un sofrito de cangrejo. Plato humilde y sabroso de la costa.",
  st:["Sofríe la cebolla, el ajo y el pimiento en el aceite 6 minutos. Añade la pasta de tomate y el cangrejo y cocina 4 minutos.",
      "Añade el agua y la sal y lleva a hervor.",
      "Echa la harina en lluvia batiendo sin parar y cocina a fuego bajo 25 minutos, removiendo, hasta que espese y se despegue."],
  tp:["Debe quedar cremosa, como un puré suave.",
      "Si espesa demasiado, añade agua caliente."],
  v:"harina de maíz con cangrejo"},
 en:{n:"Harina con Cangrejo (Cuban Cornmeal with Crab)", b:"Cuban-style soft cornmeal cooked with a crab sofrito. A humble, flavourful coastal dish.",
  st:["Cook the onion, garlic and pepper in the oil for 6 minutes. Add the tomato paste and crab and cook 4 minutes.",
      "Add the water and salt and bring to the boil.",
      "Rain in the cornmeal, whisking constantly, and cook on low heat for 25 minutes, stirring, until thick and pulling from the pan."],
  tp:["It should be creamy, like soft mash.",
      "If it gets too thick, add hot water."],
  v:"cuban cornmeal with crab"}},

{id:"enchilado-de-camarones", c:"Cuba", r:"latin-america", m:"main", t:35, s:4,
 i:[[700,"g","shrimp","protein","camarones","prawns","pelados","peeled"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [4,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"","bellpepper","aromatic","ají pimiento","pepper","picado","chopped"],
    [250,"ml","tomato","sauce","puré de tomate","tomato passata"],
    [120,"ml","winewhite","liquid","vino seco","dry cooking wine"],
    [0.5,"tsp","spice","aromatic","comino molido","ground cumin"],
    [1,"","herb","aromatic","hoja de laurel","bay leaf"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Enchilado de camarones", b:"Camarones en salsa criolla de tomate, vino seco y ajo. A pesar del nombre, no pica.",
  st:["Sofríe la cebolla, el ajo y el pimiento en el aceite 8 minutos.",
      "Añade el tomate, el vino, el comino, el laurel y la sal y cuece 12 minutos.",
      "Añade los camarones y cocina 4 minutos, hasta que estén rosados."],
  tp:["No cocines de más los camarones o quedarán duros.",
      "Sírvelo con arroz blanco."],
  v:"enchilado cubano"},
 en:{n:"Enchilado de Camarones (Cuban Prawns in Creole Sauce)", b:"Prawns in a Creole sauce of tomato, dry wine and garlic. Despite the name, it isn't spicy.",
  st:["Cook the onion, garlic and pepper in the oil for 8 minutes.",
      "Add the tomato, wine, cumin, bay and salt and simmer 12 minutes.",
      "Add the prawns and cook 4 minutes, until pink."],
  tp:["Don't overcook the prawns or they'll turn tough.",
      "Serve with white rice."],
  v:"cuban shrimp enchilado"}},

{id:"bunuelos-cubanos", c:"Cuba", r:"latin-america", m:"sweet", t:75, s:6,
 i:[[400,"g","cassava","structure","yuca","cassava","pelada","peeled"],
    [300,"g","veg","structure","malanga","taro","pelada","peeled"],
    [1,"","egg","binder","huevo","egg"],
    [60,"g","apflour","structure","harina de trigo","plain flour"],
    [1,"pinch","salt","salt","sal","salt"],
    [500,"ml","oil","fat","aceite","oil","para freír","for frying"],
    [250,"g","sugar","sweet","azúcar","sugar"],
    [200,"ml","water","liquid","agua","water"],
    [1,"tsp","spice","aromatic","anís en grano y canela en rama","aniseed and cinnamon stick"],
    [1,"","citrus","aromatic","cáscara de limón","lime peel"]],
 es:{n:"Buñuelos cubanos", b:"Buñuelos en forma de ocho de yuca y malanga, bañados en almíbar de anís. Postre de Nochebuena.",
  st:["Hierve el azúcar, el agua, el anís, la canela y la cáscara de limón 10 minutos para hacer el almíbar.",
      "Hierve la yuca y la malanga 25 minutos, hasta que estén tiernas. Quita las fibras y hazlas puré.",
      "Mezcla con el huevo, la harina y la sal hasta tener una masa suave.",
      "Forma cordones y dóblalos en forma de ocho. Fríe en el aceite a 175 °C hasta dorar.",
      "Sírvelos bañados en el almíbar."],
  tp:["Mójate las manos para formarlos sin que se peguen.",
      "El almíbar se puede hacer un día antes."],
  v:"buñuelos de yuca y malanga"},
 en:{n:"Buñuelos Cubanos (Cassava Fritters in Anise Syrup)", b:"Figure-eight fritters of cassava and taro soaked in anise syrup. A Christmas Eve dessert.",
  st:["Boil the sugar, water, aniseed, cinnamon and lime peel for 10 minutes to make the syrup.",
      "Boil the cassava and taro for 25 minutes, until tender. Remove the fibres and mash.",
      "Mix with the egg, flour and salt to a soft dough.",
      "Roll into ropes and fold into figure eights. Fry in the oil at 175 °C until golden.",
      "Serve soaked in the syrup."],
  tp:["Wet your hands to shape them without sticking.",
      "The syrup can be made a day ahead."],
  v:"cuban cassava fritters"}},

{id:"tocinillo-del-cielo", c:"Cuba", r:"latin-america", m:"sweet", t:75, s:8,
 i:[[12,"","eggyolk","structure","yemas de huevo","egg yolks"],
    [400,"g","sugar","sweet","azúcar","sugar"],
    [200,"ml","water","liquid","agua","water"],
    [1,"","citrus","aromatic","cáscara de limón","lime peel"]],
 es:{n:"Tocinillo del cielo", b:"Flan intenso hecho solo con yemas y almíbar, sobre caramelo. Heredado de los conventos españoles.",
  st:["Derrite 100 g del azúcar en un molde hasta obtener un caramelo dorado y cubre el fondo.",
      "Hierve el resto del azúcar con el agua y la cáscara de limón 8 minutos, hasta punto de hebra. Retira la cáscara y deja entibiar.",
      "Bate las yemas suavemente y añade el almíbar tibio en hilo, sin dejar de mover. Cuela.",
      "Vierte en el molde, tapa con papel de aluminio y cuece a baño María a 160 °C 40 minutos.",
      "Enfría en la nevera 4 horas y desmolda."],
  tp:["El almíbar no debe estar caliente o cuajará las yemas.",
      "Las claras sobrantes sirven para merengue."],
  v:"tocinillo de cielo cubano"},
 en:{n:"Tocinillo del Cielo (Egg Yolk Caramel Custard)", b:"A rich custard made only with yolks and syrup, set over caramel. Inherited from Spanish convents.",
  st:["Melt 100 g of the sugar in a mould to a golden caramel and coat the base.",
      "Boil the remaining sugar with the water and lime peel for 8 minutes, to thread stage. Remove the peel and let it cool slightly.",
      "Beat the yolks gently and pour in the warm syrup in a thin stream, stirring. Strain.",
      "Pour into the mould, cover with foil and bake in a water bath at 160 °C for 40 minutes.",
      "Chill 4 hours and unmould."],
  tp:["The syrup mustn't be hot or it will scramble the yolks.",
      "Use the leftover whites for meringue."],
  v:"cuban tocinillo"}},

{id:"pastelitos-de-guayaba", c:"Cuba", r:"latin-america", m:"pastry", t:45, s:12,
 i:[[500,"g","puffpastry","structure","hojaldre","puff pastry"],
    [250,"g","guavapaste","sweet","pasta de guayaba","guava paste","en láminas","in slices"],
    [200,"g","creamcheese","enrich","queso crema","cream cheese"],
    [1,"","egg","glaze","huevo","egg","batido","beaten"],
    [3,"tbsp","sugar","sweet","azúcar","sugar"],
    [3,"tbsp","water","liquid","agua","water"]],
 es:{n:"Pastelitos de guayaba y queso", b:"Hojaldre relleno de pasta de guayaba y queso crema. Lo más pedido en las ventanitas de café cubanas.",
  st:["Calienta el horno a 200 °C. Corta el hojaldre en 24 cuadrados.",
      "Pon una lámina de guayaba y una cucharadita de queso crema sobre 12 cuadrados y cubre con los otros. Sella los bordes con un tenedor.",
      "Pinta con el huevo y hornea 20 minutos, hasta que estén dorados.",
      "Hierve el azúcar con el agua 2 minutos y pinta los pastelitos al salir del horno."],
  tp:["Mantén el hojaldre frío mientras armas para que suba bien.",
      "Son mejores tibios, el mismo día."],
  v:"pastelitos cubanos de guayaba"},
 en:{n:"Pastelitos de Guayaba (Guava and Cheese Pastries)", b:"Puff pastry filled with guava paste and cream cheese. The best seller at Cuban coffee windows.",
  st:["Heat the oven to 200 °C. Cut the pastry into 24 squares.",
      "Put a slice of guava and a teaspoon of cream cheese on 12 squares and cover with the others. Seal the edges with a fork.",
      "Brush with the egg and bake 20 minutes, until golden.",
      "Boil the sugar with the water for 2 minutes and brush the pastries as they come out."],
  tp:["Keep the pastry cold while you work so it rises well.",
      "They're best warm, the same day."],
  v:"cuban guava pastries"}},

{id:"medianoche", c:"Cuba", r:"latin-america", m:"main", t:20, s:4,
 i:[[4,"","enrichedbread","structure","panes de medianoche (pan dulce de huevo)","sweet egg bread rolls"],
    [300,"g","pork","protein","cerdo asado","roast pork","en lonchas","sliced"],
    [200,"g","ham","protein","jamón cocido","cooked ham","en lonchas","sliced"],
    [150,"g","cheese","protein","queso suizo","Swiss cheese","en lonchas","sliced"],
    [8,"slice","pickles","garnish","pepinillos en vinagre","dill pickles","en láminas","sliced"],
    [2,"tbsp","mustard","sauce","mostaza amarilla","yellow mustard"],
    [30,"g","butter","fat","mantequilla","butter","blanda","softened"]],
 es:{n:"Sándwich medianoche", b:"Primo del sándwich cubano en pan dulce de huevo, prensado y caliente. Se comía de madrugada al salir de los clubes.",
  st:["Abre los panes y úntalos con la mostaza.",
      "Arma con el cerdo, el jamón, el queso y los pepinillos.",
      "Unta el exterior con la mantequilla y prensa en una sartén caliente con un peso encima 3 minutos por lado, hasta que el queso se funda."],
  tp:["Una sartén pesada encima sustituye a la plancha de prensar.",
      "Córtalo en diagonal."],
  v:"medianoche cubano"},
 en:{n:"Medianoche (Cuban Midnight Sandwich)", b:"The Cuban sandwich's cousin on sweet egg bread, pressed and hot. Eaten in the small hours after the clubs.",
  st:["Split the rolls and spread with the mustard.",
      "Fill with the pork, ham, cheese and pickles.",
      "Butter the outsides and press in a hot pan with a weight on top, 3 minutes a side, until the cheese melts."],
  tp:["A heavy pan on top stands in for a sandwich press.",
      "Cut it on the diagonal."],
  v:"cuban medianoche"}}
];
