module.exports = [
{id:"arroz-con-pollo-cu", c:"Cuba", r:"caribbean", m:"main", t:75, s:6,
 i:[[1.2,"kg","chicken","protein","pollo en presas","chicken pieces"],
    [3,"","citrus","acid","naranjas agrias (o 2 naranjas y 1 limón)","sour oranges (or 2 oranges and 1 lime)","en jugo","juiced"],
    [4,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [2,"tsp","salt","salt","sal","salt"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","ají pimiento verde","green bell pepper","picado","chopped"],
    [200,"g","tomato","sauce","puré de tomate","tomato purée"],
    [1,"tsp","achiote","aromatic","bijol o achiote en polvo","bijol or ground annatto"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [1,"leaf","herb","aromatic","hoja de laurel","bay leaf"],
    [400,"g","rice","structure","arroz de grano medio","medium-grain rice"],
    [330,"ml","beer","liquid","cerveza clara","lager beer"],
    [500,"ml","stock","liquid","caldo de pollo","chicken stock"],
    [150,"g","legume","protein","petit pois","peas"],
    [1,"","bellpepper","garnish","pimiento rojo asado","roasted red pepper","en tiras","in strips"]],
 es:{n:"Arroz con pollo a la cubana", b:"Arroz amarillo y húmedo con pollo marinado en naranja agria, cerveza y sofrito. El plato de fiesta de la casa cubana.",
  st:["Marina el pollo con el jugo de naranja, el ajo y 1 cucharadita de sal al menos 1 hora.",
      "Dora el pollo en el aceite 8 minutos. Añade la cebolla y el ají y sofríe 5 minutos.",
      "Añade el puré de tomate, el bijol, el comino, el laurel y la marinada. Cuece 5 minutos.",
      "Añade el arroz, la cerveza, el caldo y el resto de la sal. Hierve, tapa y cuece a fuego bajo 25 minutos.",
      "Añade los petit pois, tapa y deja 5 minutos. Decora con el pimiento. Debe quedar húmedo, no seco."],
  tp:["El arroz a la cubana queda meloso; si lo quieres suelto, usa 100 ml menos de caldo.",
      "Sin cerveza, usa la misma cantidad de caldo."],
  v:"arroz con pollo cubano receta"},
 en:{n:"Cuban Arroz con Pollo", b:"Moist yellow rice with chicken marinated in sour orange, beer and sofrito. The party dish of a Cuban home.",
  st:["Marinate the chicken with the orange juice, garlic and 1 teaspoon of salt for at least 1 hour.",
      "Brown the chicken in the oil for 8 minutes. Add the onion and pepper and cook 5 minutes.",
      "Add the tomato purée, bijol, cumin, bay and the marinade. Cook 5 minutes.",
      "Add the rice, beer, stock and the rest of the salt. Bring to a boil, cover and cook on low for 25 minutes.",
      "Add the peas, cover and leave 5 minutes. Garnish with the pepper. It should be moist, not dry."],
  tp:["Cuban-style rice is soft and creamy; for separate grains, use 100 ml less stock.",
      "Without beer, use the same amount of stock."],
  v:"cuban arroz con pollo recipe"}},

{id:"picadillo-cubano", c:"Cuba", r:"caribbean", m:"main", t:40, s:4,
 i:[[600,"g","beef","protein","carne molida de res","ground beef"],
    [2,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","ají pimiento verde","green bell pepper","picado","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [200,"g","tomato","sauce","puré de tomate","tomato purée"],
    [80,"ml","winewhite","liquid","vino seco","dry white wine"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [60,"g","olives","umami","aceitunas verdes sin hueso","pitted green olives"],
    [40,"g","driedfruit","sweet","pasas","raisins"],
    [1,"tbsp","capers","umami","alcaparras","capers"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Picadillo a la habanera", b:"Carne molida con sofrito, aceitunas, pasas y alcaparras. Dulce, salado y ácido, con arroz blanco y plátano maduro.",
  st:["Sofríe la cebolla, el ají y el ajo en el aceite 8 minutos.",
      "Añade la carne y cuece 8 minutos, deshaciéndola, hasta que pierda el color rosado.",
      "Añade el puré de tomate, el vino, el comino, el orégano y la sal. Cuece 10 minutos.",
      "Añade las aceitunas, las pasas y las alcaparras y cuece 5 minutos más.",
      "Sirve con arroz blanco y maduros fritos."],
  tp:["El vino seco de cocina cubano es salado: si lo usas, quita sal.",
      "El vino se puede cambiar por la misma cantidad de agua con un chorrito de limón."],
  v:"picadillo cubano receta"},
 en:{n:"Cuban Picadillo", b:"Ground beef with sofrito, olives, raisins and capers. Sweet, salty and sharp, with white rice and sweet plantains.",
  st:["Cook the onion, pepper and garlic in the oil for 8 minutes.",
      "Add the beef and cook 8 minutes, breaking it up, until no longer pink.",
      "Add the tomato purée, wine, cumin, oregano and salt. Cook 10 minutes.",
      "Add the olives, raisins and capers and cook 5 minutes more.",
      "Serve with white rice and fried sweet plantains."],
  tp:["Cuban cooking wine is salted: if you use it, cut the salt.",
      "The wine can be replaced with the same amount of water with a squeeze of lime."],
  v:"cuban picadillo recipe"}},

{id:"frijoles-negros-cu", c:"Cuba", r:"caribbean", m:"side", t:150, s:8,
 i:[[500,"g","legume","protein","frijoles negros","black beans","remojados toda la noche","soaked overnight"],
    [2,"l","water","liquid","agua","water"],
    [2,"leaf","herb","aromatic","hojas de laurel","bay leaves"],
    [60,"ml","oliveoil","fat","aceite de oliva","olive oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","ají pimiento verde","green bell pepper","picado","chopped"],
    [4,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [2,"tbsp","winevinegar","acid","vinagre de vino","wine vinegar"],
    [1,"tsp","sugar","sweet","azúcar","sugar"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Frijoles negros cubanos", b:"Frijoles negros dormidos: espesos, con sofrito, comino, un toque de vinagre y azúcar. Mejor al día siguiente.",
  st:["Cuece los frijoles escurridos en el agua con el laurel 90 minutos, hasta que estén blandos.",
      "Sofríe la cebolla, el ají y el ajo en el aceite 10 minutos con el comino y el orégano.",
      "Aplasta 1 taza de frijoles con el sofrito y regrésalo todo a la olla.",
      "Añade el vinagre, el azúcar y la sal y cuece 30 minutos a fuego bajo, hasta que espesen.",
      "Deja reposar tapados. Son frijoles dormidos si se comen al día siguiente."],
  tp:["El chorrito de aceite de oliva crudo al servir es de rigor.",
      "Sin azúcar también quedan bien; el vinagre es lo que no puede faltar."],
  v:"frijoles negros cubanos receta"},
 en:{n:"Cuban Black Beans", b:"Black beans left to rest: thick, with sofrito, cumin, a touch of vinegar and sugar. Better the next day.",
  st:["Cook the drained beans in the water with the bay for 90 minutes, until soft.",
      "Cook the onion, pepper and garlic in the oil for 10 minutes with the cumin and oregano.",
      "Mash 1 cup of beans with the sofrito and return everything to the pot.",
      "Add the vinegar, sugar and salt and cook 30 minutes on low, until thick.",
      "Leave to rest covered. They're called sleeping beans if eaten the next day."],
  tp:["A splash of raw olive oil when serving is a must.",
      "They're good without the sugar too; the vinegar is what can't be skipped."],
  v:"cuban black beans recipe"}},

{id:"moros-y-cristianos", c:"Cuba", r:"caribbean", m:"side", t:60, s:6,
 i:[[250,"g","legume","protein","frijoles negros cocidos","cooked black beans"],
    [500,"ml","water","liquid","líquido de cocción de los frijoles","bean cooking liquid"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","ají pimiento verde","green bell pepper","picado","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [1,"leaf","herb","aromatic","hoja de laurel","bay leaf"],
    [300,"g","rice","structure","arroz de grano largo","long-grain rice","enjuagado","rinsed"],
    [1.5,"tsp","salt","salt","sal","salt"]],
 es:{n:"Moros y cristianos", b:"Arroz cocido junto con frijoles negros en su caldo oscuro, con sofrito y comino. Congrí, en el oriente de Cuba.",
  st:["Sofríe la cebolla, el ají y el ajo en el aceite 8 minutos con el comino y el orégano.",
      "Añade el arroz y revuelve 2 minutos.",
      "Añade los frijoles, su líquido, el laurel y la sal. Si no llega a 1 centímetro sobre el arroz, añade agua.",
      "Hierve hasta que el líquido baje al nivel del arroz. Tapa y cuece a fuego bajo 20 minutos.",
      "Deja 5 minutos tapado y suelta con tenedor."],
  tp:["El líquido de los frijoles es lo que tiñe el arroz: no lo cambies por agua.",
      "Con frijoles colorados se llama congrí oriental."],
  v:"moros y cristianos receta"},
 en:{n:"Moros y Cristianos (Cuban Black Beans and Rice)", b:"Rice cooked with black beans in their dark liquid, with sofrito and cumin. Called congrí in eastern Cuba.",
  st:["Cook the onion, pepper and garlic in the oil for 8 minutes with the cumin and oregano.",
      "Add the rice and stir 2 minutes.",
      "Add the beans, their liquid, the bay and salt. If it doesn't reach 1 centimetre above the rice, add water.",
      "Boil until the liquid drops to the level of the rice. Cover and cook on low for 20 minutes.",
      "Leave covered 5 minutes and fluff with a fork."],
  tp:["The bean liquid is what colours the rice: don't swap it for water.",
      "With red beans it's called congrí oriental."],
  v:"moros y cristianos recipe"}},

{id:"yuca-con-mojo", c:"Cuba", r:"caribbean", m:"side", t:45, s:6,
 i:[[1,"kg","cassava","structure","yuca","cassava","pelada, en trozos","peeled, in chunks"],
    [2,"tsp","salt","salt","sal","salt"],
    [100,"ml","oliveoil","fat","aceite de oliva","olive oil"],
    [8,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [120,"ml","citrus","acid","jugo de naranja agria (o mitad naranja y mitad limón)","sour orange juice (or half orange, half lime)"],
    [0.5,"","onion","aromatic","cebolla blanca","white onion","en aros finos","in thin rings"]],
 es:{n:"Yuca con mojo", b:"Yuca hervida bañada en mojo caliente de ajo, naranja agria y aceite de oliva. Imprescindible junto al lechón.",
  st:["Cuece la yuca en agua con 1 cucharadita de sal 30 minutos, hasta que esté blanda y se abra. Escurre y quita la fibra del centro.",
      "Machaca el ajo con el resto de la sal hasta hacer una pasta.",
      "Calienta el aceite a fuego medio y sofríe la cebolla y el ajo 1 minuto, sin dorar.",
      "Apaga, añade el jugo de naranja con cuidado (salpica) y vierte sobre la yuca caliente."],
  tp:["Echar agua fría a media cocción, como en Cuba, hace que la yuca se abra y quede suave.",
      "La yuca debe cocerse del todo: nunca se come cruda."],
  v:"yuca con mojo receta"},
 en:{n:"Yuca con Mojo (Cassava with Garlic Citrus Sauce)", b:"Boiled cassava drenched in hot mojo of garlic, sour orange and olive oil. A must beside roast pork.",
  st:["Boil the cassava in water with 1 teaspoon of salt for 30 minutes, until soft and split. Drain and remove the woody core.",
      "Mash the garlic with the rest of the salt into a paste.",
      "Heat the oil over medium heat and cook the onion and garlic for 1 minute, without browning.",
      "Turn off, add the orange juice carefully (it spatters) and pour over the hot cassava."],
  tp:["Adding cold water halfway through, the Cuban way, makes the cassava split and turn tender.",
      "Cassava must be fully cooked: never eat it raw."],
  v:"yuca con mojo recipe"}},

{id:"lechon-asado", c:"Cuba", r:"caribbean", m:"main", t:300, s:10, o:160,
 i:[[3,"kg","pork","protein","paleta de cerdo con hueso y piel","bone-in, skin-on pork shoulder"],
    [12,"clove","garlic","aromatic","ajo","garlic"],
    [1,"tbsp","salt","salt","sal","salt"],
    [2,"tsp","spice","aromatic","comino molido","ground cumin"],
    [2,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [1,"tsp","pepper","aromatic","pimienta negra","black pepper"],
    [350,"ml","citrus","acid","jugo de naranja agria (o 2 partes de naranja y 1 de limón)","sour orange juice (or 2 parts orange to 1 part lime)"],
    [2,"","onion","aromatic","cebollas","onions","en aros","in rings"]],
 es:{n:"Lechón asado", b:"Paleta de cerdo marinada en mojo de ajo y naranja agria toda la noche y asada lenta hasta deshacerse, con la piel crujiente.",
  st:["Machaca el ajo con la sal, el comino, el orégano y la pimienta. Mezcla con el jugo de naranja: es el mojo.",
      "Haz cortes profundos en la carne, sin cortar la piel. Mete mojo en los cortes y marina con la cebolla toda la noche.",
      "Calienta el horno a 160 °C. Pon el cerdo con la piel arriba sobre la cebolla y la marinada, tapa con aluminio.",
      "Asa 3 horas y media, bañando cada hora.",
      "Destapa, sube el horno a 230 °C y asa 30 minutos más, hasta que la piel cruja.",
      "Reposa 20 minutos, deshebra y sirve con los jugos, moros y yuca."],
  tp:["Seca bien la piel antes del último golpe de horno para que cruja.",
      "Guarda un poco de mojo sin usar para rociar al servir."],
  v:"lechon asado cubano receta"},
 en:{n:"Cuban Roast Pork (Lechón Asado)", b:"Pork shoulder marinated overnight in garlic and sour orange mojo and roasted slowly until it falls apart, with crackling skin.",
  st:["Mash the garlic with the salt, cumin, oregano and pepper. Mix with the orange juice: this is the mojo.",
      "Cut deep slits in the meat without cutting the skin. Push mojo into the slits and marinate with the onion overnight.",
      "Heat the oven to 160 °C. Set the pork skin-side up on the onion and marinade, cover with foil.",
      "Roast 3 and a half hours, basting every hour.",
      "Uncover, raise the oven to 230 °C and roast 30 minutes more, until the skin crackles.",
      "Rest 20 minutes, shred and serve with the juices, black beans and rice and cassava."],
  tp:["Pat the skin dry before the final blast so it crackles.",
      "Keep a little unused mojo to drizzle when serving."],
  v:"cuban lechon asado recipe"}},

{id:"sandwich-cubano", c:"Cuba", r:"caribbean", m:"main", t:20, s:4,
 i:[[1,"loaf","bread","structure","pan cubano (o baguette suave)","Cuban bread (or soft baguette)"],
    [400,"g","pork","protein","lechón asado","roast pork","en tajadas","sliced"],
    [200,"g","ham","protein","jamón cocido","cooked ham","en tajadas","sliced"],
    [200,"g","cheese","protein","queso suizo","Swiss cheese","en tajadas","sliced"],
    [8,"slice","pickles","umami","pepinillos en rodajas","sliced dill pickles"],
    [3,"tbsp","mustard","spread","mostaza amarilla","yellow mustard"],
    [30,"g","butter","fat","mantequilla","butter","suave","soft"]],
 es:{n:"Sándwich cubano", b:"Pan cubano con lechón, jamón, queso suizo, pepinillos y mostaza, prensado en plancha hasta crujir. Nació entre La Habana, Tampa y Miami.",
  st:["Corta el pan en 4 trozos y ábrelos a lo largo.",
      "Unta mostaza por dentro. Pon queso, jamón, lechón, pepinillos y otra capa de queso.",
      "Unta mantequilla por fuera.",
      "Prensa en una plancha o sartén con peso encima 4 minutos por lado, hasta que el pan cruja y el queso se funda.",
      "Corta en diagonal y sirve."],
  tp:["Sin prensa, pon una olla pesada encima del sándwich.",
      "Lleva exactamente esto: sin lechuga ni tomate."],
  v:"sandwich cubano receta"},
 en:{n:"Cuban Sandwich", b:"Cuban bread with roast pork, ham, Swiss cheese, pickles and mustard, pressed on a griddle until crisp. Born between Havana, Tampa and Miami.",
  st:["Cut the bread into 4 pieces and split them lengthwise.",
      "Spread mustard inside. Layer cheese, ham, pork, pickles and another layer of cheese.",
      "Butter the outside.",
      "Press on a griddle or in a pan with a weight on top for 4 minutes per side, until the bread is crisp and the cheese melts.",
      "Cut diagonally and serve."],
  tp:["No press? Put a heavy pot on top of the sandwich.",
      "It's exactly this: no lettuce or tomato."],
  v:"cuban sandwich recipe"}},

{id:"vaca-frita", c:"Cuba", r:"caribbean", m:"main", t:120, s:4,
 i:[[800,"g","beef","protein","falda de res","beef flank"],
    [2,"l","water","liquid","agua","water"],
    [2,"tsp","salt","salt","sal","salt"],
    [6,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [3,"","citrus","acid","limones","limes","en jugo","juiced"],
    [2,"","onion","aromatic","cebollas","onions","en aros finos","in thin rings"],
    [4,"tbsp","oil","fat","aceite","oil"]],
 es:{n:"Vaca frita", b:"Falda de res hervida, desmenuzada, marinada en ajo y limón y frita hasta que las hebras crujen, con mucha cebolla.",
  st:["Cuece la carne en el agua con 1 cucharadita de sal 90 minutos. Escurre y desmenuza en hebras.",
      "Mezcla la carne con el ajo, el limón y el resto de la sal. Deja 30 minutos.",
      "Calienta el aceite en un sartén grande a fuego fuerte. Fríe la cebolla 3 minutos.",
      "Añade la carne y aplástala contra el sartén. Déjala 5 minutos sin mover, hasta que se dore y cruja; voltea y repite.",
      "Sirve con arroz, frijoles negros y maduros."],
  tp:["Sartén muy caliente y sin llenarlo: si hay demasiada carne, se cuece en vez de freírse.",
      "Seca bien la carne antes de freír."],
  v:"vaca frita receta"},
 en:{n:"Vaca Frita (Cuban Crispy Beef)", b:"Beef flank simmered, shredded, marinated in garlic and lime and fried until the strands crisp, with lots of onion.",
  st:["Simmer the beef in the water with 1 teaspoon of salt for 90 minutes. Drain and shred into strands.",
      "Mix the beef with the garlic, lime and the rest of the salt. Leave 30 minutes.",
      "Heat the oil in a large pan over high heat. Fry the onion 3 minutes.",
      "Add the beef and press it into the pan. Leave 5 minutes without stirring, until browned and crisp; turn and repeat.",
      "Serve with rice, black beans and sweet plantains."],
  tp:["Very hot pan and don't crowd it: too much beef steams instead of frying.",
      "Pat the beef dry before frying."],
  v:"vaca frita recipe"}},

{id:"maduros", c:"Cuba", r:"caribbean", m:"side", t:15, s:4,
 i:[[3,"","plantain","sweet","plátanos maduros (con la cáscara casi negra)","ripe plantains (skins nearly black)","pelados","peeled"],
    [4,"tbsp","oil","fat","aceite","oil"],
    [0.25,"tsp","salt","salt","sal","salt"]],
 es:{n:"Plátanos maduros fritos", b:"Plátano maduro frito en rodajas diagonales hasta caramelizar por fuera y quedar cremoso por dentro.",
  st:["Corta los plátanos en rodajas diagonales de 1 centímetro.",
      "Calienta el aceite a fuego medio.",
      "Fríe 3 minutos por lado, hasta que estén caramelizados y oscuros en los bordes.",
      "Escurre y espolvorea la sal."],
  tp:["El plátano debe estar casi negro: amarillo no carameliza.",
      "Fuego medio: alto quema el azúcar natural antes de que se ablande."],
  v:"platanos maduros fritos"},
 en:{n:"Maduros (Fried Sweet Plantains)", b:"Ripe plantain fried in diagonal slices until caramelised outside and creamy inside.",
  st:["Cut the plantains into 1 centimetre diagonal slices.",
      "Heat the oil over medium heat.",
      "Fry 3 minutes per side, until caramelised and dark at the edges.",
      "Drain and sprinkle with the salt."],
  tp:["The plantain should be nearly black: yellow ones won't caramelise.",
      "Medium heat: high heat burns the natural sugar before it softens."],
  v:"fried sweet plantains"}},

{id:"flan-de-coco", c:"Cuba", r:"caribbean", m:"sweet", t:90, s:8, o:170,
 i:[[150,"g","sugar","caramel","azúcar","sugar","para el caramelo","for the caramel"],
    [395,"g","condensedmilk","sweet","leche condensada","sweetened condensed milk"],
    [400,"ml","coconutmilk","liquid","leche de coco","coconut milk"],
    [150,"ml","evaporatedmilk","liquid","leche evaporada","evaporated milk"],
    [5,"","egg","set","huevos","eggs"],
    [80,"g","desiccatedcoconut","structure","coco rallado","shredded coconut"]],
 es:{n:"Flan de coco", b:"Flan cubano con leche de coco y coco rallado que sube y forma una capa en el fondo. Sobre caramelo oscuro.",
  st:["Derrite el azúcar en el molde a fuego medio hasta que esté ámbar. Cubre el fondo.",
      "Calienta el horno a 170 °C.",
      "Licúa la leche condensada, la leche de coco, la evaporada y los huevos 20 segundos. Añade el coco rallado sin licuar.",
      "Vierte sobre el caramelo, tapa con aluminio y pon el molde en una bandeja con agua caliente.",
      "Hornea 60 minutos, hasta que el centro apenas tiemble. Enfría y refrigera 4 horas antes de desmoldar."],
  tp:["El coco sube durante el horneado y queda como base al desmoldar.",
      "Tuesta el coco antes si lo quieres más aromático."],
  v:"flan de coco cubano receta"},
 en:{n:"Cuban Coconut Flan", b:"Cuban flan with coconut milk and shredded coconut that rises to form a layer at the base. Over dark caramel.",
  st:["Melt the sugar in the mould over medium heat until amber. Coat the bottom.",
      "Heat the oven to 170 °C.",
      "Blend the condensed milk, coconut milk, evaporated milk and eggs for 20 seconds. Stir in the shredded coconut without blending.",
      "Pour over the caramel, cover with foil and set the mould in a tray of hot water.",
      "Bake 60 minutes, until the centre barely wobbles. Cool and chill 4 hours before turning out."],
  tp:["The coconut rises during baking and becomes the base when turned out.",
      "Toast the coconut first for more aroma."],
  v:"cuban coconut flan recipe"}}
];
