module.exports = [
{id:"fabada", c:"Spain", r:"mediterranean", m:"soup", t:210, s:6,
 i:[[500,"g","legume","protein","fabes (alubias blancas grandes)","fabes (large white beans)","remojadas 12 horas","soaked 12 hours"],
    [2,"","chorizo","protein","chorizos asturianos","Asturian chorizos"],
    [2,"","sausage","protein","morcillas asturianas","Asturian morcillas (blood sausages)"],
    [200,"g","pancetta","protein","panceta","pancetta","en un trozo","in one piece"],
    [2,"l","water","liquid","agua fría","cold water"],
    [1,"pinch","spice","aromatic","azafrán","saffron"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Fabada asturiana", b:"Fabes cremosas cocidas despacio con chorizo, morcilla y panceta. El plato de invierno de Asturias.",
  st:["Pon las fabes escurridas, el chorizo, la morcilla y la panceta en una olla y cubre con el agua fría.",
      "Hierve a fuego medio y retira la espuma.",
      "Añade el azafrán, baja el fuego al mínimo y cuece 3 horas sin remover, solo moviendo la olla.",
      "Cada 30 minutos añade un chorrito de agua fría para cortar el hervor y que las fabes no se rompan.",
      "Sala al final, corta las carnes y sirve con las fabes."],
  tp:["No remuevas nunca con cuchara; se rompen las fabes. Mueve la olla por las asas.",
      "Mejor de un día para otro."],
  v:"fabada asturiana receta"},
 en:{n:"Fabada Asturiana (Asturian Bean Stew)", b:"Creamy fabes simmered slowly with chorizo, morcilla and pancetta. Asturias' winter dish.",
  st:["Put the drained beans, chorizo, morcilla and pancetta in a pot and cover with the cold water.",
      "Bring to a boil over medium heat and skim the foam.",
      "Add the saffron, turn the heat to the lowest and cook 3 hours without stirring, only shaking the pot.",
      "Every 30 minutes add a splash of cold water to calm the boil so the beans don't split.",
      "Salt at the end, slice the meats and serve with the beans."],
  tp:["Never stir with a spoon; the beans break. Shake the pot by its handles.",
      "Better the next day."],
  v:"fabada asturiana recipe"}},

{id:"pollo-al-ajillo", c:"Spain", r:"mediterranean", m:"main", t:45, s:4,
 i:[[1.2,"kg","chicken","protein","pollo en trozos pequeños","chicken in small pieces"],
    [1,"tsp","salt","salt","sal","salt"],
    [80,"ml","oliveoil","fat","aceite de oliva","olive oil"],
    [12,"clove","garlic","aromatic","ajo","garlic","sin pelar, aplastados","unpeeled, crushed"],
    [150,"ml","winewhite","liquid","vino blanco","white wine"],
    [2,"leaf","herb","aromatic","hojas de laurel","bay leaves"],
    [2,"sprig","herb","aromatic","tomillo","thyme"],
    [1,"handful","herb","garnish","perejil","parsley","picado","chopped"]],
 es:{n:"Pollo al ajillo", b:"Pollo dorado con ajos enteros, vino blanco y laurel. Sencillo, de bar de pueblo y de domingo en casa.",
  st:["Sala el pollo.",
      "Dora el pollo en el aceite a fuego medio 15 minutos, hasta que esté dorado por todos lados.",
      "Añade los ajos y cuece 5 minutos más.",
      "Añade el vino, el laurel y el tomillo, tapa y cuece 15 minutos, hasta que el vino reduzca.",
      "Termina con el perejil y sirve con su salsa."],
  tp:["Los ajos sin pelar no se queman y quedan cremosos por dentro.",
      "Corta el pollo en trozos pequeños para que se dore bien por todas partes."],
  v:"pollo al ajillo receta"},
 en:{n:"Pollo al Ajillo (Spanish Garlic Chicken)", b:"Chicken browned with whole garlic, white wine and bay. Simple village-bar and Sunday food.",
  st:["Salt the chicken.",
      "Brown the chicken in the oil over medium heat for 15 minutes, until golden all over.",
      "Add the garlic and cook 5 minutes more.",
      "Add the wine, bay and thyme, cover and cook 15 minutes, until the wine reduces.",
      "Finish with the parsley and serve with its sauce."],
  tp:["Unpeeled garlic doesn't burn and turns creamy inside.",
      "Cut the chicken small so it browns everywhere."],
  v:"spanish garlic chicken recipe"}},

{id:"huevos-rotos", c:"Spain", r:"mediterranean", m:"main", t:30, s:2,
 i:[[500,"g","potato","structure","patatas","potatoes","en bastones","in batons"],
    [500,"ml","oliveoil","fat","aceite de oliva para freír","olive oil for frying"],
    [1,"tsp","salt","salt","sal","salt"],
    [4,"","egg","protein","huevos","eggs"],
    [80,"g","prosciutto","protein","jamón serrano","Spanish cured ham","en lonchas","sliced"]],
 es:{n:"Huevos rotos con jamón", b:"Patatas fritas con huevos de yema líquida rotos por encima y jamón. Plato de taberna madrileña.",
  st:["Fríe las patatas en el aceite a 150 °C durante 10 minutos, hasta que estén tiernas.",
      "Sube el fuego y fríe 3 minutos más, hasta que estén doradas. Escurre y sala.",
      "Fríe los huevos en el mismo aceite, con la yema líquida.",
      "Pon las patatas en un plato, los huevos encima y el jamón.",
      "Rompe los huevos con el tenedor en la mesa y mezcla."],
  tp:["El aceite de oliva da un sabor que el de girasol no tiene.",
      "Los huevos deben quedar con puntilla y la yema cruda."],
  v:"huevos rotos con jamón receta"},
 en:{n:"Huevos Rotos (Broken Eggs with Ham)", b:"Chips with runny eggs broken over them and cured ham. A Madrid tavern dish.",
  st:["Fry the potatoes in the oil at 150 °C for 10 minutes, until tender.",
      "Raise the heat and fry 3 minutes more, until golden. Drain and salt.",
      "Fry the eggs in the same oil, with runny yolks.",
      "Pile the potatoes on a plate with the eggs and ham on top.",
      "Break the eggs with a fork at the table and mix."],
  tp:["Olive oil adds a flavour sunflower oil doesn't.",
      "The eggs should have lacy edges and raw yolks."],
  v:"huevos rotos recipe"}},

{id:"pimientos-de-padron", c:"Spain", r:"mediterranean", m:"starter", t:10, s:4,
 i:[[300,"g","bellpepper","structure","pimientos de Padrón","Padrón peppers"],
    [3,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [1,"tsp","salt","salt","sal en escamas","flaky salt"]],
 es:{n:"Pimientos de Padrón", b:"Pimientos pequeños fritos hasta que se ampollan, con sal en escamas. Unos pican y otros no.",
  st:["Lava y seca muy bien los pimientos.",
      "Calienta el aceite a fuego fuerte en una sartén grande.",
      "Fríe los pimientos 4 minutos, moviéndolos, hasta que la piel se ampolle y se dore.",
      "Escurre sobre papel, espolvorea la sal y sirve enseguida."],
  tp:["Deben estar secos o el aceite salta.",
      "Uno de cada diez más o menos pica; es parte del juego."],
  v:"pimientos de padrón receta"},
 en:{n:"Padrón Peppers", b:"Small peppers fried until blistered, with flaky salt. Some are hot and some are not.",
  st:["Wash and dry the peppers very well.",
      "Heat the oil over high heat in a large frying pan.",
      "Fry the peppers for 4 minutes, tossing, until the skin blisters and browns.",
      "Drain on paper, sprinkle with the salt and serve at once."],
  tp:["They must be dry or the oil spits.",
      "About one in ten is hot; that's part of the game."],
  v:"padron peppers recipe"}},

{id:"espinacas-con-garbanzos", c:"Spain", r:"mediterranean", m:"main", t:30, s:4,
 i:[[5,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [2,"","bread","thicken","rebanadas de pan","slices of bread"],
    [4,"clove","garlic","aromatic","ajo","garlic","en láminas","sliced"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [2,"tsp","paprika","aromatic","pimentón dulce","sweet paprika"],
    [2,"tbsp","winevinegar","acid","vinagre de Jerez","sherry vinegar"],
    [500,"g","veg","structure","espinacas frescas","fresh spinach"],
    [500,"g","legume","protein","garbanzos cocidos","cooked chickpeas","escurridos","drained"],
    [150,"ml","water","liquid","agua","water"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Espinacas con garbanzos", b:"Espinacas y garbanzos en una salsa de pan frito, ajo, comino y pimentón. Tapa sevillana de herencia morisca.",
  st:["Fríe el pan y el ajo en 3 cucharadas del aceite 3 minutos, hasta que estén dorados.",
      "Machaca el pan y el ajo con el comino, el pimentón y el vinagre hasta tener una pasta.",
      "Saltea las espinacas en el resto del aceite 3 minutos, hasta que se ablanden.",
      "Añade los garbanzos, la pasta, el agua y la sal y cuece 10 minutos.",
      "Sirve caliente."],
  tp:["El pan frito es lo que liga la salsa; no lo quites.",
      "Con espinacas congeladas, descongélalas y escúrrelas bien primero."],
  v:"espinacas con garbanzos sevillanas"},
 en:{n:"Espinacas con Garbanzos (Spinach and Chickpeas)", b:"Spinach and chickpeas in a sauce of fried bread, garlic, cumin and paprika. A Seville tapa with Moorish roots.",
  st:["Fry the bread and garlic in 3 tablespoons of the oil for 3 minutes, until golden.",
      "Pound the bread and garlic with the cumin, paprika and vinegar to a paste.",
      "Sauté the spinach in the rest of the oil for 3 minutes, until wilted.",
      "Add the chickpeas, paste, water and salt and cook 10 minutes.",
      "Serve hot."],
  tp:["The fried bread is what binds the sauce; don't leave it out.",
      "With frozen spinach, thaw and squeeze it well first."],
  v:"spinach and chickpeas recipe"}},

{id:"calamares-a-la-romana", c:"Spain", r:"mediterranean", m:"starter", t:30, s:4,
 i:[[600,"g","squid","protein","calamares limpios","cleaned squid","en anillas de 1 cm","in 1 cm rings"],
    [150,"g","apflour","dredge","harina de trigo","plain flour"],
    [1,"","egg","binder","huevo","egg"],
    [200,"ml","water","liquid","agua con gas muy fría","ice-cold sparkling water"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"l","oil","fat","aceite para freír","oil for frying"],
    [1,"","citrus","garnish","limón","lemon","en gajos","in wedges"]],
 es:{n:"Calamares a la romana", b:"Anillas de calamar en rebozado ligero y crujiente. La ración de todas las terrazas de España.",
  st:["Seca muy bien las anillas con papel.",
      "Bate la harina, el huevo, el agua con gas y la sal hasta tener una masa lisa.",
      "Calienta el aceite a 180 °C.",
      "Pasa las anillas por la masa y fríelas en tandas 2 minutos, hasta que estén doradas.",
      "Escurre sobre papel y sirve con el limón."],
  tp:["Más de 2 minutos los vuelve gomosos.",
      "El agua con gas muy fría hace el rebozado más ligero."],
  v:"calamares a la romana receta"},
 en:{n:"Calamares a la Romana (Fried Squid Rings)", b:"Squid rings in a light, crisp batter. The plate on every terrace in Spain.",
  st:["Pat the rings very dry with paper.",
      "Whisk the flour, egg, sparkling water and salt to a smooth batter.",
      "Heat the oil to 180 °C.",
      "Dip the rings in the batter and fry in batches for 2 minutes, until golden.",
      "Drain on paper and serve with the lemon."],
  tp:["More than 2 minutes makes them rubbery.",
      "Ice-cold sparkling water makes the batter lighter."],
  v:"calamares a la romana recipe"}},

{id:"leche-frita", c:"Spain", r:"mediterranean", m:"sweet", t:60, s:8,
 i:[[750,"ml","milk","liquid","leche","milk"],
    [1,"","citrus","aromatic","cáscara de limón","lemon peel","en una tira","in one strip"],
    [1,"","spice","aromatic","rama de canela","cinnamon stick"],
    [120,"g","sugar","sweet","azúcar","sugar"],
    [80,"g","cornstarch","set","fécula de maíz","cornstarch"],
    [2,"","eggyolk","enrich","yemas de huevo","egg yolks"],
    [60,"g","apflour","dredge","harina de trigo","plain flour"],
    [2,"","egg","binder","huevos batidos","beaten eggs"],
    [500,"ml","oil","fat","aceite para freír","oil for frying"],
    [80,"g","sugar","garnish","azúcar para rebozar","sugar for coating"],
    [2,"tsp","spice","garnish","canela molida","ground cinnamon"]],
 es:{n:"Leche frita", b:"Crema espesa de leche con limón y canela, cortada en cuadros, rebozada y frita. Dulce del norte de España.",
  st:["Calienta 600 ml de la leche con el limón y la canela. Deja infusionar 10 minutos y cuela.",
      "Mezcla el resto de la leche con 120 g de azúcar, la fécula y las yemas. Añade a la leche caliente y cuece 5 minutos, removiendo, hasta que esté muy espesa.",
      "Extiende en una fuente engrasada con 2 cm de grosor y refrigera 4 horas.",
      "Corta en cuadrados, pásalos por la harina y el huevo y fríelos a 180 °C durante 1 minuto por lado.",
      "Rebózalos en el azúcar mezclado con la canela."],
  tp:["La crema debe estar muy firme antes de cortarla; si no, se deshace al freír.",
      "Se come templada o fría."],
  v:"leche frita receta"},
 en:{n:"Leche Frita (Fried Milk Custard)", b:"A thick lemon and cinnamon milk custard, cut into squares, coated and fried. A sweet from northern Spain.",
  st:["Heat 600 ml of the milk with the lemon and cinnamon. Infuse 10 minutes and strain.",
      "Mix the rest of the milk with 120 g of sugar, the cornstarch and yolks. Add to the hot milk and cook 5 minutes, stirring, until very thick.",
      "Spread 2 cm thick in a greased dish and refrigerate 4 hours.",
      "Cut into squares, coat in the flour and egg and fry at 180 °C for 1 minute a side.",
      "Roll in the sugar mixed with the cinnamon."],
  tp:["The custard must be very firm before cutting; otherwise it falls apart in the oil.",
      "Eat it warm or cold."],
  v:"leche frita recipe"}},

{id:"bacalao-al-pil-pil", c:"Spain", r:"mediterranean", m:"main", t:40, s:4,
 i:[[4,"","whitefish","protein","lomos de bacalao desalado con piel","desalted salt cod loins, skin on"],
    [250,"ml","oliveoil","fat","aceite de oliva suave","mild olive oil"],
    [6,"clove","garlic","aromatic","ajo","garlic","en láminas","sliced"],
    [1,"","chilli","aromatic","guindilla seca","dried chilli","en aros","in rings"]],
 es:{n:"Bacalao al pil pil", b:"Bacalao confitado en aceite de ajo, con la salsa ligada solo por la gelatina de la piel. Un clásico vasco.",
  st:["Seca muy bien el bacalao.",
      "Dora el ajo y la guindilla en el aceite a fuego suave en una cazuela de barro. Sácalos y deja templar el aceite.",
      "Pon el bacalao con la piel hacia arriba en el aceite templado y confita a fuego muy bajo 10 minutos, moviendo la cazuela, sin que hierva.",
      "Saca el bacalao. Mueve la cazuela en círculos o bate con un colador hasta que el aceite se emulsione con la gelatina y espese como una mayonesa ligera.",
      "Vuelve a poner el bacalao, cúbrelo con la salsa y termina con el ajo y la guindilla."],
  tp:["El aceite debe estar templado, a unos 60 °C, para que el bacalao suelte la gelatina.",
      "Si no liga, añade una cucharada de agua tibia y sigue moviendo."],
  v:"bacalao al pil pil receta"},
 en:{n:"Bacalao al Pil Pil (Salt Cod in Garlic Emulsion)", b:"Salt cod poached in garlic oil, the sauce bound only by gelatin from the skin. A Basque classic.",
  st:["Pat the cod very dry.",
      "Gently brown the garlic and chilli in the oil in a clay dish. Remove them and let the oil cool slightly.",
      "Put the cod skin side up in the warm oil and poach on very low heat for 10 minutes, shaking the dish, without boiling.",
      "Remove the cod. Swirl the dish or whisk with a sieve until the oil emulsifies with the gelatin and thickens like a light mayonnaise.",
      "Return the cod, spoon the sauce over and finish with the garlic and chilli."],
  tp:["The oil should be warm, about 60 °C, for the cod to release its gelatin.",
      "If it won't bind, add a spoonful of warm water and keep swirling."],
  v:"bacalao al pil pil recipe"}},

{id:"marmitako", c:"Spain", r:"mediterranean", m:"soup", t:50, s:6,
 i:[[600,"g","tuna","protein","bonito del norte fresco","fresh albacore tuna","en dados de 3 cm","in 3 cm dice"],
    [4,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","pimiento verde","green bell pepper","picado","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"tbsp","bellpepper","umami","carne de pimiento choricero","choricero pepper paste"],
    [1,"","tomato","sauce","tomate","tomato","rallado","grated"],
    [1,"kg","potato","structure","patatas","potatoes","en trozos rotos","snapped into chunks"],
    [1.2,"l","fishstock","liquid","caldo de pescado","fish stock"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"handful","herb","garnish","perejil","parsley","picado","chopped"]],
 es:{n:"Marmitako", b:"Guiso de bonito y patata de los pescadores vascos. El bonito entra al final, casi crudo.",
  st:["Sofríe la cebolla, el pimiento y el ajo en el aceite 10 minutos.",
      "Añade la pasta de choricero y el tomate y cuece 5 minutos.",
      "Añade la patata, rehoga 2 minutos, cubre con el caldo y cuece 25 minutos.",
      "Sala el bonito y añádelo. Apaga el fuego, tapa y deja 5 minutos.",
      "Termina con el perejil."],
  tp:["El bonito se cuece con el calor residual; si hierve, se seca.",
      "Rompe la patata con el cuchillo para que suelte almidón y espese."],
  v:"marmitako de bonito receta"},
 en:{n:"Marmitako (Basque Tuna and Potato Stew)", b:"The tuna and potato stew of Basque fishermen. The tuna goes in at the end, almost raw.",
  st:["Cook the onion, pepper and garlic in the oil for 10 minutes.",
      "Add the choricero paste and tomato and cook 5 minutes.",
      "Add the potato, stir 2 minutes, cover with the stock and cook 25 minutes.",
      "Salt the tuna and add it. Turn off the heat, cover and leave 5 minutes.",
      "Finish with the parsley."],
  tp:["The tuna cooks in the residual heat; if it boils, it dries out.",
      "Snap the potato with the knife so it releases starch and thickens."],
  v:"marmitako recipe"}},

{id:"cocido-madrileno", c:"Spain", r:"mediterranean", m:"main", t:240, s:8,
 i:[[400,"g","legume","protein","garbanzos","chickpeas","remojados 12 horas","soaked 12 hours"],
    [500,"g","beef","protein","morcillo de res","beef shin"],
    [0.5,"","chicken","protein","gallina o pollo","boiling hen or chicken"],
    [150,"g","pancetta","protein","tocino fresco","fresh pork belly"],
    [1,"","ham","umami","hueso de jamón","ham bone"],
    [2,"","chorizo","protein","chorizos","chorizos"],
    [1,"","sausage","protein","morcilla","morcilla (blood sausage)"],
    [4,"l","water","liquid","agua","water"],
    [4,"","potato","structure","patatas","potatoes","peladas","peeled"],
    [3,"","veg","structure","zanahorias","carrots"],
    [0.5,"","veg","structure","repollo","cabbage","en tiras","shredded"],
    [100,"g","pasta","structure","fideos finos","fine noodles"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Cocido madrileño", b:"Garbanzos, carnes y verduras cocidos juntos y servidos en tres vuelcos: sopa, garbanzos con verdura y carnes.",
  st:["Pon la res, la gallina, el tocino y el hueso en el agua, hierve y quita la espuma. Añade los garbanzos en una red y cuece 2 horas y media a fuego bajo.",
      "Añade las patatas y las zanahorias y cuece 30 minutos más.",
      "Cuece aparte el chorizo, la morcilla y el repollo en agua con sal 30 minutos.",
      "Cuela 1,5 l del líquido del cocido y cuece en él los fideos 4 minutos. Sala.",
      "Sirve primero la sopa, luego los garbanzos con las verduras y al final las carnes."],
  tp:["El chorizo y la morcilla se cuecen aparte para que no tiñan ni engrasen la sopa.",
      "Los restos se fríen al día siguiente como ropa vieja."],
  v:"cocido madrileño receta tres vuelcos"},
 en:{n:"Cocido Madrileño (Madrid Chickpea Stew)", b:"Chickpeas, meats and vegetables cooked together and served in three courses: soup, chickpeas with vegetables, then meats.",
  st:["Put the beef, hen, pork belly and ham bone in the water, bring to a boil and skim. Add the chickpeas in a net bag and simmer 2 and a half hours on low.",
      "Add the potatoes and carrots and cook 30 minutes more.",
      "Separately, boil the chorizo, morcilla and cabbage in salted water for 30 minutes.",
      "Strain 1.5 l of the cooking liquid and cook the noodles in it for 4 minutes. Salt.",
      "Serve the soup first, then the chickpeas with the vegetables and finally the meats."],
  tp:["The chorizo and morcilla cook separately so they don't stain or grease the soup.",
      "Leftovers are fried the next day as ropa vieja."],
  v:"cocido madrileno recipe"}}
];
