module.exports = [
{id:"rabo-de-toro", c:"Spain", r:"mediterranean", m:"main", t:240, s:4,
 i:[[1.5,"kg","beef","protein","rabo de toro o de vaca en trozos","oxtail, in pieces"],
    [40,"g","apflour","dredge","harina de trigo","plain flour"],
    [5,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [2,"","onion","aromatic","cebollas","onions","picadas","chopped"],
    [2,"","veg","aromatic","zanahorias","carrots","picadas","chopped"],
    [1,"","bellpepper","aromatic","pimiento rojo","red bell pepper","picado","chopped"],
    [4,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [750,"ml","winered","liquid","vino tinto","red wine"],
    [2,"leaf","herb","aromatic","laurel","bay leaves"],
    [2,"sprig","herb","aromatic","tomillo","thyme"],
    [500,"ml","water","liquid","agua","water"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Rabo de toro", b:"Rabo guisado horas en vino tinto hasta que la carne se separa del hueso. Clásico cordobés.",
  st:["Sala el rabo, pásalo por la harina y dóralo en el aceite en tandas. Sácalo.",
      "Sofríe la cebolla, la zanahoria, el pimiento y el ajo 12 minutos.",
      "Añade el vino y deja reducir 10 minutos.",
      "Vuelve a poner el rabo con el laurel, el tomillo y el agua. Tapa y cuece 3 horas a fuego muy bajo.",
      "Saca el rabo, tritura la salsa y vuelve a juntarlos."],
  tp:["Está mejor hecho el día anterior: quita la grasa solidificada de la superficie.",
      "La carne debe separarse del hueso con un tenedor."],
  v:"rabo de toro cordobés"},
 en:{n:"Rabo de Toro (Spanish Oxtail Stew)", b:"Oxtail braised for hours in red wine until the meat falls off the bone. A Córdoba classic.",
  st:["Salt the oxtail, dredge in the flour and brown in the oil in batches. Remove.",
      "Cook the onion, carrot, pepper and garlic for 12 minutes.",
      "Add the wine and reduce 10 minutes.",
      "Return the oxtail with the bay, thyme and water. Cover and simmer 3 hours on very low heat.",
      "Lift out the oxtail, blend the sauce and combine again."],
  tp:["Better made the day before: lift off the set fat from the top.",
      "The meat should come off the bone with a fork."],
  v:"spanish oxtail stew"}},

{id:"salpicon-de-marisco", c:"Spain", r:"mediterranean", m:"starter", t:30, s:4,
 i:[[300,"g","prawn","protein","gambas cocidas y peladas","cooked peeled prawns"],
    [250,"g","mussel","protein","mejillones cocidos sin concha","cooked shelled mussels"],
    [200,"g","squid","protein","pulpo cocido","cooked octopus","en trozos","in pieces"],
    [1,"","onion","aromatic","cebolla","onion","picada fina","finely chopped"],
    [1,"","bellpepper","aromatic","pimiento rojo","red bell pepper","picado fino","finely chopped"],
    [1,"","bellpepper","aromatic","pimiento verde","green bell pepper","picado fino","finely chopped"],
    [100,"ml","oliveoil","fat","aceite de oliva virgen extra","extra virgin olive oil"],
    [40,"ml","winevinegar","acid","vinagre de Jerez","sherry vinegar"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Salpicón de marisco", b:"Ensalada fría de gambas, mejillones y pulpo con pimientos picados en vinagreta. Tapa de verano en Andalucía.",
  st:["Mezcla la cebolla y los pimientos.",
      "Bate el aceite con el vinagre y la sal.",
      "Añade el marisco y la vinagreta a las verduras.",
      "Refrigera 1 hora antes de servir."],
  tp:["Pica las verduras muy finas, del mismo tamaño.",
      "Se conserva 1 día en la nevera."],
  v:"salpicón de marisco"},
 en:{n:"Salpicón de Marisco (Spanish Seafood Salad)", b:"A cold salad of prawns, mussels and octopus with finely chopped peppers in vinaigrette. A summer tapa in Andalusia.",
  st:["Mix the onion and peppers.",
      "Whisk the oil with the vinegar and salt.",
      "Add the seafood and dressing to the vegetables.",
      "Chill 1 hour before serving."],
  tp:["Chop the vegetables very finely, all the same size.",
      "It keeps 1 day in the fridge."],
  v:"spanish seafood salad"}},

{id:"zarangollo", c:"Spain", r:"mediterranean", m:"starter", t:45, s:4,
 i:[[4,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [2,"","onion","aromatic","cebollas","onions","en tiras finas","thinly sliced"],
    [3,"","veg","structure","calabacines","courgettes","en láminas finas","thinly sliced"],
    [1,"tsp","salt","salt","sal","salt"],
    [4,"","egg","binder","huevos","eggs"]],
 es:{n:"Zarangollo murciano", b:"Calabacín y cebolla pochados lentamente y ligados con huevo. Plato de huerta de Murcia.",
  st:["Pocha la cebolla en el aceite a fuego bajo 15 minutos.",
      "Añade el calabacín y la sal y cocina 20 minutos, hasta que esté muy tierno.",
      "Bate los huevos, añádelos y remueve 2 minutos, hasta que cuajen suaves."],
  tp:["La paciencia es el secreto: la verdura debe quedar casi confitada.",
      "Retíralo cuando el huevo esté jugoso."],
  v:"zarangollo murciano"},
 en:{n:"Zarangollo (Murcian Courgette and Egg)", b:"Courgette and onion cooked down slowly and bound with egg. A garden dish from Murcia.",
  st:["Soften the onion in the oil on low for 15 minutes.",
      "Add the courgette and salt and cook 20 minutes, until very soft.",
      "Beat the eggs, add them and stir 2 minutes, until softly set."],
  tp:["Patience is the secret: the vegetables should be almost confit.",
      "Take it off while the egg is still moist."],
  v:"spanish zarangollo"}},

{id:"pollo-en-pepitoria", c:"Spain", r:"mediterranean", m:"main", t:75, s:4,
 i:[[1.2,"kg","chicken","protein","pollo en trozos","chicken pieces"],
    [30,"g","apflour","dredge","harina de trigo","plain flour"],
    [4,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic"],
    [40,"g","almond","thicken","almendras tostadas","toasted almonds"],
    [150,"ml","winewhite","liquid","vino blanco","white wine"],
    [400,"ml","water","liquid","agua","water"],
    [1,"pinch","spice","aromatic","azafrán","saffron"],
    [2,"","eggyolk","thicken","yemas de huevo duro","hard-boiled egg yolks"],
    [2,"tsp","salt","salt","sal","salt"],
    [1,"handful","herb","garnish","perejil","parsley","picado","chopped"]],
 es:{n:"Pollo en pepitoria", b:"Pollo guisado en salsa de almendra, yema de huevo y azafrán. Receta de la cocina castellana antigua.",
  st:["Sala el pollo, pásalo por la harina y dóralo en el aceite 10 minutos. Sácalo.",
      "Fríe los ajos enteros 2 minutos y sácalos. Sofríe la cebolla 8 minutos.",
      "Añade el vino, el agua y el pollo. Tapa y cuece 30 minutos.",
      "Machaca en el mortero los ajos fritos, las almendras, las yemas y el azafrán con un poco de caldo.",
      "Añade el majado a la cazuela y cuece 10 minutos más. Termina con el perejil."],
  tp:["El majado es lo que espesa y da carácter a la salsa.",
      "Algunas versiones añaden la clara picada por encima."],
  v:"pollo en pepitoria"},
 en:{n:"Pollo en Pepitoria (Chicken in Almond Saffron Sauce)", b:"Chicken braised in a sauce of almond, egg yolk and saffron. An old Castilian recipe.",
  st:["Salt the chicken, dredge in the flour and brown in the oil for 10 minutes. Remove.",
      "Fry the whole garlic cloves 2 minutes and lift out. Cook the onion 8 minutes.",
      "Add the wine, water and chicken. Cover and simmer 30 minutes.",
      "Pound the fried garlic, almonds, yolks and saffron in a mortar with a little broth.",
      "Stir the paste into the pan and cook 10 minutes more. Finish with the parsley."],
  tp:["The pounded paste thickens the sauce and gives it character.",
      "Some versions sprinkle the chopped egg white on top."],
  v:"spanish chicken pepitoria"}},

{id:"tarta-de-queso-vasca", c:"Spain", r:"mediterranean", m:"sweet", t:75, s:10,
 i:[[750,"g","creamcheese","structure","queso crema","cream cheese"],
    [250,"g","sugar","sweet","azúcar","sugar"],
    [5,"","egg","set","huevos","eggs"],
    [400,"ml","heavycream","enrich","nata para montar","double cream"],
    [20,"g","apflour","structure","harina de trigo","plain flour"]],
 es:{n:"Tarta de queso vasca", b:"Tarta de queso quemada por fuera y cremosa por dentro. Nacida en un bar de San Sebastián.",
  st:["Bate el queso con el azúcar hasta que esté liso.",
      "Añade los huevos de uno en uno, luego la nata y por último la harina tamizada.",
      "Forra un molde de 22 cm con dos hojas de papel de horno arrugadas que sobresalgan.",
      "Vierte la mezcla y hornea a 220 °C 45 minutos, hasta que esté muy tostada por fuera y tiemble en el centro.",
      "Deja enfriar a temperatura ambiente y luego refrigera 4 horas."],
  tp:["El centro debe temblar al sacarla: cuaja al enfriar.",
      "Queso a temperatura ambiente para que no queden grumos."],
  v:"tarta de queso vasca"},
 en:{n:"Basque Burnt Cheesecake", b:"A cheesecake scorched on the outside and creamy inside. Born in a San Sebastián bar.",
  st:["Beat the cheese with the sugar until smooth.",
      "Add the eggs one at a time, then the cream, then the sifted flour.",
      "Line a 22 cm tin with two crumpled sheets of baking paper standing above the rim.",
      "Pour in and bake at 220 °C for 45 minutes, until very dark outside and wobbly in the centre.",
      "Cool at room temperature, then chill 4 hours."],
  tp:["The centre should wobble when it comes out: it sets as it cools.",
      "Have the cheese at room temperature so there are no lumps."],
  v:"basque burnt cheesecake"}},

{id:"huevos-a-la-flamenca", c:"Spain", r:"mediterranean", m:"main", t:40, s:4,
 i:[[3,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [100,"g","chorizo","protein","chorizo","chorizo","en rodajas","sliced"],
    [60,"g","prosciutto","protein","jamón serrano","Spanish cured ham","en tiras","in strips"],
    [400,"g","tomato","liquid","tomate triturado","crushed tomatoes"],
    [150,"g","legume","structure","guisantes","peas"],
    [1,"","bellpepper","garnish","pimiento rojo asado","roasted red pepper","en tiras","in strips"],
    [8,"","egg","protein","huevos","eggs"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Huevos a la flamenca", b:"Huevos cuajados en cazuelitas sobre tomate con chorizo, jamón, guisantes y pimiento. Plato sevillano.",
  st:["Sofríe la cebolla y el ajo en el aceite 6 minutos. Añade el chorizo y el jamón y cocina 3 minutos.",
      "Añade el tomate y la sal y cocina 10 minutos. Añade los guisantes.",
      "Reparte en 4 cazuelitas de barro y casca 2 huevos en cada una.",
      "Decora con el pimiento.",
      "Hornea a 200 °C 10 minutos, hasta que las claras cuajen."],
  tp:["La yema debe quedar líquida.",
      "Se puede hacer en una sola cazuela grande."],
  v:"huevos a la flamenca"},
 en:{n:"Huevos a la Flamenca (Flamenco Eggs)", b:"Eggs baked in clay dishes over tomato with chorizo, ham, peas and pepper. A Seville dish.",
  st:["Cook the onion and garlic in the oil for 6 minutes. Add the chorizo and ham and cook 3 minutes.",
      "Add the tomato and salt and cook 10 minutes. Add the peas.",
      "Divide between 4 clay dishes and crack 2 eggs into each.",
      "Top with the pepper.",
      "Bake at 200 °C for 10 minutes, until the whites set."],
  tp:["The yolk should stay runny.",
      "You can make it in one large dish."],
  v:"spanish flamenco eggs"}},

{id:"caldo-gallego", c:"Spain", r:"mediterranean", m:"soup", t:150, s:6,
 i:[[250,"g","legume","structure","alubias blancas secas","dried white beans"],
    [2.5,"l","water","liquid","agua","water"],
    [300,"g","pork","protein","lacón o paleta de cerdo","pork shoulder"],
    [100,"g","lard","fat","unto o manteca de cerdo","pork fat"],
    [4,"","potato","structure","patatas","potatoes","chascadas","broken into chunks"],
    [400,"g","veg","structure","grelos o berza","turnip greens or cabbage","picados","chopped"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Caldo gallego", b:"Caldo de alubias, patata y grelos con cerdo. Reconforta los inviernos lluviosos de Galicia.",
  st:["Remoja las alubias 12 horas.",
      "Cuécelas en el agua con el cerdo y el unto 90 minutos.",
      "Añade las patatas y la sal y cuece 20 minutos.",
      "Añade los grelos y cuece 15 minutos más.",
      "Saca el cerdo, córtalo y devuélvelo a la olla."],
  tp:["Déjalo reposar 10 minutos antes de servir.",
      "Si no hay grelos, usa col rizada o berza."],
  v:"caldo gallego"},
 en:{n:"Caldo Gallego (Galician Bean and Greens Soup)", b:"A broth of white beans, potato and turnip greens with pork. Comfort through Galicia's rainy winters.",
  st:["Soak the beans 12 hours.",
      "Simmer them in the water with the pork and pork fat for 90 minutes.",
      "Add the potatoes and salt and cook 20 minutes.",
      "Add the greens and cook 15 minutes more.",
      "Lift out the pork, chop it and return it to the pot."],
  tp:["Let it rest 10 minutes before serving.",
      "No turnip greens? Use kale or cabbage."],
  v:"galician caldo gallego"}},

{id:"patatas-a-la-importancia", c:"Spain", r:"mediterranean", m:"main", t:60, s:4,
 i:[[1,"kg","potato","structure","patatas","potatoes","en rodajas de 1 cm","in 1 cm slices"],
    [100,"g","apflour","dredge","harina de trigo","plain flour"],
    [3,"","egg","binder","huevos batidos","beaten eggs"],
    [500,"ml","oliveoil","fat","aceite de oliva para freír","olive oil for frying"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [150,"ml","winewhite","liquid","vino blanco","white wine"],
    [500,"ml","water","liquid","agua","water"],
    [1,"pinch","spice","aromatic","azafrán","saffron"],
    [1,"handful","herb","aromatic","perejil","parsley","picado","chopped"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Patatas a la importancia", b:"Rodajas de patata rebozadas y guisadas en salsa de vino y azafrán. Receta humilde de Valladolid.",
  st:["Sala las patatas, pásalas por la harina y el huevo y fríelas 3 minutos por lado. Reserva.",
      "En una cazuela con 3 cucharadas del aceite, sofríe la cebolla y el ajo 8 minutos.",
      "Añade el vino, el agua, el azafrán y el perejil y hierve 5 minutos.",
      "Añade las patatas y cuece 20 minutos a fuego suave, hasta que estén tiernas."],
  tp:["Mueve la cazuela en lugar de remover para que el rebozado no se despegue.",
      "La salsa debe quedar ligada por la harina del rebozado."],
  v:"patatas a la importancia"},
 en:{n:"Patatas a la Importancia (Battered Potatoes in Saffron Sauce)", b:"Potato slices dipped in batter and braised in wine and saffron sauce. A humble recipe from Valladolid.",
  st:["Salt the potatoes, dip in the flour and egg and fry 3 minutes per side. Set aside.",
      "In a pan with 3 tablespoons of the oil, cook the onion and garlic for 8 minutes.",
      "Add the wine, water, saffron and parsley and boil 5 minutes.",
      "Add the potatoes and simmer 20 minutes, until tender."],
  tp:["Shake the pan instead of stirring so the coating stays on.",
      "The flour from the coating thickens the sauce."],
  v:"spanish potatoes a la importancia"}},

{id:"rosquillas-de-anis", c:"Spain", r:"mediterranean", m:"sweet", t:60, s:24,
 i:[[500,"g","apflour","structure","harina de trigo","plain flour"],
    [2,"tsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [3,"","egg","binder","huevos","eggs"],
    [150,"g","sugar","sweet","azúcar","sugar"],
    [100,"ml","oliveoil","fat","aceite de oliva suave","light olive oil"],
    [100,"ml","milk","liquid","leche","milk"],
    [1,"tsp","spice","aromatic","anís en grano","aniseed"],
    [1,"","citrus","aromatic","ralladura de limón","lemon zest"],
    [1,"l","oliveoil","fat","aceite de oliva suave para freír","light olive oil for frying"],
    [80,"g","sugar","garnish","azúcar (para rebozar)","sugar (for coating)"]],
 es:{n:"Rosquillas de anís", b:"Rosquillas fritas perfumadas con anís y limón. El dulce de las abuelas en Semana Santa.",
  st:["Bate los huevos con el azúcar. Añade el aceite, la leche, el anís y la ralladura.",
      "Añade la harina y el polvo de hornear hasta tener una masa blanda.",
      "Con las manos aceitadas, forma bolas, haz un agujero en el centro y estira en aro.",
      "Fríe a 170 °C 2 minutos por lado, hasta que estén doradas.",
      "Escurre y reboza en el azúcar."],
  tp:["Unta las manos con aceite para que no se pegue la masa.",
      "Guárdalas en una lata: duran una semana."],
  v:"rosquillas de anís caseras"},
 en:{n:"Rosquillas de Anís (Spanish Anise Doughnuts)", b:"Fried doughnuts scented with aniseed and lemon. Grandma's Holy Week sweet.",
  st:["Whisk the eggs with the sugar. Add the oil, milk, aniseed and zest.",
      "Add the flour and baking powder to make a soft dough.",
      "With oiled hands, shape balls, poke a hole in the centre and stretch into rings.",
      "Fry at 170 °C for 2 minutes per side, until golden.",
      "Drain and roll in the sugar."],
  tp:["Oil your hands so the dough doesn't stick.",
      "Keep them in a tin: they last a week."],
  v:"spanish anise doughnuts"}},

{id:"gachas-manchegas", c:"Spain", r:"mediterranean", m:"main", t:30, s:4,
 i:[[6,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [100,"g","pancetta","protein","panceta","pancetta","en dados","diced"],
    [3,"clove","garlic","aromatic","ajo","garlic","laminado","sliced"],
    [80,"g","legume","structure","harina de almortas","grass pea flour"],
    [1,"tsp","paprika","aromatic","pimentón dulce","sweet paprika"],
    [1,"tsp","spice","aromatic","comino","cumin"],
    [750,"ml","water","liquid","agua","water"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Gachas manchegas", b:"Crema espesa de harina de almortas con pimentón y panceta, que se come de la sartén con cuchara. Invierno en La Mancha.",
  st:["Fríe la panceta en el aceite 5 minutos. Sácala.",
      "Dora el ajo 1 minuto y sácalo.",
      "Añade la harina y tuéstala 2 minutos. Añade el pimentón y el comino.",
      "Añade el agua poco a poco, removiendo, y la sal. Cuece 10 minutos hasta que espese.",
      "Sirve con la panceta y el ajo por encima."],
  tp:["Añade el agua de a poco para que no queden grumos.",
      "Si no hay harina de almortas, usa harina de garbanzo."],
  v:"gachas manchegas"},
 en:{n:"Gachas Manchegas (La Mancha Flour Porridge)", b:"A thick cream of grass pea flour with paprika and pancetta, eaten from the pan with spoons. Winter in La Mancha.",
  st:["Fry the pancetta in the oil for 5 minutes. Lift out.",
      "Brown the garlic 1 minute and lift out.",
      "Add the flour and toast 2 minutes. Add the paprika and cumin.",
      "Add the water gradually, stirring, and the salt. Cook 10 minutes until thick.",
      "Serve with the pancetta and garlic on top."],
  tp:["Add the water little by little to avoid lumps.",
      "No grass pea flour? Use chickpea flour."],
  v:"spanish gachas manchegas"}}
];
