module.exports = [
{id:"gazpacho", c:"Spain", r:"mediterranean", m:"soup", t:20, s:6,
 i:[[1,"kg","tomato","structure","tomates maduros","ripe tomatoes","en trozos","in chunks"],
    [1,"","veg","structure","pepino","cucumber","pelado, en trozos","peeled, in chunks"],
    [1,"","bellpepper","structure","pimiento verde italiano","Italian green pepper","en trozos","in chunks"],
    [1,"clove","garlic","aromatic","ajo","garlic"],
    [50,"g","bread","thicken","pan del día anterior","day-old bread","sin corteza","crusts removed"],
    [100,"ml","oliveoil","fat","aceite de oliva virgen extra","extra virgin olive oil"],
    [2,"tbsp","winevinegar","acid","vinagre de Jerez","sherry vinegar"],
    [1,"tsp","salt","salt","sal","salt"],
    [200,"ml","water","liquid","agua fría","cold water"]],
 es:{n:"Gazpacho andaluz", b:"Sopa fría de tomate, pepino, pimiento y aceite de oliva, batida hasta quedar sedosa. El verano de Andalucía.",
  st:["Remoja el pan en el agua 5 minutos.",
      "Licúa el tomate, el pepino, el pimiento, el ajo y el pan con su agua hasta que esté liso.",
      "Con el motor en marcha, añade el aceite en hilo, luego el vinagre y la sal.",
      "Cuela si lo quieres muy fino.",
      "Refrigera al menos 2 horas y sirve bien frío."],
  tp:["Prueba y ajusta el vinagre y la sal después de enfriar: el frío apaga los sabores.",
      "Para un gazpacho sin gluten, quita el pan; queda más ligero pero igual de bueno."],
  v:"gazpacho andaluz receta"},
 en:{n:"Andalusian Gazpacho", b:"A cold soup of tomato, cucumber, pepper and olive oil, blended until silky. Summer in Andalusia.",
  st:["Soak the bread in the water for 5 minutes.",
      "Blend the tomato, cucumber, pepper, garlic and the bread with its water until smooth.",
      "With the motor running, drizzle in the oil, then the vinegar and salt.",
      "Strain it if you want it very fine.",
      "Refrigerate at least 2 hours and serve well chilled."],
  tp:["Taste and adjust the vinegar and salt after chilling: cold dulls flavour.",
      "For a gluten-free gazpacho, leave out the bread; it's lighter but just as good."],
  v:"gazpacho recipe"}},

{id:"salmorejo", c:"Spain", r:"mediterranean", m:"soup", t:20, s:4,
 i:[[1,"kg","tomato","structure","tomates maduros","ripe tomatoes","en trozos","in chunks"],
    [200,"g","bread","thicken","pan de miga densa del día anterior","day-old dense white bread","sin corteza","crusts removed"],
    [1,"clove","garlic","aromatic","ajo","garlic"],
    [150,"ml","oliveoil","fat","aceite de oliva virgen extra","extra virgin olive oil"],
    [1,"tsp","salt","salt","sal","salt"],
    [2,"","egg","garnish","huevos duros","hard-boiled eggs","picados","chopped"],
    [60,"g","prosciutto","garnish","jamón serrano","Spanish cured ham","en tiras","in strips"]],
 es:{n:"Salmorejo cordobés", b:"Crema fría y espesa de tomate, pan y aceite, con huevo duro y jamón. Más densa que el gazpacho.",
  st:["Licúa el tomate hasta que esté líquido y cuela para quitar pieles y semillas.",
      "Añade el pan y deja que se empape 10 minutos.",
      "Añade el ajo y la sal y licúa hasta que esté liso.",
      "Con el motor en marcha, añade el aceite en hilo hasta que emulsione y espese.",
      "Refrigera 2 horas. Sirve con el huevo y el jamón por encima y un hilo de aceite."],
  tp:["Debe quedar tan espeso que el huevo no se hunda.",
      "Usa el pan más denso que encuentres; el de molde lo deja pastoso."],
  v:"salmorejo cordobés receta"},
 en:{n:"Salmorejo (Cordoban Cold Tomato Cream)", b:"A thick cold cream of tomato, bread and olive oil, topped with egg and ham. Denser than gazpacho.",
  st:["Blend the tomato until liquid and strain to remove skins and seeds.",
      "Add the bread and let it soak 10 minutes.",
      "Add the garlic and salt and blend until smooth.",
      "With the motor running, drizzle in the oil until it emulsifies and thickens.",
      "Refrigerate 2 hours. Serve with the egg and ham on top and a thread of oil."],
  tp:["It should be thick enough that the egg doesn't sink.",
      "Use the densest bread you can find; sliced sandwich bread makes it pasty."],
  v:"salmorejo recipe"}},

{id:"pisto", c:"Spain", r:"mediterranean", m:"main", t:60, s:4,
 i:[[5,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [1,"","onion","aromatic","cebolla","onion","en dados","diced"],
    [1,"","bellpepper","structure","pimiento verde","green bell pepper","en dados","diced"],
    [1,"","bellpepper","structure","pimiento rojo","red bell pepper","en dados","diced"],
    [2,"","veg","structure","calabacines","courgettes (zucchini)","en dados","diced"],
    [600,"g","tomato","sauce","tomates maduros","ripe tomatoes","rallados","grated"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"pinch","sugar","sweet","azúcar","sugar"],
    [4,"","egg","protein","huevos","eggs"]],
 es:{n:"Pisto manchego", b:"Verduras de huerta pochadas despacio en aceite de oliva, con huevo frito encima. La ratatouille de La Mancha.",
  st:["Pocha la cebolla en el aceite a fuego bajo 10 minutos.",
      "Añade los pimientos y cuece 10 minutos.",
      "Añade el calabacín y cuece 10 minutos más.",
      "Añade el tomate, la sal y el azúcar y cuece 20 minutos a fuego bajo, hasta que no quede líquido.",
      "Fríe los huevos y sirve uno sobre cada ración de pisto."],
  tp:["El secreto es el fuego bajo y la paciencia: las verduras se confitan, no se fríen.",
      "El azúcar solo corrige la acidez del tomate; quítalo si el tomate es dulce."],
  v:"pisto manchego receta"},
 en:{n:"Pisto Manchego (Spanish Vegetable Stew)", b:"Garden vegetables cooked slowly in olive oil, with a fried egg on top. La Mancha's ratatouille.",
  st:["Cook the onion gently in the oil over low heat for 10 minutes.",
      "Add the peppers and cook 10 minutes.",
      "Add the courgette and cook 10 minutes more.",
      "Add the tomato, salt and sugar and cook 20 minutes on low, until no liquid remains.",
      "Fry the eggs and serve one on each portion."],
  tp:["The secret is low heat and patience: the vegetables should soften in the oil, not fry.",
      "The sugar only balances the tomato's acidity; leave it out if the tomatoes are sweet."],
  v:"pisto manchego recipe"}},

{id:"patatas-bravas", c:"Spain", r:"mediterranean", m:"starter", t:45, s:4,
 i:[[1,"kg","potato","structure","patatas harinosas","floury potatoes","en dados de 3 cm","in 3 cm cubes"],
    [1,"l","oil","fat","aceite para freír","oil for frying"],
    [2,"tsp","salt","salt","sal","salt"],
    [3,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [1,"tbsp","apflour","thicken","harina de trigo","plain flour"],
    [2,"tsp","paprika","aromatic","pimentón picante","hot smoked paprika"],
    [1,"tsp","paprika","aromatic","pimentón dulce","sweet paprika"],
    [300,"ml","water","liquid","agua","water"]],
 es:{n:"Patatas bravas", b:"Dados de patata fritos dos veces con salsa brava de pimentón picante. La tapa de todos los bares de Madrid.",
  st:["Fríe las patatas a 140 °C durante 10 minutos, hasta que estén tiernas. Escúrrelas.",
      "Para la salsa, calienta el aceite de oliva, añade la harina y cuece 1 minuto. Retira del fuego y añade los dos pimentones.",
      "Añade el agua poco a poco, batiendo, y 1 cucharadita de sal. Cuece 5 minutos hasta que espese.",
      "Sube el aceite a 190 °C y fríe las patatas otra vez 4 minutos, hasta que estén doradas y crujientes.",
      "Sala las patatas y sirve con la salsa brava por encima."],
  tp:["Añade el pimentón fuera del fuego: quemado amarga.",
      "Seca bien las patatas antes de freír para que crujan."],
  v:"patatas bravas receta salsa brava"},
 en:{n:"Patatas Bravas", b:"Twice-fried potato cubes with a hot paprika brava sauce. The tapa at every bar in Madrid.",
  st:["Fry the potatoes at 140 °C for 10 minutes, until tender. Drain.",
      "For the sauce, heat the olive oil, add the flour and cook 1 minute. Take off the heat and add both paprikas.",
      "Add the water a little at a time, whisking, and 1 teaspoon of salt. Cook 5 minutes until thick.",
      "Raise the oil to 190 °C and fry the potatoes again for 4 minutes, until golden and crisp.",
      "Salt the potatoes and serve with the brava sauce over the top."],
  tp:["Add the paprika off the heat: burnt, it turns bitter.",
      "Dry the potatoes well before frying so they crisp."],
  v:"patatas bravas recipe"}},

{id:"gambas-al-ajillo", c:"Spain", r:"mediterranean", m:"starter", t:15, s:4,
 i:[[500,"g","prawn","protein","gambas peladas","peeled prawns"],
    [150,"ml","oliveoil","fat","aceite de oliva","olive oil"],
    [6,"clove","garlic","aromatic","ajo","garlic","en láminas","sliced"],
    [2,"","chilli","aromatic","guindillas secas","dried chillies","en aros","in rings"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"handful","herb","garnish","perejil","parsley","picado","chopped"]],
 es:{n:"Gambas al ajillo", b:"Gambas en aceite de oliva hirviendo con ajo y guindilla, servidas en la cazuela de barro chisporroteando.",
  st:["Seca bien las gambas y sálalas.",
      "Calienta el aceite con el ajo y la guindilla a fuego medio en una cazuela de barro o sartén pequeña, hasta que el ajo empiece a dorarse.",
      "Añade las gambas y cuece 2 minutos, dándoles la vuelta a mitad, hasta que estén rosadas.",
      "Espolvorea el perejil.",
      "Sirve enseguida en la misma cazuela, todavía chisporroteando."],
  tp:["No dejes que el ajo se dore demasiado antes de las gambas; se quema mientras se cuecen.",
      "Las gambas pasadas se vuelven gomosas: sácalas en cuanto cambien de color."],
  v:"gambas al ajillo receta"},
 en:{n:"Gambas al Ajillo (Garlic Prawns)", b:"Prawns in sizzling olive oil with garlic and chilli, served bubbling in the clay dish.",
  st:["Pat the prawns very dry and salt them.",
      "Heat the oil with the garlic and chilli over medium heat in a clay dish or small frying pan, until the garlic begins to colour.",
      "Add the prawns and cook 2 minutes, turning halfway, until pink.",
      "Sprinkle with the parsley.",
      "Serve at once in the same dish, still sizzling."],
  tp:["Don't let the garlic brown too far before the prawns go in; it burns while they cook.",
      "Overcooked prawns turn rubbery: take them off as soon as they change colour."],
  v:"gambas al ajillo recipe"}},

{id:"pulpo-a-la-gallega", c:"Spain", r:"mediterranean", m:"starter", t:75, s:4,
 i:[[1.5,"kg","squid","protein","pulpo","octopus","congelado y descongelado","frozen and thawed"],
    [4,"l","water","liquid","agua","water"],
    [600,"g","potato","structure","patatas","potatoes","en rodajas de 2 cm","in 2 cm slices"],
    [2,"tsp","salt","salt","sal gruesa","coarse salt"],
    [2,"tsp","paprika","aromatic","pimentón dulce y picante","sweet and hot paprika"],
    [80,"ml","oliveoil","fat","aceite de oliva virgen extra","extra virgin olive oil"]],
 es:{n:"Pulpo a la gallega", b:"Pulpo tierno sobre patata cocida, con sal gruesa, pimentón y aceite. El plato de las ferias de Galicia.",
  st:["Hierve el agua. Sujeta el pulpo por la cabeza y sumérgelo 3 veces en el agua para que se ricen las patas, luego déjalo dentro.",
      "Cuece 40 minutos, hasta que un palillo entre sin resistencia en la parte gruesa de la pata.",
      "Apaga y deja el pulpo en el agua 10 minutos. Sácalo.",
      "Cuece las patatas en la misma agua 15 minutos.",
      "Corta el pulpo con tijeras en rodajas sobre las patatas. Cubre con la sal gruesa, el pimentón y el aceite."],
  tp:["Congelar el pulpo antes de cocerlo lo ablanda; el fresco hay que golpearlo.",
      "Se sirve templado, no caliente, sobre una tabla de madera."],
  v:"pulpo a la gallega receta"},
 en:{n:"Pulpo a la Gallega (Galician Octopus)", b:"Tender octopus on boiled potato, with coarse salt, paprika and olive oil. The dish of Galician fairs.",
  st:["Bring the water to a boil. Hold the octopus by the head and dip it 3 times so the tentacles curl, then leave it in.",
      "Cook 40 minutes, until a toothpick slides easily into the thick part of a tentacle.",
      "Turn off the heat and leave the octopus in the water for 10 minutes. Lift out.",
      "Cook the potatoes in the same water for 15 minutes.",
      "Snip the octopus into rounds over the potatoes. Top with the coarse salt, paprika and oil."],
  tp:["Freezing the octopus before cooking tenderises it; fresh octopus must be beaten.",
      "It is served warm, not hot, on a wooden board."],
  v:"pulpo a la gallega recipe"}},

{id:"crema-catalana", c:"Spain", r:"mediterranean", m:"sweet", t:30, s:6,
 i:[[500,"ml","milk","liquid","leche","milk"],
    [1,"","citrus","aromatic","cáscara de limón","lemon peel","en una tira","in one strip"],
    [1,"","spice","aromatic","rama de canela","cinnamon stick"],
    [5,"","eggyolk","set","yemas de huevo","egg yolks"],
    [100,"g","sugar","sweet","azúcar","sugar"],
    [20,"g","cornstarch","thicken","fécula de maíz","cornstarch"],
    [60,"g","sugar","caramel","azúcar para quemar","sugar for burning"]],
 es:{n:"Crema catalana", b:"Natilla de limón y canela con una capa de azúcar quemado que cruje bajo la cuchara.",
  st:["Calienta 400 ml de la leche con la cáscara de limón y la canela hasta que hierva. Tapa y deja infusionar 15 minutos.",
      "Bate las yemas con 100 g de azúcar y la fécula disuelta en el resto de la leche.",
      "Cuela la leche caliente sobre las yemas, batiendo. Vuelve a la olla y cuece a fuego bajo, sin dejar de remover, hasta que espese, sin que hierva.",
      "Reparte en 6 cazuelitas y refrigera al menos 3 horas.",
      "Justo antes de servir, espolvorea el resto del azúcar y quémalo con un soplete o una plancha de hierro caliente."],
  tp:["Quema el azúcar en el último momento; si espera, la capa se ablanda con la humedad.",
      "Si se corta la crema, bátela en caliente con la batidora de mano."],
  v:"crema catalana receta"},
 en:{n:"Crema Catalana", b:"A lemon and cinnamon custard with a burnt-sugar top that cracks under the spoon.",
  st:["Heat 400 ml of the milk with the lemon peel and cinnamon until boiling. Cover and infuse 15 minutes.",
      "Whisk the yolks with 100 g of sugar and the cornstarch dissolved in the rest of the milk.",
      "Strain the hot milk onto the yolks, whisking. Return to the pot and cook over low heat, stirring constantly, until thick, without boiling.",
      "Divide between 6 shallow dishes and refrigerate at least 3 hours.",
      "Just before serving, sprinkle over the rest of the sugar and burn it with a blowtorch or a hot iron."],
  tp:["Burn the sugar at the last moment; if it waits, moisture softens the crust.",
      "If the custard splits, blitz it while hot with a stick blender."],
  v:"crema catalana recipe"}},

{id:"torrijas", c:"Spain", r:"mediterranean", m:"sweet", t:40, s:6,
 i:[[1,"","bread","structure","barra de pan del día anterior","day-old baguette","en rebanadas de 2 cm","in 2 cm slices"],
    [750,"ml","milk","liquid","leche","milk"],
    [80,"g","sugar","sweet","azúcar","sugar"],
    [1,"","spice","aromatic","rama de canela","cinnamon stick"],
    [1,"","citrus","aromatic","cáscara de limón","lemon peel","en una tira","in one strip"],
    [3,"","egg","binder","huevos batidos","beaten eggs"],
    [500,"ml","oliveoil","fat","aceite de oliva suave para freír","light olive oil for frying"],
    [100,"g","sugar","garnish","azúcar para rebozar","sugar for coating"],
    [2,"tsp","spice","garnish","canela molida","ground cinnamon"]],
 es:{n:"Torrijas", b:"Pan empapado en leche con canela y limón, pasado por huevo y frito. El dulce de Semana Santa en España.",
  st:["Calienta la leche con 80 g de azúcar, la canela y el limón hasta que hierva. Deja infusionar y templar 15 minutos.",
      "Coloca el pan en una fuente y vierte la leche colada por encima. Deja empapar 10 minutos, dándoles la vuelta.",
      "Mezcla el azúcar de rebozar con la canela molida.",
      "Pasa cada rebanada por el huevo y fríe en el aceite a 170 °C durante 2 minutos por lado, hasta que esté dorada.",
      "Escurre sobre papel y reboza en el azúcar con canela mientras están calientes."],
  tp:["El pan debe ser del día anterior: el fresco se deshace en la leche.",
      "Sácalas de la leche con una espumadera para que no se rompan."],
  v:"torrijas receta tradicional"},
 en:{n:"Torrijas (Spanish French Toast)", b:"Bread soaked in cinnamon and lemon milk, dipped in egg and fried. Spain's Holy Week sweet.",
  st:["Heat the milk with 80 g of sugar, the cinnamon and lemon until boiling. Leave to infuse and cool 15 minutes.",
      "Lay the bread in a dish and strain the milk over it. Soak 10 minutes, turning.",
      "Mix the coating sugar with the ground cinnamon.",
      "Dip each slice in the egg and fry in the oil at 170 °C for 2 minutes a side, until golden.",
      "Drain on paper and roll in the cinnamon sugar while hot."],
  tp:["The bread must be a day old: fresh bread falls apart in the milk.",
      "Lift them out of the milk with a slotted spoon so they don't break."],
  v:"torrijas recipe"}},

{id:"lentejas-con-chorizo", c:"Spain", r:"mediterranean", m:"soup", t:60, s:6,
 i:[[400,"g","legume","protein","lentejas pardinas","pardina lentils"],
    [150,"g","chorizo","protein","chorizo","chorizo","en rodajas","sliced"],
    [3,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"","bellpepper","aromatic","pimiento verde","green bell pepper","picado","chopped"],
    [2,"","veg","structure","zanahorias","carrots","en rodajas","sliced"],
    [2,"","potato","structure","patatas","potatoes","en trozos","in chunks"],
    [1,"tsp","paprika","aromatic","pimentón dulce","sweet paprika"],
    [1,"leaf","herb","aromatic","hoja de laurel","bay leaf"],
    [1.5,"l","water","liquid","agua","water"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Lentejas con chorizo", b:"Lentejas guisadas con chorizo, patata y verduras. Comida de cuchara de toda la vida.",
  st:["Sofríe la cebolla, el ajo y el pimiento en el aceite 8 minutos.",
      "Añade el chorizo y cuece 2 minutos. Retira del fuego y añade el pimentón.",
      "Añade las lentejas, la zanahoria, el laurel y el agua. Hierve y cuece a fuego bajo 25 minutos.",
      "Añade la patata y la sal y cuece 20 minutos más, hasta que la patata esté tierna.",
      "Deja reposar 5 minutos antes de servir."],
  tp:["Las pardinas no necesitan remojo y no se deshacen.",
      "Rompe la patata con el cuchillo en lugar de cortarla: suelta almidón y espesa el guiso."],
  v:"lentejas con chorizo receta"},
 en:{n:"Lentejas con Chorizo (Lentil and Chorizo Stew)", b:"Lentils stewed with chorizo, potato and vegetables. Everyday Spanish spoon food.",
  st:["Cook the onion, garlic and pepper in the oil for 8 minutes.",
      "Add the chorizo and cook 2 minutes. Take off the heat and add the paprika.",
      "Add the lentils, carrot, bay and water. Bring to a boil and simmer 25 minutes.",
      "Add the potato and salt and cook 20 minutes more, until the potato is tender.",
      "Rest 5 minutes before serving."],
  tp:["Pardina lentils need no soaking and hold their shape.",
      "Snap the potato with the knife instead of cutting cleanly: it releases starch and thickens the stew."],
  v:"spanish lentils with chorizo recipe"}},

{id:"tarta-de-santiago", c:"Spain", r:"mediterranean", m:"sweet", t:50, s:10, o:180,
 i:[[250,"g","almondflour","structure","almendra molida","ground almonds"],
    [250,"g","sugar","sweet","azúcar","sugar"],
    [4,"","egg","binder","huevos","eggs"],
    [1,"","citrus","aromatic","ralladura de limón","lemon zest"],
    [1,"tsp","spice","aromatic","canela molida","ground cinnamon"],
    [2,"tbsp","icingsugar","garnish","azúcar glas","icing sugar"]],
 es:{n:"Tarta de Santiago", b:"Tarta húmeda de almendra, sin harina, con la cruz de Santiago dibujada en azúcar glas. Dulce de Galicia.",
  st:["Bate los huevos con el azúcar 3 minutos, hasta que blanqueen.",
      "Añade la almendra, la ralladura y la canela y mezcla con espátula.",
      "Vierte en un molde de 24 cm engrasado y forrado.",
      "Hornea a 180 °C durante 35 minutos, hasta que esté dorada y firme.",
      "Enfría, pon una plantilla de la cruz de Santiago en el centro y espolvorea el azúcar glas."],
  tp:["Sin harina de trigo por naturaleza; revisa que la almendra molida no se procese junto a trigo si cocinas para celíacos.",
      "Mejora al día siguiente, más húmeda."],
  v:"tarta de santiago receta"},
 en:{n:"Tarta de Santiago (Galician Almond Cake)", b:"A moist, flourless almond cake with the cross of Saint James stencilled in icing sugar. A sweet from Galicia.",
  st:["Whisk the eggs with the sugar for 3 minutes, until pale.",
      "Add the almonds, zest and cinnamon and fold with a spatula.",
      "Pour into a greased and lined 24 cm tin.",
      "Bake at 180 °C for 35 minutes, until golden and firm.",
      "Cool, place a Saint James cross stencil in the centre and dust with the icing sugar."],
  tp:["Naturally free of wheat flour; check the ground almonds aren't processed alongside wheat if cooking for coeliacs.",
      "It improves the next day, becoming moister."],
  v:"tarta de santiago recipe"}}
];
