module.exports = [
{id:"croquetas-de-jamon", c:"Spain", r:"mediterranean", m:"starter", t:240, s:30,
 i:[[80,"g","butter","fat","mantequilla","butter"],
    [3,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [100,"g","apflour","thicken","harina de trigo","plain flour"],
    [750,"ml","milk","liquid","leche entera","whole milk"],
    [150,"g","prosciutto","protein","jamón serrano","Spanish cured ham","picado muy fino","very finely chopped"],
    [1,"pinch","spice","aromatic","nuez moscada","nutmeg"],
    [2,"","egg","binder","huevos batidos","beaten eggs"],
    [150,"g","breadcrumbs","dredge","pan rallado","breadcrumbs"],
    [1,"l","oliveoil","fat","aceite de oliva suave para freír","light olive oil for frying"]],
 es:{n:"Croquetas de jamón", b:"Croquetas de bechamel cremosísima con jamón serrano, crujientes por fuera. La tapa de las abuelas españolas.",
  st:["Derrite la mantequilla con el aceite y sofríe el jamón 1 minuto. Añade la harina y cuece 3 minutos.",
      "Añade la leche caliente poco a poco, batiendo, y cuece 12 minutos a fuego bajo sin parar de remover, hasta que la masa se despegue.",
      "Añade la nuez moscada, extiende en una fuente, tapa con film en contacto y refrigera 4 horas.",
      "Forma croquetas, pásalas por el huevo y el pan rallado.",
      "Fríe a 180 °C en tandas 2 minutos, hasta que estén doradas."],
  tp:["No añadas sal hasta probar: el jamón ya sala la masa.",
      "El film en contacto evita que se forme costra."],
  v:"croquetas de jamón caseras"},
 en:{n:"Spanish Ham Croquetas", b:"Croquettes of ultra-creamy béchamel with cured ham, crisp outside. Grandma's tapa in Spain.",
  st:["Melt the butter with the oil and fry the ham 1 minute. Add the flour and cook 3 minutes.",
      "Add the hot milk gradually, whisking, and cook 12 minutes on low, stirring constantly, until the mixture pulls away.",
      "Add the nutmeg, spread in a dish, press cling film onto the surface and chill 4 hours.",
      "Shape croquettes, dip in the egg and the breadcrumbs.",
      "Fry at 180 °C in batches for 2 minutes, until golden."],
  tp:["Don't salt until you taste: the ham already seasons it.",
      "Film pressed on the surface stops a skin forming."],
  v:"spanish ham croquettes recipe"}},

{id:"albondigas-en-salsa", c:"Spain", r:"mediterranean", m:"main", t:60, s:4,
 i:[[250,"g","beef","protein","carne picada de res","minced beef"],
    [250,"g","porkmince","protein","carne picada de cerdo","minced pork"],
    [1,"","egg","binder","huevo","egg"],
    [40,"g","bread","binder","miga de pan","bread crumb (soft)","remojada en leche","soaked in milk"],
    [50,"ml","milk","moisture","leche","milk"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"handful","herb","aromatic","perejil","parsley","picado","chopped"],
    [1,"tsp","salt","salt","sal","salt"],
    [60,"g","apflour","dredge","harina de trigo","plain flour"],
    [4,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","veg","aromatic","zanahoria","carrot","picada","chopped"],
    [150,"ml","winewhite","liquid","vino blanco","white wine"],
    [300,"ml","water","liquid","agua","water"],
    [1,"pinch","spice","aromatic","azafrán","saffron"]],
 es:{n:"Albóndigas en salsa", b:"Albóndigas tiernas en una salsa de cebolla, zanahoria y vino blanco. Comida de casa en toda España.",
  st:["Mezcla la carne, el huevo, la miga remojada, el ajo, el perejil y la sal. Forma bolas de 3 cm y pásalas por la harina.",
      "Dóralas en el aceite 5 minutos. Sácalas.",
      "Sofríe la cebolla y la zanahoria en el mismo aceite 10 minutos.",
      "Añade el vino, el agua y el azafrán, cuece 5 minutos y tritura la salsa.",
      "Vuelve a poner las albóndigas en la salsa y cuece 20 minutos a fuego bajo."],
  tp:["Humedece las manos para formar las bolas sin que se peguen.",
      "Con patatas fritas en dados al lado quedan perfectas."],
  v:"albóndigas en salsa española"},
 en:{n:"Albóndigas en Salsa (Spanish Meatballs)", b:"Tender meatballs in an onion, carrot and white wine sauce. Home cooking all over Spain.",
  st:["Mix the meat, egg, soaked bread, garlic, parsley and salt. Shape 3 cm balls and dredge in the flour.",
      "Brown them in the oil for 5 minutes. Remove.",
      "Cook the onion and carrot in the same oil for 10 minutes.",
      "Add the wine, water and saffron, cook 5 minutes and blend the sauce.",
      "Return the meatballs to the sauce and simmer 20 minutes on low."],
  tp:["Wet your hands to shape the balls without sticking.",
      "Diced fried potatoes on the side make them perfect."],
  v:"spanish meatballs in sauce recipe"}},

{id:"arroz-negro", c:"Spain", r:"mediterranean", m:"main", t:50, s:4,
 i:[[4,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [500,"g","squid","protein","sepia o calamar","cuttlefish or squid","en dados","diced"],
    [1,"","onion","aromatic","cebolla","onion","picada fina","finely chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"","tomato","sauce","tomate","tomato","rallado","grated"],
    [320,"g","rice","structure","arroz bomba o redondo","bomba or short-grain rice"],
    [8,"g","squid","umami","tinta de sepia o calamar","cuttlefish or squid ink"],
    [1,"l","fishstock","liquid","caldo de pescado caliente","hot fish stock"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Arroz negro", b:"Arroz seco teñido con tinta de sepia, con sus trozos tiernos. Se sirve con alioli en la costa mediterránea.",
  st:["Dora la sepia en el aceite 5 minutos en una paellera.",
      "Añade la cebolla y el ajo y cuece 8 minutos. Añade el tomate y cuece 5 minutos.",
      "Añade el arroz y remueve 2 minutos.",
      "Disuelve la tinta en el caldo caliente, añádelo con la sal y cuece 18 minutos sin remover.",
      "Deja reposar 5 minutos tapado con un paño."],
  tp:["No remuevas después de añadir el caldo: así se forma el socarrat.",
      "Si usas tinta en sobres, 2 sobres equivalen a unos 8 g."],
  v:"arroz negro receta"},
 en:{n:"Arroz Negro (Black Squid Ink Rice)", b:"Dry rice stained black with cuttlefish ink, with tender pieces of it. Served with alioli on the Mediterranean coast.",
  st:["Brown the cuttlefish in the oil for 5 minutes in a paella pan.",
      "Add the onion and garlic and cook 8 minutes. Add the tomato and cook 5 minutes.",
      "Add the rice and stir 2 minutes.",
      "Dissolve the ink in the hot stock, add with the salt and cook 18 minutes without stirring.",
      "Rest 5 minutes covered with a cloth."],
  tp:["Don't stir after the stock goes in: that's how the socarrat crust forms.",
      "If using ink sachets, 2 sachets are about 8 g."],
  v:"arroz negro recipe"}},

{id:"fideua", c:"Spain", r:"mediterranean", m:"main", t:45, s:4,
 i:[[4,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [300,"g","pasta","structure","fideos gruesos de fideuá","short thick fideuà noodles"],
    [300,"g","squid","protein","sepia o calamar","cuttlefish or squid","en dados","diced"],
    [300,"g","prawn","protein","gambas","prawns","peladas","peeled"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"","tomato","sauce","tomate","tomato","rallado","grated"],
    [1,"tsp","paprika","aromatic","pimentón dulce","sweet paprika"],
    [1,"pinch","spice","aromatic","azafrán","saffron"],
    [900,"ml","fishstock","liquid","caldo de pescado caliente","hot fish stock"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Fideuá", b:"La prima de la paella hecha con fideos cortos tostados y marisco. Nació en Gandía, Valencia.",
  st:["Tuesta los fideos en el aceite 4 minutos, removiendo, hasta que estén dorados. Sácalos.",
      "Dora la sepia 4 minutos en el mismo aceite. Añade el ajo, el tomate y el pimentón y cuece 4 minutos.",
      "Añade los fideos, el caldo, el azafrán y la sal. Cuece 8 minutos.",
      "Añade las gambas y cuece 4 minutos más, hasta que el caldo se absorba.",
      "Deja reposar 3 minutos; los fideos se levantan de punta."],
  tp:["Tostar los fideos antes evita que se pasen.",
      "Para que se levanten, mete la paellera 2 minutos bajo el grill al final."],
  v:"fideuá receta"},
 en:{n:"Fideuà (Seafood Noodle Paella)", b:"Paella's cousin made with short toasted noodles and seafood. Born in Gandía, Valencia.",
  st:["Toast the noodles in the oil for 4 minutes, stirring, until golden. Remove.",
      "Brown the cuttlefish 4 minutes in the same oil. Add the garlic, tomato and paprika and cook 4 minutes.",
      "Add the noodles, stock, saffron and salt. Cook 8 minutes.",
      "Add the prawns and cook 4 minutes more, until the stock is absorbed.",
      "Rest 3 minutes; the noodles curl upward."],
  tp:["Toasting the noodles first stops them going soft.",
      "To make them stand up, put the pan under the grill for 2 minutes at the end."],
  v:"fideua recipe"}},

{id:"escalivada", c:"Spain", r:"mediterranean", m:"side", t:70, s:4, o:200,
 i:[[2,"","eggplant","structure","berenjenas","aubergines"],
    [2,"","bellpepper","structure","pimientos rojos","red bell peppers"],
    [2,"","onion","structure","cebollas","onions"],
    [80,"ml","oliveoil","fat","aceite de oliva virgen extra","extra virgin olive oil"],
    [1,"tsp","salt","salt","sal en escamas","flaky salt"],
    [1,"clove","garlic","aromatic","ajo","garlic","picado fino","finely chopped"]],
 es:{n:"Escalivada", b:"Berenjena, pimiento y cebolla asados enteros, pelados en tiras y aliñados con aceite. De Cataluña.",
  st:["Pinta las verduras enteras con un poco del aceite.",
      "Ásalas a 200 °C: los pimientos y las berenjenas 45 minutos, las cebollas 60 minutos, girándolas a mitad.",
      "Tapa en un bol 15 minutos para que suden.",
      "Pela y corta en tiras.",
      "Aliña con el resto del aceite, la sal y el ajo."],
  tp:["Asadas a la brasa quedan con más sabor ahumado.",
      "Se come tibia o fría, sobre pan tostado o como guarnición."],
  v:"escalivada catalana receta"},
 en:{n:"Escalivada (Catalan Roast Vegetables)", b:"Aubergine, pepper and onion roasted whole, peeled into strips and dressed with oil. From Catalonia.",
  st:["Brush the whole vegetables with a little of the oil.",
      "Roast at 200 °C: peppers and aubergines 45 minutes, onions 60 minutes, turning halfway.",
      "Cover in a bowl for 15 minutes to steam.",
      "Peel and cut into strips.",
      "Dress with the rest of the oil, the salt and the garlic."],
  tp:["Roasted over embers they taste smokier.",
      "Eat warm or cold, on toast or as a side."],
  v:"escalivada recipe"}},

{id:"pan-con-tomate", c:"Spain", r:"mediterranean", m:"breakfast", t:10, s:4,
 i:[[4,"","bread","structure","rebanadas gruesas de pan de payés","thick slices of rustic bread"],
    [2,"","tomato","structure","tomates maduros","ripe tomatoes","en mitades","halved"],
    [1,"clove","garlic","aromatic","ajo","garlic","pelado","peeled"],
    [4,"tbsp","oliveoil","fat","aceite de oliva virgen extra","extra virgin olive oil"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Pan con tomate", b:"Pan tostado frotado con ajo y tomate maduro, con aceite y sal. Pa amb tomàquet, el desayuno catalán.",
  st:["Tuesta el pan.",
      "Frota el ajo sobre el pan caliente, con suavidad.",
      "Frota el tomate cortado hasta que solo quede la piel.",
      "Riega con el aceite.",
      "Sala y sirve."],
  tp:["Usa los tomates más maduros: los de colgar son los tradicionales.",
      "El ajo es opcional en muchas casas catalanas."],
  v:"pan con tomate receta"},
 en:{n:"Pan con Tomate (Catalan Tomato Bread)", b:"Toasted bread rubbed with garlic and ripe tomato, with oil and salt. Pa amb tomàquet, the Catalan breakfast.",
  st:["Toast the bread.",
      "Rub the garlic gently over the hot bread.",
      "Rub the cut tomato over it until only the skin remains.",
      "Drizzle with the oil.",
      "Salt and serve."],
  tp:["Use the ripest tomatoes: hanging tomatoes are traditional.",
      "Garlic is optional in many Catalan homes."],
  v:"pan con tomate recipe"}},

{id:"sopa-de-ajo", c:"Spain", r:"mediterranean", m:"soup", t:30, s:4,
 i:[[5,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [8,"clove","garlic","aromatic","ajo","garlic","en láminas","sliced"],
    [150,"g","bread","structure","pan del día anterior","day-old bread","en rebanadas finas","thinly sliced"],
    [2,"tsp","paprika","aromatic","pimentón de la Vera","smoked paprika"],
    [1.2,"l","water","liquid","agua caliente","hot water"],
    [1,"tsp","salt","salt","sal","salt"],
    [4,"","egg","protein","huevos","eggs"],
    [60,"g","prosciutto","protein","jamón serrano","Spanish cured ham","en dados","diced"]],
 es:{n:"Sopa de ajo castellana", b:"Sopa de pan, ajo y pimentón con huevo escalfado y jamón. Humilde y reconfortante, de Castilla.",
  st:["Dora el ajo en el aceite a fuego bajo 3 minutos. Añade el jamón y el pan y cuece 3 minutos.",
      "Retira del fuego y añade el pimentón.",
      "Añade el agua caliente y la sal y cuece 15 minutos.",
      "Casca los huevos en la sopa y escálfalos 4 minutos.",
      "Sirve en cazuelas de barro."],
  tp:["Retira del fuego antes del pimentón: se quema en segundos.",
      "Tradicionalmente se termina en el horno en cazuelitas individuales."],
  v:"sopa de ajo castellana"},
 en:{n:"Sopa de Ajo (Castilian Garlic Soup)", b:"A soup of bread, garlic and paprika with poached egg and ham. Humble and comforting, from Castile.",
  st:["Gently brown the garlic in the oil for 3 minutes. Add the ham and bread and cook 3 minutes.",
      "Take off the heat and add the paprika.",
      "Add the hot water and salt and cook 15 minutes.",
      "Crack the eggs into the soup and poach 4 minutes.",
      "Serve in clay bowls."],
  tp:["Take it off the heat before the paprika: it burns in seconds.",
      "Traditionally it's finished in the oven in individual dishes."],
  v:"castilian garlic soup recipe"}},

{id:"ensaladilla-rusa", c:"Spain", r:"mediterranean", m:"starter", t:40, s:6,
 i:[[800,"g","potato","structure","patatas","potatoes","peladas, en dados","peeled, diced"],
    [2,"","veg","structure","zanahorias","carrots","en dados","diced"],
    [100,"g","legume","structure","guisantes","peas"],
    [3,"","egg","protein","huevos duros","hard-boiled eggs","picados","chopped"],
    [200,"g","tuna","protein","atún en aceite","tuna in oil","escurrido","drained"],
    [60,"g","olives","umami","aceitunas verdes","green olives","en rodajas","sliced"],
    [250,"g","mayo","binder","mayonesa","mayonnaise"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Ensaladilla rusa", b:"Patata, zanahoria, guisantes, huevo y atún con mayonesa. La tapa fría de todos los bares de España.",
  st:["Cuece la patata y la zanahoria en agua con sal 12 minutos. Añade los guisantes el último minuto.",
      "Escurre y enfría por completo.",
      "Mezcla con el huevo, el atún y las aceitunas.",
      "Añade la mayonesa y la sal y mezcla.",
      "Refrigera 1 hora. Cubre con un poco más de mayonesa si quieres."],
  tp:["Las verduras deben estar frías antes de la mayonesa.",
      "Mejor al día siguiente."],
  v:"ensaladilla rusa receta"},
 en:{n:"Ensaladilla Rusa (Spanish Potato Salad)", b:"Potato, carrot, peas, egg and tuna in mayonnaise. The cold tapa in every bar in Spain.",
  st:["Boil the potato and carrot in salted water for 12 minutes. Add the peas for the last minute.",
      "Drain and cool completely.",
      "Mix with the egg, tuna and olives.",
      "Add the mayonnaise and salt and fold together.",
      "Chill 1 hour. Top with a little more mayonnaise if you like."],
  tp:["The vegetables must be cold before the mayonnaise goes in.",
      "Better the next day."],
  v:"spanish potato salad recipe"}},

{id:"natillas", c:"Spain", r:"mediterranean", m:"sweet", t:30, s:6,
 i:[[750,"ml","milk","liquid","leche","milk"],
    [1,"","citrus","aromatic","cáscara de limón","lemon peel"],
    [1,"","spice","aromatic","rama de canela","cinnamon stick"],
    [5,"","eggyolk","set","yemas de huevo","egg yolks"],
    [120,"g","sugar","sweet","azúcar","sugar"],
    [20,"g","cornstarch","thicken","fécula de maíz","cornstarch"],
    [6,"","wafer","garnish","galletas María","Marie biscuits"],
    [1,"tsp","spice","garnish","canela molida","ground cinnamon"]],
 es:{n:"Natillas con galleta", b:"Crema de huevo y leche con limón y canela, con una galleta María encima. El postre de las casas españolas.",
  st:["Calienta 600 ml de la leche con el limón y la canela. Deja infusionar 10 minutos.",
      "Bate las yemas con el azúcar y la fécula disuelta en el resto de la leche.",
      "Cuela la leche caliente sobre las yemas, batiendo, y vuelve a la olla.",
      "Cuece a fuego bajo sin parar de remover 8 minutos, hasta que cubra la cuchara, sin hervir.",
      "Reparte en cuencos, pon una galleta encima y espolvorea canela. Refrigera 2 horas."],
  tp:["Si se corta, pásala por la batidora en caliente.",
      "La galleta se ablanda con la crema; ponla justo antes de enfriar."],
  v:"natillas caseras con galleta"},
 en:{n:"Natillas (Spanish Custard)", b:"A lemon and cinnamon egg custard with a Marie biscuit on top. The dessert of Spanish homes.",
  st:["Heat 600 ml of the milk with the lemon and cinnamon. Infuse 10 minutes.",
      "Whisk the yolks with the sugar and the cornstarch dissolved in the rest of the milk.",
      "Strain the hot milk onto the yolks, whisking, and return to the pot.",
      "Cook on low, stirring constantly, for 8 minutes, until it coats the spoon, without boiling.",
      "Divide into bowls, top each with a biscuit and dust with cinnamon. Chill 2 hours."],
  tp:["If it splits, blitz it while hot with a blender.",
      "The biscuit softens in the custard; add it just before chilling."],
  v:"natillas recipe"}},

{id:"magdalenas", c:"Spain", r:"mediterranean", m:"sweet", t:90, s:12, o:220,
 i:[[3,"","egg","aerate","huevos","eggs"],
    [150,"g","sugar","sweet","azúcar","sugar"],
    [150,"ml","oil","fat","aceite de girasol u oliva suave","sunflower or light olive oil"],
    [100,"ml","milk","liquid","leche","milk"],
    [1,"","citrus","aromatic","ralladura de limón","lemon zest"],
    [200,"g","apflour","structure","harina de trigo","plain flour"],
    [2,"tsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [2,"tbsp","sugar","garnish","azúcar para espolvorear","sugar for sprinkling"]],
 es:{n:"Magdalenas", b:"Bizcochitos de limón con copete alto y azúcar crujiente arriba. El desayuno de las panaderías españolas.",
  st:["Bate los huevos con el azúcar 5 minutos, hasta que blanqueen.",
      "Añade el aceite, la leche y la ralladura y mezcla.",
      "Añade la harina y el polvo de hornear y mezcla solo hasta integrar. Refrigera 1 hora.",
      "Llena cápsulas de papel hasta tres cuartos y espolvorea el azúcar.",
      "Hornea a 220 °C durante 15 minutos, hasta que suban y doren."],
  tp:["El contraste de masa fría y horno caliente forma el copete.",
      "No abras el horno los primeros 10 minutos."],
  v:"magdalenas caseras receta"},
 en:{n:"Magdalenas (Spanish Lemon Muffins)", b:"Lemon sponge cakes with a tall domed top and crunchy sugar. The breakfast of Spanish bakeries.",
  st:["Whisk the eggs with the sugar for 5 minutes, until pale.",
      "Add the oil, milk and zest and mix.",
      "Add the flour and baking powder and mix just until combined. Chill 1 hour.",
      "Fill paper cases three-quarters full and sprinkle with the sugar.",
      "Bake at 220 °C for 15 minutes, until risen and golden."],
  tp:["Cold batter in a hot oven forms the dome.",
      "Don't open the oven for the first 10 minutes."],
  v:"magdalenas recipe"}}
];
