module.exports = [
{id:"migas", c:"Spain", r:"mediterranean", m:"main", t:40, s:4,
 i:[[400,"g","bread","structure","pan del día anterior","day-old bread","en dados pequeños","in small dice"],
    [150,"ml","water","liquid","agua","water"],
    [1,"tsp","salt","salt","sal","salt"],
    [6,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [6,"clove","garlic","aromatic","ajo","garlic","con piel, aplastados","unpeeled, crushed"],
    [150,"g","chorizo","protein","chorizo","chorizo","en rodajas","sliced"],
    [150,"g","pancetta","protein","panceta","pancetta","en dados","diced"],
    [1,"tsp","paprika","aromatic","pimentón dulce","sweet paprika"]],
 es:{n:"Migas", b:"Pan del día anterior salteado despacio con ajo, chorizo y panceta. Comida de pastores de Extremadura y La Mancha.",
  st:["Humedece el pan con el agua y la sal, tapa con un paño y deja reposar toda la noche.",
      "Fríe los ajos en el aceite 3 minutos. Añade el chorizo y la panceta y cocina 5 minutos. Sácalos.",
      "Añade el pan y el pimentón al aceite y remueve sin parar a fuego medio 20 minutos, hasta que las migas estén sueltas y doradas.",
      "Vuelve a poner el chorizo, la panceta y los ajos y mezcla."],
  tp:["Remueve y corta con la espumadera sin parar: es el secreto de unas buenas migas.",
      "El pan debe estar húmedo pero no empapado."],
  v:"migas extremeñas"},
 en:{n:"Migas (Spanish Fried Breadcrumbs)", b:"Day-old bread fried slowly with garlic, chorizo and pancetta. Shepherds' food from Extremadura and La Mancha.",
  st:["Dampen the bread with the water and salt, cover with a cloth and leave overnight.",
      "Fry the garlic in the oil for 3 minutes. Add the chorizo and pancetta and cook 5 minutes. Lift out.",
      "Add the bread and paprika to the oil and stir constantly over medium heat for 20 minutes, until loose and golden.",
      "Return the chorizo, pancetta and garlic and mix."],
  tp:["Keep stirring and chopping with the spatula: that's the secret to good migas.",
      "The bread should be damp, not soaked."],
  v:"spanish migas"}},

{id:"porrusalda", c:"Spain", r:"mediterranean", m:"soup", t:45, s:4,
 i:[[4,"","leek","structure","puerros","leeks","en rodajas","sliced"],
    [4,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [2,"clove","garlic","aromatic","ajo","garlic","laminado","sliced"],
    [2,"","veg","structure","zanahorias","carrots","en rodajas","sliced"],
    [4,"","potato","structure","patatas","potatoes","chascadas","broken into chunks"],
    [1.5,"l","water","liquid","agua","water"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Porrusalda", b:"Sopa vasca humilde de puerro, patata y zanahoria. Consuelo de invierno en Euskadi.",
  st:["Sofríe el ajo en el aceite 1 minuto. Añade el puerro y cocina 8 minutos a fuego bajo.",
      "Añade la zanahoria y la patata y remueve 2 minutos.",
      "Añade el agua y la sal y cuece 25 minutos, hasta que la patata esté tierna.",
      "Deja reposar 5 minutos antes de servir."],
  tp:["Chascar la patata, rompiéndola con el cuchillo, suelta almidón y espesa el caldo.",
      "Con un buen aceite de oliva no necesita nada más."],
  v:"porrusalda vasca"},
 en:{n:"Porrusalda (Basque Leek and Potato Soup)", b:"A humble Basque soup of leek, potato and carrot. Winter comfort in the Basque Country.",
  st:["Fry the garlic in the oil for 1 minute. Add the leek and cook 8 minutes on low.",
      "Add the carrot and potato and stir 2 minutes.",
      "Add the water and salt and simmer 25 minutes, until the potato is tender.",
      "Rest 5 minutes before serving."],
  tp:["Snapping the potato into chunks, rather than slicing, releases starch that thickens the broth.",
      "With good olive oil it needs nothing else."],
  v:"basque porrusalda"}},

{id:"ajoblanco", c:"Spain", r:"mediterranean", m:"soup", t:20, s:4,
 i:[[200,"g","almond","structure","almendras crudas peladas","blanched almonds"],
    [100,"g","bread","thicken","miga de pan del día anterior","day-old bread, crusts off"],
    [2,"clove","garlic","aromatic","ajo","garlic"],
    [100,"ml","oliveoil","fat","aceite de oliva virgen extra","extra virgin olive oil"],
    [2,"tbsp","winevinegar","acid","vinagre de Jerez","sherry vinegar"],
    [750,"ml","water","liquid","agua muy fría","ice-cold water"],
    [1,"tsp","salt","salt","sal","salt"],
    [150,"g","fruit","garnish","uvas blancas","white grapes"]],
 es:{n:"Ajoblanco", b:"Sopa fría de almendra, ajo y aceite de oliva, servida con uvas. La prima blanca del gazpacho, de Málaga.",
  st:["Remoja el pan en un poco del agua 5 minutos.",
      "Tritura las almendras, el ajo, el pan y la sal con la mitad del agua hasta que esté muy fino.",
      "Añade el aceite en hilo sin dejar de triturar, y luego el vinagre.",
      "Añade el resto del agua y refrigera 2 horas.",
      "Sirve muy frío con las uvas."],
  tp:["Cuélalo si quieres una textura más sedosa.",
      "Usa medio diente de ajo si lo quieres más suave."],
  v:"ajoblanco malagueño"},
 en:{n:"Ajoblanco (Chilled Almond Garlic Soup)", b:"A cold soup of almonds, garlic and olive oil, served with grapes. Gazpacho's white cousin, from Málaga.",
  st:["Soak the bread in a little of the water for 5 minutes.",
      "Blend the almonds, garlic, bread and salt with half the water until very smooth.",
      "Pour in the oil in a thin stream while blending, then the vinegar.",
      "Add the rest of the water and chill 2 hours.",
      "Serve very cold with the grapes."],
  tp:["Strain it for a silkier texture.",
      "Use half a garlic clove for a milder soup."],
  v:"spanish ajoblanco"}},

{id:"piperrada", c:"Spain", r:"mediterranean", m:"main", t:40, s:4,
 i:[[5,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [2,"","onion","aromatic","cebollas","onions","en tiras","in strips"],
    [3,"clove","garlic","aromatic","ajo","garlic","laminado","sliced"],
    [2,"","bellpepper","structure","pimientos rojos","red bell peppers","en tiras","in strips"],
    [2,"","bellpepper","structure","pimientos verdes","green bell peppers","en tiras","in strips"],
    [3,"","tomato","liquid","tomates maduros","ripe tomatoes","pelados y picados","peeled and chopped"],
    [1,"tsp","salt","salt","sal","salt"],
    [4,"","egg","protein","huevos","eggs"]],
 es:{n:"Piperrada", b:"Pimientos, cebolla y tomate pochados despacio, con huevos al final. Plato vasco de huerta.",
  st:["Pocha la cebolla y el ajo en el aceite 10 minutos a fuego bajo.",
      "Añade los pimientos y cocina 15 minutos, hasta que estén blandos.",
      "Añade el tomate y la sal y cocina 10 minutos más.",
      "Casca los huevos encima, tapa y cocina 4 minutos, hasta que cuajen las claras."],
  tp:["La clave es el fuego lento: los pimientos deben quedar melosos.",
      "También se puede revolver los huevos con la verdura."],
  v:"piperrada vasca"},
 en:{n:"Piperrada (Basque Peppers and Eggs)", b:"Peppers, onion and tomato stewed slowly, with eggs at the end. A Basque garden dish.",
  st:["Soften the onion and garlic in the oil for 10 minutes on low.",
      "Add the peppers and cook 15 minutes, until soft.",
      "Add the tomato and salt and cook 10 minutes more.",
      "Crack the eggs on top, cover and cook 4 minutes, until the whites set."],
  tp:["Low heat is the key: the peppers should turn silky.",
      "You can also scramble the eggs into the vegetables."],
  v:"basque piperrada"}},

{id:"merluza-en-salsa-verde", c:"Spain", r:"mediterranean", m:"main", t:30, s:4,
 i:[[4,"fillet","whitefish","protein","lomos de merluza","hake fillets"],
    [300,"g","clam","protein","almejas","clams"],
    [5,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [4,"clove","garlic","aromatic","ajo","garlic","picado fino","finely chopped"],
    [1,"tbsp","apflour","thicken","harina de trigo","plain flour"],
    [100,"ml","winewhite","liquid","vino blanco","white wine"],
    [200,"ml","water","liquid","agua","water"],
    [1,"bunch","herb","aromatic","perejil","parsley","picado fino","finely chopped"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Merluza en salsa verde", b:"Merluza con almejas en una salsa ligada de ajo y perejil. Un clásico de la cocina vasca.",
  st:["Sala la merluza.",
      "Sofríe el ajo en el aceite en una cazuela baja 1 minuto, sin dorar. Añade la harina y cocina 1 minuto.",
      "Añade el vino y el agua poco a poco, removiendo.",
      "Añade la merluza con la piel hacia arriba y las almejas. Mueve la cazuela en vaivén 5 minutos para ligar la salsa.",
      "Da la vuelta a la merluza, añade el perejil y cocina 2 minutos más."],
  tp:["Mover la cazuela, no remover, liga la salsa con la gelatina del pescado.",
      "Tira las almejas que no se abran."],
  v:"merluza en salsa verde"},
 en:{n:"Hake in Green Sauce", b:"Hake with clams in a silky garlic and parsley sauce. A Basque classic.",
  st:["Salt the hake.",
      "Fry the garlic in the oil in a wide shallow pan for 1 minute, without browning. Add the flour and cook 1 minute.",
      "Add the wine and water gradually, stirring.",
      "Add the hake skin side up and the clams. Swirl the pan back and forth for 5 minutes to bind the sauce.",
      "Turn the hake, add the parsley and cook 2 minutes more."],
  tp:["Swirling the pan, not stirring, binds the sauce with the fish's gelatine.",
      "Discard any clams that don't open."],
  v:"spanish hake green sauce"}},

{id:"empanada-gallega", c:"Spain", r:"mediterranean", m:"pastry", t:150, s:8,
 i:[[500,"g","apflour","structure","harina de trigo","plain flour"],
    [10,"g","yeast","leaven","levadura seca","dried yeast"],
    [200,"ml","water","liquid","agua tibia","warm water"],
    [80,"ml","oliveoil","fat","aceite de oliva (para la masa)","olive oil (for the dough)"],
    [1,"tsp","salt","salt","sal","salt"],
    [4,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [3,"","onion","aromatic","cebollas","onions","en tiras","in strips"],
    [2,"","bellpepper","aromatic","pimientos rojos","red bell peppers","en tiras","in strips"],
    [200,"g","tomato","liquid","tomate triturado","crushed tomatoes"],
    [1,"tsp","paprika","aromatic","pimentón dulce","sweet paprika"],
    [300,"g","tuna","protein","atún en aceite","tuna in oil","escurrido","drained"],
    [2,"","egg","protein","huevos duros","hard-boiled eggs","picados","chopped"],
    [1,"","egg","glaze","huevo batido","beaten egg"]],
 es:{n:"Empanada gallega de atún", b:"Empanada grande de masa de pan rellena de sofrito de cebolla y pimiento con atún. Infaltable en las romerías gallegas.",
  st:["Mezcla la harina, la levadura, la sal, el agua y el aceite de la masa. Amasa 8 minutos y deja levar 1 hora.",
      "Pocha la cebolla y el pimiento en el aceite 20 minutos. Añade el tomate y el pimentón y cocina 10 minutos. Deja enfriar y mezcla con el atún y el huevo duro.",
      "Divide la masa en dos, estira una parte y forra una bandeja de 30 x 40 cm.",
      "Rellena, cubre con la otra parte y sella los bordes. Haz un agujero en el centro y pinta con el huevo batido.",
      "Hornea a 190 °C 40 minutos, hasta que esté dorada."],
  tp:["Usa un poco del aceite del sofrito en la masa para darle sabor.",
      "Está mejor templada que recién salida del horno."],
  v:"empanada gallega de atún"},
 en:{n:"Empanada Gallega (Galician Tuna Pie)", b:"A large bread-dough pie filled with slow-cooked onion and pepper and tuna. A must at Galician village festivals.",
  st:["Mix the flour, yeast, salt, water and dough oil. Knead 8 minutes and rise 1 hour.",
      "Soften the onion and pepper in the oil for 20 minutes. Add the tomato and paprika and cook 10 minutes. Cool and mix with the tuna and hard-boiled egg.",
      "Split the dough in two, roll one half and line a 30 x 40 cm tray.",
      "Fill, cover with the other half and seal the edges. Cut a hole in the centre and brush with the beaten egg.",
      "Bake at 190 °C for 40 minutes, until golden."],
  tp:["Use a little oil from the filling in the dough for flavour.",
      "It's better warm than straight from the oven."],
  v:"galician empanada tuna"}},

{id:"acorda-alentejana", c:"Portugal", r:"mediterranean", m:"soup", t:20, s:4,
 i:[[4,"clove","garlic","aromatic","ajo","garlic"],
    [1,"bunch","herb","aromatic","cilantro","coriander"],
    [1,"tsp","salt","salt","sal gruesa","coarse salt"],
    [80,"ml","oliveoil","fat","aceite de oliva","olive oil"],
    [1.2,"l","water","liquid","agua hirviendo","boiling water"],
    [300,"g","bread","structure","pan alentejano del día anterior","day-old country bread","en rebanadas","sliced"],
    [4,"","egg","protein","huevos","eggs"]],
 es:{n:"Açorda alentejana", b:"Sopa de pan con ajo, cilantro y aceite de oliva, con huevo escalfado. Cocina pobre y sabrosa del Alentejo.",
  st:["Machaca el ajo, el cilantro y la sal en un mortero hasta tener una pasta.",
      "Pon la pasta en una sopera con el aceite.",
      "Escalfa los huevos en el agua hirviendo 3 minutos. Sácalos.",
      "Vierte el agua caliente sobre la pasta y añade el pan.",
      "Sirve con un huevo en cada plato."],
  tp:["El pan debe ser denso y de varios días para que no se deshaga.",
      "Machaca bien el cilantro: su aroma es el plato."],
  v:"açorda alentejana"},
 en:{n:"Açorda Alentejana (Portuguese Bread Soup)", b:"Bread soup with garlic, coriander and olive oil, topped with a poached egg. The humble, tasty cooking of the Alentejo.",
  st:["Pound the garlic, coriander and salt in a mortar to a paste.",
      "Put the paste in a tureen with the oil.",
      "Poach the eggs in the boiling water for 3 minutes. Lift out.",
      "Pour the hot water over the paste and add the bread.",
      "Serve with an egg in each bowl."],
  tp:["Use dense bread that's a few days old so it doesn't fall apart.",
      "Pound the coriander well: its aroma is the dish."],
  v:"portuguese acorda alentejana"}},

{id:"ameijoas-a-bulhao-pato", c:"Portugal", r:"mediterranean", m:"starter", t:20, s:4,
 i:[[1,"kg","clam","protein","almejas","clams","purgadas","purged"],
    [5,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [5,"clove","garlic","aromatic","ajo","garlic","laminado","sliced"],
    [80,"ml","winewhite","liquid","vino blanco","white wine"],
    [1,"bunch","herb","aromatic","cilantro","coriander","picado","chopped"],
    [1,"","citrus","acid","limón","lemon"],
    [1,"pinch","pepper","aromatic","pimienta","pepper"]],
 es:{n:"Almejas a Bulhão Pato", b:"Almejas abiertas en ajo, aceite de oliva, cilantro y limón. La tapa de marisco más querida de Lisboa.",
  st:["Deja las almejas en agua con sal 1 hora para que suelten la arena.",
      "Dora el ajo en el aceite 1 minuto.",
      "Añade las almejas y el vino, tapa y cuece 4 minutos, hasta que se abran.",
      "Añade el cilantro, la pimienta y el jugo del limón y mueve la cazuela.",
      "Sirve de inmediato con su jugo."],
  tp:["Tira las almejas que no se abran.",
      "No tires el jugo: es la mejor parte."],
  v:"amêijoas à bulhão pato"},
 en:{n:"Clams Bulhão Pato", b:"Clams opened in garlic, olive oil, coriander and lemon. Lisbon's best-loved seafood petisco.",
  st:["Soak the clams in salted water for 1 hour so they release their sand.",
      "Fry the garlic in the oil for 1 minute.",
      "Add the clams and wine, cover and cook 4 minutes, until they open.",
      "Add the coriander, pepper and lemon juice and shake the pan.",
      "Serve at once with the juices."],
  tp:["Discard any clams that don't open.",
      "Spoon up the juices: they're the best part."],
  v:"portuguese clams bulhao pato"}},

{id:"frango-piri-piri", c:"Portugal", r:"mediterranean", m:"main", t:90, s:4,
 i:[[1.5,"kg","chicken","protein","pollo entero abierto en mariposa","whole chicken, spatchcocked"],
    [6,"","chilli","aromatic","guindillas piri-piri o bird's eye","piri-piri or bird's eye chillies"],
    [4,"clove","garlic","aromatic","ajo","garlic"],
    [2,"","citrus","acid","limones","lemons","exprimidos","juiced"],
    [80,"ml","oliveoil","fat","aceite de oliva","olive oil"],
    [1,"tsp","paprika","aromatic","pimentón dulce","sweet paprika"],
    [1,"tbsp","winevinegar","acid","vinagre de vino tinto","red wine vinegar"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Frango piri-piri", b:"Pollo abierto adobado en guindilla, ajo y limón, asado a la brasa. El pollo más famoso de Portugal.",
  st:["Tritura las guindillas, el ajo, el limón, el aceite, el pimentón, el vinagre y la sal.",
      "Unta el pollo con la mitad de la salsa y marina 1 hora como mínimo.",
      "Ásalo a la parrilla o en el horno a 220 °C 45 minutos, con la piel hacia arriba.",
      "Píntalo con el resto de la salsa los últimos 10 minutos.",
      "Deja reposar 5 minutos antes de cortar."],
  tp:["Si lo quieres menos picante, quita las semillas de las guindillas.",
      "Marinado toda la noche queda aún mejor."],
  v:"frango piri piri"},
 en:{n:"Frango Piri-Piri (Portuguese Chilli Chicken)", b:"Spatchcocked chicken marinated in chilli, garlic and lemon and grilled. Portugal's most famous chicken.",
  st:["Blend the chillies, garlic, lemon, oil, paprika, vinegar and salt.",
      "Rub the chicken with half the sauce and marinate at least 1 hour.",
      "Grill it, or roast at 220 °C for 45 minutes, skin side up.",
      "Brush with the rest of the sauce for the last 10 minutes.",
      "Rest 5 minutes before carving."],
  tp:["For less heat, seed the chillies.",
      "Marinated overnight it's even better."],
  v:"portuguese piri piri chicken"}},

{id:"salame-de-chocolate", c:"Portugal", r:"mediterranean", m:"sweet", t:20, s:10,
 i:[[200,"g","mariebiscuit","structure","galletas María","Marie biscuits","partidas en trozos","broken into pieces"],
    [150,"g","butter","fat","mantequilla blanda","soft butter"],
    [100,"g","sugar","sweet","azúcar","sugar"],
    [60,"g","cocoa","aromatic","cacao en polvo","cocoa powder"],
    [2,"","eggyolk","binder","yemas de huevo pasteurizadas","pasteurised egg yolks"],
    [2,"tbsp","icingsugar","garnish","azúcar glas","icing sugar"]],
 es:{n:"Salame de chocolate", b:"Rollo de chocolate y galleta que parece un salame al cortarlo. Postre sin horno de las casas portuguesas.",
  st:["Bate la mantequilla con el azúcar hasta que esté cremosa.",
      "Añade las yemas y el cacao y mezcla bien.",
      "Añade las galletas y mezcla hasta que estén cubiertas.",
      "Forma un cilindro sobre papel film, envuélvelo apretado y refrigera 4 horas.",
      "Pasa por el azúcar glas y corta en rodajas."],
  tp:["Usa yemas pasteurizadas porque no se cuecen.",
      "Deja trozos de galleta de distintos tamaños para que parezca salame."],
  v:"salame de chocolate portugués"},
 en:{n:"Salame de Chocolate (Chocolate Salami)", b:"A chocolate and biscuit log that looks like salami when sliced. A no-bake dessert from Portuguese homes.",
  st:["Beat the butter with the sugar until creamy.",
      "Add the yolks and cocoa and mix well.",
      "Add the biscuits and mix until coated.",
      "Shape into a log on cling film, wrap tightly and chill 4 hours.",
      "Roll in the icing sugar and slice."],
  tp:["Use pasteurised yolks because they aren't cooked.",
      "Leave biscuit pieces in different sizes so it looks like salami."],
  v:"portuguese chocolate salami"}}
];
