module.exports = [
{id:"enchiladas-suizas", c:"Mexico", r:"latin-america", m:"main", t:50, s:4, o:200,
 i:[[12,"","corntortilla","structure","tortillas de maíz","corn tortillas"],
    [400,"g","chicken","protein","pollo cocido deshebrado","cooked shredded chicken"],
    [600,"g","tomatillo","acid","tomatillos","tomatillos","sin cáscara","husked"],
    [2,"","chilli","aromatic","chiles serranos","serrano chiles"],
    [0.5,"","onion","aromatic","cebolla blanca","white onion"],
    [1,"clove","garlic","aromatic","ajo","garlic"],
    [1,"bunch","herb","aromatic","cilantro","cilantro"],
    [250,"ml","crema","fat","crema mexicana","Mexican crema"],
    [120,"ml","stock","liquid","caldo de pollo","chicken stock"],
    [200,"g","cheese","fat","queso Chihuahua o Monterey Jack","Chihuahua or Monterey Jack cheese","rallado","grated"],
    [60,"ml","oil","fat","aceite","oil"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Enchiladas suizas", b:"Enchiladas de pollo en salsa verde con crema, gratinadas con queso. El nombre viene de Sanborns y de la idea de que en Suiza todo lleva lácteos.",
  st:["Hierve los tomatillos, los serranos, la cebolla y el ajo 8 minutos. Lícualos con el cilantro, la crema, el caldo y la sal.",
      "Fríe la salsa en 1 cucharada de aceite 5 minutos a fuego medio, sin que hierva fuerte para que la crema no se corte.",
      "Pasa cada tortilla por aceite caliente 5 segundos por lado y luego por la salsa.",
      "Rellena con pollo, enrolla y acomoda en una fuente con la unión hacia abajo.",
      "Cubre con el resto de la salsa y el queso. Hornea a 200 °C 15 minutos, hasta que el queso burbujee y se dore en manchas."],
  tp:["Freír la tortilla antes de mojarla en salsa evita que se rompa: el aceite la sella.",
      "Si la salsa se ve cortada, lícuala otra vez unos segundos."],
  v:"enchiladas suizas receta"},
 en:{n:"Enchiladas Suizas", b:"Chicken enchiladas in a creamy green salsa, baked under melted cheese. The name comes from the idea that everything in Switzerland is made with dairy.",
  st:["Boil the tomatillos, serranos, onion and garlic for 8 minutes. Blend with the cilantro, crema, stock and salt.",
      "Fry the sauce in 1 tablespoon of oil for 5 minutes over medium heat, without letting it boil hard so the crema doesn't split.",
      "Pass each tortilla through hot oil for 5 seconds per side, then through the sauce.",
      "Fill with chicken, roll up and arrange seam side down in a baking dish.",
      "Cover with the rest of the sauce and the cheese. Bake at 200 °C for 15 minutes, until the cheese bubbles and browns in spots."],
  tp:["Frying the tortilla before dipping keeps it from tearing: the oil seals it.",
      "If the sauce looks split, blend it again for a few seconds."],
  v:"enchiladas suizas recipe"}},

{id:"enchiladas-rojas", c:"Mexico", r:"latin-america", m:"main", t:45, s:4,
 i:[[12,"","corntortilla","structure","tortillas de maíz","corn tortillas"],
    [5,"","chilli","aromatic","chiles guajillo","guajillo chiles","desvenados","stemmed and seeded"],
    [2,"","ancho","aromatic","chiles anchos","ancho chiles","desvenados","stemmed and seeded"],
    [2,"clove","garlic","aromatic","ajo","garlic"],
    [0.25,"","onion","aromatic","cebolla blanca","white onion"],
    [0.5,"tsp","herb","aromatic","orégano mexicano","Mexican oregano"],
    [0.25,"tsp","spice","aromatic","comino","cumin"],
    [400,"ml","stock","liquid","caldo de pollo","chicken stock"],
    [60,"ml","oil","fat","aceite","oil"],
    [200,"g","queso","protein","queso fresco","queso fresco","desmoronado","crumbled"],
    [0.5,"","onion","garnish","cebolla blanca","white onion","picada","chopped"],
    [2,"","veg","garnish","hojas de lechuga","lettuce leaves","en tiras","shredded"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Enchiladas rojas", b:"Tortillas pasadas por salsa de guajillo y ancho, rellenas de queso fresco y dobladas. La versión de mercado: sencilla, roja y rápida.",
  st:["Tuesta los chiles en un comal 15 segundos por lado y remójalos en agua caliente 15 minutos.",
      "Lícualos con el ajo, la cebolla, el orégano, el comino, la sal y el caldo. Cuela.",
      "Fríe la salsa en 1 cucharada de aceite 8 minutos, hasta que se espese y brille.",
      "Pasa cada tortilla por aceite caliente 5 segundos y luego por la salsa caliente.",
      "Rellena con queso, dobla por la mitad y sirve con más salsa, cebolla y lechuga."],
  tp:["Colar la salsa quita las pieles del chile, que amargan y raspan.",
      "Trabaja con la salsa caliente: fría, la tortilla se rompe."],
  v:"enchiladas rojas receta"},
 en:{n:"Red Enchiladas", b:"Tortillas dipped in guajillo and ancho sauce, filled with queso fresco and folded. The market-stall version: simple, red and quick.",
  st:["Toast the chiles on a griddle for 15 seconds per side and soak them in hot water for 15 minutes.",
      "Blend them with the garlic, onion, oregano, cumin, salt and stock. Strain.",
      "Fry the sauce in 1 tablespoon of oil for 8 minutes, until thick and glossy.",
      "Pass each tortilla through hot oil for 5 seconds, then through the hot sauce.",
      "Fill with cheese, fold in half and serve with more sauce, onion and lettuce."],
  tp:["Straining removes the chile skins, which taste bitter and scratch.",
      "Work with hot sauce: cold, the tortilla tears."],
  v:"red enchiladas recipe"}},

{id:"tamales-verdes", c:"Mexico", r:"latin-america", m:"main", t:180, s:20,
 i:[[1000,"g","masa","structure","masa de maíz para tamales","corn masa for tamales","o 500 g de harina de maíz nixtamalizado","or 500 g masa harina"],
    [250,"g","lard","fat","manteca de cerdo","lard"],
    [1,"tbsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [400,"ml","stock","liquid","caldo de pollo","chicken stock","tibio","warm"],
    [2,"tsp","salt","salt","sal","salt"],
    [600,"g","chicken","protein","pollo cocido deshebrado","cooked shredded chicken"],
    [500,"g","tomatillo","acid","tomatillos","tomatillos"],
    [3,"","chilli","aromatic","chiles serranos","serrano chiles"],
    [1,"clove","garlic","aromatic","ajo","garlic"],
    [0.5,"bunch","herb","aromatic","cilantro","cilantro"],
    [25,"","cornhusk","structure","hojas de maíz secas","dried corn husks","remojadas","soaked"]],
 es:{n:"Tamales verdes", b:"Masa batida con manteca hasta que flota, rellena de pollo en salsa verde y cocida al vapor en hoja de maíz. Una tamalada da para compartir.",
  st:["Remoja las hojas en agua caliente 1 hora hasta que estén flexibles.",
      "Hierve los tomatillos, los serranos y el ajo 8 minutos, lícualos con el cilantro y una pizca de sal, y mezcla la salsa con el pollo.",
      "Bate la manteca 5 minutos hasta que esté blanca y esponjosa. Añade la masa, el polvo de hornear y la sal, y bate añadiendo el caldo poco a poco durante 10 minutos.",
      "Prueba: una bolita de masa en un vaso de agua fría debe flotar. Si se hunde, bate 3 minutos más.",
      "Unta 2 cucharadas de masa en la parte ancha de cada hoja, pon una cucharada de relleno, dobla los lados y luego la punta hacia arriba.",
      "Acomódalos parados en la vaporera, con la punta abierta hacia arriba. Tapa con hojas y cuece a vapor 1 hora y 15 minutos.",
      "Están listos cuando la masa se despega sola de la hoja. Déjalos reposar 15 minutos antes de servir."],
  tp:["La prueba del vaso de agua dice si hay suficiente aire en la masa: ese aire es lo que los hace esponjosos.",
      "Mete una moneda en el fondo de la vaporera: cuando deje de sonar, falta agua.",
      "Se congelan bien. Recaliéntalos al vapor, no en el microondas."],
  v:"tamales verdes de pollo"},
 en:{n:"Chicken Tamales in Green Salsa", b:"Masa whipped with lard until it floats, filled with chicken in green salsa and steamed in corn husks. One batch feeds a party.",
  st:["Soak the husks in hot water for 1 hour until pliable.",
      "Boil the tomatillos, serranos and garlic for 8 minutes, blend with the cilantro and a pinch of salt, and mix the salsa with the chicken.",
      "Beat the lard for 5 minutes until white and fluffy. Add the masa, baking powder and salt and beat, adding the stock little by little, for 10 minutes.",
      "Test it: a small ball of masa dropped in a glass of cold water should float. If it sinks, beat 3 minutes more.",
      "Spread 2 tablespoons of masa on the wide end of each husk, add a spoonful of filling, fold in the sides, then fold the tip up.",
      "Stand them upright in the steamer, open end up. Cover with more husks and steam for 1 hour and 15 minutes.",
      "They're done when the masa pulls away from the husk on its own. Rest 15 minutes before serving."],
  tp:["The float test tells you whether there's enough air in the masa: that air is what makes them fluffy.",
      "Put a coin in the bottom of the steamer: when it stops rattling, you're out of water.",
      "They freeze well. Reheat them by steaming, not in the microwave."],
  v:"green chicken tamales recipe"}},

{id:"chiles-en-nogada", c:"Mexico", r:"latin-america", m:"main", t:150, s:6,
 i:[[6,"","chilli","structure","chiles poblanos","poblano chiles"],
    [250,"g","porkmince","protein","carne molida de cerdo","ground pork"],
    [250,"g","beef","protein","carne molida de res","ground beef"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [0.5,"","onion","aromatic","cebolla blanca","white onion","picada","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic"],
    [200,"g","tomato","aromatic","jitomate","tomato","picado","chopped"],
    [1,"","fruit","sweet","manzana panochera o manzana","apple","en cubos","diced"],
    [1,"","fruit","sweet","pera","pear","en cubos","diced"],
    [1,"","fruit","sweet","durazno","peach","en cubos","diced"],
    [0.5,"","plantain","sweet","plátano macho maduro","ripe plantain","en cubos","diced"],
    [40,"g","driedfruit","sweet","pasas","raisins"],
    [40,"g","almond","crunch","almendras","almonds","picadas","chopped"],
    [0.5,"tsp","spice","aromatic","canela","cinnamon"],
    [1.5,"tsp","salt","salt","sal","salt"],
    [150,"g","walnut","sauce","nueces de Castilla","walnuts","peladas","peeled"],
    [100,"g","cheese","sauce","queso de cabra fresco","fresh goat cheese"],
    [200,"ml","milk","sauce","leche","milk"],
    [1,"tbsp","sugar","sweet","azúcar","sugar"],
    [1,"","fruit","garnish","granada","pomegranate","desgranada","seeded"],
    [1,"sprig","herb","garnish","perejil","parsley"]],
 es:{n:"Chiles en nogada", b:"Poblanos rellenos de picadillo con frutas, cubiertos de salsa fría de nuez y granada. Los colores de la bandera y la temporada de agosto en Puebla.",
  st:["Asa los chiles directo en la llama hasta que la piel esté negra por todas partes. Mételos en una bolsa 10 minutos, pélalos, haz un corte lateral y retira las semillas sin romperlos.",
      "Para el relleno, sofríe la cebolla y el ajo en el aceite 5 minutos. Añade las carnes y dora 8 minutos.",
      "Añade el jitomate y cocina 5 minutos. Añade las frutas, las pasas, las almendras, la canela y la sal y cocina 10 minutos, hasta que la fruta esté tierna pero entera.",
      "Para la nogada, lícua las nueces, el queso, la leche y el azúcar hasta que esté muy lisa y espesa como crema. Ajusta con leche.",
      "Rellena los chiles con el picadillo tibio, cúbrelos con la nogada fría y termina con granada y perejil."],
  tp:["Pelar la piel fina de la nuez fresca es tedioso pero es lo que hace la nogada blanca y sin amargor. Remojar las nueces en leche una noche ayuda.",
      "El chile se sirve a temperatura ambiente y la nogada fría: es parte del plato."],
  v:"chiles en nogada receta"},
 en:{n:"Chiles en Nogada", b:"Poblanos stuffed with fruit-studded picadillo, covered in cold walnut sauce and pomegranate. The colors of the flag and August in Puebla.",
  st:["Char the chiles directly over the flame until the skin is black all over. Put them in a bag for 10 minutes, peel, cut a slit down one side and remove the seeds without tearing them.",
      "For the filling, cook the onion and garlic in the oil for 5 minutes. Add the meats and brown for 8 minutes.",
      "Add the tomato and cook 5 minutes. Add the fruit, raisins, almonds, cinnamon and salt and cook for 10 minutes, until the fruit is tender but whole.",
      "For the nogada, blend the walnuts, cheese, milk and sugar until very smooth and thick as cream. Adjust with milk.",
      "Fill the chiles with the warm picadillo, cover with the cold nogada and finish with pomegranate and parsley."],
  tp:["Peeling the thin skin off fresh walnuts is tedious, but it's what makes the nogada white and not bitter. Soaking the nuts in milk overnight helps.",
      "The chile is served at room temperature and the nogada cold: that contrast is part of the dish."],
  v:"chiles en nogada recipe"}},

{id:"chiles-rellenos", c:"Mexico", r:"latin-america", m:"main", t:60, s:4,
 i:[[4,"","chilli","structure","chiles poblanos","poblano chiles"],
    [300,"g","cheese","protein","queso Oaxaca o Chihuahua","Oaxaca or Chihuahua cheese","en bastones","in sticks"],
    [4,"","egg","aerate","huevos","eggs","separados","separated"],
    [40,"g","apflour","dredge","harina","flour"],
    [300,"ml","oil","fat","aceite","oil","para freír","for frying"],
    [400,"g","tomato","aromatic","jitomates","tomatoes"],
    [0.25,"","onion","aromatic","cebolla blanca","white onion"],
    [1,"clove","garlic","aromatic","ajo","garlic"],
    [250,"ml","stock","liquid","caldo de pollo","chicken stock"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Chiles rellenos", b:"Poblanos asados rellenos de queso, capeados en huevo batido a punto de nieve y servidos en caldillo de jitomate. El capeado debe quedar como una nube dorada.",
  st:["Asa, suda en bolsa y pela los chiles. Abre un corte, quita las semillas y rellena con el queso. Cierra con un palillo.",
      "Para el caldillo, lícua los jitomates, la cebolla, el ajo y la sal. Fríe 5 minutos en 1 cucharada de aceite, añade el caldo y cuece 10 minutos.",
      "Bate las claras a punto de nieve firme. Añade las yemas una a una, batiendo solo hasta integrar.",
      "Calienta el aceite a 180 °C. Pasa cada chile por harina, sacude el exceso y báñalo en el huevo.",
      "Fríe 2 minutos por lado, bañándolo con aceite, hasta dorar. Escurre sobre papel.",
      "Sirve en un plato hondo sobre el caldillo caliente, o déjalo hervir 1 minuto en él."],
  tp:["La harina es lo que hace que el huevo se pegue al chile. Sin ella, el capeado se resbala.",
      "Las yemas se añaden al final y solo hasta integrar: batir más baja las claras."],
  v:"chiles rellenos capeados"},
 en:{n:"Chiles Rellenos", b:"Roasted poblanos stuffed with cheese, coated in whipped-egg batter and served in tomato broth. The coating should come out like a golden cloud.",
  st:["Char, sweat in a bag and peel the chiles. Cut a slit, remove the seeds and stuff with the cheese. Close with a toothpick.",
      "For the broth, blend the tomatoes, onion, garlic and salt. Fry for 5 minutes in 1 tablespoon of oil, add the stock and simmer for 10 minutes.",
      "Whip the egg whites to stiff peaks. Add the yolks one at a time, beating only until combined.",
      "Heat the oil to 180 °C. Dredge each chile in flour, shake off the excess and coat it in the egg.",
      "Fry 2 minutes per side, basting with oil, until golden. Drain on paper.",
      "Serve in a shallow bowl over the hot broth, or let it simmer in it for 1 minute."],
  tp:["The flour is what makes the egg stick to the chile. Without it, the coating slides off.",
      "Add the yolks last and only until combined: more beating deflates the whites."],
  v:"chiles rellenos recipe"}},

{id:"pozole-verde", c:"Mexico", r:"latin-america", m:"soup", t:180, s:8,
 i:[[1000,"g","chicken","protein","pollo en piezas","chicken pieces"],
    [800,"g","hominy","structure","maíz pozolero","hominy","cocido, escurrido","cooked, drained"],
    [500,"g","tomatillo","acid","tomatillos","tomatillos"],
    [100,"g","seeds","thicken","pepitas de calabaza","pumpkin seeds","peladas","hulled"],
    [3,"","chilli","aromatic","chiles jalapeños","jalapeños"],
    [1,"bunch","herb","aromatic","cilantro","cilantro"],
    [4,"","herb","aromatic","hojas de rábano o de lechuga","radish or lettuce leaves"],
    [1,"sprig","herb","aromatic","epazote","epazote"],
    [1,"","onion","aromatic","cebolla blanca","white onion"],
    [3,"clove","garlic","aromatic","ajo","garlic"],
    [1,"tbsp","salt","salt","sal","salt"],
    [1,"plate","veg","garnish","rábano, lechuga, aguacate y limón","radish, lettuce, avocado and lime","para servir","to serve"],
    [1,"","onion","garnish","cebolla","onion","picada, para servir","chopped, to serve"]],
 es:{n:"Pozole verde", b:"El pozole de Guerrero: caldo de pollo espesado con pepita tostada, tomatillo y hierbas. Más fresco y herbal que el rojo.",
  st:["Cuece el pollo con media cebolla, el ajo y sal en 3 litros de agua a fuego bajo 45 minutos. Retira el pollo y deshébralo.",
      "Tuesta las pepitas en una sartén seca hasta que se inflen y empiecen a saltar, sin dorarlas de más.",
      "Hierve los tomatillos y los jalapeños 8 minutos. Lícualos con las pepitas, el cilantro, las hojas, el epazote, la otra media cebolla y 500 ml del caldo.",
      "Añade el maíz al caldo y cuece 30 minutos.",
      "Vierte la salsa verde y cuece a fuego bajo 15 minutos más, sin que hierva fuerte.",
      "Devuelve el pollo, rectifica la sal y sirve con las guarniciones."],
  tp:["Las pepitas espesan el caldo; si hierve fuerte después de añadirlas, se separan y el caldo se ve granuloso.",
      "Las guarniciones son la mitad del plato: cada quien arma su plato."],
  v:"pozole verde guerrero"},
 en:{n:"Green Pozole", b:"Pozole from Guerrero: chicken broth thickened with toasted pumpkin seeds, tomatillo and herbs. Fresher and greener than red pozole.",
  st:["Simmer the chicken with half the onion, the garlic and salt in 3 liters of water over low heat for 45 minutes. Remove the chicken and shred it.",
      "Toast the pumpkin seeds in a dry skillet until they puff and start to pop, without over-browning.",
      "Boil the tomatillos and jalapeños for 8 minutes. Blend with the seeds, cilantro, leaves, epazote, the other half onion and 500 ml of the broth.",
      "Add the hominy to the broth and simmer for 30 minutes.",
      "Pour in the green sauce and simmer on low for 15 minutes more, without a hard boil.",
      "Return the chicken, adjust the salt and serve with the garnishes."],
  tp:["The seeds thicken the broth; if it boils hard after adding them, they separate and the broth turns grainy.",
      "The garnishes are half the dish: everyone builds their own bowl."],
  v:"pozole verde recipe"}},

{id:"caldo-de-res", c:"Mexico", r:"latin-america", m:"soup", t:180, s:6,
 i:[[1000,"g","beef","protein","chambarete y costilla de res","beef shank and short rib"],
    [3000,"ml","water","liquid","agua","water"],
    [0.5,"","onion","aromatic","cebolla blanca","white onion"],
    [3,"clove","garlic","aromatic","ajo","garlic"],
    [2,"","herb","aromatic","hojas de laurel","bay leaves"],
    [2,"","corn","structure","elotes","ears of corn","en trozos","in chunks"],
    [2,"","veg","structure","zanahorias","carrots","en trozos","in chunks"],
    [2,"","veg","structure","calabacitas","zucchini","en trozos","in chunks"],
    [3,"","potato","structure","papas","potatoes","en trozos","in chunks"],
    [0.25,"","veg","structure","col","cabbage","en gajos","in wedges"],
    [1,"bunch","herb","aromatic","cilantro","cilantro"],
    [1,"tbsp","salt","salt","sal","salt"],
    [2,"","citrus","acid","limones","limes"]],
 es:{n:"Caldo de res", b:"Chambarete con hueso cocido a fuego lento con elote, verduras y cilantro. Un caldo claro y generoso para días fríos o convalecencias.",
  st:["Pon la carne en el agua fría con la cebolla, el ajo y el laurel. Hierve y retira la espuma durante los primeros 10 minutos.",
      "Baja a fuego muy bajo y cuece 2 horas, hasta que la carne esté tierna.",
      "Añade la sal, el elote y la zanahoria y cuece 15 minutos.",
      "Añade las papas y cuece 10 minutos. Añade la calabacita y la col y cuece 8 minutos más.",
      "Termina con el cilantro y sirve con limón, cebolla picada y chile serrano al gusto."],
  tp:["Empezar con agua fría y retirar la espuma es lo que deja el caldo claro.",
      "Las verduras entran por tiempos para que todas lleguen al punto a la vez."],
  v:"caldo de res mexicano"},
 en:{n:"Mexican Beef Soup", b:"Bone-in beef shank simmered slowly with corn, vegetables and cilantro. A clear, generous broth for cold days or sick days.",
  st:["Put the meat in the cold water with the onion, garlic and bay. Bring to a boil and skim the foam for the first 10 minutes.",
      "Drop to very low heat and simmer for 2 hours, until the meat is tender.",
      "Add the salt, corn and carrot and cook for 15 minutes.",
      "Add the potatoes and cook for 10 minutes. Add the zucchini and cabbage and cook 8 minutes more.",
      "Finish with the cilantro and serve with lime, chopped onion and serrano chile to taste."],
  tp:["Starting in cold water and skimming is what keeps the broth clear.",
      "The vegetables go in stages so they're all done at the same time."],
  v:"caldo de res recipe"}},

{id:"sopes", c:"Mexico", r:"latin-america", m:"snack", t:45, s:4,
 i:[[500,"g","masa","structure","masa de maíz","corn masa","o 250 g de harina de maíz nixtamalizado con agua","or 250 g masa harina mixed with water"],
    [0.5,"tsp","salt","salt","sal","salt"],
    [2,"tbsp","lard","fat","manteca de cerdo","lard"],
    [300,"g","legume","protein","frijoles refritos","refried beans"],
    [200,"g","chorizo","protein","chorizo","chorizo","sin tripa, frito","casing removed, fried"],
    [150,"ml","hotsauce","sauce","salsa roja","red salsa"],
    [80,"g","queso","garnish","queso fresco","queso fresco","desmoronado","crumbled"],
    [60,"ml","crema","garnish","crema","crema"],
    [2,"","veg","garnish","hojas de lechuga","lettuce leaves","en tiras","shredded"]],
 es:{n:"Sopes", b:"Discos gruesos de masa cocidos en comal, pellizcados en el borde para contener frijoles, chorizo, salsa y queso.",
  st:["Amasa la masa con la sal hasta que no se pegue a las manos. Divide en 12 bolas.",
      "Aplana cada bola a 1 centímetro de grosor, unos 9 centímetros de diámetro.",
      "Cuécelas en un comal caliente 2 minutos por lado, hasta que tengan manchas pero sigan blandas.",
      "Con la masa aún caliente, pellizca el borde para hacer una pared. Cuidado: quema.",
      "Unta manteca en el comal y dora la base de los sopes 2 minutos.",
      "Cubre con frijoles, chorizo, salsa, queso, crema y lechuga."],
  tp:["Pellizca el borde en caliente: fría, la masa se agrieta.",
      "Si la masa se agrieta al aplanar, le falta agua."],
  v:"sopes receta"},
 en:{n:"Sopes", b:"Thick masa discs cooked on a griddle and pinched at the edge to hold beans, chorizo, salsa and cheese.",
  st:["Knead the masa with the salt until it no longer sticks to your hands. Divide into 12 balls.",
      "Flatten each ball to 1 centimeter thick, about 9 centimeters across.",
      "Cook them on a hot griddle for 2 minutes per side, until spotted but still soft.",
      "While still hot, pinch up the edge to make a rim. Careful: it's hot.",
      "Grease the griddle with lard and brown the bottoms of the sopes for 2 minutes.",
      "Top with beans, chorizo, salsa, cheese, crema and lettuce."],
  tp:["Pinch the edge while hot: cold masa cracks.",
      "If the masa cracks when you flatten it, it needs more water."],
  v:"sopes recipe"}},

{id:"quesadillas", c:"Mexico", r:"latin-america", m:"snack", t:20, s:4,
 i:[[8,"","corntortilla","structure","tortillas de maíz","corn tortillas"],
    [300,"g","cheese","protein","queso Oaxaca","Oaxaca cheese","deshebrado","pulled into strands"],
    [1,"sprig","herb","aromatic","epazote","epazote","hojas","leaves"],
    [150,"ml","hotsauce","sauce","salsa verde o roja","green or red salsa"]],
 es:{n:"Quesadillas de comal", b:"Tortilla de maíz, queso Oaxaca y una hoja de epazote, doradas en comal seco. Tres ingredientes y la paciencia de esperar a que el queso se derrita.",
  st:["Calienta un comal a fuego medio, sin grasa.",
      "Calienta cada tortilla 20 segundos por lado para ablandarla.",
      "Pon queso en una mitad y una o dos hojas de epazote, y dobla.",
      "Cocina 2-3 minutos por lado, presionando, hasta que la tortilla tenga manchas doradas y el queso se derrita por completo.",
      "Sirve de inmediato con salsa."],
  tp:["Fuego medio, no alto: el queso tiene que derretirse antes de que la tortilla se queme.",
      "En la Ciudad de México, una quesadilla no siempre lleva queso. Aquí sí."],
  v:"quesadillas de comal"},
 en:{n:"Griddle Quesadillas", b:"Corn tortilla, Oaxaca cheese and a leaf of epazote, toasted on a dry griddle. Three ingredients and the patience to let the cheese melt.",
  st:["Heat a griddle over medium heat, no fat.",
      "Warm each tortilla for 20 seconds per side to soften it.",
      "Put cheese on one half with one or two epazote leaves, and fold.",
      "Cook 2-3 minutes per side, pressing down, until the tortilla is spotted golden and the cheese is fully melted.",
      "Serve right away with salsa."],
  tp:["Medium heat, not high: the cheese needs to melt before the tortilla burns.",
      "In Mexico City a quesadilla doesn't always contain cheese. This one does."],
  v:"quesadilla recipe corn tortilla"}},

{id:"flautas", c:"Mexico", r:"latin-america", m:"main", t:40, s:4,
 i:[[16,"","corntortilla","structure","tortillas de maíz","corn tortillas","delgadas","thin"],
    [400,"g","chicken","protein","pollo cocido deshebrado","cooked shredded chicken"],
    [0.5,"tsp","salt","salt","sal","salt"],
    [300,"ml","oil","fat","aceite","oil","para freír","for frying"],
    [3,"","veg","garnish","hojas de lechuga","lettuce leaves","en tiras","shredded"],
    [120,"ml","crema","garnish","crema","crema"],
    [80,"g","queso","garnish","queso fresco","queso fresco","desmoronado","crumbled"],
    [150,"ml","hotsauce","sauce","salsa verde","salsa verde"],
    [1,"","avocado","garnish","aguacate","avocado","en rebanadas","sliced"]],
 es:{n:"Flautas de pollo", b:"Tortillas enrolladas muy apretadas con pollo y fritas hasta crujir de punta a punta. Se comen con la mano y con mucha salsa.",
  st:["Calienta las tortillas en el comal para que se ablanden; si están frías se rompen al enrollar.",
      "Pon una línea de pollo salado en el borde de cada tortilla y enrolla bien apretado. Sujeta con un palillo.",
      "Fríe en aceite a 180 °C, con la unión hacia abajo primero, 3-4 minutos, girándolas hasta que estén doradas y firmes.",
      "Escurre de pie sobre papel para que suelten el aceite.",
      "Sirve sobre lechuga con crema, queso, salsa y aguacate."],
  tp:["Freír primero con la unión abajo la sella y ya no hace falta el palillo.",
      "Escurrirlas verticales las deja menos grasosas que acostadas."],
  v:"flautas de pollo receta"},
 en:{n:"Chicken Flautas", b:"Tortillas rolled tight around chicken and fried until crisp end to end. Eaten by hand, with plenty of salsa.",
  st:["Warm the tortillas on a griddle to soften them; cold ones crack when rolled.",
      "Lay a line of salted chicken along the edge of each tortilla and roll up tightly. Secure with a toothpick.",
      "Fry in oil at 180 °C, seam side down first, for 3-4 minutes, turning until golden and firm.",
      "Drain them standing up on paper so the oil runs off.",
      "Serve on lettuce with crema, cheese, salsa and avocado."],
  tp:["Frying seam side down first seals it, so the toothpick is no longer needed.",
      "Draining them upright leaves them less greasy than lying flat."],
  v:"chicken flautas recipe"}}
];
