module.exports = [
{id:"pico-de-gallo", c:"Mexico", r:"latin-america", m:"sauce", t:15, s:6,
 i:[[500,"g","tomato","aromatic","jitomates saladet","Roma tomatoes","sin semillas, en cubos","seeded, diced"],
    [0.5,"","onion","aromatic","cebolla blanca","white onion","picada fina","finely chopped"],
    [2,"","chilli","aromatic","chiles serranos","serrano chiles","picados","chopped"],
    [0.5,"bunch","herb","aromatic","cilantro","cilantro","picado","chopped"],
    [2,"","citrus","acid","limones","limes","en jugo","juiced"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Pico de gallo", b:"Jitomate, cebolla, chile y cilantro picados a cuchillo, con limón y sal. La salsa fresca que no se licúa y se come el mismo día.",
  st:["Quita las semillas y el agua de los jitomates antes de picarlos: si no, la salsa queda aguada.",
      "Enjuaga la cebolla picada en un colador con agua fría y escúrrela. Le quita el golpe crudo.",
      "Mezcla todo con el jugo de limón y la sal.",
      "Deja reposar 10 minutos para que suelte jugo, prueba y ajusta sal y limón."],
  tp:["Cuchillo, no procesador: el procesador rompe las células y todo suelta agua.",
      "Se come el mismo día; al siguiente el jitomate está harinoso."],
  v:"pico de gallo receta"},
 en:{n:"Pico de Gallo", b:"Tomato, onion, chile and cilantro chopped by hand with lime and salt. The fresh salsa that never sees a blender and is eaten the same day.",
  st:["Remove the seeds and juice from the tomatoes before dicing: otherwise the salsa turns watery.",
      "Rinse the chopped onion in a sieve under cold water and drain. It takes the raw bite off.",
      "Mix everything with the lime juice and salt.",
      "Let it sit 10 minutes to release its juices, taste and adjust salt and lime."],
  tp:["Knife, not food processor: the processor bursts the cells and everything weeps.",
      "Eat it the same day; by the next the tomato turns mealy."],
  v:"pico de gallo recipe"}},

{id:"salsa-taquera", c:"Mexico", r:"latin-america", m:"sauce", t:20, s:8,
 i:[[15,"","chilli","aromatic","chiles de árbol secos","dried árbol chiles"],
    [3,"","tomatillo","acid","tomatillos","tomatillos"],
    [2,"clove","garlic","aromatic","ajo","garlic"],
    [1,"tbsp","oil","fat","aceite","oil"],
    [120,"ml","water","liquid","agua","water"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"tsp","whitevinegar","acid","vinagre blanco","white vinegar"]],
 es:{n:"Salsa taquera de chile de árbol", b:"La salsa roja delgada y muy picante de la taquería. Chile de árbol frito, tomatillo asado y un chorrito de vinagre.",
  st:["Fríe los chiles en el aceite a fuego bajo 30 segundos, moviendo, hasta que cambien de rojo a rojo oscuro. No más: quemados amargan.",
      "Asa los tomatillos y el ajo en un comal hasta que estén blandos y manchados.",
      "Licúa todo con el agua, la sal y el vinagre hasta que quede lisa.",
      "Deja enfriar: se espesa un poco y el picante se asienta."],
  tp:["El vinagre no es para que sepa a vinagre: es para que dure una semana en el refrigerador y levante el chile.",
      "Si quedó demasiado picante, añade otro tomatillo asado."],
  v:"salsa de chile de arbol taquera"},
 en:{n:"Árbol Chile Taco Salsa", b:"The thin, fiery red salsa of the taquería. Fried árbol chiles, charred tomatillo and a splash of vinegar.",
  st:["Fry the chiles in the oil over low heat for 30 seconds, stirring, until they go from red to dark red. No longer: burned, they turn bitter.",
      "Char the tomatillos and garlic on a griddle until soft and blistered.",
      "Blend everything with the water, salt and vinegar until smooth.",
      "Let it cool: it thickens a little and the heat settles."],
  tp:["The vinegar isn't there to taste of vinegar: it keeps the salsa a week in the fridge and lifts the chile.",
      "If it's too hot, blend in another charred tomatillo."],
  v:"arbol chile salsa taqueria"}},

{id:"cebollas-encurtidas", c:"Mexico", r:"latin-america", m:"side", t:10, s:8,
 i:[[2,"","onion","aromatic","cebollas moradas","red onions","en plumas finas","thinly sliced"],
    [2,"","citrus","acid","naranjas agrias o limones","sour oranges or limes","en jugo","juiced"],
    [60,"ml","cidervinegar","acid","vinagre de manzana","cider vinegar"],
    [1,"tsp","salt","salt","sal","salt"],
    [0.5,"tsp","herb","aromatic","orégano mexicano","Mexican oregano"],
    [1,"","chilli","aromatic","chile habanero","habanero chile","opcional, en tiras","optional, in strips"]],
 es:{n:"Cebolla morada encurtida", b:"Cebolla morada en jugo de naranja agria que en media hora se vuelve rosa brillante. Acompaña cochinita, tacos y casi todo.",
  st:["Pon la cebolla en un colador y vierte encima agua hirviendo. Escurre.",
      "Mézclala con el jugo, el vinagre, la sal, el orégano y el habanero.",
      "Deja reposar al menos 30 minutos a temperatura ambiente, moviendo una vez.",
      "Guarda en frasco en el refrigerador hasta 1 semana."],
  tp:["El agua hirviendo suaviza la cebolla y ayuda a que tome el color rosa más rápido.",
      "Sin naranja agria, usa mitad jugo de naranja y mitad de limón."],
  v:"cebolla morada encurtida yucateca"},
 en:{n:"Pickled Red Onions", b:"Red onion in sour-orange juice that turns bright pink in half an hour. It goes with cochinita, tacos and nearly everything.",
  st:["Put the onion in a sieve and pour boiling water over it. Drain.",
      "Toss with the juice, vinegar, salt, oregano and habanero.",
      "Let it sit at least 30 minutes at room temperature, stirring once.",
      "Keep in a jar in the fridge for up to 1 week."],
  tp:["The boiling water softens the onion and helps it turn pink faster.",
      "No sour oranges? Use half orange juice, half lime juice."],
  v:"pickled red onions yucatan"}},

{id:"rajas-con-crema", c:"Mexico", r:"latin-america", m:"side", t:35, s:4,
 i:[[4,"","chilli","structure","chiles poblanos","poblano chiles"],
    [1,"","onion","aromatic","cebolla blanca","white onion","en plumas","sliced"],
    [2,"","corn","structure","elotes","ears of corn","desgranados","kernels cut off"],
    [20,"g","butter","fat","mantequilla","butter"],
    [200,"ml","crema","fat","crema mexicana","Mexican crema"],
    [100,"g","cheese","fat","queso Oaxaca o Chihuahua","Oaxaca or Chihuahua cheese","rallado","grated"],
    [0.75,"tsp","salt","salt","sal","salt"]],
 es:{n:"Rajas con crema", b:"Tiras de poblano asado con elote y cebolla en crema. Van en tacos, sobre arroz o como guarnición de cualquier carne.",
  st:["Asa los poblanos en la llama hasta que estén negros, sudalos en una bolsa 10 minutos, pélalos y córtalos en tiras.",
      "Sofríe la cebolla en la mantequilla 6 minutos hasta que esté blanda.",
      "Añade el elote y cocina 4 minutos.",
      "Añade las rajas, la crema y la sal, y cocina a fuego bajo 5 minutos.",
      "Añade el queso, tapa y apaga el fuego. Sirve cuando se haya derretido."],
  tp:["No laves los chiles para pelarlos: el agua se lleva el sabor asado. Usa un trapo.",
      "Fuego bajo con la crema: si hierve fuerte se corta."],
  v:"rajas con crema receta"},
 en:{n:"Poblano Strips in Cream", b:"Roasted poblano strips with corn and onion in crema. For tacos, over rice, or next to any meat.",
  st:["Char the poblanos over the flame until black, sweat them in a bag for 10 minutes, peel and cut into strips.",
      "Cook the onion in the butter for 6 minutes until soft.",
      "Add the corn and cook 4 minutes.",
      "Add the strips, crema and salt and cook over low heat for 5 minutes.",
      "Add the cheese, cover and turn off the heat. Serve once it's melted."],
  tp:["Don't rinse the chiles to peel them: water washes off the roasted flavor. Use a towel.",
      "Low heat with the crema: a hard boil splits it."],
  v:"rajas con crema recipe"}},

{id:"calabacitas", c:"Mexico", r:"latin-america", m:"side", t:25, s:4,
 i:[[600,"g","veg","structure","calabacitas","Mexican squash or zucchini","en cubos","diced"],
    [300,"g","tomato","aromatic","jitomate","tomato","picado","chopped"],
    [0.5,"","onion","aromatic","cebolla blanca","white onion","picada","chopped"],
    [1,"clove","garlic","aromatic","ajo","garlic"],
    [1,"","chilli","aromatic","chile serrano","serrano chile"],
    [1,"","corn","structure","elote","ear of corn","desgranado","kernels cut off"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"tsp","salt","salt","sal","salt"],
    [60,"g","queso","garnish","queso fresco","queso fresco","opcional","optional"]],
 es:{n:"Calabacitas a la mexicana", b:"Calabacita, elote y jitomate guisados juntos hasta que la calabaza está tierna pero todavía tiene forma. Guarnición de diario.",
  st:["Sofríe la cebolla, el ajo y el serrano en el aceite 4 minutos.",
      "Añade el jitomate y cocina 5 minutos hasta que se deshaga.",
      "Añade la calabacita, el elote y la sal. Tapa y cocina a fuego medio-bajo 8 minutos.",
      "Destapa y cocina 3 minutos más para evaporar el exceso de líquido.",
      "Sirve con queso fresco desmoronado."],
  tp:["La calabacita suelta mucha agua: por eso el jitomate se cocina antes, para que no quede un caldo.",
      "Para una comida completa, añade pollo deshebrado al final."],
  v:"calabacitas a la mexicana"},
 en:{n:"Mexican-Style Zucchini", b:"Squash, corn and tomato stewed together until the squash is tender but still holds its shape. An everyday side.",
  st:["Cook the onion, garlic and serrano in the oil for 4 minutes.",
      "Add the tomato and cook for 5 minutes until it breaks down.",
      "Add the squash, corn and salt. Cover and cook over medium-low heat for 8 minutes.",
      "Uncover and cook 3 minutes more to evaporate the excess liquid.",
      "Serve with crumbled queso fresco."],
  tp:["Squash gives off a lot of water: that's why the tomato cooks first, so you don't end up with soup.",
      "For a full meal, stir in shredded chicken at the end."],
  v:"calabacitas recipe mexican"}},

{id:"arroz-verde", c:"Mexico", r:"latin-america", m:"side", t:40, s:6,
 i:[[400,"g","rice","structure","arroz de grano largo","long-grain rice"],
    [2,"","chilli","aromatic","chiles poblanos","poblano chiles","sin semillas","seeded"],
    [1,"bunch","herb","aromatic","cilantro","cilantro"],
    [0.5,"bunch","herb","aromatic","perejil","parsley"],
    [0.25,"","onion","aromatic","cebolla blanca","white onion"],
    [1,"clove","garlic","aromatic","ajo","garlic"],
    [750,"ml","stock","liquid","caldo de pollo","chicken stock"],
    [60,"ml","oil","fat","aceite","oil"],
    [1.5,"tsp","salt","salt","sal","salt"]],
 es:{n:"Arroz verde", b:"Arroz frito y cocido en un licuado de poblano, cilantro y perejil. Mismo método que el rojo, sabor más fresco.",
  st:["Enjuaga el arroz y escúrrelo 10 minutos.",
      "Licúa los poblanos crudos, las hierbas, la cebolla y el ajo con 250 ml del caldo.",
      "Fríe el arroz en el aceite 6 minutos, moviendo, hasta que esté blanco opaco y suene a arena. Que no se dore mucho: el color verde se ensucia.",
      "Añade el licuado, el resto del caldo y la sal. Hierve, tapa y cocina al mínimo 18 minutos.",
      "Reposa 5 minutos tapado y esponja con un tenedor."],
  tp:["El poblano crudo da color más brillante que el asado.",
      "Si el licuado tiene fibras, cuélalo."],
  v:"arroz verde mexicano"},
 en:{n:"Green Rice", b:"Rice fried and then cooked in a purée of poblano, cilantro and parsley. The same method as red rice, a fresher flavor.",
  st:["Rinse the rice and let it drain for 10 minutes.",
      "Blend the raw poblanos, herbs, onion and garlic with 250 ml of the stock.",
      "Fry the rice in the oil for 6 minutes, stirring, until opaque white and sandy-sounding. Don't let it brown much: it muddies the green.",
      "Add the purée, the rest of the stock and the salt. Bring to a boil, cover and cook on the lowest heat for 18 minutes.",
      "Rest 5 minutes covered and fluff with a fork."],
  tp:["Raw poblano gives a brighter color than roasted.",
      "If the purée is stringy, strain it."],
  v:"arroz verde recipe"}},

{id:"frijoles-charros", c:"Mexico", r:"latin-america", m:"soup", t:60, s:6,
 i:[[800,"g","legume","protein","frijoles pintos cocidos con su líquido de cocción","cooked pinto beans with their cooking liquid"],
    [150,"g","bacon","fat","tocino","bacon","en trozos","chopped"],
    [150,"g","chorizo","protein","chorizo","chorizo"],
    [100,"g","sausage","protein","salchichas","frankfurters","en rodajas","sliced"],
    [0.5,"","onion","aromatic","cebolla blanca","white onion","picada","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic"],
    [300,"g","tomato","aromatic","jitomate","tomato","picado","chopped"],
    [2,"","chilli","aromatic","chiles jalapeños","jalapeños","picados","chopped"],
    [0.5,"bunch","herb","aromatic","cilantro","cilantro"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Frijoles charros", b:"Frijoles pintos en su caldo con tocino, chorizo, jitomate y jalapeño. El acompañante de la carne asada del norte.",
  st:["Dora el tocino a fuego medio hasta que suelte la grasa y esté crujiente, 6 minutos.",
      "Añade el chorizo y cocina 4 minutos, deshaciéndolo. Añade la salchicha y dora 2 minutos.",
      "Añade la cebolla, el ajo y el jalapeño y cocina 4 minutos. Añade el jitomate y cocina 5 minutos.",
      "Vierte los frijoles con su caldo y cuece a fuego bajo 20 minutos.",
      "Ajusta la sal y añade el cilantro al final."],
  tp:["El caldo de los frijoles es la base: si usas de lata, añade un poco de agua y no los escurras.",
      "Deben quedar caldosos, no espesos como refritos."],
  v:"frijoles charros receta"},
 en:{n:"Charro Beans", b:"Pinto beans in their broth with bacon, chorizo, tomato and jalapeño. The northern Mexican side for carne asada.",
  st:["Cook the bacon over medium heat until the fat renders and it's crisp, 6 minutes.",
      "Add the chorizo and cook 4 minutes, breaking it up. Add the frankfurters and brown 2 minutes.",
      "Add the onion, garlic and jalapeño and cook 4 minutes. Add the tomato and cook 5 minutes.",
      "Pour in the beans with their broth and simmer on low for 20 minutes.",
      "Adjust the salt and add the cilantro at the end."],
  tp:["The bean broth is the base: if using canned, add a little water and don't drain them.",
      "They should be brothy, not thick like refried beans."],
  v:"charro beans recipe"}},

{id:"tacos-de-pescado", c:"Mexico", r:"latin-america", m:"main", t:40, s:4,
 i:[[500,"g","whitefish","protein","pescado blanco firme","firm white fish","en tiras","in strips"],
    [120,"g","apflour","structure","harina","flour"],
    [1,"tsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [180,"ml","beer","liquid","cerveza clara fría","cold lager"],
    [1,"tsp","salt","salt","sal","salt"],
    [500,"ml","oil","fat","aceite","oil","para freír","for frying"],
    [8,"","corntortilla","structure","tortillas de maíz","corn tortillas"],
    [0.25,"","veg","garnish","col","cabbage","en tiras finas","finely shredded"],
    [80,"g","mayo","sauce","mayonesa","mayonnaise"],
    [60,"ml","crema","sauce","crema","crema"],
    [1,"tbsp","chipotleadobo","sauce","adobo de chipotle","chipotle adobo sauce"],
    [2,"","citrus","acid","limones","limes"],
    [150,"ml","hotsauce","sauce","pico de gallo o salsa","pico de gallo or salsa"]],
 es:{n:"Tacos de pescado estilo Baja", b:"Pescado en capeado de cerveza, frito hasta crujir, en tortilla de maíz con col, crema de chipotle y limón. Ensenada en un taco.",
  st:["Mezcla la mayonesa, la crema y el adobo de chipotle.",
      "Bate la harina, el polvo de hornear y la sal con la cerveza fría hasta tener una pasta como de hot cakes. Deja unos grumos.",
      "Calienta el aceite a 185 °C. Seca el pescado, sálalo, pásalo por la pasta y fríelo 3-4 minutos hasta que esté dorado y suene hueco.",
      "Escurre sobre una rejilla, no sobre papel.",
      "Calienta las tortillas y arma: col, pescado, crema de chipotle, salsa y limón."],
  tp:["La cerveza fría y la pasta con grumos dan un capeado ligero: el gas y el frío frenan el gluten.",
      "La rejilla mantiene crujiente la parte de abajo; el papel la ablanda con el vapor.",
      "Sin gluten: usa harina de arroz y agua mineral en vez de harina y cerveza."],
  v:"tacos de pescado estilo ensenada"},
 en:{n:"Baja Fish Tacos", b:"Beer-battered fish fried until crackling, in corn tortillas with cabbage, chipotle crema and lime. Ensenada in a taco.",
  st:["Mix the mayonnaise, crema and chipotle adobo.",
      "Whisk the flour, baking powder and salt with the cold beer into a pancake-batter consistency. Leave some lumps.",
      "Heat the oil to 185 °C. Pat the fish dry, salt it, dip it in the batter and fry 3-4 minutes until golden and hollow-sounding.",
      "Drain on a rack, not on paper.",
      "Warm the tortillas and build: cabbage, fish, chipotle crema, salsa and lime."],
  tp:["Cold beer and a lumpy batter make a light crust: the bubbles and the cold slow the gluten.",
      "A rack keeps the bottom crisp; paper steams it soft.",
      "Gluten-free: use rice flour and sparkling water instead of flour and beer."],
  v:"baja fish tacos recipe"}},

{id:"tacos-de-bistec", c:"Mexico", r:"latin-america", m:"main", t:30, s:4,
 i:[[600,"g","beef","protein","bistec de res delgado","thin beef steak","sirloin o arrachera","sirloin or skirt"],
    [1,"tbsp","oil","fat","aceite","oil"],
    [1,"tsp","salt","salt","sal","salt"],
    [0.5,"tsp","pepper","aromatic","pimienta negra","black pepper"],
    [1,"","onion","aromatic","cebolla blanca","white onion","media en rodajas, media picada","half sliced, half chopped"],
    [12,"","corntortilla","structure","tortillas de maíz","corn tortillas","pequeñas","small"],
    [0.5,"bunch","herb","garnish","cilantro","cilantro","picado","chopped"],
    [150,"ml","hotsauce","sauce","salsa verde o taquera","salsa verde or taco salsa"],
    [2,"","citrus","acid","limones","limes"]],
 es:{n:"Tacos de bistec", b:"Bistec delgado a la plancha muy caliente, picado fino, en tortilla doble con cebolla y cilantro. El taco de trompo más sencillo.",
  st:["Seca la carne, sálala y pimiéntala.",
      "Calienta una plancha o sartén de hierro hasta que humee. Añade el aceite y la carne en una capa.",
      "Cocina 1-2 minutos por lado hasta dorar. Saca y deja reposar 3 minutos.",
      "En la misma plancha, dora la cebolla en rodajas 5 minutos en la grasa de la carne.",
      "Pica la carne en trozos pequeños y regrésala a la plancha 30 segundos para que se impregne del jugo.",
      "Sirve en dos tortillas calientes con cebolla picada, cilantro, salsa y limón."],
  tp:["El bistec delgado se cuece en segundos: la plancha tiene que estar muy caliente para dorar antes de que se seque.",
      "Picar después de cocer, no antes: así queda jugoso."],
  v:"tacos de bistec receta"},
 en:{n:"Steak Tacos", b:"Thin steak seared on a smoking-hot griddle, chopped fine and served in doubled tortillas with onion and cilantro.",
  st:["Pat the meat dry and season with salt and pepper.",
      "Heat a griddle or cast-iron skillet until smoking. Add the oil and the meat in one layer.",
      "Cook 1-2 minutes per side until browned. Remove and rest 3 minutes.",
      "On the same griddle, brown the sliced onion for 5 minutes in the meat fat.",
      "Chop the meat into small pieces and return it to the griddle for 30 seconds to soak up the juices.",
      "Serve in two warm tortillas with chopped onion, cilantro, salsa and lime."],
  tp:["Thin steak cooks in seconds: the griddle must be very hot so it browns before it dries out.",
      "Chop after cooking, not before: that keeps it juicy."],
  v:"steak tacos recipe mexican"}},

{id:"picadillo", c:"Mexico", r:"latin-america", m:"main", t:40, s:6,
 i:[[700,"g","beef","protein","carne molida de res","ground beef"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [0.5,"","onion","aromatic","cebolla blanca","white onion","picada","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic"],
    [400,"g","tomato","aromatic","jitomates","tomatoes","licuados","blended"],
    [2,"","potato","structure","papas","potatoes","en cubos pequeños","small dice"],
    [2,"","veg","structure","zanahorias","carrots","en cubos pequeños","small dice"],
    [100,"g","veg","structure","chícharos","peas"],
    [1,"","chilli","aromatic","chile serrano","serrano chile"],
    [0.5,"tsp","spice","aromatic","comino","cumin"],
    [250,"ml","water","liquid","agua","water"],
    [1.5,"tsp","salt","salt","sal","salt"]],
 es:{n:"Picadillo", b:"Carne molida guisada con jitomate, papa, zanahoria y chícharos. Comida de casa: sobre arroz, en tacos o para rellenar chiles.",
  st:["Dora la carne en el aceite a fuego alto 8 minutos, sin moverla al principio, hasta que suelte su jugo y se dore.",
      "Añade la cebolla, el ajo y el serrano y cocina 4 minutos.",
      "Añade el jitomate licuado y el comino y cocina 5 minutos.",
      "Añade la papa, la zanahoria, el agua y la sal. Tapa y cuece 12 minutos.",
      "Añade los chícharos y cocina 5 minutos más sin tapa, hasta que la papa esté tierna y quede poco líquido."],
  tp:["Dorar la carne en una capa sin moverla le da el sabor tostado; revuelta desde el principio solo se cuece en su jugo.",
      "Cubos pequeños de verdura para que se cuezan al mismo tiempo que se reduce la salsa."],
  v:"picadillo mexicano receta"},
 en:{n:"Mexican Picadillo", b:"Ground beef stewed with tomato, potato, carrot and peas. Home cooking: over rice, in tacos or to stuff chiles.",
  st:["Brown the meat in the oil over high heat for 8 minutes, not stirring at first, until it releases its juices and browns.",
      "Add the onion, garlic and serrano and cook 4 minutes.",
      "Add the blended tomato and the cumin and cook 5 minutes.",
      "Add the potato, carrot, water and salt. Cover and cook 12 minutes.",
      "Add the peas and cook 5 minutes more uncovered, until the potato is tender and little liquid remains."],
  tp:["Browning the meat in one layer without stirring gives it the toasted flavor; stirred from the start it just stews in its juices.",
      "Small dice so the vegetables cook in the time it takes the sauce to reduce."],
  v:"mexican picadillo recipe"}}
];
