module.exports = [
{id:"chilaquiles-verdes", c:"Mexico", r:"latin-america", m:"breakfast", t:35, s:4,
 i:[[12,"","corntortilla","structure","tortillas de maíz","corn tortillas","del día anterior, en triángulos","day-old, cut in triangles"],
    [250,"ml","oil","fat","aceite","oil","para freír","for frying"],
    [500,"g","tomatillo","acid","tomates verdes (tomatillos)","tomatillos","sin cáscara","husked"],
    [2,"","chilli","aromatic","chiles serranos","serrano chiles"],
    [0.5,"","onion","aromatic","cebolla blanca","white onion"],
    [1,"clove","garlic","aromatic","ajo","garlic"],
    [1,"bunch","herb","aromatic","cilantro","cilantro"],
    [250,"ml","stock","liquid","caldo de pollo","chicken stock"],
    [1,"tsp","salt","salt","sal","salt"],
    [120,"ml","crema","fat","crema mexicana","Mexican crema"],
    [80,"g","queso","garnish","queso fresco","queso fresco","desmoronado","crumbled"],
    [0.5,"","onion","garnish","cebolla morada","red onion","en aros finos","thinly sliced"],
    [4,"","egg","protein","huevos","eggs","fritos, opcional","fried, optional"]],
 es:{n:"Chilaquiles verdes", b:"Totopos fritos que se bañan en salsa verde hirviendo justo antes de servir. El truco está en el tiempo: tienen que ablandarse por fuera y seguir crujiendo por dentro.",
  st:["Fríe los triángulos de tortilla en tandas en aceite a 180 °C hasta que dejen de burbujear y estén dorados. Escúrrelos sobre papel y sálalos.",
      "Hierve los tomatillos, los serranos, la cebolla y el ajo en agua 8 minutos, hasta que los tomatillos cambien de verde brillante a verde oliva.",
      "Lícualos con el cilantro, la sal y la mitad del caldo.",
      "Calienta 1 cucharada del aceite de freír en una sartén amplia y vierte la salsa: debe chisporrotear. Cocina 5 minutos hasta que oscurezca un tono, añadiendo el resto del caldo.",
      "Con la salsa hirviendo, echa los totopos y mueve 1 minuto, solo hasta cubrirlos.",
      "Sirve de inmediato con crema, queso, cebolla morada y el huevo encima."],
  tp:["Tortilla de ayer, no de hoy: la tortilla fresca tiene más agua, absorbe aceite y queda correosa.",
      "Freír la salsa es lo que le da fondo. Sin ese paso sabe a crudo.",
      "Si los preparas con antelación, guarda totopos y salsa por separado."],
  v:"chilaquiles verdes receta"},
 en:{n:"Chilaquiles Verdes", b:"Fried tortilla chips tossed in boiling-hot green salsa right before serving. Timing is everything: they should soften on the outside and still crunch inside.",
  st:["Fry the tortilla triangles in batches in oil at 180 °C until they stop bubbling and turn golden. Drain on paper and salt them.",
      "Boil the tomatillos, serranos, onion and garlic in water for 8 minutes, until the tomatillos turn from bright green to olive.",
      "Blend them with the cilantro, the salt and half the stock.",
      "Heat 1 tablespoon of the frying oil in a wide skillet and pour in the salsa: it should sputter. Cook 5 minutes until it darkens a shade, adding the rest of the stock.",
      "With the salsa boiling, add the chips and toss for 1 minute, just until coated.",
      "Serve right away with crema, queso fresco, red onion and the egg on top."],
  tp:["Yesterday's tortillas, not today's: fresh ones hold more water, soak up oil and turn leathery.",
      "Frying the salsa is what gives it depth. Skip it and it tastes raw.",
      "If making ahead, keep the chips and salsa separate."],
  v:"chilaquiles verdes recipe"}},

{id:"mole-poblano", c:"Mexico", r:"latin-america", m:"main", t:240, s:10,
 i:[[2000,"g","turkey","protein","pavo o pollo en piezas","turkey or chicken pieces"],
    [6,"","ancho","aromatic","chiles anchos","ancho chiles","desvenados","stemmed and seeded"],
    [6,"","chilli","aromatic","chiles mulatos","mulato chiles","desvenados","stemmed and seeded"],
    [4,"","chilli","aromatic","chiles pasilla","pasilla chiles","desvenados","stemmed and seeded"],
    [2,"","chipotle","aromatic","chiles chipotle secos","dried chipotle chiles"],
    [120,"g","lard","fat","manteca de cerdo","lard"],
    [300,"g","tomato","aromatic","jitomates","tomatoes"],
    [150,"g","tomatillo","acid","tomatillos","tomatillos"],
    [1,"","onion","aromatic","cebolla blanca","white onion","en cuartos","quartered"],
    [6,"clove","garlic","aromatic","ajo","garlic"],
    [50,"g","almond","crunch","almendras","almonds"],
    [50,"g","peanut","crunch","cacahuates","peanuts"],
    [40,"g","sesameseed","crunch","ajonjolí","sesame seeds","más un poco para servir","plus extra to serve"],
    [40,"g","driedfruit","sweet","pasas","raisins"],
    [1,"","plantain","sweet","plátano macho maduro","ripe plantain","en rodajas","sliced"],
    [1,"","corntortilla","thicken","tortilla de maíz","corn tortilla","seca","stale"],
    [1,"slice","bread","thicken","bolillo o pan blanco","bolillo or white bread"],
    [90,"g","tablechocolate","sweet","chocolate de mesa","Mexican table chocolate"],
    [1,"tsp","spice","aromatic","canela en raja, anís, clavo y pimienta gorda","cinnamon stick, anise, cloves and allspice"],
    [2000,"ml","stock","liquid","caldo de pollo o de pavo","chicken or turkey stock"],
    [2,"tbsp","sugar","sweet","azúcar","sugar"],
    [1,"tbsp","salt","salt","sal","salt"]],
 es:{n:"Mole poblano", b:"Unos veinte ingredientes, cada uno frito por separado, molidos y cocidos hasta que la salsa se vuelve una sola cosa. Es un día de trabajo y rinde para varios.",
  st:["Cuece el pavo en el caldo con sal a fuego bajo 1 hora. Reserva la carne y el caldo.",
      "Tuesta los chiles 20 segundos por lado en un comal: solo hasta que huelan. Remójalos en caldo caliente 20 minutos.",
      "En manteca, fríe por separado y hasta dorar: almendras, cacahuates, ajonjolí, pasas (hasta que se inflen), plátano, tortilla y pan. Cada uno tiene su tiempo; juntos se queman los chicos.",
      "Asa en el comal los jitomates, los tomatillos, la cebolla y el ajo hasta que tengan manchas negras.",
      "Licúa todo por tandas con los chiles, las especias y el caldo de remojo hasta tener una pasta muy fina. Pásala por un colador.",
      "Calienta 2 cucharadas de manteca en una cazuela gruesa hasta que humee y vierte la pasta: salpica fuerte. Fríela 15 minutos moviendo sin parar hasta que oscurezca y se espese.",
      "Añade el chocolate, el azúcar y caldo hasta que la salsa cubra una cuchara. Cuece a fuego bajo 1 hora, moviendo seguido, hasta que la grasa suba a la superficie.",
      "Rectifica de sal y de dulce, calienta el pavo en el mole y sirve con ajonjolí tostado."],
  tp:["Tostar los chiles de más los vuelve amargos, y ese amargor no se va. Veinte segundos bastan.",
      "Freír la pasta es el paso que convierte el licuado en mole. Si no salpica, el aceite está frío.",
      "Sabe mejor al día siguiente. Se congela bien hasta 3 meses."],
  v:"mole poblano tradicional"},
 en:{n:"Mole Poblano", b:"About twenty ingredients, each fried on its own, ground and simmered until the sauce becomes a single thing. It takes a day and feeds a crowd.",
  st:["Simmer the turkey in the stock with salt over low heat for 1 hour. Set aside the meat and the stock.",
      "Toast the chiles 20 seconds per side on a dry griddle: just until fragrant. Soak them in hot stock for 20 minutes.",
      "In lard, fry separately until golden: almonds, peanuts, sesame, raisins (until they puff), plantain, tortilla and bread. Each takes its own time; together, the small ones burn.",
      "Char the tomatoes, tomatillos, onion and garlic on the griddle until blackened in spots.",
      "Blend everything in batches with the chiles, spices and soaking stock into a very smooth paste. Push it through a sieve.",
      "Heat 2 tablespoons of lard in a heavy pot until smoking and pour in the paste: it will spatter hard. Fry it for 15 minutes, stirring constantly, until it darkens and thickens.",
      "Add the chocolate, sugar and enough stock that the sauce coats a spoon. Simmer over low heat for 1 hour, stirring often, until the fat rises to the surface.",
      "Adjust salt and sweetness, warm the turkey in the mole and serve with toasted sesame."],
  tp:["Over-toasted chiles turn bitter, and that bitterness never leaves. Twenty seconds is enough.",
      "Frying the paste is the step that turns a purée into mole. If it doesn't spatter, the fat is too cold.",
      "Better the next day. Freezes well for up to 3 months."],
  v:"mole poblano authentic recipe"}},

{id:"sopa-de-tortilla", c:"Mexico", r:"latin-america", m:"soup", t:45, s:4,
 i:[[8,"","corntortilla","crunch","tortillas de maíz","corn tortillas","en tiras","cut in strips"],
    [150,"ml","oil","fat","aceite","oil","para freír","for frying"],
    [400,"g","tomato","aromatic","jitomates","tomatoes"],
    [0.5,"","onion","aromatic","cebolla blanca","white onion"],
    [2,"clove","garlic","aromatic","ajo","garlic"],
    [2,"","chilli","aromatic","chiles pasilla","pasilla chiles","desvenados","stemmed and seeded"],
    [1200,"ml","stock","liquid","caldo de pollo","chicken stock"],
    [1,"sprig","herb","aromatic","epazote","epazote"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"","avocado","garnish","aguacate","avocado","en cubos","diced"],
    [100,"g","queso","garnish","queso fresco","queso fresco","en cubos","cubed"],
    [60,"ml","crema","garnish","crema mexicana","Mexican crema"],
    [1,"","citrus","acid","limón","lime","en gajos","in wedges"]],
 es:{n:"Sopa de tortilla", b:"Un caldo de jitomate asado con chile pasilla, servido sobre tiras de tortilla frita. Los acompañantes no son decoración: la sopa está pensada para ellos.",
  st:["Fríe las tiras de tortilla en aceite a 180 °C hasta que estén crujientes. Escúrrelas y sálalas.",
      "Fríe los chiles pasilla 10 segundos en el mismo aceite, hasta que se inflen. Reserva uno para decorar.",
      "Asa los jitomates, la cebolla y el ajo en un comal hasta que tengan manchas negras. Lícualos con los chiles y 250 ml del caldo.",
      "En una olla con 1 cucharada de aceite muy caliente, fríe el licuado 5 minutos hasta que espese y oscurezca.",
      "Añade el resto del caldo y el epazote, y cuece 15 minutos. Ajusta la sal.",
      "Reparte las tiras en platos hondos, vierte el caldo hirviendo encima y sirve con aguacate, queso, crema, el chile desmoronado y limón."],
  tp:["Las tiras van en el plato, no en la olla: si hierven con el caldo se deshacen.",
      "El epazote es el sabor que falta cuando esta sopa sabe \"casi bien\". Si no lo encuentras, usa un poco de orégano mexicano."],
  v:"sopa de tortilla receta"},
 en:{n:"Tortilla Soup", b:"A broth of charred tomato and pasilla chile ladled over fried tortilla strips. The toppings aren't decoration: the soup is built around them.",
  st:["Fry the tortilla strips in oil at 180 °C until crisp. Drain and salt them.",
      "Fry the pasilla chiles for 10 seconds in the same oil, until they puff. Keep one aside for garnish.",
      "Char the tomatoes, onion and garlic on a griddle until blackened in spots. Blend with the chiles and 250 ml of the stock.",
      "In a pot with 1 tablespoon of very hot oil, fry the purée for 5 minutes until it thickens and darkens.",
      "Add the rest of the stock and the epazote and simmer for 15 minutes. Adjust the salt.",
      "Divide the strips among deep bowls, pour the boiling broth over them and serve with avocado, cheese, crema, the crumbled chile and lime."],
  tp:["The strips go in the bowl, not the pot: boiled in the broth they fall apart.",
      "Epazote is the missing flavor when this soup tastes \"almost right\". If you can't find it, use a little Mexican oregano."],
  v:"sopa de tortilla recipe"}},

{id:"frijoles-de-la-olla", c:"Mexico", r:"latin-america", m:"side", t:150, s:6,
 i:[[500,"g","legume","protein","frijoles negros secos","dried black beans"],
    [2500,"ml","water","liquid","agua","water"],
    [0.5,"","onion","aromatic","cebolla blanca","white onion"],
    [2,"clove","garlic","aromatic","ajo","garlic"],
    [2,"sprig","herb","aromatic","epazote","epazote"],
    [1,"tbsp","lard","fat","manteca de cerdo","lard"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Frijoles de la olla", b:"Frijoles negros cocidos despacio con cebolla, ajo y epazote. El caldo espeso que sueltan vale tanto como el frijol.",
  st:["Enjuaga los frijoles y retira piedritas. Remojarlos es opcional: acorta la cocción unos 30 minutos.",
      "Ponlos en una olla con el agua, la cebolla, el ajo y la manteca. Hierve y baja a fuego muy bajo, con la tapa entreabierta.",
      "Cuece 2 horas, añadiendo agua caliente cuando el nivel baje de los frijoles.",
      "Cuando un frijol se aplaste fácil entre los dedos, añade la sal y el epazote y cuece 15 minutos más.",
      "Sirve con su caldo, o machácalos en manteca caliente para hacer frijoles refritos."],
  tp:["La sal al final: añadida al principio no los endurece, pero sí sala de más un caldo que se va a reducir.",
      "Agua caliente siempre: el agua fría corta la cocción y la piel se arruga."],
  v:"frijoles de la olla receta"},
 en:{n:"Frijoles de la Olla", b:"Black beans simmered slowly with onion, garlic and epazote. The thick broth they give off is worth as much as the beans.",
  st:["Rinse the beans and pick out any stones. Soaking is optional: it cuts about 30 minutes off the cooking.",
      "Put them in a pot with the water, onion, garlic and lard. Bring to a boil, then drop to very low heat with the lid ajar.",
      "Cook for 2 hours, adding hot water whenever the level drops below the beans.",
      "When a bean crushes easily between your fingers, add the salt and epazote and cook 15 minutes more.",
      "Serve with their broth, or mash them in hot lard for refried beans."],
  tp:["Salt at the end: early salt doesn't toughen them, but it over-seasons a broth that is going to reduce.",
      "Always hot water: cold water stalls the cooking and the skins wrinkle."],
  v:"frijoles de la olla recipe"}},

{id:"arroz-rojo", c:"Mexico", r:"latin-america", m:"side", t:40, s:6,
 i:[[400,"g","rice","structure","arroz de grano largo","long-grain rice"],
    [60,"ml","oil","fat","aceite","oil"],
    [300,"g","tomato","aromatic","jitomates","tomatoes"],
    [0.25,"","onion","aromatic","cebolla blanca","white onion"],
    [1,"clove","garlic","aromatic","ajo","garlic"],
    [700,"ml","stock","liquid","caldo de pollo","chicken stock"],
    [100,"g","veg","garnish","chícharos y zanahoria en cubos","peas and diced carrot"],
    [1,"","chilli","aromatic","chile serrano","serrano chile","entero","whole"],
    [2,"sprig","herb","aromatic","cilantro","cilantro"],
    [1.5,"tsp","salt","salt","sal","salt"]],
 es:{n:"Arroz rojo", b:"El arroz de las fondas mexicanas: primero se fríe hasta dorar y después se cuece en caldo de jitomate. Granos sueltos, nunca pastosos.",
  st:["Enjuaga el arroz hasta que el agua salga casi clara y déjalo escurrir 10 minutos.",
      "Lícua los jitomates, la cebolla y el ajo, y cuela el licuado.",
      "Fríe el arroz en el aceite a fuego medio, moviendo, 6-8 minutos, hasta que suene a arena y los granos estén dorados.",
      "Vierte el licuado: chisporrotea. Mueve hasta que se absorba casi del todo, 3 minutos.",
      "Añade el caldo caliente, la sal, las verduras, el chile y el cilantro. Hierve, tapa y baja al mínimo 18 minutos sin destapar.",
      "Apaga y deja reposar 5 minutos tapado. Esponja con un tenedor."],
  tp:["Freír el arroz sella el almidón de la superficie: por eso los granos quedan sueltos.",
      "Una vez tapado, no se mueve. Mover libera almidón y se hace engrudo."],
  v:"arroz rojo mexicano"},
 en:{n:"Mexican Red Rice", b:"The rice of Mexican fondas: fried until golden first, then cooked in tomato broth. Separate grains, never mushy.",
  st:["Rinse the rice until the water runs almost clear and let it drain for 10 minutes.",
      "Blend the tomatoes, onion and garlic, and strain the purée.",
      "Fry the rice in the oil over medium heat, stirring, for 6-8 minutes, until it sounds like sand and the grains are golden.",
      "Pour in the purée: it will sizzle. Stir until it's almost fully absorbed, 3 minutes.",
      "Add the hot stock, salt, vegetables, chile and cilantro. Bring to a boil, cover and cook on the lowest heat for 18 minutes without lifting the lid.",
      "Turn off the heat and rest 5 minutes covered. Fluff with a fork."],
  tp:["Frying the rice seals the starch on the surface: that's why the grains stay separate.",
      "Once covered, don't stir. Stirring releases starch and turns it to paste."],
  v:"mexican red rice recipe"}},

{id:"tinga-de-pollo", c:"Mexico", r:"latin-america", m:"main", t:50, s:6,
 i:[[800,"g","chicken","protein","pechuga de pollo","chicken breast"],
    [1,"","onion","aromatic","cebolla blanca","white onion","media para cocer, media en rodajas","half for poaching, half sliced"],
    [2,"clove","garlic","aromatic","ajo","garlic"],
    [2,"","herb","aromatic","hojas de laurel","bay leaves"],
    [500,"g","tomato","aromatic","jitomates","tomatoes"],
    [3,"","chipotleadobo","aromatic","chiles chipotle en adobo","chipotles in adobo","más 1 cda del adobo","plus 1 tbsp of the sauce"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"tsp","herb","aromatic","orégano mexicano","Mexican oregano"],
    [1.5,"tsp","salt","salt","sal","salt"],
    [12,"","corntortilla","serve","tostadas o tortillas de maíz","corn tostadas or corn tortillas","para servir","to serve"],
    [60,"ml","crema","garnish","crema","crema"]],
 es:{n:"Tinga de pollo", b:"Pollo deshebrado en una salsa de jitomate y chipotle con mucha cebolla. Ahumada, un poco dulce, y mejor sobre una tostada.",
  st:["Cuece el pollo con media cebolla, un diente de ajo, el laurel y sal en agua apenas hirviendo 20 minutos. Deja enfriar en el caldo y deshébralo.",
      "Lícua los jitomates, el otro ajo, los chipotles, el adobo y 120 ml del caldo de cocción.",
      "Sofríe la cebolla en rodajas en el aceite a fuego medio 8 minutos, hasta que esté blanda y transparente, sin dorar.",
      "Añade el licuado y el orégano y cuece 8 minutos, hasta que la salsa espese.",
      "Incorpora el pollo y cocina 5 minutos más, hasta que absorba casi toda la salsa pero siga jugoso.",
      "Sirve sobre tostadas con crema."],
  tp:["Enfriar el pollo en su caldo evita que se seque al deshebrarlo.",
      "La cebolla es la mitad del plato: no la escatimes."],
  v:"tinga de pollo receta"},
 en:{n:"Chicken Tinga", b:"Shredded chicken in a tomato and chipotle sauce with plenty of onion. Smoky, a little sweet, and best on a tostada.",
  st:["Poach the chicken with half the onion, one garlic clove, the bay and salt in barely simmering water for 20 minutes. Let it cool in the broth, then shred it.",
      "Blend the tomatoes, the other garlic clove, the chipotles, the adobo and 120 ml of the poaching broth.",
      "Cook the sliced onion in the oil over medium heat for 8 minutes, until soft and translucent, not browned.",
      "Add the purée and oregano and cook for 8 minutes, until the sauce thickens.",
      "Stir in the chicken and cook 5 minutes more, until it has absorbed most of the sauce but is still juicy.",
      "Serve on tostadas with crema."],
  tp:["Cooling the chicken in its broth keeps it from drying out when shredded.",
      "The onion is half the dish: don't skimp on it."],
  v:"chicken tinga recipe"}},

{id:"carnitas", c:"Mexico", r:"latin-america", m:"main", t:210, s:8,
 i:[[2000,"g","pork","protein","espaldilla de cerdo","pork shoulder","en trozos de 5 cm","in 5 cm chunks"],
    [500,"g","lard","fat","manteca de cerdo","lard"],
    [1,"","citrus","acid","naranja","orange","en mitades","halved"],
    [0.5,"","onion","aromatic","cebolla blanca","white onion"],
    [4,"clove","garlic","aromatic","ajo","garlic"],
    [2,"","herb","aromatic","hojas de laurel","bay leaves"],
    [1,"tsp","herb","aromatic","orégano mexicano","Mexican oregano"],
    [120,"ml","water","liquid","agua","water"],
    [1,"tbsp","salt","salt","sal","salt"]],
 es:{n:"Carnitas", b:"Cerdo confitado en su propia manteca hasta que se deshace, y dorado al final en la misma grasa. Michoacán en una olla.",
  st:["Sala la carne. En una olla de fondo grueso derrite la manteca y añade la carne, el agua, la naranja exprimida (con las cáscaras), la cebolla, el ajo y las hierbas.",
      "Cocina a fuego bajo, sin tapar, 2 horas y media. La grasa debe burbujear apenas, nunca freír fuerte.",
      "Cuando la carne se deshaga con una cuchara y el agua se haya evaporado, sube el fuego.",
      "Deja que se doren 10-15 minutos, moviendo de vez en cuando, hasta que los bordes estén crujientes y color caoba.",
      "Escurre, pica grueso y sirve en tortillas con cebolla, cilantro y salsa verde."],
  tp:["El agua al principio hace que la carne se cueza antes de freírse: sin ella se endurece por fuera.",
      "La manteca colada se guarda en el refrigerador y sirve para la siguiente tanda o para frijoles."],
  v:"carnitas michoacanas"},
 en:{n:"Carnitas", b:"Pork confited in its own lard until it falls apart, then browned in the same fat. Michoacán in a pot.",
  st:["Salt the meat. In a heavy pot, melt the lard and add the meat, water, squeezed orange (with the peels), onion, garlic and herbs.",
      "Cook over low heat, uncovered, for 2 and a half hours. The fat should barely bubble, never fry hard.",
      "When the meat falls apart with a spoon and the water has evaporated, turn up the heat.",
      "Let it brown for 10-15 minutes, stirring now and then, until the edges are crisp and mahogany.",
      "Drain, chop coarsely and serve in tortillas with onion, cilantro and salsa verde."],
  tp:["The water at the start lets the meat cook through before it fries: without it the outside toughens.",
      "Strained lard keeps in the fridge for the next batch or for beans."],
  v:"carnitas recipe michoacan"}},

{id:"esquites", c:"Mexico", r:"latin-america", m:"snack", t:20, s:4,
 i:[[4,"","corn","structure","elotes","ears of corn","desgranados","kernels cut off"],
    [30,"g","butter","fat","mantequilla","butter"],
    [1,"","chilli","aromatic","chile serrano","serrano chile","picado","chopped"],
    [1,"sprig","herb","aromatic","epazote","epazote"],
    [60,"g","mayo","sauce","mayonesa","mayonnaise"],
    [60,"g","cotija","garnish","queso cotija","cotija cheese","rallado","grated"],
    [1,"","citrus","acid","limón","lime"],
    [1,"tsp","chilliblend","garnish","chile piquín en polvo","ground piquín chile"],
    [0.5,"tsp","salt","salt","sal","salt"]],
 es:{n:"Esquites", b:"Granos de elote salteados en mantequilla con epazote, servidos en vaso con mayonesa, queso, limón y chile. El antojo de la esquina, hecho en casa.",
  st:["Derrite la mantequilla en una sartén amplia a fuego alto hasta que deje de espumar.",
      "Añade los granos en una sola capa y déjalos sin mover 2 minutos para que se tuesten. Mueve y repite 2 veces.",
      "Añade el serrano, el epazote, la sal y 60 ml de agua, y cocina 3 minutos hasta que se evapore.",
      "Sirve en vasos, con mayonesa, queso, limón y chile en polvo por encima."],
  tp:["Los granos deben tostarse, no cocerse: sartén grande y sin amontonar.",
      "Con elote congelado funciona; descongélalo y sécalo bien antes."],
  v:"esquites receta"},
 en:{n:"Esquites", b:"Corn kernels sautéed in butter with epazote, served in a cup with mayo, cheese, lime and chile. The street-corner snack, made at home.",
  st:["Melt the butter in a wide skillet over high heat until it stops foaming.",
      "Add the kernels in a single layer and leave them alone for 2 minutes so they toast. Stir and repeat 2 times.",
      "Add the serrano, epazote, salt and 60 ml of water, and cook for 3 minutes until it evaporates.",
      "Serve in cups topped with mayo, cheese, lime and chile powder."],
  tp:["The kernels should toast, not steam: big pan, no crowding.",
      "Frozen corn works; thaw it and dry it well first."],
  v:"esquites recipe"}},

{id:"agua-de-horchata", c:"Mexico", r:"latin-america", m:"drink", t:15, s:8,
 i:[[200,"g","rice","structure","arroz blanco crudo","raw white rice"],
    [1,"","spice","aromatic","raja de canela","cinnamon stick"],
    [1500,"ml","water","liquid","agua","water"],
    [150,"g","sugar","sweet","azúcar","sugar"],
    [1,"tsp","vanilla","aromatic","extracto de vainilla","vanilla extract"],
    [250,"ml","evaporatedmilk","enrich","leche evaporada","evaporated milk","opcional","optional"]],
 es:{n:"Agua de horchata", b:"Arroz remojado con canela, licuado y colado. Fresca, cremosa y sin nada de leche si no quieres: la leche evaporada es opcional.",
  st:["Remoja el arroz con la canela troceada en 750 ml del agua al menos 8 horas.",
      "Lícualo todo 2 minutos, hasta que no queden granos visibles.",
      "Cuélalo por una manta de cielo o un colador muy fino, exprimiendo bien.",
      "Añade el resto del agua, el azúcar, la vainilla y la leche evaporada si la usas. Mezcla y enfría.",
      "Sirve con mucho hielo y remueve antes de servir: el almidón se asienta."],
  tp:["El tiempo de remojo es lo que hace cremosa la horchata. Menos de 8 horas y queda arenosa.",
      "Sin leche evaporada es apta para dieta sin lácteos."],
  v:"agua de horchata receta"},
 en:{n:"Horchata", b:"Rice soaked with cinnamon, blended and strained. Cool, creamy and dairy-free if you want it to be: the evaporated milk is optional.",
  st:["Soak the rice with the broken cinnamon in 750 ml of the water for at least 8 hours.",
      "Blend it all for 2 minutes, until no grains are visible.",
      "Strain through cheesecloth or a very fine sieve, squeezing hard.",
      "Add the rest of the water, the sugar, the vanilla and the evaporated milk if using. Stir and chill.",
      "Serve over lots of ice and stir before pouring: the starch settles."],
  tp:["The soaking time is what makes horchata creamy. Less than 8 hours and it's gritty.",
      "Without the evaporated milk it's dairy-free."],
  v:"horchata recipe mexican"}},

{id:"huevos-rancheros", c:"Mexico", r:"latin-america", m:"breakfast", t:25, s:2,
 i:[[4,"","corntortilla","structure","tortillas de maíz","corn tortillas"],
    [4,"","egg","protein","huevos","eggs"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [300,"g","tomato","aromatic","jitomates","tomatoes"],
    [1,"","chilli","aromatic","chile serrano","serrano chile"],
    [0.25,"","onion","aromatic","cebolla blanca","white onion"],
    [1,"clove","garlic","aromatic","ajo","garlic"],
    [0.5,"tsp","salt","salt","sal","salt"],
    [150,"g","refriedbeans","serve","frijoles refritos","refried beans","opcional","optional"],
    [1,"sprig","herb","garnish","cilantro","cilantro"]],
 es:{n:"Huevos rancheros", b:"Huevos estrellados sobre tortillas pasadas por aceite, bañados en salsa ranchera caliente. Un desayuno de rancho que no necesita más.",
  st:["Asa los jitomates, el chile, la cebolla y el ajo en un comal hasta que tengan manchas negras. Lícualos con la sal sin que quede totalmente liso.",
      "Fríe la salsa en 1 cucharada de aceite 5 minutos, hasta que cambie a un rojo más oscuro.",
      "Pasa las tortillas por aceite caliente 10 segundos por lado, para que se ablanden sin endurecerse. Escúrrelas.",
      "Fríe los huevos en el mismo aceite, rociando la clara con la grasa hasta que cuaje y la yema siga líquida.",
      "Pon dos tortillas por plato, los huevos encima y cúbrelos de salsa, dejando la yema a la vista. Sirve con frijoles y cilantro."],
  tp:["La salsa va caliente: fría endurece la tortilla.",
      "Rociar la clara con aceite cuaja la parte de arriba sin voltear el huevo."],
  v:"huevos rancheros receta"},
 en:{n:"Huevos Rancheros", b:"Fried eggs on oil-softened tortillas, smothered in hot ranchera sauce. A ranch breakfast that needs nothing else.",
  st:["Char the tomatoes, chile, onion and garlic on a griddle until blackened in spots. Blend with the salt, leaving it a little rough.",
      "Fry the salsa in 1 tablespoon of oil for 5 minutes, until it turns a darker red.",
      "Pass the tortillas through hot oil for 10 seconds per side, so they soften without crisping. Drain.",
      "Fry the eggs in the same oil, basting the whites with fat until set while the yolks stay runny.",
      "Put two tortillas on each plate, the eggs on top and cover with salsa, leaving the yolks showing. Serve with beans and cilantro."],
  tp:["The salsa goes on hot: cold, it stiffens the tortilla.",
      "Basting the whites with oil sets the top without flipping the egg."],
  v:"huevos rancheros recipe"}}
];
