module.exports = [
{id:"papadzules", c:"Mexico", r:"latin-america", m:"main", t:50, s:4,
 i:[[200,"g","seeds","structure","pepitas de calabaza peladas","hulled pumpkin seeds"],
    [300,"ml","water","liquid","agua caliente","hot water"],
    [1,"sprig","herb","aromatic","epazote","epazote"],
    [1,"tsp","salt","salt","sal","salt"],
    [12,"","corntortilla","structure","tortillas de maíz","corn tortillas"],
    [6,"","egg","protein","huevos duros","hard-boiled eggs","picados","chopped"],
    [4,"","tomato","sauce","tomates","tomatoes"],
    [0.5,"","onion","aromatic","cebolla","onion"],
    [1,"","chilli","aromatic","chile habanero","habanero chilli"],
    [1,"tbsp","oil","fat","aceite","oil"]],
 es:{n:"Papadzules", b:"Tortillas rellenas de huevo duro y bañadas en salsa de pepita, con salsa de tomate y habanero. Plato maya de Yucatán.",
  st:["Tuesta las pepitas en un comal 4 minutos. Muélelas con el agua caliente, el epazote y la sal hasta tener una salsa cremosa.",
      "Asa los tomates, la cebolla y el habanero 8 minutos. Licúa y cuece en el aceite 5 minutos.",
      "Calienta las tortillas y pásalas por la salsa de pepita tibia.",
      "Rellena con el huevo y enrolla.",
      "Baña con el resto de la salsa de pepita y la salsa de tomate encima."],
  tp:["No calientes demasiado la salsa de pepita o se corta.",
      "Quita las semillas del habanero si la quieres menos picante."],
  v:"papadzules yucatecos receta"},
 en:{n:"Papadzules (Yucatecan Egg Enchiladas)", b:"Tortillas filled with hard-boiled egg in pumpkin-seed sauce, topped with tomato and habanero sauce. A Mayan dish from Yucatán.",
  st:["Toast the pumpkin seeds on a griddle for 4 minutes. Grind with the hot water, epazote and salt to a creamy sauce.",
      "Char the tomatoes, onion and habanero for 8 minutes. Blend and fry in the oil for 5 minutes.",
      "Warm the tortillas and dip them in the warm seed sauce.",
      "Fill with the egg and roll up.",
      "Pour over the rest of the seed sauce and the tomato sauce on top."],
  tp:["Don't overheat the seed sauce or it splits.",
      "Seed the habanero for less heat."],
  v:"papadzules recipe"}},

{id:"huevos-motulenos", c:"Mexico", r:"latin-america", m:"breakfast", t:30, s:4,
 i:[[4,"","corntortilla","structure","tortillas de maíz","corn tortillas"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [300,"g","refriedbeans","structure","frijoles negros refritos","refried black beans"],
    [8,"","egg","protein","huevos","eggs"],
    [3,"","tomato","sauce","tomates","tomatoes"],
    [0.5,"","onion","aromatic","cebolla","onion"],
    [1,"","chilli","aromatic","chile habanero","habanero chilli"],
    [100,"g","ham","protein","jamón cocido","cooked ham","en dados","diced"],
    [80,"g","legume","structure","chícharos","peas"],
    [80,"g","queso","garnish","queso fresco","fresh cheese","desmenuzado","crumbled"],
    [1,"","plantain","garnish","plátano macho maduro","ripe plantain","en rodajas, frito","sliced, fried"]],
 es:{n:"Huevos motuleños", b:"Tortilla frita con frijol, huevo estrellado, salsa de tomate, jamón, chícharos y plátano. El desayuno de Motul, Yucatán.",
  st:["Asa los tomates, la cebolla y el habanero, licúa y cuece en 1 cucharada de aceite 5 minutos con los chícharos y el jamón.",
      "Fríe las tortillas en el resto del aceite hasta que estén crujientes.",
      "Unta cada tortilla con frijoles.",
      "Fríe los huevos y pon dos sobre cada tortilla.",
      "Baña con la salsa y termina con el queso y el plátano."],
  tp:["Calienta bien los frijoles para que el plato llegue caliente a la mesa.",
      "Quita las semillas del habanero si la quieres menos picante."],
  v:"huevos motuleños receta"},
 en:{n:"Huevos Motuleños (Yucatán Breakfast Eggs)", b:"Fried tortilla with beans, fried eggs, tomato sauce, ham, peas and plantain. Breakfast from Motul, Yucatán.",
  st:["Char the tomatoes, onion and habanero, blend and fry in 1 tablespoon of oil for 5 minutes with the peas and ham.",
      "Fry the tortillas in the rest of the oil until crisp.",
      "Spread each tortilla with beans.",
      "Fry the eggs and put two on each tortilla.",
      "Pour over the sauce and finish with the cheese and plantain."],
  tp:["Heat the beans well so the plate reaches the table hot.",
      "Seed the habanero for less heat."],
  v:"huevos motulenos recipe"}},

{id:"torta-ahogada", c:"Mexico", r:"latin-america", m:"main", t:40, s:4,
 i:[[4,"","bread","structure","birotes o bolillos salados","birote or crusty rolls"],
    [600,"g","pork","protein","pierna de cerdo cocida y dorada","cooked, browned pork leg","deshebrada","shredded"],
    [4,"","tomato","sauce","tomates","tomatoes"],
    [1,"clove","garlic","aromatic","ajo","garlic"],
    [0.5,"","onion","aromatic","cebolla","onion"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [1,"tsp","salt","salt","sal","salt"],
    [15,"","chilli","sauce","chiles de árbol secos","dried árbol chillies"],
    [100,"ml","whitevinegar","acid","vinagre blanco","white vinegar"],
    [1,"","onion","garnish","cebolla morada","red onion","en aros","in rings"],
    [2,"","citrus","acid","limones","limes","en jugo","juiced"]],
 es:{n:"Torta ahogada", b:"Birote relleno de carnitas y ahogado en salsa de tomate y otra de chile de árbol. El antojo de Guadalajara.",
  st:["Mezcla la cebolla morada con el jugo de limón y una pizca de sal.",
      "Cuece los tomates, el ajo y la media cebolla en agua 10 minutos. Licúa con el orégano y la sal y calienta.",
      "Tuesta los chiles 30 segundos, remójalos 10 minutos y licúalos con el vinagre y una pizca de sal.",
      "Abre los birotes y rellena con el cerdo caliente.",
      "Baña cada torta con la salsa de tomate, añade salsa de chile al gusto y la cebolla encima."],
  tp:["El birote de Guadalajara tiene corteza dura que aguanta la salsa; un bolillo bien tostado sirve.",
      "La salsa de chile de árbol pica mucho: ponla poco a poco."],
  v:"torta ahogada tapatía receta"},
 en:{n:"Torta Ahogada (Drowned Pork Sandwich)", b:"A birote roll filled with carnitas and drowned in tomato sauce and árbol chilli sauce. Guadalajara's favourite snack.",
  st:["Mix the red onion with the lime juice and a pinch of salt.",
      "Boil the tomatoes, garlic and half onion in water for 10 minutes. Blend with the oregano and salt and heat.",
      "Toast the chillies 30 seconds, soak 10 minutes and blend with the vinegar and a pinch of salt.",
      "Split the rolls and fill with the hot pork.",
      "Drench each torta in the tomato sauce, add chilli sauce to taste and top with the onion."],
  tp:["Guadalajara's birote has a hard crust that stands up to the sauce; a well-toasted crusty roll works.",
      "The árbol chilli sauce is very hot: add it gradually."],
  v:"torta ahogada recipe"}},

{id:"pescado-zarandeado", c:"Mexico", r:"latin-america", m:"main", t:50, s:4,
 i:[[1.5,"kg","whitefish","protein","pargo o huachinango entero","whole red snapper","abierto en mariposa","butterflied"],
    [4,"","chilli","sauce","chiles guajillo","guajillo chillies","sin semillas, remojados","seeded, soaked"],
    [3,"clove","garlic","aromatic","ajo","garlic"],
    [3,"tbsp","soysauce","umami","salsa de soya","soy sauce"],
    [3,"tbsp","mayo","fat","mayonesa","mayonnaise"],
    [2,"","citrus","acid","limones","limes","en jugo","juiced"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Pescado zarandeado", b:"Pescado entero abierto, untado de adobo de guajillo y asado a la brasa en una rejilla. De Nayarit y Sinaloa.",
  st:["Licúa los chiles, el ajo, la salsa de soya, la mayonesa, el jugo de limón y la sal.",
      "Unta el pescado abierto por el lado de la carne con la mitad del adobo.",
      "Colócalo en una rejilla doble y ásalo con la piel hacia el fuego 15 minutos.",
      "Voltea, unta el resto del adobo y asa 10 minutos más, hasta que la carne se separe fácilmente.",
      "Sirve entero con tortillas, cebolla y pepino."],
  tp:["La rejilla doble permite voltearlo sin que se rompa.",
      "En horno, asa a 220 °C durante 25 minutos con la piel hacia abajo."],
  v:"pescado zarandeado nayarit receta"},
 en:{n:"Pescado Zarandeado (Grilled Butterflied Fish)", b:"A whole butterflied fish brushed with guajillo marinade and grilled over coals in a basket. From Nayarit and Sinaloa.",
  st:["Blend the chillies, garlic, soy sauce, mayonnaise, lime juice and salt.",
      "Brush the flesh side of the fish with half the marinade.",
      "Put it in a hinged grill basket and grill skin side to the fire for 15 minutes.",
      "Turn, brush with the rest of the marinade and grill 10 minutes more, until the flesh flakes easily.",
      "Serve whole with tortillas, onion and cucumber."],
  tp:["The hinged basket lets you turn it without breaking it.",
      "In the oven, bake at 220 °C for 25 minutes skin side down."],
  v:"pescado zarandeado recipe"}},

{id:"mixiotes", c:"Mexico", r:"latin-america", m:"main", t:210, s:6,
 i:[[1.5,"kg","lamb","protein","pierna de carnero o cordero","lamb leg","en trozos","in pieces"],
    [4,"","chilli","sauce","chiles guajillo","guajillo chillies","sin semillas","seeded"],
    [2,"","ancho","sauce","chiles anchos","ancho chillies","sin semillas","seeded"],
    [4,"clove","garlic","aromatic","ajo","garlic"],
    [1,"tsp","spice","aromatic","comino","cumin"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [3,"tbsp","whitevinegar","acid","vinagre blanco","white vinegar"],
    [2,"tsp","salt","salt","sal","salt"],
    [6,"leaf","herb","aromatic","hojas de aguacate","avocado leaves"],
    [6,"piece","veg","structure","hojas de mixiote o papel para hornear","mixiote sheets or baking paper"]],
 es:{n:"Mixiotes de carnero", b:"Carne en adobo de chiles envuelta en paquetes y cocida al vapor hasta deshacerse. Del centro de México.",
  st:["Remoja los chiles en agua caliente 15 minutos. Licúa con el ajo, el comino, el orégano, el vinagre y la sal.",
      "Marina la carne en el adobo al menos 4 horas.",
      "Pon carne y una hoja de aguacate en el centro de cada hoja de mixiote o papel. Cierra como bolsita y ata.",
      "Cuece al vapor 2 horas y media, hasta que la carne esté muy suave.",
      "Sirve en su paquete con tortillas calientes."],
  tp:["Las hojas de aguacate dan un aroma anisado; tuéstalas un poco antes.",
      "Con pollo, basta 1 hora de vapor."],
  v:"mixiotes de carnero receta"},
 en:{n:"Mixiotes (Steamed Chilli Lamb Parcels)", b:"Meat in chilli marinade wrapped in parcels and steamed until falling apart. From central Mexico.",
  st:["Soak the chillies in hot water for 15 minutes. Blend with the garlic, cumin, oregano, vinegar and salt.",
      "Marinate the meat in the sauce for at least 4 hours.",
      "Put meat and an avocado leaf in the centre of each mixiote sheet or paper. Gather into a pouch and tie.",
      "Steam 2 and a half hours, until the meat is very tender.",
      "Serve in their parcels with warm tortillas."],
  tp:["Avocado leaves give an anise aroma; toast them lightly first.",
      "With chicken, 1 hour of steaming is enough."],
  v:"mixiotes recipe"}},

{id:"elotes-asados", c:"Mexico", r:"latin-america", m:"snack", t:25, s:4,
 i:[[4,"","corn","structure","elotes","corn cobs","sin hojas","husked"],
    [30,"g","butter","fat","mantequilla derretida","melted butter"],
    [4,"tbsp","mayo","enrich","mayonesa","mayonnaise"],
    [80,"g","cotija","garnish","queso cotija","cotija cheese","rallado","grated"],
    [2,"tsp","chilli","garnish","chile en polvo","chilli powder"],
    [2,"","citrus","acid","limones","limes","en gajos","in wedges"]],
 es:{n:"Elotes asados", b:"Elote asado en brasa, con mayonesa, queso cotija, chile en polvo y limón. De los puestos de la calle.",
  st:["Asa los elotes a fuego medio 12 minutos, girándolos, hasta que tengan manchas tostadas.",
      "Pinta con la mantequilla.",
      "Unta cada elote con mayonesa.",
      "Rueda por el queso cotija.",
      "Espolvorea el chile y sirve con el limón."],
  tp:["Clava un palo en la base para comerlo como paleta.",
      "Si no tienes parrilla, ásalos directo sobre la llama de la estufa."],
  v:"elotes asados callejeros"},
 en:{n:"Elotes (Mexican Street Corn)", b:"Grilled corn with mayonnaise, cotija cheese, chilli powder and lime. From the street stalls.",
  st:["Grill the cobs over medium heat for 12 minutes, turning, until charred in spots.",
      "Brush with the butter.",
      "Spread each cob with mayonnaise.",
      "Roll in the cotija.",
      "Sprinkle with the chilli and serve with the lime."],
  tp:["Push a stick into the base to eat it like a lolly.",
      "Without a grill, char them straight over a gas flame."],
  v:"mexican street corn recipe"}},

{id:"calabaza-en-tacha", c:"Mexico", r:"latin-america", m:"sweet", t:90, s:8,
 i:[[2,"kg","veg","structure","calabaza de Castilla","Mexican pumpkin","en trozos con cáscara","in chunks, skin on"],
    [500,"g","jaggery","sweet","piloncillo","piloncillo (unrefined cane sugar)"],
    [500,"ml","water","liquid","agua","water"],
    [3,"","spice","aromatic","ramas de canela","cinnamon sticks"],
    [1,"","citrus","aromatic","cáscara de naranja","orange peel"]],
 es:{n:"Calabaza en tacha", b:"Calabaza cocida en almíbar espeso de piloncillo con canela y naranja. Se come el Día de Muertos.",
  st:["Cuece el piloncillo con el agua, la canela y la naranja hasta que se disuelva.",
      "Pon la calabaza en una olla con la cáscara hacia abajo.",
      "Vierte el almíbar encima, tapa y cuece a fuego bajo 60 minutos.",
      "Destapa y cuece 20 minutos más, bañando la calabaza con el almíbar, hasta que esté brillante y oscura.",
      "Sirve tibia o fría con su almíbar."],
  tp:["Haz unos cortes en la pulpa para que el almíbar penetre.",
      "Se guarda 5 días en la nevera."],
  v:"calabaza en tacha receta"},
 en:{n:"Calabaza en Tacha (Candied Pumpkin)", b:"Pumpkin cooked in thick piloncillo syrup with cinnamon and orange. Eaten on the Day of the Dead.",
  st:["Simmer the piloncillo with the water, cinnamon and orange until dissolved.",
      "Arrange the pumpkin in a pot skin side down.",
      "Pour the syrup over, cover and cook on low for 60 minutes.",
      "Uncover and cook 20 minutes more, basting with the syrup, until glossy and dark.",
      "Serve warm or cold with its syrup."],
  tp:["Score the flesh so the syrup soaks in.",
      "Keeps 5 days in the fridge."],
  v:"candied pumpkin recipe"}},

{id:"cafe-de-olla", c:"Mexico", r:"latin-america", m:"drink", t:15, s:4,
 i:[[1,"l","water","liquid","agua","water"],
    [60,"g","jaggery","sweet","piloncillo","piloncillo (unrefined cane sugar)"],
    [1,"","spice","aromatic","rama de canela","cinnamon stick"],
    [2,"","spice","aromatic","clavos de olor","whole cloves"],
    [50,"g","coffee","structure","café molido grueso","coarse-ground coffee"]],
 es:{n:"Café de olla", b:"Café hervido en olla de barro con piloncillo, canela y clavo. Dulce y especiado, de mañana en el campo.",
  st:["Hierve el agua con el piloncillo, la canela y los clavos 5 minutos.",
      "Retira del fuego y añade el café.",
      "Tapa y deja reposar 5 minutos.",
      "Cuela.",
      "Sirve caliente, idealmente en jarritos de barro."],
  tp:["No hiervas el café: se amarga.",
      "Una tira de cáscara de naranja le va bien."],
  v:"café de olla receta"},
 en:{n:"Café de Olla (Spiced Pot Coffee)", b:"Coffee brewed in a clay pot with piloncillo, cinnamon and clove. Sweet and spiced, for country mornings.",
  st:["Boil the water with the piloncillo, cinnamon and cloves for 5 minutes.",
      "Take off the heat and add the coffee.",
      "Cover and leave 5 minutes.",
      "Strain.",
      "Serve hot, ideally in clay mugs."],
  tp:["Don't boil the coffee: it turns bitter.",
      "A strip of orange peel suits it well."],
  v:"cafe de olla recipe"}},

{id:"ponche-navideno", c:"Mexico", r:"latin-america", m:"drink", t:60, s:10,
 i:[[3,"l","water","liquid","agua","water"],
    [250,"g","jaggery","sweet","piloncillo","piloncillo (unrefined cane sugar)"],
    [3,"","spice","aromatic","ramas de canela","cinnamon sticks"],
    [20,"g","herb","aromatic","flor de jamaica","dried hibiscus"],
    [300,"g","fruit","structure","tejocotes","tejocotes (Mexican hawthorn)"],
    [6,"","fruit","structure","guayabas","guavas","en cuartos","quartered"],
    [2,"","fruit","structure","manzanas","apples","en dados","diced"],
    [2,"","sugar","structure","trozos de caña de azúcar","sugarcane sticks","pelados, en tiras","peeled, in strips"],
    [100,"g","driedfruit","sweet","ciruelas pasas","prunes"],
    [1,"","citrus","aromatic","naranja","orange","en rodajas","sliced"]],
 es:{n:"Ponche navideño", b:"Bebida caliente de frutas de temporada con piloncillo y canela. El olor de las posadas en México.",
  st:["Hierve el agua con la canela y la jamaica 10 minutos. Cuela la jamaica.",
      "Añade los tejocotes y el piloncillo y cuece 15 minutos.",
      "Pela los tejocotes, quítales la semilla y regrésalos a la olla.",
      "Añade la guayaba, la manzana, la caña, las ciruelas y la naranja.",
      "Cuece a fuego bajo 30 minutos. Sirve caliente con fruta en cada taza."],
  tp:["Los tejocotes se pelan fácil después de cocerlos.",
      "Sin tejocotes, usa más manzana y guayaba."],
  v:"ponche navideño receta"},
 en:{n:"Ponche Navideño (Mexican Christmas Punch)", b:"A hot drink of seasonal fruit with piloncillo and cinnamon. The smell of the posadas in Mexico.",
  st:["Boil the water with the cinnamon and hibiscus for 10 minutes. Strain out the hibiscus.",
      "Add the tejocotes and piloncillo and cook 15 minutes.",
      "Peel the tejocotes, remove the seeds and return them to the pot.",
      "Add the guava, apple, sugarcane, prunes and orange.",
      "Simmer 30 minutes. Serve hot with fruit in every cup."],
  tp:["Tejocotes peel easily once cooked.",
      "Without tejocotes, use more apple and guava."],
  v:"mexican christmas punch recipe"}},

{id:"panuchos", c:"Mexico", r:"latin-america", m:"main", t:60, s:4,
 i:[[300,"g","masa","structure","harina de maíz nixtamalizado","masa harina"],
    [350,"ml","water","liquid","agua tibia","warm water"],
    [200,"g","refriedbeans","structure","frijoles negros refritos","refried black beans"],
    [500,"ml","oil","fat","aceite para freír","oil for frying"],
    [400,"g","chicken","protein","pollo cocido","cooked chicken","deshebrado","shredded"],
    [2,"","citrus","acid","naranjas agrias (o 1 naranja y 1 limón)","sour oranges (or 1 orange and 1 lime)","en jugo","juiced"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [1,"","onion","garnish","cebolla morada","red onion","en aros finos","in thin rings"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"","avocado","garnish","aguacate","avocado","en rebanadas","sliced"],
    [2,"","tomato","garnish","tomates","tomatoes","en rodajas","sliced"],
    [4,"leaf","veg","garnish","hojas de lechuga","lettuce leaves","en tiras","shredded"]],
 es:{n:"Panuchos", b:"Tortillas infladas rellenas de frijol negro, fritas y cubiertas con pollo, cebolla encurtida y aguacate. De Yucatán.",
  st:["Mezcla la cebolla con la mitad del jugo de naranja y la sal. Mezcla el pollo con el resto del jugo y el orégano.",
      "Mezcla la harina con el agua y forma 8 tortillas. Cuécelas en el comal hasta que se inflen.",
      "Abre con cuidado la capa superior de cada tortilla inflada y mete una cucharada de frijoles. Cierra presionando.",
      "Fríe en el aceite a 180 °C durante 2 minutos, hasta que estén crujientes.",
      "Cubre con la lechuga, el pollo, el tomate, el aguacate y la cebolla."],
  tp:["Si la tortilla no se infla, dale un golpecito con la espátula en el comal.",
      "Escurre bien los panuchos para que no queden grasosos."],
  v:"panuchos yucatecos receta"},
 en:{n:"Panuchos (Bean-Stuffed Fried Tortillas)", b:"Puffed tortillas stuffed with black beans, fried and topped with chicken, pickled onion and avocado. From Yucatán.",
  st:["Mix the onion with half the orange juice and the salt. Mix the chicken with the rest of the juice and the oregano.",
      "Mix the masa harina with the water and shape 8 tortillas. Cook on the griddle until they puff.",
      "Carefully open the top layer of each puffed tortilla and slip in a spoonful of beans. Press to close.",
      "Fry in the oil at 180 °C for 2 minutes, until crisp.",
      "Top with the lettuce, chicken, tomato, avocado and onion."],
  tp:["If a tortilla won't puff, tap it with the spatula on the griddle.",
      "Drain the panuchos well so they aren't greasy."],
  v:"panuchos recipe"}}
];
