module.exports = [
{id:"tortillas-de-maiz", c:"Mexico", r:"latin-america", m:"bread", t:40, s:6,
 i:[[250,"g","masa","structure","harina de maíz nixtamalizado","masa harina"],
    [330,"ml","water","liquid","agua tibia","warm water"],
    [0.5,"tsp","salt","salt","sal","salt"]],
 es:{n:"Tortillas de maíz", b:"Tortillas hechas en casa con harina de maíz nixtamalizado, agua y sal. Se inflan en el comal cuando la masa está bien.",
  st:["Mezcla la harina, la sal y el agua. Amasa 2 minutos, hasta que se sienta como plastilina y no se pegue.",
      "Tapa con un trapo húmedo y deja reposar 15 minutos.",
      "Calienta un comal a fuego medio-alto. Forma 16 bolas.",
      "Aplana cada bola en una prensa entre 2 hojas de plástico, a unos 2 milímetros.",
      "Cuece 30 segundos, voltea y cuece 1 minuto, voltea otra vez: debe inflarse. Presiona con un trapo si no se infla.",
      "Guárdalas apiladas en un trapo para que se suavicen con su propio vapor."],
  tp:["Si los bordes se agrietan al prensar, a la masa le falta agua.",
      "Si se pegan al plástico, le sobra agua: añade un poco de harina."],
  v:"tortillas de maiz hechas en casa receta"},
 en:{n:"Homemade Corn Tortillas", b:"Tortillas made at home with masa harina, water and salt. They puff on the griddle when the dough is right.",
  st:["Mix the masa harina, salt and water. Knead 2 minutes, until it feels like modelling clay and doesn't stick.",
      "Cover with a damp towel and rest 15 minutes.",
      "Heat a griddle over medium-high heat. Shape 16 balls.",
      "Flatten each ball in a press between 2 sheets of plastic, to about 2 millimetres.",
      "Cook 30 seconds, flip and cook 1 minute, flip again: it should puff. Press with a towel if it doesn't.",
      "Keep them stacked in a towel so they soften in their own steam."],
  tp:["If the edges crack when pressed, the dough needs more water.",
      "If it sticks to the plastic, it has too much: add a little masa harina."],
  v:"homemade corn tortillas recipe"}},

{id:"tortillas-de-harina", c:"Mexico", r:"latin-america", m:"bread", t:60, s:6,
 i:[[500,"g","apflour","structure","harina de trigo","all-purpose flour"],
    [100,"g","lard","fat","manteca de cerdo o vegetal","lard or vegetable shortening"],
    [1,"tsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [1.5,"tsp","salt","salt","sal","salt"],
    [250,"ml","water","liquid","agua caliente","hot water"]],
 es:{n:"Tortillas de harina", b:"Las tortillas suaves del norte, con manteca. Delgadas, con manchas doradas y dobladas sin romperse.",
  st:["Mezcla la harina, el polvo de hornear y la sal. Frota la manteca con los dedos hasta que parezca arena.",
      "Añade el agua caliente y amasa 5 minutos, hasta que la masa esté lisa.",
      "Forma 12 bolas, tapa y deja reposar 30 minutos.",
      "Extiende cada bola con rodillo en un círculo delgado de 20 centímetros.",
      "Cuece en un comal caliente sin grasa 30 segundos por lado, hasta que salgan burbujas y manchas doradas.",
      "Guárdalas en un trapo mientras haces las demás."],
  tp:["El reposo relaja el gluten: sin él la masa se encoge al estirarla.",
      "Con manteca vegetal quedan igual de suaves y sin cerdo."],
  v:"tortillas de harina receta"},
 en:{n:"Flour Tortillas", b:"The soft tortillas of northern Mexico, made with lard. Thin, spotted golden and they fold without cracking.",
  st:["Mix the flour, baking powder and salt. Rub in the lard with your fingertips until it looks like sand.",
      "Add the hot water and knead 5 minutes, until smooth.",
      "Shape 12 balls, cover and rest 30 minutes.",
      "Roll each ball into a thin 20 centimetre circle.",
      "Cook on a hot dry griddle for 30 seconds per side, until bubbles and golden spots appear.",
      "Keep them in a towel while you make the rest."],
  tp:["Resting relaxes the gluten: without it the dough shrinks back when rolled.",
      "Vegetable shortening makes them just as soft with no pork."],
  v:"flour tortillas recipe"}},

{id:"conchas", c:"Mexico", r:"latin-america", m:"bread", t:210, s:12, o:180,
 i:[[500,"g","breadflour","structure","harina de trigo de fuerza","bread flour"],
    [7,"g","yeast","leaven","levadura seca","instant yeast"],
    [100,"g","sugar","sweet","azúcar","sugar"],
    [1,"tsp","salt","salt","sal","salt"],
    [2,"","egg","binder","huevos","eggs"],
    [180,"ml","milk","liquid","leche tibia","warm milk"],
    [80,"g","butter","fat","mantequilla","butter","suave","soft"],
    [100,"g","apflour","structure","harina de trigo","all-purpose flour","para la cubierta","for the topping"],
    [100,"g","icingsugar","sweet","azúcar glas","powdered sugar","para la cubierta","for the topping"],
    [100,"g","shortening","fat","manteca vegetal","vegetable shortening","para la cubierta","for the topping"],
    [1,"tbsp","cocoa","aromatic","cacao en polvo","cocoa powder","opcional","optional"]],
 es:{n:"Conchas", b:"El pan dulce más querido de México: bollo suave de huevo y mantequilla con una costra de azúcar marcada como concha.",
  st:["Mezcla la harina de fuerza, la levadura, el azúcar y la sal. Añade los huevos y la leche y amasa 5 minutos.",
      "Añade la mantequilla en trozos y amasa 10 minutos más, hasta que la masa esté lisa y elástica.",
      "Tapa y deja crecer 90 minutos, hasta que doble su tamaño.",
      "Para la cubierta, mezcla la harina, el azúcar glas y la manteca vegetal hasta formar una pasta. Divide en 2 y añade el cacao a una mitad.",
      "Divide la masa en 12 bolas y ponlas en charolas con papel. Aplana 12 bolitas de cubierta entre plástico y cubre cada pan. Marca las rayas con un cuchillo.",
      "Deja crecer 60 minutos más. Calienta el horno a 180 °C.",
      "Hornea 18 a 20 minutos, hasta que la base esté dorada y la cubierta siga clara."],
  tp:["La cubierta no debe dorarse: si se oscurece, baja la charola una rejilla.",
      "Congeladas duran 1 mes; se recalientan 5 minutos en el horno."],
  v:"conchas pan dulce receta"},
 en:{n:"Conchas (Mexican Sweet Bread)", b:"Mexico's favourite sweet bread: a soft egg and butter bun with a sugar crust scored like a shell.",
  st:["Mix the bread flour, yeast, sugar and salt. Add the eggs and milk and knead 5 minutes.",
      "Add the butter in pieces and knead 10 minutes more, until smooth and elastic.",
      "Cover and let rise 90 minutes, until doubled.",
      "For the topping, mix the flour, powdered sugar and shortening into a paste. Divide in 2 and add the cocoa to one half.",
      "Divide the dough into 12 balls and set them on lined trays. Flatten 12 balls of topping between plastic and cover each bun. Score the lines with a knife.",
      "Let rise 60 minutes more. Heat the oven to 180 °C.",
      "Bake 18 to 20 minutes, until the base is golden and the topping still pale."],
  tp:["The topping shouldn't brown: if it darkens, move the tray down a rack.",
      "Frozen they keep 1 month; reheat 5 minutes in the oven."],
  v:"conchas recipe"}},

{id:"polvorones", c:"Mexico", r:"latin-america", m:"cookie", t:45, s:24, o:175,
 i:[[250,"g","apflour","structure","harina de trigo","all-purpose flour"],
    [200,"g","butter","fat","mantequilla","butter","suave","soft"],
    [60,"g","icingsugar","sweet","azúcar glas","powdered sugar","para la masa","for the dough"],
    [100,"g","pecan","crunch","nueces pecanas","pecans","molidas finas","finely ground"],
    [0.25,"tsp","salt","salt","sal","salt"],
    [1,"tsp","vanilla","aromatic","extracto de vainilla","vanilla extract"],
    [100,"g","icingsugar","sweet","azúcar glas","powdered sugar","para cubrir","for coating"]],
 es:{n:"Polvorones de nuez", b:"Bolitas de mantequilla y nuez pecana que se deshacen en la boca, revolcadas en azúcar glas. Las galletas de las bodas.",
  st:["Calienta el horno a 175 °C.",
      "Bate la mantequilla con el azúcar glas de la masa y la vainilla hasta que esté cremosa.",
      "Añade la harina, las nueces y la sal. Mezcla solo hasta integrar.",
      "Forma 24 bolitas y ponlas en una charola con papel.",
      "Hornea 15 minutos, hasta que la base apenas se dore.",
      "Deja enfriar 5 minutos y revuélcalas en el azúcar glas. Cuando estén frías, revuélcalas otra vez."],
  tp:["Tibias se rompen: espera los 5 minutos antes de la primera capa de azúcar.",
      "Sin nueces, usa 100 gramos más de harina tostada en sartén hasta que huela a galleta."],
  v:"polvorones de nuez receta"},
 en:{n:"Mexican Wedding Cookies (Polvorones)", b:"Butter and pecan balls that melt in the mouth, rolled in powdered sugar. The wedding cookie.",
  st:["Heat the oven to 175 °C.",
      "Beat the butter with the dough's powdered sugar and the vanilla until creamy.",
      "Add the flour, pecans and salt. Mix just until combined.",
      "Shape 24 balls and set them on a lined tray.",
      "Bake 15 minutes, until the bases barely colour.",
      "Cool 5 minutes, then roll in the powdered sugar. When cold, roll them again."],
  tp:["Warm, they break: wait the 5 minutes before the first coat of sugar.",
      "No nuts? Use 100 grams more flour toasted in a pan until it smells like cookies."],
  v:"mexican wedding cookies recipe"}},

{id:"capirotada", c:"Mexico", r:"latin-america", m:"sweet", t:75, s:8, o:180,
 i:[[6,"","bread","structure","bolillos del día anterior","day-old bolillo rolls","en rebanadas","sliced"],
    [60,"g","butter","fat","mantequilla","butter","derretida","melted"],
    [750,"ml","water","liquid","agua","water"],
    [250,"g","jaggery","sweet","piloncillo","piloncillo (unrefined cane sugar)"],
    [2,"","spice","aromatic","rajas de canela","cinnamon sticks"],
    [4,"","spice","aromatic","clavos de olor","cloves"],
    [100,"g","driedfruit","sweet","pasas","raisins"],
    [80,"g","peanut","crunch","cacahuates tostados","roasted peanuts"],
    [150,"g","cheese","protein","queso Cotija o añejo","Cotija or aged cheese","desmoronado","crumbled"],
    [1,"","plantain","sweet","plátano macho maduro","ripe plantain","en rodajas","sliced"]],
 es:{n:"Capirotada", b:"El budín de pan de Cuaresma: capas de bolillo tostado, miel de piloncillo con canela, pasas, cacahuate y queso salado.",
  st:["Calienta el horno a 180 °C. Unta el pan con la mantequilla y tuéstalo en charolas 10 minutos, hasta que esté dorado y seco.",
      "Hierve el agua con el piloncillo, la canela y el clavo 15 minutos, hasta que sea una miel ligera. Cuela.",
      "En un refractario, haz capas: pan, pasas, cacahuates, plátano y queso. Repite hasta terminar.",
      "Vierte la miel encima poco a poco, dejando que el pan la absorba.",
      "Tapa con aluminio y hornea 25 minutos. Destapa y hornea 10 minutos más.",
      "Deja reposar 15 minutos antes de servir, tibia o fría."],
  tp:["El pan debe estar bien seco o se deshace en la miel.",
      "El queso salado contra la miel es lo que la hace capirotada; no lo quites si puedes."],
  v:"capirotada receta"},
 en:{n:"Capirotada (Mexican Bread Pudding)", b:"The Lenten bread pudding: layers of toasted bolillo, piloncillo syrup with cinnamon, raisins, peanuts and salty cheese.",
  st:["Heat the oven to 180 °C. Butter the bread and toast it on trays for 10 minutes, until golden and dry.",
      "Boil the water with the piloncillo, cinnamon and cloves for 15 minutes, into a light syrup. Strain.",
      "In a baking dish, make layers: bread, raisins, peanuts, plantain and cheese. Repeat until used up.",
      "Pour the syrup over little by little, letting the bread soak it up.",
      "Cover with foil and bake 25 minutes. Uncover and bake 10 minutes more.",
      "Rest 15 minutes before serving, warm or cold."],
  tp:["The bread must be very dry or it falls apart in the syrup.",
      "Salty cheese against the syrup is what makes it capirotada; keep it if you can."],
  v:"capirotada recipe"}},

{id:"jericalla", c:"Mexico", r:"latin-america", m:"sweet", t:75, s:6, o:160,
 i:[[750,"ml","milk","liquid","leche entera","whole milk"],
    [1,"","spice","aromatic","raja de canela","cinnamon stick"],
    [1,"","vanillabean","aromatic","vaina de vainilla","vanilla pod","abierta","split"],
    [150,"g","sugar","sweet","azúcar","sugar"],
    [5,"","eggyolk","set","yemas de huevo","egg yolks"],
    [1,"","egg","set","huevo","egg"]],
 es:{n:"Jericalla", b:"El flan de Guadalajara con la superficie quemada. Leche con canela y vainilla cuajada con yemas, sin caramelo.",
  st:["Calienta la leche con la canela, la vainilla y el azúcar hasta que humee. Apaga y deja infusionar 15 minutos.",
      "Calienta el horno a 160 °C. Pon 6 moldes en un refractario.",
      "Bate las yemas y el huevo sin hacer espuma. Vierte la leche tibia poco a poco, batiendo. Cuela.",
      "Llena los moldes y vierte agua caliente en el refractario hasta la mitad de los moldes.",
      "Hornea 35 minutos, hasta que el centro tiemble apenas.",
      "Pásalos a la parte alta del horno con el grill encendido 3 a 5 minutos, hasta que la superficie tenga manchas oscuras. Enfría y refrigera 2 horas."],
  tp:["Las manchas quemadas son la gracia; vigílalas porque pasan de doradas a negras en segundos.",
      "Si salen burbujas, el horno estaba muy caliente."],
  v:"jericalla receta"},
 en:{n:"Jericalla (Guadalajara Custard)", b:"Guadalajara's custard with a scorched top. Milk infused with cinnamon and vanilla, set with yolks, no caramel.",
  st:["Heat the milk with the cinnamon, vanilla and sugar until steaming. Turn off and infuse 15 minutes.",
      "Heat the oven to 160 °C. Set 6 ramekins in a baking dish.",
      "Whisk the yolks and egg without making foam. Pour in the warm milk slowly, whisking. Strain.",
      "Fill the ramekins and pour hot water into the dish halfway up their sides.",
      "Bake 35 minutes, until the centres barely wobble.",
      "Move them to the top of the oven under the grill for 3 to 5 minutes, until the tops have dark spots. Cool and chill 2 hours."],
  tp:["The scorched spots are the point; watch closely, they go from golden to black in seconds.",
      "If they come out bubbly, the oven was too hot."],
  v:"jericalla recipe"}},

{id:"cajeta", c:"Mexico", r:"latin-america", m:"sauce", t:150, s:12,
 i:[[2,"l","milk","liquid","leche de cabra","goat's milk"],
    [400,"g","sugar","sweet","azúcar","sugar"],
    [1,"","spice","aromatic","raja de canela","cinnamon stick"],
    [0.5,"tsp","bakingsoda","set","bicarbonato de sodio","baking soda","disuelto en 1 cucharada de agua","dissolved in 1 tablespoon of water"]],
 es:{n:"Cajeta", b:"El dulce de leche de cabra de Celaya: leche con azúcar reducida durante horas hasta quedar color ámbar y espesa.",
  st:["En una olla grande y ancha, calienta la leche con el azúcar y la canela, moviendo, hasta que el azúcar se disuelva.",
      "Cuando esté por hervir, retira del fuego y añade el bicarbonato disuelto. Hará mucha espuma: por eso la olla grande.",
      "Regresa al fuego medio-bajo y cuece 2 horas, moviendo cada 5 minutos al principio y sin parar al final.",
      "Está lista cuando es color caramelo y al pasar una cuchara por el fondo se ve la olla un segundo.",
      "Saca la canela y pásala a frascos limpios. Espesa al enfriar."],
  tp:["El bicarbonato evita que la leche se corte y le da el color oscuro.",
      "Con leche de vaca sale igual de buena, un poco menos intensa."],
  v:"cajeta de leche de cabra receta"},
 en:{n:"Cajeta (Goat's Milk Caramel)", b:"Celaya's goat's milk caramel: milk and sugar reduced for hours until amber and thick.",
  st:["In a large, wide pot, heat the milk with the sugar and cinnamon, stirring, until the sugar dissolves.",
      "Just before it boils, take it off the heat and add the dissolved baking soda. It foams a lot: hence the big pot.",
      "Return to medium-low heat and cook 2 hours, stirring every 5 minutes at first and constantly at the end.",
      "It is ready when caramel-coloured and a spoon dragged across the bottom shows the pot for a second.",
      "Remove the cinnamon and pour into clean jars. It thickens as it cools."],
  tp:["The baking soda keeps the milk from curdling and gives the dark colour.",
      "Cow's milk makes an equally good one, a little milder."],
  v:"cajeta recipe"}},

{id:"atole-de-vainilla", c:"Mexico", r:"latin-america", m:"drink", t:20, s:4,
 i:[[500,"ml","water","liquid","agua","water"],
    [500,"ml","milk","liquid","leche","milk"],
    [80,"g","masa","thicken","masa fresca de maíz","fresh corn masa"],
    [80,"g","jaggery","sweet","piloncillo","piloncillo (unrefined cane sugar)","picado","chopped"],
    [1,"","spice","aromatic","raja de canela","cinnamon stick"],
    [1,"","vanillabean","aromatic","vaina de vainilla","vanilla pod","abierta","split"]],
 es:{n:"Atole de vainilla", b:"Bebida caliente y espesa de masa de maíz con piloncillo, canela y vainilla. El desayuno de puesto de tamales.",
  st:["Deshaz la masa en el agua con las manos o licúala hasta que no queden grumos.",
      "Cuélala a una olla con la leche, el piloncillo, la canela y la vainilla.",
      "Cuece a fuego medio-bajo 12 minutos, moviendo sin parar, hasta que espese.",
      "Saca la canela y la vainilla y sirve caliente."],
  tp:["Si queda muy espeso, añade leche caliente.",
      "Para atole de fresa, licúa 250 gramos de fresas con el agua."],
  v:"atole de vainilla receta"},
 en:{n:"Vanilla Atole", b:"A thick hot drink of corn masa with piloncillo, cinnamon and vanilla. Breakfast from the tamale stand.",
  st:["Break up the masa in the water with your hands or blend until there are no lumps.",
      "Strain it into a pot with the milk, piloncillo, cinnamon and vanilla.",
      "Cook over medium-low heat for 12 minutes, stirring constantly, until thick.",
      "Remove the cinnamon and vanilla and serve hot."],
  tp:["If it's too thick, add hot milk.",
      "For strawberry atole, blend 250 grams of strawberries with the water."],
  v:"atole recipe"}},

{id:"agua-de-jamaica", c:"Mexico", r:"latin-america", m:"drink", t:30, s:8,
 i:[[60,"g","herb","aromatic","flor de jamaica seca","dried hibiscus flowers"],
    [2,"l","water","liquid","agua","water"],
    [150,"g","sugar","sweet","azúcar","sugar"],
    [1,"","citrus","acid","limón","lime","en jugo, opcional","juiced, optional"],
    [1,"handful","ice","serve","hielo","ice"]],
 es:{n:"Agua de jamaica", b:"Agua fresca color rubí de flor de jamaica: ácida, ligeramente astringente y endulzada al gusto.",
  st:["Enjuaga la flor de jamaica en un colador.",
      "Hierve 500 ml del agua, apaga, añade la flor y deja reposar 15 minutos.",
      "Cuela apretando las flores. Disuelve el azúcar en el concentrado caliente.",
      "Añade el resto del agua fría y el limón. Sirve con hielo."],
  tp:["Más de 20 minutos de reposo y amarga.",
      "Las flores ya usadas sirven para tacos: se guisan con cebolla y chile."],
  v:"agua de jamaica receta"},
 en:{n:"Hibiscus Agua Fresca (Agua de Jamaica)", b:"Ruby-red hibiscus agua fresca: tart, slightly tannic and sweetened to taste.",
  st:["Rinse the hibiscus in a sieve.",
      "Boil 500 ml of the water, turn it off, add the flowers and steep 15 minutes.",
      "Strain, pressing the flowers. Dissolve the sugar in the hot concentrate.",
      "Add the rest of the water, cold, and the lime. Serve over ice."],
  tp:["Steep longer than 20 minutes and it turns bitter.",
      "The spent flowers make good tacos: cook them with onion and chile."],
  v:"agua de jamaica recipe"}},

{id:"agua-de-tamarindo", c:"Mexico", r:"latin-america", m:"drink", t:40, s:8,
 i:[[250,"g","tamarind","acid","vainas de tamarindo","tamarind pods","peladas","shelled"],
    [2,"l","water","liquid","agua","water"],
    [150,"g","sugar","sweet","azúcar","sugar"],
    [1,"handful","ice","serve","hielo","ice"]],
 es:{n:"Agua de tamarindo", b:"Agua fresca agridulce de pulpa de tamarindo. Color café claro y sabor que despierta.",
  st:["Hierve el tamarindo pelado en 1 litro del agua 10 minutos, hasta que la pulpa se ablande.",
      "Deja enfriar 15 minutos y deshaz la pulpa con las manos para separarla de las semillas.",
      "Cuela apretando bien. Tira las semillas y las fibras.",
      "Añade el resto del agua y el azúcar, mezcla hasta disolver y sirve con hielo."],
  tp:["Con pulpa de tamarindo en bloque, usa 150 gramos y remójala en agua caliente.",
      "El concentrado dura 5 días en el refrigerador."],
  v:"agua de tamarindo receta"},
 en:{n:"Tamarind Agua Fresca", b:"A sweet-sour agua fresca of tamarind pulp. Light brown and wakes you up.",
  st:["Boil the shelled tamarind in 1 litre of the water for 10 minutes, until the pulp softens.",
      "Cool 15 minutes and squeeze the pulp off the seeds with your hands.",
      "Strain, pressing well. Discard the seeds and fibres.",
      "Add the rest of the water and the sugar, stir to dissolve and serve over ice."],
  tp:["With block tamarind pulp, use 150 grams and soak it in hot water.",
      "The concentrate keeps 5 days in the fridge."],
  v:"tamarind agua fresca recipe"}}
];
