module.exports = [
{id:"barbacoa", c:"Mexico", r:"latin-america", m:"main", t:300, s:8, o:160,
 i:[[2,"kg","beef","protein","cachete o espaldilla de res","beef cheek or chuck","en trozos grandes","in large pieces"],
    [4,"","chilli","aromatic","chiles guajillo","guajillo chiles","sin semillas","seeded"],
    [2,"","ancho","aromatic","chiles anchos","ancho chiles","sin semillas","seeded"],
    [6,"clove","garlic","aromatic","ajo","garlic"],
    [0.5,"","onion","aromatic","cebolla blanca","white onion"],
    [60,"ml","cidervinegar","acid","vinagre de manzana","cider vinegar"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [3,"","spice","aromatic","clavos de olor","cloves"],
    [3,"leaf","herb","aromatic","hojas de laurel","bay leaves"],
    [4,"leaf","herb","aromatic","hojas de aguacate secas","dried avocado leaves","opcional","optional"],
    [2.5,"tsp","salt","salt","sal","salt"],
    [250,"ml","water","liquid","agua","water"],
    [24,"","corntortilla","serve","tortillas de maíz","corn tortillas"],
    [0.5,"","onion","garnish","cebolla blanca","white onion","picada","chopped"],
    [1,"bunch","herb","garnish","cilantro","cilantro","picado","chopped"]],
 es:{n:"Barbacoa de res al horno", b:"Res adobada con guajillo y ancho, cocida tapada durante horas hasta deshacerse. La barbacoa de hoyo, adaptada a la cocina de casa.",
  st:["Remoja los chiles en agua caliente 15 minutos. Licúalos con el ajo, la cebolla, el vinagre, el comino, el orégano, el clavo, la sal y el agua.",
      "Unta la carne con el adobo y déjala en el refrigerador al menos 2 horas o toda la noche.",
      "Calienta el horno a 160 °C. Pon el laurel y las hojas de aguacate en el fondo de una olla de hierro, la carne encima y todo el adobo.",
      "Tapa bien, con papel aluminio bajo la tapa, y hornea 4 horas, hasta que la carne se deshaga con un tenedor.",
      "Deshebra la carne en su jugo. Sirve en tortillas calientes con cebolla y cilantro, y el jugo aparte en tazas."],
  tp:["El jugo de la olla se toma como consomé: sálalo y sírvelo con garbanzos cocidos.",
      "Las hojas de aguacate dan el sabor anisado del hoyo; si no las encuentras, se puede sin ellas."],
  v:"barbacoa de res al horno receta"},
 en:{n:"Oven Beef Barbacoa", b:"Beef marinated in guajillo and ancho, cooked covered for hours until it falls apart. Pit barbacoa, adapted to a home kitchen.",
  st:["Soak the chiles in hot water for 15 minutes. Blend with the garlic, onion, vinegar, cumin, oregano, cloves, salt and water.",
      "Coat the beef in the marinade and chill at least 2 hours or overnight.",
      "Heat the oven to 160 °C. Put the bay and avocado leaves in the bottom of a cast-iron pot, the beef on top and all the marinade.",
      "Cover tightly, with foil under the lid, and bake 4 hours, until the beef falls apart with a fork.",
      "Shred the beef in its juices. Serve in warm corn tortillas with onion and cilantro, and the juices on the side in cups."],
  tp:["The pot juices are drunk as consommé: salt them and serve with cooked chickpeas.",
      "Avocado leaves give the anise note of the pit; if you can't find them, it works without."],
  v:"beef barbacoa recipe"}},

{id:"pollo-pibil", c:"Mexico", r:"latin-america", m:"main", t:150, s:6, o:180,
 i:[[1.5,"kg","chicken","protein","piezas de pollo","chicken pieces","sin piel","skinless"],
    [100,"g","achiote","aromatic","pasta de achiote","achiote paste"],
    [250,"ml","citrus","acid","jugo de naranja agria (o mitad naranja y mitad limón)","sour orange juice (or half orange, half lime)"],
    [4,"clove","garlic","aromatic","ajo","garlic"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [0.5,"tsp","spice","aromatic","comino molido","ground cumin"],
    [1.5,"tsp","salt","salt","sal","salt"],
    [2,"leaf","veg","serve","hojas de plátano","banana leaves","pasadas por la llama","passed over a flame"],
    [1,"","onion","garnish","cebolla morada","red onion","en pluma fina","thinly sliced"],
    [1,"","chilli","garnish","chile habanero","habanero chile","picado fino","finely chopped"],
    [2,"","citrus","acid","limones","limes","en jugo","juiced"],
    [18,"","corntortilla","serve","tortillas de maíz","corn tortillas"]],
 es:{n:"Pollo pibil", b:"Pollo marinado en achiote y naranja agria, envuelto en hoja de plátano y horneado hasta deshacerse. Con cebolla morada en limón y habanero.",
  st:["Licúa el achiote con el jugo de naranja agria, el ajo, el orégano, el comino y la sal.",
      "Marina el pollo en la mezcla al menos 2 horas.",
      "Calienta el horno a 180 °C. Forra un refractario con las hojas de plátano, pon el pollo con toda la marinada y cierra las hojas encima. Tapa con aluminio.",
      "Hornea 90 minutos. Deshebra el pollo en su jugo.",
      "Mezcla la cebolla con el habanero, el jugo de limón y una pizca de sal. Deja 20 minutos.",
      "Sirve el pollo en tortillas con la cebolla encima."],
  tp:["Usa guantes para el achiote y el habanero: el primero tiñe y el segundo quema.",
      "Si falta hoja de plátano, papel aluminio funciona, pero pierde el aroma."],
  v:"pollo pibil receta"},
 en:{n:"Pollo Pibil", b:"Chicken marinated in achiote and sour orange, wrapped in banana leaves and baked until it falls apart. With red onion in lime and habanero.",
  st:["Blend the achiote with the sour orange juice, garlic, oregano, cumin and salt.",
      "Marinate the chicken in the mixture for at least 2 hours.",
      "Heat the oven to 180 °C. Line a baking dish with the banana leaves, add the chicken with all the marinade and fold the leaves over. Cover with foil.",
      "Bake 90 minutes. Shred the chicken in its juices.",
      "Mix the onion with the habanero, lime juice and a pinch of salt. Leave 20 minutes.",
      "Serve the chicken in corn tortillas with the onion on top."],
  tp:["Wear gloves for the achiote and the habanero: one stains and the other burns.",
      "No banana leaves? Foil works, but you lose the aroma."],
  v:"pollo pibil recipe"}},

{id:"mole-verde", c:"Mexico", r:"latin-america", m:"main", t:90, s:6,
 i:[[1.2,"kg","pork","protein","espinazo o costilla de cerdo","pork backbone or ribs","en trozos","in pieces"],
    [2,"l","water","liquid","agua","water"],
    [0.5,"","onion","aromatic","cebolla","onion"],
    [4,"clove","garlic","aromatic","ajo","garlic"],
    [2,"tsp","salt","salt","sal","salt"],
    [100,"g","seeds","thicken","pepitas de calabaza peladas","hulled pumpkin seeds"],
    [500,"g","tomatillo","sauce","tomatillos","tomatillos"],
    [3,"","chilli","aromatic","chiles jalapeños","jalapeño chiles"],
    [4,"leaf","veg","aromatic","hojas de lechuga romana","romaine lettuce leaves"],
    [1,"bunch","herb","aromatic","cilantro","cilantro"],
    [4,"sprig","herb","aromatic","epazote","epazote"],
    [2,"leaf","herb","aromatic","hojas santas (opcional)","hoja santa leaves (optional)"],
    [1,"tbsp","lard","fat","manteca de cerdo","lard"]],
 es:{n:"Mole verde con cerdo", b:"Un mole fresco de pepita, tomatillo y hierbas verdes, con cerdo tierno. Verde brillante si no se hierve de más.",
  st:["Cuece el cerdo con el agua, la cebolla, 2 dientes de ajo y la sal 60 minutos, hasta que esté tierno. Guarda el líquido.",
      "Tuesta las pepitas en un sartén seco hasta que empiecen a saltar. No las dejes dorar.",
      "Hierve los tomatillos y los jalapeños 5 minutos.",
      "Licúa las pepitas, los tomatillos, los jalapeños, 2 dientes de ajo y 500 ml del líquido del cerdo. Luego añade la lechuga y las hierbas y licúa solo hasta que esté liso.",
      "Calienta la manteca en una olla y fríe la salsa 5 minutos a fuego medio, moviendo.",
      "Añade el cerdo y más líquido hasta que la salsa cubra una cuchara. Calienta sin hervir fuerte y sirve."],
  tp:["Las hierbas se licúan al final y no hierven mucho: así el mole queda verde y no café.",
      "Con pollo en vez de cerdo se cuece 35 minutos."],
  v:"mole verde receta"},
 en:{n:"Green Mole with Pork", b:"A fresh mole of pumpkin seeds, tomatillo and green herbs, with tender pork. Bright green as long as you don't overboil it.",
  st:["Simmer the pork with the water, onion, 2 garlic cloves and salt for 60 minutes, until tender. Keep the liquid.",
      "Toast the pumpkin seeds in a dry pan until they start to pop. Don't let them brown.",
      "Boil the tomatillos and jalapeños for 5 minutes.",
      "Blend the seeds, tomatillos, jalapeños, 2 garlic cloves and 500 ml of the pork liquid. Then add the lettuce and herbs and blend just until smooth.",
      "Heat the lard in a pot and fry the sauce for 5 minutes over medium heat, stirring.",
      "Add the pork and more liquid until the sauce coats a spoon. Heat without a hard boil and serve."],
  tp:["The herbs are blended last and barely boiled: that keeps the mole green, not brown.",
      "With chicken instead of pork, simmer it 35 minutes."],
  v:"mole verde recipe"}},

{id:"pipian-rojo", c:"Mexico", r:"latin-america", m:"main", t:75, s:4,
 i:[[1,"kg","chicken","protein","piezas de pollo","chicken pieces"],
    [1.5,"l","water","liquid","agua","water"],
    [0.5,"","onion","aromatic","cebolla","onion"],
    [3,"clove","garlic","aromatic","ajo","garlic"],
    [1.5,"tsp","salt","salt","sal","salt"],
    [100,"g","seeds","thicken","pepitas de calabaza peladas","hulled pumpkin seeds"],
    [2,"tbsp","sesameseed","thicken","ajonjolí","sesame seeds"],
    [4,"","chilli","aromatic","chiles guajillo","guajillo chiles","sin semillas","seeded"],
    [2,"","ancho","aromatic","chiles anchos","ancho chiles","sin semillas","seeded"],
    [2,"","tomato","aromatic","jitomates","tomatoes"],
    [0.25,"tsp","spice","aromatic","canela molida","ground cinnamon"],
    [2,"","spice","aromatic","clavos de olor","cloves"],
    [1,"tbsp","oil","fat","aceite","oil"]],
 es:{n:"Pipián rojo con pollo", b:"Salsa roja espesada con pepitas y ajonjolí tostados, con guajillo y ancho. Más rápida que un mole y igual de profunda.",
  st:["Cuece el pollo con el agua, la cebolla, 2 dientes de ajo y la sal 35 minutos. Guarda el líquido.",
      "Tuesta las pepitas y el ajonjolí en un sartén seco hasta que huelan y empiecen a saltar. Tuesta los chiles 20 segundos por lado.",
      "Remoja los chiles en agua caliente 15 minutos.",
      "Licúa las semillas, los chiles, los jitomates, 1 diente de ajo, la canela y el clavo con 500 ml del líquido del pollo. Cuela.",
      "Fríe la salsa en el aceite 10 minutos a fuego bajo, moviendo, hasta que espese. Añade líquido si hace falta.",
      "Añade el pollo, calienta 5 minutos y sirve con arroz."],
  tp:["Las semillas se queman en segundos: sácalas del sartén en cuanto empiecen a saltar.",
      "Sin ajonjolí, usa 30 gramos más de pepitas."],
  v:"pipian rojo receta"},
 en:{n:"Red Pipián with Chicken", b:"A red sauce thickened with toasted pumpkin and sesame seeds, with guajillo and ancho. Quicker than mole and just as deep.",
  st:["Simmer the chicken with the water, onion, 2 garlic cloves and salt for 35 minutes. Keep the liquid.",
      "Toast the pumpkin and sesame seeds in a dry pan until fragrant and starting to pop. Toast the chiles 20 seconds per side.",
      "Soak the chiles in hot water for 15 minutes.",
      "Blend the seeds, chiles, tomatoes, 1 garlic clove, cinnamon and cloves with 500 ml of the chicken liquid. Strain.",
      "Fry the sauce in the oil for 10 minutes on low, stirring, until thick. Add liquid if needed.",
      "Add the chicken, heat 5 minutes and serve with rice."],
  tp:["Seeds burn in seconds: take them out of the pan as soon as they start to pop.",
      "No sesame? Use 30 grams more pumpkin seeds."],
  v:"pipian rojo recipe"}},

{id:"puerco-en-adobo", c:"Mexico", r:"latin-america", m:"main", t:120, s:6,
 i:[[1.2,"kg","pork","protein","espaldilla de cerdo","pork shoulder","en cubos de 4 cm","in 4 cm cubes"],
    [1.5,"tsp","salt","salt","sal","salt"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [4,"","ancho","aromatic","chiles anchos","ancho chiles","sin semillas","seeded"],
    [3,"","chilli","aromatic","chiles guajillo","guajillo chiles","sin semillas","seeded"],
    [4,"clove","garlic","aromatic","ajo","garlic"],
    [0.25,"","onion","aromatic","cebolla","onion"],
    [2,"tbsp","cidervinegar","acid","vinagre de manzana","cider vinegar"],
    [0.5,"tsp","spice","aromatic","comino molido","ground cumin"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [0.25,"tsp","spice","aromatic","canela molida","ground cinnamon"],
    [500,"ml","water","liquid","agua","water"],
    [2,"leaf","herb","aromatic","hojas de laurel","bay leaves"]],
 es:{n:"Puerco en adobo", b:"Cerdo guisado despacio en un adobo de ancho y guajillo con vinagre y especias. Mejor al día siguiente.",
  st:["Sala el cerdo y dóralo en el aceite en tandas, 8 minutos por tanda. Sácalo.",
      "Remoja los chiles en agua caliente 15 minutos. Licúalos con el ajo, la cebolla, el vinagre, las especias, el orégano y el agua. Cuela.",
      "Fríe el adobo en la misma olla 5 minutos, raspando el fondo.",
      "Regresa el cerdo con el laurel, tapa y cuece a fuego bajo 75 minutos, hasta que esté tierno.",
      "Destapa los últimos 15 minutos si la salsa está delgada. Sirve con arroz y tortillas."],
  tp:["Dorar la carne en tandas es lo que da color; si llenas la olla, se cuece al vapor.",
      "Aguanta 4 días en el refrigerador y se congela bien."],
  v:"puerco en adobo receta"},
 en:{n:"Pork in Adobo", b:"Pork braised slowly in an ancho and guajillo adobo with vinegar and spices. Better the next day.",
  st:["Salt the pork and brown it in the oil in batches, 8 minutes per batch. Remove.",
      "Soak the chiles in hot water for 15 minutes. Blend with the garlic, onion, vinegar, spices, oregano and the water. Strain.",
      "Fry the adobo in the same pot for 5 minutes, scraping the bottom.",
      "Return the pork with the bay leaves, cover and simmer on low for 75 minutes, until tender.",
      "Uncover for the last 15 minutes if the sauce is thin. Serve with rice and corn tortillas."],
  tp:["Browning in batches is what gives colour; a crowded pot steams instead.",
      "Keeps 4 days in the fridge and freezes well."],
  v:"pork adobo mexican recipe"}},

{id:"chile-colorado", c:"Mexico", r:"latin-america", m:"main", t:120, s:6,
 i:[[1.2,"kg","beef","protein","espaldilla de res","beef chuck","en cubos de 3 cm","in 3 cm cubes"],
    [1.5,"tsp","salt","salt","sal","salt"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [8,"","chilli","aromatic","chiles guajillo o de Nuevo México","guajillo or New Mexico chiles","sin semillas","seeded"],
    [4,"clove","garlic","aromatic","ajo","garlic"],
    [0.5,"tsp","spice","aromatic","comino molido","ground cumin"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [750,"ml","water","liquid","agua","water"]],
 es:{n:"Chile colorado", b:"Res en una salsa roja de chile seco, sin jitomate: solo chile, ajo, comino y orégano. El guiso del norte para burritos.",
  st:["Hierve los chiles en 500 ml del agua 10 minutos. Licúalos con esa agua, el ajo, el comino y el orégano. Cuela.",
      "Sala la carne y dórala en el aceite en tandas.",
      "Vierte la salsa y el resto del agua. Tapa y cuece a fuego bajo 90 minutos, hasta que la carne esté tierna y la salsa espesa.",
      "Prueba de sal y sirve con frijoles, arroz o en tortillas."],
  tp:["Colar la salsa es obligatorio: la piel del chile seco no se deshace.",
      "Si queda amarga, quedaron semillas o venas en los chiles: quítalas todas."],
  v:"chile colorado receta"},
 en:{n:"Chile Colorado", b:"Beef in a red sauce of dried chiles with no tomato: just chile, garlic, cumin and oregano. The northern stew for burritos.",
  st:["Boil the chiles in 500 ml of the water for 10 minutes. Blend with that water, the garlic, cumin and oregano. Strain.",
      "Salt the beef and brown it in the oil in batches.",
      "Pour in the sauce and the rest of the water. Cover and simmer on low for 90 minutes, until the beef is tender and the sauce thick.",
      "Taste for salt and serve with beans, rice or in tortillas."],
  tp:["Straining is a must: dried chile skin never breaks down.",
      "If it tastes bitter, seeds or veins were left in the chiles: remove them all."],
  v:"chile colorado recipe"}},

{id:"chile-verde", c:"Mexico", r:"latin-america", m:"main", t:120, s:6,
 i:[[1.2,"kg","pork","protein","espaldilla de cerdo","pork shoulder","en cubos de 3 cm","in 3 cm cubes"],
    [1.5,"tsp","salt","salt","sal","salt"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [700,"g","tomatillo","sauce","tomatillos","tomatillos"],
    [3,"","chilli","aromatic","chiles poblanos","poblano chiles"],
    [2,"","chilli","aromatic","chiles jalapeños","jalapeño chiles"],
    [1,"","onion","aromatic","cebolla","onion"],
    [5,"clove","garlic","aromatic","ajo","garlic"],
    [1,"bunch","herb","aromatic","cilantro","cilantro"],
    [0.5,"tsp","spice","aromatic","comino molido","ground cumin"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [250,"ml","water","liquid","agua","water"]],
 es:{n:"Chile verde de cerdo", b:"Cerdo guisado en una salsa de tomatillo, poblano y jalapeño asados. Ácido, verde y para comer con tortillas de harina o maíz.",
  st:["Asa los tomatillos, los chiles, la cebolla en trozos y el ajo bajo el grill o en comal hasta que estén manchados de negro. Pela los poblanos y quítales las semillas.",
      "Licúa todo lo asado con el cilantro, el comino, el orégano y el agua.",
      "Sala el cerdo y dóralo en el aceite en tandas.",
      "Vierte la salsa, tapa y cuece a fuego bajo 90 minutos, hasta que el cerdo esté tierno.",
      "Prueba de sal y sirve."],
  tp:["El asado es el sabor: no hiervas los tomatillos para esta receta.",
      "Si la salsa quedó muy ácida, cuece 10 minutos más destapado."],
  v:"chile verde de puerco receta"},
 en:{n:"Pork Chile Verde", b:"Pork braised in a sauce of charred tomatillo, poblano and jalapeño. Tart, green and made for tortillas.",
  st:["Char the tomatillos, chiles, onion in chunks and garlic under the grill or on a griddle until blackened in spots. Peel and seed the poblanos.",
      "Blend everything charred with the cilantro, cumin, oregano and water.",
      "Salt the pork and brown it in the oil in batches.",
      "Pour in the sauce, cover and simmer on low for 90 minutes, until the pork is tender.",
      "Taste for salt and serve."],
  tp:["The charring is the flavour: don't boil the tomatillos for this one.",
      "If the sauce is too tart, simmer 10 minutes more uncovered."],
  v:"chile verde pork recipe"}},

{id:"camarones-diabla", c:"Mexico", r:"latin-america", m:"main", t:30, s:4,
 i:[[700,"g","shrimp","protein","camarones grandes","large shrimp","pelados, con cola","peeled, tails on"],
    [4,"","chilli","aromatic","chiles guajillo","guajillo chiles","sin semillas","seeded"],
    [6,"","chilli","aromatic","chiles de árbol","árbol chiles"],
    [2,"","chipotle","aromatic","chiles chipotles en adobo","chipotles in adobo"],
    [3,"","tomato","sauce","jitomates","tomatoes"],
    [3,"clove","garlic","aromatic","ajo","garlic"],
    [0.25,"","onion","aromatic","cebolla","onion"],
    [200,"ml","water","liquid","agua","water"],
    [30,"g","butter","fat","mantequilla","butter"],
    [1,"tbsp","oil","fat","aceite","oil"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Camarones a la diabla", b:"Camarones en una salsa roja muy picante de guajillo, árbol y chipotle, terminada con mantequilla.",
  st:["Hierve los guajillos, los chiles de árbol y los jitomates 10 minutos.",
      "Licúalos con los chipotles, el ajo, la cebolla, el agua y la sal. Cuela.",
      "Calienta el aceite y la mantequilla en un sartén grande. Fríe la salsa 8 minutos, hasta que espese.",
      "Añade los camarones y cuece 3 a 4 minutos, moviendo, hasta que estén rosados.",
      "Sirve con arroz blanco."],
  tp:["Para menos picante, usa 2 chiles de árbol.",
      "Los camarones se cuecen en minutos: añádelos al final y sirve enseguida."],
  v:"camarones a la diabla receta"},
 en:{n:"Devilled Shrimp (Camarones a la Diabla)", b:"Shrimp in a very hot red sauce of guajillo, árbol and chipotle chiles, finished with butter.",
  st:["Boil the guajillos, árbol chiles and tomatoes for 10 minutes.",
      "Blend with the chipotles, garlic, onion, water and salt. Strain.",
      "Heat the oil and butter in a large pan. Fry the sauce for 8 minutes, until thick.",
      "Add the shrimp and cook 3 to 4 minutes, stirring, until pink.",
      "Serve with white rice."],
  tp:["For less heat, use 2 árbol chiles.",
      "Shrimp cook in minutes: add them last and serve right away."],
  v:"camarones a la diabla recipe"}},

{id:"arroz-con-leche-mx", c:"Mexico", r:"latin-america", m:"sweet", t:50, s:6,
 i:[[200,"g","rice","structure","arroz blanco","white rice","enjuagado","rinsed"],
    [500,"ml","water","liquid","agua","water"],
    [1,"","spice","aromatic","raja de canela","cinnamon stick"],
    [1,"l","milk","liquid","leche entera","whole milk"],
    [200,"ml","condensedmilk","sweet","leche condensada","sweetened condensed milk"],
    [1,"tsp","vanilla","aromatic","extracto de vainilla","vanilla extract"],
    [50,"g","driedfruit","garnish","pasas","raisins","opcional","optional"],
    [0.25,"tsp","salt","salt","sal","salt"],
    [1,"tsp","spice","garnish","canela molida","ground cinnamon"]],
 es:{n:"Arroz con leche", b:"Arroz cocido con canela y terminado en leche y leche condensada hasta quedar cremoso. Tibio o frío, con canela encima.",
  st:["Hierve el arroz en el agua con la raja de canela 15 minutos, hasta que se absorba casi toda el agua.",
      "Añade la leche y la sal. Cuece a fuego bajo 20 minutos, moviendo seguido para que no se pegue.",
      "Añade la leche condensada y las pasas; cuece 5 minutos más.",
      "Apaga el fuego, saca la canela y añade la vainilla.",
      "Sirve con canela molida. Se espesa al enfriar."],
  tp:["Si quedó muy espeso al día siguiente, añade un chorro de leche y calienta.",
      "Remoja las pasas en agua caliente 10 minutos antes para que queden jugosas."],
  v:"arroz con leche mexicano receta"},
 en:{n:"Mexican Rice Pudding (Arroz con Leche)", b:"Rice cooked with cinnamon and finished in milk and condensed milk until creamy. Warm or cold, with cinnamon on top.",
  st:["Boil the rice in the water with the cinnamon stick for 15 minutes, until nearly all the water is absorbed.",
      "Add the milk and salt. Simmer on low for 20 minutes, stirring often so it doesn't stick.",
      "Add the condensed milk and raisins; cook 5 minutes more.",
      "Turn off the heat, remove the cinnamon and add the vanilla.",
      "Serve with ground cinnamon. It thickens as it cools."],
  tp:["If it's too thick the next day, add a splash of milk and warm it.",
      "Soak the raisins in hot water for 10 minutes first so they're plump."],
  v:"arroz con leche recipe"}},

{id:"champurrado", c:"Mexico", r:"latin-america", m:"drink", t:25, s:6,
 i:[[1,"l","water","liquid","agua","water"],
    [1,"","spice","aromatic","raja de canela","cinnamon stick"],
    [60,"g","jaggery","sweet","piloncillo","piloncillo (unrefined cane sugar)","picado","chopped"],
    [90,"g","tablechocolate","sweet","chocolate de mesa","Mexican table chocolate","en trozos","in pieces"],
    [100,"g","masa","thicken","masa fresca de maíz","fresh corn masa"],
    [500,"ml","milk","liquid","leche","milk"]],
 es:{n:"Champurrado", b:"Atole espeso de masa de maíz con chocolate de mesa, piloncillo y canela. La bebida caliente de los tamales.",
  st:["Hierve el agua con la canela y el piloncillo 5 minutos, hasta que se disuelva.",
      "Añade el chocolate y mueve hasta que se funda.",
      "Deshaz la masa en la leche con las manos o licúala, hasta que no queden grumos.",
      "Vierte la leche con masa a la olla colándola, moviendo sin parar.",
      "Cuece a fuego bajo 10 minutos, moviendo, hasta que espese y cubra una cuchara. Saca la canela y sirve caliente."],
  tp:["Mueve todo el tiempo: la masa se pega al fondo en segundos.",
      "Bátelo con molinillo o batidor antes de servir para que haga espuma."],
  v:"champurrado receta"},
 en:{n:"Champurrado", b:"A thick corn masa drink with Mexican table chocolate, piloncillo and cinnamon. The hot drink that goes with tamales.",
  st:["Boil the water with the cinnamon and piloncillo for 5 minutes, until dissolved.",
      "Add the chocolate and stir until melted.",
      "Break up the masa in the milk with your hands or blend it, until there are no lumps.",
      "Strain the masa milk into the pot, stirring constantly.",
      "Cook on low for 10 minutes, stirring, until thick enough to coat a spoon. Remove the cinnamon and serve hot."],
  tp:["Stir the whole time: masa sticks to the bottom in seconds.",
      "Froth it with a molinillo or whisk before serving."],
  v:"champurrado recipe"}}
];
