module.exports = [
{id:"tlayudas", c:"Mexico", r:"latin-america", m:"main", t:40, s:4,
 i:[[4,"","corntortilla","structure","tlayudas (tortillas grandes de maíz)","tlayudas (large corn tortillas)"],
    [4,"tbsp","lard","fat","asiento o manteca de cerdo","asiento or lard"],
    [400,"g","refriedbeans","protein","frijoles negros refritos","refried black beans"],
    [300,"g","queso","protein","quesillo (queso Oaxaca)","quesillo (Oaxaca cheese)","deshebrado","pulled into strands"],
    [400,"g","beef","protein","cecina o tasajo de res","thin salted beef (tasajo)"],
    [0.25,"head","veg","garnish","col","cabbage","rebanada fina","finely shredded"],
    [2,"","tomato","garnish","jitomates","tomatoes","en rodajas","sliced"],
    [1,"","avocado","garnish","aguacate","avocado","en rebanadas","sliced"],
    [250,"ml","salsa","sauce","salsa de tomatillo","tomatillo salsa"]],
 es:{n:"Tlayudas oaxaqueñas", b:"Una tortilla enorme untada de asiento y frijol negro, con quesillo y tasajo, tostada sobre las brasas hasta crujir.",
  st:["Asa la carne en un comal o parrilla muy caliente 2 minutos por lado. Córtala en tiras.",
      "Unta cada tlayuda con 1 cucharada de asiento y luego con una capa delgada de frijoles.",
      "Pon el quesillo en una mitad. Dobla la tlayuda.",
      "Tuéstala en el comal a fuego medio 3 a 4 minutos por lado, apretando, hasta que crujan los bordes y se funda el queso.",
      "Ábrela y sirve con la carne, la col, el jitomate, el aguacate y la salsa."],
  tp:["Sin tlayudas, usa 2 tortillas grandes de maíz algo secas: crujen igual.",
      "Una rejilla sobre la estufa de gas da el sabor ahumado de las brasas."],
  v:"tlayudas oaxaqueñas receta"},
 en:{n:"Oaxacan Tlayudas", b:"A huge tortilla spread with asiento and black beans, topped with quesillo and tasajo, toasted over the coals until crisp.",
  st:["Sear the beef on a very hot griddle or grill for 2 minutes per side. Cut into strips.",
      "Spread each tlayuda with 1 tablespoon of asiento, then a thin layer of beans.",
      "Put the cheese on one half. Fold the tlayuda over.",
      "Toast it on a griddle over medium heat for 3 to 4 minutes per side, pressing, until the edges crisp and the cheese melts.",
      "Open it up and serve with the beef, cabbage, tomato, avocado and salsa."],
  tp:["No tlayudas? Use 2 large corn tortillas that have dried a little: they crisp the same way.",
      "A rack over a gas flame gives the smoky taste of the coals."],
  v:"tlayuda recipe"}},

{id:"tacos-de-canasta", c:"Mexico", r:"latin-america", m:"main", t:75, s:6,
 i:[[500,"g","potato","protein","papas","potatoes","peladas, en trozos","peeled, in chunks"],
    [1,"","chipotleadobo","aromatic","chile chipotle en adobo","chipotle in adobo"],
    [400,"g","refriedbeans","protein","frijoles refritos","refried beans"],
    [30,"","corntortilla","structure","tortillas de maíz chicas","small corn tortillas"],
    [150,"ml","oil","fat","aceite","oil"],
    [4,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"","chilli","aromatic","chiles guajillo","guajillo chiles","sin semillas, remojados","seeded, soaked"],
    [1.5,"tsp","salt","salt","sal","salt"],
    [1,"","onion","aromatic","cebolla","onion","en tiras","sliced"],
    [250,"ml","salsa","sauce","salsa verde","green salsa"]],
 es:{n:"Tacos de canasta", b:"Tacos sudados: rellenos de papa o frijol, bañados en aceite de chile y guardados calientes en una canasta con tela hasta que se funden en uno.",
  st:["Hierve las papas en agua con 1 cucharadita de sal 20 minutos. Escurre y machaca con el chipotle.",
      "Licúa los guajillos con el ajo, la cebolla, el resto de la sal y el aceite. Calienta la mezcla en un sartén 5 minutos.",
      "Pasa cada tortilla por el aceite de chile, rellena con 1 cucharada de papa o de frijol y dóblala.",
      "Forra una olla o canasta con un trapo y una bolsa de plástico. Acomoda los tacos en capas apretadas y baña cada capa con más aceite.",
      "Tapa bien y deja sudar 30 minutos. Sirve con salsa verde."],
  tp:["El reposo tapado es la receta: el vapor ablanda las tortillas hasta que quedan suaves y grasosas.",
      "Para mantenerlos más tiempo, pon la olla tapada dentro de una hielera."],
  v:"tacos de canasta receta"},
 en:{n:"Basket Tacos (Tacos de Canasta)", b:"Sweated tacos: filled with potato or beans, brushed with chile oil and kept warm in a cloth-lined basket until they steam into one.",
  st:["Boil the potatoes in water with 1 teaspoon of the salt for 20 minutes. Drain and mash with the chipotle.",
      "Blend the guajillos with the garlic, onion, the rest of the salt and the oil. Heat the mixture in a pan for 5 minutes.",
      "Dip each tortilla in the chile oil, fill with 1 tablespoon of potato or beans and fold.",
      "Line a pot or basket with a towel and a plastic bag. Pack the tacos in tight layers, brushing each layer with more oil.",
      "Cover well and let them sweat 30 minutes. Serve with green salsa."],
  tp:["The covered rest is the recipe: the steam softens the tortillas until they turn tender and rich.",
      "To hold them longer, put the covered pot inside a cooler."],
  v:"tacos de canasta recipe"}},

{id:"gorditas", c:"Mexico", r:"latin-america", m:"main", t:45, s:4,
 i:[[500,"g","masa","structure","masa fresca de maíz","fresh corn masa"],
    [2,"tbsp","lard","fat","manteca de cerdo","lard"],
    [0.5,"tsp","salt","salt","sal","salt"],
    [300,"g","refriedbeans","protein","frijoles refritos","refried beans"],
    [150,"g","queso","protein","queso fresco","queso fresco","desmoronado","crumbled"],
    [0.25,"head","veg","garnish","lechuga","lettuce","rebanada fina","shredded"],
    [250,"ml","salsa","sauce","salsa verde","green salsa"],
    [2,"tbsp","oil","fat","aceite","oil"]],
 es:{n:"Gorditas de frijol con queso", b:"Tortillas gruesas de masa cocidas en comal, abiertas como bolsita y rellenas de frijol y queso.",
  st:["Amasa la masa con la manteca y la sal hasta que no se pegue en las manos. Si está seca, añade agua de a poco.",
      "Forma 8 bolas y aplánalas a 1 centímetro de grueso.",
      "Cuécelas en un comal a fuego medio con un poco de aceite, 4 minutos por lado, hasta que se inflen un poco y tengan manchas doradas.",
      "Ábrelas por un lado con un cuchillo, como pan árabe, cuando aún estén calientes.",
      "Rellena con frijoles, queso, lechuga y salsa."],
  tp:["Si se agrietan al aplanarlas, la masa está seca: añade agua.",
      "Envueltas en un trapo se mantienen suaves 30 minutos."],
  v:"gorditas de frijol con queso receta"},
 en:{n:"Bean and Cheese Gorditas", b:"Thick masa cakes cooked on a griddle, split open like a pocket and stuffed with beans and cheese.",
  st:["Knead the masa with the lard and salt until it no longer sticks to your hands. If dry, add water a little at a time.",
      "Shape 8 balls and flatten them to 1 centimetre thick.",
      "Cook on a griddle over medium heat with a little oil, 4 minutes per side, until they puff slightly and have golden spots.",
      "Slit them open along one side with a knife, like a pita pocket, while still hot.",
      "Fill with beans, cheese, lettuce and salsa."],
  tp:["If they crack when flattened, the masa is dry: add water.",
      "Wrapped in a towel they stay soft for 30 minutes."],
  v:"gorditas recipe"}},

{id:"molletes", c:"Mexico", r:"latin-america", m:"breakfast", t:25, s:4, o:200,
 i:[[4,"","bread","structure","bolillos","bolillo rolls","abiertos a la mitad","split in half"],
    [30,"g","butter","fat","mantequilla","butter","suave","soft"],
    [300,"g","refriedbeans","protein","frijoles refritos","refried beans"],
    [200,"g","cheese","protein","queso Chihuahua o manchego rallado","grated Chihuahua or Monterey Jack cheese"],
    [2,"","tomato","garnish","jitomates","tomatoes","en cubos","diced"],
    [0.25,"","onion","garnish","cebolla blanca","white onion","picada","chopped"],
    [1,"","chilli","garnish","chile serrano","serrano chile","picado","chopped"],
    [1,"handful","herb","garnish","cilantro","cilantro","picado","chopped"],
    [1,"","citrus","acid","limón","lime","en jugo","juiced"],
    [0.25,"tsp","salt","salt","sal","salt"]],
 es:{n:"Molletes", b:"Bolillo abierto con mantequilla, frijoles y queso gratinado, con pico de gallo encima. El desayuno de cafetería mexicana.",
  st:["Calienta el horno a 200 °C.",
      "Unta las mitades de bolillo con mantequilla y tuéstalas 5 minutos en el horno.",
      "Úntalas con frijoles, cubre con queso y hornea 8 minutos, hasta que el queso burbujee.",
      "Mientras, mezcla el jitomate, la cebolla, el chile, el cilantro, el limón y la sal.",
      "Sirve los molletes calientes con el pico de gallo encima."],
  tp:["Tostar el pan antes de los frijoles evita que quede aguado.",
      "Añade chorizo frito sobre los frijoles para la versión de fonda."],
  v:"molletes receta"},
 en:{n:"Molletes", b:"Split rolls with butter, refried beans and melted cheese, topped with pico de gallo. The Mexican café breakfast.",
  st:["Heat the oven to 200 °C.",
      "Butter the roll halves and toast them in the oven for 5 minutes.",
      "Spread with beans, cover with cheese and bake 8 minutes, until bubbling.",
      "Meanwhile, mix the tomato, onion, chile, cilantro, lime and salt.",
      "Serve the molletes hot with the pico de gallo on top."],
  tp:["Toasting the bread before the beans keeps it from going soggy.",
      "Add fried chorizo over the beans for the diner version."],
  v:"molletes recipe"}},

{id:"huevos-divorciados", c:"Mexico", r:"latin-america", m:"breakfast", t:30, s:2,
 i:[[4,"","egg","protein","huevos","eggs"],
    [4,"","corntortilla","structure","tortillas de maíz","corn tortillas"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [2,"","tomato","sauce","jitomates","tomatoes"],
    [4,"","tomatillo","sauce","tomatillos","tomatillos"],
    [2,"","chilli","aromatic","chiles serranos","serrano chiles"],
    [2,"clove","garlic","aromatic","ajo","garlic"],
    [0.25,"","onion","aromatic","cebolla","onion"],
    [0.5,"tsp","salt","salt","sal","salt"],
    [200,"g","refriedbeans","serve","frijoles refritos","refried beans"],
    [1,"handful","herb","garnish","cilantro","cilantro"]],
 es:{n:"Huevos divorciados", b:"Dos huevos estrellados, uno con salsa roja y otro con salsa verde, separados por una línea de frijoles.",
  st:["Hierve los jitomates, los tomatillos y los chiles 10 minutos. Licúa los jitomates con 1 chile, 1 diente de ajo y la mitad de la cebolla. Licúa los tomatillos igual con el resto.",
      "Fríe cada salsa por separado en 1 cucharadita de aceite 5 minutos. Sala al gusto.",
      "Pasa las tortillas por aceite caliente unos segundos para que se ablanden.",
      "Fríe los huevos en el resto del aceite, con la clara cuajada y la yema líquida.",
      "En cada plato pon 2 tortillas y 1 huevo encima de cada una. Cubre uno con salsa roja y otro con verde. Pon frijoles en medio y cilantro encima."],
  tp:["Las 2 salsas duran 4 días en el refrigerador: haz el doble.",
      "Con yema líquida, usa huevos frescos; en embarazo o con defensas bajas, cuécelos hasta que la yema cuaje."],
  v:"huevos divorciados receta"},
 en:{n:"Divorced Eggs", b:"Two fried eggs, one under red salsa and one under green, split down the middle by a line of beans.",
  st:["Boil the tomatoes, tomatillos and chiles for 10 minutes. Blend the tomatoes with 1 chile, 1 garlic clove and half the onion. Blend the tomatillos the same way with the rest.",
      "Fry each salsa separately in 1 teaspoon of oil for 5 minutes. Salt to taste.",
      "Pass the tortillas through hot oil for a few seconds to soften.",
      "Fry the eggs in the rest of the oil, whites set and yolks runny.",
      "On each plate put 2 tortillas with 1 egg on each. Cover one with red salsa and one with green. Put beans between them and cilantro on top."],
  tp:["Both salsas keep 4 days in the fridge: make double.",
      "For runny yolks use fresh eggs; if pregnant or immunocompromised, cook until the yolk sets."],
  v:"huevos divorciados recipe"}},

{id:"entomatadas", c:"Mexico", r:"latin-america", m:"main", t:40, s:4,
 i:[[600,"g","tomato","sauce","jitomates","tomatoes"],
    [0.5,"","onion","aromatic","cebolla","onion"],
    [2,"clove","garlic","aromatic","ajo","garlic"],
    [1,"","chilli","aromatic","chile serrano","serrano chile"],
    [1,"tbsp","oil","fat","aceite","oil"],
    [1,"tsp","salt","salt","sal","salt"],
    [12,"","corntortilla","structure","tortillas de maíz","corn tortillas"],
    [300,"g","chicken","protein","pollo cocido deshebrado","shredded cooked chicken"],
    [120,"ml","crema","garnish","crema mexicana","Mexican crema"],
    [100,"g","queso","garnish","queso fresco","queso fresco","desmoronado","crumbled"],
    [0.25,"","onion","garnish","cebolla","onion","en aros","in rings"]],
 es:{n:"Entomatadas", b:"Tortillas dobladas y bañadas en salsa de jitomate, rellenas de pollo. Más suaves que las enchiladas, sin chile seco.",
  st:["Hierve los jitomates y el chile 10 minutos. Licúalos con la cebolla, el ajo y la sal.",
      "Calienta el aceite y fríe la salsa 10 minutos, hasta que espese un poco.",
      "Calienta las tortillas en un comal.",
      "Pasa cada tortilla por la salsa caliente, rellena con pollo y dóblala en cuatro.",
      "Sirve 3 por plato con más salsa, crema, queso y aros de cebolla."],
  tp:["Sumerge las tortillas justo antes de servir para que no se deshagan.",
      "Sin pollo quedan bien con frijoles o solo con queso."],
  v:"entomatadas receta"},
 en:{n:"Entomatadas", b:"Folded tortillas bathed in tomato sauce and filled with chicken. Gentler than enchiladas, with no dried chile.",
  st:["Boil the tomatoes and chile for 10 minutes. Blend with the onion, garlic and salt.",
      "Heat the oil and fry the sauce for 10 minutes, until slightly thick.",
      "Warm the tortillas on a griddle.",
      "Dip each tortilla in the hot sauce, fill with chicken and fold into quarters.",
      "Serve 3 per plate with more sauce, crema, cheese and onion rings."],
  tp:["Dip the tortillas just before serving so they don't fall apart.",
      "Without chicken they are good with beans or just cheese."],
  v:"entomatadas recipe"}},

{id:"enfrijoladas", c:"Mexico", r:"latin-america", m:"main", t:30, s:4,
 i:[[600,"g","legume","sauce","frijoles negros cocidos","cooked black beans"],
    [400,"ml","water","liquid","líquido de cocción de los frijoles","bean cooking liquid"],
    [1,"","chipotleadobo","aromatic","chile chipotle en adobo","chipotle in adobo"],
    [1,"clove","garlic","aromatic","ajo","garlic"],
    [1,"tbsp","oil","fat","aceite","oil"],
    [1,"tsp","salt","salt","sal","salt"],
    [12,"","corntortilla","structure","tortillas de maíz","corn tortillas"],
    [150,"g","queso","protein","queso fresco","queso fresco","desmoronado","crumbled"],
    [120,"ml","crema","garnish","crema mexicana","Mexican crema"],
    [0.25,"","onion","garnish","cebolla morada","red onion","en aros","in rings"],
    [1,"","avocado","garnish","aguacate","avocado","en rebanadas","sliced"]],
 es:{n:"Enfrijoladas", b:"Tortillas bañadas en una crema tersa de frijol negro con chipotle, dobladas sobre queso fresco.",
  st:["Licúa los frijoles con su líquido, el chipotle, el ajo y la sal hasta que quede como crema espesa.",
      "Calienta el aceite y cuece la crema de frijol 5 minutos a fuego bajo. Si espesa demasiado, añade agua.",
      "Calienta las tortillas en un comal.",
      "Pasa cada tortilla por la crema de frijol, pon queso en el centro y dóblala en dos.",
      "Sirve con más frijol encima, crema, cebolla y aguacate."],
  tp:["La crema de frijol debe cubrir una cuchara, no pegarse: ajusta con agua.",
      "Añade 1 hoja de aguacate tostada al licuar para el sabor de Oaxaca."],
  v:"enfrijoladas receta"},
 en:{n:"Enfrijoladas", b:"Tortillas bathed in a smooth black bean sauce with chipotle, folded over queso fresco.",
  st:["Blend the beans with their liquid, the chipotle, garlic and salt until thick and creamy.",
      "Heat the oil and cook the bean sauce 5 minutes on low. If it gets too thick, add water.",
      "Warm the tortillas on a griddle.",
      "Dip each tortilla in the bean sauce, put cheese in the middle and fold in half.",
      "Serve with more bean sauce on top, crema, onion and avocado."],
  tp:["The bean sauce should coat a spoon, not cling to it: adjust with water.",
      "Blend in 1 toasted avocado leaf for the taste of Oaxaca."],
  v:"enfrijoladas recipe"}},

{id:"sopa-de-fideo", c:"Mexico", r:"latin-america", m:"soup", t:30, s:4,
 i:[[200,"g","pasta","structure","fideo delgado","fine vermicelli (fideo)"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [3,"","tomato","aromatic","jitomates","tomatoes"],
    [0.25,"","onion","aromatic","cebolla","onion"],
    [1,"clove","garlic","aromatic","ajo","garlic"],
    [1.5,"l","stock","liquid","caldo de pollo","chicken stock"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"sprig","herb","aromatic","cilantro","cilantro"],
    [60,"ml","crema","garnish","crema mexicana","Mexican crema"],
    [1,"","citrus","garnish","limón","lime","en cuartos","quartered"]],
 es:{n:"Sopa de fideo", b:"Fideo dorado en aceite y cocido en caldo de jitomate. La sopa aguada de todos los días en casa.",
  st:["Licúa los jitomates, la cebolla y el ajo. Cuela.",
      "Calienta el aceite en una olla y dora el fideo 3 minutos, moviendo sin parar, hasta que esté color avellana.",
      "Vierte el jitomate de golpe (salpica) y fríe 3 minutos.",
      "Añade el caldo, la sal y el cilantro. Hierve 8 minutos, hasta que el fideo esté suave.",
      "Sirve con crema y limón."],
  tp:["Dorar el fideo es el sabor: sin ese paso es solo pasta en caldo.",
      "Sácale el cilantro antes de servir: ya dio su sabor."],
  v:"sopa de fideo receta"},
 en:{n:"Mexican Noodle Soup (Sopa de Fideo)", b:"Fine noodles toasted in oil and simmered in tomato broth. The everyday soup of a Mexican home.",
  st:["Blend the tomatoes, onion and garlic. Strain.",
      "Heat the oil in a pot and toast the noodles for 3 minutes, stirring constantly, until the colour of hazelnut shells.",
      "Pour in the tomato all at once (it spatters) and fry 3 minutes.",
      "Add the stock, salt and cilantro. Boil 8 minutes, until the noodles are soft.",
      "Serve with crema and lime."],
  tp:["Toasting the noodles is the flavour: skip it and it's just pasta in broth.",
      "Pull out the cilantro before serving: it has done its job."],
  v:"sopa de fideo recipe"}},

{id:"crema-de-elote", c:"Mexico", r:"latin-america", m:"soup", t:40, s:4,
 i:[[600,"g","corn","protein","granos de elote","corn kernels","frescos o congelados","fresh or frozen"],
    [30,"g","butter","fat","mantequilla","butter"],
    [0.5,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"clove","garlic","aromatic","ajo","garlic"],
    [500,"ml","milk","liquid","leche","milk"],
    [500,"ml","stock","liquid","caldo de pollo o de verduras","chicken or vegetable stock"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"","chilli","garnish","chile poblano","poblano chile","asado, pelado, en rajas","roasted, peeled, in strips"],
    [60,"g","queso","garnish","queso fresco","queso fresco","en cubos","cubed"]],
 es:{n:"Crema de elote", b:"Sopa tersa de elote dulce con leche y mantequilla, con rajas de poblano y queso fresco encima.",
  st:["Derrite la mantequilla y sofríe la cebolla 5 minutos. Añade el ajo 1 minuto.",
      "Añade el elote y cuece 5 minutos. Separa 1 taza de granos para decorar.",
      "Añade el caldo y la sal; hierve 10 minutos.",
      "Licúa con la leche hasta que quede lisa. Cuela si quieres textura de restaurante.",
      "Calienta sin hervir y sirve con los granos apartados, rajas y queso."],
  tp:["No hiervas después de añadir la leche: se puede cortar.",
      "Con elote fuera de temporada, el congelado sabe más dulce que el de lata."],
  v:"crema de elote receta"},
 en:{n:"Cream of Corn Soup", b:"Silky sweet corn soup with milk and butter, topped with poblano strips and queso fresco.",
  st:["Melt the butter and cook the onion 5 minutes. Add the garlic for 1 minute.",
      "Add the corn and cook 5 minutes. Set aside 1 cup of kernels for garnish.",
      "Add the stock and salt; boil 10 minutes.",
      "Blend with the milk until smooth. Strain for a restaurant finish.",
      "Heat without boiling and serve with the reserved kernels, poblano strips and cheese."],
  tp:["Don't boil once the milk is in: it can curdle.",
      "Out of season, frozen corn tastes sweeter than canned."],
  v:"cream of corn soup mexican recipe"}},

{id:"caldo-tlalpeno", c:"Mexico", r:"latin-america", m:"soup", t:70, s:6,
 i:[[1,"kg","chicken","protein","piezas de pollo con hueso","bone-in chicken pieces"],
    [2.5,"l","water","liquid","agua","water"],
    [0.5,"","onion","aromatic","cebolla","onion"],
    [3,"clove","garlic","aromatic","ajo","garlic"],
    [2,"tsp","salt","salt","sal","salt"],
    [2,"","tomato","aromatic","jitomates","tomatoes"],
    [2,"","chipotleadobo","aromatic","chiles chipotles en adobo","chipotles in adobo"],
    [1,"tbsp","oil","fat","aceite","oil"],
    [2,"","veg","protein","zanahorias","carrots","en cubos","diced"],
    [2,"","veg","protein","calabacitas","zucchini","en cubos","diced"],
    [400,"g","legume","protein","garbanzos cocidos","cooked chickpeas"],
    [2,"sprig","herb","aromatic","epazote","epazote"],
    [1,"","avocado","garnish","aguacate","avocado","en cubos","diced"],
    [100,"g","queso","garnish","queso fresco o Oaxaca","queso fresco or Oaxaca cheese","en cubos","cubed"],
    [2,"","citrus","garnish","limones","limes"]],
 es:{n:"Caldo tlalpeño", b:"Caldo de pollo ahumado con chipotle, con garbanzo, zanahoria y calabacita, y aguacate y queso al servir.",
  st:["Cuece el pollo con el agua, la cebolla, 2 dientes de ajo y la sal 40 minutos a fuego bajo. Saca el pollo y deshébralo.",
      "Licúa los jitomates, los chipotles y 1 diente de ajo con 250 ml del líquido de la olla.",
      "En otra olla, fríe la mezcla en el aceite 5 minutos. Añade el líquido de la olla colado.",
      "Añade la zanahoria y cuece 10 minutos. Añade la calabacita, los garbanzos y el epazote; 8 minutos más.",
      "Regresa el pollo y sirve con aguacate, queso y limón."],
  tp:["El queso va en el plato y el caldo encima: así se funde apenas.",
      "Empieza con 1 chipotle si no te gusta muy picante."],
  v:"caldo tlalpeño receta"},
 en:{n:"Caldo Tlalpeño (Smoky Chicken Soup)", b:"Chicken soup smoky with chipotle, with chickpeas, carrot and zucchini, and avocado and cheese at the table.",
  st:["Simmer the chicken with the water, onion, 2 garlic cloves and salt for 40 minutes on low. Lift out the chicken and shred it.",
      "Blend the tomatoes, chipotles and 1 garlic clove with 250 ml of the cooking liquid.",
      "In another pot, fry the mixture in the oil for 5 minutes. Add the strained cooking liquid.",
      "Add the carrot and cook 10 minutes. Add the zucchini, chickpeas and epazote; 8 minutes more.",
      "Return the chicken and serve with avocado, cheese and lime."],
  tp:["Put the cheese in the bowl and the soup on top: it just softens.",
      "Start with 1 chipotle if you don't like it very hot."],
  v:"caldo tlalpeño recipe"}}
];
