module.exports = [
{id:"tacos-gobernador", c:"Mexico", r:"latin-america", m:"main", t:30, s:4,
 i:[[500,"g","shrimp","protein","camarones pelados","peeled shrimp","picados","chopped"],
    [2,"tbsp","butter","fat","mantequilla","butter"],
    [0.5,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","chilli","aromatic","chile poblano asado","roasted poblano chilli","en rajas","in strips"],
    [2,"","tomato","structure","tomates","tomatoes","picados","chopped"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [1,"tsp","salt","salt","sal","salt"],
    [8,"","flourtortilla","structure","tortillas de harina","flour tortillas"],
    [200,"g","cheese","protein","queso Chihuahua o manchego","Chihuahua or Monterey Jack cheese","rallado","grated"],
    [1,"","avocado","garnish","aguacate","avocado","en rebanadas","sliced"]],
 es:{n:"Tacos gobernador", b:"Tacos de camarón guisado con poblano y queso fundido en tortilla dorada. De Sinaloa.",
  st:["Sofríe la cebolla en la mantequilla 3 minutos. Añade las rajas y el tomate y cuece 3 minutos.",
      "Añade el camarón, el orégano y la sal y cuece 3 minutos, hasta que esté rosado.",
      "Pon queso en media tortilla, añade el camarón y dobla.",
      "Dora en un comal 2 minutos por lado, hasta que el queso se funda.",
      "Sirve con el aguacate."],
  tp:["Pica el camarón en trozos pequeños para que se reparta bien.",
      "No cuezas el camarón de más: termina de hacerse en el comal."],
  v:"tacos gobernador sinaloa receta"},
 en:{n:"Tacos Gobernador (Shrimp and Cheese Tacos)", b:"Tacos of stewed shrimp with poblano and melted cheese in a crisped tortilla. From Sinaloa.",
  st:["Cook the onion in the butter for 3 minutes. Add the poblano and tomato and cook 3 minutes.",
      "Add the shrimp, oregano and salt and cook 3 minutes, until pink.",
      "Put cheese on half a tortilla, add the shrimp and fold.",
      "Crisp on a griddle for 2 minutes a side, until the cheese melts.",
      "Serve with the avocado."],
  tp:["Chop the shrimp small so it spreads evenly.",
      "Don't overcook the shrimp: it finishes on the griddle."],
  v:"tacos gobernador recipe"}},

{id:"camarones-al-mojo-de-ajo", c:"Mexico", r:"latin-america", m:"main", t:20, s:4,
 i:[[700,"g","shrimp","protein","camarones grandes","large shrimp","pelados, con cola","peeled, tails on"],
    [60,"g","butter","fat","mantequilla","butter"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [10,"clove","garlic","aromatic","ajo","garlic","picado fino","finely chopped"],
    [2,"","chilli","aromatic","chiles guajillo","guajillo chillies","en aros","in rings"],
    [1,"","citrus","acid","limón","lime","en jugo","juiced"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"handful","herb","garnish","perejil","parsley","picado","chopped"]],
 es:{n:"Camarones al mojo de ajo", b:"Camarones salteados en mantequilla con mucho ajo dorado y chile guajillo. Clásico de las marisquerías.",
  st:["Calienta la mantequilla y el aceite a fuego medio-bajo.",
      "Añade el ajo y el chile y cuece 4 minutos, hasta que el ajo esté dorado pálido.",
      "Sube el fuego, añade los camarones y la sal y saltea 3 minutos, hasta que estén rosados.",
      "Añade el jugo de limón.",
      "Termina con el perejil y sirve con arroz blanco."],
  tp:["Cuida el ajo: debe dorarse suave, no quemarse.",
      "Seca bien los camarones antes de saltearlos."],
  v:"camarones al mojo de ajo receta"},
 en:{n:"Camarones al Mojo de Ajo (Garlic Butter Shrimp)", b:"Shrimp sautéed in butter with plenty of golden garlic and guajillo chilli. A seafood-restaurant classic.",
  st:["Heat the butter and oil over medium-low heat.",
      "Add the garlic and chilli and cook 4 minutes, until the garlic is pale gold.",
      "Raise the heat, add the shrimp and salt and sauté 3 minutes, until pink.",
      "Add the lime juice.",
      "Finish with the parsley and serve with white rice."],
  tp:["Watch the garlic: it should turn gently golden, not burn.",
      "Pat the shrimp dry before sautéing."],
  v:"garlic shrimp mexican recipe"}},

{id:"chalupas-poblanas", c:"Mexico", r:"latin-america", m:"snack", t:40, s:4,
 i:[[12,"","corntortilla","structure","tortillas de maíz pequeñas","small corn tortillas"],
    [80,"g","lard","fat","manteca de cerdo","lard"],
    [300,"g","pork","protein","carne de cerdo cocida","cooked pork","deshebrada","shredded"],
    [4,"","tomatillo","sauce","tomates verdes","tomatillos"],
    [2,"","chilli","sauce","chiles serranos","serrano chillies"],
    [4,"","tomato","sauce","jitomates","tomatoes"],
    [2,"","chilli","sauce","chiles chipotles secos","dried chipotle chillies"],
    [2,"clove","garlic","aromatic","ajo","garlic"],
    [1,"tsp","salt","salt","sal","salt"],
    [0.5,"","onion","garnish","cebolla","onion","picada","chopped"]],
 es:{n:"Chalupas poblanas", b:"Tortillas pequeñas fritas en manteca, mitad con salsa verde y mitad con salsa roja, con cerdo deshebrado. De Puebla.",
  st:["Cuece los tomates verdes con los serranos 8 minutos y licúa con 1 ajo y media cucharadita de sal.",
      "Asa los jitomates y los chipotles y licúa con el otro ajo y el resto de la sal.",
      "Calienta la manteca en un comal y fríe las tortillas por un lado 1 minuto.",
      "Voltea y baña la mitad de cada una con salsa verde y la otra mitad con salsa roja.",
      "Cubre con el cerdo y la cebolla y sirve de inmediato."],
  tp:["Las tortillas deben quedar suaves por dentro y crujientes en los bordes.",
      "Quita las semillas de los chiles para que piquen menos."],
  v:"chalupas poblanas receta"},
 en:{n:"Chalupas Poblanas", b:"Small tortillas fried in lard, half with green salsa and half with red, topped with shredded pork. From Puebla.",
  st:["Boil the tomatillos with the serranos for 8 minutes and blend with 1 garlic clove and half a teaspoon of salt.",
      "Char the tomatoes and chipotles and blend with the other garlic clove and the rest of the salt.",
      "Heat the lard on a griddle and fry the tortillas on one side for 1 minute.",
      "Turn and spoon green salsa over half of each and red salsa over the other half.",
      "Top with the pork and onion and serve at once."],
  tp:["The tortillas should stay soft in the middle and crisp at the edges.",
      "Seed the chillies for less heat."],
  v:"chalupas poblanas recipe"}},

{id:"machaca-con-huevo", c:"Mexico", r:"latin-america", m:"breakfast", t:20, s:4,
 i:[[150,"g","driedmeat","protein","machaca (carne seca deshebrada)","machaca (shredded dried beef)"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [0.5,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"","tomato","structure","tomates","tomatoes","picados","chopped"],
    [2,"","chilli","aromatic","chiles serranos o jalapeños","serrano or jalapeño chillies","picados","chopped"],
    [6,"","egg","protein","huevos","eggs","batidos","beaten"],
    [8,"","flourtortilla","serve","tortillas de harina","flour tortillas"]],
 es:{n:"Machaca con huevo", b:"Carne seca deshebrada revuelta con huevo, tomate y chile. El desayuno de Monterrey, en tortilla de harina.",
  st:["Sofríe la cebolla, el tomate y el chile en el aceite 4 minutos.",
      "Añade la machaca y cuece 3 minutos, hasta que se hidrate con el jugo del tomate.",
      "Añade los huevos y revuelve a fuego medio 2 minutos, hasta que cuajen.",
      "Prueba antes de salar: la machaca ya es salada.",
      "Sirve con las tortillas de harina calientes."],
  tp:["Si la machaca está muy seca, añade una cucharada de agua con el tomate.",
      "Se come en burritos para llevar."],
  v:"machaca con huevo receta"},
 en:{n:"Machaca con Huevo (Dried Beef and Eggs)", b:"Shredded dried beef scrambled with egg, tomato and chilli. Monterrey's breakfast, in a flour tortilla.",
  st:["Cook the onion, tomato and chilli in the oil for 4 minutes.",
      "Add the machaca and cook 3 minutes, until it rehydrates in the tomato juice.",
      "Add the eggs and scramble over medium heat for 2 minutes, until set.",
      "Taste before salting: machaca is already salty.",
      "Serve with the warm flour tortillas."],
  tp:["If the machaca is very dry, add a spoonful of water with the tomato.",
      "It's eaten in burritos to go."],
  v:"machaca con huevo recipe"}},

{id:"chilorio", c:"Mexico", r:"latin-america", m:"main", t:180, s:8,
 i:[[1.5,"kg","pork","protein","pierna o paleta de cerdo","pork leg or shoulder","en trozos","in chunks"],
    [1,"l","water","liquid","agua","water"],
    [2,"tsp","salt","salt","sal","salt"],
    [8,"","chilli","sauce","chiles anchos o guajillo","ancho or guajillo chillies","sin semillas","seeded"],
    [4,"clove","garlic","aromatic","ajo","garlic"],
    [1,"tsp","spice","aromatic","comino","cumin"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [80,"ml","whitevinegar","acid","vinagre blanco","white vinegar"],
    [3,"tbsp","lard","fat","manteca de cerdo","lard"]],
 es:{n:"Chilorio sinaloense", b:"Cerdo cocido, deshebrado y frito en manteca con adobo de chile y vinagre. Relleno de burritos en Sinaloa.",
  st:["Cuece el cerdo en el agua con la sal 90 minutos, hasta que se deshaga. Deshebra y guarda 250 ml del líquido.",
      "Remoja los chiles en agua caliente 15 minutos. Licúa con el ajo, el comino, el orégano, el vinagre y el líquido reservado.",
      "Calienta la manteca y fríe la carne 5 minutos.",
      "Añade el adobo y cuece a fuego bajo 30 minutos, removiendo, hasta que se absorba y la carne quede jugosa.",
      "Sirve en burritos o con tortillas."],
  tp:["Guarda en frascos cubierto con su grasa; dura 1 semana en la nevera.",
      "Mejora de un día para otro."],
  v:"chilorio sinaloense receta"},
 en:{n:"Chilorio (Sinaloa Chilli Pork)", b:"Pork simmered, shredded and fried in lard with a chilli and vinegar sauce. Burrito filling in Sinaloa.",
  st:["Simmer the pork in the water with the salt for 90 minutes, until falling apart. Shred and keep 250 ml of the liquid.",
      "Soak the chillies in hot water for 15 minutes. Blend with the garlic, cumin, oregano, vinegar and the reserved liquid.",
      "Heat the lard and fry the meat for 5 minutes.",
      "Add the sauce and cook on low for 30 minutes, stirring, until absorbed and the meat is juicy.",
      "Serve in burritos or with tortillas."],
  tp:["Store in jars covered with its fat; keeps 1 week in the fridge.",
      "It improves overnight."],
  v:"chilorio recipe"}},

{id:"carne-asada-nortena", c:"Mexico", r:"latin-america", m:"main", t:30, s:6,
 i:[[1.2,"kg","beef","protein","arrachera o diezmillo delgado","thin skirt or chuck steak"],
    [3,"","citrus","acid","limones","limes","en jugo","juiced"],
    [1,"","citrus","acid","naranja","orange","en jugo","juiced"],
    [3,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [2,"tsp","salt","salt","sal gruesa","coarse salt"],
    [1,"tsp","pepper","aromatic","pimienta negra","black pepper"],
    [6,"","scallion","serve","cebollitas cambray","spring onions"],
    [12,"","corntortilla","serve","tortillas de maíz","corn tortillas"]],
 es:{n:"Carne asada norteña", b:"Carne delgada marinada en limón y naranja, asada al carbón con cebollitas. El domingo en el norte de México.",
  st:["Marina la carne con los jugos, el ajo y la pimienta 1 hora.",
      "Enciende el carbón hasta que esté blanco.",
      "Sala la carne justo antes de asarla y ásala 3 minutos por lado.",
      "Asa las cebollitas junto a la carne hasta que estén tiernas.",
      "Pica la carne y sirve en tortillas calientes con las cebollitas."],
  tp:["Sala justo antes de asar para que no suelte jugo.",
      "Corta siempre contra la fibra."],
  v:"carne asada norteña receta"},
 en:{n:"Carne Asada Norteña (Northern Grilled Steak)", b:"Thin steak marinated in lime and orange, grilled over charcoal with spring onions. Sunday in northern Mexico.",
  st:["Marinate the meat with the juices, garlic and pepper for 1 hour.",
      "Light the charcoal until white.",
      "Salt the meat just before grilling and grill 3 minutes a side.",
      "Grill the spring onions beside the meat until tender.",
      "Chop the meat and serve in warm tortillas with the onions."],
  tp:["Salt just before grilling so it doesn't weep.",
      "Always slice against the grain."],
  v:"carne asada recipe"}},

{id:"sopa-de-habas", c:"Mexico", r:"latin-america", m:"soup", t:75, s:6,
 i:[[300,"g","legume","protein","habas secas peladas","dried peeled fava beans"],
    [2,"l","water","liquid","agua","water"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [0.5,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"","tomato","sauce","jitomates","tomatoes","licuados","blended"],
    [1,"","chipotle","aromatic","chile chipotle seco","dried chipotle chilli"],
    [1,"handful","herb","aromatic","cilantro","cilantro"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Sopa de habas", b:"Sopa espesa de habas secas con jitomate, chipotle y cilantro. Comida de Cuaresma en el centro de México.",
  st:["Remoja las habas 4 horas y escúrrelas.",
      "Sofríe la cebolla y el ajo en el aceite 4 minutos. Añade el jitomate y cuece 5 minutos.",
      "Añade las habas, el agua, el chipotle y la sal. Cuece 50 minutos, hasta que las habas se deshagan.",
      "Añade el cilantro los últimos 5 minutos.",
      "Retira el chipotle y sirve."],
  tp:["Si la quieres lisa, licúa la mitad.",
      "Rompe el chipotle si la quieres más picante."],
  v:"sopa de habas receta"},
 en:{n:"Sopa de Habas (Fava Bean Soup)", b:"A thick soup of dried fava beans with tomato, chipotle and cilantro. Lenten food in central Mexico.",
  st:["Soak the beans 4 hours and drain.",
      "Cook the onion and garlic in the oil for 4 minutes. Add the tomato and cook 5 minutes.",
      "Add the beans, water, chipotle and salt. Cook 50 minutes, until the beans break down.",
      "Add the cilantro for the last 5 minutes.",
      "Remove the chipotle and serve."],
  tp:["For a smooth soup, blend half.",
      "Break the chipotle open for more heat."],
  v:"fava bean soup recipe"}},

{id:"tamales-de-dulce", c:"Mexico", r:"latin-america", m:"sweet", t:120, s:16,
 i:[[500,"g","masa","structure","harina de maíz para tamales","masa harina for tamales"],
    [200,"g","lard","fat","manteca de cerdo","lard"],
    [150,"g","sugar","sweet","azúcar","sugar"],
    [1,"tsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [1,"pinch","salt","salt","sal","salt"],
    [450,"ml","water","liquid","agua tibia","warm water"],
    [1,"tsp","foodcolour","garnish","colorante rosa","pink food colouring"],
    [80,"g","driedfruit","sweet","pasas","raisins"],
    [16,"","cornhusk","structure","hojas de maíz","corn husks","remojadas","soaked"]],
 es:{n:"Tamales de dulce", b:"Tamales rosados, dulces y esponjosos con pasas. Se toman con atole la mañana del 2 de febrero.",
  st:["Bate la manteca 5 minutos, hasta que esté blanca y esponjosa.",
      "Añade la harina, el azúcar, el polvo de hornear, la sal, el colorante y el agua poco a poco. Bate 5 minutos.",
      "Añade las pasas.",
      "Pon 3 cucharadas de masa en cada hoja y dobla.",
      "Cuece al vapor 60 minutos, hasta que la masa se despegue de la hoja."],
  tp:["Una bolita de masa debe flotar en agua: es señal de que está bien batida.",
      "Sin colorante quedan igual de buenos, solo blancos."],
  v:"tamales de dulce rosas receta"},
 en:{n:"Tamales de Dulce (Sweet Pink Tamales)", b:"Pink, sweet, fluffy tamales with raisins. Eaten with atole on the morning of 2 February.",
  st:["Beat the lard for 5 minutes, until white and fluffy.",
      "Add the masa harina, sugar, baking powder, salt, colouring and water gradually. Beat 5 minutes.",
      "Stir in the raisins.",
      "Put 3 tablespoons of dough on each husk and fold.",
      "Steam 60 minutes, until the dough comes away from the husk."],
  tp:["A little ball of dough should float in water: that means it's well beaten.",
      "Without colouring they're just as good, only white."],
  v:"sweet tamales recipe"}},

{id:"chocolate-caliente-mexicano", c:"Mexico", r:"latin-america", m:"drink", t:15, s:4,
 i:[[1,"l","milk","liquid","leche","milk"],
    [180,"g","tablechocolate","sweet","chocolate de mesa","Mexican table chocolate","en trozos","in pieces"],
    [1,"","spice","aromatic","rama de canela","cinnamon stick"]],
 es:{n:"Chocolate caliente mexicano", b:"Chocolate de mesa con canela, batido con molinillo hasta hacer espuma. Con pan dulce en la merienda.",
  st:["Calienta la leche con la canela hasta que humee.",
      "Añade el chocolate y remueve hasta que se disuelva.",
      "Cuece 5 minutos a fuego bajo.",
      "Saca la canela.",
      "Bate con molinillo o batidor hasta que haga mucha espuma y sirve."],
  tp:["La espuma es parte del chocolate: bate justo antes de servir.",
      "También se hace con agua en lugar de leche, como en Oaxaca."],
  v:"chocolate caliente mexicano receta"},
 en:{n:"Mexican Hot Chocolate", b:"Table chocolate with cinnamon, whisked with a molinillo until frothy. With sweet bread at teatime.",
  st:["Heat the milk with the cinnamon until steaming.",
      "Add the chocolate and stir until dissolved.",
      "Simmer 5 minutes on low.",
      "Remove the cinnamon.",
      "Froth with a molinillo or whisk until very foamy and serve."],
  tp:["The foam is part of it: whisk just before serving.",
      "It's also made with water instead of milk, as in Oaxaca."],
  v:"mexican hot chocolate recipe"}},

{id:"flan-napolitano", c:"Mexico", r:"latin-america", m:"sweet", t:90, s:10, o:180,
 i:[[150,"g","sugar","caramel","azúcar","sugar"],
    [395,"g","condensedmilk","sweet","leche condensada","condensed milk"],
    [360,"ml","evaporatedmilk","liquid","leche evaporada","evaporated milk"],
    [190,"g","creamcheese","enrich","queso crema","cream cheese"],
    [5,"","egg","set","huevos","eggs"],
    [1,"tsp","vanilla","aromatic","extracto de vainilla","vanilla extract"]],
 es:{n:"Flan napolitano", b:"Flan mexicano de leche condensada y queso crema, más denso y cremoso, con caramelo.",
  st:["Derrite el azúcar a fuego medio hasta tener un caramelo ámbar y cubre un molde de 22 cm.",
      "Licúa la leche condensada, la leche evaporada, el queso crema, los huevos y la vainilla 1 minuto.",
      "Vierte sobre el caramelo y cubre con papel de aluminio.",
      "Hornea al baño María a 180 °C durante 60 minutos, hasta que cuaje con un temblor en el centro.",
      "Enfría, refrigera 6 horas y desmolda."],
  tp:["Deja reposar la mezcla 5 minutos para que suban las burbujas.",
      "Para desmoldar, pasa un cuchillo por el borde y voltea con decisión."],
  v:"flan napolitano receta"},
 en:{n:"Flan Napolitano (Mexican Cream Cheese Flan)", b:"A Mexican flan of condensed milk and cream cheese, denser and creamier, with caramel.",
  st:["Melt the sugar over medium heat to an amber caramel and coat a 22 cm mould.",
      "Blend the condensed milk, evaporated milk, cream cheese, eggs and vanilla for 1 minute.",
      "Pour over the caramel and cover with foil.",
      "Bake in a water bath at 180 °C for 60 minutes, until set with a wobble in the centre.",
      "Cool, refrigerate 6 hours and turn out."],
  tp:["Let the mixture rest 5 minutes so the bubbles rise.",
      "To turn out, run a knife round the edge and flip decisively."],
  v:"flan napolitano recipe"}}
];
