module.exports = [
{id:"tamales-rajas", c:"Mexico", r:"latin-america", m:"main", t:180, s:10,
 i:[[1,"kg","masa","structure","masa fresca de maíz para tamales","fresh corn masa for tamales"],
    [250,"g","lard","fat","manteca de cerdo","lard","a temperatura ambiente","at room temperature"],
    [250,"ml","stock","liquid","caldo de pollo","chicken stock","tibio","warm"],
    [2,"tsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [2,"tsp","salt","salt","sal","salt"],
    [5,"","chilli","aromatic","chiles poblanos","poblano chiles","asados, pelados, en tiras","roasted, peeled, cut in strips"],
    [2,"","tomato","aromatic","jitomates","tomatoes","en rodajas finas","thinly sliced"],
    [1,"","onion","aromatic","cebolla blanca","white onion","en tiras","sliced"],
    [400,"g","queso","protein","queso Oaxaca","Oaxaca cheese","deshebrado","pulled into strands"],
    [25,"","cornhusk","serve","hojas de maíz para tamal","corn husks for tamales","remojadas","soaked"]],
 es:{n:"Tamales de rajas con queso", b:"Masa batida con manteca hasta que flota, rellena de chile poblano, jitomate y queso que se derrite. Tamales para una tarde con familia.",
  st:["Remoja las hojas en agua caliente 30 minutos hasta que estén flexibles. Escúrrelas.",
      "Bate la manteca con una batidora 3 minutos hasta que esté blanca y esponjosa.",
      "Añade la masa en 4 partes, alternando con el caldo tibio, la sal y el polvo de hornear. Bate 10 minutos más.",
      "Prueba de flotación: una bolita de masa en un vaso de agua fría debe flotar. Si se hunde, bate 5 minutos más.",
      "Unta 2 cucharadas de masa en la parte ancha de cada hoja, dejando borde. Pon rajas, 1 rodaja de jitomate, cebolla y queso en el centro.",
      "Dobla los lados sobre el relleno y luego la punta hacia atrás.",
      "Acomoda los tamales de pie, con el doblez abajo, en una vaporera con agua que no los toque. Tapa con hojas sobrantes y un trapo.",
      "Cuece a vapor 60 a 75 minutos. Están listos cuando la masa se despega sola de la hoja. Reposa 15 minutos antes de servir."],
  tp:["Pon una moneda en el agua de la vaporera: mientras suene, hay agua. Cuando deje de sonar, añade agua caliente.",
      "Congelados en su hoja duran 3 meses; se recalientan al vapor 20 minutos."],
  v:"tamales de rajas con queso receta"},
 en:{n:"Poblano and Cheese Tamales", b:"Masa whipped with lard until it floats, filled with poblano, tomato and melting cheese. Tamales for an afternoon with family.",
  st:["Soak the husks in hot water for 30 minutes until pliable. Drain.",
      "Beat the lard with a mixer for 3 minutes until white and fluffy.",
      "Add the masa in 4 parts, alternating with the warm stock, the salt and the baking powder. Beat 10 minutes more.",
      "Float test: a small ball of masa dropped in a glass of cold water should float. If it sinks, beat 5 minutes more.",
      "Spread 2 tablespoons of masa on the wide end of each husk, leaving a border. Put poblano strips, 1 tomato slice, onion and cheese in the middle.",
      "Fold the sides over the filling, then fold the tip back.",
      "Stand the tamales upright, fold down, in a steamer with water that doesn't touch them. Cover with leftover husks and a towel.",
      "Steam 60 to 75 minutes. They are done when the masa pulls cleanly away from the husk. Rest 15 minutes before serving."],
  tp:["Drop a coin in the steamer water: while it rattles, there is water. When it goes quiet, add hot water.",
      "Frozen in their husks they keep 3 months; reheat by steaming 20 minutes."],
  v:"rajas con queso tamales recipe"}},

{id:"mole-de-olla", c:"Mexico", r:"latin-america", m:"soup", t:180, s:6,
 i:[[1,"kg","beef","protein","chambarete de res con hueso","bone-in beef shank","en trozos","in pieces"],
    [3,"l","water","liquid","agua","water"],
    [0.5,"","onion","aromatic","cebolla blanca","white onion"],
    [4,"clove","garlic","aromatic","ajo","garlic"],
    [2,"tsp","salt","salt","sal","salt"],
    [3,"","chilli","aromatic","chiles guajillo","guajillo chiles","sin semillas","seeded"],
    [2,"","ancho","aromatic","chiles anchos","ancho chiles","sin semillas","seeded"],
    [2,"","tomato","aromatic","jitomates","tomatoes"],
    [2,"","corn","protein","elotes","ears of corn","en rodajas gruesas","cut in thick rounds"],
    [2,"","veg","protein","calabacitas","zucchini","en trozos","in chunks"],
    [1,"","veg","protein","chayote","chayote","pelado, en trozos","peeled, in chunks"],
    [150,"g","veg","protein","ejotes","green beans","en trozos","in pieces"],
    [2,"","potato","protein","papas","potatoes","en cubos","cubed"],
    [2,"sprig","herb","aromatic","epazote","epazote"],
    [3,"","citrus","garnish","limones","limes","en cuartos","quartered"]],
 es:{n:"Mole de olla", b:"El caldo rojo de res con chile guajillo y ancho, lleno de elote, calabacita y chayote. Nada que ver con el mole de fiesta: este es de diario.",
  st:["Pon la carne en la olla con el agua, la cebolla, 2 dientes de ajo y la sal. Hierve, espuma y cuece tapado a fuego bajo 2 horas, hasta que la carne esté tierna.",
      "Remoja los chiles en agua caliente 15 minutos. Licúalos con los jitomates, 2 dientes de ajo y 250 ml del líquido de la olla. Cuela.",
      "Vierte el chile colado a la olla y hierve 10 minutos.",
      "Añade el elote y la papa; cuece 10 minutos. Añade el chayote y los ejotes; 8 minutos. Termina con la calabacita y el epazote, 5 minutos.",
      "Prueba de sal y sirve con limón."],
  tp:["Colar el chile es lo que da un caldo liso en vez de uno con pellejos.",
      "Las verduras van por orden de dureza para que ninguna quede deshecha."],
  v:"mole de olla receta"},
 en:{n:"Mole de Olla (Beef and Vegetable Chile Soup)", b:"The red beef soup with guajillo and ancho chiles, full of corn, zucchini and chayote. Nothing like party mole: this one is for every day.",
  st:["Put the beef in the pot with the water, onion, 2 garlic cloves and the salt. Bring to a boil, skim and simmer covered on low for 2 hours, until tender.",
      "Soak the chiles in hot water for 15 minutes. Blend them with the tomatoes, 2 garlic cloves and 250 ml of the cooking liquid. Strain.",
      "Pour the strained chile into the pot and boil 10 minutes.",
      "Add the corn and potato; cook 10 minutes. Add the chayote and green beans; 8 minutes. Finish with the zucchini and epazote, 5 minutes.",
      "Taste for salt and serve with lime."],
  tp:["Straining the chile is what gives a smooth soup instead of one full of skins.",
      "The vegetables go in by hardness so none turns to mush."],
  v:"mole de olla recipe"}},

{id:"albondigas-chipotle", c:"Mexico", r:"latin-america", m:"main", t:60, s:4,
 i:[[600,"g","beef","protein","carne molida de res","ground beef"],
    [60,"g","rice","structure","arroz crudo","uncooked rice","enjuagado","rinsed"],
    [1,"","egg","binder","huevo","egg"],
    [1,"handful","herb","aromatic","hierbabuena","mint","picada","chopped"],
    [1,"tsp","salt","salt","sal","salt"],
    [4,"","tomato","sauce","jitomates","tomatoes"],
    [2,"","chipotle","aromatic","chiles chipotles en adobo","chipotles in adobo"],
    [0.5,"","onion","aromatic","cebolla","onion"],
    [2,"clove","garlic","aromatic","ajo","garlic"],
    [500,"ml","stock","liquid","caldo de pollo","chicken stock"],
    [1,"tbsp","oil","fat","aceite","oil"]],
 es:{n:"Albóndigas en chipotle", b:"Albóndigas de res con arroz y hierbabuena, cocidas en un caldillo de jitomate y chipotle. El arroz se cuece dentro y las deja suaves.",
  st:["Mezcla la carne, el arroz, el huevo, la hierbabuena y la sal con las manos. Forma 16 bolas.",
      "Licúa los jitomates, los chipotles, la cebolla, el ajo y el caldo.",
      "Calienta el aceite en una olla ancha y fríe la salsa 5 minutos, hasta que cambie de color.",
      "Baja el fuego, acomoda las albóndigas en la salsa sin moverlas y tapa.",
      "Cuece 35 minutos a fuego bajo. Muévelas con cuidado a la mitad. Están listas cuando el arroz de dentro está suave."],
  tp:["No aprietes al formarlas: si la mezcla queda compacta, las albóndigas quedan duras.",
      "Empieza con 1 chipotle y añade más al final si quieres más picante."],
  v:"albondigas en chipotle receta"},
 en:{n:"Meatballs in Chipotle Sauce", b:"Beef meatballs with rice and mint, simmered in a tomato and chipotle broth. The rice cooks inside and keeps them tender.",
  st:["Mix the beef, rice, egg, mint and salt with your hands. Shape 16 balls.",
      "Blend the tomatoes, chipotles, onion, garlic and stock.",
      "Heat the oil in a wide pot and fry the sauce for 5 minutes, until it darkens.",
      "Lower the heat, set the meatballs in the sauce without stirring and cover.",
      "Simmer 35 minutes on low. Turn them gently halfway. They are done when the rice inside is soft."],
  tp:["Don't squeeze when shaping: a packed mixture makes tough meatballs.",
      "Start with 1 chipotle and add more at the end if you want more heat."],
  v:"albondigas en chipotle recipe"}},

{id:"pescado-veracruzana", c:"Mexico", r:"latin-america", m:"main", t:40, s:4,
 i:[[4,"fillet","whitefish","protein","filetes de huachinango o robalo","red snapper or sea bass fillets"],
    [1,"tsp","salt","salt","sal","salt"],
    [3,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [1,"","onion","aromatic","cebolla blanca","white onion","en tiras","sliced"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [600,"g","tomato","sauce","jitomates","tomatoes","picados","chopped"],
    [80,"g","olives","umami","aceitunas verdes","green olives","sin hueso","pitted"],
    [2,"tbsp","capers","umami","alcaparras","capers"],
    [4,"","pickledpepper","aromatic","chiles güeros en escabeche","pickled güero chiles"],
    [2,"leaf","herb","aromatic","hojas de laurel","bay leaves"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"]],
 es:{n:"Pescado a la veracruzana", b:"Pescado blanco en una salsa de jitomate con aceitunas, alcaparras y chiles güeros. El cruce de España y Veracruz en un solo sartén.",
  st:["Sala el pescado y déjalo 10 minutos.",
      "Calienta el aceite en un sartén ancho y sofríe la cebolla 5 minutos. Añade el ajo 1 minuto.",
      "Añade el jitomate, el laurel y el orégano. Cuece 10 minutos hasta que espese.",
      "Añade las aceitunas, las alcaparras y los chiles.",
      "Acomoda el pescado encima, cúbrelo con salsa, tapa y cuece 8 a 10 minutos, hasta que se separe en lajas."],
  tp:["Las aceitunas y alcaparras ya son saladas: prueba antes de añadir más sal a la salsa.",
      "Con arroz blanco para recoger la salsa."],
  v:"pescado a la veracruzana receta"},
 en:{n:"Veracruz-Style Fish", b:"White fish in a tomato sauce with olives, capers and güero chiles. Spain meets Veracruz in one pan.",
  st:["Salt the fish and let it sit 10 minutes.",
      "Heat the oil in a wide pan and cook the onion 5 minutes. Add the garlic for 1 minute.",
      "Add the tomato, bay and oregano. Cook 10 minutes until thick.",
      "Add the olives, capers and chiles.",
      "Lay the fish on top, spoon sauce over it, cover and cook 8 to 10 minutes, until it flakes."],
  tp:["Olives and capers are already salty: taste before adding more salt to the sauce.",
      "Serve with white rice to catch the sauce."],
  v:"veracruz style fish recipe"}},

{id:"aguachile", c:"Mexico", ce:"México", r:"latin-america", m:"starter", t:30, s:4,
 i:[[500,"g","shrimp","protein","camarones crudos muy frescos","very fresh raw shrimp","pelados, abiertos en mariposa","peeled, butterflied"],
    [10,"","citrus","acid","limones","limes","en jugo","juiced"],
    [4,"","chilli","aromatic","chiles serranos","serrano chiles"],
    [1,"bunch","herb","aromatic","cilantro","cilantro"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"","veg","protein","pepino","cucumber","en medias lunas","in half-moons"],
    [0.5,"","onion","aromatic","cebolla morada","red onion","en tiras finas","thinly sliced"],
    [1,"","avocado","garnish","aguacate","avocado","en rebanadas","sliced"]],
 es:{n:"Aguachile verde", b:"Camarón crudo curado en limón con serrano y cilantro licuados. Frío, ácido y muy picante: la comida de playa de Sinaloa.",
  st:["Licúa el jugo de limón con los serranos, la mitad del cilantro y la sal.",
      "Extiende los camarones en un plato hondo, cúbrelos con la mezcla y refrigera 15 minutos, hasta que estén opacos por fuera.",
      "Añade el pepino y la cebolla. Mezcla.",
      "Sirve de inmediato con aguacate y el resto del cilantro."],
  tp:["El limón no cuece como el fuego: usa camarón muy fresco o que se congeló antes. En embarazo o con defensas bajas, cuécelo 2 minutos en agua hirviendo y enfría antes.",
      "Más de 30 minutos en el limón y el camarón queda chicloso."],
  v:"aguachile verde receta"},
 en:{n:"Green Aguachile", b:"Raw shrimp cured in lime with blended serrano and cilantro. Cold, sharp and very hot: beach food from Sinaloa.",
  st:["Blend the lime juice with the serranos, half the cilantro and the salt.",
      "Spread the shrimp in a shallow dish, cover with the mixture and chill 15 minutes, until opaque outside.",
      "Add the cucumber and onion. Toss.",
      "Serve right away with avocado and the rest of the cilantro."],
  tp:["Lime does not cook like heat does: use very fresh or previously frozen shrimp. If pregnant or immunocompromised, boil the shrimp 2 minutes and chill first.",
      "More than 30 minutes in lime and the shrimp turns rubbery."],
  v:"aguachile recipe"}},

{id:"coctel-de-camaron", c:"Mexico", r:"latin-america", m:"starter", t:30, s:4,
 i:[[500,"g","shrimp","protein","camarones medianos","medium shrimp","pelados","peeled"],
    [1,"l","water","liquid","agua","water"],
    [1,"tsp","salt","salt","sal","salt"],
    [150,"ml","ketchup","sauce","catsup","ketchup"],
    [3,"","citrus","acid","limones","limes","en jugo","juiced"],
    [1,"tsp","hotsauce","aromatic","salsa picante","hot sauce"],
    [2,"","tomato","protein","jitomates","tomatoes","en cubos","diced"],
    [0.5,"","onion","aromatic","cebolla blanca","white onion","picada","chopped"],
    [1,"","veg","protein","pepino","cucumber","en cubos","diced"],
    [1,"handful","herb","garnish","cilantro","cilantro","picado","chopped"],
    [1,"","avocado","garnish","aguacate","avocado","en cubos","diced"],
    [1,"handful","tortillachips","serve","totopos","tortilla chips"]],
 es:{n:"Cóctel de camarón", b:"Camarón en su propia agua de cocción fría con catsup, limón y verduras picadas. Se sirve en copa, con totopos y salsa picante al gusto.",
  st:["Hierve el agua con la sal. Añade los camarones y apaga el fuego. Déjalos 3 minutos, hasta que estén rosados.",
      "Sácalos y enfría el agua de cocción. Guarda 250 ml.",
      "Mezcla el agua de cocción fría con la catsup, el limón y la salsa picante.",
      "Añade los camarones, el jitomate, la cebolla, el pepino y el cilantro. Refrigera 20 minutos.",
      "Sirve en vasos con el aguacate encima y totopos al lado."],
  tp:["Apagar el fuego y dejarlos en el agua caliente los mantiene jugosos.",
      "El agua de cocción da el sabor a mar; no la cambies por agua simple."],
  v:"coctel de camaron mexicano receta"},
 en:{n:"Mexican Shrimp Cocktail", b:"Shrimp in their own chilled cooking water with ketchup, lime and chopped vegetables. Served in a glass with tortilla chips and hot sauce to taste.",
  st:["Boil the water with the salt. Add the shrimp and turn off the heat. Leave them 3 minutes, until pink.",
      "Lift them out and chill the cooking water. Keep 250 ml.",
      "Mix the cold cooking water with the ketchup, lime and hot sauce.",
      "Add the shrimp, tomato, onion, cucumber and cilantro. Chill 20 minutes.",
      "Serve in glasses with avocado on top and chips on the side."],
  tp:["Turning off the heat and leaving them in the hot water keeps them juicy.",
      "The cooking water carries the taste of the sea; don't swap it for plain water."],
  v:"mexican shrimp cocktail recipe"}},

{id:"nopales", c:"Mexico", r:"latin-america", m:"side", t:35, s:4,
 i:[[500,"g","veg","protein","nopales limpios","cleaned cactus paddles","en tiras","cut in strips"],
    [1.5,"tsp","salt","salt","sal","salt"],
    [2,"","tomato","protein","jitomates","tomatoes","en cubos","diced"],
    [0.5,"","onion","aromatic","cebolla blanca","white onion","picada","chopped"],
    [1,"","chilli","aromatic","chile serrano","serrano chile","picado","chopped"],
    [1,"handful","herb","aromatic","cilantro","cilantro","picado","chopped"],
    [0.5,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [2,"","citrus","acid","limones","limes","en jugo","juiced"],
    [80,"g","queso","garnish","queso fresco","queso fresco","desmoronado","crumbled"]],
 es:{n:"Ensalada de nopales", b:"Nopales cocidos sin baba con jitomate, cebolla, cilantro y queso fresco. Fresca, ácida y lista para taco o guarnición.",
  st:["Pon los nopales en un sartén caliente sin aceite con 1 cucharadita de sal. Cuécelos a fuego medio 15 minutos, moviendo, hasta que suelten la baba y esta se seque.",
      "Pásalos a un colador, enjuaga con agua fría y escurre bien.",
      "Mezcla con el jitomate, la cebolla, el chile, el cilantro, el orégano, el limón y el resto de la sal.",
      "Sirve con el queso encima."],
  tp:["Cocerlos en sartén seco en vez de hervirlos deja menos baba y más sabor.",
      "Aguanta 2 días en el refrigerador sin el queso."],
  v:"ensalada de nopales receta"},
 en:{n:"Cactus Paddle Salad", b:"Nopales cooked until no longer slimy, with tomato, onion, cilantro and queso fresco. Fresh and sharp, for tacos or on the side.",
  st:["Put the nopales in a hot dry pan with 1 teaspoon of the salt. Cook over medium heat for 15 minutes, stirring, until they release their slime and it dries up.",
      "Tip them into a sieve, rinse with cold water and drain well.",
      "Mix with the tomato, onion, chile, cilantro, oregano, lime and the rest of the salt.",
      "Serve with the queso fresco on top."],
  tp:["Dry-pan cooking instead of boiling leaves less slime and more flavour.",
      "Keeps 2 days in the fridge without the cheese."],
  v:"nopales salad recipe"}},

{id:"tacos-de-papa", c:"Mexico", r:"latin-america", m:"main", t:50, s:4,
 i:[[800,"g","potato","protein","papas blancas","white potatoes","peladas, en trozos","peeled, in chunks"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"","chipotle","aromatic","chile chipotle en adobo","chipotle in adobo","picado, opcional","chopped, optional"],
    [16,"","corntortilla","structure","tortillas de maíz","corn tortillas"],
    [120,"ml","oil","fat","aceite","oil","para freír","for frying"],
    [0.25,"head","veg","garnish","col o lechuga","cabbage or lettuce","rebanada fina","finely shredded"],
    [120,"ml","crema","garnish","crema mexicana","Mexican crema"],
    [80,"g","queso","garnish","queso fresco","queso fresco","desmoronado","crumbled"],
    [250,"ml","tomatillo","sauce","salsa verde","green salsa"]],
 es:{n:"Tacos dorados de papa", b:"Tortillas rellenas de puré de papa, fritas hasta crujir y cubiertas de col, crema, queso y salsa verde. Baratos y de los más queridos.",
  st:["Hierve las papas en agua con sal 20 minutos, hasta que estén blandas. Escurre y machaca con el chipotle.",
      "Calienta las tortillas para que se doblen sin romperse.",
      "Pon 2 cucharadas de papa en cada tortilla, enróllala y ciérrala con un palillo.",
      "Calienta el aceite en un sartén a fuego medio. Fríe los tacos 3 minutos por lado, hasta que estén dorados. Escurre en papel.",
      "Sirve con la col, la crema, el queso y la salsa."],
  tp:["Fríelos con la costura hacia abajo primero: así se sellan y puedes quitar el palillo.",
      "La salsa verde puede ser la de tomatillo cocido de los chilaquiles."],
  v:"tacos dorados de papa receta"},
 en:{n:"Crispy Potato Tacos", b:"Tortillas filled with mashed potato, fried until crisp and topped with cabbage, crema, cheese and green salsa. Cheap and much loved.",
  st:["Boil the potatoes in salted water for 20 minutes, until soft. Drain and mash with the chipotle.",
      "Warm the tortillas so they fold without cracking.",
      "Put 2 tablespoons of potato on each tortilla, roll it up and pin it with a toothpick.",
      "Heat the oil in a pan over medium heat. Fry the tacos 3 minutes per side, until golden. Drain on paper.",
      "Serve with the cabbage, crema, cheese and salsa."],
  tp:["Fry them seam-side down first: they seal shut and you can pull the toothpick.",
      "The green salsa can be the cooked tomatillo one from the chilaquiles."],
  v:"tacos dorados de papa recipe"}},

{id:"huevos-a-la-mexicana", c:"Mexico", r:"latin-america", m:"breakfast", t:15, s:2,
 i:[[4,"","egg","protein","huevos","eggs"],
    [1,"","tomato","aromatic","jitomate","tomato","picado","chopped"],
    [0.25,"","onion","aromatic","cebolla blanca","white onion","picada","chopped"],
    [1,"","chilli","aromatic","chile serrano","serrano chile","picado","chopped"],
    [1,"tbsp","oil","fat","aceite","oil"],
    [0.5,"tsp","salt","salt","sal","salt"],
    [6,"","corntortilla","serve","tortillas de maíz","corn tortillas","calientes","warm"],
    [250,"g","legume","serve","frijoles refritos","refried beans"]],
 es:{n:"Huevos a la mexicana", b:"Huevos revueltos con jitomate, cebolla y chile: los colores de la bandera en el desayuno.",
  st:["Calienta el aceite y sofríe la cebolla y el chile 2 minutos.",
      "Añade el jitomate y cuece 3 minutos, hasta que suelte su jugo y se seque un poco.",
      "Bate los huevos con la sal, viértelos y mueve a fuego medio-bajo hasta que cuajen pero sigan brillantes.",
      "Sirve con tortillas y frijoles."],
  tp:["Cocer el jitomate antes evita que los huevos queden aguados.",
      "Apaga el fuego un momento antes de que se vean listos; el calor del sartén los termina."],
  v:"huevos a la mexicana receta"},
 en:{n:"Mexican-Style Scrambled Eggs", b:"Eggs scrambled with tomato, onion and chile: the colours of the flag at breakfast.",
  st:["Heat the oil and cook the onion and chile for 2 minutes.",
      "Add the tomato and cook 3 minutes, until it releases its juice and dries a little.",
      "Beat the eggs with the salt, pour them in and stir over medium-low heat until set but still glossy.",
      "Serve with tortillas and beans."],
  tp:["Cooking the tomato first keeps the eggs from turning watery.",
      "Turn off the heat just before they look done; the pan finishes them."],
  v:"huevos a la mexicana recipe"}},

{id:"sopa-de-lima", c:"Mexico", r:"latin-america", m:"soup", t:75, s:6,
 i:[[2,"thigh","chicken","protein","muslos de pollo con hueso","bone-in chicken thighs"],
    [1,"","chicken","protein","pechuga de pollo con hueso","bone-in chicken breast"],
    [2.5,"l","water","liquid","agua","water"],
    [1,"","onion","aromatic","cebolla blanca","white onion","en tiras","sliced"],
    [4,"clove","garlic","aromatic","ajo","garlic"],
    [1,"","bellpepper","aromatic","pimiento verde","green bell pepper","en tiras","sliced"],
    [2,"","tomato","aromatic","jitomates","tomatoes","picados","chopped"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [4,"","spice","aromatic","pimientas gordas","allspice berries"],
    [2,"","spice","aromatic","clavos de olor","cloves"],
    [2,"tsp","salt","salt","sal","salt"],
    [3,"","citrus","acid","limas yucatecas (o limones)","Yucatán sweet limes (or limes)","2 en jugo, 1 en rodajas","2 juiced, 1 sliced"],
    [6,"","corntortilla","crunch","tortillas de maíz","corn tortillas","en tiras","in strips"],
    [120,"ml","oil","fat","aceite","oil","para freír","for frying"],
    [1,"handful","herb","garnish","cilantro","cilantro"]],
 es:{n:"Sopa de lima", b:"El caldo de pollo de Yucatán perfumado con lima, pimienta gorda y clavo, con tiras de tortilla frita encima.",
  st:["Pon el pollo, el agua, la mitad de la cebolla, 2 dientes de ajo, la pimienta gorda, el clavo y la sal en una olla. Cuece 40 minutos a fuego bajo.",
      "Saca el pollo, deshébralo y cuela el líquido de la olla.",
      "En otra olla con 1 cucharada de aceite, sofríe el resto de la cebolla, el ajo picado y el pimiento 5 minutos. Añade el jitomate y el orégano, 5 minutos más.",
      "Vierte el líquido colado y hierve 10 minutos. Añade el pollo y el jugo de lima; apaga el fuego enseguida.",
      "Fríe las tiras de tortilla en el aceite hasta que estén doradas y escurre.",
      "Sirve con rodajas de lima, tiras de tortilla y cilantro."],
  tp:["El jugo de lima va al final y sin hervir: hervido se amarga.",
      "Echa las tiras de tortilla al servir, no antes, para que crujan."],
  v:"sopa de lima yucateca receta"},
 en:{n:"Yucatán Lime Soup", b:"Yucatán's chicken soup scented with sweet lime, allspice and clove, topped with crisp tortilla strips.",
  st:["Put the chicken, water, half the onion, 2 garlic cloves, allspice, cloves and salt in a pot. Simmer 40 minutes on low.",
      "Lift out the chicken, shred it and strain the cooking liquid.",
      "In another pot with 1 tablespoon of the oil, cook the rest of the onion, the chopped garlic and the bell pepper for 5 minutes. Add the tomato and oregano, 5 minutes more.",
      "Pour in the strained liquid and boil 10 minutes. Add the chicken and lime juice; turn off the heat right away.",
      "Fry the tortilla strips in the oil until golden and drain.",
      "Serve with lime slices, tortilla strips and cilantro."],
  tp:["The lime juice goes in at the end and is never boiled: boiled, it turns bitter.",
      "Add the tortilla strips at the table, not before, so they stay crisp."],
  v:"sopa de lima recipe"}}
];
