module.exports = [
{id:"caldo-de-albondigas", c:"Mexico", r:"latin-america", m:"soup", t:60, s:6,
 i:[[500,"g","beef","protein","carne molida de res","minced beef"],
    [50,"g","rice","binder","arroz crudo","uncooked rice"],
    [1,"","egg","binder","huevo","egg"],
    [1,"sprig","herb","aromatic","hierbabuena","mint","picada","chopped"],
    [1.5,"tsp","salt","salt","sal","salt"],
    [3,"","tomato","liquid","jitomates","tomatoes"],
    [0.5,"","onion","aromatic","cebolla","onion"],
    [1,"clove","garlic","aromatic","ajo","garlic"],
    [1,"","chipotleadobo","aromatic","chile chipotle adobado","chipotle in adobo"],
    [1,"tbsp","oil","fat","aceite","oil"],
    [1.5,"l","water","liquid","agua","water"],
    [2,"","veg","structure","zanahorias","carrots","en rodajas","sliced"],
    [2,"","veg","structure","calabacitas","courgettes","en cubos","cubed"]],
 es:{n:"Caldo de albóndigas", b:"Albóndigas con arroz y hierbabuena en caldo de jitomate con verduras. Comida de casa mexicana.",
  st:["Mezcla la carne, el arroz, el huevo, la hierbabuena y 1 cucharadita de sal. Forma 20 albóndigas.",
      "Licúa los jitomates, la cebolla, el ajo y el chipotle.",
      "Fríe la salsa en el aceite 5 minutos. Añade el agua y el resto de la sal y hierve.",
      "Añade las albóndigas y la zanahoria y cuece 25 minutos a fuego suave.",
      "Añade la calabacita y cuece 8 minutos más."],
  tp:["El arroz crudo se cuece dentro de la albóndiga y la hace esponjosa.",
      "No remuevas los primeros minutos para que las albóndigas no se rompan."],
  v:"caldo de albóndigas"},
 en:{n:"Caldo de Albóndigas (Mexican Meatball Soup)", b:"Meatballs with rice and mint in a tomato broth with vegetables. Mexican home cooking.",
  st:["Mix the beef, rice, egg, mint and 1 teaspoon of salt. Shape 20 meatballs.",
      "Blend the tomatoes, onion, garlic and chipotle.",
      "Fry the sauce in the oil for 5 minutes. Add the water and remaining salt and bring to the boil.",
      "Add the meatballs and carrot and simmer 25 minutes.",
      "Add the courgette and cook 8 minutes more."],
  tp:["The raw rice cooks inside the meatball and makes it tender.",
      "Don't stir for the first few minutes so the meatballs don't break."],
  v:"mexican meatball soup"}},

{id:"carne-en-su-jugo", c:"Mexico", r:"latin-america", m:"soup", t:60, s:4,
 i:[[150,"g","bacon","protein","tocino","bacon","picado","chopped"],
    [600,"g","beef","protein","bistec de res","beef steak","en trocitos","in small pieces"],
    [500,"g","tomatillo","sauce","tomates verdes","tomatillos"],
    [2,"","chilli","sauce","chiles serranos","serrano chillies"],
    [0.5,"","onion","aromatic","cebolla","onion"],
    [2,"clove","garlic","aromatic","ajo","garlic"],
    [1,"handful","herb","aromatic","cilantro","coriander"],
    [750,"ml","water","liquid","agua","water"],
    [400,"g","legume","structure","frijoles bayos cocidos","cooked pinto beans"],
    [1.5,"tsp","salt","salt","sal","salt"],
    [4,"","veg","garnish","rábanos","radishes","en rodajas","sliced"],
    [0.5,"","onion","garnish","cebolla (para servir)","onion (to serve)","picada","chopped"],
    [2,"","citrus","acid","limones","limes"]],
 es:{n:"Carne en su jugo", b:"Trocitos de res en caldo de tomate verde con tocino y frijoles. Especialidad de Guadalajara.",
  st:["Fríe el tocino 5 minutos, hasta que esté crujiente. Sácalo.",
      "Dora la carne en la grasa del tocino 5 minutos.",
      "Hierve los tomates verdes y los chiles 8 minutos. Lícualos con la cebolla, el ajo, el cilantro y el agua.",
      "Añade el caldo a la carne con la sal y cuece 20 minutos.",
      "Sirve con los frijoles, el tocino, el rábano, la cebolla y el limón."],
  tp:["Los frijoles se sirven en el plato, no se cuecen con el caldo.",
      "Pica la carne muy fina para que quede tierna."],
  v:"carne en su jugo tapatía"},
 en:{n:"Carne en su Jugo (Guadalajara Beef in Broth)", b:"Small pieces of beef in a tomatillo broth with bacon and beans. A Guadalajara speciality.",
  st:["Fry the bacon 5 minutes, until crisp. Remove.",
      "Brown the beef in the bacon fat for 5 minutes.",
      "Boil the tomatillos and chillies for 8 minutes. Blend with the onion, garlic, coriander and water.",
      "Add the broth to the beef with the salt and simmer 20 minutes.",
      "Serve with the beans, bacon, radish, onion and lime."],
  tp:["The beans go in the bowl, not into the pot.",
      "Chop the beef very small so it's tender."],
  v:"mexican carne en su jugo"}},

{id:"arroz-blanco-mx", c:"Mexico", r:"latin-america", m:"side", t:35, s:6,
 i:[[400,"g","rice","structure","arroz de grano largo","long-grain rice"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [0.5,"","onion","aromatic","cebolla","onion","en trozo","in one piece"],
    [2,"clove","garlic","aromatic","ajo","garlic","enteros","whole"],
    [800,"ml","water","liquid","agua caliente","hot water"],
    [1,"","chilli","aromatic","chile serrano entero","whole serrano chilli"],
    [1,"sprig","herb","aromatic","cilantro","coriander"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Arroz blanco a la mexicana", b:"Arroz frito antes de cocerlo, suelto y perfumado con ajo y cilantro. Acompaña casi todo en México.",
  st:["Enjuaga el arroz hasta que el agua salga clara y escúrrelo bien.",
      "Fríelo en el aceite 5 minutos, removiendo, hasta que esté opaco.",
      "Añade la cebolla, el ajo, el agua, el chile, el cilantro y la sal.",
      "Cuece destapado hasta que el agua baje al nivel del arroz. Tapa y cuece 15 minutos a fuego bajo.",
      "Deja reposar 5 minutos y retira la cebolla, el ajo, el chile y el cilantro."],
  tp:["Freír el arroz lo deja suelto.",
      "No remuevas una vez que lo tapas."],
  v:"arroz blanco mexicano"},
 en:{n:"Mexican White Rice", b:"Rice fried before simmering, fluffy and scented with garlic and coriander. Goes with almost everything in Mexico.",
  st:["Rinse the rice until the water runs clear and drain well.",
      "Fry it in the oil for 5 minutes, stirring, until opaque.",
      "Add the onion, garlic, water, chilli, coriander and salt.",
      "Cook uncovered until the water drops to the rice level. Cover and cook 15 minutes on low.",
      "Rest 5 minutes and remove the onion, garlic, chilli and coriander."],
  tp:["Frying the rice keeps the grains separate.",
      "Don't stir once it's covered."],
  v:"mexican white rice"}},

{id:"frijoles-refritos", c:"Mexico", r:"latin-america", m:"side", t:20, s:6,
 i:[[3,"tbsp","lard","fat","manteca de cerdo","lard"],
    [0.5,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [750,"g","legume","structure","frijoles negros o bayos cocidos","cooked black or pinto beans","con un poco de su líquido","with a little of their liquid"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Frijoles refritos caseros", b:"Frijoles machacados y fritos en manteca con cebolla. La base de mil antojitos mexicanos.",
  st:["Sofríe la cebolla en la manteca 5 minutos, hasta que dore.",
      "Añade los frijoles con su líquido y la sal.",
      "Machaca con un machacador mientras cocinas 10 minutos, hasta que espesen y se despeguen de la sartén."],
  tp:["Para una versión sin cerdo, usa aceite en lugar de manteca.",
      "Añade más líquido si los quieres más cremosos."],
  v:"frijoles refritos caseros"},
 en:{n:"Homemade Refried Beans", b:"Beans mashed and fried in lard with onion. The base of a thousand Mexican snacks.",
  st:["Cook the onion in the lard for 5 minutes, until golden.",
      "Add the beans with their liquid and the salt.",
      "Mash with a masher as they cook for 10 minutes, until thick and pulling away from the pan."],
  tp:["For a pork-free version, use oil instead of lard.",
      "Add more liquid for creamier beans."],
  v:"homemade refried beans"}},

{id:"salsa-de-molcajete", c:"Mexico", r:"latin-america", m:"sauce", t:20, s:8,
 i:[[4,"","tomato","structure","jitomates","tomatoes"],
    [3,"","chilli","aromatic","chiles serranos","serrano chillies"],
    [2,"clove","garlic","aromatic","ajo","garlic","con piel","unpeeled"],
    [0.25,"","onion","aromatic","cebolla","onion"],
    [1,"tsp","salt","salt","sal gruesa","coarse salt"],
    [1,"handful","herb","aromatic","cilantro","coriander","picado","chopped"]],
 es:{n:"Salsa de molcajete", b:"Salsa roja de jitomate y chile asados, machacada en molcajete. Rústica y llena de sabor tostado.",
  st:["Asa los jitomates, los chiles, el ajo y la cebolla en un comal 10 minutos, hasta que tengan manchas negras.",
      "Pela el ajo.",
      "Machaca el ajo y los chiles con la sal en el molcajete.",
      "Añade la cebolla y los jitomates y machaca hasta tener una salsa gruesa.",
      "Termina con el cilantro."],
  tp:["Sin molcajete, pulsa en la licuadora unos segundos: debe quedar con textura.",
      "Se conserva 3 días en la nevera."],
  v:"salsa de molcajete"},
 en:{n:"Salsa de Molcajete (Charred Tomato Salsa)", b:"A red salsa of charred tomato and chilli, pounded in a stone mortar. Rustic and full of roasted flavour.",
  st:["Char the tomatoes, chillies, garlic and onion on a griddle for 10 minutes, until blackened in spots.",
      "Peel the garlic.",
      "Pound the garlic and chillies with the salt in the mortar.",
      "Add the onion and tomatoes and pound into a chunky salsa.",
      "Finish with the coriander."],
  tp:["No mortar? Pulse in a blender for a few seconds: keep it chunky.",
      "It keeps 3 days in the fridge."],
  v:"molcajete salsa"}},

{id:"ensalada-de-nopales", c:"Mexico", r:"latin-america", m:"side", t:30, s:4,
 i:[[500,"g","veg","structure","nopales","cactus paddles","limpios y en tiras","cleaned, in strips"],
    [1,"tsp","salt","salt","sal","salt"],
    [2,"","tomato","structure","jitomates","tomatoes","picados","chopped"],
    [0.5,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","chilli","aromatic","chile serrano","serrano chilli","picado","chopped"],
    [1,"handful","herb","aromatic","cilantro","coriander","picado","chopped"],
    [2,"","citrus","acid","limones","limes","exprimidos","juiced"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [80,"g","queso","garnish","queso fresco","queso fresco","desmoronado","crumbled"]],
 es:{n:"Ensalada de nopales", b:"Nopales tiernos con jitomate, cebolla, chile y queso fresco. Fresca y muy mexicana.",
  st:["Hierve los nopales con la sal 10 minutos. Escurre y enjuaga con agua fría para quitar la baba.",
      "Mezcla con el jitomate, la cebolla, el chile y el cilantro.",
      "Aliña con el limón y el orégano.",
      "Sirve con el queso por encima."],
  tp:["Enjuagarlos bien quita la textura babosa.",
      "Se conserva 1 día en la nevera sin el queso."],
  v:"ensalada de nopales"},
 en:{n:"Nopales Salad (Mexican Cactus Salad)", b:"Tender cactus paddles with tomato, onion, chilli and fresh cheese. Fresh and very Mexican.",
  st:["Boil the cactus with the salt for 10 minutes. Drain and rinse in cold water to remove the slime.",
      "Mix with the tomato, onion, chilli and coriander.",
      "Dress with the lime and oregano.",
      "Serve with the cheese on top."],
  tp:["Rinsing well removes the slimy texture.",
      "It keeps 1 day in the fridge without the cheese."],
  v:"mexican cactus salad"}},

{id:"paletas-de-fresa", c:"Mexico", r:"latin-america", m:"sweet", t:15, s:8,
 i:[[500,"g","fruit","structure","fresas","strawberries"],
    [100,"g","sugar","sweet","azúcar","sugar"],
    [250,"ml","water","liquid","agua","water"],
    [1,"","citrus","acid","limón","lime","exprimido","juiced"]],
 es:{n:"Paletas de fresa", b:"Paletas heladas de fresa natural, como las de las paleterías michoacanas.",
  st:["Calienta el agua con el azúcar hasta que se disuelva. Deja enfriar.",
      "Licúa las fresas con el almíbar y el limón. Deja algunos trozos si quieres.",
      "Llena moldes de paleta y pon los palitos.",
      "Congela 6 horas."],
  tp:["Pasa el molde por agua tibia unos segundos para desmoldar.",
      "Prueba antes de congelar: el frío apaga el dulzor."],
  v:"paletas de fresa caseras"},
 en:{n:"Strawberry Paletas (Mexican Ice Pops)", b:"Fresh strawberry ice pops, like those from Michoacán-style paleterías.",
  st:["Heat the water with the sugar until dissolved. Cool.",
      "Blend the strawberries with the syrup and lime. Leave some chunks if you like.",
      "Fill ice pop moulds and insert the sticks.",
      "Freeze 6 hours."],
  tp:["Dip the mould in warm water for a few seconds to release.",
      "Taste before freezing: cold dulls sweetness."],
  v:"mexican strawberry paletas"}},

{id:"enchiladas-mineras", c:"Mexico", r:"latin-america", m:"main", t:60, s:4,
 i:[[6,"","ancho","sauce","chiles guajillo","guajillo chillies","sin semillas","seeded"],
    [1,"clove","garlic","sauce","ajo","garlic"],
    [1,"tsp","salt","salt","sal","salt"],
    [12,"","corntortilla","structure","tortillas de maíz","corn tortillas"],
    [150,"ml","oil","fat","aceite","oil"],
    [200,"g","queso","enrich","queso ranchero","queso fresco","desmoronado","crumbled"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [3,"","potato","garnish","papas","potatoes","en cubos, cocidas","cubed, boiled"],
    [3,"","veg","garnish","zanahorias","carrots","en cubos, cocidas","cubed, boiled"],
    [2,"","chicken","protein","piernas de pollo cocidas","cooked chicken legs"],
    [4,"","pickledpepper","garnish","chiles jalapeños en escabeche","pickled jalapeños"]],
 es:{n:"Enchiladas mineras", b:"Enchiladas de guajillo rellenas de queso, con papas y zanahorias doradas y pollo. Plato de Guanajuato.",
  st:["Remoja los chiles en agua caliente 10 minutos y lícualos con el ajo, la sal y 250 ml de agua. Cuela.",
      "Pasa cada tortilla por la salsa y fríela en el aceite 20 segundos por lado.",
      "Rellena con queso y cebolla y enrolla.",
      "Dora la papa y la zanahoria en el mismo aceite 6 minutos. Dora el pollo 4 minutos.",
      "Sirve las enchiladas con la papa, la zanahoria, el pollo y los jalapeños."],
  tp:["No dejes la tortilla mucho en la salsa o se rompe.",
      "Los jalapeños en escabeche llevan vinagre."],
  v:"enchiladas mineras guanajuatenses"},
 en:{n:"Enchiladas Mineras (Miners' Enchiladas)", b:"Guajillo enchiladas filled with cheese, with golden potato, carrot and chicken. A Guanajuato dish.",
  st:["Soak the chillies in hot water for 10 minutes and blend with the garlic, salt and 250 ml of water. Strain.",
      "Dip each tortilla in the sauce and fry in the oil for 20 seconds per side.",
      "Fill with cheese and onion and roll.",
      "Brown the potato and carrot in the same oil for 6 minutes. Brown the chicken 4 minutes.",
      "Serve the enchiladas with the potato, carrot, chicken and jalapeños."],
  tp:["Don't leave the tortilla in the sauce too long or it tears.",
      "Pickled jalapeños contain vinegar."],
  v:"mexican enchiladas mineras"}},

{id:"tacos-arabes", c:"Mexico", r:"latin-america", m:"main", t:40, s:4,
 i:[[700,"g","pork","protein","pierna de cerdo","pork leg","en filetes finos","in thin slices"],
    [1,"","onion","aromatic","cebolla","onion","rallada","grated"],
    [2,"","citrus","acid","limones","limes","exprimidos","juiced"],
    [1,"","citrus","acid","naranja","orange","exprimida","juiced"],
    [3,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1.5,"tsp","salt","salt","sal","salt"],
    [8,"","flatbread","structure","panes árabes (pita)","pita breads"],
    [3,"","chipotleadobo","sauce","chiles chipotles adobados","chipotles in adobo"],
    [2,"","citrus","acid","limones (para la salsa)","limes (for the salsa)"]],
 es:{n:"Tacos árabes", b:"Cerdo marinado en cítricos y especias, envuelto en pan árabe con salsa de chipotle. Herencia libanesa de Puebla.",
  st:["Marina el cerdo con la cebolla, los jugos, el ajo, el comino, el orégano, el aceite y la sal 4 horas.",
      "Ásalo en una plancha muy caliente 3 minutos por lado. Córtalo en tiras.",
      "Licúa los chipotles con el jugo de los limones de la salsa y un poco de agua.",
      "Calienta los panes y rellénalos con la carne. Sirve con la salsa."],
  tp:["Marinado toda la noche queda más jugoso.",
      "El pan árabe se calienta en el comal para que se ablande."],
  v:"tacos árabes poblanos"},
 en:{n:"Tacos Árabes (Puebla Pork in Pita)", b:"Pork marinated in citrus and spices, wrapped in pita with chipotle sauce. Lebanese heritage from Puebla.",
  st:["Marinate the pork with the onion, juices, garlic, cumin, oregano, oil and salt for 4 hours.",
      "Cook on a very hot griddle for 3 minutes per side. Cut into strips.",
      "Blend the chipotles with the salsa lime juice and a little water.",
      "Warm the pitas and fill with the pork. Serve with the salsa."],
  tp:["Marinated overnight it's juicier.",
      "Warm the pita on the griddle so it softens."],
  v:"tacos arabes puebla"}},

{id:"pescado-empapelado", c:"Mexico", r:"latin-america", m:"main", t:35, s:4,
 i:[[4,"fillet","whitefish","protein","filetes de pescado blanco","white fish fillets"],
    [1,"tsp","salt","salt","sal","salt"],
    [2,"","tomato","aromatic","jitomates","tomatoes","en rodajas","sliced"],
    [0.5,"","onion","aromatic","cebolla","onion","en rodajas","sliced"],
    [2,"","chilli","aromatic","chiles jalapeños","jalapeño chillies","en rajas","in strips"],
    [4,"sprig","herb","aromatic","epazote","epazote"],
    [40,"g","butter","fat","mantequilla","butter"],
    [2,"","citrus","acid","limones","limes"]],
 es:{n:"Pescado empapelado", b:"Filetes de pescado cocidos en papel con jitomate, chile y epazote. Ligero y jugoso, de la costa de Veracruz.",
  st:["Pon cada filete sobre un cuadrado de papel de aluminio. Sala.",
      "Cubre con el jitomate, la cebolla, el chile, el epazote y un trozo de mantequilla.",
      "Cierra bien los paquetes.",
      "Hornea a 200 °C 18 minutos.",
      "Abre con cuidado y sirve con limón."],
  tp:["Cierra los paquetes herméticamente para que el pescado se cueza al vapor.",
      "Cuidado al abrir: sale vapor caliente."],
  v:"pescado empapelado"},
 en:{n:"Pescado Empapelado (Fish Baked in Parcels)", b:"Fish fillets baked in parcels with tomato, chilli and epazote. Light and juicy, from the Veracruz coast.",
  st:["Put each fillet on a square of foil. Salt.",
      "Top with the tomato, onion, chilli, epazote and a knob of butter.",
      "Seal the parcels well.",
      "Bake at 200 °C for 18 minutes.",
      "Open carefully and serve with lime."],
  tp:["Seal the parcels tightly so the fish steams.",
      "Careful when opening: hot steam escapes."],
  v:"mexican fish in foil"}}
];
