module.exports = [
{id:"sikil-pak", c:"Mexico", r:"latin-america", m:"sauce", t:30, s:6,
 i:[[200,"g","seeds","structure","pepitas de calabaza peladas","hulled pumpkin seeds"],
    [2,"","tomato","liquid","jitomates","tomatoes"],
    [1,"","chilli","aromatic","chile habanero","habanero chilli"],
    [1,"handful","herb","aromatic","cilantro","coriander"],
    [2,"","scallion","aromatic","cebollines","spring onions"],
    [1,"","citrus","acid","naranja agria o limón","sour orange or lime","exprimido","juiced"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Sikil pak", b:"Dip maya de pepita de calabaza tostada con jitomate asado y habanero. Botana de Yucatán.",
  st:["Tuesta las pepitas en una sartén seca 5 minutos, hasta que se inflen y doren.",
      "Asa los jitomates y el chile en un comal 8 minutos.",
      "Muele las pepitas hasta que estén finas.",
      "Licúa las pepitas con los jitomates, el chile, el cilantro, los cebollines, el jugo y la sal hasta tener una pasta.",
      "Sirve a temperatura ambiente."],
  tp:["Usa medio habanero si no te gusta muy picante.",
      "Añade agua si queda demasiado espeso."],
  v:"sikil pak yucateco"},
 en:{n:"Sikil Pak (Mayan Pumpkin Seed Dip)", b:"A Mayan dip of toasted pumpkin seeds with charred tomato and habanero. A Yucatán snack.",
  st:["Toast the seeds in a dry pan for 5 minutes, until puffed and golden.",
      "Char the tomatoes and chilli on a griddle for 8 minutes.",
      "Grind the seeds finely.",
      "Blend the seeds with the tomatoes, chilli, coriander, spring onions, juice and salt into a paste.",
      "Serve at room temperature."],
  tp:["Use half a habanero for milder heat.",
      "Add water if it's too thick."],
  v:"sikil pak pumpkin seed dip"}},

{id:"poc-chuc", c:"Mexico", r:"latin-america", m:"main", t:60, s:4,
 i:[[800,"g","pork","protein","filetes finos de pierna de cerdo","thin pork leg steaks"],
    [4,"","citrus","acid","naranjas agrias (o 3 naranjas y 1 limón)","sour oranges (or 3 oranges and 1 lime)","exprimidas","juiced"],
    [3,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [2,"tsp","salt","salt","sal","salt"],
    [1,"","onion","garnish","cebolla morada","red onion","en rodajas","sliced"],
    [3,"","tomato","garnish","jitomates","tomatoes"],
    [1,"handful","herb","garnish","cilantro","coriander","picado","chopped"]],
 es:{n:"Poc chuc", b:"Cerdo marinado en naranja agria y asado a la brasa, con cebolla y jitomate asados. Clásico de Yucatán.",
  st:["Marina el cerdo con la mitad del jugo, el ajo y la sal 30 minutos.",
      "Asa el cerdo a la parrilla muy caliente 3 minutos por lado.",
      "Asa la cebolla y los jitomates hasta que se tuesten.",
      "Pica los jitomates y mézclalos con la cebolla, el cilantro y el resto del jugo.",
      "Corta el cerdo en tiras y sirve con la salsa."],
  tp:["No marines más de 1 hora: el cítrico cuece la carne.",
      "Una sartén de hierro bien caliente sustituye la parrilla."],
  v:"poc chuc yucateco"},
 en:{n:"Poc Chuc (Yucatán Grilled Pork)", b:"Pork marinated in sour orange and grilled, with charred onion and tomato. A Yucatán classic.",
  st:["Marinate the pork with half the juice, the garlic and salt for 30 minutes.",
      "Grill the pork over very high heat for 3 minutes per side.",
      "Grill the onion and tomatoes until charred.",
      "Chop the tomatoes and mix with the onion, coriander and the rest of the juice.",
      "Slice the pork and serve with the salsa."],
  tp:["Don't marinate over 1 hour: the citrus cooks the meat.",
      "A very hot cast-iron pan stands in for the grill."],
  v:"poc chuc grilled pork"}},

{id:"frijol-con-puerco", c:"Mexico", r:"latin-america", m:"main", t:150, s:6,
 i:[[400,"g","legume","structure","frijoles negros secos","dried black beans"],
    [2.5,"l","water","liquid","agua","water"],
    [1,"kg","pork","protein","carne de cerdo (espinazo y pierna)","pork (backbone and leg)","en trozos","in pieces"],
    [0.5,"","onion","aromatic","cebolla","onion"],
    [1,"sprig","herb","aromatic","epazote","epazote"],
    [2,"tsp","salt","salt","sal","salt"],
    [3,"","tomato","garnish","jitomates","tomatoes","asados y picados","charred and chopped"],
    [4,"","veg","garnish","rábanos","radishes","picados","chopped"],
    [1,"handful","herb","garnish","cilantro","coriander","picado","chopped"],
    [1,"","chilli","garnish","chile habanero","habanero chilli","picado","chopped"],
    [3,"","citrus","acid","limones","limes"]],
 es:{n:"Frijol con puerco", b:"Frijoles negros cocidos con cerdo y epazote, servidos con salsa de jitomate y rábano. El plato de los lunes en Yucatán.",
  st:["Remoja los frijoles 8 horas y escúrrelos.",
      "Cuécelos en el agua con la cebolla 60 minutos.",
      "Añade el cerdo, el epazote y la sal y cuece 60 minutos más.",
      "Mezcla el jitomate, el rábano, el cilantro, el chile y el jugo de un limón.",
      "Sirve el frijol con la carne y la salsa al lado, y limón."],
  tp:["Tradicionalmente se sirve la carne aparte del caldo de frijol.",
      "Sirve el habanero aparte para quien lo quiera."],
  v:"frijol con puerco yucateco"},
 en:{n:"Frijol con Puerco (Yucatán Pork and Black Beans)", b:"Black beans simmered with pork and epazote, served with a tomato and radish salsa. Monday's dish in Yucatán.",
  st:["Soak the beans 8 hours and drain.",
      "Simmer them in the water with the onion for 60 minutes.",
      "Add the pork, epazote and salt and cook 60 minutes more.",
      "Mix the tomato, radish, coriander, chilli and the juice of one lime.",
      "Serve the beans with the pork, the salsa on the side, and lime."],
  tp:["Traditionally the meat is served separately from the bean broth.",
      "Serve the habanero on the side for those who want it."],
  v:"yucatan frijol con puerco"}},

{id:"xnipec", c:"Mexico", r:"latin-america", m:"sauce", t:15, s:8,
 i:[[1,"","onion","structure","cebolla morada","red onion","picada","chopped"],
    [2,"","tomato","structure","jitomates","tomatoes","sin semillas, picados","seeded, chopped"],
    [2,"","chilli","aromatic","chiles habaneros","habanero chillies","picados finos","finely chopped"],
    [1,"handful","herb","aromatic","cilantro","coriander","picado","chopped"],
    [3,"","citrus","acid","naranjas agrias (o 2 limones)","sour oranges (or 2 limes)","exprimidas","juiced"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Xnipec", b:"Salsa yucateca cruda de habanero, cebolla morada y naranja agria. Su nombre maya significa nariz de perro, por lo que hace sudar.",
  st:["Mezcla la cebolla, el jitomate, el chile y el cilantro.",
      "Añade el jugo y la sal.",
      "Deja reposar 10 minutos antes de servir."],
  tp:["Usa guantes al picar el habanero.",
      "Se conserva 2 días en la nevera."],
  v:"xnipec salsa yucateca"},
 en:{n:"Xnipec (Yucatán Habanero Salsa)", b:"A raw Yucatán salsa of habanero, red onion and sour orange. Its Mayan name means dog's nose, for the sweat it brings on.",
  st:["Mix the onion, tomato, chilli and coriander.",
      "Add the juice and salt.",
      "Rest 10 minutes before serving."],
  tp:["Wear gloves when chopping the habanero.",
      "It keeps 2 days in the fridge."],
  v:"xnipec habanero salsa"}},

{id:"memelas", c:"Mexico", r:"latin-america", m:"main", t:40, s:4,
 i:[[500,"g","masa","structure","masa de maíz","fresh corn masa"],
    [1,"tsp","salt","salt","sal","salt"],
    [60,"g","lard","fat","asiento (manteca de cerdo)","pork lard"],
    [250,"g","legume","spread","frijoles negros cocidos","cooked black beans","machacados","mashed"],
    [4,"","tomato","sauce","jitomates","tomatoes"],
    [2,"","chilli","sauce","chiles de árbol","árbol chillies"],
    [1,"clove","garlic","sauce","ajo","garlic"],
    [100,"g","queso","garnish","quesillo o queso fresco","Oaxaca cheese or queso fresco","desmenuzado","shredded"]],
 es:{n:"Memelas", b:"Tortillas gruesas con bordes pellizcados, untadas con asiento, frijol, salsa y queso. Desayuno de mercado en Oaxaca.",
  st:["Amasa la masa con la sal. Forma 8 tortillas gruesas de 12 cm.",
      "Cuécelas en el comal 2 minutos por lado y pellizca el borde para formar un reborde.",
      "Asa los jitomates, los chiles y el ajo y lícualos con sal.",
      "Unta cada memela con asiento y vuelve al comal 1 minuto.",
      "Cubre con frijol, salsa y queso."],
  tp:["Pellizca las memelas en caliente, con cuidado de no quemarte.",
      "El asiento es la manteca con restos de chicharrón: le da el sabor oaxaqueño."],
  v:"memelas oaxaqueñas"},
 en:{n:"Memelas (Oaxacan Masa Cakes)", b:"Thick tortillas with pinched edges, spread with lard, beans, salsa and cheese. A market breakfast in Oaxaca.",
  st:["Knead the masa with the salt. Shape 8 thick 12 cm tortillas.",
      "Cook on the griddle 2 minutes per side and pinch the edge into a rim.",
      "Char the tomatoes, chillies and garlic and blend with salt.",
      "Spread each memela with lard and return to the griddle for 1 minute.",
      "Top with beans, salsa and cheese."],
  tp:["Pinch them while hot, taking care not to burn yourself.",
      "Oaxacan asiento is lard with crackling bits: it gives the local flavour."],
  v:"oaxacan memelas"}},

{id:"chilaquiles-rojos", c:"Mexico", r:"latin-america", m:"breakfast", t:30, s:4,
 i:[[12,"","corntortilla","structure","tortillas de maíz del día anterior","day-old corn tortillas","en triángulos","cut in triangles"],
    [250,"ml","oil","fat","aceite","oil"],
    [4,"","tomato","sauce","jitomates","tomatoes"],
    [3,"","ancho","sauce","chiles guajillo","guajillo chillies","sin semillas","seeded"],
    [1,"clove","garlic","sauce","ajo","garlic"],
    [0.5,"","onion","sauce","cebolla","onion"],
    [250,"ml","water","liquid","agua","water"],
    [1,"tsp","salt","salt","sal","salt"],
    [120,"ml","crema","garnish","crema","Mexican crema"],
    [80,"g","queso","garnish","queso fresco","queso fresco","desmoronado","crumbled"],
    [0.5,"","onion","garnish","cebolla (para decorar)","onion (to garnish)","en aros","in rings"]],
 es:{n:"Chilaquiles rojos", b:"Totopos bañados en salsa roja de guajillo, con crema y queso. El desayuno mexicano por excelencia.",
  st:["Fríe los triángulos de tortilla en el aceite hasta que estén crujientes. Escurre.",
      "Hierve los jitomates y los chiles 8 minutos. Lícualos con el ajo, la cebolla, el agua y la sal.",
      "Fríe la salsa en 1 cucharada del aceite 5 minutos.",
      "Añade los totopos y mezcla 1 minuto.",
      "Sirve con crema, queso y cebolla."],
  tp:["Sírvelos en cuanto los mezcles si los quieres crujientes.",
      "Tortillas del día anterior se fríen mejor."],
  v:"chilaquiles rojos"},
 en:{n:"Chilaquiles Rojos", b:"Fried tortilla chips tossed in red guajillo sauce, with crema and cheese. The Mexican breakfast.",
  st:["Fry the tortilla triangles in the oil until crisp. Drain.",
      "Boil the tomatoes and chillies for 8 minutes. Blend with the garlic, onion, water and salt.",
      "Fry the sauce in 1 tablespoon of the oil for 5 minutes.",
      "Add the chips and toss 1 minute.",
      "Serve with crema, cheese and onion."],
  tp:["Serve straight after tossing if you like them crisp.",
      "Day-old tortillas fry better."],
  v:"red chilaquiles"}},

{id:"huevos-ahogados", c:"Mexico", r:"latin-america", m:"breakfast", t:30, s:4,
 i:[[4,"","tomato","sauce","jitomates","tomatoes"],
    [2,"","chilli","sauce","chiles serranos","serrano chillies"],
    [0.5,"","onion","aromatic","cebolla","onion"],
    [1,"clove","garlic","aromatic","ajo","garlic"],
    [1,"tbsp","oil","fat","aceite","oil"],
    [500,"ml","water","liquid","agua","water"],
    [1,"sprig","herb","aromatic","epazote","epazote"],
    [1,"tsp","salt","salt","sal","salt"],
    [8,"","egg","protein","huevos","eggs"]],
 es:{n:"Huevos ahogados", b:"Huevos escalfados en un caldillo picante de jitomate con epazote. Desayuno de casa mexicano.",
  st:["Licúa los jitomates, los chiles, la cebolla y el ajo.",
      "Fríe la salsa en el aceite 5 minutos. Añade el agua, el epazote y la sal y hierve 5 minutos.",
      "Baja el fuego y casca los huevos uno a uno en el caldillo.",
      "Tapa y cuece 5 minutos, hasta que las claras cuajen.",
      "Sirve en platos hondos con el caldillo."],
  tp:["El caldillo debe hervir suave, no a borbotones, para que los huevos no se rompan.",
      "Casca cada huevo en una taza antes de echarlo."],
  v:"huevos ahogados en caldillo"},
 en:{n:"Huevos Ahogados (Eggs Poached in Tomato Broth)", b:"Eggs poached in a spicy tomato broth with epazote. A Mexican home breakfast.",
  st:["Blend the tomatoes, chillies, onion and garlic.",
      "Fry the sauce in the oil for 5 minutes. Add the water, epazote and salt and boil 5 minutes.",
      "Lower the heat and crack the eggs one by one into the broth.",
      "Cover and cook 5 minutes, until the whites set.",
      "Serve in deep bowls with the broth."],
  tp:["Keep the broth at a gentle simmer so the eggs don't break.",
      "Crack each egg into a cup first."],
  v:"mexican eggs poached tomato broth"}},

{id:"molotes", c:"Mexico", r:"latin-america", m:"snack", t:60, s:16,
 i:[[500,"g","masa","structure","masa de maíz","fresh corn masa"],
    [1,"tsp","salt","salt","sal","salt"],
    [3,"","potato","structure","papas","potatoes"],
    [200,"g","chorizo","protein","chorizo mexicano","Mexican chorizo"],
    [750,"ml","oil","fat","aceite para freír","oil for frying"],
    [120,"ml","crema","garnish","crema","Mexican crema"],
    [2,"handful","veg","garnish","lechuga","lettuce","picada","shredded"]],
 es:{n:"Molotes", b:"Empanadas alargadas de masa de maíz rellenas de papa con chorizo, fritas. Antojito de Puebla y Oaxaca.",
  st:["Cuece la papa 20 minutos, pélala y hazla puré.",
      "Fríe el chorizo 5 minutos y mézclalo con la papa.",
      "Amasa la masa con la sal. Aplana porciones en óvalos finos entre dos plásticos.",
      "Rellena, dobla y cierra en forma de huso.",
      "Fríe a 180 °C 4 minutos, hasta que estén dorados. Sirve con crema y lechuga."],
  tp:["Si la masa se agrieta, añade un poco de agua.",
      "Sella bien las puntas para que no entre aceite."],
  v:"molotes de papa con chorizo"},
 en:{n:"Molotes (Fried Masa Turnovers)", b:"Spindle-shaped corn masa turnovers filled with potato and chorizo, fried. A street snack from Puebla and Oaxaca.",
  st:["Boil the potato 20 minutes, peel and mash.",
      "Fry the chorizo 5 minutes and mix with the potato.",
      "Knead the masa with the salt. Press portions into thin ovals between two sheets of plastic.",
      "Fill, fold and seal into a spindle shape.",
      "Fry at 180 °C for 4 minutes, until golden. Serve with crema and lettuce."],
  tp:["If the masa cracks, add a little water.",
      "Seal the tips well so oil doesn't get in."],
  v:"mexican molotes"}},

{id:"chileatole", c:"Mexico", r:"latin-america", m:"soup", t:40, s:6,
 i:[[4,"","corn","structure","elotes","corn cobs","desgranados","kernels cut off"],
    [1.5,"l","water","liquid","agua","water"],
    [100,"g","masa","thicken","masa de maíz","corn masa"],
    [3,"","chilli","aromatic","chiles serranos","serrano chillies"],
    [1,"bunch","herb","aromatic","epazote","epazote"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Chileatole verde", b:"Atole salado de elote espesado con masa, verde de chile y epazote. Se toma en el campo de Puebla y Tlaxcala.",
  st:["Cuece los granos de elote en el agua con la sal 15 minutos.",
      "Licúa los chiles y el epazote con 250 ml del caldo.",
      "Disuelve la masa en 250 ml del caldo.",
      "Añade ambas mezclas a la olla y cuece 10 minutos removiendo, hasta que espese.",
      "Sirve caliente."],
  tp:["Remueve sin parar al añadir la masa para evitar grumos.",
      "Añade más agua si lo quieres más ligero."],
  v:"chileatole verde de elote"},
 en:{n:"Chileatole Verde (Savoury Corn Atole)", b:"A savoury corn drink-soup thickened with masa, green with chilli and epazote. Enjoyed in the countryside of Puebla and Tlaxcala.",
  st:["Simmer the corn kernels in the water with the salt for 15 minutes.",
      "Blend the chillies and epazote with 250 ml of the broth.",
      "Dissolve the masa in 250 ml of the broth.",
      "Stir both into the pot and cook 10 minutes, stirring, until thick.",
      "Serve hot."],
  tp:["Stir constantly when adding the masa to avoid lumps.",
      "Add more water for a thinner version."],
  v:"mexican chileatole"}},

{id:"marquesitas", c:"Mexico", r:"latin-america", m:"sweet", t:30, s:8,
 i:[[150,"g","apflour","structure","harina de trigo","plain flour"],
    [2,"","egg","structure","huevos","eggs"],
    [250,"ml","milk","liquid","leche","milk"],
    [60,"g","sugar","sweet","azúcar","sugar"],
    [30,"g","butter","fat","mantequilla derretida","melted butter"],
    [1,"tsp","vanilla","aromatic","esencia de vainilla","vanilla extract"],
    [150,"g","cheese","enrich","queso de bola (Edam)","Edam cheese","rallado","grated"]],
 es:{n:"Marquesitas", b:"Crepas crujientes enrolladas con queso de bola rallado. Se venden en carritos en las plazas de Mérida.",
  st:["Bate la harina, los huevos, la leche, el azúcar, la mantequilla y la vainilla hasta tener una masa líquida.",
      "Vierte un cucharón en una sartén antiadherente caliente y extiende muy fino.",
      "Cocina 3 minutos a fuego medio, hasta que esté dorada y crujiente.",
      "Espolvorea queso por encima y enrolla como un tubo.",
      "Sirve de inmediato."],
  tp:["Deben quedar crujientes como un barquillo: cocina a fuego medio sin prisa.",
      "El contraste dulce y salado es la gracia."],
  v:"marquesitas yucatecas"},
 en:{n:"Marquesitas (Yucatán Crispy Cheese Crêpes)", b:"Crisp crêpes rolled around grated Edam cheese. Sold from carts in the squares of Mérida.",
  st:["Whisk the flour, eggs, milk, sugar, butter and vanilla into a runny batter.",
      "Pour a ladleful into a hot non-stick pan and spread very thin.",
      "Cook 3 minutes over medium heat, until golden and crisp.",
      "Sprinkle cheese over and roll into a tube.",
      "Serve at once."],
  tp:["They should be crisp like a wafer: cook over medium heat, unhurried.",
      "The sweet-salty contrast is the point."],
  v:"yucatan marquesitas"}}
];
