module.exports = [
{id:"caldo-de-camaron", c:"Mexico", r:"latin-america", m:"soup", t:50, s:4,
 i:[[500,"g","shrimp","protein","camarones con cabeza","head-on prawns"],
    [1.5,"l","water","liquid","agua","water"],
    [3,"","ancho","aromatic","chiles guajillo","guajillo chillies","sin semillas","seeded"],
    [2,"","tomato","liquid","jitomates","tomatoes"],
    [0.5,"","onion","aromatic","cebolla","onion"],
    [2,"clove","garlic","aromatic","ajo","garlic"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [2,"","veg","structure","zanahorias","carrots","en dados","diced"],
    [2,"","potato","structure","papas","potatoes","en dados","diced"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [2,"tsp","salt","salt","sal","salt"],
    [2,"","citrus","acid","limones","limes","en cuartos","quartered"]],
 es:{n:"Caldo de camarón", b:"Caldo rojo y picosito hecho con las cabezas del camarón. El caldo de las marisquerías mexicanas.",
  st:["Pela los camarones y hierve las cáscaras y cabezas en el agua 20 minutos. Cuela.",
      "Remoja los chiles en agua caliente 10 minutos y lícualos con el jitomate, la cebolla, el ajo y un poco de caldo.",
      "Fríe la salsa en el aceite 5 minutos.",
      "Añade el caldo, la zanahoria, la papa, el orégano y la sal. Cuece 15 minutos.",
      "Añade los camarones y cuece 3 minutos. Sirve con los limones."],
  tp:["No cuezas de más los camarones o quedan duros.",
      "Las cabezas dan casi todo el sabor: no las tires."],
  v:"caldo de camarón estilo marisquería"},
 en:{n:"Caldo de Camarón (Mexican Prawn Soup)", b:"A red, gently spicy broth made from the prawn heads. The soup of Mexican seafood joints.",
  st:["Peel the prawns and boil the shells and heads in the water for 20 minutes. Strain.",
      "Soak the chillies in hot water for 10 minutes and blend with the tomato, onion, garlic and a little broth.",
      "Fry the sauce in the oil for 5 minutes.",
      "Add the broth, carrot, potato, oregano and salt. Simmer 15 minutes.",
      "Add the prawns and cook 3 minutes. Serve with the limes."],
  tp:["Don't overcook the prawns or they turn tough.",
      "The heads carry most of the flavour: don't throw them out."],
  v:"mexican caldo de camaron"}},

{id:"arroz-a-la-tumbada", c:"Mexico", r:"latin-america", m:"main", t:50, s:4,
 i:[[3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"","bellpepper","aromatic","pimiento verde","green bell pepper","picado","chopped"],
    [3,"","tomato","liquid","jitomates","tomatoes","picados","chopped"],
    [300,"g","rice","structure","arroz","rice"],
    [1,"l","water","liquid","agua caliente","hot water"],
    [300,"g","shrimp","protein","camarones pelados","peeled prawns"],
    [300,"g","clam","protein","almejas","clams"],
    [250,"g","squid","protein","calamar en aros","squid rings"],
    [1,"handful","herb","aromatic","epazote o cilantro","epazote or coriander"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Arroz a la tumbada", b:"Arroz caldoso con mariscos del puerto de Veracruz, rojo de jitomate y perfumado con epazote.",
  st:["Sofríe la cebolla, el ajo y el pimiento en el aceite 5 minutos.",
      "Añade el jitomate y cocina 8 minutos hasta que se deshaga.",
      "Añade el arroz, mezcla 2 minutos y agrega el agua y la sal. Cuece 12 minutos.",
      "Añade el calamar, las almejas y los camarones y cuece 6 minutos, hasta que las almejas se abran.",
      "Termina con la hierba picada. Debe quedar caldoso."],
  tp:["Tira las almejas que no se abran.",
      "Sírvelo en cuanto esté: el arroz sigue absorbiendo caldo."],
  v:"arroz a la tumbada veracruzano"},
 en:{n:"Arroz a la Tumbada (Veracruz Seafood Rice)", b:"Soupy seafood rice from the port of Veracruz, red with tomato and fragrant with epazote.",
  st:["Cook the onion, garlic and pepper in the oil for 5 minutes.",
      "Add the tomato and cook 8 minutes until it breaks down.",
      "Add the rice, stir 2 minutes and add the water and salt. Cook 12 minutes.",
      "Add the squid, clams and prawns and cook 6 minutes, until the clams open.",
      "Finish with the chopped herb. It should stay soupy."],
  tp:["Discard any clams that don't open.",
      "Serve straight away: the rice keeps soaking up broth."],
  v:"arroz a la tumbada veracruz"}},

{id:"pambazos", c:"Mexico", r:"latin-america", m:"main", t:50, s:6,
 i:[[6,"","bread","structure","panes para pambazo o bolillos","pambazo rolls or bolillos"],
    [6,"","ancho","sauce","chiles guajillo","guajillo chillies","sin semillas","seeded"],
    [1,"clove","garlic","aromatic","ajo (para la salsa)","garlic (for the sauce)"],
    [4,"tbsp","oil","fat","aceite","oil"],
    [3,"","potato","structure","papas","potatoes","en cubos","cubed"],
    [200,"g","chorizo","protein","chorizo mexicano","Mexican chorizo"],
    [2,"handful","veg","garnish","lechuga","lettuce","picada","shredded"],
    [120,"ml","crema","garnish","crema","Mexican crema"],
    [80,"g","queso","garnish","queso fresco","queso fresco","desmoronado","crumbled"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Pambazos", b:"Pan bañado en salsa de guajillo y dorado en el comal, relleno de papa con chorizo. Antojito de la Ciudad de México.",
  st:["Hierve la papa 12 minutos y escúrrela.",
      "Fríe el chorizo 5 minutos, añade la papa y aplasta un poco. Sala.",
      "Remoja los chiles en agua caliente 10 minutos y lícualos con el ajo y 200 ml de su agua. Cuela.",
      "Abre los panes, báñalos por fuera en la salsa y dóralos en el aceite 1 minuto por lado.",
      "Rellena con la papa con chorizo, la lechuga, la crema y el queso."],
  tp:["El pan debe ser algo duro para que aguante la salsa sin romperse.",
      "Báñalos justo antes de dorarlos para que no se empapen."],
  v:"pambazos de papa con chorizo"},
 en:{n:"Pambazos", b:"Bread dunked in guajillo sauce and crisped on the griddle, stuffed with potato and chorizo. A Mexico City street snack.",
  st:["Boil the potato for 12 minutes and drain.",
      "Fry the chorizo 5 minutes, add the potato and crush lightly. Salt.",
      "Soak the chillies in hot water for 10 minutes and blend with the garlic and 200 ml of the soaking water. Strain.",
      "Split the rolls, dip the outsides in the sauce and fry in the oil 1 minute per side.",
      "Fill with the potato and chorizo, lettuce, crema and cheese."],
  tp:["Slightly stale bread holds the sauce without falling apart.",
      "Dip right before frying so they don't go soggy."],
  v:"mexican pambazos recipe"}},

{id:"tlacoyos", c:"Mexico", r:"latin-america", m:"main", t:50, s:4,
 i:[[500,"g","masa","structure","masa de maíz","fresh corn masa"],
    [1,"tsp","salt","salt","sal","salt"],
    [250,"g","legume","structure","frijoles negros cocidos","cooked black beans","escurridos","drained"],
    [1,"tbsp","oil","fat","aceite","oil"],
    [200,"g","veg","garnish","nopales cocidos","cooked cactus paddles","en tiras","in strips"],
    [80,"g","queso","garnish","queso fresco","queso fresco","desmoronado","crumbled"],
    [0.5,"","onion","garnish","cebolla","onion","picada","chopped"],
    [1,"handful","herb","garnish","cilantro","coriander","picado","chopped"]],
 es:{n:"Tlacoyos de frijol", b:"Óvalos de masa rellenos de frijol, cocidos en comal. Antojito de los mercados del centro de México.",
  st:["Machaca los frijoles con el aceite y una pizca de sal hasta formar una pasta.",
      "Amasa la masa con la sal. Forma 8 bolas.",
      "Aplana cada bola, pon 1 cucharada de frijol, cierra y aplana en forma de óvalo de 1 cm.",
      "Cuécelos en un comal caliente 4 minutos por lado.",
      "Cubre con los nopales, el queso, la cebolla y el cilantro."],
  tp:["Si la masa se agrieta, añade un poco de agua.",
      "El comal debe estar bien caliente para que no se peguen."],
  v:"tlacoyos de frijol"},
 en:{n:"Bean Tlacoyos", b:"Ovals of corn masa stuffed with beans and cooked on the griddle. A market snack from central Mexico.",
  st:["Mash the beans with the oil and a pinch of salt into a paste.",
      "Knead the masa with the salt. Shape 8 balls.",
      "Flatten each ball, add 1 tablespoon of bean, close and pat into a 1 cm oval.",
      "Cook on a hot griddle for 4 minutes per side.",
      "Top with the cactus, cheese, onion and coriander."],
  tp:["If the masa cracks, add a little water.",
      "The griddle must be very hot so they don't stick."],
  v:"bean tlacoyos recipe"}},

{id:"tortitas-de-papa", c:"Mexico", r:"latin-america", m:"main", t:50, s:4,
 i:[[800,"g","potato","structure","papas","potatoes"],
    [150,"g","queso","enrich","queso fresco","queso fresco","desmoronado","crumbled"],
    [2,"","egg","binder","huevos","eggs"],
    [2,"tbsp","apflour","binder","harina de trigo","plain flour"],
    [1,"tsp","salt","salt","sal","salt"],
    [200,"ml","oil","fat","aceite para freír","oil for frying"],
    [4,"","tomato","sauce","jitomates","tomatoes"],
    [0.5,"","onion","aromatic","cebolla","onion"],
    [1,"clove","garlic","aromatic","ajo","garlic"],
    [300,"ml","water","liquid","agua","water"]],
 es:{n:"Tortitas de papa en caldillo", b:"Tortitas de papa con queso, fritas y servidas en un caldillo de jitomate. Comida de Cuaresma en México.",
  st:["Hierve las papas 20 minutos, pélalas y hazlas puré.",
      "Mezcla el puré con el queso, los huevos, la harina y la sal. Forma 12 tortitas.",
      "Fríelas en el aceite 3 minutos por lado. Escurre.",
      "Licúa el jitomate, la cebolla, el ajo y el agua. Cuece 10 minutos con 1 cucharada del aceite y sala.",
      "Pon las tortitas en el caldillo 3 minutos y sirve."],
  tp:["Deja enfriar el puré antes de formar para que no se deshagan.",
      "Mételas al caldillo justo antes de servir para que no se ablanden de más."],
  v:"tortitas de papa en caldillo"},
 en:{n:"Tortitas de Papa (Potato Cakes in Tomato Broth)", b:"Cheesy potato cakes, fried and served in a light tomato broth. A Lenten meal in Mexico.",
  st:["Boil the potatoes 20 minutes, peel and mash.",
      "Mix the mash with the cheese, eggs, flour and salt. Shape 12 cakes.",
      "Fry them in the oil for 3 minutes per side. Drain.",
      "Blend the tomato, onion, garlic and water. Simmer 10 minutes with 1 tablespoon of the oil and salt.",
      "Put the cakes in the broth for 3 minutes and serve."],
  tp:["Let the mash cool before shaping so they hold together.",
      "Add them to the broth just before serving so they don't go too soft."],
  v:"mexican potato cakes tomato broth"}},

{id:"agua-de-pepino", c:"Mexico", r:"latin-america", m:"drink", t:10, s:6,
 i:[[2,"","veg","structure","pepinos","cucumbers","en trozos","in chunks"],
    [3,"","citrus","acid","limones","limes","exprimidos","juiced"],
    [1.5,"l","water","liquid","agua fría","cold water"],
    [100,"g","sugar","sweet","azúcar","sugar"],
    [1,"handful","herb","aromatic","hojas de menta","mint leaves"],
    [300,"g","ice","liquid","hielo","ice"]],
 es:{n:"Agua de pepino con limón", b:"Agua fresca verde y ligera, de las que se venden en vitroleros en los mercados de México.",
  st:["Licúa el pepino con la menta y 500 ml de agua.",
      "Cuela si la quieres más fina.",
      "Mezcla con el resto del agua, el jugo de limón y el azúcar hasta que se disuelva.",
      "Sirve con el hielo."],
  tp:["Pela el pepino si tiene la piel amarga.",
      "Sírvela el mismo día: pierde color con las horas."],
  v:"agua de pepino con limón"},
 en:{n:"Agua de Pepino (Cucumber Lime Cooler)", b:"A light green agua fresca, the kind sold from big glass jars in Mexican markets.",
  st:["Blend the cucumber with the mint and 500 ml of water.",
      "Strain if you want it smoother.",
      "Mix with the rest of the water, lime juice and sugar until dissolved.",
      "Serve over the ice."],
  tp:["Peel the cucumber if the skin is bitter.",
      "Drink it the same day: it loses colour over time."],
  v:"cucumber lime agua fresca"}},

{id:"chicharron-en-salsa-verde", c:"Mexico", r:"latin-america", m:"main", t:30, s:4,
 i:[[500,"g","tomatillo","sauce","tomates verdes","tomatillos"],
    [2,"","chilli","sauce","chiles serranos","serrano chillies"],
    [0.5,"","onion","aromatic","cebolla","onion"],
    [2,"clove","garlic","aromatic","ajo","garlic"],
    [1,"handful","herb","aromatic","cilantro","coriander"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [200,"g","porkskin","protein","chicharrón de cerdo","pork crackling","en trozos","in pieces"],
    [250,"ml","water","liquid","agua","water"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Chicharrón en salsa verde", b:"Chicharrón que se ablanda en una salsa de tomate verde picosa. Desayuno de fonda mexicana.",
  st:["Hierve los tomates verdes y los chiles 8 minutos.",
      "Lícualos con la cebolla, el ajo, el cilantro y el agua.",
      "Fríe la salsa en el aceite 5 minutos y sala.",
      "Añade el chicharrón y cuece 10 minutos a fuego bajo, hasta que se ablande."],
  tp:["Si lo quieres con algo de textura, cuécelo solo 5 minutos.",
      "Prueba de sal al final: el chicharrón ya es salado."],
  v:"chicharrón en salsa verde"},
 en:{n:"Chicharrón en Salsa Verde", b:"Pork crackling softened in a spicy tomatillo sauce. A Mexican diner breakfast.",
  st:["Boil the tomatillos and chillies for 8 minutes.",
      "Blend with the onion, garlic, coriander and water.",
      "Fry the sauce in the oil for 5 minutes and salt.",
      "Add the crackling and simmer 10 minutes on low, until softened."],
  tp:["For some bite left, cook it only 5 minutes.",
      "Taste for salt at the end: the crackling is already salty."],
  v:"chicharron in green sauce"}},

{id:"sopa-de-lentejas-mx", c:"Mexico", r:"latin-america", m:"soup", t:60, s:6,
 i:[[300,"g","legume","structure","lentejas","lentils"],
    [2,"l","water","liquid","agua","water"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"","tomato","liquid","jitomates","tomatoes","picados","chopped"],
    [1,"","veg","structure","zanahoria","carrot","en dados","diced"],
    [1,"","plantain","sweet","plátano macho maduro","ripe plantain","en rodajas","sliced"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Sopa de lentejas con plátano", b:"Lentejas caldosas con jitomate y rodajas de plátano macho maduro, que les da un toque dulce. Muy de casa en México.",
  st:["Cuece las lentejas en el agua 25 minutos.",
      "Sofríe la cebolla y el ajo en el aceite 5 minutos. Añade el jitomate y cocina 5 minutos.",
      "Agrega el sofrito a las lentejas con la zanahoria y la sal. Cuece 15 minutos.",
      "Añade el plátano y cuece 10 minutos más."],
  tp:["El plátano debe estar bien maduro, con la piel casi negra.",
      "Si espesa, añade agua caliente."],
  v:"sopa de lentejas con plátano macho"},
 en:{n:"Mexican Lentil Soup with Plantain", b:"Brothy lentils with tomato and slices of ripe plantain for a touch of sweetness. A Mexican home staple.",
  st:["Simmer the lentils in the water for 25 minutes.",
      "Cook the onion and garlic in the oil for 5 minutes. Add the tomato and cook 5 minutes.",
      "Stir this into the lentils with the carrot and salt. Simmer 15 minutes.",
      "Add the plantain and cook 10 minutes more."],
  tp:["The plantain should be very ripe, its skin nearly black.",
      "If it thickens, add hot water."],
  v:"mexican lentil soup with plantain"}},

{id:"frijoles-puercos", c:"Mexico", r:"latin-america", m:"side", t:30, s:6,
 i:[[150,"g","chorizo","protein","chorizo mexicano","Mexican chorizo"],
    [100,"g","bacon","protein","tocino","bacon","picado","chopped"],
    [0.5,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"","chipotleadobo","aromatic","chiles chipotles adobados","chipotles in adobo","picados","chopped"],
    [750,"g","legume","structure","frijoles bayos cocidos con su líquido de cocción","cooked pinto beans with their cooking liquid"],
    [100,"g","cheese","garnish","queso Chihuahua rallado","grated Chihuahua cheese"],
    [1,"handful","olives","garnish","aceitunas","olives","picadas","chopped"]],
 es:{n:"Frijoles puercos", b:"Frijoles machacados con chorizo, tocino y chipotle, cubiertos de queso. Botana del norte y occidente de México.",
  st:["Fríe el tocino 5 minutos. Añade el chorizo y la cebolla y cocina 5 minutos.",
      "Añade los chipotles y los frijoles con su líquido.",
      "Machaca y cocina 10 minutos, removiendo, hasta que espesen.",
      "Cubre con el queso y las aceitunas y tapa 2 minutos para que se funda."],
  tp:["Sírvelos calientes, para untar.",
      "Si quedan secos, añade más líquido de los frijoles."],
  v:"frijoles puercos"},
 en:{n:"Frijoles Puercos", b:"Mashed beans with chorizo, bacon and chipotle, topped with cheese. A snack from northern and western Mexico.",
  st:["Fry the bacon 5 minutes. Add the chorizo and onion and cook 5 minutes.",
      "Add the chipotles and the beans with their liquid.",
      "Mash and cook 10 minutes, stirring, until thick.",
      "Top with the cheese and olives and cover 2 minutes to melt."],
  tp:["Eat them warm as a dip.",
      "If they dry out, add more bean liquid."],
  v:"mexican frijoles puercos"}},

{id:"camote-enmielado", c:"Mexico", r:"latin-america", m:"sweet", t:70, s:6,
 i:[[1,"kg","veg","structure","camotes","sweet potatoes","en trozos grandes","in large chunks"],
    [300,"g","brownsugar","sweet","piloncillo","piloncillo (unrefined cane sugar)"],
    [500,"ml","water","liquid","agua","water"],
    [1,"piece","spice","aromatic","rama de canela","cinnamon stick"],
    [2,"piece","citrus","aromatic","cáscara de naranja","orange peel strips"]],
 es:{n:"Camote enmielado", b:"Camote cocido lentamente en miel de piloncillo con canela. Dulce de Día de Muertos.",
  st:["Hierve el agua con el piloncillo, la canela y la cáscara hasta que se disuelva.",
      "Añade el camote y cuece tapado 40 minutos a fuego bajo, volteando a mitad.",
      "Destapa y cuece 15 minutos más, hasta que el almíbar espese y brille.",
      "Sirve tibio o frío con su almíbar."],
  tp:["Mueve la olla en vez de remover para que el camote no se rompa.",
      "Se conserva 4 días en la nevera."],
  v:"camote enmielado con piloncillo"},
 en:{n:"Camote Enmielado (Candied Sweet Potato)", b:"Sweet potato simmered slowly in piloncillo syrup with cinnamon. A Day of the Dead sweet.",
  st:["Boil the water with the piloncillo, cinnamon and peel until dissolved.",
      "Add the sweet potato and simmer covered for 40 minutes on low, turning halfway.",
      "Uncover and cook 15 minutes more, until the syrup thickens and shines.",
      "Serve warm or cold with its syrup."],
  tp:["Shake the pot instead of stirring so the sweet potato stays whole.",
      "It keeps 4 days in the fridge."],
  v:"mexican candied sweet potato"}}
];
