module.exports = [
{id:"huaraches", c:"Mexico", r:"latin-america", m:"main", t:50, s:4,
 i:[[500,"g","masa","structure","masa de maíz","fresh corn masa"],
    [1,"tsp","salt","salt","sal","salt"],
    [250,"g","legume","structure","frijoles negros cocidos","cooked black beans","machacados","mashed"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [300,"g","beef","protein","bistec de res","beef steak","en tiras","in strips"],
    [4,"","tomatillo","sauce","tomates verdes","tomatillos"],
    [1,"","chilli","sauce","chile serrano","serrano chilli"],
    [1,"clove","garlic","sauce","ajo","garlic"],
    [0.5,"","onion","garnish","cebolla","onion","picada","chopped"],
    [80,"g","queso","garnish","queso fresco","queso fresco","desmoronado","crumbled"],
    [60,"ml","crema","garnish","crema","Mexican crema"]],
 es:{n:"Huaraches", b:"Tortillas alargadas de masa rellenas de frijol, con bistec, salsa verde y queso. Nacieron en los mercados de la Ciudad de México.",
  st:["Amasa la masa con la sal. Divide en 4 bolas y forma cilindros de 15 cm.",
      "Abre cada cilindro, pon una línea de frijol, cierra y aplana en forma de suela de 5 mm.",
      "Cuécelos en un comal caliente 3 minutos por lado.",
      "Hierve los tomates verdes, el chile y el ajo 8 minutos y licúalos con sal.",
      "Saltea la carne en el aceite 4 minutos. Cubre cada huarache con salsa, carne, cebolla, queso y crema."],
  tp:["Aplana entre dos plásticos para que no se rompan.",
      "Pasa los huaraches por el aceite caliente de la carne para que se doren."],
  v:"huaraches de bistec"},
 en:{n:"Huaraches", b:"Long, sandal-shaped masa cakes filled with beans and topped with steak, green salsa and cheese. Born in Mexico City's markets.",
  st:["Knead the masa with the salt. Divide into 4 balls and roll into 15 cm logs.",
      "Open each log, lay in a line of beans, close and flatten into a 5 mm sole shape.",
      "Cook on a hot griddle for 3 minutes per side.",
      "Boil the tomatillos, chilli and garlic for 8 minutes and blend with salt.",
      "Stir-fry the beef in the oil for 4 minutes. Top each huarache with salsa, beef, onion, cheese and crema."],
  tp:["Flatten between two sheets of plastic so they don't tear.",
      "Crisp the huaraches in the hot oil from the steak."],
  v:"mexican huaraches"}},

{id:"sopa-de-flor-de-calabaza", c:"Mexico", r:"latin-america", m:"soup", t:40, s:4,
 i:[[2,"tbsp","butter","fat","mantequilla","butter"],
    [0.5,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"","veg","structure","calabacitas","courgettes","en cubos","cubed"],
    [150,"g","corn","structure","granos de elote","corn kernels"],
    [300,"g","veg","structure","flores de calabaza","squash blossoms","sin pistilos, picadas","stamens removed, chopped"],
    [1,"l","water","liquid","agua","water"],
    [1,"sprig","herb","aromatic","epazote","epazote"],
    [1,"tsp","salt","salt","sal","salt"],
    [80,"g","queso","garnish","queso fresco","queso fresco","en cubos","cubed"]],
 es:{n:"Sopa de flor de calabaza", b:"Sopa ligera de flor de calabaza, calabacita y elote. Sabor de la temporada de lluvias en el centro de México.",
  st:["Sofríe la cebolla y el ajo en la mantequilla 4 minutos.",
      "Añade la calabacita y el elote y cocina 5 minutos.",
      "Añade el agua, el epazote y la sal y cuece 10 minutos.",
      "Añade las flores y cuece 3 minutos más.",
      "Sirve con el queso en cubos."],
  tp:["Las flores se cuecen en segundos: añádelas al final.",
      "Quita los pistilos: amargan."],
  v:"sopa de flor de calabaza"},
 en:{n:"Squash Blossom Soup", b:"A light soup of squash blossoms, courgette and corn. The taste of the rainy season in central Mexico.",
  st:["Cook the onion and garlic in the butter for 4 minutes.",
      "Add the courgette and corn and cook 5 minutes.",
      "Add the water, epazote and salt and simmer 10 minutes.",
      "Add the blossoms and cook 3 minutes more.",
      "Serve with the cubed cheese."],
  tp:["The blossoms cook in seconds: add them last.",
      "Remove the stamens: they're bitter."],
  v:"mexican squash blossom soup"}},

{id:"pollo-en-salsa-de-cacahuate", c:"Mexico", r:"latin-america", m:"main", t:60, s:4,
 i:[[4,"thigh","chicken","protein","muslos de pollo","chicken thighs"],
    [1,"l","water","liquid","agua","water"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [150,"g","peanut","sauce","cacahuates tostados sin sal","unsalted roasted peanuts"],
    [2,"","ancho","sauce","chiles guajillo","guajillo chillies","sin semillas","seeded"],
    [2,"","tomato","sauce","jitomates","tomatoes"],
    [0.5,"","onion","aromatic","cebolla","onion"],
    [2,"clove","garlic","aromatic","ajo","garlic"],
    [1,"piece","spice","aromatic","rama de canela","cinnamon stick"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Pollo en salsa de cacahuate", b:"Pollo en una salsa espesa de cacahuate tostado, jitomate y guajillo. Comida de fiesta en Veracruz y Puebla.",
  st:["Cuece el pollo en el agua con 1 cucharadita de sal 25 minutos. Guarda el caldo.",
      "Tuesta los chiles 30 segundos y remójalos en caldo caliente 10 minutos.",
      "Licúa los cacahuates, los chiles, el jitomate, la cebolla, el ajo, la canela y 500 ml de caldo.",
      "Fríe la salsa en el aceite 10 minutos, removiendo, y sala.",
      "Añade el pollo y cuece 10 minutos a fuego bajo."],
  tp:["Si la salsa espesa demasiado, añade más caldo.",
      "Remueve siempre: el cacahuate se pega fácil."],
  v:"pollo en salsa de cacahuate"},
 en:{n:"Chicken in Peanut Sauce (Mexican)", b:"Chicken in a thick sauce of roasted peanuts, tomato and guajillo. A festive dish in Veracruz and Puebla.",
  st:["Simmer the chicken in the water with 1 teaspoon of salt for 25 minutes. Keep the broth.",
      "Toast the chillies for 30 seconds and soak in hot broth for 10 minutes.",
      "Blend the peanuts, chillies, tomato, onion, garlic, cinnamon and 500 ml of broth.",
      "Fry the sauce in the oil for 10 minutes, stirring, and salt.",
      "Add the chicken and simmer 10 minutes on low."],
  tp:["If the sauce gets too thick, add more broth.",
      "Keep stirring: peanut catches easily."],
  v:"mexican chicken peanut sauce"}},

{id:"caldo-de-pollo-mx", c:"Mexico", r:"latin-america", m:"soup", t:75, s:6,
 i:[[1.2,"kg","chicken","protein","pollo en piezas","chicken pieces"],
    [3,"l","water","liquid","agua","water"],
    [0.5,"","onion","aromatic","cebolla","onion"],
    [3,"clove","garlic","aromatic","ajo","garlic"],
    [2,"","veg","structure","zanahorias","carrots","en trozos","in chunks"],
    [2,"","veg","structure","calabacitas","courgettes","en trozos","in chunks"],
    [2,"","potato","structure","papas","potatoes","en trozos","in chunks"],
    [1,"","corn","structure","elote","corn cob","en rodajas","in rounds"],
    [1,"handful","herb","aromatic","cilantro","coriander"],
    [3,"tsp","salt","salt","sal","salt"],
    [3,"","citrus","acid","limones","limes"]],
 es:{n:"Caldo de pollo", b:"El caldo de pollo mexicano con verduras en trozos grandes. Remedio de abuela para cualquier mal.",
  st:["Cuece el pollo en el agua con la cebolla, el ajo y la sal 40 minutos, espumando.",
      "Añade la zanahoria, la papa y el elote y cuece 15 minutos.",
      "Añade la calabacita y el cilantro y cuece 8 minutos más.",
      "Sirve con limón."],
  tp:["Espuma bien al principio para un caldo limpio.",
      "Sirve con un poco de arroz blanco dentro del plato, como en las fondas."],
  v:"caldo de pollo mexicano"},
 en:{n:"Caldo de Pollo (Mexican Chicken Soup)", b:"Mexican chicken soup with big chunks of vegetables. Grandma's cure for anything.",
  st:["Simmer the chicken in the water with the onion, garlic and salt for 40 minutes, skimming.",
      "Add the carrot, potato and corn and cook 15 minutes.",
      "Add the courgette and coriander and cook 8 minutes more.",
      "Serve with lime."],
  tp:["Skim well at the start for a clear broth.",
      "Serve with a scoop of plain rice in the bowl, as diners do."],
  v:"mexican caldo de pollo"}},

{id:"bistec-a-la-mexicana", c:"Mexico", r:"latin-america", m:"main", t:30, s:4,
 i:[[600,"g","beef","protein","bistec de res","beef steak","en tiras","in strips"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"","chilli","aromatic","chiles serranos","serrano chillies","picados","chopped"],
    [4,"","tomato","liquid","jitomates","tomatoes","picados","chopped"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"handful","herb","garnish","cilantro","coriander","picado","chopped"]],
 es:{n:"Bistec a la mexicana", b:"Bistec en tiras guisado con jitomate, cebolla y chile: los colores de la bandera. Guisado de fonda.",
  st:["Sala la carne y dórala en el aceite a fuego fuerte 4 minutos.",
      "Añade la cebolla y el chile y cocina 3 minutos.",
      "Añade el jitomate y cocina 8 minutos, hasta que suelte su jugo.",
      "Termina con el cilantro."],
  tp:["Sírvelo con arroz blanco.",
      "Si el jitomate está seco, añade un chorrito de agua."],
  v:"bistec a la mexicana"},
 en:{n:"Bistec a la Mexicana", b:"Beef strips stewed with tomato, onion and chilli: the colours of the flag. A Mexican diner stew.",
  st:["Salt the beef and brown it in the oil over high heat for 4 minutes.",
      "Add the onion and chilli and cook 3 minutes.",
      "Add the tomato and cook 8 minutes, until juicy.",
      "Finish with the coriander."],
  tp:["Serve with white rice.",
      "If the tomato is dry, add a splash of water."],
  v:"mexican steak with tomato"}},

{id:"chiles-en-escabeche", c:"Mexico", r:"latin-america", m:"sauce", t:30, s:12,
 i:[[400,"g","chilli","structure","chiles jalapeños","jalapeño chillies","en rodajas","sliced"],
    [3,"","veg","structure","zanahorias","carrots","en rodajas","sliced"],
    [1,"","onion","aromatic","cebolla","onion","en gajos","in wedges"],
    [8,"clove","garlic","aromatic","ajo","garlic","pelados","peeled"],
    [60,"ml","oil","fat","aceite","oil"],
    [400,"ml","whitevinegar","acid","vinagre blanco","white vinegar"],
    [200,"ml","water","liquid","agua","water"],
    [3,"leaf","herb","aromatic","laurel","bay leaves"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [1,"tsp","herb","aromatic","tomillo seco","dried thyme"],
    [2,"tsp","salt","salt","sal","salt"],
    [1,"tsp","sugar","sweet","azúcar","sugar"]],
 es:{n:"Chiles en escabeche", b:"Jalapeños y zanahorias en vinagre con hierbas. Están en la mesa de toda taquería mexicana.",
  st:["Sofríe el ajo, la cebolla y la zanahoria en el aceite 4 minutos.",
      "Añade los chiles y cocina 3 minutos.",
      "Añade el vinagre, el agua, las hierbas, la sal y el azúcar y hierve 5 minutos.",
      "Pasa a frascos limpios y deja enfriar. Refrigera 24 horas antes de comer."],
  tp:["Se conservan 1 mes en la nevera.",
      "No los cuezas de más: deben seguir firmes."],
  v:"chiles en escabeche caseros"},
 en:{n:"Chiles en Escabeche (Pickled Jalapeños)", b:"Jalapeños and carrots pickled with herbs. On the table of every Mexican taquería.",
  st:["Cook the garlic, onion and carrot in the oil for 4 minutes.",
      "Add the chillies and cook 3 minutes.",
      "Add the vinegar, water, herbs, salt and sugar and boil 5 minutes.",
      "Pour into clean jars and cool. Chill 24 hours before eating."],
  tp:["They keep 1 month in the fridge.",
      "Don't overcook: they should stay firm."],
  v:"mexican pickled jalapenos"}},

{id:"costillas-en-salsa-verde", c:"Mexico", r:"latin-america", m:"main", t:90, s:4,
 i:[[1,"kg","pork","protein","costillas de cerdo","pork ribs","en trozos","in pieces"],
    [1,"l","water","liquid","agua","water"],
    [2,"tsp","salt","salt","sal","salt"],
    [600,"g","tomatillo","sauce","tomates verdes","tomatillos"],
    [3,"","chilli","sauce","chiles serranos","serrano chillies"],
    [0.5,"","onion","aromatic","cebolla","onion"],
    [2,"clove","garlic","aromatic","ajo","garlic"],
    [1,"handful","herb","aromatic","cilantro","coriander"],
    [3,"","veg","structure","calabacitas","courgettes","en cubos","cubed"],
    [1,"tbsp","oil","fat","aceite","oil"]],
 es:{n:"Costillas de cerdo en salsa verde", b:"Costillas tiernas guisadas en salsa de tomate verde con calabacitas. Guisado de comida corrida mexicana.",
  st:["Cuece las costillas en el agua con la sal 45 minutos. Guarda 300 ml del caldo.",
      "Hierve los tomates verdes y los chiles 8 minutos. Lícualos con la cebolla, el ajo, el cilantro y el caldo.",
      "Dora las costillas escurridas en el aceite 5 minutos.",
      "Añade la salsa y cuece 10 minutos.",
      "Añade la calabacita y cuece 10 minutos más."],
  tp:["Dorar las costillas antes de la salsa les da más sabor.",
      "Prueba de sal al final."],
  v:"costillas en salsa verde"},
 en:{n:"Pork Ribs in Salsa Verde", b:"Tender pork ribs stewed in tomatillo sauce with courgettes. A Mexican set-lunch stew.",
  st:["Simmer the ribs in the water with the salt for 45 minutes. Keep 300 ml of the broth.",
      "Boil the tomatillos and chillies for 8 minutes. Blend with the onion, garlic, coriander and broth.",
      "Brown the drained ribs in the oil for 5 minutes.",
      "Add the sauce and simmer 10 minutes.",
      "Add the courgette and cook 10 minutes more."],
  tp:["Browning the ribs before the sauce adds flavour.",
      "Taste for salt at the end."],
  v:"mexican pork ribs green sauce"}},

{id:"gorditas-de-nata", c:"Mexico", r:"latin-america", m:"sweet", t:40, s:12,
 i:[[300,"g","apflour","structure","harina de trigo","plain flour"],
    [1,"tsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [100,"g","sugar","sweet","azúcar","sugar"],
    [200,"ml","cream","enrich","nata o crema espesa","thick cream"],
    [1,"","egg","binder","huevo","egg"],
    [1,"tsp","vanilla","aromatic","esencia de vainilla","vanilla extract"],
    [1,"tsp","spice","aromatic","canela molida","ground cinnamon"]],
 es:{n:"Gorditas de nata", b:"Panecitos dulces y suaves hechos con nata, cocidos en comal. Se venden en las ferias y en la Villa de Guadalupe.",
  st:["Mezcla la harina, el polvo de hornear, el azúcar y la canela.",
      "Añade la nata, el huevo y la vainilla y mezcla hasta tener una masa suave.",
      "Forma 12 bolas y aplánalas a 1 cm.",
      "Cuécelas en un comal a fuego bajo 4 minutos por lado, hasta que estén doradas."],
  tp:["El fuego bajo es clave para que se cuezan por dentro.",
      "Guárdalas envueltas en un paño para que sigan suaves."],
  v:"gorditas de nata"},
 en:{n:"Gorditas de Nata (Sweet Cream Griddle Cakes)", b:"Soft, sweet little cakes made with cream and cooked on a griddle. Sold at fairs and outside the Basilica of Guadalupe.",
  st:["Mix the flour, baking powder, sugar and cinnamon.",
      "Add the cream, egg and vanilla and mix into a soft dough.",
      "Shape 12 balls and flatten to 1 cm.",
      "Cook on a griddle over low heat for 4 minutes per side, until golden."],
  tp:["Low heat is key so they cook through.",
      "Keep them wrapped in a tea towel so they stay soft."],
  v:"mexican gorditas de nata"}},

{id:"empanadas-de-calabaza", c:"Mexico", r:"latin-america", m:"pastry", t:90, s:12,
 i:[[800,"g","veg","structure","calabaza de Castilla","pumpkin","en trozos","in chunks"],
    [200,"g","brownsugar","sweet","piloncillo","piloncillo (unrefined cane sugar)"],
    [1,"piece","spice","aromatic","rama de canela","cinnamon stick"],
    [200,"ml","water","liquid","agua","water"],
    [400,"g","apflour","structure","harina de trigo","plain flour"],
    [120,"g","shortening","fat","manteca vegetal","vegetable shortening"],
    [1,"tsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [0.5,"tsp","salt","salt","sal","salt"],
    [150,"ml","water","liquid","agua fría (segunda parte)","cold water (second part)"],
    [2,"tbsp","sugar","garnish","azúcar","sugar"]],
 es:{n:"Empanadas de calabaza", b:"Empanadas horneadas rellenas de calabaza con piloncillo y canela. Panadería de temporada de otoño en México.",
  st:["Cuece la calabaza con el piloncillo, la canela y el agua 30 minutos. Retira la canela, machaca y cuece hasta que espese. Deja enfriar.",
      "Mezcla la harina, el polvo de hornear y la sal. Frota la manteca y añade el agua fría hasta formar una masa.",
      "Estira a 3 mm y corta círculos de 12 cm.",
      "Rellena, dobla y sella con un tenedor. Espolvorea con el azúcar.",
      "Hornea a 190 °C 20 minutos, hasta que estén doradas."],
  tp:["El relleno debe estar frío y espeso para que no se salga.",
      "Pincha cada empanada para que salga el vapor."],
  v:"empanadas de calabaza"},
 en:{n:"Empanadas de Calabaza (Pumpkin Turnovers)", b:"Baked turnovers filled with pumpkin, cane sugar and cinnamon. Autumn bakery fare in Mexico.",
  st:["Cook the pumpkin with the piloncillo, cinnamon and water for 30 minutes. Remove the cinnamon, mash and cook until thick. Cool.",
      "Mix the flour, baking powder and salt. Rub in the shortening and add the cold water to form a dough.",
      "Roll to 3 mm and cut 12 cm circles.",
      "Fill, fold and seal with a fork. Sprinkle with the sugar.",
      "Bake at 190 °C for 20 minutes, until golden."],
  tp:["The filling must be cold and thick so it doesn't leak.",
      "Prick each turnover to let steam out."],
  v:"mexican pumpkin empanadas"}},

{id:"agua-de-chia", c:"Mexico", r:"latin-america", m:"drink", t:20, s:6,
 i:[[3,"tbsp","seeds","structure","semillas de chía","chia seeds"],
    [1.5,"l","water","liquid","agua fría","cold water"],
    [5,"","citrus","acid","limones","limes","exprimidos","juiced"],
    [100,"g","sugar","sweet","azúcar","sugar"],
    [300,"g","ice","liquid","hielo","ice"]],
 es:{n:"Agua de limón con chía", b:"Limonada con semillas de chía hidratadas. Refrescante y de las aguas frescas más vendidas en México.",
  st:["Hidrata la chía en 250 ml de agua 15 minutos, removiendo a veces.",
      "Mezcla el resto del agua con el jugo de limón y el azúcar hasta que se disuelva.",
      "Añade la chía y remueve.",
      "Sirve con el hielo."],
  tp:["Remueve la chía al principio para que no forme grumos.",
      "Remueve antes de servir: la chía se asienta."],
  v:"agua de limón con chía"},
 en:{n:"Agua de Chía (Chia Limeade)", b:"Limeade with soaked chia seeds. Refreshing and one of Mexico's best-selling aguas frescas.",
  st:["Soak the chia in 250 ml of the water for 15 minutes, stirring now and then.",
      "Mix the rest of the water with the lime juice and sugar until dissolved.",
      "Add the chia and stir.",
      "Serve over the ice."],
  tp:["Stir the chia early on so it doesn't clump.",
      "Stir before serving: the chia settles."],
  v:"chia limeade agua fresca"}}
];
