module.exports = [
{id:"menudo", c:"Mexico", r:"latin-america", m:"soup", t:300, s:10,
 i:[[1.5,"kg","beef","protein","panza de res (callo)","beef tripe","lavada y en cuadros de 3 cm","washed, in 3 cm squares"],
    [1,"","beef","protein","pata de res","beef foot","partida en trozos","cut in pieces"],
    [4,"l","water","liquid","agua","water"],
    [1,"","onion","aromatic","cebolla","onion","en mitades","halved"],
    [1,"","garlic","aromatic","cabeza de ajo","head of garlic","partida a la mitad","halved"],
    [6,"","chilli","sauce","chiles guajillo","guajillo chillies","sin semillas","seeded"],
    [2,"","ancho","sauce","chiles anchos","ancho chillies","sin semillas","seeded"],
    [1,"tbsp","herb","aromatic","orégano seco","dried oregano"],
    [800,"g","hominy","structure","maíz pozolero cocido","cooked hominy","escurrido","drained"],
    [1,"tbsp","salt","salt","sal","salt"],
    [1,"","onion","garnish","cebolla blanca","white onion","picada","chopped"],
    [3,"","citrus","garnish","limones","limes","en cuartos","in wedges"]],
 es:{n:"Menudo rojo", b:"Sopa de panza y pata de res en caldillo de guajillo con maíz pozolero. El remedio de los domingos en el norte de México.",
  st:["Cubre la panza y la pata con el agua, añade la cebolla en mitades, el ajo y la sal. Hierve y cuece tapado a fuego bajo 3 horas, hasta que la panza esté tierna.",
      "Remoja los chiles en agua caliente 15 minutos. Licúalos con 250 ml del líquido de la olla y cuela.",
      "Saca la cebolla y el ajo. Deshuesa la pata y regresa la carne a la olla.",
      "Añade la salsa de chile, la mitad del orégano y el maíz. Cuece 45 minutos más.",
      "Sirve con la cebolla picada, el resto del orégano y los limones."],
  tp:["Lava la panza con agua y limón y enjuaga bien antes de cocerla; así huele menos.",
      "Sabe mejor al día siguiente. Quita la grasa que cuaja arriba al enfriar."],
  v:"menudo rojo norteño receta"},
 en:{n:"Menudo (Red Tripe and Hominy Soup)", b:"Beef tripe and foot in a guajillo chilli soup with hominy. The Sunday cure of northern Mexico.",
  st:["Cover the tripe and foot with the water and add the halved onion, garlic and salt. Bring to a boil and simmer covered on low for 3 hours, until the tripe is tender.",
      "Soak the chillies in hot water for 15 minutes. Blend with 250 ml of the pot liquid and strain.",
      "Remove the onion and garlic. Take the meat off the foot bones and return it to the pot.",
      "Add the chilli sauce, half the oregano and the hominy. Cook 45 minutes more.",
      "Serve with the chopped onion, the rest of the oregano and the limes."],
  tp:["Wash the tripe with water and lime and rinse well before cooking; it smells less.",
      "It tastes better the next day. Lift off the fat that sets on top as it cools."],
  v:"menudo recipe"}},

{id:"pan-de-muerto", c:"Mexico", r:"latin-america", m:"bread", t:240, s:8, o:180,
 i:[[500,"g","apflour","structure","harina de trigo","plain flour"],
    [100,"g","sugar","sweet","azúcar","sugar"],
    [10,"g","yeast","leaven","levadura seca","dried yeast"],
    [1,"tsp","salt","salt","sal","salt"],
    [4,"","egg","enrich","huevos","eggs"],
    [80,"ml","milk","liquid","leche tibia","warm milk"],
    [120,"g","butter","fat","mantequilla blanda","soft butter"],
    [1,"tbsp","flowerwater","aromatic","agua de azahar","orange-blossom water"],
    [1,"","citrus","aromatic","ralladura de naranja","orange zest"],
    [1,"tsp","spice","aromatic","semillas de anís","aniseed","molidas","ground"],
    [50,"g","butter","glaze","mantequilla derretida","melted butter"],
    [100,"g","sugar","glaze","azúcar para cubrir","sugar for coating"]],
 es:{n:"Pan de muerto", b:"Pan dulce de azahar y naranja con huesitos encima y cubierto de azúcar. Se hace para el Día de Muertos.",
  st:["Mezcla la harina, 100 g de azúcar, la levadura, la sal y el anís. Añade los huevos, la leche, el azahar y la ralladura y amasa 10 minutos.",
      "Añade la mantequilla blanda poco a poco y amasa 10 minutos más, hasta que la masa esté lisa y elástica.",
      "Tapa y deja crecer 2 horas, hasta que doble su tamaño.",
      "Aparta un cuarto de la masa. Forma 2 bolas con el resto. Con la masa apartada, haz tiras con nudos para los huesos y bolitas para la cabeza y ponlas encima. Deja crecer 45 minutos.",
      "Hornea a 180 °C durante 30 minutos. Aún tibio, pinta con la mantequilla derretida y cubre con el azúcar."],
  tp:["La masa es pegajosa al principio; no añadas harina, sigue amasando.",
      "Para que el azúcar se pegue, pinta y reboza cuando el pan aún esté tibio."],
  v:"pan de muerto receta tradicional"},
 en:{n:"Pan de Muerto (Day of the Dead Bread)", b:"A sweet orange-blossom and orange bread with dough bones on top and a sugar coating. Made for the Day of the Dead.",
  st:["Mix the flour, 100 g of sugar, the yeast, salt and aniseed. Add the eggs, milk, orange-blossom water and zest and knead 10 minutes.",
      "Add the soft butter a little at a time and knead 10 minutes more, until the dough is smooth and elastic.",
      "Cover and leave to rise 2 hours, until doubled.",
      "Set aside a quarter of the dough. Shape 2 balls from the rest. With the reserved dough, make knotted ropes for the bones and small balls for the skull and set them on top. Rise 45 minutes.",
      "Bake at 180 °C for 30 minutes. While still warm, brush with the melted butter and coat with the sugar."],
  tp:["The dough is sticky at first; don't add flour, keep kneading.",
      "For the sugar to stick, brush and coat while the bread is still warm."],
  v:"pan de muerto recipe"}},

{id:"rosca-de-reyes", c:"Mexico", r:"latin-america", m:"bread", t:240, s:12, o:180,
 i:[[500,"g","apflour","structure","harina de trigo","plain flour"],
    [120,"g","sugar","sweet","azúcar","sugar"],
    [10,"g","yeast","leaven","levadura seca","dried yeast"],
    [1,"tsp","salt","salt","sal","salt"],
    [4,"","egg","enrich","huevos","eggs"],
    [100,"ml","milk","liquid","leche tibia","warm milk"],
    [120,"g","butter","fat","mantequilla blanda","soft butter"],
    [1,"","citrus","aromatic","ralladura de naranja","orange zest"],
    [1,"tsp","vanilla","aromatic","extracto de vainilla","vanilla extract"],
    [1,"","egg","glaze","huevo batido","beaten egg"],
    [150,"g","quincepaste","garnish","ate de membrillo","quince paste","en tiras","in strips"],
    [80,"g","candiedfruit","garnish","higos o acitrón cristalizados","candied figs or citron","en tiras","in strips"]],
 es:{n:"Rosca de Reyes", b:"Pan dulce en forma de corona, adornado con tiras de ate y fruta cristalizada. Se parte el 6 de enero.",
  st:["Mezcla la harina, el azúcar, la levadura y la sal. Añade 4 huevos, la leche, la ralladura y la vainilla y amasa 10 minutos.",
      "Añade la mantequilla poco a poco y amasa 10 minutos más, hasta que la masa esté lisa. Tapa y deja crecer 2 horas.",
      "Forma un cordón largo y une los extremos en una corona sobre la bandeja. Deja crecer 45 minutos.",
      "Pinta con el huevo batido y decora con las tiras de ate y de fruta cristalizada.",
      "Hornea a 180 °C durante 25 minutos, hasta que esté dorada. Enfría sobre una rejilla."],
  tp:["Si escondes un muñequito en la masa, avisa antes de repartir para que nadie lo muerda.",
      "Tapa con papel de aluminio a mitad de horneado si se dora demasiado rápido."],
  v:"rosca de reyes receta casera"},
 en:{n:"Rosca de Reyes (Three Kings Bread)", b:"A crown-shaped sweet bread decorated with strips of quince paste and candied fruit. Cut on 6 January.",
  st:["Mix the flour, sugar, yeast and salt. Add 4 eggs, the milk, zest and vanilla and knead 10 minutes.",
      "Add the butter a little at a time and knead 10 minutes more, until smooth. Cover and rise 2 hours.",
      "Shape into a long rope and join the ends into a ring on the tray. Rise 45 minutes.",
      "Brush with the beaten egg and decorate with the strips of quince paste and candied fruit.",
      "Bake at 180 °C for 25 minutes, until golden. Cool on a rack."],
  tp:["If you hide a little figurine in the dough, say so before serving so no one bites it.",
      "Cover with foil halfway through baking if it browns too fast."],
  v:"rosca de reyes recipe"}},

{id:"bolillos", c:"Mexico", r:"latin-america", m:"bread", t:180, s:8, o:220,
 i:[[500,"g","breadflour","structure","harina de trigo de fuerza","bread flour"],
    [7,"g","yeast","leaven","levadura seca","dried yeast"],
    [1,"tsp","sugar","sweet","azúcar","sugar"],
    [10,"g","salt","salt","sal","salt"],
    [320,"ml","water","liquid","agua tibia","warm water"],
    [20,"g","shortening","fat","manteca vegetal","vegetable shortening"]],
 es:{n:"Bolillos", b:"El pan blanco de cada día en México: corteza crujiente, miga suave y la raya en el centro. Base de tortas y molletes.",
  st:["Mezcla la harina, la levadura, el azúcar y la sal. Añade el agua y la manteca y amasa 10 minutos, hasta que la masa esté lisa.",
      "Tapa y deja crecer 1 hora, hasta que doble su tamaño.",
      "Divide en 8 piezas. Aplana cada una, enróllala apretada y dale forma alargada con las puntas finas. Deja crecer 40 minutos.",
      "Haz un corte a lo largo en cada bolillo.",
      "Hornea a 220 °C durante 20 minutos con un recipiente con agua en el fondo del horno, hasta que estén dorados y suenen huecos."],
  tp:["El vapor del agua en el horno es lo que da la corteza delgada y crujiente.",
      "Al día siguiente, rocíalos con agua y caliéntalos 5 minutos para que vuelvan a crujir."],
  v:"bolillos caseros receta"},
 en:{n:"Bolillos (Mexican Bread Rolls)", b:"Mexico's everyday white roll: crisp crust, soft crumb and a split down the middle. The base for tortas and molletes.",
  st:["Mix the flour, yeast, sugar and salt. Add the water and shortening and knead 10 minutes, until smooth.",
      "Cover and rise 1 hour, until doubled.",
      "Divide into 8 pieces. Flatten each, roll up tightly and shape into an oval with tapered ends. Rise 40 minutes.",
      "Slash each roll lengthwise.",
      "Bake at 220 °C for 20 minutes with a tray of water at the bottom of the oven, until golden and hollow-sounding."],
  tp:["Steam from the water in the oven is what gives the thin, crisp crust.",
      "Next day, mist with water and warm for 5 minutes to crisp them again."],
  v:"bolillo recipe"}},

{id:"bunuelos-mexicanos", c:"Mexico", r:"latin-america", m:"sweet", t:90, s:12,
 i:[[400,"g","apflour","structure","harina de trigo","plain flour"],
    [1,"tsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [1,"tbsp","sugar","sweet","azúcar","sugar"],
    [1,"pinch","salt","salt","sal","salt"],
    [1,"","egg","binder","huevo","egg"],
    [40,"g","butter","fat","mantequilla derretida","melted butter"],
    [180,"ml","water","liquid","agua tibia","warm water"],
    [1,"l","oil","fat","aceite para freír","oil for frying"],
    [250,"g","sugar","sweet","piloncillo","piloncillo (unrefined cane sugar)"],
    [500,"ml","water","liquid","agua (segunda parte)","water (second amount)"],
    [2,"","spice","aromatic","ramas de canela","cinnamon sticks"]],
 es:{n:"Buñuelos de rodilla", b:"Discos de masa estirados finísimos, fritos hasta crujir y bañados en almíbar de piloncillo. Postre de posada navideña.",
  st:["Mezcla la harina, el polvo de hornear, el azúcar y la sal. Añade el huevo, la mantequilla y el agua y amasa 5 minutos. Tapa y deja 30 minutos.",
      "Cuece el piloncillo con el agua y la canela 15 minutos, hasta tener un almíbar ligero.",
      "Divide la masa en 12 bolitas. Estira cada una lo más fino posible, hasta que casi se transparente.",
      "Fríe cada disco a 180 °C durante 1 minuto por lado, hasta que esté dorado y crujiente. Escurre sobre papel.",
      "Sirve con la almíbar de piloncillo por encima."],
  tp:["Tradicionalmente se estiran sobre la rodilla cubierta con un paño; así salen finísimos.",
      "Guárdalos sin almíbar en una lata; se bañan justo al servir."],
  v:"buñuelos mexicanos receta"},
 en:{n:"Mexican Buñuelos", b:"Dough rounds stretched paper-thin, fried until crisp and drenched in piloncillo syrup. A Christmas posada dessert.",
  st:["Mix the flour, baking powder, sugar and salt. Add the egg, butter and water and knead 5 minutes. Cover and leave 30 minutes.",
      "Simmer the piloncillo with the water and cinnamon for 15 minutes, to a light syrup.",
      "Divide the dough into 12 balls. Stretch each as thin as possible, until almost see-through.",
      "Fry each round at 180 °C for 1 minute a side, until golden and crisp. Drain on paper.",
      "Serve with the piloncillo syrup poured over."],
  tp:["Traditionally they are stretched over a cloth-covered knee; that's how they get so thin.",
      "Store them unsyruped in a tin; pour the syrup on just before serving."],
  v:"mexican bunuelos recipe"}},

{id:"pastel-de-elote", c:"Mexico", r:"latin-america", m:"sweet", t:60, s:10, o:180,
 i:[[500,"g","corn","structure","granos de elote","sweetcorn kernels","frescos o congelados","fresh or frozen"],
    [395,"g","condensedmilk","sweet","leche condensada","condensed milk"],
    [4,"","egg","set","huevos","eggs"],
    [100,"g","butter","fat","mantequilla derretida","melted butter"],
    [60,"g","cornstarch","structure","fécula de maíz","cornstarch"],
    [2,"tsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [1,"pinch","salt","salt","sal","salt"]],
 es:{n:"Pastel de elote", b:"Pan húmedo de elote licuado con leche condensada. Entre pastel y budín, dulce de maíz.",
  st:["Enciende el horno a 180 °C y engrasa un molde de 22 cm.",
      "Licúa el elote, la leche condensada, los huevos y la mantequilla hasta que esté casi liso.",
      "Añade la fécula, el polvo de hornear y la sal y licúa 10 segundos más.",
      "Vierte en el molde y hornea 45 minutos, hasta que esté dorado y firme en el centro.",
      "Deja enfriar 20 minutos antes de desmoldar."],
  tp:["Con elote fresco sale más húmedo y dulce que con congelado.",
      "Queda como budín firme; no esperes la miga de un bizcocho."],
  v:"pastel de elote receta"},
 en:{n:"Pastel de Elote (Sweetcorn Cake)", b:"A moist cake of blended sweetcorn and condensed milk. Somewhere between cake and pudding.",
  st:["Heat the oven to 180 °C and grease a 22 cm tin.",
      "Blend the corn, condensed milk, eggs and butter until almost smooth.",
      "Add the cornstarch, baking powder and salt and blend 10 seconds more.",
      "Pour into the tin and bake 45 minutes, until golden and firm in the centre.",
      "Cool 20 minutes before turning out."],
  tp:["Fresh corn makes it moister and sweeter than frozen.",
      "It sets like a firm pudding; don't expect the crumb of a sponge."],
  v:"mexican corn cake recipe"}},

{id:"mojo-cubano", c:"Cuba", r:"caribbean", m:"sauce", t:10, s:8,
 i:[[250,"ml","citrus","acid","jugo de naranja agria","sour orange juice"],
    [10,"clove","garlic","aromatic","ajo","garlic"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [120,"ml","oliveoil","fat","aceite de oliva","olive oil"]],
 es:{n:"Mojo criollo cubano", b:"Ajo, naranja agria y aceite caliente. Adobo para el lechón y salsa para la yuca.",
  st:["Maja el ajo con la sal hasta tener una pasta.",
      "Añade el comino, el orégano y el jugo de naranja agria.",
      "Calienta el aceite hasta que brille, sin que humee, y viértelo sobre la mezcla. Chisporroteará.",
      "Mezcla y deja reposar 10 minutos antes de usar."],
  tp:["Sin naranja agria, usa 2 partes de jugo de naranja y 1 de jugo de lima.",
      "Guarda hasta 1 semana en la nevera en un frasco cerrado."],
  v:"mojo criollo cubano receta"},
 en:{n:"Cuban Mojo", b:"Garlic, sour orange and hot oil. A marinade for roast pork and a sauce for cassava.",
  st:["Mash the garlic with the salt to a paste.",
      "Add the cumin, oregano and sour orange juice.",
      "Heat the oil until shimmering, not smoking, and pour it over the mixture. It will sizzle.",
      "Stir and leave 10 minutes before using."],
  tp:["Without sour orange, use 2 parts orange juice to 1 part lime juice.",
      "Keeps up to 1 week in the fridge in a closed jar."],
  v:"cuban mojo recipe"}},

{id:"croquetas-cubanas", c:"Cuba", r:"caribbean", m:"snack", t:240, s:30,
 i:[[60,"g","butter","fat","mantequilla","butter"],
    [1,"","onion","aromatic","cebolla","onion","picada muy fina","very finely chopped"],
    [90,"g","apflour","thicken","harina de trigo","plain flour"],
    [500,"ml","milk","liquid","leche","milk"],
    [300,"g","ham","protein","jamón cocido","cooked ham","molido","minced"],
    [1,"pinch","spice","aromatic","nuez moscada","nutmeg"],
    [1,"pinch","salt","salt","sal","salt"],
    [2,"","egg","binder","huevos batidos","beaten eggs"],
    [150,"g","breadcrumbs","dredge","pan rallado fino","fine breadcrumbs"],
    [1,"l","oil","fat","aceite para freír","oil for frying"]],
 es:{n:"Croquetas de jamón cubanas", b:"Croquetas alargadas de bechamel espesa y jamón molido. En Cuba y Miami se comen a cualquier hora con café.",
  st:["Sofríe la cebolla en la mantequilla 5 minutos. Añade la harina y cuece 2 minutos.",
      "Añade la leche poco a poco, batiendo, y cuece 8 minutos, hasta que la masa se despegue de la olla.",
      "Añade el jamón, la nuez moscada y la sal. Extiende en una fuente, tapa y refrigera 3 horas.",
      "Forma cilindros de 6 cm, pásalos por el huevo y luego por el pan rallado.",
      "Fríe a 180 °C durante 3 minutos, hasta que estén dorados."],
  tp:["Prueba antes de salar: el jamón ya aporta sal.",
      "Congela las croquetas empanizadas en una bandeja y luego en bolsa; fríelas sin descongelar."],
  v:"croquetas de jamon cubanas"},
 en:{n:"Cuban Ham Croquettes", b:"Long croquettes of thick béchamel and minced ham. In Cuba and Miami they're eaten at any hour with coffee.",
  st:["Cook the onion in the butter for 5 minutes. Add the flour and cook 2 minutes.",
      "Add the milk a little at a time, whisking, and cook 8 minutes, until the mixture pulls away from the pot.",
      "Add the ham, nutmeg and salt. Spread in a dish, cover and refrigerate 3 hours.",
      "Shape into 6 cm logs, dip in the egg and then the breadcrumbs.",
      "Fry at 180 °C for 3 minutes, until golden."],
  tp:["Taste before salting: the ham already brings salt.",
      "Freeze crumbed croquettes on a tray, then bag them; fry from frozen."],
  v:"cuban ham croquettes recipe"}},

{id:"tamal-en-cazuela", c:"Cuba", r:"caribbean", m:"main", t:75, s:6,
 i:[[500,"g","pork","protein","carne de cerdo","pork","en dados de 2 cm","in 2 cm dice"],
    [2,"","citrus","acid","naranjas agrias (o 1 naranja y 1 limón)","sour oranges (or 1 orange and 1 lime)","en jugo","juiced"],
    [4,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","ají pimiento verde","green bell pepper","picado","chopped"],
    [200,"g","tomato","sauce","puré de tomate","tomato purée"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [250,"g","cornmeal","structure","harina de maíz amarilla fina","fine yellow cornmeal"],
    [1.5,"l","water","liquid","agua","water"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Tamal en cazuela", b:"Todo el sabor del tamal cubano sin envolver: harina de maíz cocida con cerdo en sofrito, suave como una polenta.",
  st:["Adoba el cerdo con el jugo de naranja, el ajo y 1 cucharadita de sal 30 minutos.",
      "Dora el cerdo escurrido en el aceite 8 minutos. Añade la cebolla y el ají y cuece 5 minutos. Añade el puré de tomate, el comino y la marinada y cuece 5 minutos.",
      "Mezcla la harina de maíz con 500 ml del agua fría hasta que no haya grumos.",
      "Añade el resto del agua y la sal a la olla y hierve. Añade la harina de maíz disuelta, batiendo.",
      "Cuece a fuego bajo 35 minutos, removiendo a menudo, hasta que esté espeso y la harina no sepa cruda."],
  tp:["Disolver la harina en agua fría primero evita los grumos.",
      "Espesa al reposar; si queda muy firme, añade agua caliente al recalentar."],
  v:"tamal en cazuela cubano receta"},
 en:{n:"Tamal en Cazuela (Cuban Cornmeal and Pork Stew)", b:"All the flavour of a Cuban tamal without the wrapping: cornmeal cooked with pork in sofrito, soft like polenta.",
  st:["Season the pork with the orange juice, garlic and 1 teaspoon of salt for 30 minutes.",
      "Brown the drained pork in the oil for 8 minutes. Add the onion and pepper and cook 5 minutes. Add the tomato purée, cumin and marinade and cook 5 minutes.",
      "Mix the cornmeal with 500 ml of the cold water until smooth.",
      "Add the rest of the water and the salt to the pot and bring to a boil. Add the dissolved cornmeal, whisking.",
      "Cook on low for 35 minutes, stirring often, until thick and the cornmeal no longer tastes raw."],
  tp:["Dissolving the cornmeal in cold water first prevents lumps.",
      "It thickens as it stands; if too firm, add hot water when reheating."],
  v:"cuban tamal en cazuela recipe"}},

{id:"boniatillo", c:"Cuba", r:"caribbean", m:"sweet", t:45, s:6,
 i:[[600,"g","veg","structure","boniato (batata blanca)","boniato (white sweet potato)","pelado, en trozos","peeled, in chunks"],
    [250,"g","sugar","sweet","azúcar","sugar"],
    [250,"ml","water","liquid","agua","water"],
    [1,"","spice","aromatic","rama de canela","cinnamon stick"],
    [1,"","citrus","aromatic","cáscara de limón","lime peel","en una tira","in one strip"],
    [2,"","eggyolk","enrich","yemas de huevo","egg yolks"],
    [15,"g","butter","fat","mantequilla","butter"],
    [1,"pinch","salt","salt","sal","salt"],
    [1,"tsp","spice","garnish","canela molida","ground cinnamon"]],
 es:{n:"Boniatillo", b:"Crema dulce de boniato con canela y limón. Un postre cubano de siempre, sencillo y barato.",
  st:["Hierve el boniato en agua 20 minutos, hasta que esté tierno. Escurre y haz un puré fino.",
      "Cuece el azúcar con el agua, la canela y la cáscara de limón 10 minutos, hasta tener un almíbar ligero. Saca la canela y la cáscara.",
      "Añade el puré al almíbar y cuece 10 minutos a fuego bajo, removiendo, hasta que espese.",
      "Retira del fuego, añade las yemas batidas, la mantequilla y la sal, y mezcla rápido. Cuece 2 minutos más sin que hierva.",
      "Sirve frío o tibio con la canela molida por encima."],
  tp:["Añade las yemas fuera del fuego y mezcla rápido para que no cuajen en grumos.",
      "Si lo quieres más firme, cuécelo 5 minutos más antes de las yemas."],
  v:"boniatillo cubano receta"},
 en:{n:"Boniatillo (Cuban Sweet Potato Pudding)", b:"A sweet cream of boniato with cinnamon and lime. An old Cuban dessert, simple and cheap.",
  st:["Boil the boniato in water for 20 minutes, until tender. Drain and mash smooth.",
      "Simmer the sugar with the water, cinnamon and lime peel for 10 minutes, to a light syrup. Remove the cinnamon and peel.",
      "Add the mash to the syrup and cook 10 minutes on low, stirring, until thick.",
      "Off the heat, add the beaten yolks, butter and salt and mix quickly. Cook 2 minutes more without boiling.",
      "Serve cold or warm with the ground cinnamon on top."],
  tp:["Add the yolks off the heat and mix fast so they don't set in lumps.",
      "For a firmer set, cook it 5 minutes longer before the yolks."],
  v:"boniatillo recipe"}}
];
