module.exports = [
{id:"arroz-con-mariscos", c:"Peru", ce:"Perú", r:"latin-america", m:"main", t:45, s:4,
 i:[[3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla roja","red onion","picada","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"tbsp","ajipaste","aromatic","pasta de ají amarillo","ají amarillo paste"],
    [1,"tbsp","ajipaste","aromatic","pasta de ají panca","ají panca paste"],
    [1,"","bellpepper","structure","pimiento rojo","red bell pepper","en dados","diced"],
    [100,"ml","winewhite","liquid","vino blanco","white wine"],
    [300,"g","rice","structure","arroz","rice"],
    [700,"ml","fishstock","liquid","caldo de pescado","fish stock"],
    [250,"g","shrimp","protein","camarones pelados","peeled shrimp"],
    [250,"g","squid","protein","calamares","squid","en anillas","in rings"],
    [300,"g","mussel","protein","choritos (mejillones)","mussels","limpios","cleaned"],
    [100,"g","legume","structure","arvejas","peas"],
    [1,"handful","herb","garnish","cilantro","cilantro","picado","chopped"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"","citrus","garnish","limón","lime","en gajos","in wedges"]],
 es:{n:"Arroz con mariscos", b:"Arroz húmedo y anaranjado de ají, con camarones, calamares y choritos. Un clásico de las cebicherías.",
  st:["Sofríe la cebolla, el ajo y las dos pastas de ají en el aceite 8 minutos.",
      "Añade el pimiento y el vino y cuece 2 minutos.",
      "Añade el arroz, el caldo y la sal. Cuece tapado 15 minutos a fuego bajo.",
      "Añade los camarones, los calamares, los choritos y las arvejas. Tapa y cuece 5 minutos, hasta que los choritos se abran.",
      "Termina con el cilantro y sirve con el limón."],
  tp:["Debe quedar húmedo, no seco como una paella.",
      "Tira los choritos que sigan cerrados."],
  v:"arroz con mariscos peruano receta"},
 en:{n:"Peruvian Arroz con Mariscos (Seafood Rice)", b:"Moist rice, orange with ají, with shrimp, squid and mussels. A cebichería classic.",
  st:["Cook the onion, garlic and both ají pastes in the oil for 8 minutes.",
      "Add the pepper and wine and cook 2 minutes.",
      "Add the rice, stock and salt. Cook covered on low for 15 minutes.",
      "Add the shrimp, squid, mussels and peas. Cover and cook 5 minutes, until the mussels open.",
      "Finish with the cilantro and serve with the lime."],
  tp:["It should be moist, not dry like a paella.",
      "Discard any mussels that stay closed."],
  v:"peruvian seafood rice recipe"}},

{id:"sudado-de-pescado", c:"Peru", ce:"Perú", r:"latin-america", m:"main", t:30, s:4,
 i:[[4,"","whitefish","protein","filetes de pescado blanco firme","firm white fish fillets"],
    [1,"tsp","salt","salt","sal","salt"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla roja","red onion","en gajos gruesos","in thick wedges"],
    [2,"","tomato","sauce","tomates","tomatoes","en gajos","in wedges"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"tbsp","ajipaste","aromatic","pasta de ají amarillo","ají amarillo paste"],
    [1,"","chilli","aromatic","ají amarillo fresco","fresh ají amarillo","en tiras","in strips"],
    [250,"ml","fishstock","liquid","caldo de pescado","fish stock"],
    [1,"handful","herb","garnish","cilantro","cilantro","picado","chopped"],
    [1,"","citrus","acid","limón","lime","en jugo","juiced"]],
 es:{n:"Sudado de pescado", b:"Pescado cocido al vapor sobre cebolla, tomate y ají. Rápido, ligero y muy del norte del Perú.",
  st:["Sala el pescado.",
      "Sofríe el ajo y la pasta de ají en el aceite 2 minutos en una sartén ancha.",
      "Añade la cebolla, el tomate y el ají fresco y cuece 3 minutos.",
      "Pon el pescado encima, añade el caldo, tapa y cuece 8 minutos a fuego medio.",
      "Rocía con el limón, termina con el cilantro y sirve con arroz y yuca."],
  tp:["La cebolla y el tomate deben quedar enteros y algo firmes.",
      "No muevas el pescado mientras se cuece o se rompe."],
  v:"sudado de pescado peruano"},
 en:{n:"Sudado de Pescado (Peruvian Steamed Fish)", b:"Fish steamed over onion, tomato and ají. Quick, light and very northern Peru.",
  st:["Salt the fish.",
      "Cook the garlic and ají paste in the oil for 2 minutes in a wide frying pan.",
      "Add the onion, tomato and fresh ají and cook 3 minutes.",
      "Lay the fish on top, add the stock, cover and cook 8 minutes over medium heat.",
      "Drizzle with the lime, finish with the cilantro and serve with rice and cassava."],
  tp:["The onion and tomato should stay whole and a little firm.",
      "Don't move the fish while it cooks or it breaks."],
  v:"peruvian steamed fish recipe"}},

{id:"jalea", c:"Peru", ce:"Perú", r:"latin-america", m:"main", t:45, s:4,
 i:[[300,"g","whitefish","protein","pescado blanco","white fish","en trozos","in chunks"],
    [200,"g","shrimp","protein","camarones pelados","peeled shrimp"],
    [200,"g","squid","protein","calamares","squid","en anillas","in rings"],
    [2,"tsp","salt","salt","sal","salt"],
    [150,"g","apflour","dredge","harina de trigo","plain flour"],
    [1,"l","oil","fat","aceite para freír","oil for frying"],
    [500,"g","cassava","structure","yuca cocida","boiled cassava","en bastones","in batons"],
    [1,"","onion","garnish","cebolla roja","red onion","en pluma fina","thinly sliced"],
    [1,"","chilli","garnish","ají limo","ají limo","picado","chopped"],
    [2,"","citrus","acid","limones","limes","en jugo","juiced"],
    [1,"handful","herb","garnish","cilantro","cilantro","picado","chopped"]],
 es:{n:"Jalea mixta", b:"Pescado y mariscos fritos crujientes con yuca frita y salsa criolla encima. Para compartir en la mesa.",
  st:["Mezcla la cebolla, el ají, el jugo de limón, el cilantro y 1 cucharadita de sal. Deja reposar.",
      "Fríe la yuca a 180 °C durante 4 minutos, hasta que esté dorada. Escúrrela.",
      "Sala el pescado y los mariscos y pásalos por la harina.",
      "Fríe en tandas a 180 °C durante 2 minutos, hasta que estén dorados.",
      "Sirve el frito sobre la yuca con la salsa criolla por encima."],
  tp:["Fríe en tandas pequeñas para que el aceite no se enfríe.",
      "La salsa criolla se pone al final para que el rebozado siga crujiente."],
  v:"jalea mixta peruana receta"},
 en:{n:"Jalea (Peruvian Fried Seafood Platter)", b:"Crisp fried fish and seafood with fried cassava and salsa criolla on top. For sharing.",
  st:["Mix the onion, ají, lime juice, cilantro and 1 teaspoon of salt. Set aside.",
      "Fry the cassava at 180 °C for 4 minutes, until golden. Drain.",
      "Salt the fish and seafood and coat in the flour.",
      "Fry in batches at 180 °C for 2 minutes, until golden.",
      "Serve the fried seafood over the cassava with the salsa criolla on top."],
  tp:["Fry in small batches so the oil doesn't cool.",
      "The salsa goes on last so the coating stays crisp."],
  v:"jalea peruvian recipe"}},

{id:"ocopa", c:"Peru", ce:"Perú", r:"latin-america", m:"starter", t:40, s:6,
 i:[[3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla roja","red onion","en trozos","in chunks"],
    [2,"clove","garlic","aromatic","ajo","garlic"],
    [3,"tbsp","ajipaste","aromatic","pasta de ají mirasol","ají mirasol paste"],
    [1,"handful","herb","aromatic","hojas de huacatay","huacatay (black mint) leaves"],
    [60,"g","peanut","thicken","maní tostado","roasted peanuts"],
    [150,"g","queso","structure","queso fresco","fresh cheese"],
    [200,"ml","evaporatedmilk","liquid","leche evaporada","evaporated milk"],
    [4,"","crackers","thicken","galletas de soda","soda crackers"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"kg","potato","structure","papas amarillas","yellow potatoes","cocidas, en rodajas","boiled, sliced"],
    [3,"","egg","garnish","huevos duros","hard-boiled eggs","en mitades","halved"],
    [60,"g","olives","garnish","aceitunas negras","black olives"]],
 es:{n:"Ocopa arequipeña", b:"Papas bañadas en una salsa verde de ají mirasol, huacatay, maní y queso. De Arequipa.",
  st:["Sofríe la cebolla, el ajo y la pasta de ají en el aceite 8 minutos.",
      "Añade el huacatay y cuece 1 minuto.",
      "Licúa el sofrito con el maní, el queso, la leche, las galletas y la sal hasta tener una crema espesa.",
      "Pon las papas en una fuente y cúbrelas con la salsa.",
      "Decora con los huevos y las aceitunas."],
  tp:["Ajusta la espesura con más leche o más galletas.",
      "El huacatay se encuentra congelado o en pasta en tiendas latinas."],
  v:"ocopa arequipeña receta"},
 en:{n:"Ocopa (Potatoes in Huacatay Peanut Sauce)", b:"Potatoes covered in a green sauce of ají mirasol, huacatay, peanuts and cheese. From Arequipa.",
  st:["Cook the onion, garlic and ají paste in the oil for 8 minutes.",
      "Add the huacatay and cook 1 minute.",
      "Blend the mixture with the peanuts, cheese, milk, crackers and salt to a thick cream.",
      "Lay the potatoes on a platter and cover with the sauce.",
      "Garnish with the eggs and olives."],
  tp:["Adjust the thickness with more milk or more crackers.",
      "Huacatay is sold frozen or as a paste in Latin shops."],
  v:"ocopa recipe"}},

{id:"cau-cau", c:"Peru", ce:"Perú", r:"latin-america", m:"main", t:150, s:6,
 i:[[1,"kg","beef","protein","mondongo (panza de res)","beef tripe","limpio","cleaned"],
    [2,"l","water","liquid","agua","water"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla roja","red onion","picada","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [3,"tbsp","ajipaste","aromatic","pasta de ají amarillo","ají amarillo paste"],
    [1,"tsp","spice","aromatic","palillo (cúrcuma)","ground turmeric (palillo)"],
    [800,"g","potato","structure","papas blancas","white potatoes","en dados","diced"],
    [100,"g","legume","structure","arvejas","peas"],
    [1,"handful","herb","garnish","hierbabuena","mint","picada","chopped"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Cau cau", b:"Mondongo guisado con papa, ají amarillo, palillo y hierbabuena. Guiso criollo limeño de herencia africana.",
  st:["Cuece el mondongo en el agua con 1 cucharadita de sal 90 minutos, hasta que esté tierno. Córtalo en dados pequeños y guarda 500 ml del agua.",
      "Sofríe la cebolla, el ajo, la pasta de ají y el palillo en el aceite 8 minutos.",
      "Añade el mondongo y el agua reservada y cuece 10 minutos.",
      "Añade las papas, las arvejas y el resto de la sal y cuece 20 minutos, hasta que la papa esté tierna.",
      "Termina con la hierbabuena y sirve con arroz."],
  tp:["Lava el mondongo con limón y sal antes de cocerlo.",
      "Parte de la papa se deshace y espesa el guiso; es lo esperado."],
  v:"cau cau peruano receta"},
 en:{n:"Cau Cau (Peruvian Tripe Stew)", b:"Tripe stewed with potato, ají amarillo, turmeric and mint. A Lima Creole stew with African roots.",
  st:["Simmer the tripe in the water with 1 teaspoon of salt for 90 minutes, until tender. Dice small and keep 500 ml of the water.",
      "Cook the onion, garlic, ají paste and turmeric in the oil for 8 minutes.",
      "Add the tripe and reserved water and cook 10 minutes.",
      "Add the potatoes, peas and the rest of the salt and cook 20 minutes, until tender.",
      "Finish with the mint and serve with rice."],
  tp:["Wash the tripe with lime and salt before cooking.",
      "Some of the potato breaks down and thickens the stew; that's intended."],
  v:"cau cau recipe"}},

{id:"adobo-arequipeno", c:"Peru", ce:"Perú", r:"latin-america", m:"main", t:150, s:6,
 i:[[1.2,"kg","pork","protein","paleta o costilla de cerdo","pork shoulder or ribs","en trozos grandes","in large pieces"],
    [4,"tbsp","ajipaste","aromatic","pasta de ají panca","ají panca paste"],
    [6,"clove","garlic","aromatic","ajo","garlic","molido","crushed"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [100,"ml","winevinegar","acid","vinagre de vino tinto","red wine vinegar"],
    [2,"","onion","aromatic","cebollas rojas","red onions","en gajos gruesos","in thick wedges"],
    [400,"ml","water","liquid","agua","water"],
    [2,"tsp","salt","salt","sal","salt"],
    [6,"","bread","serve","panes de tres puntas o panecillos","three-cornered bread or rolls"]],
 es:{n:"Adobo arequipeño", b:"Cerdo marinado en ají panca y vinagre, cocido con cebolla en gajos. Se toma el domingo temprano con pan.",
  st:["Mezcla la pasta de ají, el ajo, el comino, el orégano, el vinagre y la sal. Marina el cerdo 12 horas.",
      "Pon el cerdo con su marinada en una olla de barro o pesada con la cebolla y el agua.",
      "Tapa y cuece a fuego bajo 2 horas, hasta que la carne esté muy tierna.",
      "Prueba y ajusta la sal.",
      "Sirve en platos hondos con su jugo y el pan para mojar."],
  tp:["La marinada larga es clave: no la acortes.",
      "En Arequipa se usa chicha de jora; el vinagre da un resultado muy parecido."],
  v:"adobo arequipeño receta"},
 en:{n:"Adobo Arequipeño (Arequipa Pork Stew)", b:"Pork marinated in ají panca and vinegar, cooked with onion wedges. An early Sunday meal with bread.",
  st:["Mix the ají paste, garlic, cumin, oregano, vinegar and salt. Marinate the pork 12 hours.",
      "Put the pork and its marinade in a clay or heavy pot with the onion and water.",
      "Cover and cook on low for 2 hours, until very tender.",
      "Taste and adjust the salt.",
      "Serve in deep bowls with its juices and the bread for dipping."],
  tp:["The long marinade is key: don't cut it short.",
      "In Arequipa chicha de jora is used; vinegar gives a very similar result."],
  v:"adobo arequipeno recipe"}},

{id:"sopa-de-quinua", c:"Peru", ce:"Perú", r:"latin-america", m:"soup", t:45, s:6,
 i:[[150,"g","grain","structure","quinua","quinoa","bien lavada","well rinsed"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"tbsp","ajipaste","aromatic","pasta de ají amarillo","ají amarillo paste"],
    [2,"","veg","structure","zanahorias","carrots","en dados","diced"],
    [400,"g","potato","structure","papas","potatoes","en dados","diced"],
    [1.8,"l","stock","liquid","caldo de pollo o de verduras","chicken or vegetable stock"],
    [100,"g","queso","enrich","queso fresco","fresh cheese","en dados","diced"],
    [1,"handful","herb","garnish","huacatay o cilantro","huacatay or cilantro","picado","chopped"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Sopa de quinua", b:"Sopa andina de quinua con papa, zanahoria y queso fresco. Nutritiva y reconfortante.",
  st:["Sofríe la cebolla, el ajo y la pasta de ají en el aceite 5 minutos.",
      "Añade la quinua y tuesta 2 minutos.",
      "Añade el caldo, la zanahoria y la sal y cuece 15 minutos.",
      "Añade la papa y cuece 15 minutos más, hasta que esté tierna.",
      "Añade el queso y la hierba y sirve."],
  tp:["Lava bien la quinua frotándola bajo el agua; la saponina amarga.",
      "Espesa al reposar; añade caldo al recalentar."],
  v:"sopa de quinua peruana"},
 en:{n:"Peruvian Quinoa Soup", b:"An Andean quinoa soup with potato, carrot and fresh cheese. Nourishing and comforting.",
  st:["Cook the onion, garlic and ají paste in the oil for 5 minutes.",
      "Add the quinoa and toast 2 minutes.",
      "Add the stock, carrot and salt and cook 15 minutes.",
      "Add the potato and cook 15 minutes more, until tender.",
      "Add the cheese and herb and serve."],
  tp:["Rinse the quinoa well, rubbing it under the tap; the saponin is bitter.",
      "It thickens on standing; add stock when reheating."],
  v:"peruvian quinoa soup recipe"}},

{id:"caldo-de-gallina-pe", c:"Peru", ce:"Perú", r:"latin-america", m:"soup", t:150, s:6,
 i:[[1.5,"kg","chicken","protein","gallina en presas","boiling hen pieces"],
    [3,"l","water","liquid","agua","water"],
    [1,"tbsp","spice","aromatic","kion (jengibre fresco)","fresh ginger (kion)","en rodajas","sliced"],
    [2,"tsp","salt","salt","sal","salt"],
    [6,"","potato","structure","papas amarillas","yellow potatoes","peladas","peeled"],
    [150,"g","pasta","structure","fideos cabello de ángel o tallarín","angel-hair noodles or tagliatelle"],
    [6,"","egg","protein","huevos duros","hard-boiled eggs","pelados","peeled"],
    [4,"","scallion","garnish","cebolla china","spring onion","picada","chopped"],
    [2,"","citrus","garnish","limones","limes","en gajos","in wedges"]],
 es:{n:"Caldo de gallina", b:"Sopa de gallina con kion, fideos, papa amarilla y huevo duro. Se toma de madrugada en Lima.",
  st:["Cuece la gallina en el agua con el kion y la sal 2 horas, quitando la espuma.",
      "Añade las papas y cuece 15 minutos.",
      "Añade los fideos y cuece 8 minutos.",
      "Reparte en platos hondos con una presa de gallina, una papa y un huevo.",
      "Sirve con la cebolla china y el limón."],
  tp:["La gallina necesita cocción larga; con pollo, 45 minutos bastan.",
      "Cuece los fideos en el caldo justo antes de servir para que no se pasen."],
  v:"caldo de gallina peruano"},
 en:{n:"Caldo de Gallina (Peruvian Hen Soup)", b:"Hen soup with ginger, noodles, yellow potato and hard-boiled egg. Eaten in the early hours in Lima.",
  st:["Simmer the hen in the water with the ginger and salt for 2 hours, skimming.",
      "Add the potatoes and cook 15 minutes.",
      "Add the noodles and cook 8 minutes.",
      "Divide into deep bowls with a piece of hen, a potato and an egg each.",
      "Serve with the spring onion and lime."],
  tp:["A hen needs long cooking; with chicken, 45 minutes is enough.",
      "Cook the noodles in the soup just before serving so they don't go soft."],
  v:"peruvian hen soup recipe"}},

{id:"tallarin-saltado", c:"Peru", ce:"Perú", r:"latin-america", m:"main", t:30, s:4,
 i:[[400,"g","pasta","structure","tallarines o espaguetis","spaghetti"],
    [500,"g","beef","protein","lomo o bistec de res","beef sirloin","en tiras","in strips"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"tbsp","spice","aromatic","kion (jengibre)","ginger (kion)","rallado","grated"],
    [1,"","onion","aromatic","cebolla roja","red onion","en gajos","in wedges"],
    [2,"","tomato","structure","tomates","tomatoes","en gajos","in wedges"],
    [1,"","chilli","aromatic","ají amarillo","ají amarillo","en tiras","in strips"],
    [4,"tbsp","soysauce","umami","sillao (salsa de soja)","soy sauce"],
    [2,"tbsp","oystersauce","umami","salsa de ostión","oyster sauce"],
    [2,"tbsp","winevinegar","acid","vinagre de vino tinto","red wine vinegar"],
    [3,"","scallion","garnish","cebolla china","spring onion","en trozos","in lengths"]],
 es:{n:"Tallarín saltado", b:"Fideos salteados al wok con tiras de res, cebolla, tomate y sillao. Chifa limeño, primo del lomo saltado.",
  st:["Cuece los tallarines en agua con sal y escúrrelos.",
      "Saltea la carne en el wok muy caliente con la mitad del aceite 2 minutos. Sácala.",
      "Saltea el ajo y el kion en el resto del aceite 30 segundos. Añade la cebolla, el tomate y el ají y saltea 2 minutos.",
      "Añade el sillao, la salsa de ostión, el vinagre y la carne.",
      "Añade los tallarines y la cebolla china y saltea 1 minuto, hasta que se impregnen."],
  tp:["El wok debe estar humeando para que la carne se selle sin soltar jugo.",
      "La cebolla y el tomate deben quedar crujientes."],
  v:"tallarín saltado de carne"},
 en:{n:"Tallarín Saltado (Peruvian Stir-Fried Noodles)", b:"Noodles stir-fried with beef strips, onion, tomato and soy. Lima chifa, cousin to lomo saltado.",
  st:["Cook the noodles in salted water and drain.",
      "Stir-fry the beef in a very hot wok with half the oil for 2 minutes. Remove.",
      "Stir-fry the garlic and ginger in the rest of the oil for 30 seconds. Add the onion, tomato and ají and stir-fry 2 minutes.",
      "Add the soy sauce, oyster sauce, vinegar and the beef.",
      "Add the noodles and spring onion and toss 1 minute, until coated."],
  tp:["The wok must be smoking so the meat sears without releasing juice.",
      "The onion and tomato should stay crisp."],
  v:"tallarin saltado recipe"}},

{id:"turron-de-dona-pepa", c:"Peru", ce:"Perú", r:"latin-america", m:"sweet", t:120, s:16, o:180,
 i:[[500,"g","apflour","structure","harina de trigo","plain flour"],
    [1,"tsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [250,"g","butter","fat","mantequilla","butter"],
    [4,"","eggyolk","binder","yemas de huevo","egg yolks"],
    [1,"tbsp","spice","aromatic","anís en grano","aniseed"],
    [100,"ml","water","liquid","agua de anís tibia","warm aniseed tea"],
    [500,"g","jaggery","sweet","chancaca","chancaca (unrefined cane sugar)"],
    [300,"ml","water","liquid","agua","water"],
    [1,"","citrus","aromatic","cáscara de naranja","orange peel"],
    [2,"","spice","aromatic","ramas de canela y clavos","cinnamon sticks and cloves"],
    [50,"g","sprinkles","garnish","grageas de colores","coloured sprinkles"]],
 es:{n:"Turrón de Doña Pepa", b:"Palitos de masa de anís en capas con miel de chancaca y grageas. El dulce del mes morado en Lima.",
  st:["Mezcla la harina, el polvo de hornear y el anís. Añade la mantequilla, las yemas y el agua de anís y junta la masa sin amasar.",
      "Forma palitos de 1 cm de grosor y 20 cm de largo. Hornea a 180 °C durante 15 minutos.",
      "Cuece la chancaca con el agua, la naranja, la canela y los clavos 30 minutos, hasta tener un almíbar espeso. Cuela.",
      "En una fuente, pon una capa de palitos, báñala con almíbar y repite 3 capas.",
      "Termina con almíbar y las grageas. Deja reposar 2 horas antes de cortar."],
  tp:["El almíbar está listo cuando una gota en agua fría forma una bolita blanda.",
      "Se guarda 1 semana tapado a temperatura ambiente."],
  v:"turrón de doña pepa receta"},
 en:{n:"Turrón de Doña Pepa (Peruvian Anise Layer Sweet)", b:"Anise pastry sticks layered with chancaca syrup and sprinkles. The sweet of Lima's purple month.",
  st:["Mix the flour, baking powder and aniseed. Add the butter, yolks and aniseed tea and bring together without kneading.",
      "Shape into sticks 1 cm thick and 20 cm long. Bake at 180 °C for 15 minutes.",
      "Simmer the chancaca with the water, orange, cinnamon and cloves for 30 minutes, to a thick syrup. Strain.",
      "In a dish, lay a layer of sticks, pour over syrup and repeat for 3 layers.",
      "Finish with syrup and the sprinkles. Leave 2 hours before cutting."],
  tp:["The syrup is ready when a drop in cold water forms a soft ball.",
      "Keeps 1 week covered at room temperature."],
  v:"turron de dona pepa recipe"}}
];
