module.exports = [
{id:"aguadito-de-pollo", c:"Peru", r:"latin-america", m:"soup", t:60, s:6,
 i:[[1,"kg","chicken","protein","pollo en presas","chicken pieces"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla roja","red onion","picada","chopped"],
    [4,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [3,"tbsp","ajipaste","aromatic","ají amarillo molido","ají amarillo paste"],
    [2,"bunch","herb","aromatic","culantro (cilantro)","coriander","licuado con 250 ml de agua","blended with 250 ml water"],
    [2,"l","water","liquid","agua","water"],
    [200,"g","rice","structure","arroz","rice"],
    [1,"","bellpepper","aromatic","pimiento rojo","red bell pepper","en tiras","in strips"],
    [1,"","veg","structure","zanahoria","carrot","en dados","diced"],
    [150,"g","legume","structure","arvejas","green peas"],
    [150,"g","corn","structure","granos de choclo","corn kernels"],
    [4,"","potato","structure","papas amarillas","yellow potatoes","en trozos","in chunks"],
    [2,"tsp","salt","salt","sal","salt"],
    [2,"","citrus","acid","limones","limes"]],
 es:{n:"Aguadito de pollo", b:"Sopa verde de arroz con pollo y mucho culantro. Levanta muertos en Lima después de una fiesta.",
  st:["Sala el pollo y dóralo en el aceite 8 minutos. Sácalo.",
      "Sofríe la cebolla, el ajo y el ají 6 minutos. Añade el culantro licuado y cocina 3 minutos.",
      "Añade el agua y el pollo y cuece 20 minutos.",
      "Añade el arroz, la papa, la zanahoria y el pimiento y cuece 15 minutos.",
      "Añade las arvejas y el choclo, cuece 5 minutos más y sala. Sirve con limón."],
  tp:["Licúa el culantro con agua fría para que se mantenga bien verde.",
      "Debe quedar caldoso: añade agua si el arroz absorbe mucho."],
  v:"aguadito de pollo peruano"},
 en:{n:"Aguadito de Pollo (Peruvian Green Chicken Soup)", b:"A green rice soup with chicken and lots of coriander. Lima's cure after a party.",
  st:["Salt the chicken and brown it in the oil for 8 minutes. Remove.",
      "Cook the onion, garlic and ají for 6 minutes. Add the blended coriander and cook 3 minutes.",
      "Add the water and chicken and simmer 20 minutes.",
      "Add the rice, potato, carrot and pepper and cook 15 minutes.",
      "Add the peas and corn, cook 5 minutes more and salt. Serve with lime."],
  tp:["Blend the coriander with cold water so it stays bright green.",
      "It should be brothy: add water if the rice drinks too much."],
  v:"peruvian aguadito de pollo"}},

{id:"estofado-de-pollo-pe", c:"Peru", r:"latin-america", m:"main", t:60, s:4,
 i:[[1,"kg","chicken","protein","pollo en presas","chicken pieces"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla roja","red onion","picada","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"tbsp","ajipaste","aromatic","ají panca molido","ají panca paste"],
    [3,"","tomato","liquid","tomates","tomatoes","licuados","blended"],
    [1,"leaf","herb","aromatic","laurel","bay leaf"],
    [150,"ml","winered","liquid","vino tinto","red wine"],
    [250,"ml","water","liquid","agua","water"],
    [2,"","veg","structure","zanahorias","carrots","en rodajas","sliced"],
    [4,"","potato","structure","papas","potatoes","en mitades","halved"],
    [150,"g","legume","structure","arvejas","green peas"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Estofado de pollo", b:"Pollo guisado en tomate, ají panca y vino, con papas y arvejas. El almuerzo de casa peruano.",
  st:["Sala el pollo y dóralo en el aceite 8 minutos. Sácalo.",
      "Sofríe la cebolla, el ajo y el ají panca 6 minutos. Añade el tomate y cocina 8 minutos.",
      "Añade el vino, el laurel, el agua y el pollo. Tapa y cuece 20 minutos.",
      "Añade la zanahoria y las papas y cuece 15 minutos.",
      "Añade las arvejas, cuece 5 minutos y sala."],
  tp:["Sírvelo con arroz blanco.",
      "Si la salsa está ácida, deja reducir un poco más."],
  v:"estofado de pollo peruano"},
 en:{n:"Peruvian Chicken Estofado", b:"Chicken stewed in tomato, ají panca and wine, with potatoes and peas. Peruvian home lunch.",
  st:["Salt the chicken and brown it in the oil for 8 minutes. Remove.",
      "Cook the onion, garlic and ají panca for 6 minutes. Add the tomato and cook 8 minutes.",
      "Add the wine, bay, water and chicken. Cover and simmer 20 minutes.",
      "Add the carrots and potatoes and cook 15 minutes.",
      "Add the peas, cook 5 minutes and salt."],
  tp:["Serve with white rice.",
      "If the sauce tastes sharp, reduce it a little longer."],
  v:"peruvian chicken estofado"}},

{id:"pepian-de-choclo", c:"Peru", r:"latin-america", m:"main", t:50, s:4,
 i:[[6,"","corn","structure","choclos","corn cobs","desgranados y rallados","kernels grated off"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla roja","red onion","picada","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"tbsp","ajipaste","aromatic","ají amarillo molido","ají amarillo paste"],
    [400,"ml","water","liquid","agua","water"],
    [1,"handful","herb","aromatic","albahaca","basil","picada","chopped"],
    [1,"tsp","salt","salt","sal","salt"],
    [4,"thigh","chicken","protein","muslos de pollo","chicken thighs"]],
 es:{n:"Pepián de choclo", b:"Crema espesa de choclo rallado con ají amarillo y albahaca, con pollo. Plato criollo de la costa peruana.",
  st:["Sala el pollo y dóralo en 1 cucharada de aceite 10 minutos. Añade 150 ml de agua, tapa y cuece 20 minutos.",
      "Sofríe la cebolla, el ajo y el ají en el resto del aceite 6 minutos.",
      "Añade el choclo rallado y el resto del agua y cuece 15 minutos, removiendo, hasta que espese.",
      "Añade la albahaca y la sal.",
      "Sirve el pepián con el pollo encima."],
  tp:["Remueve sin parar: el choclo se pega fácil.",
      "Debe quedar como un puré suave."],
  v:"pepián de choclo con pollo"},
 en:{n:"Pepián de Choclo (Peruvian Creamed Corn)", b:"A thick cream of grated corn with ají amarillo and basil, served with chicken. A creole dish of the Peruvian coast.",
  st:["Salt the chicken and brown it in 1 tablespoon of oil for 10 minutes. Add 150 ml of water, cover and cook 20 minutes.",
      "Cook the onion, garlic and ají in the rest of the oil for 6 minutes.",
      "Add the grated corn and the rest of the water and cook 15 minutes, stirring, until thick.",
      "Add the basil and salt.",
      "Serve the pepián with the chicken on top."],
  tp:["Stir constantly: corn catches easily.",
      "It should look like a soft mash."],
  v:"peruvian pepian de choclo"}},

{id:"queso-helado", c:"Peru", r:"latin-america", m:"sweet", t:30, s:8,
 i:[[500,"ml","milk","liquid","leche entera","whole milk"],
    [400,"ml","evaporatedmilk","liquid","leche evaporada","evaporated milk"],
    [400,"g","condensedmilk","sweet","leche condensada","condensed milk"],
    [80,"g","desiccatedcoconut","aromatic","coco rallado","desiccated coconut"],
    [4,"piece","spice","aromatic","clavos de olor","cloves"],
    [2,"piece","spice","aromatic","ramas de canela","cinnamon sticks"],
    [1,"tsp","vanilla","aromatic","esencia de vainilla","vanilla extract"],
    [1,"tsp","spice","garnish","canela molida","ground cinnamon"]],
 es:{n:"Queso helado", b:"Helado arequipeño de leche con coco, canela y clavo. No lleva queso: se llama así por su forma.",
  st:["Hierve la leche con la canela y el clavo 10 minutos. Cuela y deja enfriar.",
      "Mezcla con la leche evaporada, la condensada, el coco y la vainilla.",
      "Congela en un recipiente 4 horas, batiendo cada 45 minutos para romper los cristales.",
      "Sirve en bolas con canela molida."],
  tp:["Si tienes heladera, úsala: queda más cremoso.",
      "Sácalo 10 minutos antes de servir para que se ablande."],
  v:"queso helado arequipeño"},
 en:{n:"Queso Helado (Arequipa Coconut Ice Cream)", b:"Arequipa's milk ice cream with coconut, cinnamon and clove. There's no cheese in it: it's named for its shape.",
  st:["Boil the milk with the cinnamon and cloves for 10 minutes. Strain and cool.",
      "Mix with the evaporated milk, condensed milk, coconut and vanilla.",
      "Freeze in a tub for 4 hours, whisking every 45 minutes to break up the crystals.",
      "Serve in scoops with ground cinnamon."],
  tp:["If you have an ice-cream maker, use it: it's creamier.",
      "Take it out 10 minutes before serving to soften."],
  v:"peruvian queso helado"}},

{id:"emoliente", c:"Peru", r:"latin-america", m:"drink", t:40, s:6,
 i:[[60,"g","barley","structure","cebada tostada","toasted barley"],
    [2,"tbsp","flax","thicken","linaza","flaxseed"],
    [2,"l","water","liquid","agua","water"],
    [1,"handful","herb","aromatic","cola de caballo seca","dried horsetail"],
    [1,"handful","herb","aromatic","manzanilla seca","dried chamomile"],
    [100,"g","sugar","sweet","azúcar","sugar"],
    [3,"","citrus","acid","limones","limes","exprimidos","juiced"]],
 es:{n:"Emoliente", b:"Bebida caliente de cebada, linaza y hierbas, vendida en carritos en las esquinas de Lima desde la madrugada.",
  st:["Hierve la cebada en el agua 20 minutos.",
      "Añade la linaza y cuece 10 minutos, hasta que el líquido se ponga algo espeso.",
      "Añade las hierbas, apaga y deja reposar 5 minutos. Cuela.",
      "Endulza con el azúcar y añade el limón al servir."],
  tp:["Se toma caliente en invierno y frío en verano.",
      "La linaza le da la textura suave típica: no la omitas."],
  v:"emoliente peruano"},
 en:{n:"Emoliente (Peruvian Barley Herbal Drink)", b:"A hot drink of barley, flaxseed and herbs, sold from carts on Lima's street corners from dawn.",
  st:["Boil the barley in the water for 20 minutes.",
      "Add the flaxseed and cook 10 minutes, until the liquid thickens slightly.",
      "Add the herbs, turn off and steep 5 minutes. Strain.",
      "Sweeten with the sugar and add the lime when serving."],
  tp:["Drink it hot in winter and cold in summer.",
      "The flaxseed gives its typical silky body: don't skip it."],
  v:"peruvian emoliente drink"}},

{id:"choritos-a-la-chalaca", c:"Peru", r:"latin-america", m:"starter", t:30, s:4,
 i:[[24,"","mussel","protein","choros (mejillones)","mussels"],
    [250,"ml","water","liquid","agua","water"],
    [1,"","onion","aromatic","cebolla roja","red onion","picada fina","finely chopped"],
    [2,"","tomato","aromatic","tomates","tomatoes","sin semillas, picados finos","seeded, finely chopped"],
    [1,"","chilli","aromatic","rocoto","rocoto chilli","picado fino","finely chopped"],
    [100,"g","corn","structure","granos de choclo cocidos","cooked corn kernels"],
    [1,"handful","herb","aromatic","culantro (cilantro)","coriander","picado","chopped"],
    [4,"","citrus","acid","limones","limes","exprimidos","juiced"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Choritos a la chalaca", b:"Mejillones cubiertos de una salsa fresca de cebolla, tomate, rocoto y limón. Un clásico del Callao.",
  st:["Cuece los choros en el agua tapados 5 minutos, hasta que se abran. Deja enfriar.",
      "Retira una concha de cada choro y deja la carne en la otra.",
      "Mezcla la cebolla, el tomate, el rocoto, el choclo, el culantro, el limón y la sal.",
      "Cubre cada choro con la mezcla y sirve frío."],
  tp:["Tira los choros que no se abran.",
      "Prepara la mezcla justo antes de servir para que la cebolla quede crujiente."],
  v:"choritos a la chalaca"},
 en:{n:"Choritos a la Chalaca (Callao-Style Mussels)", b:"Mussels topped with a fresh salsa of onion, tomato, rocoto and lime. A classic from Callao.",
  st:["Steam the mussels in the water, covered, for 5 minutes, until they open. Cool.",
      "Remove one shell from each mussel, leaving the meat in the other.",
      "Mix the onion, tomato, rocoto, corn, coriander, lime and salt.",
      "Spoon the mix over each mussel and serve cold."],
  tp:["Discard any mussels that don't open.",
      "Mix the topping just before serving so the onion stays crisp."],
  v:"peruvian mussels a la chalaca"}},

{id:"chicharron-de-pescado", c:"Peru", r:"latin-america", m:"main", t:30, s:4,
 i:[[600,"g","whitefish","protein","pescado blanco firme","firm white fish","en trozos de 3 cm","in 3 cm chunks"],
    [3,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [2,"","citrus","acid","limones","limes","exprimidos","juiced"],
    [1,"tsp","salt","salt","sal","salt"],
    [100,"g","apflour","dredge","harina de trigo","plain flour"],
    [50,"g","cornstarch","dredge","maicena","cornflour"],
    [750,"ml","oil","fat","aceite para freír","oil for frying"]],
 es:{n:"Chicharrón de pescado", b:"Trozos de pescado marinados en ajo y limón, enharinados y fritos hasta quedar crujientes. Infaltable en las cevicherías.",
  st:["Marina el pescado con el ajo, la mitad del limón y la sal 15 minutos.",
      "Mezcla la harina con la maicena y pasa el pescado por la mezcla.",
      "Fríe a 180 °C en tandas 4 minutos, hasta que esté dorado.",
      "Escurre y sirve con el resto del limón."],
  tp:["No llenes la olla: el aceite pierde temperatura y el pescado queda aceitoso.",
      "La maicena lo hace más crujiente."],
  v:"chicharrón de pescado peruano"},
 en:{n:"Chicharrón de Pescado (Peruvian Fried Fish)", b:"Fish chunks marinated in garlic and lime, floured and fried until crisp. A cevichería essential.",
  st:["Marinate the fish with the garlic, half the lime juice and the salt for 15 minutes.",
      "Mix the flour and cornflour and dredge the fish.",
      "Fry at 180 °C in batches for 4 minutes, until golden.",
      "Drain and serve with the rest of the lime."],
  tp:["Don't crowd the pot: the oil cools and the fish turns greasy.",
      "The cornflour makes it crisper."],
  v:"peruvian fried fish chicharron"}},

{id:"arroz-con-pato", c:"Peru", r:"latin-america", m:"main", t:120, s:6,
 i:[[6,"thigh","duck","protein","piernas de pato","duck legs"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla roja","red onion","picada","chopped"],
    [4,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"tbsp","ajipaste","aromatic","ají amarillo molido","ají amarillo paste"],
    [2,"bunch","herb","aromatic","culantro (cilantro)","coriander","licuado con 250 ml de agua","blended with 250 ml water"],
    [350,"ml","beer","liquid","cerveza negra","dark beer"],
    [1,"l","water","liquid","agua","water"],
    [500,"g","rice","structure","arroz","rice"],
    [150,"g","legume","structure","arvejas","green peas"],
    [1,"","bellpepper","garnish","pimiento rojo","red bell pepper","en tiras","in strips"],
    [3,"tsp","salt","salt","sal","salt"]],
 es:{n:"Arroz con pato", b:"Arroz verde de culantro y cerveza negra con pato tierno. El orgullo de Chiclayo.",
  st:["Sala el pato y dóralo en el aceite con la piel hacia abajo 10 minutos. Sácalo.",
      "Sofríe la cebolla, el ajo y el ají en la grasa 6 minutos. Añade el culantro licuado y cocina 5 minutos.",
      "Añade la cerveza, el agua y el pato. Tapa y cuece 60 minutos, hasta que esté tierno. Saca el pato.",
      "Mide 1 l del caldo, añade el arroz y cuece tapado 18 minutos.",
      "Añade las arvejas y el pimiento, tapa 5 minutos y sirve con el pato encima."],
  tp:["Quita el exceso de grasa del pato antes de añadir el arroz.",
      "Algunos marinan el pato la noche anterior con ajo y cerveza."],
  v:"arroz con pato chiclayano"},
 en:{n:"Arroz con Pato (Peruvian Duck with Coriander Rice)", b:"Green coriander and dark-beer rice with tender duck. Chiclayo's pride.",
  st:["Salt the duck and brown it skin side down in the oil for 10 minutes. Remove.",
      "Cook the onion, garlic and ají in the fat for 6 minutes. Add the blended coriander and cook 5 minutes.",
      "Add the beer, water and duck. Cover and simmer 60 minutes, until tender. Lift out the duck.",
      "Measure 1 l of the broth, add the rice and cook covered for 18 minutes.",
      "Add the peas and pepper, cover 5 minutes and serve with the duck on top."],
  tp:["Skim off excess duck fat before adding the rice.",
      "Some cooks marinate the duck overnight in garlic and beer."],
  v:"peruvian arroz con pato"}},

{id:"frejol-colado", c:"Peru", r:"latin-america", m:"sweet", t:180, s:10,
 i:[[500,"g","legume","structure","frejol canario o negro","canary or black beans"],
    [2,"l","water","liquid","agua","water"],
    [500,"g","brownsugar","sweet","chancaca","chancaca (unrefined cane sugar)"],
    [400,"ml","evaporatedmilk","liquid","leche evaporada","evaporated milk"],
    [6,"piece","spice","aromatic","clavos de olor","cloves"],
    [2,"piece","spice","aromatic","ramas de canela","cinnamon sticks"],
    [2,"tbsp","sesameseed","garnish","ajonjolí tostado","toasted sesame seeds"]],
 es:{n:"Frejol colado", b:"Dulce espeso de frejol colado con chancaca y clavo, cubierto de ajonjolí. Tradición afroperuana de Chincha.",
  st:["Remoja el frejol 12 horas. Cuécelo en el agua 90 minutos, hasta que esté muy tierno.",
      "Licúa y cuela para quitar las pieles.",
      "Cuece el puré con la chancaca, la leche, el clavo y la canela 45 minutos, removiendo sin parar, hasta ver el fondo de la olla.",
      "Retira la canela y el clavo, pasa a una fuente y cubre con el ajonjolí."],
  tp:["Usa una cuchara de palo larga: salpica mucho al espesar.",
      "Se conserva 1 semana en la nevera."],
  v:"frejol colado chinchano"},
 en:{n:"Frejol Colado (Peruvian Sweet Bean Fudge)", b:"A thick sweet of sieved beans with cane sugar and clove, topped with sesame. An Afro-Peruvian tradition from Chincha.",
  st:["Soak the beans 12 hours. Simmer them in the water for 90 minutes, until very soft.",
      "Blend and sieve to remove the skins.",
      "Cook the purée with the cane sugar, milk, cloves and cinnamon for 45 minutes, stirring constantly, until you can see the bottom of the pan.",
      "Remove the cinnamon and cloves, spread in a dish and top with the sesame."],
  tp:["Use a long wooden spoon: it spits as it thickens.",
      "It keeps 1 week in the fridge."],
  v:"peruvian frejol colado"}},

{id:"pollo-saltado", c:"Peru", r:"latin-america", m:"main", t:30, s:4,
 i:[[600,"g","chicken","protein","pechuga de pollo","chicken breast","en tiras","in strips"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla roja","red onion","en gajos","in wedges"],
    [3,"","tomato","aromatic","tomates","tomatoes","en gajos","in wedges"],
    [1,"","chilli","aromatic","ají amarillo fresco","fresh ají amarillo","en tiras","in strips"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [3,"tbsp","soysauce","umami","sillao (salsa de soja)","soy sauce"],
    [2,"tbsp","winevinegar","acid","vinagre de vino tinto","red wine vinegar"],
    [1,"handful","herb","garnish","culantro (cilantro)","coriander","picado","chopped"],
    [1,"pinch","pepper","aromatic","pimienta","pepper"]],
 es:{n:"Pollo saltado", b:"El hermano del lomo saltado: pollo al wok con cebolla, tomate, ají y sillao. Cocina chifa peruana.",
  st:["Calienta el wok a fuego muy fuerte con 2 cucharadas de aceite y saltea el pollo 4 minutos. Sácalo.",
      "Añade el resto del aceite y saltea la cebolla, el ajo y el ají 1 minuto.",
      "Añade el tomate y el pollo y saltea 1 minuto.",
      "Añade el sillao y el vinagre por el borde del wok, mezcla y termina con el culantro y la pimienta."],
  tp:["El wok debe humear: el saltado se hace en segundos.",
      "Sírvelo con arroz blanco."],
  v:"pollo saltado peruano"},
 en:{n:"Pollo Saltado (Peruvian Chicken Stir-Fry)", b:"Lomo saltado's sibling: wok-fried chicken with onion, tomato, ají and soy sauce. Peruvian chifa cooking.",
  st:["Heat the wok on very high heat with 2 tablespoons of oil and stir-fry the chicken 4 minutes. Remove.",
      "Add the rest of the oil and stir-fry the onion, garlic and ají for 1 minute.",
      "Add the tomato and chicken and toss 1 minute.",
      "Pour the soy sauce and vinegar around the edge of the wok, toss and finish with the coriander and pepper."],
  tp:["The wok should smoke: a saltado takes seconds.",
      "Serve with white rice."],
  v:"peruvian chicken saltado"}}
];
