module.exports = [
{id:"sopa-seca-chinchana", c:"Peru", r:"latin-america", m:"main", t:60, s:6,
 i:[[3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla roja","red onion","picada","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"tbsp","ajipaste","aromatic","ají panca molido","ají panca paste"],
    [1,"bunch","herb","aromatic","albahaca","basil"],
    [1,"handful","herb","aromatic","culantro (cilantro)","coriander"],
    [2,"","tomato","liquid","tomates","tomatoes"],
    [1,"l","water","liquid","agua","water"],
    [500,"g","pasta","structure","tallarines","spaghetti"],
    [4,"thigh","chicken","protein","muslos de pollo","chicken thighs"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Sopa seca chinchana", b:"Tallarines cocidos en una salsa de albahaca, culantro y ají panca hasta absorberla. Se sirve con carapulcra en Chincha.",
  st:["Licúa la albahaca, el culantro y el tomate con un poco del agua.",
      "Dora el pollo en el aceite 8 minutos. Sácalo.",
      "Sofríe la cebolla, el ajo y el ají 6 minutos. Añade lo licuado y cocina 5 minutos.",
      "Añade el agua, la sal y el pollo y hierve. Añade los tallarines crudos partidos y cuece 15 minutos, removiendo, hasta que absorban el líquido."],
  tp:["Debe quedar seca, sin caldo: de ahí el nombre.",
      "Remueve a menudo al final para que no se pegue."],
  v:"sopa seca chinchana"},
 en:{n:"Sopa Seca (Peruvian Basil Noodles)", b:"Spaghetti cooked in a basil, coriander and ají panca sauce until it's all absorbed. Served with carapulcra in Chincha.",
  st:["Blend the basil, coriander and tomato with a little of the water.",
      "Brown the chicken in the oil for 8 minutes. Remove.",
      "Cook the onion, garlic and ají for 6 minutes. Add the blended herbs and cook 5 minutes.",
      "Add the water, salt and chicken and bring to the boil. Add the broken raw spaghetti and cook 15 minutes, stirring, until the liquid is absorbed."],
  tp:["It should end up dry, with no broth: hence the name.",
      "Stir often at the end so it doesn't stick."],
  v:"peruvian sopa seca"}},

{id:"escabeche-de-pescado", c:"Peru", r:"latin-america", m:"main", t:50, s:4,
 i:[[4,"fillet","whitefish","protein","filetes de pescado blanco (bonito o corvina)","white fish fillets"],
    [60,"g","apflour","dredge","harina de trigo","plain flour"],
    [150,"ml","oil","fat","aceite","oil"],
    [3,"","onion","aromatic","cebollas rojas","red onions","en gajos gruesos","in thick wedges"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"tbsp","ajipaste","aromatic","ají panca molido","ají panca paste"],
    [1,"","chilli","aromatic","ají amarillo fresco","fresh ají amarillo","en tiras","in strips"],
    [100,"ml","winevinegar","acid","vinagre de vino tinto","red wine vinegar"],
    [1,"tsp","spice","aromatic","comino","cumin"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [2,"tsp","salt","salt","sal","salt"],
    [2,"","egg","garnish","huevos duros","hard-boiled eggs","en rodajas","sliced"],
    [6,"","olives","garnish","aceitunas de botija","Peruvian black olives"]],
 es:{n:"Escabeche de pescado", b:"Pescado frito cubierto con cebolla en vinagre y ají, con huevo y aceituna. Plato de Semana Santa en Lima.",
  st:["Sala el pescado, pásalo por la harina y fríelo en el aceite 3 minutos por lado. Reserva.",
      "Sofríe el ajo, el ají panca, el comino y el orégano en 3 cucharadas del aceite 2 minutos.",
      "Añade la cebolla y el ají amarillo y cocina 3 minutos: la cebolla debe quedar crujiente.",
      "Añade el vinagre y el resto de la sal y hierve 1 minuto.",
      "Cubre el pescado con el escabeche y decora con el huevo y las aceitunas."],
  tp:["Se sirve tibio o frío: está mejor tras reposar 1 hora.",
      "No cocines de más la cebolla."],
  v:"escabeche de pescado peruano"},
 en:{n:"Peruvian Escabeche de Pescado", b:"Fried fish topped with onions in vinegar and ají, with egg and olive. A Holy Week dish in Lima.",
  st:["Salt the fish, dredge in the flour and fry in the oil for 3 minutes per side. Set aside.",
      "Cook the garlic, ají panca, cumin and oregano in 3 tablespoons of the oil for 2 minutes.",
      "Add the onion and ají amarillo and cook 3 minutes: the onion should stay crisp.",
      "Add the vinegar and remaining salt and boil 1 minute.",
      "Spoon the escabeche over the fish and garnish with the egg and olives."],
  tp:["Serve warm or cold: it's better after resting 1 hour.",
      "Don't overcook the onion."],
  v:"peruvian fish escabeche"}},

{id:"tallarines-rojos", c:"Peru", r:"latin-america", m:"main", t:60, s:4,
 i:[[4,"thigh","chicken","protein","presas de pollo","chicken pieces"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla roja","red onion","picada","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"tbsp","ajipaste","aromatic","ají panca molido","ají panca paste"],
    [5,"","tomato","liquid","tomates","tomatoes","licuados","blended"],
    [1,"","veg","aromatic","zanahoria","carrot","rallada","grated"],
    [1,"leaf","herb","aromatic","laurel","bay leaf"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [2,"tsp","salt","salt","sal","salt"],
    [400,"g","pasta","structure","tallarines","spaghetti"],
    [50,"g","parmesan","garnish","queso parmesano rallado","grated parmesan"]],
 es:{n:"Tallarines rojos con pollo", b:"Tallarines con salsa de tomate, ají panca y pollo guisado. Almuerzo de domingo en muchas casas peruanas.",
  st:["Sala el pollo y dóralo en el aceite 8 minutos. Sácalo.",
      "Sofríe la cebolla, el ajo, el ají y la zanahoria 8 minutos.",
      "Añade el tomate, el laurel, el orégano, el resto de la sal y el pollo. Cuece tapado 35 minutos.",
      "Cuece los tallarines en agua con sal según el paquete.",
      "Mezcla con la salsa y sirve con el pollo y el queso."],
  tp:["La zanahoria rallada quita la acidez al tomate.",
      "Si la salsa espesa demasiado, añade un poco del agua de la pasta."],
  v:"tallarines rojos peruanos"},
 en:{n:"Tallarines Rojos (Peruvian Red Spaghetti)", b:"Spaghetti in tomato and ají panca sauce with braised chicken. Sunday lunch in many Peruvian homes.",
  st:["Salt the chicken and brown it in the oil for 8 minutes. Remove.",
      "Cook the onion, garlic, ají and carrot for 8 minutes.",
      "Add the tomato, bay, oregano, remaining salt and the chicken. Cover and simmer 35 minutes.",
      "Cook the spaghetti in salted water as the packet says.",
      "Toss with the sauce and serve with the chicken and cheese."],
  tp:["The grated carrot takes the edge off the tomato's acidity.",
      "If the sauce gets too thick, add a little pasta water."],
  v:"peruvian red spaghetti chicken"}},

{id:"ranfanote", c:"Peru", r:"latin-america", m:"sweet", t:40, s:6,
 i:[[300,"g","bread","structure","pan francés del día anterior","day-old French bread","en cubos y tostado","cubed and toasted"],
    [400,"g","brownsugar","sweet","chancaca","chancaca (unrefined cane sugar)"],
    [400,"ml","water","liquid","agua","water"],
    [1,"piece","spice","aromatic","rama de canela","cinnamon stick"],
    [4,"piece","spice","aromatic","clavos de olor","cloves"],
    [60,"g","walnut","crunch","nueces","walnuts","picadas","chopped"],
    [60,"g","driedfruit","sweet","pasas","raisins"],
    [60,"g","desiccatedcoconut","crunch","coco rallado","desiccated coconut"],
    [80,"g","queso","garnish","queso fresco","queso fresco","en cubos","cubed"]],
 es:{n:"Ranfañote", b:"Pan tostado bañado en miel de chancaca con nueces, pasas, coco y queso fresco. Postre afroperuano de la vieja Lima.",
  st:["Hierve la chancaca con el agua, la canela y el clavo 15 minutos, hasta tener una miel.",
      "Cuela y deja entibiar.",
      "Mezcla el pan con las nueces, las pasas y el coco en una fuente.",
      "Baña con la miel tibia y añade el queso.",
      "Sirve de inmediato."],
  tp:["Tuesta bien el pan para que no se deshaga con la miel.",
      "El queso salado equilibra el dulzor."],
  v:"ranfañote limeño"},
 en:{n:"Ranfañote (Peruvian Bread Pudding in Cane Syrup)", b:"Toasted bread soaked in cane-sugar syrup with walnuts, raisins, coconut and fresh cheese. An Afro-Peruvian dessert from old Lima.",
  st:["Boil the chancaca with the water, cinnamon and cloves for 15 minutes, into a syrup.",
      "Strain and let it cool slightly.",
      "Mix the bread with the walnuts, raisins and coconut in a dish.",
      "Pour over the warm syrup and add the cheese.",
      "Serve at once."],
  tp:["Toast the bread well so it doesn't fall apart in the syrup.",
      "The salty cheese balances the sweetness."],
  v:"peruvian ranfanote"}},

{id:"tamal-criollo", c:"Peru", r:"latin-america", m:"main", t:180, s:10,
 i:[[1,"kg","hominy","structure","maíz blanco pelado (mote)","hulled white corn"],
    [200,"g","lard","fat","manteca de cerdo","lard"],
    [4,"tbsp","ajipaste","aromatic","ají panca molido","ají panca paste"],
    [3,"clove","garlic","aromatic","ajo","garlic","molido","crushed"],
    [3,"tsp","salt","salt","sal","salt"],
    [500,"g","pork","protein","carne de cerdo","pork shoulder","en trozos","in pieces"],
    [250,"ml","water","liquid","agua","water"],
    [10,"","olives","garnish","aceitunas de botija","Peruvian black olives"],
    [2,"","egg","garnish","huevos duros","hard-boiled eggs","en cuartos","quartered"],
    [40,"g","peanut","garnish","maní tostado","roasted peanuts"],
    [10,"","veg","structure","hojas de plátano","banana leaves"]],
 es:{n:"Tamal criollo", b:"Tamal de maíz blanco con ají panca relleno de cerdo, aceituna, huevo y maní, envuelto en hoja de plátano. Desayuno de domingo en Lima.",
  st:["Cuece el maíz 60 minutos y muélelo hasta tener una masa.",
      "Cuece el cerdo en el agua con 1 cucharadita de sal 40 minutos.",
      "Fríe el ajo y el ají en la manteca 5 minutos. Añade la masa y el resto de la sal y cocina 15 minutos, removiendo.",
      "Pon masa en cada hoja, añade cerdo, una aceituna, huevo y maní, y cubre con más masa. Envuelve y ata.",
      "Cuece al vapor 60 minutos."],
  tp:["Pasa las hojas por el fuego para que se ablanden y no se rompan.",
      "Sírvelos calientes, recién salidos del vapor."],
  v:"tamal criollo peruano"},
 en:{n:"Tamal Criollo (Peruvian Pork Tamales)", b:"White corn tamales with ají panca, filled with pork, olive, egg and peanut and wrapped in banana leaf. Sunday breakfast in Lima.",
  st:["Cook the corn 60 minutes and grind into a dough.",
      "Simmer the pork in the water with 1 teaspoon of salt for 40 minutes.",
      "Fry the garlic and ají in the lard for 5 minutes. Add the dough and remaining salt and cook 15 minutes, stirring.",
      "Spread dough on each leaf, add pork, an olive, egg and peanuts, and cover with more dough. Wrap and tie.",
      "Steam 60 minutes."],
  tp:["Pass the leaves over a flame so they soften and don't tear.",
      "Serve them warm, straight from the steamer."],
  v:"peruvian tamal criollo"}},

{id:"seco-de-cordero", c:"Peru", r:"latin-america", m:"main", t:120, s:6,
 i:[[1.2,"kg","lamb","protein","pierna de cordero","lamb leg","en trozos","in pieces"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla roja","red onion","picada","chopped"],
    [4,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"tbsp","ajipaste","aromatic","ají amarillo molido","ají amarillo paste"],
    [2,"bunch","herb","aromatic","culantro (cilantro)","coriander","licuado con 250 ml de agua","blended with 250 ml water"],
    [350,"ml","beer","liquid","cerveza rubia","lager"],
    [500,"ml","water","liquid","agua","water"],
    [150,"g","legume","structure","arvejas","green peas"],
    [4,"","potato","structure","papas amarillas","yellow potatoes","en mitades","halved"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Seco de cordero", b:"Cordero guisado en culantro, ají amarillo y cerveza. Plato norteño peruano.",
  st:["Sala el cordero y dóralo en el aceite 10 minutos. Sácalo.",
      "Sofríe la cebolla, el ajo y el ají 6 minutos. Añade el culantro licuado y cocina 5 minutos.",
      "Añade la cerveza, el agua y el cordero. Tapa y cuece 70 minutos a fuego bajo.",
      "Añade las papas y cuece 20 minutos. Añade las arvejas los últimos 5 minutos."],
  tp:["Sírvelo con arroz blanco.",
      "Tradicionalmente se usa chicha de jora, que es de maíz: si la usas, cuenta el maíz."],
  v:"seco de cordero norteño"},
 en:{n:"Seco de Cordero (Peruvian Coriander Lamb Stew)", b:"Lamb stewed in coriander, ají amarillo and beer. A dish from northern Peru.",
  st:["Salt the lamb and brown it in the oil for 10 minutes. Remove.",
      "Cook the onion, garlic and ají for 6 minutes. Add the blended coriander and cook 5 minutes.",
      "Add the beer, water and lamb. Cover and simmer 70 minutes on low.",
      "Add the potatoes and cook 20 minutes. Add the peas for the last 5 minutes."],
  tp:["Serve with white rice.",
      "Traditionally chicha de jora is used, which is made from corn: if you use it, count the corn."],
  v:"peruvian lamb seco"}},

{id:"wantan-frito", c:"Peru", r:"latin-america", m:"snack", t:50, s:30,
 i:[[250,"g","porkmince","protein","carne molida de cerdo","minced pork"],
    [2,"","scallion","aromatic","cebolla china","spring onions","picada","chopped"],
    [1,"tbsp","soysauce","umami","sillao (salsa de soja)","soy sauce"],
    [1,"tsp","sesameoil","aromatic","aceite de ajonjolí","sesame oil"],
    [1,"tsp","spice","aromatic","jengibre rallado","grated ginger"],
    [30,"","eggnoodles","structure","masas de wantán (trigo y huevo)","wonton wrappers (wheat and egg)"],
    [750,"ml","oil","fat","aceite para freír","oil for frying"]],
 es:{n:"Wantán frito", b:"Wantanes crujientes rellenos de cerdo. La entrada infaltable de los chifas peruanos.",
  st:["Mezcla el cerdo, la cebolla china, el sillao, el aceite de ajonjolí y el jengibre.",
      "Pon 1 cucharadita de relleno en cada masa, moja los bordes con agua y dobla en triángulo. Une dos puntas.",
      "Fríe a 175 °C en tandas 3 minutos, hasta que estén dorados.",
      "Escurre en papel."],
  tp:["Cubre las masas con un paño húmedo para que no se sequen.",
      "Revisa la etiqueta de las masas por si llevan soja."],
  v:"wantán frito chifa"},
 en:{n:"Wantán Frito (Peruvian Chifa Fried Wontons)", b:"Crisp fried wontons filled with pork. The must-have starter of Peruvian chifa restaurants.",
  st:["Mix the pork, spring onion, soy sauce, sesame oil and ginger.",
      "Put 1 teaspoon of filling on each wrapper, wet the edges and fold into a triangle. Join two corners.",
      "Fry at 175 °C in batches for 3 minutes, until golden.",
      "Drain on paper."],
  tp:["Keep the wrappers under a damp cloth so they don't dry out.",
      "Check the wrapper label in case they contain soy."],
  v:"peruvian fried wontons"}},

{id:"picante-de-mariscos", c:"Peru", r:"latin-america", m:"main", t:40, s:4,
 i:[[3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla roja","red onion","picada","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [3,"tbsp","ajipaste","aromatic","ají amarillo molido","ají amarillo paste"],
    [1,"tbsp","ajipaste","aromatic","ají panca molido","ají panca paste"],
    [250,"g","shrimp","protein","langostinos pelados","peeled prawns"],
    [250,"g","squid","protein","calamar en aros","squid rings"],
    [250,"g","mussel","protein","choros sin concha","shelled mussels"],
    [100,"ml","winewhite","liquid","vino blanco","white wine"],
    [200,"ml","evaporatedmilk","liquid","leche evaporada","evaporated milk"],
    [80,"g","queso","enrich","queso fresco","queso fresco"],
    [4,"","potato","structure","papas amarillas cocidas","boiled yellow potatoes"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Picante de mariscos", b:"Mariscos en una crema de ají amarillo, leche y queso, con papas. Plato de la costa peruana.",
  st:["Sofríe la cebolla, el ajo y los ajíes en el aceite 6 minutos.",
      "Añade el vino y deja reducir 2 minutos.",
      "Licúa la leche con el queso y añádelo. Cuece 3 minutos.",
      "Añade los mariscos y la sal y cocina 4 minutos.",
      "Sirve sobre las papas cocidas en rodajas."],
  tp:["No cocines de más los mariscos o quedan gomosos.",
      "Sírvelo con arroz blanco."],
  v:"picante de mariscos peruano"},
 en:{n:"Picante de Mariscos (Peruvian Spicy Seafood)", b:"Seafood in a creamy sauce of ají amarillo, milk and cheese, with potatoes. A dish of the Peruvian coast.",
  st:["Cook the onion, garlic and ají pastes in the oil for 6 minutes.",
      "Add the wine and reduce 2 minutes.",
      "Blend the milk with the cheese and add it. Cook 3 minutes.",
      "Add the seafood and salt and cook 4 minutes.",
      "Serve over the sliced boiled potatoes."],
  tp:["Don't overcook the seafood or it turns rubbery.",
      "Serve with white rice."],
  v:"peruvian spicy seafood"}},

{id:"pan-con-pejerrey", c:"Peru", r:"latin-america", m:"main", t:30, s:4,
 i:[[500,"g","whitefish","protein","pejerreyes limpios y abiertos","cleaned, butterflied silversides"],
    [1,"tsp","salt","salt","sal","salt"],
    [80,"g","apflour","dredge","harina de trigo","plain flour"],
    [500,"ml","oil","fat","aceite para freír","oil for frying"],
    [4,"","bread","structure","panes franceses","crusty rolls"],
    [1,"","onion","garnish","cebolla roja","red onion","en pluma fina","thinly sliced"],
    [1,"","chilli","garnish","ají limo","limo chilli","picado","chopped"],
    [2,"","citrus","acid","limones","limes","exprimidos","juiced"],
    [1,"handful","herb","garnish","culantro (cilantro)","coriander","picado","chopped"]],
 es:{n:"Pan con pejerrey", b:"Pan francés con pejerrey frito y salsa criolla. Desayuno de los mercados del Callao y Chorrillos.",
  st:["Sala los pejerreyes y pásalos por la harina.",
      "Fríelos a 180 °C 2 minutos por lado. Escurre.",
      "Mezcla la cebolla, el ají, el limón, el culantro y una pizca de sal.",
      "Abre los panes y rellénalos con el pescado y la cebolla."],
  tp:["Enjuaga la cebolla en agua fría para que pique menos.",
      "Si no hay pejerrey, usa filetes finos de pescado blanco."],
  v:"pan con pejerrey"},
 en:{n:"Pan con Pejerrey (Peruvian Fried Fish Sandwich)", b:"A crusty roll with fried silverside and onion relish. Breakfast at the markets of Callao and Chorrillos.",
  st:["Salt the fish and dredge in the flour.",
      "Fry at 180 °C for 2 minutes per side. Drain.",
      "Mix the onion, chilli, lime, coriander and a pinch of salt.",
      "Split the rolls and fill with the fish and onion."],
  tp:["Rinse the onion in cold water to tame it.",
      "No silversides? Use thin white fish fillets."],
  v:"peruvian fried fish sandwich"}}
];
