module.exports = [
{id:"olluquito-con-charqui", c:"Peru", ce:"Perú", r:"latin-america", m:"main", t:50, s:4,
 i:[[150,"g","driedmeat","protein","charqui de res o alpaca","beef or alpaca charqui","desalado y deshilachado","desalted and shredded"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla roja","red onion","picada","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"tbsp","ajipaste","aromatic","pasta de ají panca","ají panca paste"],
    [800,"g","veg","structure","olluco","olluco (ulluco)","en tiras finas","in fine strips"],
    [200,"ml","water","liquid","agua","water"],
    [1,"handful","herb","garnish","perejil","parsley","picado","chopped"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Olluquito con charqui", b:"Olluco en tiras guisado con charqui y ají panca. Plato andino de raíz prehispánica.",
  st:["Sofríe la cebolla, el ajo y la pasta de ají en el aceite 8 minutos.",
      "Añade el charqui y cuece 5 minutos.",
      "Añade el olluco, sin lavarlo después de cortarlo, y mezcla.",
      "Añade el agua, tapa y cuece 20 minutos a fuego bajo, hasta que el olluco esté tierno. Sala al gusto.",
      "Termina con el perejil y sirve con arroz."],
  tp:["No laves el olluco una vez cortado: suelta una baba que espesa el guiso.",
      "Con carne fresca de res en lugar de charqui también queda bien."],
  v:"olluquito con charqui receta"},
 en:{n:"Olluquito con Charqui (Ulluco and Dried Meat Stew)", b:"Strips of ulluco stewed with dried meat and ají panca. An Andean dish with pre-Hispanic roots.",
  st:["Cook the onion, garlic and ají paste in the oil for 8 minutes.",
      "Add the charqui and cook 5 minutes.",
      "Add the ulluco, without washing it after cutting, and stir.",
      "Add the water, cover and cook 20 minutes on low, until tender. Salt to taste.",
      "Finish with the parsley and serve with rice."],
  tp:["Don't wash the ulluco once cut: its slippery juice thickens the stew.",
      "Fresh beef instead of charqui works well too."],
  v:"olluquito con charqui recipe"}},

{id:"tacacho-con-cecina", c:"Peru", ce:"Perú", r:"latin-america", m:"main", t:40, s:4,
 i:[[4,"","plantain","structure","plátanos verdes","green plantains","pelados, en trozos","peeled, in chunks"],
    [100,"g","lard","fat","manteca de cerdo","lard"],
    [100,"g","porkskin","crunch","chicharrón de cerdo","pork crackling","picado","chopped"],
    [1,"tsp","salt","salt","sal","salt"],
    [600,"g","curedmeat","protein","cecina de cerdo","cecina (smoked cured pork)","en tiras","in strips"],
    [2,"tbsp","oil","fat","aceite","oil"]],
 es:{n:"Tacacho con cecina", b:"Bolas de plátano verde asado majado con manteca y chicharrón, con cecina frita. El desayuno de la Amazonía peruana.",
  st:["Asa los trozos de plátano en la parrilla o en una sartén seca 15 minutos, hasta que estén tiernos y dorados.",
      "Maja el plátano caliente con la manteca, el chicharrón y la sal.",
      "Forma 4 bolas grandes.",
      "Fríe la cecina en el aceite 5 minutos, hasta que esté dorada.",
      "Sirve cada tacacho con la cecina."],
  tp:["Maja el plátano en cuanto sale del fuego; frío no se une.",
      "La cecina amazónica es cerdo ahumado y salado: no añadas más sal."],
  v:"tacacho con cecina receta"},
 en:{n:"Tacacho con Cecina (Amazon Plantain Balls with Smoked Pork)", b:"Balls of grilled green plantain mashed with lard and crackling, with fried cecina. Breakfast in the Peruvian Amazon.",
  st:["Grill the plantain chunks on a grill or dry pan for 15 minutes, until tender and golden.",
      "Mash the hot plantain with the lard, crackling and salt.",
      "Shape into 4 large balls.",
      "Fry the cecina in the oil for 5 minutes, until golden.",
      "Serve each tacacho with the cecina."],
  tp:["Mash the plantain as soon as it's off the heat; cold, it won't bind.",
      "Amazonian cecina is smoked, salted pork: don't add more salt."],
  v:"tacacho con cecina recipe"}},

{id:"inchicapi", c:"Peru", ce:"Perú", r:"latin-america", m:"soup", t:75, s:6,
 i:[[1.2,"kg","chicken","protein","gallina o pollo en presas","hen or chicken pieces"],
    [2.5,"l","water","liquid","agua","water"],
    [150,"g","peanut","thicken","maní crudo","raw peanuts"],
    [60,"g","masa","thicken","harina de maíz","corn flour"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [400,"g","cassava","structure","yuca","cassava","en trozos","in chunks"],
    [1,"handful","herb","aromatic","sacha culantro o culantro","sacha culantro or culantro","picado","chopped"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Inchicapi", b:"Sopa amazónica de gallina espesada con maní y maíz, con yuca y sacha culantro.",
  st:["Cuece el pollo en el agua con la sal 40 minutos.",
      "Tuesta el maní y muélelo con 250 ml del caldo hasta tener una crema.",
      "Sofríe la cebolla y el ajo en el aceite 5 minutos y añádelos a la olla con la yuca. Cuece 15 minutos.",
      "Disuelve la harina de maíz en agua fría y añádela con la crema de maní, removiendo. Cuece 10 minutos.",
      "Termina con el sacha culantro."],
  tp:["Remueve después de añadir el maní y el maíz: se pegan al fondo.",
      "El sacha culantro es como un culantro muy intenso."],
  v:"inchicapi de gallina receta"},
 en:{n:"Inchicapi (Amazon Chicken Peanut Soup)", b:"An Amazonian hen soup thickened with peanuts and corn, with cassava and sacha culantro.",
  st:["Simmer the chicken in the water with the salt for 40 minutes.",
      "Toast the peanuts and grind with 250 ml of the broth to a cream.",
      "Cook the onion and garlic in the oil for 5 minutes and add to the pot with the cassava. Cook 15 minutes.",
      "Dissolve the corn flour in cold water and add with the peanut cream, stirring. Cook 10 minutes.",
      "Finish with the sacha culantro."],
  tp:["Stir after adding the peanut and corn: they catch on the bottom.",
      "Sacha culantro is like a very intense culantro."],
  v:"inchicapi recipe"}},

{id:"ensalada-de-pallares", c:"Peru", ce:"Perú", r:"latin-america", m:"side", t:20, s:4,
 i:[[500,"g","legume","structure","pallares cocidos","cooked lima beans (pallares)"],
    [1,"","onion","aromatic","cebolla roja","red onion","en dados","diced"],
    [2,"","tomato","structure","tomates","tomatoes","en dados","diced"],
    [1,"","chilli","aromatic","ají amarillo","ají amarillo","en dados","diced"],
    [1,"handful","herb","aromatic","perejil","parsley","picado","chopped"],
    [3,"","citrus","acid","limones","limes","en jugo","juiced"],
    [3,"tbsp","oil","fat","aceite de oliva","olive oil"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Ensalada de pallares", b:"Pallares con cebolla, tomate, ají y limón. Fresca y rápida, de la costa sur del Perú.",
  st:["Remoja la cebolla en agua con sal 5 minutos y escúrrela.",
      "Mezcla los pallares con la cebolla, el tomate y el ají.",
      "Añade el jugo de limón, el aceite y la sal.",
      "Mezcla con el perejil.",
      "Deja reposar 10 minutos antes de servir."],
  tp:["Si usas pallares secos, remójalos 12 horas y pela la piel antes de cocerlos.",
      "Quita las venas del ají para que pique menos."],
  v:"ensalada de pallares receta"},
 en:{n:"Peruvian Lima Bean Salad", b:"Lima beans with onion, tomato, ají and lime. Fresh and quick, from Peru's southern coast.",
  st:["Soak the onion in salted water for 5 minutes and drain.",
      "Mix the beans with the onion, tomato and ají.",
      "Add the lime juice, oil and salt.",
      "Toss with the parsley.",
      "Leave 10 minutes before serving."],
  tp:["If using dried beans, soak 12 hours and slip off the skins before cooking.",
      "Remove the ají veins for less heat."],
  v:"lima bean salad recipe"}},

{id:"arroz-zambito", c:"Peru", ce:"Perú", r:"latin-america", m:"sweet", t:60, s:8,
 i:[[200,"g","rice","structure","arroz","rice"],
    [1,"l","water","liquid","agua","water"],
    [250,"g","jaggery","sweet","chancaca","chancaca (unrefined cane sugar)","rallada","grated"],
    [2,"","spice","aromatic","ramas de canela","cinnamon sticks"],
    [4,"","spice","aromatic","clavos de olor","whole cloves"],
    [400,"ml","evaporatedmilk","liquid","leche evaporada","evaporated milk"],
    [60,"g","driedfruit","sweet","pasas","raisins"],
    [40,"g","desiccatedcoconut","garnish","coco rallado","desiccated coconut"],
    [30,"g","butter","enrich","mantequilla","butter"]],
 es:{n:"Arroz zambito", b:"Arroz con leche oscuro de chancaca, con coco y pasas. Dulce limeño de herencia afroperuana.",
  st:["Cuece el arroz en el agua con la canela y los clavos 20 minutos.",
      "Añade la chancaca y remueve hasta que se disuelva.",
      "Añade la leche evaporada y cuece 20 minutos a fuego bajo, removiendo, hasta que espese.",
      "Añade las pasas, el coco y la mantequilla y cuece 5 minutos.",
      "Retira la canela y los clavos y sirve tibio o frío."],
  tp:["La chancaca da el color oscuro que le da nombre.",
      "Espesa al enfriar; si queda muy firme, añade leche."],
  v:"arroz zambito receta"},
 en:{n:"Arroz Zambito (Dark Rice Pudding)", b:"A dark rice pudding sweetened with chancaca, with coconut and raisins. A Lima sweet with Afro-Peruvian roots.",
  st:["Cook the rice in the water with the cinnamon and cloves for 20 minutes.",
      "Add the chancaca and stir until dissolved.",
      "Add the evaporated milk and cook 20 minutes on low, stirring, until thick.",
      "Add the raisins, coconut and butter and cook 5 minutes.",
      "Remove the cinnamon and cloves and serve warm or cold."],
  tp:["Chancaca gives the dark colour behind the name.",
      "It thickens as it cools; if too firm, add milk."],
  v:"arroz zambito recipe"}},

{id:"champus", c:"Peru", ce:"Perú", r:"latin-america", m:"drink", t:60, s:8,
 i:[[150,"g","hominy","structure","mote de maíz pelado","peeled hominy corn","cocido","cooked"],
    [2,"l","water","liquid","agua","water"],
    [2,"","fruit","structure","membrillos","quinces","en dados","diced"],
    [0.5,"","fruit","structure","piña","pineapple","en dados","diced"],
    [2,"","fruit","structure","manzanas","apples","en dados","diced"],
    [2,"","spice","aromatic","ramas de canela","cinnamon sticks"],
    [4,"","spice","aromatic","clavos de olor","whole cloves"],
    [250,"g","jaggery","sweet","chancaca","chancaca (unrefined cane sugar)"],
    [60,"g","masa","thicken","harina de maíz","corn flour"],
    [1,"","fruit","aromatic","naranjilla o lulo (opcional)","naranjilla or lulo (optional)","en jugo","juiced"]],
 es:{n:"Champús", b:"Bebida espesa y caliente de mote, frutas y chancaca con canela. Se toma en invierno en Lima y en el sur de Colombia.",
  st:["Hierve el agua con la canela, los clavos y la chancaca 10 minutos.",
      "Añade el membrillo y la manzana y cuece 15 minutos.",
      "Añade el mote y la piña.",
      "Disuelve la harina de maíz en agua fría y añádela, removiendo. Cuece 10 minutos hasta que espese.",
      "Añade el jugo de naranjilla y sirve caliente."],
  tp:["El membrillo da el aroma característico; no lo quites.",
      "Se toma caliente en Lima y frío en el sur de Colombia."],
  v:"champús receta"},
 en:{n:"Champús (Hominy and Fruit Drink)", b:"A thick hot drink of hominy, fruit and chancaca with cinnamon. Drunk in winter in Lima and southern Colombia.",
  st:["Boil the water with the cinnamon, cloves and chancaca for 10 minutes.",
      "Add the quince and apple and cook 15 minutes.",
      "Add the hominy and pineapple.",
      "Dissolve the corn flour in cold water and add, stirring. Cook 10 minutes until thick.",
      "Add the naranjilla juice and serve hot."],
  tp:["Quince gives the characteristic aroma; don't leave it out.",
      "It's drunk hot in Lima and cold in southern Colombia."],
  v:"champus recipe"}},

{id:"chilcano", c:"Peru", ce:"Perú", r:"latin-america", m:"drink", t:5, s:1,
 i:[[60,"ml","spirit","liquid","pisco","pisco"],
    [1,"","citrus","acid","limón","lime","en jugo","juiced"],
    [150,"ml","softdrink","liquid","ginger ale","ginger ale"],
    [3,"","spirit","aromatic","gotas de amargo de angostura","dashes of Angostura bitters"],
    [1,"handful","ice","structure","hielo","ice"]],
 es:{n:"Chilcano de pisco", b:"Pisco con limón y ginger ale sobre hielo. El trago más refrescante del Perú.",
  st:["Llena un vaso alto de hielo.",
      "Añade el pisco y el jugo de limón.",
      "Completa con el ginger ale.",
      "Añade el amargo de angostura por encima.",
      "Remueve suave una vez y sirve."],
  tp:["Añade el ginger ale al final para que no pierda el gas.",
      "Un pisco quebranta es el más usado."],
  v:"chilcano de pisco receta"},
 en:{n:"Chilcano (Pisco and Ginger Ale)", b:"Pisco with lime and ginger ale over ice. Peru's most refreshing drink.",
  st:["Fill a tall glass with ice.",
      "Add the pisco and lime juice.",
      "Top with the ginger ale.",
      "Add the Angostura on top.",
      "Stir gently once and serve."],
  tp:["Add the ginger ale last so it keeps its fizz.",
      "Quebranta pisco is the usual choice."],
  v:"chilcano recipe"}},

{id:"pescado-a-lo-macho", c:"Peru", ce:"Perú", r:"latin-america", m:"main", t:45, s:4,
 i:[[4,"","whitefish","protein","filetes de pescado blanco","white fish fillets"],
    [80,"g","apflour","dredge","harina de trigo","plain flour"],
    [4,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla roja","red onion","picada","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"tbsp","ajipaste","aromatic","pasta de ají amarillo","ají amarillo paste"],
    [1,"tbsp","ajipaste","aromatic","pasta de ají panca","ají panca paste"],
    [100,"ml","winewhite","liquid","vino blanco","white wine"],
    [300,"ml","fishstock","liquid","caldo de pescado","fish stock"],
    [200,"g","shrimp","protein","camarones","shrimp","pelados","peeled"],
    [200,"g","squid","protein","calamares","squid","en anillas","in rings"],
    [300,"g","mussel","protein","choritos","mussels","limpios","cleaned"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"handful","herb","garnish","perejil","parsley","picado","chopped"]],
 es:{n:"Pescado a lo macho", b:"Filete de pescado frito bañado en una salsa picante de ají con mariscos. Plato de fuerza de las cebicherías.",
  st:["Sala el pescado, pásalo por la harina y fríelo en 2 cucharadas de aceite 3 minutos por lado. Resérvalo.",
      "Sofríe la cebolla, el ajo y las pastas de ají en el resto del aceite 8 minutos.",
      "Añade el vino y cuece 2 minutos. Añade el caldo y cuece 5 minutos.",
      "Añade los mariscos, tapa y cuece 4 minutos, hasta que los choritos se abran.",
      "Sirve el pescado bañado con la salsa de mariscos y el perejil."],
  tp:["Dora el pescado justo antes de servir para que no se ablande.",
      "Tira los choritos que queden cerrados."],
  v:"pescado a lo macho receta"},
 en:{n:"Pescado a lo Macho (Fish in Spicy Seafood Sauce)", b:"Fried fish fillet under a spicy ají sauce with seafood. A hearty cebichería dish.",
  st:["Salt the fish, dredge in the flour and fry in 2 tablespoons of oil for 3 minutes a side. Set aside.",
      "Cook the onion, garlic and ají pastes in the rest of the oil for 8 minutes.",
      "Add the wine and cook 2 minutes. Add the stock and cook 5 minutes.",
      "Add the seafood, cover and cook 4 minutes, until the mussels open.",
      "Serve the fish covered with the seafood sauce and the parsley."],
  tp:["Fry the fish just before serving so it stays crisp.",
      "Discard any mussels that stay shut."],
  v:"pescado a lo macho recipe"}},

{id:"sancochado", c:"Peru", ce:"Perú", r:"latin-america", m:"soup", t:150, s:8,
 i:[[1,"kg","beef","protein","pecho de res","beef brisket","en trozos","in pieces"],
    [4,"l","water","liquid","agua","water"],
    [1,"","onion","aromatic","cebolla","onion","en mitades","halved"],
    [2,"","scallion","aromatic","poro o cebolla china","leek or spring onion"],
    [2,"tsp","salt","salt","sal","salt"],
    [4,"","potato","structure","papas amarillas","yellow potatoes"],
    [400,"g","cassava","structure","yuca","cassava","en trozos","in chunks"],
    [300,"g","veg","structure","camote","sweet potato","en trozos","in chunks"],
    [2,"","corn","structure","choclos","corn cobs","en ruedas","in rounds"],
    [0.25,"","veg","structure","repollo","cabbage","en gajos","in wedges"],
    [2,"","veg","structure","zanahorias","carrots","en trozos","in chunks"]],
 es:{n:"Sancochado limeño", b:"Carne y verduras hervidas enteras en un caldo claro. Se sirve el caldo aparte y todo lo demás en fuente.",
  st:["Cuece la carne en el agua con la cebolla, el poro y la sal 90 minutos, quitando la espuma.",
      "Añade la yuca y el choclo y cuece 15 minutos.",
      "Añade las papas, el camote y la zanahoria y cuece 15 minutos.",
      "Añade el repollo y cuece 10 minutos más.",
      "Sirve el caldo en tazas y la carne con las verduras en una fuente."],
  tp:["Añade cada verdura según su tiempo de cocción para que ninguna se deshaga.",
      "Se acompaña con una salsa de hierbas o de ají al gusto."],
  v:"sancochado limeño receta"},
 en:{n:"Sancochado (Lima Boiled Dinner)", b:"Beef and whole vegetables boiled in a clear broth. The broth is served on the side and everything else on a platter.",
  st:["Simmer the beef in the water with the onion, leek and salt for 90 minutes, skimming.",
      "Add the cassava and corn and cook 15 minutes.",
      "Add the potatoes, sweet potato and carrot and cook 15 minutes.",
      "Add the cabbage and cook 10 minutes more.",
      "Serve the broth in cups and the meat with the vegetables on a platter."],
  tp:["Add each vegetable according to its cooking time so none falls apart.",
      "It's served with an herb or chilli sauce to taste."],
  v:"sancochado recipe"}}
];
