module.exports = [
{id:"picarones", c:"Peru", ce:"Perú", r:"latin-america", m:"sweet", t:150, s:6,
 i:[[300,"g","veg","structure","zapallo","pumpkin (zapallo)","pelado, en trozos","peeled, in chunks"],
    [300,"g","veg","structure","camote","sweet potato","pelado, en trozos","peeled, in chunks"],
    [1,"tbsp","spice","aromatic","anís en grano","aniseed"],
    [7,"g","yeast","leaven","levadura seca","instant yeast"],
    [1,"tbsp","sugar","sweet","azúcar","sugar"],
    [400,"g","apflour","structure","harina de trigo","all-purpose flour"],
    [1,"l","oil","fat","aceite","oil","para freír","for frying"],
    [300,"g","jaggery","sweet","chancaca o panela","chancaca or panela (unrefined cane sugar)","para la miel","for the syrup"],
    [300,"ml","water","liquid","agua","water","para la miel","for the syrup"],
    [2,"","spice","aromatic","rajas de canela","cinnamon sticks"],
    [4,"","spice","aromatic","clavos de olor","cloves"],
    [1,"","citrus","aromatic","cáscara de naranja","orange peel","en tiras","in strips"]],
 es:{n:"Picarones", b:"Aros fritos de masa de zapallo y camote con anís, bañados en miel de chancaca especiada. El dulce de las calles de Lima.",
  st:["Hierve el zapallo y el camote con el anís en agua 20 minutos. Escurre, guarda 250 ml del agua y haz un puré.",
      "Disuelve la levadura y el azúcar en el agua tibia guardada. Deja 10 minutos, hasta que haga espuma.",
      "Mezcla el puré, la levadura y la harina y bate con la mano 10 minutos, hasta que la masa esté elástica y pegajosa.",
      "Tapa y deja crecer 90 minutos, hasta que doble y tenga burbujas.",
      "Para la miel, hierve la chancaca con el agua, la canela, el clavo y la naranja 20 minutos, hasta que espese un poco. Cuela.",
      "Calienta el aceite a 180 °C. Con la mano mojada, toma un poco de masa, haz un agujero con el pulgar y déjala caer al aceite. Fríe 1 minuto por lado.",
      "Sirve calientes bañados en la miel."],
  tp:["Moja la mano en agua con sal entre cada picarón para que la masa no se pegue.",
      "Sin práctica salen deformes; saben igual de bien."],
  v:"picarones receta"},
 en:{n:"Picarones (Pumpkin and Sweet Potato Doughnuts)", b:"Fried rings of pumpkin and sweet potato dough with anise, drenched in spiced chancaca syrup. The street sweet of Lima.",
  st:["Boil the pumpkin and sweet potato with the aniseed in water for 20 minutes. Drain, keep 250 ml of the water and mash.",
      "Dissolve the yeast and sugar in the reserved warm water. Leave 10 minutes, until foamy.",
      "Mix the mash, yeast and flour and beat by hand for 10 minutes, until elastic and sticky.",
      "Cover and let rise 90 minutes, until doubled and bubbly.",
      "For the syrup, boil the chancaca with the water, cinnamon, cloves and orange peel for 20 minutes, until slightly thick. Strain.",
      "Heat the oil to 180 °C. With a wet hand, grab some dough, poke a hole with your thumb and drop it into the oil. Fry 1 minute per side.",
      "Serve hot, drenched in the syrup."],
  tp:["Dip your hand in salted water between each one so the dough doesn't stick.",
      "Without practice they come out misshapen; they taste just as good."],
  v:"picarones recipe"}},

{id:"suspiro-limeno", c:"Peru", ce:"Perú", r:"latin-america", m:"sweet", t:60, s:6,
 i:[[395,"g","condensedmilk","sweet","leche condensada","sweetened condensed milk"],
    [400,"ml","evaporatedmilk","liquid","leche evaporada","evaporated milk"],
    [4,"","eggyolk","set","yemas de huevo","egg yolks"],
    [1,"tsp","vanilla","aromatic","extracto de vainilla","vanilla extract"],
    [3,"","eggwhite","aerate","claras de huevo","egg whites"],
    [150,"g","sugar","sweet","azúcar","sugar","para el merengue","for the meringue"],
    [80,"ml","wine","aromatic","oporto","port wine"],
    [1,"tsp","spice","garnish","canela molida","ground cinnamon"]],
 es:{n:"Suspiro limeño", b:"Manjar blanco de leche con yemas cubierto de un merengue perfumado con oporto y canela. Dulce como un suspiro de mujer, dicen.",
  st:["Cuece la leche condensada y la evaporada a fuego medio-bajo 25 minutos, moviendo sin parar, hasta que espese y se vea el fondo de la olla.",
      "Retira del fuego. Bate las yemas y añade un poco del manjar caliente, luego mezcla todo. Añade la vainilla. Reparte en copas y enfría.",
      "Hierve el oporto con el azúcar 5 minutos, hasta que haga un almíbar a punto de hilo.",
      "Bate las claras a punto de nieve. Vierte el almíbar caliente en hilo mientras bates, hasta que el merengue esté brillante y frío.",
      "Cubre el manjar con el merengue y espolvorea canela."],
  tp:["Las yemas cuajan con el calor del manjar: no lo regreses al fuego después.",
      "Las claras no se cuecen del todo en este merengue: en embarazo o con defensas bajas, usa claras pasteurizadas."],
  v:"suspiro limeño receta"},
 en:{n:"Suspiro Limeño", b:"A milk and yolk caramel cream under a meringue scented with port and cinnamon. Sweet as a woman's sigh, the saying goes.",
  st:["Cook the condensed and evaporated milk over medium-low heat for 25 minutes, stirring constantly, until thick and the bottom of the pot shows.",
      "Take off the heat. Whisk the yolks, add a little of the hot cream, then combine everything. Add the vanilla. Divide among glasses and cool.",
      "Boil the port with the sugar for 5 minutes, to a syrup at thread stage.",
      "Whisk the whites to stiff peaks. Pour in the hot syrup in a thin stream while whisking, until the meringue is glossy and cool.",
      "Top the cream with the meringue and dust with cinnamon."],
  tp:["The yolks set with the heat of the cream: don't return it to the stove.",
      "The whites aren't fully cooked in this meringue: if pregnant or immunocompromised, use pasteurised whites."],
  v:"suspiro limeno recipe"}},

{id:"mazamorra-morada", c:"Peru", ce:"Perú", r:"latin-america", m:"sweet", t:90, s:8,
 i:[[500,"g","corn","structure","maíz morado","purple corn","en mazorcas partidas","cobs, broken"],
    [2.5,"l","water","liquid","agua","water"],
    [1,"","fruit","aromatic","cáscara de piña","pineapple peel"],
    [2,"","spice","aromatic","rajas de canela","cinnamon sticks"],
    [6,"","spice","aromatic","clavos de olor","cloves"],
    [250,"g","sugar","sweet","azúcar","sugar"],
    [150,"g","driedfruit","sweet","orejones y ciruelas secas","dried apricots and prunes","en trozos","chopped"],
    [1,"","fruit","sweet","manzana","apple","en cubos","diced"],
    [80,"g","potato","thicken","chuño (fécula de papa)","potato starch (chuño)","disuelto en agua fría","dissolved in cold water"],
    [1,"","citrus","acid","limón","lime","en jugo","juiced"]],
 es:{n:"Mazamorra morada", b:"Postre espeso de maíz morado con frutas secas, canela y clavo. Morado brillante y con arroz con leche al lado se llama clásico.",
  st:["Hierve el maíz, la cáscara de piña, la canela y el clavo en el agua 45 minutos. Cuela y guarda el líquido morado.",
      "Añade el azúcar, las frutas secas y la manzana. Hierve 15 minutos.",
      "Añade el chuño disuelto poco a poco, moviendo sin parar. Cuece 5 minutos, hasta que espese.",
      "Apaga, añade el limón y sirve tibia o fría con canela encima."],
  tp:["El limón al final aviva el color morado.",
      "Se sirve tibia en invierno y fría en verano."],
  v:"mazamorra morada receta"},
 en:{n:"Mazamorra Morada (Purple Corn Pudding)", b:"A thick pudding of purple corn with dried fruit, cinnamon and clove. Bright purple, and with rice pudding alongside it's called a classic.",
  st:["Boil the corn, pineapple peel, cinnamon and cloves in the water for 45 minutes. Strain and keep the purple liquid.",
      "Add the sugar, dried fruit and apple. Boil 15 minutes.",
      "Add the dissolved potato starch little by little, stirring constantly. Cook 5 minutes, until thick.",
      "Turn off, add the lime and serve warm or cold with cinnamon on top."],
  tp:["The lime at the end brightens the purple.",
      "Serve it warm in winter and cold in summer."],
  v:"mazamorra morada recipe"}},

{id:"chicha-morada", c:"Peru", ce:"Perú", r:"latin-america", m:"drink", t:75, s:8,
 i:[[500,"g","corn","aromatic","maíz morado","purple corn","en mazorcas partidas","cobs, broken"],
    [3,"l","water","liquid","agua","water"],
    [1,"","fruit","aromatic","cáscara de piña","pineapple peel"],
    [1,"","fruit","aromatic","manzana","apple","en trozos","in pieces"],
    [2,"","spice","aromatic","rajas de canela","cinnamon sticks"],
    [6,"","spice","aromatic","clavos de olor","cloves"],
    [200,"g","sugar","sweet","azúcar","sugar"],
    [3,"","citrus","acid","limones","limes","en jugo","juiced"],
    [1,"handful","ice","serve","hielo","ice"]],
 es:{n:"Chicha morada", b:"Refresco peruano de maíz morado hervido con piña, manzana, canela y clavo. Sin alcohol, dulce y ácido.",
  st:["Hierve el maíz, la cáscara de piña, la manzana, la canela y el clavo en el agua 45 minutos.",
      "Cuela y deja enfriar.",
      "Añade el azúcar y el limón al gusto y mezcla hasta disolver.",
      "Sirve muy fría con hielo y trocitos de manzana."],
  tp:["Se puede hervir el maíz una segunda vez con agua nueva para otra jarra más suave.",
      "Dura 4 días en el refrigerador sin el limón; añádelo al servir."],
  v:"chicha morada receta"},
 en:{n:"Chicha Morada (Purple Corn Drink)", b:"A Peruvian cooler of purple corn boiled with pineapple, apple, cinnamon and clove. Alcohol-free, sweet and tart.",
  st:["Boil the corn, pineapple peel, apple, cinnamon and cloves in the water for 45 minutes.",
      "Strain and cool.",
      "Add the sugar and lime to taste and stir to dissolve.",
      "Serve very cold with ice and bits of apple."],
  tp:["You can boil the corn a second time with fresh water for another, milder jug.",
      "Keeps 4 days in the fridge without the lime; add it when serving."],
  v:"chicha morada recipe"}},

{id:"quinua-atamalada", c:"Peru", ce:"Perú", r:"latin-america", m:"main", t:40, s:4,
 i:[[250,"g","grain","structure","quinua","quinoa","bien enjuagada","well rinsed"],
    [750,"ml","water","liquid","agua","water"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla morada","red onion","picada","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [3,"tbsp","ajipaste","aromatic","pasta de ají amarillo","ají amarillo paste"],
    [300,"g","potato","structure","papa amarilla","yellow potato","en cubos","diced"],
    [200,"ml","evaporatedmilk","enrich","leche evaporada","evaporated milk"],
    [150,"g","queso","protein","queso fresco","queso fresco","en cubos","cubed"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"handful","herb","garnish","huacatay o cilantro","huacatay or cilantro","picado","chopped"]],
 es:{n:"Quinua atamalada", b:"Quinua cremosa como un tamal suelto, con ají amarillo, papa, leche y queso fresco. Plato andino de un solo tiempo.",
  st:["Frota la quinua bajo el agua hasta que deje de hacer espuma: quita el amargor.",
      "Sofríe la cebolla, el ajo y el ají en el aceite 8 minutos.",
      "Añade la quinua, la papa, el agua y la sal. Cuece a fuego bajo 20 minutos, moviendo de vez en cuando, hasta que la quinua abra y esté cremosa.",
      "Añade la leche y el queso y cuece 3 minutos más.",
      "Sirve con huacatay picado."],
  tp:["Debe quedar cremosa como un risotto; añade agua si se seca.",
      "Se espesa al reposar: añade agua caliente al recalentar."],
  v:"quinua atamalada receta"},
 en:{n:"Quinua Atamalada (Creamy Quinoa Stew)", b:"Quinoa as creamy as a loose tamale, with ají amarillo, potato, milk and queso fresco. A one-pot Andean dish.",
  st:["Rub the quinoa under running water until it stops foaming: that removes the bitterness.",
      "Cook the onion, garlic and ají in the oil for 8 minutes.",
      "Add the quinoa, potato, water and salt. Simmer on low for 20 minutes, stirring now and then, until the quinoa opens and turns creamy.",
      "Add the milk and cheese and cook 3 minutes more.",
      "Serve with chopped huacatay."],
  tp:["It should be creamy like risotto; add water if it dries out.",
      "It thickens as it sits: add hot water when reheating."],
  v:"quinoa atamalada recipe"}},

{id:"solterito", c:"Peru", ce:"Perú", r:"latin-america", m:"starter", t:30, s:4,
 i:[[250,"g","legume","protein","habas frescas o congeladas","fresh or frozen fava beans","peladas","peeled"],
    [2,"","corn","protein","choclos","ears of corn","cocidos, desgranados","cooked, kernels cut off"],
    [2,"","tomato","aromatic","tomates","tomatoes","en cubos","diced"],
    [0.5,"","onion","aromatic","cebolla morada","red onion","en cubos","diced"],
    [0.5,"","chilli","aromatic","rocoto","rocoto pepper","sin semillas, en cubos pequeños","seeded, finely diced"],
    [150,"g","queso","protein","queso fresco","queso fresco","en cubos","cubed"],
    [10,"","olives","garnish","aceitunas negras","black olives","en rodajas","sliced"],
    [2,"","citrus","acid","limones","limes","en jugo","juiced"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [0.5,"tsp","salt","salt","sal","salt"],
    [1,"handful","herb","garnish","perejil","parsley","picado","chopped"]],
 es:{n:"Solterito arequipeño", b:"Ensalada fresca de Arequipa con habas, choclo, queso fresco, aceituna y rocoto, aliñada con limón.",
  st:["Hierve las habas 4 minutos en agua con sal. Escurre y enfría en agua fría.",
      "Mezcla las habas, el choclo, el tomate, la cebolla, el rocoto, el queso y las aceitunas.",
      "Bate el limón con el aceite y la sal y aliña.",
      "Termina con perejil y sirve frío."],
  tp:["El rocoto es muy picante: empieza con poco.",
      "Quien toma medicamentos llamados IMAO o tiene favismo (déficit de G6PD) no debe comer habas."],
  v:"solterito arequipeño receta"},
 en:{n:"Solterito (Arequipa Fava Bean Salad)", b:"A fresh Arequipa salad of fava beans, corn, queso fresco, olives and rocoto, dressed with lime.",
  st:["Boil the fava beans 4 minutes in salted water. Drain and cool in cold water.",
      "Mix the beans, corn, tomato, onion, rocoto, cheese and olives.",
      "Whisk the lime with the oil and salt and dress the salad.",
      "Finish with parsley and serve cold."],
  tp:["Rocoto is very hot: start with a little.",
      "Anyone on MAOI medication or with favism (G6PD deficiency) should not eat fava beans."],
  v:"solterito recipe"}},

{id:"pisco-sour", c:"Peru", ce:"Perú", r:"latin-america", m:"drink", t:5, s:2,
 i:[[120,"ml","spirit","liquid","pisco quebranta","pisco (quebranta)"],
    [45,"ml","citrus","acid","jugo de limón","lime juice","recién exprimido","freshly squeezed"],
    [30,"ml","sugar","sweet","jarabe de goma (azúcar y agua 1:1)","simple syrup (1:1 sugar and water)"],
    [1,"","eggwhite","aerate","clara de huevo","egg white"],
    [1,"handful","ice","liquid","hielo","ice"],
    [3,"drop","spirit","garnish","amargo de angostura","Angostura bitters"]],
 es:{n:"Pisco sour", b:"El cóctel del Perú: pisco, limón, jarabe y clara batidos con hielo hasta espumar, con gotas de amargo encima.",
  st:["Pon el pisco, el limón, el jarabe y la clara en una coctelera o licuadora.",
      "Añade el hielo y bate 15 segundos, hasta que haga espuma espesa.",
      "Sirve en vasos cortos y pon 3 gotas de amargo sobre la espuma."],
  tp:["Lleva alcohol y clara cruda: con embarazo o defensas bajas, no. Usa clara pasteurizada si dudas.",
      "El limón debe exprimirse en el momento, sin apretar la cáscara, para que no amargue."],
  v:"pisco sour receta"},
 en:{n:"Pisco Sour", b:"Peru's cocktail: pisco, lime, syrup and egg white shaken with ice until foamy, with drops of bitters on top.",
  st:["Put the pisco, lime, syrup and egg white in a shaker or blender.",
      "Add the ice and shake 15 seconds, until thickly foamy.",
      "Pour into short glasses and put 3 drops of bitters on the foam."],
  tp:["It contains alcohol and raw egg white: not for pregnancy or weakened immunity. Use pasteurised white if in doubt.",
      "Squeeze the limes just before, without pressing the peel, so it doesn't turn bitter."],
  v:"pisco sour recipe"}},

{id:"pan-con-chicharron", c:"Peru", ce:"Perú", r:"latin-america", m:"breakfast", t:120, s:4,
 i:[[800,"g","porkbelly","protein","panceta o costilla de cerdo","pork belly or ribs","en trozos","in pieces"],
    [1,"l","water","liquid","agua","water"],
    [1.5,"tsp","salt","salt","sal","salt"],
    [2,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [1,"","veg","structure","camote","sweet potato","en rodajas","sliced"],
    [4,"","bread","serve","panes franceses o bolillos","crusty rolls"],
    [1,"","onion","aromatic","cebolla morada","red onion","en pluma fina","thinly sliced"],
    [1,"","chilli","aromatic","ají limo o amarillo","ají limo or yellow chile","en tiras","in strips"],
    [2,"","citrus","acid","limones","limes","en jugo","juiced"],
    [1,"handful","herb","aromatic","cilantro","cilantro","picado","chopped"]],
 es:{n:"Pan con chicharrón", b:"El desayuno de domingo en Lima: pan crujiente con chicharrón de cerdo, camote frito y salsa criolla.",
  st:["Pon el cerdo con el agua, la sal y el ajo en una olla ancha. Hierve destapado 60 minutos, hasta que el agua se evapore.",
      "Deja que el cerdo se fría en su propia grasa 20 minutos, volteando, hasta que esté dorado y crujiente.",
      "Fríe las rodajas de camote en la grasa del cerdo 4 minutos, hasta que estén doradas.",
      "Mezcla la cebolla con el ají, el limón, el cilantro y una pizca de sal.",
      "Abre los panes y rellena con chicharrón, camote y la salsa criolla."],
  tp:["El agua cuece el cerdo y luego, al evaporarse, deja la grasa para freírlo: no añadas aceite.",
      "Remoja la cebolla en agua fría 10 minutos para quitarle el picor."],
  v:"pan con chicharron receta"},
 en:{n:"Pan con Chicharrón (Pork Crackling Sandwich)", b:"Sunday breakfast in Lima: crusty bread with pork crackling, fried sweet potato and salsa criolla.",
  st:["Put the pork with the water, salt and garlic in a wide pot. Boil uncovered for 60 minutes, until the water evaporates.",
      "Let the pork fry in its own fat for 20 minutes, turning, until golden and crisp.",
      "Fry the sweet potato slices in the pork fat for 4 minutes, until golden.",
      "Mix the onion with the chile, lime, cilantro and a pinch of salt.",
      "Split the rolls and fill with pork, sweet potato and the salsa."],
  tp:["The water cooks the pork, then evaporates and leaves the fat to fry it in: add no oil.",
      "Soak the onion in cold water for 10 minutes to take the bite off."],
  v:"pan con chicharron recipe"}},

{id:"juane", c:"Peru", ce:"Perú", r:"latin-america", m:"main", t:120, s:6,
 i:[[6,"thigh","chicken","protein","muslos de pollo","chicken thighs"],
    [2,"tsp","salt","salt","sal","salt"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [4,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"tsp","spice","aromatic","cúrcuma (palillo)","ground turmeric"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [500,"g","rice","structure","arroz blanco","white rice"],
    [1,"l","water","liquid","agua","water"],
    [3,"","egg","binder","huevos","eggs","batidos","beaten"],
    [3,"","egg","garnish","huevos duros","hard-boiled eggs","en mitades","halved"],
    [12,"","olives","garnish","aceitunas negras","black olives"],
    [12,"leaf","veg","serve","hojas de plátano o bijao","banana or bijao leaves","pasadas por la llama","passed over a flame"]],
 es:{n:"Juane", b:"El plato de la selva peruana para San Juan: arroz amarillo con pollo, huevo y aceituna, envuelto en hoja y hervido.",
  st:["Sala el pollo y dóralo en el aceite. Añade la cebolla, el ajo, la cúrcuma, el comino y el orégano y sofríe 5 minutos.",
      "Añade el arroz y el agua. Cuece tapado 20 minutos. Deja entibiar y mezcla con los huevos batidos.",
      "Cruza 2 hojas, pon una porción de arroz en el centro, un muslo, medio huevo duro y 2 aceitunas, y cubre con más arroz.",
      "Cierra las hojas formando una bolsa y amarra con pabilo.",
      "Hierve los juanes en agua con sal 40 minutos. Escurre y sirve abiertos en el plato."],
  tp:["Los huevos batidos unen el arroz para que el juane se corte en rebanadas.",
      "En la selva se sirve con plátano frito."],
  v:"juane receta"},
 en:{n:"Juane (Amazonian Rice Parcels)", b:"The Peruvian Amazon's dish for San Juan: yellow rice with chicken, egg and olive, wrapped in leaves and boiled.",
  st:["Salt the chicken and brown it in the oil. Add the onion, garlic, turmeric, cumin and oregano and cook 5 minutes.",
      "Add the rice and water. Cook covered 20 minutes. Cool slightly and mix with the beaten eggs.",
      "Cross 2 leaves, put a portion of rice in the centre, a thigh, half a boiled egg and 2 olives, and cover with more rice.",
      "Close the leaves into a pouch and tie with string.",
      "Boil the juanes in salted water for 40 minutes. Drain and serve opened on the plate."],
  tp:["The beaten eggs bind the rice so the juane slices cleanly.",
      "In the Amazon it comes with fried plantain."],
  v:"juane recipe"}},

{id:"arroz-tapado", c:"Peru", ce:"Perú", r:"latin-america", m:"main", t:50, s:4,
 i:[[300,"g","rice","structure","arroz blanco","white rice"],
    [600,"ml","water","liquid","agua","water"],
    [1.5,"tsp","salt","salt","sal","salt"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [400,"g","beef","protein","carne molida de res","ground beef"],
    [0.5,"","onion","aromatic","cebolla morada","red onion","picada","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"tbsp","ajipaste","aromatic","pasta de ají panca","ají panca paste"],
    [1,"","tomato","aromatic","tomate","tomato","picado","chopped"],
    [40,"g","driedfruit","sweet","pasas","raisins"],
    [8,"","olives","garnish","aceitunas negras","black olives","picadas","chopped"],
    [2,"","egg","garnish","huevos duros","hard-boiled eggs","picados","chopped"]],
 es:{n:"Arroz tapado", b:"Arroz blanco moldeado con un relleno de picadillo, pasas, aceituna y huevo en medio. Almuerzo de casa limeña.",
  st:["Cuece el arroz con el agua y 1 cucharadita de sal.",
      "Sofríe la cebolla, el ajo y el ají en el aceite 5 minutos. Añade la carne, el tomate y el resto de la sal y cuece 12 minutos. Añade las pasas, las aceitunas y el huevo.",
      "Engrasa una taza o molde. Pon una capa de arroz apretada, luego el relleno, y cubre con más arroz.",
      "Voltea sobre el plato y retira el molde.",
      "Sirve con plátano frito y salsa criolla."],
  tp:["Aprieta bien cada capa para que el arroz se sostenga al desmoldar.",
      "Un huevo frito encima lo convierte en arroz tapado a caballo."],
  v:"arroz tapado receta"},
 en:{n:"Arroz Tapado (Rice Mould with Picadillo)", b:"White rice moulded around a filling of beef picadillo, raisins, olive and egg. A Lima home lunch.",
  st:["Cook the rice with the water and 1 teaspoon of salt.",
      "Cook the onion, garlic and ají in the oil for 5 minutes. Add the beef, tomato and the rest of the salt and cook 12 minutes. Add the raisins, olives and egg.",
      "Grease a cup or mould. Press in a layer of rice, then the filling, and cover with more rice.",
      "Turn out onto the plate and lift off the mould.",
      "Serve with fried plantain and salsa criolla."],
  tp:["Press each layer firmly so the rice holds when turned out.",
      "A fried egg on top makes it arroz tapado a caballo."],
  v:"arroz tapado recipe"}}
];
