module.exports = [
{id:"carapulcra", c:"Peru", ce:"Perú", r:"latin-america", m:"main", t:120, s:6,
 i:[[400,"g","potato","structure","papa seca","dried potato (papa seca)"],
    [800,"g","pork","protein","carne de cerdo","pork shoulder","en cubos","cubed"],
    [2,"tsp","salt","salt","sal","salt"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla morada","red onion","picada","chopped"],
    [4,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [3,"tbsp","ajipaste","aromatic","pasta de ají panca","ají panca paste"],
    [1,"tbsp","ajipaste","aromatic","pasta de ají mirasol","ají mirasol paste"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [60,"g","peanut","thicken","maní tostado","roasted peanuts","molido","ground"],
    [2,"","spice","aromatic","clavos de olor","cloves"],
    [0.25,"tsp","spice","aromatic","canela molida","ground cinnamon"],
    [1.5,"l","water","liquid","agua","water"]],
 es:{n:"Carapulcra", b:"Guiso afroperuano de papa seca tostada con cerdo, ají panca y maní. Espeso, rojizo y con un fondo dulce de clavo y canela.",
  st:["Tuesta la papa seca en un sartén seco 5 minutos, moviendo, hasta que huela a nuez. Remójala en agua 30 minutos y escurre.",
      "Sala el cerdo y dóralo en el aceite 10 minutos. Sácalo.",
      "Sofríe la cebolla, el ajo, los ajíes y el comino 10 minutos.",
      "Regresa el cerdo con la papa seca, el maní, el clavo, la canela y el agua.",
      "Cuece a fuego bajo 60 minutos, moviendo seguido para que no se pegue, hasta que la papa esté suave y espesa. Añade agua si hace falta."],
  tp:["La papa seca se pega fácil: mueve cada 5 minutos y raspa el fondo.",
      "Se sirve con arroz y sopa seca en la tradición de Chincha."],
  v:"carapulcra receta"},
 en:{n:"Carapulcra (Dried Potato and Pork Stew)", b:"An Afro-Peruvian stew of toasted dried potato with pork, ají panca and peanuts. Thick, reddish and with a sweet undertone of clove and cinnamon.",
  st:["Toast the dried potato in a dry pan for 5 minutes, stirring, until it smells nutty. Soak it in water for 30 minutes and drain.",
      "Salt the pork and brown it in the oil for 10 minutes. Remove.",
      "Cook the onion, garlic, ají pastes and cumin for 10 minutes.",
      "Return the pork with the dried potato, peanuts, cloves, cinnamon and water.",
      "Simmer on low for 60 minutes, stirring often so it doesn't stick, until the potato is soft and thick. Add water if needed."],
  tp:["Dried potato sticks easily: stir every 5 minutes and scrape the bottom.",
      "In the Chincha tradition it's served with rice and sopa seca."],
  v:"carapulcra recipe"}},

{id:"rocoto-relleno", c:"Peru", ce:"Perú", r:"latin-america", m:"main", t:90, s:6, o:180,
 i:[[6,"","chilli","structure","rocotos","rocoto peppers"],
    [4,"tbsp","sugar","preserve","azúcar","sugar","para el blanqueado","for blanching"],
    [120,"ml","whitevinegar","preserve","vinagre blanco","white vinegar","para el blanqueado","for blanching"],
    [500,"g","beef","protein","carne molida de res","ground beef"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla morada","red onion","picada","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"tbsp","ajipaste","aromatic","pasta de ají panca","ají panca paste"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [1,"tsp","salt","salt","sal","salt"],
    [40,"g","peanut","crunch","maní tostado","roasted peanuts","picado","chopped"],
    [40,"g","driedfruit","sweet","pasas","raisins"],
    [2,"","egg","garnish","huevos duros","hard-boiled eggs","picados","chopped"],
    [6,"","olives","garnish","aceitunas negras","black olives"],
    [6,"slice","queso","protein","queso fresco","queso fresco","en tajadas","sliced"],
    [200,"ml","evaporatedmilk","set","leche evaporada","evaporated milk"],
    [2,"","egg","set","huevos","eggs","para la mezcla de leche","for the milk mixture"]],
 es:{n:"Rocoto relleno arequipeño", b:"Rocotos rellenos de un picadillo de carne con maní y pasas, cubiertos de queso y horneados en leche con huevo. Picante de Arequipa.",
  st:["Corta la tapa de los rocotos y quita semillas y venas. Hiérvelos 5 minutos en agua con la mitad del azúcar y del vinagre. Escurre y repite con agua nueva y el resto. Esto baja el picante.",
      "Sofríe la cebolla, el ajo, el ají panca y el comino en el aceite 8 minutos. Añade la carne y la sal y cuece 10 minutos. Añade el maní y las pasas.",
      "Rellena los rocotos con la carne, un trozo de huevo y una aceituna. Pon una tajada de queso encima.",
      "Calienta el horno a 180 °C. Pon los rocotos en una fuente con sus tapas al lado.",
      "Bate la leche con los huevos y viértela alrededor. Hornea 25 minutos, hasta que el queso se funda y la leche cuaje.",
      "Sirve con pastel de papa o papas doradas."],
  tp:["Usa guantes para limpiar los rocotos: queman la piel y los ojos.",
      "Si los quieres más suaves, blanquéalos una tercera vez."],
  v:"rocoto relleno receta"},
 en:{n:"Arequipa Stuffed Rocoto Peppers", b:"Rocoto peppers stuffed with a beef picadillo with peanuts and raisins, topped with cheese and baked in egg and milk. Arequipa heat.",
  st:["Cut the tops off the rocotos and remove the seeds and veins. Boil them 5 minutes in water with half the sugar and vinegar. Drain and repeat with fresh water and the rest. This tames the heat.",
      "Cook the onion, garlic, ají panca and cumin in the oil for 8 minutes. Add the beef and salt and cook 10 minutes. Add the peanuts and raisins.",
      "Fill the rocotos with the beef, a piece of egg and an olive. Put a slice of cheese on top.",
      "Heat the oven to 180 °C. Set the rocotos in a dish with their tops beside them.",
      "Whisk the milk with the eggs and pour around them. Bake 25 minutes, until the cheese melts and the milk sets.",
      "Serve with potato gratin or browned potatoes."],
  tp:["Wear gloves to clean rocotos: they burn skin and eyes.",
      "For milder ones, blanch them a third time."],
  v:"rocoto relleno recipe"}},

{id:"tacu-tacu", c:"Peru", ce:"Perú", r:"latin-america", m:"main", t:30, s:4,
 i:[[500,"g","legume","protein","frijoles canarios cocidos","cooked canary beans"],
    [400,"g","rice","structure","arroz blanco cocido","cooked white rice"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [0.5,"","onion","aromatic","cebolla morada","red onion","picada","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"tbsp","ajipaste","aromatic","pasta de ají amarillo","ají amarillo paste"],
    [0.5,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [1,"tsp","salt","salt","sal","salt"],
    [4,"","egg","garnish","huevos","eggs","fritos","fried"],
    [2,"","plantain","garnish","plátanos maduros","ripe plantains","fritos","fried"]],
 es:{n:"Tacu tacu", b:"Frijoles y arroz sobrantes aplastados y dorados en sartén como una tortilla gruesa y crujiente. Con huevo frito y plátano.",
  st:["Sofríe la cebolla, el ajo y el ají en 1 cucharada de aceite 5 minutos.",
      "Añade los frijoles, aplasta la mitad con un tenedor, y el orégano y la sal. Mezcla con el arroz.",
      "Calienta el resto del aceite en un sartén. Pon la mezcla y dale forma de óvalo alargado moviendo el sartén.",
      "Dora 5 minutos, voltéalo con ayuda de un plato y dora 5 minutos más, hasta que tenga costra.",
      "Sirve con huevo frito y plátano."],
  tp:["Los frijoles medio aplastados son el pegamento: si están enteros, se desarma.",
      "Con lomo saltado encima es un clásico de Lima."],
  v:"tacu tacu receta"},
 en:{n:"Tacu Tacu (Crispy Rice and Beans)", b:"Leftover beans and rice mashed and browned in a pan like a thick, crusty omelette. With a fried egg and plantain.",
  st:["Cook the onion, garlic and ají in 1 tablespoon of oil for 5 minutes.",
      "Add the beans, mashing half with a fork, plus the oregano and salt. Mix with the rice.",
      "Heat the rest of the oil in a pan. Add the mixture and shape it into a long oval by shaking the pan.",
      "Brown 5 minutes, flip it using a plate and brown 5 minutes more, until crusted.",
      "Serve with fried egg and plantain."],
  tp:["Half-mashed beans are the glue: whole, it falls apart.",
      "With lomo saltado on top it's a Lima classic."],
  v:"tacu tacu recipe"}},

{id:"tallarines-verdes", c:"Peru", ce:"Perú", r:"latin-america", m:"main", t:30, s:4,
 i:[[400,"g","pasta","structure","tallarines","linguine"],
    [150,"g","veg","aromatic","espinaca","spinach"],
    [1,"bunch","herb","aromatic","albahaca","basil"],
    [150,"g","queso","protein","queso fresco","queso fresco"],
    [120,"ml","evaporatedmilk","liquid","leche evaporada","evaporated milk"],
    [0.5,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic"],
    [60,"ml","oil","fat","aceite","oil"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Tallarines verdes", b:"El pesto peruano: espinaca, albahaca, queso fresco y leche evaporada licuados sobre tallarines. Sin piñones.",
  st:["Hierve la espinaca y la albahaca 30 segundos y pásalas a agua con hielo. Escurre.",
      "Sofríe la cebolla y el ajo en 2 cucharadas del aceite 5 minutos.",
      "Licúa las hojas, el sofrito, el queso, la leche, el resto del aceite y la sal hasta que esté liso.",
      "Cuece la pasta en agua con sal. Escurre y guarda un poco del agua.",
      "Mezcla la pasta con la salsa en la olla a fuego bajo 1 minuto, con agua de la pasta si hace falta."],
  tp:["El blanqueado rápido mantiene el verde brillante.",
      "Con un bistec encima es el menú de los domingos."],
  v:"tallarines verdes receta"},
 en:{n:"Tallarines Verdes (Peruvian Pesto Pasta)", b:"Peru's pesto: spinach, basil, queso fresco and evaporated milk blended over linguine. No pine nuts.",
  st:["Blanch the spinach and basil for 30 seconds and plunge into ice water. Drain.",
      "Cook the onion and garlic in 2 tablespoons of the oil for 5 minutes.",
      "Blend the leaves, the onion mixture, cheese, milk, the rest of the oil and salt until smooth.",
      "Cook the pasta in salted water. Drain, keeping a little of the water.",
      "Toss the pasta with the sauce in the pot over low heat for 1 minute, with pasta water if needed."],
  tp:["Quick blanching keeps the green bright.",
      "With a steak on top it's the Sunday lunch."],
  v:"tallarines verdes recipe"}},

{id:"pollo-a-la-brasa", c:"Peru", ce:"Perú", r:"latin-america", m:"main", t:120, s:4, o:200,
 i:[[1.6,"kg","chicken","protein","pollo entero","whole chicken"],
    [3,"tbsp","soysauce","umami","sillao (salsa de soja)","soy sauce (sillao)"],
    [2,"","citrus","acid","limones","limes","en jugo","juiced"],
    [6,"clove","garlic","aromatic","ajo","garlic","molido","crushed"],
    [2,"tbsp","ajipaste","aromatic","pasta de ají panca","ají panca paste"],
    [2,"tsp","spice","aromatic","comino molido","ground cumin"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [1,"tsp","paprika","aromatic","pimentón","paprika"],
    [1,"tsp","pepper","aromatic","pimienta negra","black pepper"],
    [1,"tsp","salt","salt","sal","salt"],
    [2,"tbsp","oil","fat","aceite","oil"]],
 es:{n:"Pollo a la brasa", b:"El pollo asado de Perú: marinado en sillao, ají panca, ajo y comino, y asado hasta quedar con piel oscura y crujiente.",
  st:["Mezcla todos los ingredientes menos el pollo hasta tener una pasta.",
      "Abre el pollo por la espalda y aplánalo. Úntalo con la marinada, también bajo la piel. Refrigera toda la noche.",
      "Calienta el horno a 200 °C. Pon el pollo sobre una rejilla encima de una bandeja, con la piel arriba.",
      "Asa 50 a 60 minutos, hasta que la piel esté muy dorada y los jugos del muslo salgan claros.",
      "Reposa 10 minutos y sirve con papas fritas, ensalada y ají verde."],
  tp:["La rejilla deja que el aire rodee el pollo: sin ella, la parte de abajo queda cocida al vapor.",
      "La noche de marinada es lo que da sabor hasta el hueso."],
  v:"pollo a la brasa en horno receta"},
 en:{n:"Peruvian Roast Chicken (Pollo a la Brasa)", b:"Peru's roast chicken: marinated in soy sauce, ají panca, garlic and cumin and roasted until the skin is dark and crisp.",
  st:["Mix everything except the chicken into a paste.",
      "Split the chicken down the back and flatten it. Rub it with the marinade, under the skin too. Chill overnight.",
      "Heat the oven to 200 °C. Set the chicken skin-side up on a rack over a tray.",
      "Roast 50 to 60 minutes, until the skin is deep golden and the thigh juices run clear.",
      "Rest 10 minutes and serve with fries, salad and ají verde."],
  tp:["The rack lets air circulate: without it, the underside steams.",
      "The overnight marinade is what flavours it to the bone."],
  v:"peruvian chicken recipe"}},

{id:"aji-verde", c:"Peru", ce:"Perú", r:"latin-america", m:"sauce", t:10, s:8,
 i:[[2,"","chilli","aromatic","chiles jalapeños","jalapeño chiles","sin semillas","seeded"],
    [1,"bunch","herb","aromatic","cilantro","cilantro"],
    [4,"tbsp","mayo","fat","mayonesa","mayonnaise"],
    [30,"g","queso","umami","queso fresco o parmesano","queso fresco or parmesan"],
    [1,"clove","garlic","aromatic","ajo","garlic"],
    [1,"","citrus","acid","limón","lime","en jugo","juiced"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [0.5,"tsp","salt","salt","sal","salt"]],
 es:{n:"Ají verde de pollería", b:"La salsa verde cremosa de las pollerías: jalapeño, cilantro, mayonesa y queso licuados.",
  st:["Licúa todo hasta que quede liso y de un verde intenso.",
      "Prueba y ajusta sal y limón.",
      "Refrigera 15 minutos antes de servir."],
  tp:["Con semillas queda más picante.",
      "Dura 3 días en el refrigerador."],
  v:"aji verde peruano receta"},
 en:{n:"Peruvian Green Sauce (Ají Verde)", b:"The creamy green sauce of Peruvian chicken shops: jalapeño, cilantro, mayonnaise and cheese blended.",
  st:["Blend everything until smooth and deep green.",
      "Taste and adjust salt and lime.",
      "Chill 15 minutes before serving."],
  tp:["Leave the seeds in for more heat.",
      "Keeps 3 days in the fridge."],
  v:"peruvian green sauce recipe"}},

{id:"chupe-de-camarones", c:"Peru", ce:"Perú", r:"latin-america", m:"soup", t:60, s:6,
 i:[[500,"g","shrimp","protein","camarones","shrimp","pelados","peeled"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"tbsp","ajipaste","aromatic","pasta de ají panca","ají panca paste"],
    [1,"","tomato","aromatic","tomate","tomato","picado","chopped"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [1.5,"l","fishstock","liquid","caldo de pescado","fish stock"],
    [500,"g","potato","structure","papas amarillas","yellow potatoes","en cubos","cubed"],
    [2,"","corn","protein","choclos","ears of corn","en rodajas","in rounds"],
    [60,"g","rice","thicken","arroz","rice"],
    [100,"g","legume","protein","arvejas","peas"],
    [200,"ml","evaporatedmilk","enrich","leche evaporada","evaporated milk"],
    [100,"g","queso","enrich","queso fresco","queso fresco","en cubos","cubed"],
    [4,"","egg","protein","huevos","eggs"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"handful","herb","garnish","huacatay o cilantro","huacatay or cilantro","picado","chopped"]],
 es:{n:"Chupe de camarones", b:"La sopa espesa de Arequipa con camarones, papa, choclo, leche, queso y huevo escalfado. Una comida en un plato.",
  st:["Sofríe la cebolla, el ajo, el ají panca, el tomate y el orégano en el aceite 10 minutos.",
      "Añade el caldo y hierve. Añade la papa, el choclo y el arroz y cuece 15 minutos.",
      "Añade las arvejas y cuece 5 minutos.",
      "Baja el fuego. Rompe los huevos dentro de la sopa uno a uno y cuece 3 minutos sin mover.",
      "Añade los camarones y cuece 2 minutos. Añade la leche, el queso y la sal y calienta sin hervir.",
      "Sirve con huacatay picado, con 1 huevo por plato."],
  tp:["Si la sopa hierve después de la leche, se corta.",
      "Las cabezas de camarón dan el caldo más sabroso: hiérvelas 20 minutos y cuela."],
  v:"chupe de camarones receta"},
 en:{n:"Shrimp Chupe (Arequipa Shrimp Chowder)", b:"Arequipa's thick soup of shrimp, potato, corn, milk, cheese and a poached egg. A meal in a bowl.",
  st:["Cook the onion, garlic, ají panca, tomato and oregano in the oil for 10 minutes.",
      "Add the stock and bring to a boil. Add the potato, corn and rice and cook 15 minutes.",
      "Add the peas and cook 5 minutes.",
      "Lower the heat. Crack the eggs into the soup one at a time and cook 3 minutes without stirring.",
      "Add the shrimp and cook 2 minutes. Add the milk, cheese and salt and heat without boiling.",
      "Serve with chopped huacatay, 1 egg per bowl."],
  tp:["If the soup boils after the milk goes in, it curdles.",
      "Shrimp heads make the tastiest stock: boil them 20 minutes and strain."],
  v:"chupe de camarones recipe"}},

{id:"parihuela", c:"Peru", ce:"Perú", r:"latin-america", m:"soup", t:60, s:6,
 i:[[500,"g","whitefish","protein","pescado blanco firme","firm white fish","en trozos","in pieces"],
    [300,"g","shrimp","protein","camarones o langostinos","shrimp or prawns"],
    [2,"","crab","protein","cangrejos","crabs","partidos","halved"],
    [300,"g","mussel","protein","choros (mejillones)","mussels","limpios","cleaned"],
    [200,"g","squid","protein","calamar","squid","en aros","in rings"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla morada","red onion","picada","chopped"],
    [4,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"tbsp","ajipaste","aromatic","pasta de ají panca","ají panca paste"],
    [1,"tbsp","ajipaste","aromatic","pasta de ají amarillo","ají amarillo paste"],
    [3,"","tomato","aromatic","tomates","tomatoes","picados","chopped"],
    [150,"ml","winewhite","liquid","vino blanco","white wine"],
    [1.5,"l","fishstock","liquid","caldo de pescado","fish stock"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"handful","herb","garnish","cilantro","cilantro","picado","chopped"],
    [2,"","citrus","garnish","limones","limes"]],
 es:{n:"Parihuela", b:"La sopa de mariscos más potente del Perú: pescado, cangrejo, choros, calamar y camarones en un caldo rojo de ají panca y tomate.",
  st:["Sofríe la cebolla, el ajo, los ajíes y el tomate en el aceite 10 minutos.",
      "Añade el vino y reduce 3 minutos. Añade el caldo y los cangrejos y hierve 10 minutos.",
      "Añade los choros, tapa y cuece 4 minutos, hasta que se abran. Tira los que sigan cerrados.",
      "Añade el pescado y el calamar, 3 minutos. Añade los camarones, 2 minutos.",
      "Añade la sal, apaga y sirve con cilantro y limón."],
  tp:["Los cangrejos van primero porque dan sabor al caldo.",
      "Tradicionalmente lleva chicha de jora en vez de vino."],
  v:"parihuela receta"},
 en:{n:"Parihuela (Peruvian Seafood Soup)", b:"Peru's most powerful seafood soup: fish, crab, mussels, squid and shrimp in a red broth of ají panca and tomato.",
  st:["Cook the onion, garlic, ají pastes and tomato in the oil for 10 minutes.",
      "Add the wine and reduce 3 minutes. Add the stock and crabs and boil 10 minutes.",
      "Add the mussels, cover and cook 4 minutes, until they open. Discard any that stay shut.",
      "Add the fish and squid, 3 minutes. Add the shrimp, 2 minutes.",
      "Add the salt, turn off and serve with cilantro and lime."],
  tp:["The crabs go first because they flavour the broth.",
      "Traditionally it uses chicha de jora instead of wine."],
  v:"parihuela recipe"}},

{id:"sopa-criolla", c:"Peru", ce:"Perú", r:"latin-america", m:"soup", t:35, s:4,
 i:[[250,"g","beef","protein","carne de res","beef","en tiras finas","in thin strips"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [0.5,"","onion","aromatic","cebolla morada","red onion","picada","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"tbsp","ajipaste","aromatic","pasta de ají panca","ají panca paste"],
    [1,"","tomato","aromatic","tomate","tomato","picado","chopped"],
    [1.2,"l","water","liquid","agua","water"],
    [100,"g","pasta","structure","cabellos de ángel","angel hair pasta"],
    [150,"ml","evaporatedmilk","enrich","leche evaporada","evaporated milk"],
    [4,"","egg","protein","huevos","eggs"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [1,"tsp","salt","salt","sal","salt"],
    [4,"slice","bread","serve","pan","bread","tostado","toasted"]],
 es:{n:"Sopa criolla", b:"Sopa limeña de carne con cabellos de ángel, leche y un huevo escalfado, con pan tostado. Reconfortante y rápida.",
  st:["Saltea la carne en el aceite 3 minutos. Añade la cebolla, el ajo, el ají y el tomate y cuece 5 minutos.",
      "Añade el agua y la sal y hierve 10 minutos.",
      "Añade la pasta y cuece 4 minutos.",
      "Baja el fuego, rompe los huevos dentro y cuece 3 minutos. Añade la leche y el orégano y calienta sin hervir.",
      "Sirve con 1 huevo por plato y pan tostado."],
  tp:["Frota el orégano entre las manos al echarlo para despertar su aroma.",
      "Rompe la pasta en trozos cortos para comerla con cuchara."],
  v:"sopa criolla peruana receta"},
 en:{n:"Sopa Criolla (Peruvian Beef Noodle Soup)", b:"A Lima soup of beef, angel hair pasta, milk and a poached egg, with toast. Comforting and quick.",
  st:["Stir-fry the beef in the oil for 3 minutes. Add the onion, garlic, ají and tomato and cook 5 minutes.",
      "Add the water and salt and boil 10 minutes.",
      "Add the pasta and cook 4 minutes.",
      "Lower the heat, crack in the eggs and cook 3 minutes. Add the milk and oregano and heat without boiling.",
      "Serve with 1 egg per bowl and toast."],
  tp:["Rub the oregano between your hands as you add it to wake up its aroma.",
      "Break the pasta into short pieces so it's easy to eat with a spoon."],
  v:"sopa criolla recipe"}},

{id:"papas-rellenas", c:"Peru", ce:"Perú", r:"latin-america", m:"snack", t:90, s:6,
 i:[[1,"kg","potato","structure","papas blancas harinosas","floury white potatoes"],
    [1.5,"tsp","salt","salt","sal","salt"],
    [300,"g","beef","protein","carne molida de res","ground beef"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [0.5,"","onion","aromatic","cebolla morada","red onion","picada","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"tbsp","ajipaste","aromatic","pasta de ají panca","ají panca paste"],
    [0.5,"tsp","spice","aromatic","comino molido","ground cumin"],
    [40,"g","driedfruit","sweet","pasas","raisins"],
    [2,"","egg","garnish","huevos duros","hard-boiled eggs","picados","chopped"],
    [8,"","olives","garnish","aceitunas negras","black olives","picadas","chopped"],
    [60,"g","apflour","dredge","harina de trigo","all-purpose flour"],
    [1,"","egg","dredge","huevo","egg","batido","beaten"],
    [1,"l","oil","fat","aceite","oil","para freír","for frying"]],
 es:{n:"Papas rellenas", b:"Croquetas grandes de puré de papa rellenas de picadillo con huevo, aceituna y pasas, fritas hasta dorar. Con salsa criolla.",
  st:["Hierve las papas con piel 25 minutos. Pélalas calientes, haz puré y mezcla con 1 cucharadita de sal. Enfría.",
      "Sofríe la cebolla, el ajo, el ají y el comino en 2 cucharadas de aceite 5 minutos. Añade la carne y el resto de la sal y cuece 10 minutos. Añade las pasas. Enfría y mezcla con el huevo y las aceitunas.",
      "Con las manos húmedas, aplana una porción de puré en la palma, pon 1 cucharada de relleno, cierra y dale forma de papa.",
      "Pasa cada papa por harina, luego por huevo batido.",
      "Fríe en aceite a 180 °C 4 minutos, girándolas, hasta que estén doradas. Escurre y sirve con salsa criolla."],
  tp:["El puré debe estar frío para que se pueda moldear.",
      "Con las manos húmedas el puré no se pega."],
  v:"papas rellenas peruanas receta"},
 en:{n:"Papas Rellenas (Stuffed Potato Croquettes)", b:"Large mashed potato croquettes stuffed with beef picadillo, egg, olive and raisins, fried until golden. With salsa criolla.",
  st:["Boil the potatoes in their skins for 25 minutes. Peel hot, mash and mix with 1 teaspoon of salt. Cool.",
      "Cook the onion, garlic, ají and cumin in 2 tablespoons of oil for 5 minutes. Add the beef and the rest of the salt and cook 10 minutes. Add the raisins. Cool and mix with the egg and olives.",
      "With wet hands, flatten a portion of mash in your palm, add 1 tablespoon of filling, close and shape like a potato.",
      "Roll each one in flour, then in beaten egg.",
      "Fry in oil at 180 °C for 4 minutes, turning, until golden. Drain and serve with salsa criolla."],
  tp:["The mash must be cold to hold its shape.",
      "Wet hands keep the mash from sticking."],
  v:"papas rellenas recipe"}}
];
