module.exports = [
{id:"tiradito", c:"Peru", ce:"Perú", r:"latin-america", m:"starter", t:25, s:4,
 i:[[500,"g","whitefish","protein","pescado blanco muy fresco (corvina o lenguado)","very fresh white fish (corvina or sole)","en láminas finas","in thin slices"],
    [8,"","citrus","acid","limones","limes","en jugo","juiced"],
    [2,"tbsp","ajipaste","aromatic","pasta de ají amarillo","ají amarillo paste"],
    [1,"tsp","herb","aromatic","jengibre","ginger","rallado","grated"],
    [1,"clove","garlic","aromatic","ajo","garlic","rallado","grated"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"handful","herb","garnish","cilantro","cilantro","hojas","leaves"],
    [1,"","corn","garnish","choclo cocido","cooked Peruvian corn","desgranado","kernels"]],
 es:{n:"Tiradito de ají amarillo", b:"Láminas de pescado crudo cortadas como sashimi, bañadas en una leche de ají amarillo y limón. El ceviche con técnica japonesa.",
  st:["Extiende las láminas de pescado en platos fríos, sin encimarlas. Refrigera.",
      "Licúa el jugo de limón con la pasta de ají, el jengibre, el ajo y la sal hasta que esté liso. Cuela.",
      "Justo antes de servir, baña el pescado con la salsa.",
      "Decora con cilantro y choclo y sirve de inmediato."],
  tp:["El pescado crudo debe ser muy fresco o haberse congelado antes; en embarazo o con defensas bajas, no lo comas crudo.",
      "Corta con un cuchillo muy afilado en un solo movimiento para que las láminas queden limpias."],
  v:"tiradito de aji amarillo receta"},
 en:{n:"Ají Amarillo Tiradito", b:"Slices of raw fish cut like sashimi and bathed in an ají amarillo and lime sauce. Ceviche with Japanese technique.",
  st:["Lay the fish slices on cold plates without overlapping. Chill.",
      "Blend the lime juice with the ají paste, ginger, garlic and salt until smooth. Strain.",
      "Just before serving, spoon the sauce over the fish.",
      "Garnish with cilantro and corn and serve right away."],
  tp:["Raw fish must be very fresh or previously frozen; if pregnant or immunocompromised, don't eat it raw.",
      "Slice with a very sharp knife in one stroke so the slices are clean."],
  v:"tiradito recipe"}},

{id:"leche-de-tigre", c:"Peru", ce:"Perú", r:"latin-america", m:"starter", t:20, s:4,
 i:[[150,"g","whitefish","protein","recortes de pescado blanco muy fresco","very fresh white fish trimmings"],
    [10,"","citrus","acid","limones","limes","en jugo","juiced"],
    [1,"stalk","celery","aromatic","apio","celery"],
    [0.25,"","onion","aromatic","cebolla morada","red onion"],
    [1,"clove","garlic","aromatic","ajo","garlic"],
    [1,"tsp","herb","aromatic","jengibre","ginger"],
    [1,"","chilli","aromatic","ají limo o habanero","ají limo or habanero"],
    [1,"handful","herb","aromatic","cilantro","cilantro"],
    [1,"tsp","salt","salt","sal","salt"],
    [4,"","ice","liquid","cubos de hielo","ice cubes"],
    [200,"g","whitefish","protein","pescado blanco en cubos","white fish in cubes","para servir","to serve"]],
 es:{n:"Leche de tigre", b:"El jugo del ceviche servido solo en vaso: limón, pescado, ají y cilantro licuados con hielo. Famoso por levantar muertos.",
  st:["Licúa los recortes de pescado, el limón, el apio, la cebolla, el ajo, el jengibre, el ají, el cilantro, la sal y el hielo 30 segundos.",
      "Cuela apretando.",
      "Mezcla con los cubos de pescado y deja 2 minutos.",
      "Sirve en vasos fríos con un poco de cebolla y cilantro encima."],
  tp:["Licúa poco tiempo: mucho licuado amarga el limón.",
      "El pescado crudo debe ser muy fresco o haberse congelado antes; en embarazo o con defensas bajas, evítalo."],
  v:"leche de tigre receta"},
 en:{n:"Leche de Tigre", b:"Ceviche's marinade served on its own in a glass: lime, fish, chile and cilantro blended with ice. Famous as a hangover cure.",
  st:["Blend the fish trimmings, lime, celery, onion, garlic, ginger, chile, cilantro, salt and ice for 30 seconds.",
      "Strain, pressing.",
      "Mix with the fish cubes and leave 2 minutes.",
      "Serve in cold glasses with a little onion and cilantro on top."],
  tp:["Blend briefly: over-blending makes the lime bitter.",
      "Raw fish must be very fresh or previously frozen; if pregnant or immunocompromised, avoid it."],
  v:"leche de tigre recipe"}},

{id:"aji-de-gallina", c:"Peru", ce:"Perú", r:"latin-america", m:"main", t:75, s:6,
 i:[[1,"kg","chicken","protein","pechugas de pollo o gallina","chicken or hen breasts"],
    [1.5,"l","water","liquid","agua","water"],
    [2,"tsp","salt","salt","sal","salt"],
    [4,"slice","bread","thicken","pan de molde sin corteza","crustless sandwich bread"],
    [400,"ml","evaporatedmilk","liquid","leche evaporada","evaporated milk"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada fina","finely chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [4,"tbsp","ajipaste","aromatic","pasta de ají amarillo","ají amarillo paste"],
    [60,"g","walnut","thicken","nueces","walnuts","molidas","ground"],
    [50,"g","parmesan","umami","queso parmesano rallado","grated parmesan"],
    [800,"g","potato","serve","papas amarillas","yellow potatoes","cocidas, en rodajas","boiled, sliced"],
    [3,"","egg","garnish","huevos duros","hard-boiled eggs","en cuartos","quartered"],
    [12,"","olives","garnish","aceitunas negras","black olives"]],
 es:{n:"Ají de gallina", b:"Pollo desmechado en una crema amarilla de ají, pan remojado en leche, nueces y parmesano. Sobre papa, con huevo y aceituna.",
  st:["Cuece el pollo en el agua con 1 cucharadita de sal 25 minutos. Desmecha y guarda 250 ml del líquido.",
      "Remoja el pan en la leche evaporada 10 minutos y licúalo.",
      "Sofríe la cebolla y el ajo en el aceite 10 minutos a fuego bajo, hasta que estén dorados. Añade el ají y cuece 5 minutos.",
      "Añade el pan licuado y el líquido guardado y cuece 10 minutos, moviendo, hasta que espese.",
      "Añade el pollo, las nueces, el parmesano y el resto de la sal. Cuece 5 minutos.",
      "Sirve sobre las papas con huevo, aceitunas y arroz blanco."],
  tp:["La cebolla bien dorada es la base: no la apures.",
      "Si espesa demasiado al recalentar, añade un poco de leche o agua."],
  v:"aji de gallina receta"},
 en:{n:"Ají de Gallina (Peruvian Creamy Chicken)", b:"Shredded chicken in a yellow cream of ají amarillo, milk-soaked bread, walnuts and parmesan. Over potatoes, with egg and olives.",
  st:["Poach the chicken in the water with 1 teaspoon of salt for 25 minutes. Shred and keep 250 ml of the liquid.",
      "Soak the bread in the evaporated milk for 10 minutes and blend.",
      "Cook the onion and garlic in the oil for 10 minutes on low, until golden. Add the ají and cook 5 minutes.",
      "Add the blended bread and reserved liquid and cook 10 minutes, stirring, until thick.",
      "Add the chicken, walnuts, parmesan and the rest of the salt. Cook 5 minutes.",
      "Serve over the potatoes with egg, olives and white rice."],
  tp:["Well-browned onion is the base: don't rush it.",
      "If it thickens too much when reheated, add a little milk or water."],
  v:"aji de gallina recipe"}},

{id:"causa-limena", c:"Peru", ce:"Perú", r:"latin-america", m:"starter", t:60, s:6,
 i:[[1,"kg","potato","structure","papas amarillas","yellow potatoes"],
    [3,"tbsp","ajipaste","aromatic","pasta de ají amarillo","ají amarillo paste"],
    [3,"","citrus","acid","limones","limes","en jugo","juiced"],
    [60,"ml","oil","fat","aceite","oil"],
    [1.5,"tsp","salt","salt","sal","salt"],
    [300,"g","chicken","protein","pollo cocido desmechado","shredded cooked chicken"],
    [4,"tbsp","mayo","fat","mayonesa","mayonnaise"],
    [0.25,"","onion","aromatic","cebolla morada","red onion","picada fina","finely chopped"],
    [2,"","avocado","protein","aguacates (paltas)","avocados","en rebanadas","sliced"],
    [2,"","egg","garnish","huevos duros","hard-boiled eggs","en rodajas","sliced"],
    [6,"","olives","garnish","aceitunas negras","black olives"]],
 es:{n:"Causa limeña", b:"Capas frías de puré de papa amarilla con ají y limón, rellenas de pollo con mayonesa y palta.",
  st:["Hierve las papas con piel 25 minutos, hasta que estén blandas. Pélalas calientes y pásalas por un pasapurés.",
      "Deja enfriar y amasa con el ají, el limón, el aceite y 1 cucharadita de sal, hasta tener una masa lisa.",
      "Mezcla el pollo con la mayonesa, la cebolla y el resto de la sal.",
      "En un molde con plástico, pon una capa de papa, luego el pollo, luego la palta, y termina con papa.",
      "Refrigera 30 minutos, desmolda y decora con huevo y aceitunas."],
  tp:["Pela y machaca las papas calientes: frías se ponen pegajosas.",
      "Se arma hasta 1 día antes y se guarda tapada en el refrigerador."],
  v:"causa limeña receta"},
 en:{n:"Causa Limeña (Layered Potato Terrine)", b:"Cold layers of yellow potato mash with ají and lime, filled with chicken in mayonnaise and avocado.",
  st:["Boil the potatoes in their skins for 25 minutes, until soft. Peel them hot and pass through a ricer.",
      "Cool and knead with the ají, lime, oil and 1 teaspoon of salt, into a smooth dough.",
      "Mix the chicken with the mayonnaise, onion and the rest of the salt.",
      "In a plastic-lined mould, lay a layer of potato, then the chicken, then the avocado, and finish with potato.",
      "Chill 30 minutes, turn out and garnish with egg and olives."],
  tp:["Peel and mash the potatoes hot: cold, they turn gluey.",
      "It can be assembled up to 1 day ahead and kept covered in the fridge."],
  v:"causa limena recipe"}},

{id:"papa-a-la-huancaina", c:"Peru", ce:"Perú", r:"latin-america", m:"starter", t:40, s:4,
 i:[[800,"g","potato","structure","papas amarillas","yellow potatoes"],
    [4,"tbsp","ajipaste","aromatic","pasta de ají amarillo","ají amarillo paste"],
    [200,"g","queso","protein","queso fresco","queso fresco"],
    [150,"ml","evaporatedmilk","liquid","leche evaporada","evaporated milk"],
    [4,"","crackers","thicken","galletas de soda","soda crackers"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [0.5,"tsp","salt","salt","sal","salt"],
    [2,"","egg","garnish","huevos duros","hard-boiled eggs","en mitades","halved"],
    [8,"","olives","garnish","aceitunas negras","black olives"],
    [4,"leaf","veg","garnish","hojas de lechuga","lettuce leaves"]],
 es:{n:"Papa a la huancaína", b:"Papas amarillas frías bañadas en una salsa cremosa de ají amarillo y queso fresco. Con huevo y aceituna.",
  st:["Hierve las papas con piel 25 minutos. Pélalas, enfría y corta en rodajas gruesas.",
      "Licúa el ají, el queso, la leche, las galletas, el aceite y la sal hasta que esté liso y espeso.",
      "Pon la lechuga en los platos, encima las papas y cúbrelas con la salsa.",
      "Decora con huevo y aceitunas."],
  tp:["Si la salsa está muy espesa, añade leche; si está líquida, otra galleta.",
      "La salsa sobrante es buena con papas fritas o con yuca."],
  v:"papa a la huancaina receta"},
 en:{n:"Papa a la Huancaína (Potatoes in Ají Cheese Sauce)", b:"Cold yellow potatoes under a creamy sauce of ají amarillo and queso fresco. With egg and olives.",
  st:["Boil the potatoes in their skins for 25 minutes. Peel, cool and cut into thick slices.",
      "Blend the ají, cheese, milk, crackers, oil and salt until smooth and thick.",
      "Put the lettuce on the plates, the potatoes on top and cover them with the sauce.",
      "Garnish with egg and olives."],
  tp:["If the sauce is too thick, add milk; if runny, another cracker.",
      "Leftover sauce is good with fries or cassava."],
  v:"papa a la huancaina recipe"}},

{id:"anticuchos", c:"Peru", ce:"Perú", r:"latin-america", m:"main", t:60, s:4,
 i:[[800,"g","beef","protein","corazón de res limpio","trimmed beef heart","en cubos de 3 cm","in 3 cm cubes"],
    [4,"tbsp","ajipaste","aromatic","pasta de ají panca","ají panca paste"],
    [60,"ml","winevinegar","acid","vinagre de vino tinto","red wine vinegar"],
    [4,"clove","garlic","aromatic","ajo","garlic","molido","crushed"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [1.5,"tsp","salt","salt","sal","salt"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [8,"","skewer","serve","palitos de brocheta","skewers","remojados","soaked"],
    [4,"","potato","serve","papas","potatoes","cocidas","boiled"],
    [2,"","corn","serve","choclos","ears of corn","cocidos","boiled"]],
 es:{n:"Anticuchos de corazón", b:"Brochetas de corazón de res marinadas en ají panca y vinagre, asadas a fuego vivo. Comida de esquina limeña.",
  st:["Mezcla el ají panca, el vinagre, el ajo, el comino, el orégano, la sal y el aceite.",
      "Marina el corazón en la mezcla al menos 3 horas o toda la noche.",
      "Ensarta 4 cubos por palito.",
      "Asa a la parrilla o en plancha muy caliente 2 minutos por lado, pintando con la marinada. Deben quedar rosados por dentro.",
      "Sirve con papa y choclo."],
  tp:["El corazón es magro: cocido de más se pone duro.",
      "Pídele al carnicero que lo limpie de nervios y grasa."],
  v:"anticuchos de corazon receta"},
 en:{n:"Beef Heart Anticuchos", b:"Skewers of beef heart marinated in ají panca and vinegar and grilled over high heat. Lima street-corner food.",
  st:["Mix the ají panca, vinegar, garlic, cumin, oregano, salt and oil.",
      "Marinate the heart in the mixture for at least 3 hours or overnight.",
      "Thread 4 cubes per skewer.",
      "Grill or sear on a very hot griddle for 2 minutes per side, brushing with the marinade. They should be pink inside.",
      "Serve with potato and corn."],
  tp:["Heart is lean: overcooked, it turns tough.",
      "Ask the butcher to trim it of sinew and fat."],
  v:"anticuchos recipe"}},

{id:"arroz-con-pollo-pe", c:"Peru", ce:"Perú", r:"latin-america", m:"main", t:75, s:6,
 i:[[6,"thigh","chicken","protein","muslos de pollo","chicken thighs"],
    [2,"tsp","salt","salt","sal","salt"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [2,"bunch","herb","aromatic","cilantro","cilantro"],
    [1,"","onion","aromatic","cebolla morada","red onion","picada","chopped"],
    [4,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"tbsp","ajipaste","aromatic","pasta de ají amarillo","ají amarillo paste"],
    [330,"ml","beer","liquid","cerveza negra","dark beer"],
    [500,"ml","stock","liquid","caldo de pollo","chicken stock"],
    [400,"g","rice","structure","arroz blanco","white rice"],
    [150,"g","legume","protein","arvejas","peas"],
    [1,"","veg","protein","zanahoria","carrot","en cubos","diced"],
    [1,"","bellpepper","garnish","pimiento rojo","red bell pepper","en tiras","in strips"]],
 es:{n:"Arroz con pollo peruano", b:"Arroz verde de cilantro con cerveza negra y ají amarillo, con pollo dorado, arvejas y zanahoria.",
  st:["Sala el pollo y dóralo en el aceite 5 minutos por lado. Sácalo.",
      "Licúa el cilantro con 120 ml del caldo.",
      "En la misma grasa, sofríe la cebolla, el ajo y el ají 8 minutos. Añade el cilantro licuado y cuece 3 minutos.",
      "Añade la cerveza, el resto del caldo y el pollo. Cuece tapado 15 minutos.",
      "Añade el arroz, las arvejas y la zanahoria. Hierve hasta que el líquido baje al nivel del arroz, tapa y cuece a fuego bajo 20 minutos.",
      "Decora con el pimiento y sirve con salsa criolla."],
  tp:["El verde viene del cilantro: usa mucho, con tallos.",
      "Sin cerveza, usa la misma cantidad de caldo."],
  v:"arroz con pollo peruano receta"},
 en:{n:"Peruvian Green Rice with Chicken", b:"Cilantro-green rice with dark beer and ají amarillo, with browned chicken, peas and carrot.",
  st:["Salt the chicken and brown it in the oil for 5 minutes per side. Remove.",
      "Blend the cilantro with 120 ml of the stock.",
      "In the same fat, cook the onion, garlic and ají for 8 minutes. Add the blended cilantro and cook 3 minutes.",
      "Add the beer, the rest of the stock and the chicken. Cook covered 15 minutes.",
      "Add the rice, peas and carrot. Boil until the liquid drops to the level of the rice, cover and cook on low for 20 minutes.",
      "Garnish with the bell pepper and serve with salsa criolla."],
  tp:["The green comes from the cilantro: use a lot, stems included.",
      "Without beer, use the same amount of stock."],
  v:"peruvian arroz con pollo recipe"}},

{id:"seco-de-res", c:"Peru", ce:"Perú", r:"latin-america", m:"main", t:120, s:6,
 i:[[1.2,"kg","beef","protein","asado de res o espaldilla","beef chuck","en trozos de 5 cm","in 5 cm pieces"],
    [2,"tsp","salt","salt","sal","salt"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [2,"bunch","herb","aromatic","cilantro","cilantro"],
    [1,"","onion","aromatic","cebolla morada","red onion","picada","chopped"],
    [4,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [2,"tbsp","ajipaste","aromatic","pasta de ají amarillo","ají amarillo paste"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [330,"ml","beer","liquid","cerveza","beer"],
    [500,"ml","water","liquid","agua","water"],
    [200,"g","legume","protein","arvejas","peas"],
    [1,"","veg","protein","zanahoria","carrot","en cubos","diced"],
    [4,"","potato","structure","papas amarillas","yellow potatoes","peladas, en mitades","peeled, halved"]],
 es:{n:"Seco de res", b:"Guiso norteño de res en salsa verde de cilantro con cerveza y ají, con arvejas, papa y frijoles aparte.",
  st:["Sala la carne y dórala en el aceite en tandas. Sácala.",
      "Licúa el cilantro con 250 ml del agua.",
      "Sofríe la cebolla, el ajo, el ají y el comino 8 minutos. Añade el cilantro licuado y cuece 5 minutos.",
      "Regresa la carne con la cerveza y el resto del agua. Tapa y cuece a fuego bajo 75 minutos.",
      "Añade las papas, la zanahoria y las arvejas y cuece 20 minutos más, hasta que la carne esté tierna.",
      "Sirve con arroz y frijoles."],
  tp:["En el norte se usa chicha de jora en vez de cerveza.",
      "Es aún mejor al día siguiente."],
  v:"seco de res receta"},
 en:{n:"Seco de Res (Peruvian Cilantro Beef Stew)", b:"A northern Peruvian beef stew in a green cilantro sauce with beer and ají, with peas and potatoes, and beans on the side.",
  st:["Salt the beef and brown it in the oil in batches. Remove.",
      "Blend the cilantro with 250 ml of the water.",
      "Cook the onion, garlic, ají and cumin for 8 minutes. Add the blended cilantro and cook 5 minutes.",
      "Return the beef with the beer and the rest of the water. Cover and cook on low for 75 minutes.",
      "Add the potatoes, carrot and peas and cook 20 minutes more, until the beef is tender.",
      "Serve with rice and beans."],
  tp:["In the north, chicha de jora is used instead of beer.",
      "It's even better the next day."],
  v:"seco de res recipe"}},

{id:"arroz-chaufa", c:"Peru", ce:"Perú", r:"latin-america", m:"main", t:30, s:4,
 i:[[600,"g","rice","structure","arroz blanco cocido del día anterior","day-old cooked white rice"],
    [3,"","egg","protein","huevos","eggs","batidos","beaten"],
    [300,"g","chicken","protein","pollo","chicken","en cubos","diced"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"tbsp","herb","aromatic","jengibre","ginger","picado","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [6,"","scallion","aromatic","cebollas chinas","green onions","en rodajas","sliced"],
    [3,"tbsp","soysauce","umami","sillao (salsa de soja)","soy sauce (sillao)"],
    [1,"tsp","sesameoil","aromatic","aceite de sésamo","sesame oil"],
    [0.5,"tsp","salt","salt","sal","salt"]],
 es:{n:"Arroz chaufa", b:"El arroz frito de las chifas de Lima: arroz, huevo, pollo, cebolla china y sillao al wok bien caliente.",
  st:["Haz una tortilla fina con los huevos en 1 cucharada de aceite. Córtala en tiras.",
      "Calienta el wok muy fuerte con el resto del aceite. Saltea el pollo con la sal 4 minutos, hasta que esté dorado.",
      "Añade el jengibre, el ajo y la parte blanca de la cebolla china 30 segundos.",
      "Añade el arroz y saltea 3 minutos, separándolo, hasta que chisporrotee.",
      "Añade el sillao por los bordes del wok, la tortilla, el resto de la cebolla y el aceite de sésamo. Saltea 1 minuto y sirve."],
  tp:["El arroz frío del día anterior no se apelmaza: el recién hecho sí.",
      "El wok debe humear; si tu estufa es débil, cocina en 2 tandas."],
  v:"arroz chaufa receta"},
 en:{n:"Arroz Chaufa (Peruvian Fried Rice)", b:"The fried rice of Lima's chifas: rice, egg, chicken, green onion and soy sauce over a very hot wok.",
  st:["Make a thin omelette with the eggs in 1 tablespoon of oil. Cut into strips.",
      "Heat the wok very hot with the rest of the oil. Stir-fry the chicken with the salt for 4 minutes, until browned.",
      "Add the ginger, garlic and the white part of the green onion for 30 seconds.",
      "Add the rice and stir-fry 3 minutes, breaking it up, until it crackles.",
      "Add the soy sauce around the edge of the wok, the omelette, the rest of the green onion and the sesame oil. Toss 1 minute and serve."],
  tp:["Day-old cold rice doesn't clump: freshly cooked does.",
      "The wok should smoke; if your stove is weak, cook in 2 batches."],
  v:"arroz chaufa recipe"}},

{id:"salsa-criolla", c:"Peru", ce:"Perú", r:"latin-america", m:"sauce", t:15, s:6,
 i:[[2,"","onion","aromatic","cebollas moradas","red onions","en pluma fina","thinly sliced"],
    [1,"","chilli","aromatic","ají limo o amarillo","ají limo or yellow chile","en tiras finas","in thin strips"],
    [3,"","citrus","acid","limones","limes","en jugo","juiced"],
    [1,"handful","herb","aromatic","cilantro","cilantro","picado","chopped"],
    [0.5,"tsp","salt","salt","sal","salt"]],
 es:{n:"Salsa criolla peruana", b:"Cebolla morada en pluma con ají, limón y cilantro. Acompaña casi todo: chicharrón, pan con chicharrón, arroz con pollo.",
  st:["Remoja la cebolla en agua fría con sal 10 minutos y escúrrela bien.",
      "Mezcla con el ají, el limón, el cilantro y la sal.",
      "Sirve enseguida, mientras la cebolla está crujiente."],
  tp:["El remojo quita el picor de la cebolla y la deja crujiente.",
      "Corta la cebolla a lo largo, siguiendo sus líneas, para que no suelte agua."],
  v:"salsa criolla peruana receta"},
 en:{n:"Peruvian Salsa Criolla", b:"Thinly sliced red onion with chile, lime and cilantro. It goes with almost everything: pork crackling, sandwiches, arroz con pollo.",
  st:["Soak the onion in cold salted water for 10 minutes and drain well.",
      "Mix with the chile, lime, cilantro and salt.",
      "Serve right away, while the onion is crisp."],
  tp:["Soaking takes the bite off the onion and keeps it crisp.",
      "Slice the onion lengthwise, along its lines, so it doesn't weep."],
  v:"peruvian salsa criolla recipe"}}
];
