module.exports = [
{id:"mofongo", c:"Puerto Rico", r:"caribbean", m:"main", t:40, s:4,
 i:[[3,"","plantain","structure","plátanos verdes","green plantains","pelados y en rodajas de 2 cm","peeled, in 2 cm slices"],
    [500,"ml","oil","fat","aceite para freír","oil for frying"],
    [4,"clove","garlic","aromatic","ajo","garlic"],
    [2,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [1,"tsp","salt","salt","sal","salt"],
    [100,"g","porkskin","crunch","chicharrón de cerdo","pork crackling","desmenuzado","crumbled"],
    [250,"ml","stock","moisture","caldo de pollo caliente","hot chicken stock"]],
 es:{n:"Mofongo", b:"Plátano verde frito y majado en pilón con ajo y chicharrón. La base de la mesa puertorriqueña.",
  st:["Calienta el aceite a 170 °C. Fríe las rodajas de plátano 8 minutos, hasta que estén tiernas pero no doradas. Escúrrelas.",
      "Maja el ajo con la sal y el aceite de oliva en el pilón o en un bol.",
      "Añade un tercio del plátano y un tercio del chicharrón y maja hasta tener una masa gruesa. Humedece con 2 cucharadas del caldo.",
      "Forma una bola apretada en un bol pequeño y desmolda. Repite con el resto.",
      "Sirve cada mofongo con el resto del caldo caliente por encima o al lado."],
  tp:["Maja el plátano en cuanto sale del aceite; frío se endurece y no se une.",
      "Si el plátano queda seco al majar, añade más caldo de cucharada en cucharada."],
  v:"mofongo puertorriqueño receta"},
 en:{n:"Mofongo", b:"Green plantain fried and mashed in a pilón with garlic and crackling. The foundation of the Puerto Rican table.",
  st:["Heat the oil to 170 °C. Fry the plantain slices for 8 minutes, until tender but not browned. Drain.",
      "Mash the garlic with the salt and olive oil in the pilón or a bowl.",
      "Add a third of the plantain and a third of the crackling and mash to a coarse mass. Moisten with 2 tablespoons of the stock.",
      "Pack into a small bowl and turn out as a dome. Repeat with the rest.",
      "Serve each mofongo with the rest of the hot stock poured over or on the side."],
  tp:["Mash the plantain as soon as it leaves the oil; cold, it hardens and won't hold together.",
      "If the plantain is dry as you mash, add more stock a spoonful at a time."],
  v:"puerto rican mofongo recipe"}},

{id:"arroz-con-gandules", c:"Puerto Rico", r:"caribbean", m:"main", t:60, s:8,
 i:[[3,"tbsp","oil","fat","aceite","oil"],
    [1,"tbsp","achiote","aromatic","semillas de achiote","annatto seeds"],
    [120,"g","ham","protein","jamón de cocinar","cooking ham","en dados","diced"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","pimiento verde","green bell pepper","picado","chopped"],
    [4,"","bellpepper","aromatic","ajíes dulces","ajíes dulces (sweet peppers)","picados","chopped"],
    [4,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"bunch","herb","aromatic","culantro (recao) y cilantro","culantro (recao) and cilantro","picados","chopped"],
    [120,"g","tomato","sauce","salsa de tomate natural","plain tomato sauce"],
    [60,"g","olives","umami","aceitunas verdes","green olives"],
    [1,"tbsp","capers","umami","alcaparras","capers"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [500,"g","rice","structure","arroz de grano medio","medium-grain rice","lavado","rinsed"],
    [450,"g","legume","protein","gandules cocidos","cooked pigeon peas","escurridos","drained"],
    [750,"ml","water","liquid","agua","water"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Arroz con gandules", b:"El arroz de Navidad de Puerto Rico: amarillo de achiote, con gandules, jamón y un sofrito de ajíes dulces y recao.",
  st:["Calienta el aceite con el achiote 3 minutos a fuego bajo y cuélalo. Tira las semillas.",
      "En un caldero, sofríe el jamón en el aceite de achiote 3 minutos. Añade la cebolla, los pimientos, los ajíes y el ajo y cuece 5 minutos.",
      "Añade las hierbas, la salsa de tomate, las aceitunas, las alcaparras y el comino. Cuece 3 minutos.",
      "Añade el arroz, los gandules, el agua y la sal. Hierve sin tapar hasta que el agua baje al nivel del arroz.",
      "Voltea una vez, tapa con una hoja de papel de aluminio y la tapa, y cuece 25 minutos a fuego bajo sin destapar."],
  tp:["El pegao, la capa tostada del fondo, es el premio: sube el fuego los últimos 5 minutos si lo quieres.",
      "Los ajíes dulces no pican; si no los encuentras, usa medio pimiento rojo más."],
  v:"arroz con gandules receta boricua"},
 en:{n:"Arroz con Gandules (Rice with Pigeon Peas)", b:"Puerto Rico's Christmas rice: gold from annatto, with pigeon peas, ham and a base of sweet peppers and recao.",
  st:["Warm the oil with the annatto for 3 minutes over low heat and strain. Discard the seeds.",
      "In a heavy pot, fry the ham in the annatto oil for 3 minutes. Add the onion, peppers, ajíes and garlic and cook 5 minutes.",
      "Add the herbs, tomato sauce, olives, capers and cumin. Cook 3 minutes.",
      "Add the rice, pigeon peas, water and salt. Boil uncovered until the water drops to the level of the rice.",
      "Stir once, cover with a sheet of foil and the lid, and cook 25 minutes on low without lifting the lid."],
  tp:["The pegao, the toasted crust on the bottom, is the prize: raise the heat for the last 5 minutes if you want it.",
      "Ajíes dulces aren't hot; if you can't find them, use half a red bell pepper more."],
  v:"arroz con gandules recipe"}},

{id:"pernil", c:"Puerto Rico", r:"caribbean", m:"main", t:330, s:10, o:160,
 i:[[3.5,"kg","pork","protein","paleta de cerdo con piel","bone-in pork shoulder with skin"],
    [12,"clove","garlic","aromatic","ajo","garlic"],
    [1,"tbsp","herb","aromatic","orégano seco","dried oregano"],
    [2,"tbsp","salt","salt","sal gruesa","coarse salt"],
    [1,"tsp","pepper","aromatic","pimienta negra molida","ground black pepper"],
    [3,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [2,"tbsp","whitevinegar","acid","vinagre blanco","white vinegar"]],
 es:{n:"Pernil al horno", b:"Paleta de cerdo adobada con ajo y orégano, asada despacio hasta que la carne se deshace y la piel cruje.",
  st:["Maja el ajo, el orégano, la sal, la pimienta, el aceite y el vinagre hasta tener una pasta.",
      "Separa la piel de la carne con un cuchillo sin quitarla. Haz cortes profundos en la carne y rellénalos con el adobo, también bajo la piel.",
      "Tapa y deja en la nevera al menos 12 horas.",
      "Asa tapado con papel de aluminio a 160 °C durante 4 horas.",
      "Destapa, sube a 220 °C y asa 30 minutos más, hasta que la piel esté inflada y crujiente. Reposa 15 minutos antes de cortar."],
  tp:["Seca bien la piel con papel antes del último paso; así cruje más.",
      "La carne está lista cuando se separa del hueso con un tenedor."],
  v:"pernil al horno puertorriqueño"},
 en:{n:"Pernil (Roast Pork Shoulder)", b:"Pork shoulder rubbed with garlic and oregano, roasted low until the meat falls apart and the skin crackles.",
  st:["Mash the garlic, oregano, salt, pepper, oil and vinegar into a paste.",
      "Loosen the skin from the meat with a knife without removing it. Cut deep slits in the meat and fill them with the paste, under the skin too.",
      "Cover and refrigerate at least 12 hours.",
      "Roast covered with foil at 160 °C for 4 hours.",
      "Uncover, raise to 220 °C and roast 30 minutes more, until the skin puffs and crackles. Rest 15 minutes before carving."],
  tp:["Pat the skin very dry with paper before the last step; it crisps better.",
      "The meat is ready when it pulls from the bone with a fork."],
  v:"puerto rican pernil recipe"}},

{id:"tembleque", c:"Puerto Rico", r:"caribbean", m:"sweet", t:20, s:8,
 i:[[800,"ml","coconutmilk","structure","leche de coco","coconut milk"],
    [100,"g","sugar","sweet","azúcar","sugar"],
    [70,"g","cornstarch","set","fécula de maíz","cornstarch"],
    [1,"pinch","salt","salt","sal","salt"],
    [1,"","spice","aromatic","rama de canela","cinnamon stick"],
    [1,"tsp","spice","garnish","canela molida","ground cinnamon"]],
 es:{n:"Tembleque", b:"Flan de coco sin huevo que tiembla al servirlo. Postre de Navidad en Puerto Rico.",
  st:["Mezcla 200 ml de la leche de coco con la fécula hasta que no haya grumos.",
      "Calienta el resto de la leche de coco con el azúcar, la sal y la rama de canela hasta que humee.",
      "Saca la canela, añade la mezcla de fécula y remueve sin parar a fuego medio 6 minutos, hasta que espese como una crema densa.",
      "Vierte en un molde humedecido con agua y deja enfriar. Refrigera 4 horas.",
      "Desmolda y espolvorea con la canela molida."],
  tp:["Remueve con varillas desde el primer momento; la fécula se agarra al fondo enseguida.",
      "Si queda muy blando, faltó cocción: la mezcla debe hervir al menos 1 minuto."],
  v:"tembleque receta puerto rico"},
 en:{n:"Tembleque (Coconut Pudding)", b:"An egg-free coconut pudding that wobbles when served. A Puerto Rican Christmas dessert.",
  st:["Whisk 200 ml of the coconut milk with the cornstarch until smooth.",
      "Heat the rest of the coconut milk with the sugar, salt and cinnamon stick until steaming.",
      "Remove the cinnamon, add the cornstarch mixture and stir constantly over medium heat for 6 minutes, until as thick as dense custard.",
      "Pour into a mould rinsed with water and let cool. Refrigerate 4 hours.",
      "Turn out and dust with the ground cinnamon."],
  tp:["Whisk from the very start; cornstarch catches on the bottom at once.",
      "If it sets too soft, it wasn't cooked enough: the mixture must boil for at least 1 minute."],
  v:"tembleque recipe"}},

{id:"tostones", c:"Puerto Rico", r:"caribbean", m:"side", t:25, s:4,
 i:[[3,"","plantain","structure","plátanos verdes","green plantains","pelados, en trozos de 3 cm","peeled, in 3 cm pieces"],
    [500,"ml","oil","fat","aceite para freír","oil for frying"],
    [500,"ml","water","liquid","agua","water"],
    [2,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Tostones", b:"Plátano verde frito dos veces y aplastado. Crujiente por fuera, tierno por dentro, con agua de ajo.",
  st:["Mezcla el agua con el ajo y 1 cucharadita de sal.",
      "Fríe los trozos de plátano a 160 °C durante 5 minutos, hasta que estén tiernos y apenas dorados. Escúrrelos.",
      "Aplasta cada trozo hasta 1 cm con una tostonera o el fondo de un vaso.",
      "Pásalos rápido por el agua de ajo y sécalos con papel.",
      "Fríe de nuevo a 180 °C durante 3 minutos, hasta que estén dorados. Sala y sirve enseguida."],
  tp:["Seca bien los tostones después del agua de ajo; el agua en el aceite caliente salta.",
      "Aplástalos calientes; fríos se rompen."],
  v:"tostones receta"},
 en:{n:"Tostones (Twice-Fried Plantains)", b:"Green plantain fried twice and smashed. Crisp outside, tender inside, with garlic water.",
  st:["Mix the water with the garlic and 1 teaspoon of salt.",
      "Fry the plantain pieces at 160 °C for 5 minutes, until tender and barely golden. Drain.",
      "Smash each piece to 1 cm with a tostonera or the base of a glass.",
      "Dip quickly in the garlic water and pat dry with paper.",
      "Fry again at 180 °C for 3 minutes, until golden. Salt and serve at once."],
  tp:["Dry the tostones well after the garlic water; water in hot oil spits.",
      "Smash them while hot; cold, they crack."],
  v:"tostones recipe"}},

{id:"mangu", c:"Dominican Republic", r:"caribbean", m:"breakfast", t:35, s:4,
 i:[[4,"","plantain","structure","plátanos verdes","green plantains","pelados, en trozos","peeled, in chunks"],
    [1,"l","water","liquid","agua","water"],
    [2,"tsp","salt","salt","sal","salt"],
    [40,"g","butter","fat","mantequilla","butter"],
    [1,"","onion","garnish","cebolla roja","red onion","en aros finos","in thin rings"],
    [3,"tbsp","whitevinegar","acid","vinagre blanco","white vinegar"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [250,"g","sausage","protein","salami dominicano","Dominican salami","en rodajas de 1 cm","in 1 cm slices"],
    [250,"g","cheese","protein","queso de freír","frying cheese","en lonchas de 1 cm","in 1 cm slices"],
    [4,"","egg","protein","huevos","eggs"]],
 es:{n:"Mangú con los tres golpes", b:"Puré de plátano verde con cebolla encurtida, salami frito, queso frito y huevo. El desayuno dominicano.",
  st:["Mezcla la cebolla con el vinagre y una pizca de sal y deja reposar mientras cocinas.",
      "Hierve el plátano en el agua con 1 cucharadita de sal 20 minutos, hasta que esté muy tierno.",
      "Escurre guardando 150 ml del agua. Maja el plátano con la mantequilla, el resto de la sal y el agua reservada hasta tener un puré suave.",
      "Fríe en el aceite el salami 3 minutos por lado y luego el queso 2 minutos por lado. Fríe los huevos en la misma sartén.",
      "Sirve el mangú con la cebolla escurrida encima y el salami, el queso y los huevos al lado."],
  tp:["Maja el plátano caliente con el agua de cocción aún tibia; si se enfría se pone gomoso.",
      "Retira la cebolla del vinagre antes de servir para que no humedezca el mangú."],
  v:"mangu con los tres golpes receta"},
 en:{n:"Mangú with Los Tres Golpes", b:"Green plantain mash with pickled onion, fried salami, fried cheese and egg. The Dominican breakfast.",
  st:["Mix the onion with the vinegar and a pinch of salt and leave while you cook.",
      "Boil the plantain in the water with 1 teaspoon of salt for 20 minutes, until very tender.",
      "Drain, keeping 150 ml of the water. Mash the plantain with the butter, the rest of the salt and the reserved water to a smooth purée.",
      "In the oil, fry the salami 3 minutes a side, then the cheese 2 minutes a side. Fry the eggs in the same pan.",
      "Serve the mangú with the drained onion on top and the salami, cheese and eggs alongside."],
  tp:["Mash the plantain hot with the cooking water still warm; if it cools it turns gummy.",
      "Lift the onion out of the vinegar before serving so it doesn't wet the mangú."],
  v:"dominican mangu recipe"}},

{id:"sancocho-dominicano", c:"Dominican Republic", r:"caribbean", m:"soup", t:150, s:10,
 i:[[500,"g","beef","protein","carne de res para guisar","stewing beef","en dados","diced"],
    [500,"g","pork","protein","costillas de cerdo","pork ribs","en trozos","cut up"],
    [800,"g","chicken","protein","pollo en presas","chicken pieces"],
    [2,"","citrus","acid","limones","limes","en jugo","juiced"],
    [4,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [1,"tbsp","herb","aromatic","orégano seco","dried oregano"],
    [1,"bunch","herb","aromatic","cilantro","cilantro","picado","chopped"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [3,"l","water","liquid","agua","water"],
    [400,"g","veg","structure","ñame","yam (ñame)","pelado, en trozos","peeled, in chunks"],
    [400,"g","veg","structure","yautía","yautía (malanga)","pelada, en trozos","peeled, in chunks"],
    [500,"g","cassava","structure","yuca","cassava","pelada, en trozos","peeled, in chunks"],
    [2,"","plantain","structure","plátanos verdes","green plantains","pelados, en trozos","peeled, in chunks"],
    [300,"g","veg","structure","auyama","calabaza (West Indian pumpkin)","en trozos","in chunks"],
    [2,"","corn","structure","mazorcas de maíz","corn cobs","en ruedas","in rounds"],
    [1,"tbsp","salt","salt","sal","salt"]],
 es:{n:"Sancocho dominicano", b:"El sancocho de siete carnes en versión de casa: tres carnes, víveres, auyama y maíz en una sopa espesa.",
  st:["Adoba las tres carnes con el jugo de limón, el ajo, el orégano, la mitad del cilantro y la sal. Deja 30 minutos.",
      "En una olla grande, dora la res y el cerdo en el aceite 8 minutos con la cebolla. Añade 250 ml del agua y cuece tapado 30 minutos.",
      "Añade el pollo y cuece 10 minutos más.",
      "Añade el resto del agua, el ñame, la yautía, la yuca, el plátano y la mitad de la auyama. Cuece 40 minutos.",
      "Añade el maíz y el resto de la auyama y cuece 20 minutos, hasta que la auyama deshecha espese la sopa. Termina con el resto del cilantro."],
  tp:["La auyama que se deshace es lo que da cuerpo; no la saques antes.",
      "Se sirve con arroz blanco y aguacate al lado."],
  v:"sancocho dominicano receta"},
 en:{n:"Dominican Sancocho", b:"The seven-meat sancocho in a home version: three meats, root vegetables, calabaza and corn in a thick soup.",
  st:["Season the three meats with the lime juice, garlic, oregano, half the cilantro and the salt. Leave 30 minutes.",
      "In a large pot, brown the beef and pork in the oil for 8 minutes with the onion. Add 250 ml of the water and cook covered for 30 minutes.",
      "Add the chicken and cook 10 minutes more.",
      "Add the rest of the water, the yam, yautía, cassava, plantain and half the calabaza. Cook 40 minutes.",
      "Add the corn and the rest of the calabaza and cook 20 minutes, until the broken-down calabaza thickens the soup. Finish with the rest of the cilantro."],
  tp:["The calabaza that falls apart is what gives it body; don't take it out early.",
      "It is served with white rice and avocado on the side."],
  v:"dominican sancocho recipe"}},

{id:"habichuelas-guisadas", c:"Dominican Republic", r:"caribbean", m:"side", t:45, s:6,
 i:[[2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","pimiento verde","green bell pepper","picado","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"tbsp","tomatopaste","umami","pasta de tomate","tomato paste"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [800,"g","legume","protein","habichuelas rojas cocidas","cooked red kidney beans","con 250 ml de su líquido","with 250 ml of their liquid"],
    [250,"g","veg","structure","auyama","calabaza (West Indian pumpkin)","en dados de 1 cm","in 1 cm dice"],
    [250,"ml","water","liquid","agua","water"],
    [1,"handful","herb","garnish","cilantro","cilantro","picado","chopped"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Habichuelas guisadas", b:"Frijoles rojos guisados con auyama que se deshace y los espesa. La mitad de la bandera dominicana.",
  st:["Sofríe la cebolla, el pimiento y el ajo en el aceite 5 minutos.",
      "Añade la pasta de tomate y el orégano y cuece 1 minuto.",
      "Añade las habichuelas con su líquido, la auyama, el agua y la sal. Cuece 25 minutos a fuego medio.",
      "Aplasta algunos trozos de auyama y de habichuela contra la olla para espesar.",
      "Termina con el cilantro y sirve sobre arroz blanco."],
  tp:["Deben quedar espesas pero con salsa para mojar el arroz.",
      "Con habichuelas secas, remoja 250 g toda la noche y cuécelas 90 minutos antes de empezar."],
  v:"habichuelas guisadas dominicanas"},
 en:{n:"Habichuelas Guisadas (Dominican Stewed Beans)", b:"Red beans stewed with calabaza that melts and thickens them. Half of the Dominican bandera.",
  st:["Cook the onion, pepper and garlic in the oil for 5 minutes.",
      "Add the tomato paste and oregano and cook 1 minute.",
      "Add the beans with their liquid, the calabaza, water and salt. Cook 25 minutes over medium heat.",
      "Crush some of the calabaza and beans against the pot to thicken.",
      "Finish with the cilantro and serve over white rice."],
  tp:["They should be thick but saucy enough to soak the rice.",
      "With dried beans, soak 250 g overnight and cook them 90 minutes before you start."],
  v:"dominican habichuelas guisadas recipe"}},

{id:"pollo-guisado-dominicano", c:"Dominican Republic", r:"caribbean", m:"main", t:70, s:6,
 i:[[1.5,"kg","chicken","protein","pollo en presas sin piel","skinless chicken pieces"],
    [2,"","citrus","acid","limones","limes","en jugo","juiced"],
    [4,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [2,"tsp","salt","salt","sal","salt"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"tbsp","sugar","caramel","azúcar","sugar"],
    [1,"","onion","aromatic","cebolla","onion","en tiras","sliced"],
    [1,"","bellpepper","aromatic","pimiento verde","green bell pepper","en tiras","sliced"],
    [2,"tbsp","tomatopaste","umami","pasta de tomate","tomato paste"],
    [60,"g","olives","umami","aceitunas verdes","green olives"],
    [250,"ml","water","liquid","agua","water"],
    [1,"handful","herb","garnish","cilantro","cilantro","picado","chopped"]],
 es:{n:"Pollo guisado dominicano", b:"Pollo dorado en azúcar caramelizada y guisado con ajo, orégano y aceitunas. Color oscuro, sabor profundo.",
  st:["Adoba el pollo con el jugo de limón, el ajo, el orégano y la sal. Deja al menos 30 minutos.",
      "Calienta el aceite con el azúcar a fuego medio hasta que el azúcar se vuelva marrón oscuro, unos 2 minutos.",
      "Añade el pollo escurrido con cuidado, porque salta, y dóralo 8 minutos, volteando para que tome color.",
      "Añade la cebolla, el pimiento, la pasta de tomate, las aceitunas, el adobo y el agua. Tapa y cuece 35 minutos.",
      "Destapa y reduce 5 minutos hasta tener una salsa espesa. Termina con el cilantro."],
  tp:["El azúcar debe quedar oscuro, no negro; si humea mucho, empieza de nuevo o amargará.",
      "Sirve con arroz blanco y habichuelas."],
  v:"pollo guisado dominicano receta"},
 en:{n:"Dominican Pollo Guisado (Braised Chicken)", b:"Chicken browned in caramelized sugar and braised with garlic, oregano and olives. Dark colour, deep flavour.",
  st:["Season the chicken with the lime juice, garlic, oregano and salt. Leave at least 30 minutes.",
      "Heat the oil with the sugar over medium heat until the sugar turns dark brown, about 2 minutes.",
      "Add the drained chicken carefully, as it spits, and brown it 8 minutes, turning to colour it.",
      "Add the onion, pepper, tomato paste, olives, the marinade and the water. Cover and cook 35 minutes.",
      "Uncover and reduce 5 minutes to a thick sauce. Finish with the cilantro."],
  tp:["The sugar should be dark, not black; if it smokes heavily, start again or it will taste bitter.",
      "Serve with white rice and stewed beans."],
  v:"dominican pollo guisado recipe"}},

{id:"habichuelas-con-dulce", c:"Dominican Republic", r:"caribbean", m:"sweet", t:60, s:8,
 i:[[500,"g","legume","structure","habichuelas rojas cocidas","cooked red kidney beans","escurridas","drained"],
    [750,"ml","water","liquid","agua","water"],
    [400,"ml","coconutmilk","liquid","leche de coco","coconut milk"],
    [400,"ml","evaporatedmilk","enrich","leche evaporada","evaporated milk"],
    [180,"g","sugar","sweet","azúcar","sugar"],
    [300,"g","veg","structure","batata","sweet potato","pelada, en dados de 1 cm","peeled, in 1 cm dice"],
    [60,"g","driedfruit","sweet","pasas","raisins"],
    [2,"","spice","aromatic","ramas de canela","cinnamon sticks"],
    [6,"","spice","aromatic","clavos de olor","whole cloves"],
    [1,"pinch","salt","salt","sal","salt"],
    [20,"g","butter","fat","mantequilla","butter"]],
 es:{n:"Habichuelas con dulce", b:"Crema dulce de frijoles rojos con coco, batata y especias. Se prepara en Cuaresma y se reparte entre vecinos.",
  st:["Licúa las habichuelas con 500 ml del agua hasta que estén lisas y cuela a una olla.",
      "Añade el resto del agua, la leche de coco, la canela, los clavos y la sal. Hierve y cuece 10 minutos a fuego bajo, removiendo.",
      "Añade la batata y cuece 15 minutos, hasta que esté tierna.",
      "Añade la leche evaporada, el azúcar, las pasas y la mantequilla y cuece 10 minutos más, removiendo, hasta que cubra una cuchara.",
      "Retira la canela y los clavos. Sirve fría o tibia."],
  tp:["Espesa al enfriar; si queda muy densa, aligérala con un poco de agua.",
      "Guarda hasta 3 días en la nevera."],
  v:"habichuelas con dulce receta dominicana"},
 en:{n:"Habichuelas con Dulce (Sweet Cream of Beans)", b:"A sweet cream of red beans with coconut, sweet potato and spices. Made in Lent and shared among neighbours.",
  st:["Blend the beans with 500 ml of the water until smooth and strain into a pot.",
      "Add the rest of the water, the coconut milk, cinnamon, cloves and salt. Bring to a boil and simmer 10 minutes, stirring.",
      "Add the sweet potato and cook 15 minutes, until tender.",
      "Add the evaporated milk, sugar, raisins and butter and cook 10 minutes more, stirring, until it coats a spoon.",
      "Remove the cinnamon and cloves. Serve cold or warm."],
  tp:["It thickens as it cools; if too dense, loosen with a little water.",
      "Keeps up to 3 days in the fridge."],
  v:"habichuelas con dulce recipe"}}
];
