module.exports = [
{id:"caldeirada-de-peixe", c:"Portugal", r:"mediterranean", m:"main", t:60, s:6,
 i:[[1.2,"kg","whitefish","protein","pescados variados (rape, raya, pescadilla) en rodajas","mixed fish steaks (monkfish, skate, whiting)"],
    [80,"ml","oliveoil","fat","aceite de oliva","olive oil"],
    [2,"","onion","aromatic","cebollas","onions","en rodajas","sliced"],
    [4,"clove","garlic","aromatic","ajo","garlic","laminado","sliced"],
    [2,"","bellpepper","aromatic","pimientos rojos","red bell peppers","en tiras","in strips"],
    [4,"","tomato","liquid","tomates maduros","ripe tomatoes","en rodajas","sliced"],
    [4,"","potato","structure","patatas","potatoes","en rodajas","sliced"],
    [200,"ml","winewhite","liquid","vino blanco","white wine"],
    [2,"leaf","herb","aromatic","laurel","bay leaves"],
    [1,"bunch","herb","aromatic","perejil","parsley","picado","chopped"],
    [1,"tsp","paprika","aromatic","pimentón dulce","sweet paprika"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Caldeirada de peixe", b:"Guiso de pescados variados en capas con patata, pimiento y tomate. El guiso de los pescadores portugueses.",
  st:["Sala el pescado.",
      "En una olla ancha, pon una capa de cebolla, ajo, pimiento, tomate y patata con aceite y pimentón.",
      "Añade una capa de pescado y repite las capas, terminando con tomate. Añade el laurel y el perejil.",
      "Riega con el vino y el resto del aceite.",
      "Tapa y cuece 35 minutos a fuego bajo, moviendo la olla sin remover."],
  tp:["No remuevas: se mueve la olla para que el pescado no se rompa.",
      "Usa pescados de carne firme."],
  v:"caldeirada de peixe portuguesa"},
 en:{n:"Caldeirada (Portuguese Fish Stew)", b:"A layered stew of mixed fish with potato, pepper and tomato. The Portuguese fishermen's stew.",
  st:["Salt the fish.",
      "In a wide pot, layer onion, garlic, pepper, tomato and potato with oil and paprika.",
      "Add a layer of fish and repeat, ending with tomato. Add the bay and parsley.",
      "Pour over the wine and the rest of the oil.",
      "Cover and cook 35 minutes on low, shaking the pot rather than stirring."],
  tp:["Don't stir: shake the pot so the fish stays whole.",
      "Use firm-fleshed fish."],
  v:"portuguese caldeirada"}},

{id:"bacalhau-com-natas", c:"Portugal", r:"mediterranean", m:"main", t:75, s:6,
 i:[[500,"g","whitefish","protein","bacalao salado desalado","desalted salt cod","desmenuzado","flaked"],
    [800,"g","potato","structure","patatas","potatoes","en daditos","small dice"],
    [500,"ml","oil","fat","aceite para freír","oil for frying"],
    [4,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [2,"","onion","aromatic","cebollas","onions","en tiras finas","thinly sliced"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [40,"g","butter","fat","mantequilla","butter"],
    [40,"g","apflour","thicken","harina de trigo","plain flour"],
    [500,"ml","milk","liquid","leche","milk"],
    [200,"ml","cream","enrich","nata","single cream"],
    [1,"pinch","spice","aromatic","nuez moscada","nutmeg"],
    [50,"g","parmesan","garnish","queso rallado","grated cheese"]],
 es:{n:"Bacalhau com natas", b:"Bacalao con patata frita y cebolla en salsa cremosa, gratinado. Uno de los platos más populares de Portugal.",
  st:["Fríe la patata en el aceite hasta que esté dorada. Escurre.",
      "Pocha la cebolla y el ajo en el aceite de oliva 10 minutos. Añade el bacalao y cocina 5 minutos.",
      "Derrite la mantequilla, añade la harina y cocina 1 minuto. Añade la leche batiendo y cuece 5 minutos. Añade la nata y la nuez moscada.",
      "Mezcla el bacalao, la patata y dos tercios de la salsa. Pasa a una fuente y cubre con el resto de la salsa y el queso.",
      "Gratina a 220 °C 20 minutos."],
  tp:["Prueba antes de salar: el bacalao aporta sal.",
      "Desala el bacalao 36 horas, cambiando el agua a menudo."],
  v:"bacalhau com natas"},
 en:{n:"Bacalhau com Natas (Creamy Salt Cod Bake)", b:"Salt cod with fried potato and onion in a creamy sauce, gratinéed. One of Portugal's most popular dishes.",
  st:["Fry the potato in the oil until golden. Drain.",
      "Soften the onion and garlic in the olive oil for 10 minutes. Add the cod and cook 5 minutes.",
      "Melt the butter, add the flour and cook 1 minute. Whisk in the milk and cook 5 minutes. Add the cream and nutmeg.",
      "Mix the cod, potato and two thirds of the sauce. Tip into a dish and top with the rest of the sauce and the cheese.",
      "Bake at 220 °C for 20 minutes."],
  tp:["Taste before salting: the cod adds salt.",
      "Soak the cod 36 hours, changing the water often."],
  v:"portuguese salt cod cream bake"}},

{id:"arroz-de-marisco", c:"Portugal", r:"mediterranean", m:"main", t:60, s:4,
 i:[[4,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"","bellpepper","aromatic","pimiento verde","green bell pepper","picado","chopped"],
    [3,"","tomato","liquid","tomates maduros","ripe tomatoes","picados","chopped"],
    [100,"ml","winewhite","liquid","vino blanco","white wine"],
    [300,"g","rice","structure","arroz de grano medio","medium-grain rice"],
    [1.2,"l","water","liquid","agua","water"],
    [400,"g","prawn","protein","gambas enteras","whole prawns"],
    [500,"g","clam","protein","almejas","clams"],
    [500,"g","mussel","protein","mejillones","mussels"],
    [1,"bunch","herb","aromatic","cilantro","coriander","picado","chopped"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Arroz de marisco", b:"Arroz caldoso con gambas, almejas y mejillones, lleno de cilantro. El arroz de las marisquerías portuguesas.",
  st:["Pela las gambas y hierve las cáscaras en el agua 15 minutos. Cuela.",
      "Sofríe la cebolla, el ajo y el pimiento en el aceite 6 minutos. Añade el tomate y cocina 8 minutos.",
      "Añade el vino, el arroz, el caldo y la sal y cuece 12 minutos.",
      "Añade las almejas, los mejillones y las gambas y cuece 5 minutos, hasta que se abran.",
      "Termina con el cilantro y sirve de inmediato: debe quedar caldoso."],
  tp:["Tira las almejas y los mejillones que no se abran.",
      "Sírvelo en cuanto esté: el arroz sigue absorbiendo."],
  v:"arroz de marisco português"},
 en:{n:"Arroz de Marisco (Portuguese Seafood Rice)", b:"Soupy rice with prawns, clams and mussels, loaded with coriander. The rice of Portuguese seafood houses.",
  st:["Peel the prawns and boil the shells in the water for 15 minutes. Strain.",
      "Cook the onion, garlic and pepper in the oil for 6 minutes. Add the tomato and cook 8 minutes.",
      "Add the wine, rice, stock and salt and cook 12 minutes.",
      "Add the clams, mussels and prawns and cook 5 minutes, until they open.",
      "Finish with the coriander and serve at once: it should be soupy."],
  tp:["Discard any clams or mussels that don't open.",
      "Serve as soon as it's ready: the rice keeps absorbing."],
  v:"portuguese seafood rice"}},

{id:"bolo-de-bolacha", c:"Portugal", r:"mediterranean", m:"sweet", t:40, s:10,
 i:[[400,"g","mariebiscuit","structure","galletas María","Marie biscuits"],
    [300,"ml","coffee","liquid","café fuerte frío","strong coffee, cooled"],
    [250,"g","butter","fat","mantequilla blanda","soft butter"],
    [200,"g","icingsugar","sweet","azúcar glas","icing sugar"],
    [2,"","eggyolk","enrich","yemas de huevo pasteurizadas","pasteurised egg yolks"]],
 es:{n:"Bolo de bolacha", b:"Pastel sin horno de galletas mojadas en café con crema de mantequilla. Postre de las casas portuguesas.",
  st:["Bate la mantequilla con el azúcar glas 5 minutos. Añade las yemas y bate hasta que esté esponjosa.",
      "Moja cada galleta en el café un segundo.",
      "Alterna capas de galletas y crema en un plato, formando una torre.",
      "Cubre todo con crema y espolvorea galleta molida.",
      "Refrigera 4 horas."],
  tp:["Moja las galletas muy rápido para que no se deshagan.",
      "Usa yemas pasteurizadas porque no se cuecen."],
  v:"bolo de bolacha"},
 en:{n:"Bolo de Bolacha (Portuguese Biscuit Cake)", b:"A no-bake cake of coffee-dipped biscuits and butter cream. A Portuguese home dessert.",
  st:["Beat the butter with the icing sugar for 5 minutes. Add the yolks and beat until fluffy.",
      "Dip each biscuit in the coffee for a second.",
      "Alternate layers of biscuits and cream on a plate, building a stack.",
      "Cover with cream and sprinkle with crushed biscuit.",
      "Chill 4 hours."],
  tp:["Dip the biscuits very briefly so they don't fall apart.",
      "Use pasteurised yolks because they aren't cooked."],
  v:"portuguese biscuit cake"}},

{id:"sopa-de-pedra", c:"Portugal", r:"mediterranean", m:"soup", t:150, s:6,
 i:[[300,"g","legume","structure","alubias rojas secas","dried red kidney beans"],
    [2.5,"l","water","liquid","agua","water"],
    [150,"g","chorizo","protein","chorizo","chorizo","en rodajas","sliced"],
    [150,"g","pancetta","protein","panceta","pancetta","en dados","diced"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [3,"","potato","structure","patatas","potatoes","en cubos","cubed"],
    [2,"","veg","structure","zanahorias","carrots","en dados","diced"],
    [1,"bunch","herb","aromatic","cilantro","coriander","picado","chopped"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Sopa de pedra", b:"La sopa de la leyenda del fraile que pedía una piedra: alubias, embutidos y verduras. Especialidad de Almeirim.",
  st:["Remoja las alubias 12 horas.",
      "Cuécelas en el agua con el chorizo, la panceta, la cebolla y el ajo 90 minutos.",
      "Añade las patatas, la zanahoria y la sal y cuece 25 minutos.",
      "Termina con el cilantro."],
  tp:["En Almeirim se sirve con una piedra limpia en la sopera, por la leyenda.",
      "Mejor al día siguiente."],
  v:"sopa da pedra almeirim"},
 en:{n:"Sopa da Pedra (Portuguese Stone Soup)", b:"The soup from the tale of the friar who asked for a stone: beans, sausage and vegetables. An Almeirim speciality.",
  st:["Soak the beans 12 hours.",
      "Simmer them in the water with the chorizo, pancetta, onion and garlic for 90 minutes.",
      "Add the potatoes, carrot and salt and cook 25 minutes.",
      "Finish with the coriander."],
  tp:["In Almeirim a clean stone is served in the tureen, for the legend.",
      "Better the next day."],
  v:"portuguese stone soup"}},

{id:"prego-no-pao", c:"Portugal", r:"mediterranean", m:"main", t:20, s:4,
 i:[[4,"slice","beef","protein","filetes finos de ternera","thin beef steaks"],
    [4,"clove","garlic","aromatic","ajo","garlic","laminado","sliced"],
    [1,"tsp","salt","salt","sal gruesa","coarse salt"],
    [2,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [30,"g","butter","fat","mantequilla","butter"],
    [4,"","bread","structure","panecillos portugueses (papo-secos)","crusty Portuguese rolls"],
    [1,"leaf","herb","aromatic","laurel","bay leaf"]],
 es:{n:"Prego no pão", b:"Filete fino con ajo en un panecillo crujiente. El bocadillo de las tascas portuguesas.",
  st:["Frota los filetes con el ajo y la sal y deja reposar 15 minutos.",
      "Calienta el aceite, la mantequilla y el laurel en una sartén a fuego fuerte.",
      "Cocina los filetes con el ajo 1 minuto por lado.",
      "Abre los panes, mójalos en el jugo de la sartén y pon un filete en cada uno."],
  tp:["Mojar el pan en el jugo es el secreto.",
      "No cocines de más la carne: debe quedar jugosa."],
  v:"prego no pão"},
 en:{n:"Prego no Pão (Portuguese Steak Roll)", b:"A thin garlicky steak in a crusty roll. The sandwich of Portuguese taverns.",
  st:["Rub the steaks with the garlic and salt and rest 15 minutes.",
      "Heat the oil, butter and bay in a pan over high heat.",
      "Cook the steaks with the garlic for 1 minute per side.",
      "Split the rolls, dip them in the pan juices and put a steak in each."],
  tp:["Dipping the bread in the juices is the secret.",
      "Don't overcook the beef: it should stay juicy."],
  v:"portuguese steak sandwich"}},

{id:"bacalhau-a-gomes-de-sa", c:"Portugal", r:"mediterranean", m:"main", t:60, s:4,
 i:[[500,"g","whitefish","protein","bacalao salado desalado","desalted salt cod"],
    [500,"ml","milk","liquid","leche","milk"],
    [700,"g","potato","structure","patatas","potatoes","cocidas en rodajas","boiled and sliced"],
    [150,"ml","oliveoil","fat","aceite de oliva","olive oil"],
    [2,"","onion","aromatic","cebollas","onions","en rodajas","sliced"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [3,"","egg","garnish","huevos duros","hard-boiled eggs","en rodajas","sliced"],
    [12,"","olives","garnish","aceitunas negras","black olives"],
    [1,"handful","herb","garnish","perejil","parsley","picado","chopped"]],
 es:{n:"Bacalhau à Gomes de Sá", b:"Bacalao desmigado con patata, cebolla y aceite, al horno con huevo y aceitunas. Receta de Oporto.",
  st:["Calienta la leche, apaga y deja el bacalao en ella 1 hora. Escurre y desmíga.",
      "Pocha la cebolla y el ajo en el aceite 10 minutos.",
      "Mezcla con la patata y el bacalao.",
      "Pasa a una fuente y hornea a 200 °C 15 minutos.",
      "Decora con el huevo, las aceitunas y el perejil."],
  tp:["Remojar el bacalao en leche lo suaviza.",
      "No escatimes el aceite: es parte del plato."],
  v:"bacalhau à gomes de sá"},
 en:{n:"Bacalhau à Gomes de Sá (Porto Salt Cod Bake)", b:"Flaked salt cod with potato, onion and olive oil, baked and topped with egg and olives. A recipe from Porto.",
  st:["Heat the milk, turn off and leave the cod in it for 1 hour. Drain and flake.",
      "Soften the onion and garlic in the oil for 10 minutes.",
      "Mix with the potato and cod.",
      "Tip into a dish and bake at 200 °C for 15 minutes.",
      "Top with the egg, olives and parsley."],
  tp:["Soaking the cod in milk makes it tender.",
      "Don't skimp on the oil: it's part of the dish."],
  v:"portuguese gomes de sa"}},

{id:"baba-de-camelo", c:"Portugal", r:"mediterranean", m:"sweet", t:180, s:6,
 i:[[397,"g","condensedmilk","sweet","leche condensada","condensed milk"],
    [4,"","egg","aerate","huevos pasteurizados, separadas claras y yemas","pasteurised eggs, separated"],
    [30,"g","almond","garnish","almendra laminada tostada","toasted flaked almonds"]],
 es:{n:"Baba de camelo", b:"Mousse de leche condensada caramelizada. Postre portugués de tres ingredientes.",
  st:["Hierve la lata cerrada de leche condensada cubierta de agua 2 horas y media. Deja enfriar del todo.",
      "Abre la lata y bate el dulce con las yemas.",
      "Bate las claras a punto de nieve e incorpóralas con movimientos envolventes.",
      "Reparte en copas, refrigera 2 horas y decora con la almendra."],
  tp:["La lata debe estar siempre cubierta de agua mientras hierve.",
      "Usa huevos pasteurizados porque no se cuecen."],
  v:"baba de camelo"},
 en:{n:"Baba de Camelo (Portuguese Caramel Mousse)", b:"A mousse of caramelised condensed milk. A three-ingredient Portuguese dessert.",
  st:["Boil the sealed can of condensed milk covered in water for 2 and a half hours. Cool completely.",
      "Open the can and beat the caramel with the yolks.",
      "Whisk the whites to stiff peaks and fold them in.",
      "Divide between glasses, chill 2 hours and top with the almonds."],
  tp:["Keep the can covered with water at all times while it boils.",
      "Use pasteurised eggs because they aren't cooked."],
  v:"portuguese caramel mousse"}},

{id:"torta-de-laranja", c:"Portugal", r:"mediterranean", m:"sweet", t:45, s:10,
 i:[[6,"","egg","structure","huevos","eggs"],
    [250,"g","sugar","sweet","azúcar","sugar"],
    [2,"","citrus","aromatic","naranjas","oranges","ralladura y jugo","zest and juice"],
    [1,"tbsp","cornstarch","structure","maicena","cornflour"],
    [30,"g","sugar","garnish","azúcar (para el papel)","sugar (for the paper)"]],
 es:{n:"Torta de laranja", b:"Brazo de naranja sin harina, húmedo y con piel caramelizada. Clásico de pastelería portuguesa.",
  st:["Bate los huevos con el azúcar 5 minutos.",
      "Añade la ralladura, 150 ml de jugo de naranja y la maicena.",
      "Forra una bandeja de 30 x 40 cm con papel, engrásalo y espolvorea el azúcar.",
      "Vierte la mezcla y hornea a 200 °C 15 minutos.",
      "Vuelca sobre un paño con azúcar, retira el papel y enrolla en caliente."],
  tp:["Enróllala en caliente o se agrieta.",
      "La superficie arrugada es la marca de una buena torta."],
  v:"torta de laranja"},
 en:{n:"Torta de Laranja (Portuguese Orange Roll)", b:"A flourless orange roll, moist with a caramelised skin. A Portuguese bakery classic.",
  st:["Whisk the eggs with the sugar for 5 minutes.",
      "Add the zest, 150 ml of orange juice and the cornflour.",
      "Line a 30 x 40 cm tray with paper, grease it and sprinkle with the sugar.",
      "Pour in the mixture and bake at 200 °C for 15 minutes.",
      "Turn onto a sugared cloth, peel off the paper and roll up while hot."],
  tp:["Roll it hot or it will crack.",
      "The wrinkled top is the mark of a good torta."],
  v:"portuguese orange roll"}},

{id:"pataniscas-de-bacalhau", c:"Portugal", r:"mediterranean", m:"snack", t:40, s:16,
 i:[[300,"g","whitefish","protein","bacalao salado desalado","desalted salt cod","desmenuzado","flaked"],
    [200,"g","apflour","structure","harina de trigo","plain flour"],
    [2,"","egg","binder","huevos","eggs"],
    [250,"ml","water","liquid","agua","water"],
    [1,"","onion","aromatic","cebolla","onion","picada fina","finely chopped"],
    [1,"handful","herb","aromatic","perejil","parsley","picado","chopped"],
    [1,"pinch","pepper","aromatic","pimienta","pepper"],
    [750,"ml","oil","fat","aceite para freír","oil for frying"]],
 es:{n:"Pataniscas de bacalhau", b:"Buñuelos planos de bacalao con perejil y cebolla. Tapa de las tascas de Lisboa.",
  st:["Bate la harina, los huevos y el agua hasta tener una masa lisa.",
      "Añade el bacalao, la cebolla, el perejil y la pimienta.",
      "Fríe cucharadas de masa a 180 °C, aplanándolas, 2 minutos por lado.",
      "Escurre en papel."],
  tp:["Prueba el bacalao: si está salado, remójalo más.",
      "Deben quedar planas e irregulares."],
  v:"pataniscas de bacalhau"},
 en:{n:"Pataniscas de Bacalhau (Salt Cod Fritters)", b:"Flat salt cod fritters with parsley and onion. A tapa in Lisbon's taverns.",
  st:["Whisk the flour, eggs and water into a smooth batter.",
      "Add the cod, onion, parsley and pepper.",
      "Fry spoonfuls at 180 °C, flattening them, for 2 minutes per side.",
      "Drain on paper."],
  tp:["Taste the cod: if salty, soak it longer.",
      "They should be flat and irregular."],
  v:"portuguese salt cod fritters"}}
];
