module.exports = [
{id:"caldo-verde", c:"Portugal", r:"mediterranean", m:"soup", t:45, s:6,
 i:[[4,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [800,"g","potato","structure","patatas harinosas","floury potatoes","en trozos","in chunks"],
    [1.5,"l","water","liquid","agua","water"],
    [2,"tsp","salt","salt","sal","salt"],
    [250,"g","veg","structure","col gallega o berza","Portuguese cabbage or kale","en tiras finísimas","in very fine shreds"],
    [150,"g","chorizo","protein","chouriço (chorizo portugués)","chouriço (Portuguese chorizo)","en rodajas finas","thinly sliced"]],
 es:{n:"Caldo verde", b:"Crema de patata con tiras finísimas de berza y rodajas de chouriço. La sopa nacional de Portugal.",
  st:["Sofríe la cebolla y el ajo en 2 cucharadas del aceite 5 minutos.",
      "Añade la patata, el agua y la sal y cuece 20 minutos, hasta que la patata esté tierna.",
      "Tritura hasta tener una crema lisa.",
      "Añade la berza y cuece 5 minutos sin tapar, para que quede verde.",
      "Dora el chouriço en una sartén 2 minutos. Sirve la sopa con el chouriço y el resto del aceite por encima."],
  tp:["Enrolla las hojas de berza como un puro y córtalas lo más fino posible; así se cuecen en 5 minutos.",
      "No tapes la olla después de añadir la berza o pierde el color."],
  v:"caldo verde receita portuguesa"},
 en:{n:"Caldo Verde (Portuguese Kale Soup)", b:"A potato purée with very fine ribbons of kale and slices of chouriço. Portugal's national soup.",
  st:["Cook the onion and garlic in 2 tablespoons of the oil for 5 minutes.",
      "Add the potato, water and salt and cook 20 minutes, until tender.",
      "Blend until smooth.",
      "Add the kale and cook 5 minutes uncovered, so it stays green.",
      "Brown the chouriço in a frying pan for 2 minutes. Serve the soup with the chouriço and the rest of the oil on top."],
  tp:["Roll the leaves like a cigar and slice as thin as you can; that way they cook in 5 minutes.",
      "Don't cover the pot after adding the kale or it loses its colour."],
  v:"caldo verde recipe"}},

{id:"bacalhau-a-bras", c:"Portugal", r:"mediterranean", m:"main", t:40, s:4,
 i:[[400,"g","whitefish","protein","bacalao desalado","desalted salt cod","desmigado","flaked"],
    [500,"g","potato","structure","patatas","potatoes","en bastones muy finos","in very thin matchsticks"],
    [500,"ml","oil","fat","aceite para freír","oil for frying"],
    [4,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [2,"","onion","aromatic","cebollas","onions","en juliana","thinly sliced"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [6,"","egg","binder","huevos","eggs","batidos","beaten"],
    [1,"handful","herb","garnish","perejil","parsley","picado","chopped"],
    [60,"g","olives","garnish","aceitunas negras","black olives"]],
 es:{n:"Bacalhau à Brás", b:"Bacalao desmigado con patatas paja y cebolla, ligado con huevo cremoso. Un clásico de las tascas de Lisboa.",
  st:["Fríe las patatas en el aceite a 170 °C durante 4 minutos, hasta que estén doradas y crujientes. Escúrrelas.",
      "Pocha la cebolla y el ajo en el aceite de oliva 10 minutos, hasta que estén blandos.",
      "Añade el bacalao y cuece 3 minutos.",
      "Añade las patatas y luego los huevos, removiendo a fuego bajo, solo hasta que el huevo esté cremoso.",
      "Retira del fuego, termina con el perejil y las aceitunas."],
  tp:["Retira del fuego cuando el huevo aún esté brillante; sigue cuajando con el calor.",
      "Prueba antes de salar: el bacalao desalado conserva algo de sal."],
  v:"bacalhau à brás receita"},
 en:{n:"Bacalhau à Brás (Salt Cod with Eggs and Potatoes)", b:"Flaked salt cod with matchstick potatoes and onion, bound with creamy egg. A classic of Lisbon taverns.",
  st:["Fry the potatoes in the oil at 170 °C for 4 minutes, until golden and crisp. Drain.",
      "Cook the onion and garlic gently in the olive oil for 10 minutes, until soft.",
      "Add the cod and cook 3 minutes.",
      "Add the potatoes and then the eggs, stirring over low heat, just until the egg is creamy.",
      "Take off the heat and finish with the parsley and olives."],
  tp:["Take it off the heat while the egg still looks glossy; it keeps setting.",
      "Taste before salting: desalted cod keeps some salt."],
  v:"bacalhau a bras recipe"}},

{id:"bifanas", c:"Portugal", r:"mediterranean", m:"main", t:30, s:4,
 i:[[500,"g","pork","protein","filetes finos de lomo de cerdo","thin pork loin steaks"],
    [4,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [200,"ml","winewhite","liquid","vino blanco","white wine"],
    [1,"tsp","paprika","aromatic","pimentón dulce","sweet paprika"],
    [1,"leaf","herb","aromatic","hoja de laurel","bay leaf"],
    [1,"tsp","salt","salt","sal","salt"],
    [2,"tbsp","lard","fat","manteca de cerdo","lard"],
    [4,"","bread","serve","panecillos","bread rolls"]],
 es:{n:"Bifanas", b:"Filetes finos de cerdo marinados en vino y ajo, en un panecillo. El bocadillo de la calle en Portugal.",
  st:["Golpea los filetes hasta dejarlos de 3 mm.",
      "Marina el cerdo con el ajo, el vino, el pimentón, el laurel y la sal al menos 1 hora.",
      "Calienta la manteca en una sartén y dora los filetes escurridos 1 minuto por lado.",
      "Añade la marinada y cuece 5 minutos, hasta que la salsa reduzca a la mitad.",
      "Abre los panecillos, moja el interior en la salsa y rellena con la carne."],
  tp:["Los filetes deben ser muy finos para que queden tiernos con tan poca cocción.",
      "Moja bien el pan en la salsa: es la mitad del sabor."],
  v:"bifanas receita"},
 en:{n:"Bifanas (Portuguese Pork Sandwiches)", b:"Thin pork steaks marinated in wine and garlic, in a soft roll. Portugal's street sandwich.",
  st:["Pound the steaks to 3 mm.",
      "Marinate the pork with the garlic, wine, paprika, bay and salt for at least 1 hour.",
      "Heat the lard in a frying pan and brown the drained steaks 1 minute a side.",
      "Add the marinade and cook 5 minutes, until the sauce reduces by half.",
      "Split the rolls, dip the insides in the sauce and fill with the meat."],
  tp:["The steaks must be very thin to stay tender with so little cooking.",
      "Soak the bread well in the sauce: it is half the flavour."],
  v:"bifanas recipe"}},

{id:"sardinhas-assadas", c:"Portugal", r:"mediterranean", m:"main", t:30, s:4,
 i:[[12,"","whitefish","protein","sardinas frescas enteras","whole fresh sardines"],
    [2,"tbsp","salt","salt","sal gruesa","coarse salt"],
    [3,"tbsp","oliveoil","fat","aceite de oliva","olive oil"],
    [2,"","bellpepper","serve","pimientos rojos","red bell peppers"],
    [1,"","onion","serve","cebolla","onion","en juliana","thinly sliced"],
    [1,"tbsp","winevinegar","acid","vinagre de vino","wine vinegar"],
    [800,"g","potato","serve","patatas pequeñas","small potatoes"]],
 es:{n:"Sardinas asadas a la portuguesa", b:"Sardinas enteras a la brasa con sal gruesa, pimientos asados y patatas. El olor de las fiestas de junio en Lisboa.",
  st:["Cubre las sardinas con la sal gruesa y deja 30 minutos. Sacude el exceso.",
      "Cuece las patatas en agua con sal 20 minutos.",
      "Asa los pimientos en la parrilla 15 minutos, pélalos y córtalos en tiras. Aliña con la cebolla, el vinagre y la mitad del aceite.",
      "Asa las sardinas a fuego fuerte 3 minutos por lado, hasta que la piel se ampolle.",
      "Sirve con las patatas y los pimientos, con el resto del aceite por encima."],
  tp:["No escames ni limpies las sardinas pequeñas: la tripa da sabor y se come alrededor.",
      "Engrasa bien la parrilla para que la piel no se pegue."],
  v:"sardinhas assadas receita"},
 en:{n:"Portuguese Grilled Sardines", b:"Whole sardines grilled with coarse salt, roasted peppers and potatoes. The smell of Lisbon's June festivals.",
  st:["Cover the sardines with the coarse salt and leave 30 minutes. Shake off the excess.",
      "Boil the potatoes in salted water for 20 minutes.",
      "Grill the peppers for 15 minutes, peel and slice. Dress with the onion, vinegar and half the oil.",
      "Grill the sardines over high heat for 3 minutes a side, until the skin blisters.",
      "Serve with the potatoes and peppers, with the rest of the oil on top."],
  tp:["Don't scale or gut small sardines: the insides add flavour and you eat around them.",
      "Oil the grill well so the skin doesn't stick."],
  v:"portuguese grilled sardines recipe"}},

{id:"polvo-a-lagareiro", c:"Portugal", r:"mediterranean", m:"main", t:90, s:4, o:200,
 i:[[1.5,"kg","squid","protein","pulpo","octopus","congelado y descongelado","frozen and thawed"],
    [1,"","onion","aromatic","cebolla","onion","en mitades","halved"],
    [4,"l","water","liquid","agua","water"],
    [800,"g","potato","structure","patatas pequeñas","small potatoes"],
    [2,"tbsp","salt","salt","sal gruesa","coarse salt"],
    [8,"clove","garlic","aromatic","ajo","garlic","laminado","sliced"],
    [200,"ml","oliveoil","fat","aceite de oliva virgen extra","extra virgin olive oil"],
    [1,"handful","herb","garnish","perejil","parsley","picado","chopped"]],
 es:{n:"Pulpo a lagareiro", b:"Pulpo cocido y luego asado, con patatas a murro y un baño de aceite caliente con ajo.",
  st:["Cuece el pulpo con la cebolla en el agua 40 minutos, hasta que esté tierno. Escúrrelo.",
      "Asa las patatas con la mitad de la sal gruesa a 200 °C durante 35 minutos. Dales un golpe con el puño para abrirlas.",
      "Pon el pulpo en una fuente con las patatas y asa 15 minutos más.",
      "Calienta el aceite con el ajo hasta que el ajo empiece a dorarse.",
      "Vierte el aceite caliente sobre el pulpo y las patatas y termina con el resto de la sal y el perejil."],
  tp:["Las patatas a murro se golpean para que el aceite entre en la pulpa.",
      "Si no tienes horno, dora el pulpo cocido en una plancha muy caliente 3 minutos por lado."],
  v:"polvo à lagareiro receita"},
 en:{n:"Polvo à Lagareiro (Roast Octopus with Garlic Oil)", b:"Boiled then roasted octopus with punched potatoes and a bath of hot garlic oil.",
  st:["Simmer the octopus with the onion in the water for 40 minutes, until tender. Drain.",
      "Roast the potatoes with half the coarse salt at 200 °C for 35 minutes. Give each a punch to split it.",
      "Put the octopus in a dish with the potatoes and roast 15 minutes more.",
      "Heat the oil with the garlic until the garlic begins to colour.",
      "Pour the hot oil over the octopus and potatoes and finish with the rest of the salt and the parsley."],
  tp:["The potatoes are punched so the oil gets into the flesh.",
      "Without an oven, brown the boiled octopus on a very hot griddle for 3 minutes a side."],
  v:"polvo a lagareiro recipe"}},

{id:"arroz-doce", c:"Portugal", r:"mediterranean", m:"sweet", t:60, s:8,
 i:[[200,"g","rice","structure","arroz redondo","short-grain rice"],
    [500,"ml","water","liquid","agua","water"],
    [1,"","citrus","aromatic","cáscara de limón","lemon peel","en una tira","in one strip"],
    [1,"pinch","salt","salt","sal","salt"],
    [1,"l","milk","liquid","leche caliente","hot milk"],
    [200,"g","sugar","sweet","azúcar","sugar"],
    [4,"","eggyolk","enrich","yemas de huevo","egg yolks"],
    [2,"tsp","spice","garnish","canela molida","ground cinnamon"]],
 es:{n:"Arroz doce", b:"Arroz con leche portugués ligado con yemas y decorado con dibujos de canela. Dulce de fiestas y bodas.",
  st:["Cuece el arroz en el agua con la cáscara de limón y la sal 10 minutos, hasta que absorba el agua.",
      "Añade la leche caliente poco a poco y cuece 30 minutos a fuego bajo, removiendo a menudo.",
      "Añade el azúcar y cuece 5 minutos más.",
      "Retira del fuego y saca el limón. Tempera las yemas con un poco del arroz y añádelas, removiendo rápido.",
      "Reparte en una fuente y, cuando esté frío, dibuja con la canela."],
  tp:["Añade las yemas fuera del fuego para que no cuajen.",
      "Los dibujos de canela se hacen con una plantilla de papel o espolvoreando entre los dedos."],
  v:"arroz doce receita portuguesa"},
 en:{n:"Arroz Doce (Portuguese Rice Pudding)", b:"Portuguese rice pudding enriched with yolks and decorated with cinnamon patterns. For feasts and weddings.",
  st:["Cook the rice in the water with the lemon peel and salt for 10 minutes, until absorbed.",
      "Add the hot milk a little at a time and cook 30 minutes on low, stirring often.",
      "Add the sugar and cook 5 minutes more.",
      "Take off the heat and remove the lemon. Temper the yolks with a little of the rice and stir them in quickly.",
      "Spread in a dish and, once cold, draw patterns with the cinnamon."],
  tp:["Add the yolks off the heat so they don't scramble.",
      "The cinnamon patterns are made with a paper stencil or by sprinkling between your fingers."],
  v:"portuguese rice pudding recipe"}},

{id:"bolinhos-de-bacalhau", c:"Portugal", r:"mediterranean", m:"snack", t:60, s:24,
 i:[[300,"g","whitefish","protein","bacalao desalado","desalted salt cod"],
    [400,"g","potato","structure","patatas harinosas","floury potatoes","cocidas y hechas puré","boiled and mashed"],
    [1,"","onion","aromatic","cebolla pequeña","small onion","rallada","grated"],
    [1,"handful","herb","aromatic","perejil","parsley","picado fino","finely chopped"],
    [3,"","egg","binder","huevos","eggs"],
    [1,"pinch","spice","aromatic","nuez moscada","nutmeg"],
    [1,"l","oil","fat","aceite para freír","oil for frying"]],
 es:{n:"Bolinhos de bacalhau", b:"Croquetas de bacalao y patata en forma de quenelle, doradas por fuera y esponjosas por dentro.",
  st:["Cuece el bacalao en agua 5 minutos. Escúrrelo, quita piel y espinas y desmígalo muy fino.",
      "Mezcla el bacalao, el puré de patata, la cebolla, el perejil y la nuez moscada.",
      "Añade los huevos uno a uno y bate con cuchara 3 minutos, hasta que la masa esté ligera.",
      "Forma quenelles con dos cucharas.",
      "Fríe a 175 °C durante 4 minutos, hasta que estén doradas. Escurre sobre papel."],
  tp:["El puré debe estar seco; patatas acuosas hacen bolinhos que se abren.",
      "Prueba la masa antes de freír: el bacalao suele aportar toda la sal."],
  v:"bolinhos de bacalhau receita"},
 en:{n:"Bolinhos de Bacalhau (Salt Cod Fritters)", b:"Salt cod and potato fritters shaped like quenelles, golden outside and fluffy within.",
  st:["Simmer the cod in water for 5 minutes. Drain, remove skin and bones and flake very finely.",
      "Mix the cod, mashed potato, onion, parsley and nutmeg.",
      "Add the eggs one at a time and beat with a spoon for 3 minutes, until light.",
      "Shape into quenelles with two spoons.",
      "Fry at 175 °C for 4 minutes, until golden. Drain on paper."],
  tp:["The mash must be dry; watery potatoes make fritters that split.",
      "Taste the mixture before frying: the cod usually brings all the salt."],
  v:"bolinhos de bacalhau recipe"}},

{id:"carne-de-porco-alentejana", c:"Portugal", r:"mediterranean", m:"main", t:60, s:4,
 i:[[700,"g","pork","protein","magro de cerdo","lean pork","en dados de 3 cm","in 3 cm dice"],
    [2,"tbsp","bellpepper","aromatic","pasta de pimiento rojo (massa de pimentão)","red pepper paste (massa de pimentão)"],
    [4,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [200,"ml","winewhite","liquid","vino blanco","white wine"],
    [1,"leaf","herb","aromatic","hoja de laurel","bay leaf"],
    [3,"tbsp","lard","fat","manteca de cerdo","lard"],
    [1,"kg","clam","protein","almejas","clams","purgadas en agua con sal","purged in salted water"],
    [600,"g","potato","serve","patatas","potatoes","en dados de 2 cm, fritas","in 2 cm dice, fried"],
    [1,"handful","herb","garnish","cilantro","cilantro","picado","chopped"],
    [1,"","citrus","garnish","limón","lemon","en gajos","in wedges"]],
 es:{n:"Carne de cerdo a la alentejana", b:"Cerdo marinado en pasta de pimiento y vino, con almejas y patatas fritas. Mar y montaña del sur de Portugal.",
  st:["Marina el cerdo con la pasta de pimiento, el ajo, el vino y el laurel al menos 4 horas.",
      "Escurre el cerdo, guarda la marinada, y dóralo en la manteca 8 minutos a fuego fuerte.",
      "Añade la marinada y cuece 15 minutos, hasta que reduzca.",
      "Añade las almejas, tapa y cuece 5 minutos, hasta que se abran. Tira las que sigan cerradas.",
      "Mezcla con las patatas fritas, termina con el cilantro y sirve con el limón."],
  tp:["La massa de pimentão es salada; no añadas sal hasta probar.",
      "Deja las almejas en agua con sal 1 hora para que suelten la arena."],
  v:"carne de porco à alentejana receita"},
 en:{n:"Carne de Porco à Alentejana (Pork and Clams)", b:"Pork marinated in red pepper paste and wine, with clams and fried potatoes. Surf and turf from southern Portugal.",
  st:["Marinate the pork with the pepper paste, garlic, wine and bay for at least 4 hours.",
      "Drain the pork, keeping the marinade, and brown it in the lard for 8 minutes over high heat.",
      "Add the marinade and cook 15 minutes, until reduced.",
      "Add the clams, cover and cook 5 minutes, until they open. Discard any that stay shut.",
      "Toss with the fried potatoes, finish with the cilantro and serve with the lemon."],
  tp:["Massa de pimentão is salty; don't add salt until you've tasted.",
      "Leave the clams in salted water for 1 hour so they release their sand."],
  v:"carne de porco a alentejana recipe"}},

{id:"arroz-de-pato", c:"Portugal", r:"mediterranean", m:"main", t:150, s:6, o:200,
 i:[[1,"","duck","protein","pato entero (unos 2 kg)","whole duck (about 2 kg)","en cuartos","quartered"],
    [2,"l","water","liquid","agua","water"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"leaf","herb","aromatic","hoja de laurel","bay leaf"],
    [2,"tsp","salt","salt","sal","salt"],
    [400,"g","rice","structure","arroz carolino o de grano medio","carolino or medium-grain rice"],
    [150,"g","chorizo","protein","chouriço (chorizo portugués)","chouriço (Portuguese chorizo)","en rodajas","sliced"],
    [80,"g","bacon","protein","tocino ahumado","smoked bacon","en tiras","in strips"]],
 es:{n:"Arroz de pato", b:"Arroz cocido en el jugo del pato, con la carne desmenuzada y chouriço, gratinado en el horno.",
  st:["Cuece el pato en el agua con la mitad de la cebolla, el laurel y la sal 90 minutos. Saca el pato y desmenúzalo. Guarda 1 l del líquido y quita la grasa de arriba.",
      "Sofríe el resto de la cebolla y el ajo en 2 cucharadas de la grasa del pato 5 minutos.",
      "Añade el arroz y el líquido reservado, cuece 12 minutos y mezcla con la carne.",
      "Pasa a una fuente y cubre con el chouriço y el tocino.",
      "Hornea a 200 °C durante 15 minutos, hasta que el chouriço esté tostado y el arroz seco por arriba."],
  tp:["Enfriar el líquido de cocción hace fácil retirar la grasa, que se guarda para freír patatas.",
      "Se prepara con antelación hasta el paso 4 y se hornea al servir."],
  v:"arroz de pato receita"},
 en:{n:"Arroz de Pato (Portuguese Duck Rice)", b:"Rice cooked in the duck's own cooking liquid, with shredded meat and chouriço, baked until crisp on top.",
  st:["Simmer the duck in the water with half the onion, the bay and salt for 90 minutes. Lift out and shred. Keep 1 l of the liquid and skim the fat.",
      "Cook the rest of the onion and the garlic in 2 tablespoons of the duck fat for 5 minutes.",
      "Add the rice and the reserved liquid, cook 12 minutes and mix in the meat.",
      "Transfer to a dish and cover with the chouriço and bacon.",
      "Bake at 200 °C for 15 minutes, until the chouriço is crisp and the rice dry on top."],
  tp:["Chilling the cooking liquid makes the fat easy to lift; keep it for frying potatoes.",
      "Make it ahead up to step 4 and bake to serve."],
  v:"arroz de pato recipe"}},

{id:"pao-de-lo", c:"Portugal", r:"mediterranean", m:"sweet", t:60, s:10, o:180,
 i:[[6,"","egg","aerate","huevos","eggs"],
    [4,"","eggyolk","enrich","yemas de huevo","egg yolks"],
    [200,"g","sugar","sweet","azúcar","sugar"],
    [100,"g","apflour","structure","harina de trigo","plain flour","tamizada","sifted"],
    [1,"pinch","salt","salt","sal","salt"]],
 es:{n:"Pão de ló", b:"Bizcocho portugués solo de huevo, azúcar y harina, esponjoso por fuera y cremoso por dentro.",
  st:["Forra un molde de 24 cm con papel de horno arrugado.",
      "Bate los huevos, las yemas, el azúcar y la sal 15 minutos a velocidad alta, hasta que tripliquen su volumen.",
      "Incorpora la harina con espátula en tres veces, con movimientos envolventes.",
      "Vierte en el molde y hornea a 180 °C durante 25 minutos. El centro debe quedar húmedo.",
      "Deja enfriar en el molde y sirve con el papel."],
  tp:["El batido largo es la única levadura: no lo acortes.",
      "No abras el horno en los primeros 20 minutos o se hunde."],
  v:"pão de ló de ovar receita"},
 en:{n:"Pão de Ló (Portuguese Sponge)", b:"A Portuguese sponge of just egg, sugar and flour, fluffy outside and creamy in the middle.",
  st:["Line a 24 cm tin with crumpled baking paper.",
      "Whisk the eggs, yolks, sugar and salt for 15 minutes on high, until tripled in volume.",
      "Fold in the flour with a spatula in three goes.",
      "Pour into the tin and bake at 180 °C for 25 minutes. The centre should stay moist.",
      "Cool in the tin and serve on its paper."],
  tp:["The long whisking is the only leavening: don't cut it short.",
      "Don't open the oven for the first 20 minutes or it will sink."],
  v:"pao de lo recipe"}}
];
