module.exports = [
{id:"vitel-tone", c:"Argentina", r:"latin-america", m:"starter", t:120, s:8,
 i:[[1.2,"kg","veal","protein","peceto de ternera","veal eye of round"],
    [1.5,"l","water","liquid","agua","water"],
    [1,"","onion","aromatic","cebolla","onion","en mitades","halved"],
    [1,"","veg","aromatic","zanahoria","carrot"],
    [1,"leaf","herb","aromatic","hoja de laurel","bay leaf"],
    [150,"ml","winewhite","liquid","vino blanco","white wine"],
    [1,"tsp","salt","salt","sal","salt"],
    [250,"g","mayo","sauce","mayonesa","mayonnaise"],
    [160,"g","tuna","sauce","atún en aceite","tuna in oil","escurrido","drained"],
    [4,"","anchovy","umami","filetes de anchoa","anchovy fillets"],
    [2,"tbsp","capers","garnish","alcaparras","capers"]],
 es:{n:"Vitel toné", b:"Carne fría en lonchas finas con salsa de atún, anchoas y mayonesa. Infaltable en la mesa de Navidad argentina.",
  st:["Cuece la carne en el agua con la cebolla, la zanahoria, el laurel, el vino y la sal 90 minutos a fuego bajo. Deja enfriar en el líquido.",
      "Corta la carne fría en lonchas muy finas.",
      "Licúa la mayonesa, el atún y las anchoas con 4 cucharadas del líquido de cocción hasta tener una salsa lisa.",
      "Coloca la carne en una fuente y cúbrela con la salsa.",
      "Decora con las alcaparras y refrigera al menos 2 horas."],
  tp:["Enfriar la carne en su líquido la mantiene jugosa.",
      "Se prepara un día antes: gana sabor."],
  v:"vitel toné receta argentina"},
 en:{n:"Vitel Toné (Veal in Tuna Sauce)", b:"Thin slices of cold veal under a sauce of tuna, anchovy and mayonnaise. A must on the Argentine Christmas table.",
  st:["Simmer the veal in the water with the onion, carrot, bay, wine and salt for 90 minutes on low. Cool in the liquid.",
      "Slice the cold meat very thinly.",
      "Blend the mayonnaise, tuna and anchovies with 4 tablespoons of the cooking liquid until smooth.",
      "Lay the meat on a platter and cover with the sauce.",
      "Scatter over the capers and chill at least 2 hours."],
  tp:["Cooling the meat in its liquid keeps it juicy.",
      "Make it a day ahead: it gains flavour."],
  v:"vitel tone recipe"}},

{id:"guiso-de-lentejas-ar", c:"Argentina", r:"latin-america", m:"main", t:75, s:6,
 i:[[400,"g","legume","protein","lentejas","lentils","remojadas 2 horas","soaked 2 hours"],
    [150,"g","pancetta","protein","panceta","pancetta","en dados","diced"],
    [2,"","chorizo","protein","chorizos colorados","Spanish-style chorizos","en rodajas","sliced"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","morrón rojo","red bell pepper","picado","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"","veg","structure","zanahoria","carrot","en dados","diced"],
    [300,"g","tomato","sauce","puré de tomate","tomato purée"],
    [1,"tsp","paprika","aromatic","pimentón dulce","sweet paprika"],
    [2,"","potato","structure","papas","potatoes","en dados","diced"],
    [300,"g","veg","structure","calabaza","squash","en dados","diced"],
    [1.5,"l","water","liquid","agua caliente","hot water"],
    [1,"leaf","herb","aromatic","hoja de laurel","bay leaf"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Guiso de lentejas", b:"Guiso espeso de lentejas con panceta, chorizo colorado, papa y calabaza. Comida de invierno y de 25 de mayo.",
  st:["Dora la panceta y el chorizo en el aceite 5 minutos.",
      "Añade la cebolla, el morrón y el ajo y cuece 8 minutos. Añade la zanahoria y el pimentón.",
      "Añade el puré de tomate y cuece 5 minutos.",
      "Añade las lentejas escurridas, el agua, el laurel y la sal y cuece 25 minutos.",
      "Añade la papa y la calabaza y cuece 20 minutos más, hasta que todo esté tierno y espeso."],
  tp:["Deja reposar 10 minutos antes de servir; espesa y se asienta.",
      "Rinde para dos días; recalienta con un poco de agua."],
  v:"guiso de lentejas argentino"},
 en:{n:"Argentine Lentil Stew", b:"A thick lentil stew with pancetta, chorizo, potato and squash. Winter food, and a 25 May tradition.",
  st:["Brown the pancetta and chorizo in the oil for 5 minutes.",
      "Add the onion, pepper and garlic and cook 8 minutes. Add the carrot and paprika.",
      "Add the tomato purée and cook 5 minutes.",
      "Add the drained lentils, water, bay and salt and cook 25 minutes.",
      "Add the potato and squash and cook 20 minutes more, until tender and thick."],
  tp:["Rest 10 minutes before serving; it thickens and settles.",
      "It lasts two days; reheat with a little water."],
  v:"argentine lentil stew recipe"}},

{id:"pastelitos-criollos", c:"Argentina", r:"latin-america", m:"sweet", t:60, s:12,
 i:[[500,"g","puffpastry","structure","masa de hojaldre","puff pastry"],
    [300,"g","quincepaste","sweet","dulce de membrillo","quince paste","en cubos","in cubes"],
    [1,"l","oil","fat","aceite para freír","oil for frying"],
    [200,"g","sugar","glaze","azúcar","sugar"],
    [150,"ml","water","liquid","agua","water"],
    [1,"","citrus","aromatic","cáscara de naranja","orange peel"]],
 es:{n:"Pastelitos criollos", b:"Estrellas de hojaldre rellenas de membrillo, fritas y bañadas en almíbar. Se comen el 25 de mayo.",
  st:["Estira el hojaldre a 3 mm y corta 24 cuadrados de 10 cm.",
      "Pon un cubo de membrillo en el centro de un cuadrado y cubre con otro girado 45 grados, formando una estrella. Pega las puntas con agua.",
      "Cuece el azúcar con el agua y la cáscara de naranja 5 minutos hasta tener un almíbar ligero.",
      "Fríe los pastelitos a 170 °C durante 3 minutos, hasta que se abran y doren.",
      "Pásalos por el almíbar tibio y deja escurrir."],
  tp:["El aceite no debe estar muy caliente o se doran antes de abrir las capas.",
      "Pellizca cada punta hacia arriba para que la estrella se note."],
  v:"pastelitos criollos de membrillo"},
 en:{n:"Pastelitos Criollos (Quince Pastry Stars)", b:"Puff pastry stars filled with quince paste, fried and dipped in syrup. Eaten on 25 May.",
  st:["Roll the pastry to 3 mm and cut 24 squares of 10 cm.",
      "Put a cube of quince in the centre of one square and cover with another turned 45 degrees, making a star. Stick the points with water.",
      "Simmer the sugar with the water and orange peel for 5 minutes to a light syrup.",
      "Fry the pastries at 170 °C for 3 minutes, until they open and turn golden.",
      "Dip them in the warm syrup and drain."],
  tp:["The oil shouldn't be too hot or they brown before the layers open.",
      "Pinch each point upward so the star shape shows."],
  v:"pastelitos criollos recipe"}},

{id:"noquis-de-papa", c:"Argentina", r:"latin-america", m:"main", t:60, s:4,
 i:[[1,"kg","potato","structure","papas harinosas","floury potatoes"],
    [250,"g","apflour","structure","harina de trigo","plain flour"],
    [1,"","egg","binder","huevo","egg"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"pinch","spice","aromatic","nuez moscada","nutmeg"],
    [60,"g","butter","sauce","mantequilla","butter"],
    [8,"leaf","herb","aromatic","hojas de salvia","sage leaves"],
    [60,"g","parmesan","garnish","queso parmesano rallado","grated parmesan"]],
 es:{n:"Ñoquis de papa", b:"Ñoquis caseros de papa con manteca y salvia. En Argentina se comen el 29 de cada mes con un billete bajo el plato.",
  st:["Hierve las papas con piel 25 minutos. Pélalas calientes y pásalas por el pisapuré.",
      "Añade el huevo, la sal, la nuez moscada y la harina poco a poco hasta tener una masa suave que no se pegue.",
      "Haz cilindros de 2 cm, corta trozos de 2 cm y pásalos por un tenedor.",
      "Cuece en agua hirviendo con sal hasta que floten, 2 minutos.",
      "Derrite la mantequilla con la salvia hasta que haga espuma, saltea los ñoquis y sirve con el queso."],
  tp:["Usa la menor cantidad de harina posible: los ñoquis quedan más livianos.",
      "Prueba cociendo uno antes; si se deshace, añade un poco de harina."],
  v:"ñoquis de papa caseros"},
 en:{n:"Ñoquis de Papa (Potato Gnocchi)", b:"Homemade potato gnocchi with butter and sage. In Argentina they're eaten on the 29th of each month, with a banknote under the plate.",
  st:["Boil the potatoes in their skins for 25 minutes. Peel while hot and press through a ricer.",
      "Add the egg, salt, nutmeg and the flour gradually to a soft dough that doesn't stick.",
      "Roll into 2 cm ropes, cut 2 cm pieces and roll them over a fork.",
      "Cook in boiling salted water until they float, 2 minutes.",
      "Melt the butter with the sage until foaming, toss the gnocchi and serve with the cheese."],
  tp:["Use as little flour as you can: the gnocchi turn out lighter.",
      "Test-cook one first; if it falls apart, add a little flour."],
  v:"potato gnocchi recipe"}},

{id:"budin-de-pan", c:"Argentina", r:"latin-america", m:"sweet", t:90, s:10, o:170,
 i:[[150,"g","sugar","caramel","azúcar para el caramelo","sugar for the caramel"],
    [300,"g","bread","structure","pan del día anterior","day-old bread","en trozos","torn"],
    [750,"ml","milk","liquid","leche","milk"],
    [4,"","egg","set","huevos","eggs"],
    [150,"g","sugar","sweet","azúcar","sugar"],
    [1,"","citrus","aromatic","ralladura de naranja","orange zest"],
    [80,"g","driedfruit","sweet","pasas","raisins"]],
 es:{n:"Budín de pan", b:"Pan viejo remojado en leche y horneado al baño María con caramelo. El postre de aprovechamiento de las abuelas.",
  st:["Haz un caramelo con 150 g de azúcar y cubre un molde de budín inglés.",
      "Remoja el pan en la leche 20 minutos y aplástalo con un tenedor.",
      "Bate los huevos con 150 g de azúcar y la ralladura. Mezcla con el pan y las pasas.",
      "Vierte en el molde y hornea al baño María a 170 °C durante 60 minutos, hasta que un palillo salga limpio.",
      "Enfría, refrigera 4 horas y desmolda."],
  tp:["Cuanto más seco el pan, más leche absorbe.",
      "Desmolda frío para que no se rompa."],
  v:"budín de pan receta"},
 en:{n:"Budín de Pan (Argentine Bread Pudding)", b:"Stale bread soaked in milk and baked in a water bath with caramel. Grandma's thrifty dessert.",
  st:["Make a caramel with 150 g of sugar and coat a loaf tin.",
      "Soak the bread in the milk for 20 minutes and mash with a fork.",
      "Whisk the eggs with 150 g of sugar and the zest. Mix with the bread and raisins.",
      "Pour into the tin and bake in a water bath at 170 °C for 60 minutes, until a skewer comes out clean.",
      "Cool, refrigerate 4 hours and turn out."],
  tp:["The drier the bread, the more milk it soaks up.",
      "Turn it out cold so it doesn't break."],
  v:"bread pudding recipe"}},

{id:"torta-rogel", c:"Argentina", r:"latin-america", m:"sweet", t:120, s:12, o:200,
 i:[[400,"g","apflour","structure","harina de trigo","plain flour"],
    [8,"","eggyolk","binder","yemas de huevo","egg yolks"],
    [50,"g","butter","fat","mantequilla blanda","soft butter"],
    [100,"ml","water","liquid","agua fría","cold water"],
    [1,"pinch","salt","salt","sal","salt"],
    [1,"kg","dulcedeleche","sweet","dulce de leche repostero","thick dulce de leche"],
    [4,"","eggwhite","aerate","claras de huevo","egg whites"],
    [250,"g","sugar","sweet","azúcar","sugar"],
    [80,"ml","water","liquid","agua para el merengue","water for the meringue"]],
 es:{n:"Torta Rogel", b:"Capas finísimas de masa crocante con dulce de leche y un merengue italiano encima. La torta de cumpleaños argentina.",
  st:["Mezcla la harina, las yemas, la mantequilla, el agua y la sal. Amasa 5 minutos hasta que esté lisa. Deja 30 minutos.",
      "Divide en 8 bollos y estira cada uno muy fino en un círculo de 24 cm. Pínchalos.",
      "Hornea cada disco a 200 °C durante 6 minutos, hasta que esté apenas dorado. Enfría.",
      "Arma la torta alternando discos y dulce de leche.",
      "Hierve el azúcar con el agua del merengue hasta 118 °C. Viértelo en hilo sobre las claras batidas y bate 8 minutos, hasta que esté frío. Cubre la torta."],
  tp:["Arma la torta la noche anterior: las capas se ablandan un poco y se corta mejor.",
      "El dulce de leche repostero es más firme y no se escurre."],
  v:"torta rogel receta"},
 en:{n:"Torta Rogel (Dulce de Leche Layer Cake)", b:"Paper-thin crisp pastry layers with dulce de leche and an Italian meringue on top. Argentina's birthday cake.",
  st:["Mix the flour, yolks, butter, water and salt. Knead 5 minutes until smooth. Rest 30 minutes.",
      "Divide into 8 balls and roll each very thin into a 24 cm circle. Prick them.",
      "Bake each disc at 200 °C for 6 minutes, until barely golden. Cool.",
      "Build the cake alternating discs and dulce de leche.",
      "Boil the sugar with the meringue water to 118 °C. Pour in a thin stream onto the whisked whites and whisk 8 minutes, until cool. Cover the cake."],
  tp:["Assemble the night before: the layers soften slightly and it slices better.",
      "Baker's dulce de leche is firmer and doesn't run."],
  v:"torta rogel recipe"}},

{id:"pascualina", c:"Uruguay", r:"latin-america", m:"main", t:75, s:8, o:190,
 i:[[2,"","shortcrust","structure","tapas para pascualina","shortcrust pastry rounds"],
    [1,"kg","veg","structure","acelga","Swiss chard","hervida, escurrida y picada","boiled, squeezed and chopped"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [80,"g","parmesan","enrich","queso rallado","grated cheese"],
    [2,"","egg","binder","huevos batidos","beaten eggs"],
    [5,"","egg","protein","huevos enteros","whole eggs"],
    [1,"pinch","spice","aromatic","nuez moscada","nutmeg"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Pascualina", b:"Tarta de acelga con huevos enteros escondidos que aparecen al cortar. Se hace en Semana Santa en Uruguay.",
  st:["Sofríe la cebolla en el aceite 5 minutos. Mezcla con la acelga, el queso, los huevos batidos, la nuez moscada y la sal.",
      "Forra un molde de 26 cm con una tapa y rellena con la acelga.",
      "Haz 5 huecos en el relleno y casca un huevo entero en cada uno.",
      "Cubre con la otra tapa, sella el borde con un repulgue y pincha la superficie.",
      "Hornea a 190 °C durante 40 minutos, hasta que esté dorada."],
  tp:["Escurre muy bien la acelga o la masa de abajo queda cruda.",
      "Marca dónde quedan los huevos para cortar por ellos."],
  v:"pascualina uruguaya receta"},
 en:{n:"Pascualina (Easter Chard Pie)", b:"A chard pie with whole eggs hidden inside that appear when you cut it. Made for Holy Week in Uruguay.",
  st:["Cook the onion in the oil for 5 minutes. Mix with the chard, cheese, beaten eggs, nutmeg and salt.",
      "Line a 26 cm tin with one pastry round and fill with the chard.",
      "Make 5 hollows in the filling and crack a whole egg into each.",
      "Cover with the other round, crimp the edge and prick the top.",
      "Bake at 190 °C for 40 minutes, until golden."],
  tp:["Squeeze the chard very well or the bottom pastry stays raw.",
      "Mark where the eggs sit so you can cut through them."],
  v:"pascualina recipe"}},

{id:"mbeju", c:"Paraguay", r:"latin-america", m:"breakfast", t:25, s:4,
 i:[[300,"g","cassavastarch","structure","almidón de mandioca","cassava starch"],
    [150,"g","queso","protein","queso Paraguay o queso fresco","Paraguayan or fresh cheese","rallado","grated"],
    [50,"g","butter","fat","mantequilla","butter"],
    [80,"ml","milk","liquid","leche","milk"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Mbejú", b:"Torta de almidón de mandioca y queso hecha en sartén, crocante por fuera. Se acompaña con cocido en Paraguay.",
  st:["Mezcla el almidón con la sal y la mantequilla hasta tener una arena gruesa.",
      "Añade el queso y la leche poco a poco, frotando con las manos, hasta que parezca arena húmeda.",
      "Calienta una sartén de 20 cm a fuego medio y pon la mitad de la mezcla, aplanando.",
      "Cuece 3 minutos hasta que se una y dore, voltea y cuece 2 minutos más.",
      "Repite con el resto y sirve caliente."],
  tp:["La mezcla no debe ser una masa: debe quedar granulada.",
      "Si se desarma al voltear, le falta un poco de leche."],
  v:"mbeju paraguayo receta"},
 en:{n:"Mbejú (Paraguayan Cassava Cheese Cake)", b:"A pan-cooked cake of cassava starch and cheese, crisp outside. Eaten with yerba cocido in Paraguay.",
  st:["Mix the starch with the salt and butter to a coarse sand.",
      "Add the cheese and milk a little at a time, rubbing with your hands, until like damp sand.",
      "Heat a 20 cm frying pan over medium heat and add half the mixture, pressing flat.",
      "Cook 3 minutes until it fuses and browns, flip and cook 2 minutes more.",
      "Repeat with the rest and serve hot."],
  tp:["The mixture shouldn't be a dough: it should stay crumbly.",
      "If it falls apart when flipped, it needs a little more milk."],
  v:"mbeju recipe"}},

{id:"chipa-guasu", c:"Paraguay", r:"latin-america", m:"side", t:70, s:8, o:180,
 i:[[600,"g","corn","structure","granos de choclo","sweetcorn kernels"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [4,"","egg","binder","huevos","eggs"],
    [200,"ml","milk","liquid","leche","milk"],
    [250,"g","queso","protein","queso Paraguay o fresco","Paraguayan or fresh cheese","desmenuzado","crumbled"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Chipa guasu", b:"Pastel de choclo licuado con queso y huevo, húmedo y dorado. Compañero del asado en Paraguay.",
  st:["Sofríe la cebolla en el aceite 5 minutos.",
      "Licúa el choclo con la leche, dejando algo de textura.",
      "Bate los huevos y mezcla con el choclo, la cebolla, el queso y la sal.",
      "Vierte en un molde engrasado de 22 x 30 cm.",
      "Hornea a 180 °C durante 45 minutos, hasta que esté dorado y firme."],
  tp:["Deja enfriar 10 minutos antes de cortar.",
      "Con choclo congelado, descongélalo y sécalo bien."],
  v:"chipa guasu receta"},
 en:{n:"Chipa Guasu (Paraguayan Corn and Cheese Bake)", b:"A bake of blended sweetcorn with cheese and egg, moist and golden. The partner to a Paraguayan asado.",
  st:["Cook the onion in the oil for 5 minutes.",
      "Blend the corn with the milk, leaving some texture.",
      "Whisk the eggs and mix with the corn, onion, cheese and salt.",
      "Pour into a greased 22 x 30 cm dish.",
      "Bake at 180 °C for 45 minutes, until golden and set."],
  tp:["Let it cool 10 minutes before cutting.",
      "With frozen corn, thaw and dry it well."],
  v:"chipa guasu recipe"}},

{id:"kiveve", c:"Paraguay", r:"latin-america", m:"side", t:45, s:6,
 i:[[1,"kg","veg","structure","calabaza (andaí)","pumpkin (andaí)","pelada, en trozos","peeled, in chunks"],
    [500,"ml","water","liquid","agua","water"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [250,"ml","milk","liquid","leche","milk"],
    [80,"g","cornmeal","thicken","harina de maíz","cornmeal"],
    [1,"tbsp","sugar","sweet","azúcar","sugar"],
    [150,"g","queso","protein","queso Paraguay o fresco","Paraguayan or fresh cheese","en dados","diced"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Kiveve", b:"Crema espesa y anaranjada de calabaza con harina de maíz y queso. Plato guaraní, dulce y salado.",
  st:["Cuece la calabaza en el agua 20 minutos y aplástala con su líquido.",
      "Sofríe la cebolla en el aceite 5 minutos y añádela a la calabaza.",
      "Mezcla la harina de maíz con la leche y añádela, removiendo.",
      "Añade el azúcar y la sal y cuece 10 minutos a fuego bajo, sin parar de remover.",
      "Añade el queso y retira cuando empiece a fundirse."],
  tp:["Debe quedar como un puré espeso, no como sopa.",
      "Se sirve con carne asada o solo, como plato principal."],
  v:"kiveve paraguayo receta"},
 en:{n:"Kiveve (Paraguayan Pumpkin and Cheese Cream)", b:"A thick orange cream of pumpkin with cornmeal and cheese. A Guaraní dish, sweet and savoury.",
  st:["Cook the pumpkin in the water for 20 minutes and mash with its liquid.",
      "Cook the onion in the oil for 5 minutes and add to the pumpkin.",
      "Mix the cornmeal with the milk and add, stirring.",
      "Add the sugar and salt and cook 10 minutes on low, stirring constantly.",
      "Add the cheese and take off the heat as it begins to melt."],
  tp:["It should be like a thick mash, not a soup.",
      "It's served with grilled meat or on its own as a main."],
  v:"kiveve recipe"}}
];
