module.exports = [
{id:"tallarines-con-tuco", c:"Argentina", r:"latin-america", m:"main", t:120, s:4,
 i:[[400,"g","apflour","structure","harina de trigo","plain flour"],
    [4,"","egg","structure","huevos","eggs"],
    [0.5,"tsp","salt","salt","sal (para la masa)","salt (for the dough)"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [500,"g","beef","protein","carne de res para guiso (roast beef)","beef braising cut","en trozos","in pieces"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","morrón rojo","red bell pepper","picado","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [800,"g","tomato","liquid","tomate triturado","crushed tomatoes"],
    [2,"leaf","herb","aromatic","laurel","bay leaves"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [1,"tsp","sugar","sweet","azúcar","sugar"],
    [2,"tsp","salt","salt","sal","salt"],
    [60,"g","parmesan","garnish","queso rallado","grated parmesan"]],
 es:{n:"Tallarines caseros con tuco", b:"Tallarines de huevo hechos a mano con tuco de carne cocido despacio. El almuerzo de domingo de la nona en Argentina.",
  st:["Haz un volcán con la harina y la sal, pon los huevos en el centro y amasa 10 minutos. Reposa 30 minutos tapada.",
      "Dora la carne en el aceite 6 minutos. Añade la cebolla, el morrón y el ajo y cocina 8 minutos.",
      "Añade el tomate, el laurel, el orégano, el azúcar y la sal. Cuece tapado 60 minutos a fuego bajo.",
      "Estira la masa muy fina, enharínala, enróllala y corta tiras de 5 mm.",
      "Cuece los tallarines en agua hirviendo con sal 3 minutos. Sirve con el tuco y el queso."],
  tp:["Deja secar los tallarines 15 minutos sobre un paño antes de cocerlos.",
      "El azúcar corrige la acidez del tomate."],
  v:"tallarines caseros con tuco"},
 en:{n:"Tallarines con Tuco (Homemade Noodles with Meat Sauce)", b:"Hand-made egg noodles with a slow-cooked beef tomato sauce. Nonna's Sunday lunch in Argentina.",
  st:["Make a well in the flour and salt, crack the eggs into it and knead 10 minutes. Rest 30 minutes covered.",
      "Brown the beef in the oil for 6 minutes. Add the onion, pepper and garlic and cook 8 minutes.",
      "Add the tomato, bay, oregano, sugar and salt. Cover and simmer 60 minutes on low.",
      "Roll the dough very thin, flour it, roll it up and cut 5 mm strips.",
      "Cook the noodles in boiling salted water for 3 minutes. Serve with the sauce and cheese."],
  tp:["Let the noodles dry 15 minutes on a cloth before cooking.",
      "The sugar balances the tomato's acidity."],
  v:"argentine homemade noodles tuco"}},

{id:"canelones-de-verdura", c:"Argentina", r:"latin-america", m:"main", t:90, s:6,
 i:[[150,"g","apflour","structure","harina de trigo (para los panqueques)","plain flour (for the crêpes)"],
    [2,"","egg","structure","huevos (para los panqueques)","eggs (for the crêpes)"],
    [350,"ml","milk","liquid","leche (para los panqueques)","milk (for the crêpes)"],
    [800,"g","veg","structure","acelga","chard","hervida y picada","blanched and chopped"],
    [250,"g","ricottacheese","enrich","ricota","ricotta"],
    [80,"g","parmesan","enrich","queso rallado","grated parmesan"],
    [1,"","egg","binder","huevo (para el relleno)","egg (for the filling)"],
    [1,"pinch","spice","aromatic","nuez moscada","nutmeg"],
    [40,"g","butter","fat","mantequilla","butter"],
    [40,"g","apflour","thicken","harina de trigo (para la salsa blanca)","plain flour (for the white sauce)"],
    [500,"ml","milk","liquid","leche (para la salsa blanca)","milk (for the white sauce)"],
    [400,"g","tomato","sauce","tomate triturado","crushed tomatoes"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Canelones de verdura", b:"Panqueques rellenos de acelga y ricota, con salsa blanca y tomate. Clásico de las fiestas familiares en Argentina.",
  st:["Bate la harina, los huevos y la leche de los panqueques. Haz 12 panqueques finos en una sartén untada.",
      "Escurre muy bien la acelga y mézclala con la ricota, la mitad del queso, el huevo, la nuez moscada y sal.",
      "Derrite la mantequilla, añade la harina y cocina 1 minuto. Añade la leche batiendo y cuece 8 minutos hasta espesar.",
      "Rellena y enrolla los panqueques. Ponlos en una fuente sobre el tomate.",
      "Cubre con la salsa blanca y el resto del queso. Hornea a 200 °C 20 minutos."],
  tp:["Exprime bien la acelga o el relleno quedará aguado.",
      "Se pueden armar el día anterior y hornear al momento."],
  v:"canelones de verdura argentinos"},
 en:{n:"Canelones de Verdura (Chard and Ricotta Cannelloni)", b:"Crêpes filled with chard and ricotta, with white sauce and tomato. A classic of Argentine family gatherings.",
  st:["Whisk the crêpe flour, eggs and milk. Make 12 thin crêpes in a greased pan.",
      "Squeeze the chard very dry and mix with the ricotta, half the cheese, the egg, nutmeg and salt.",
      "Melt the butter, add the flour and cook 1 minute. Whisk in the milk and cook 8 minutes until thick.",
      "Fill and roll the crêpes. Lay them in a dish over the tomato.",
      "Cover with the white sauce and the rest of the cheese. Bake at 200 °C for 20 minutes."],
  tp:["Squeeze the chard well or the filling will be watery.",
      "Assemble them the day before and bake when needed."],
  v:"argentine chard cannelloni"}},

{id:"pollo-al-verdeo", c:"Argentina", r:"latin-america", m:"main", t:40, s:4,
 i:[[4,"","chicken","protein","pechugas de pollo","chicken breasts"],
    [1,"tsp","salt","salt","sal","salt"],
    [30,"g","butter","fat","mantequilla","butter"],
    [1,"tbsp","oil","fat","aceite","oil"],
    [2,"bunch","scallion","aromatic","cebolla de verdeo","spring onions","picada","chopped"],
    [150,"ml","winewhite","liquid","vino blanco","white wine"],
    [250,"ml","heavycream","sauce","crema de leche","double cream"],
    [1,"pinch","pepper","aromatic","pimienta","pepper"]],
 es:{n:"Pollo al verdeo", b:"Pechugas en salsa de crema con mucha cebolla de verdeo y vino blanco. Plato de bodegón porteño.",
  st:["Sala el pollo y dóralo en la mantequilla con el aceite 5 minutos por lado. Sácalo.",
      "Sofríe el verdeo en la misma sartén 4 minutos.",
      "Añade el vino y deja reducir 3 minutos.",
      "Añade la crema y la pimienta, vuelve a poner el pollo y cuece 8 minutos a fuego bajo."],
  tp:["Guarda un poco de la parte verde del verdeo para decorar.",
      "Sírvelo con arroz blanco."],
  v:"pollo al verdeo"},
 en:{n:"Pollo al Verdeo (Chicken in Spring Onion Cream)", b:"Chicken breasts in a cream sauce with lots of spring onion and white wine. A Buenos Aires tavern dish.",
  st:["Salt the chicken and brown it in the butter and oil for 5 minutes per side. Remove.",
      "Cook the spring onion in the same pan for 4 minutes.",
      "Add the wine and reduce 3 minutes.",
      "Add the cream and pepper, return the chicken and simmer 8 minutes on low."],
  tp:["Keep some of the green tops to garnish.",
      "Serve with white rice."],
  v:"argentine chicken spring onion cream"}},

{id:"berenjenas-en-escabeche", c:"Argentina", r:"latin-america", m:"starter", t:60, s:8,
 i:[[1,"kg","eggplant","structure","berenjenas","aubergines","peladas en tiras","peeled, in strips"],
    [2,"tbsp","salt","salt","sal gruesa","coarse salt"],
    [500,"ml","whitevinegar","acid","vinagre blanco","white vinegar"],
    [500,"ml","water","liquid","agua","water"],
    [4,"clove","garlic","aromatic","ajo","garlic","laminado","sliced"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"],
    [1,"tsp","chilli","aromatic","ají molido","crushed chilli flakes"],
    [2,"leaf","herb","aromatic","laurel","bay leaves"],
    [300,"ml","oil","fat","aceite","oil"]],
 es:{n:"Berenjenas en escabeche", b:"Tiras de berenjena en vinagre y aceite con ajo, orégano y ají. La picada infaltable de las casas argentinas.",
  st:["Espolvorea las berenjenas con la sal y deja escurrir 2 horas. Enjuaga.",
      "Hierve el vinagre con el agua. Cuece la berenjena 5 minutos y escurre muy bien.",
      "Mezcla con el ajo, el orégano, el ají y el laurel.",
      "Pon en frascos limpios y cubre con el aceite.",
      "Refrigera 24 horas antes de comer."],
  tp:["Aprieta bien la berenjena al escurrir para que no agüe el aceite.",
      "Se conservan 2 semanas en la nevera cubiertas de aceite."],
  v:"berenjenas en escabeche"},
 en:{n:"Berenjenas en Escabeche (Pickled Aubergine)", b:"Aubergine strips in vinegar and oil with garlic, oregano and chilli. A must on every Argentine snack board.",
  st:["Sprinkle the aubergines with the salt and drain 2 hours. Rinse.",
      "Bring the vinegar and water to the boil. Cook the aubergine 5 minutes and drain very well.",
      "Mix with the garlic, oregano, chilli and bay.",
      "Pack into clean jars and cover with the oil.",
      "Chill 24 hours before eating."],
  tp:["Squeeze the aubergine hard when draining so the oil stays clear.",
      "They keep 2 weeks in the fridge covered in oil."],
  v:"argentine pickled eggplant"}},

{id:"lengua-a-la-vinagreta", c:"Argentina", r:"latin-america", m:"starter", t:180, s:8,
 i:[[1,"kg","beef","protein","lengua de res","beef tongue"],
    [0.5,"","onion","aromatic","cebolla (para la cocción)","onion (for cooking)"],
    [2,"leaf","herb","aromatic","laurel","bay leaves"],
    [2,"tsp","salt","salt","sal","salt"],
    [1,"","onion","aromatic","cebolla","onion","picada fina","finely chopped"],
    [1,"","bellpepper","aromatic","morrón rojo","red bell pepper","picado fino","finely chopped"],
    [2,"","egg","enrich","huevos duros","hard-boiled eggs","picados","chopped"],
    [1,"handful","herb","aromatic","perejil","parsley","picado","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado fino","finely chopped"],
    [100,"ml","oil","fat","aceite","oil"],
    [60,"ml","winevinegar","acid","vinagre de vino","wine vinegar"]],
 es:{n:"Lengua a la vinagreta", b:"Lengua de res tierna en rodajas, cubierta con vinagreta de morrón, huevo y perejil. Entrada de las fiestas argentinas.",
  st:["Cuece la lengua en agua con la cebolla, el laurel y la sal 2 horas y media, hasta que esté tierna.",
      "Pélala en caliente y deja enfriar. Córtala en rodajas finas.",
      "Mezcla la cebolla, el morrón, el huevo, el perejil, el ajo, el aceite y el vinagre.",
      "Cubre las rodajas con la vinagreta y refrigera 2 horas."],
  tp:["Pela la lengua en caliente: en frío la piel no sale.",
      "Mejor preparada el día anterior."],
  v:"lengua a la vinagreta"},
 en:{n:"Lengua a la Vinagreta (Beef Tongue Vinaigrette)", b:"Tender sliced beef tongue topped with a pepper, egg and parsley vinaigrette. A festive Argentine starter.",
  st:["Simmer the tongue in water with the onion, bay and salt for 2 and a half hours, until tender.",
      "Peel it while hot and let it cool. Slice thinly.",
      "Mix the onion, pepper, egg, parsley, garlic, oil and vinegar.",
      "Cover the slices with the vinaigrette and chill 2 hours."],
  tp:["Peel the tongue hot: cold, the skin won't come off.",
      "Best made the day before."],
  v:"argentine beef tongue vinaigrette"}},

{id:"mollejas-a-la-parrilla", c:"Argentina", r:"latin-america", m:"starter", t:60, s:4,
 i:[[600,"g","veal","protein","mollejas de ternera","veal sweetbreads"],
    [1,"tsp","salt","salt","sal gruesa","coarse salt"],
    [2,"","citrus","acid","limones","lemons"]],
 es:{n:"Mollejas a la parrilla", b:"Mollejas crujientes por fuera y tiernas por dentro, con limón. La achura favorita del asado argentino.",
  st:["Hierve las mollejas 5 minutos y enfríalas en agua con hielo.",
      "Retira la grasa y las membranas más gruesas.",
      "Ásalas a la parrilla a fuego medio 20 minutos, dándoles la vuelta, hasta que estén doradas y crujientes.",
      "Sala, corta en trozos y sirve con limón."],
  tp:["El hervor previo las mantiene firmes en la parrilla.",
      "También se hacen en una sartén de hierro bien caliente."],
  v:"mollejas a la parrilla"},
 en:{n:"Grilled Sweetbreads (Mollejas)", b:"Sweetbreads crisp outside and tender inside, with lemon. The favourite offal cut of an Argentine asado.",
  st:["Blanch the sweetbreads 5 minutes and cool them in iced water.",
      "Remove the fat and the thickest membranes.",
      "Grill over medium heat for 20 minutes, turning, until golden and crisp.",
      "Salt, cut into pieces and serve with lemon."],
  tp:["Blanching keeps them firm on the grill.",
      "A very hot cast-iron pan works too."],
  v:"argentine grilled sweetbreads"}},

{id:"caldillo-de-congrio", c:"Chile", r:"latin-america", m:"soup", t:60, s:4,
 i:[[800,"g","whitefish","protein","congrio en postas","conger eel steaks"],
    [1.5,"l","water","liquid","agua","water"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","en pluma","sliced"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"","veg","aromatic","zanahoria","carrot","en rodajas","sliced"],
    [2,"","tomato","aromatic","tomates","tomatoes","pelados y picados","peeled and chopped"],
    [1,"tsp","paprika","aromatic","pimentón","paprika"],
    [4,"","potato","structure","papas","potatoes","en rodajas","sliced"],
    [150,"ml","winewhite","liquid","vino blanco","white wine"],
    [100,"ml","cream","enrich","crema de leche","single cream"],
    [1,"handful","herb","garnish","cilantro","coriander","picado","chopped"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Caldillo de congrio", b:"Sopa chilena de congrio con papas, tomate y vino, a la que Pablo Neruda dedicó una oda.",
  st:["Sofríe la cebolla, el ajo y la zanahoria en el aceite 6 minutos. Añade el tomate y el pimentón y cocina 5 minutos.",
      "Añade el agua, las papas y la sal y cuece 15 minutos.",
      "Añade el vino y el congrio y cuece 10 minutos a fuego suave.",
      "Apaga, añade la crema y termina con el cilantro."],
  tp:["Si no hay congrio, usa merluza o corvina.",
      "No remuevas tras añadir el pescado para que no se deshaga."],
  v:"caldillo de congrio chileno"},
 en:{n:"Caldillo de Congrio (Chilean Conger Eel Soup)", b:"A Chilean conger eel soup with potatoes, tomato and wine, the subject of an ode by Pablo Neruda.",
  st:["Cook the onion, garlic and carrot in the oil for 6 minutes. Add the tomato and paprika and cook 5 minutes.",
      "Add the water, potatoes and salt and simmer 15 minutes.",
      "Add the wine and fish and cook 10 minutes on a gentle simmer.",
      "Turn off, stir in the cream and finish with the coriander."],
  tp:["No conger? Use hake or sea bass.",
      "Don't stir once the fish is in so it doesn't break up."],
  v:"chilean conger eel soup"}},

{id:"sopaipillas-pasadas", c:"Chile", r:"latin-america", m:"sweet", t:60, s:6,
 i:[[300,"g","apflour","structure","harina de trigo","plain flour"],
    [250,"g","veg","structure","zapallo cocido","cooked pumpkin","en puré","puréed"],
    [60,"g","butter","fat","mantequilla derretida","melted butter"],
    [1,"tsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [0.5,"tsp","salt","salt","sal","salt"],
    [750,"ml","oil","fat","aceite para freír","oil for frying"],
    [300,"g","brownsugar","sweet","chancaca","chancaca (unrefined cane sugar)"],
    [400,"ml","water","liquid","agua","water"],
    [1,"piece","spice","aromatic","rama de canela","cinnamon stick"],
    [1,"piece","citrus","aromatic","cáscara de naranja","orange peel"],
    [1,"tbsp","cornstarch","thicken","maicena","cornflour"]],
 es:{n:"Sopaipillas pasadas", b:"Sopaipillas de zapallo remojadas en almíbar de chancaca. Se comen en Chile los días de lluvia.",
  st:["Mezcla la harina, el zapallo, la mantequilla, el polvo de hornear y la sal. Amasa y deja reposar 15 minutos.",
      "Estira a 5 mm, corta círculos de 8 cm y pincha cada uno.",
      "Fríe a 175 °C 2 minutos por lado. Escurre.",
      "Hierve la chancaca con el agua, la canela y la cáscara 15 minutos. Espesa con la maicena disuelta en un poco de agua.",
      "Pasa las sopaipillas por el almíbar caliente 2 minutos y sirve."],
  tp:["Deben quedar blandas y empapadas, no crujientes.",
      "Sin pasar por el almíbar también se comen solas."],
  v:"sopaipillas pasadas chilenas"},
 en:{n:"Sopaipillas Pasadas (Pumpkin Fritters in Cane Syrup)", b:"Pumpkin fritters soaked in chancaca syrup. Eaten in Chile on rainy days.",
  st:["Mix the flour, pumpkin, butter, baking powder and salt. Knead and rest 15 minutes.",
      "Roll to 5 mm, cut 8 cm circles and prick each one.",
      "Fry at 175 °C for 2 minutes per side. Drain.",
      "Boil the chancaca with the water, cinnamon and peel for 15 minutes. Thicken with the cornflour mixed with a little water.",
      "Dip the sopaipillas in the hot syrup for 2 minutes and serve."],
  tp:["They should be soft and soaked, not crisp.",
      "Unsoaked, they're also eaten plain."],
  v:"chilean sopaipillas pasadas"}},

{id:"porotos-con-riendas", c:"Chile", r:"latin-america", m:"main", t:150, s:6,
 i:[[400,"g","legume","structure","porotos tórtola secos","dried cranberry beans"],
    [2.5,"l","water","liquid","agua","water"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"tsp","paprika","aromatic","pimentón","paprika"],
    [300,"g","veg","structure","zapallo","pumpkin","en cubos","cubed"],
    [150,"g","pasta","structure","tallarines","spaghetti","partidos","broken"],
    [2,"tsp","salt","salt","sal","salt"],
    [1,"tsp","herb","aromatic","orégano seco","dried oregano"]],
 es:{n:"Porotos con riendas", b:"Porotos guisados con zapallo y tallarines, las riendas. Almuerzo de invierno chileno.",
  st:["Remoja los porotos 12 horas y escúrrelos.",
      "Cuécelos en el agua 90 minutos, hasta que estén tiernos.",
      "Sofríe la cebolla y el ajo en el aceite 6 minutos. Añade el pimentón y el orégano.",
      "Añade el sofrito, el zapallo y la sal a los porotos y cuece 20 minutos.",
      "Añade los tallarines y cuece 10 minutos más, removiendo."],
  tp:["El zapallo se deshace y espesa el guiso.",
      "Si espesa demasiado, añade agua."],
  v:"porotos con riendas"},
 en:{n:"Porotos con Riendas (Chilean Beans with Noodles)", b:"Beans stewed with pumpkin and spaghetti, the 'reins'. A Chilean winter lunch.",
  st:["Soak the beans 12 hours and drain.",
      "Simmer them in the water for 90 minutes, until tender.",
      "Cook the onion and garlic in the oil for 6 minutes. Add the paprika and oregano.",
      "Add this, the pumpkin and salt to the beans and simmer 20 minutes.",
      "Add the spaghetti and cook 10 minutes more, stirring."],
  tp:["The pumpkin melts in and thickens the stew.",
      "Add water if it gets too thick."],
  v:"chilean beans with noodles"}},

{id:"cola-de-mono", c:"Chile", r:"latin-america", m:"drink", t:30, s:8,
 i:[[1,"l","milk","liquid","leche","milk"],
    [150,"g","sugar","sweet","azúcar","sugar"],
    [2,"tbsp","coffee","aromatic","café instantáneo","instant coffee"],
    [1,"piece","spice","aromatic","rama de canela","cinnamon stick"],
    [4,"piece","spice","aromatic","clavos de olor","cloves"],
    [1,"piece","citrus","aromatic","cáscara de naranja","orange peel"],
    [1,"tsp","vanilla","aromatic","esencia de vainilla","vanilla extract"],
    [250,"ml","spirit","liquid","aguardiente o pisco","aguardiente or pisco"]],
 es:{n:"Cola de mono", b:"Bebida navideña chilena de leche con café, especias y aguardiente, servida muy fría.",
  st:["Hierve la leche con el azúcar, la canela, el clavo y la cáscara 10 minutos.",
      "Apaga, añade el café y la vainilla y deja enfriar.",
      "Cuela y añade el aguardiente.",
      "Refrigera toda la noche y sirve muy frío."],
  tp:["Añade el alcohol en frío para que no se evapore.",
      "Contiene alcohol: para niños, hazla sin el aguardiente."],
  v:"cola de mono chilena"},
 en:{n:"Cola de Mono (Chilean Coffee Milk Punch)", b:"Chile's Christmas drink of milk with coffee, spices and aguardiente, served very cold.",
  st:["Boil the milk with the sugar, cinnamon, cloves and peel for 10 minutes.",
      "Turn off, add the coffee and vanilla and cool.",
      "Strain and add the aguardiente.",
      "Chill overnight and serve very cold."],
  tp:["Add the spirit when cold so it doesn't evaporate.",
      "Contains alcohol: for children, make it without the aguardiente."],
  v:"chilean cola de mono"}}
];
