module.exports = [
{id:"carlota-de-limon", c:"Mexico", r:"latin-america", m:"sweet", t:30, s:8,
 i:[[395,"g","condensedmilk","sweet","leche condensada","condensed milk"],
    [360,"ml","evaporatedmilk","liquid","leche evaporada","evaporated milk"],
    [6,"","citrus","acid","limones","limes","exprimidos","juiced"],
    [1,"","citrus","garnish","ralladura de limón","lime zest"],
    [300,"g","mariebiscuit","structure","galletas María","Marie biscuits"]],
 es:{n:"Carlota de limón", b:"Capas de galletas María y crema de limón que cuaja sola en la nevera. El postre sin horno de las fiestas mexicanas.",
  st:["Licúa la leche condensada con la evaporada 1 minuto.",
      "Añade el jugo de limón poco a poco con la licuadora en marcha: la crema espesará.",
      "En un molde de 20 x 20 cm alterna capas de galletas y crema, terminando con crema.",
      "Refrigera 4 horas como mínimo.",
      "Decora con la ralladura antes de servir."],
  tp:["Añade el limón despacio para que espese sin cortarse.",
      "Mejor si reposa toda la noche: las galletas se ablandan como un pastel."],
  v:"carlota de limón mexicana"},
 en:{n:"Carlota de Limón (Mexican Lime Icebox Cake)", b:"Layers of Marie biscuits and a lime cream that sets on its own in the fridge. Mexico's no-bake party dessert.",
  st:["Blend the condensed milk with the evaporated milk for 1 minute.",
      "Add the lime juice gradually with the blender running: the cream will thicken.",
      "In a 20 x 20 cm dish, alternate layers of biscuits and cream, ending with cream.",
      "Chill at least 4 hours.",
      "Top with the zest before serving."],
  tp:["Add the lime slowly so it thickens without splitting.",
      "Best left overnight: the biscuits soften like cake."],
  v:"mexican lime icebox cake"}},

{id:"gelatina-de-mosaico", c:"Mexico", r:"latin-america", m:"sweet", t:60, s:12,
 i:[[35,"g","gelatin","set","grenetina en polvo sin sabor","unflavoured powdered gelatine"],
    [250,"ml","fruit","liquid","jugo de fresa licuada y colada","strained strawberry purée"],
    [250,"ml","fruit","liquid","jugo de mango","mango juice"],
    [250,"ml","fruit","liquid","jugo de uva","grape juice"],
    [150,"g","sugar","sweet","azúcar","sugar"],
    [395,"g","condensedmilk","sweet","leche condensada","condensed milk"],
    [360,"ml","evaporatedmilk","liquid","leche evaporada","evaporated milk"],
    [250,"ml","milk","liquid","leche","milk"],
    [1,"tsp","vanilla","aromatic","esencia de vainilla","vanilla extract"],
    [250,"ml","water","liquid","agua","water"]],
 es:{n:"Gelatina de mosaico", b:"Cubitos de gelatina de colores dentro de una gelatina de leche. La gelatina de todos los cumpleaños mexicanos.",
  st:["Hidrata 20 g de grenetina en el agua 5 minutos y derrítela a fuego bajo.",
      "Calienta cada jugo con 50 g de azúcar y un tercio de la grenetina. Vierte cada uno en un recipiente y refrigera 2 horas.",
      "Corta las gelatinas de colores en cubos y ponlos en un molde de rosca.",
      "Hidrata el resto de la grenetina en 60 ml de la leche y disuélvela en la leche restante caliente. Mezcla con la condensada, la evaporada y la vainilla y deja entibiar.",
      "Vierte sobre los cubos y refrigera 4 horas. Desmolda."],
  tp:["La mezcla de leche debe estar tibia, no caliente, para no derretir los cubos.",
      "Pasa el molde por agua caliente unos segundos para desmoldar."],
  v:"gelatina de mosaico"},
 en:{n:"Gelatina de Mosaico (Mosaic Jelly)", b:"Cubes of coloured fruit jelly set inside a milk jelly. The jelly of every Mexican birthday.",
  st:["Soak 20 g of gelatine in the water for 5 minutes and melt over low heat.",
      "Heat each juice with 50 g of sugar and a third of the gelatine. Pour each into a container and chill 2 hours.",
      "Cut the coloured jellies into cubes and put them in a ring mould.",
      "Soak the rest of the gelatine in 60 ml of the milk and dissolve it in the remaining hot milk. Mix with the condensed milk, evaporated milk and vanilla and let it cool to lukewarm.",
      "Pour over the cubes and chill 4 hours. Turn out."],
  tp:["The milk mixture must be lukewarm, not hot, so the cubes don't melt.",
      "Dip the mould in hot water for a few seconds to turn it out."],
  v:"mexican mosaic gelatin"}},

{id:"mazapan-de-cacahuate", c:"Mexico", r:"latin-america", m:"sweet", t:20, s:16,
 i:[[250,"g","peanut","structure","cacahuates tostados sin sal","unsalted roasted peanuts"],
    [200,"g","icingsugar","sweet","azúcar glas","icing sugar"],
    [1,"pinch","salt","salt","sal","salt"]],
 es:{n:"Mazapán de cacahuate", b:"Discos de cacahuate molido con azúcar que se deshacen en la boca. El dulce de la tiendita mexicana, hecho en casa.",
  st:["Muele los cacahuates en un procesador 1 minuto, hasta que parezcan arena húmeda, sin llegar a crema.",
      "Añade el azúcar glas y la sal y procesa 30 segundos.",
      "Presiona porciones de la mezcla con fuerza en un cortador redondo de 4 cm.",
      "Desmolda con cuidado y deja reposar 1 hora para que se asienten."],
  tp:["No muelas de más o el cacahuate suelta aceite y se vuelve pasta.",
      "Presiona muy fuerte para que no se desmoronen."],
  v:"mazapán de cacahuate casero"},
 en:{n:"Mazapán de Cacahuate (Mexican Peanut Candy)", b:"Discs of ground peanut and sugar that melt in your mouth. The corner-shop Mexican candy, made at home.",
  st:["Grind the peanuts in a processor for 1 minute, until like damp sand but not butter.",
      "Add the icing sugar and salt and process 30 seconds.",
      "Press portions firmly into a 4 cm round cutter.",
      "Unmould carefully and rest 1 hour to firm up."],
  tp:["Don't over-grind or the peanuts release oil and turn to paste.",
      "Press very hard so they don't crumble."],
  v:"mexican peanut marzipan"}},

{id:"dulce-de-guayaba", c:"Colombia", r:"latin-america", m:"sweet", t:90, s:12,
 i:[[1,"kg","fruit","structure","guayabas maduras","ripe guavas"],
    [500,"ml","water","liquid","agua","water"],
    [600,"g","sugar","sweet","azúcar","sugar"],
    [2,"","citrus","acid","limones","limes","exprimidos","juiced"]],
 es:{n:"Bocadillo de guayaba casero", b:"Pasta firme de guayaba con azúcar, como el bocadillo veleño. Se come con queso en toda Colombia.",
  st:["Corta las guayabas en cuartos y cuécelas en el agua 20 minutos.",
      "Licúa y cuela para quitar las semillas.",
      "Cuece el puré con el azúcar y el limón 50 minutos a fuego medio-bajo, removiendo sin parar, hasta ver el fondo de la olla.",
      "Vierte en un molde forrado con papel, alisa y deja secar 24 horas.",
      "Corta en barras."],
  tp:["Usa una cuchara de palo larga: salpica mucho al espesar.",
      "Se conserva 1 mes envuelto en un lugar fresco."],
  v:"bocadillo de guayaba casero"},
 en:{n:"Homemade Guava Paste", b:"A firm guava and sugar paste, like Colombia's bocadillo veleño. Eaten with cheese all over Colombia.",
  st:["Quarter the guavas and simmer them in the water for 20 minutes.",
      "Blend and sieve out the seeds.",
      "Cook the purée with the sugar and lime for 50 minutes over medium-low heat, stirring constantly, until you can see the bottom of the pan.",
      "Pour into a lined tin, smooth and leave to dry 24 hours.",
      "Cut into bars."],
  tp:["Use a long wooden spoon: it spits as it thickens.",
      "It keeps 1 month wrapped in a cool place."],
  v:"homemade guava paste"}},

{id:"dulce-de-leche-cortada", c:"Venezuela", r:"latin-america", m:"sweet", t:90, s:8,
 i:[[2,"l","milk","liquid","leche entera","whole milk"],
    [4,"","citrus","acid","limones","limes","exprimidos","juiced"],
    [300,"g","brownsugar","sweet","papelón","papelón (unrefined cane sugar)","rallado","grated"],
    [250,"ml","water","liquid","agua","water"],
    [2,"piece","spice","aromatic","ramas de canela","cinnamon sticks"],
    [4,"piece","spice","aromatic","clavos de olor","cloves"]],
 es:{n:"Dulce de leche cortada", b:"Grumos de leche cortada con limón, cocidos en melado de papelón con canela y clavo. Dulce tradicional venezolano.",
  st:["Calienta la leche hasta que hierva, apaga y añade el limón. Deja reposar 10 minutos, hasta que se corte.",
      "Cuela con un paño y deja escurrir 30 minutos.",
      "Hierve el papelón con el agua, la canela y el clavo 10 minutos para hacer un melado.",
      "Añade los grumos de leche y cuece 30 minutos a fuego bajo, sin remover mucho, hasta que se doren y el melado espese.",
      "Sirve frío."],
  tp:["Mueve la olla en lugar de remover para que los grumos no se deshagan.",
      "Se conserva 1 semana en la nevera."],
  v:"dulce de leche cortada venezolano"},
 en:{n:"Dulce de Leche Cortada (Curdled Milk Sweet)", b:"Milk curds set with lime and simmered in cane-sugar syrup with cinnamon and clove. A traditional Venezuelan sweet.",
  st:["Heat the milk to the boil, turn off and add the lime. Rest 10 minutes, until it curdles.",
      "Strain through a cloth and drain 30 minutes.",
      "Boil the papelón with the water, cinnamon and cloves for 10 minutes into a syrup.",
      "Add the curds and simmer 30 minutes on low, stirring little, until golden and the syrup thickens.",
      "Serve cold."],
  tp:["Shake the pan rather than stirring so the curds stay whole.",
      "It keeps 1 week in the fridge."],
  v:"venezuelan curdled milk sweet"}},

{id:"torta-de-platano", c:"Venezuela", r:"latin-america", m:"sweet", t:70, s:8,
 i:[[4,"","plantain","structure","plátanos muy maduros","very ripe plantains"],
    [60,"g","butter","fat","mantequilla","butter"],
    [100,"g","sugar","sweet","azúcar","sugar"],
    [3,"","egg","binder","huevos","eggs"],
    [200,"g","queso","enrich","queso blanco duro","hard white cheese","rallado","grated"],
    [1,"tsp","spice","aromatic","canela molida","ground cinnamon"],
    [120,"ml","milk","liquid","leche","milk"]],
 es:{n:"Torta de plátano", b:"Pastel de plátano maduro con queso blanco y canela, dulce y salado a la vez. Merienda venezolana.",
  st:["Pela los plátanos, córtalos en rodajas y fríelos en la mantequilla 3 minutos por lado.",
      "Bate los huevos con el azúcar, la leche y la canela.",
      "En un molde de 22 cm engrasado, alterna capas de plátano y queso.",
      "Vierte la mezcla de huevo por encima.",
      "Hornea a 180 °C 40 minutos, hasta que esté dorada y cuajada."],
  tp:["Los plátanos deben tener la piel casi negra.",
      "Deja reposar 15 minutos antes de cortar."],
  v:"torta de plátano venezolana"},
 en:{n:"Torta de Plátano (Venezuelan Plantain Cake)", b:"A cake of ripe plantain with white cheese and cinnamon, sweet and salty at once. A Venezuelan afternoon treat.",
  st:["Peel and slice the plantains and fry them in the butter for 3 minutes per side.",
      "Whisk the eggs with the sugar, milk and cinnamon.",
      "In a greased 22 cm tin, layer plantain and cheese.",
      "Pour the egg mixture over.",
      "Bake at 180 °C for 40 minutes, until golden and set."],
  tp:["The plantain skins should be almost black.",
      "Rest 15 minutes before slicing."],
  v:"venezuelan plantain cake"}},

{id:"flan-de-queso", c:"Puerto Rico", r:"caribbean", m:"sweet", t:90, s:10,
 i:[[200,"g","sugar","caramel","azúcar (para el caramelo)","sugar (for the caramel)"],
    [225,"g","creamcheese","enrich","queso crema","cream cheese"],
    [395,"g","condensedmilk","sweet","leche condensada","condensed milk"],
    [360,"ml","evaporatedmilk","liquid","leche evaporada","evaporated milk"],
    [5,"","egg","set","huevos","eggs"],
    [1,"tsp","vanilla","aromatic","esencia de vainilla","vanilla extract"]],
 es:{n:"Flan de queso", b:"Flan denso y cremoso con queso crema. El flan de las fiestas en Puerto Rico y Cuba.",
  st:["Derrite el azúcar en un molde de flan hasta que tenga color ámbar y cubre el fondo. Deja enfriar.",
      "Licúa el queso crema, la leche condensada, la evaporada, los huevos y la vainilla.",
      "Vierte sobre el caramelo.",
      "Hornea a baño María a 175 °C 60 minutos, hasta que cuaje.",
      "Deja enfriar y refrigera 4 horas antes de desmoldar."],
  tp:["El queso crema debe estar a temperatura ambiente para que no queden grumos.",
      "Desmolda pasando un cuchillo por el borde."],
  v:"flan de queso boricua"},
 en:{n:"Flan de Queso (Cream Cheese Flan)", b:"A dense, creamy flan made with cream cheese. The party flan in Puerto Rico and Cuba.",
  st:["Melt the sugar in a flan mould until amber and coat the base. Cool.",
      "Blend the cream cheese, condensed milk, evaporated milk, eggs and vanilla.",
      "Pour over the caramel.",
      "Bake in a water bath at 175 °C for 60 minutes, until set.",
      "Cool and chill 4 hours before turning out."],
  tp:["Have the cream cheese at room temperature so there are no lumps.",
      "Run a knife around the edge to turn it out."],
  v:"puerto rican cream cheese flan"}},

{id:"bunuelos-de-viento", c:"Spain", r:"mediterranean", m:"sweet", t:40, s:30,
 i:[[250,"ml","water","liquid","agua","water"],
    [50,"g","butter","fat","mantequilla","butter"],
    [1,"pinch","salt","salt","sal","salt"],
    [1,"piece","citrus","aromatic","piel de limón","lemon peel"],
    [150,"g","apflour","structure","harina de trigo","plain flour"],
    [4,"","egg","structure","huevos","eggs"],
    [1,"l","oliveoil","fat","aceite de oliva suave para freír","light olive oil for frying"],
    [80,"g","sugar","garnish","azúcar","sugar"]],
 es:{n:"Buñuelos de viento", b:"Bolitas huecas de masa frita, ligeras como el aire. El dulce de Todos los Santos en España.",
  st:["Hierve el agua con la mantequilla, la sal y la piel de limón. Retira la piel.",
      "Añade la harina de golpe y remueve 2 minutos a fuego bajo, hasta que la masa se despegue.",
      "Deja entibiar y añade los huevos de uno en uno, batiendo bien.",
      "Fríe cucharaditas de masa a 170 °C 5 minutos: se inflarán y girarán solas.",
      "Escurre y reboza en el azúcar."],
  tp:["El aceite no debe estar muy caliente o se cierran antes de inflarse.",
      "Sírvelos recién hechos, aún crujientes."],
  v:"buñuelos de viento"},
 en:{n:"Buñuelos de Viento (Spanish Puff Fritters)", b:"Hollow fried dough puffs, light as air. Spain's All Saints' Day sweet.",
  st:["Boil the water with the butter, salt and lemon peel. Remove the peel.",
      "Tip in the flour all at once and stir 2 minutes on low, until the dough pulls away.",
      "Cool slightly and beat in the eggs one at a time.",
      "Fry teaspoons of dough at 170 °C for 5 minutes: they will puff and turn on their own.",
      "Drain and roll in the sugar."],
  tp:["Don't let the oil get too hot or they seal before they puff.",
      "Serve them fresh, while still crisp."],
  v:"spanish bunuelos de viento"}},

{id:"chocoflan", c:"Mexico", r:"latin-america", m:"sweet", t:120, s:12,
 i:[[150,"g","dulcedeleche","glaze","cajeta","cajeta (goat's milk caramel)"],
    [120,"g","butter","fat","mantequilla blanda","soft butter"],
    [200,"g","sugar","sweet","azúcar","sugar"],
    [1,"","egg","structure","huevo (para el pastel)","egg (for the cake)"],
    [200,"g","apflour","structure","harina de trigo","plain flour"],
    [40,"g","cocoa","aromatic","cacao en polvo","cocoa powder"],
    [1,"tsp","bakingsoda","aerate","bicarbonato de sodio","bicarbonate of soda"],
    [1,"tsp","bakingpowder","leaven","polvo de hornear","baking powder"],
    [240,"ml","milk","liquid","leche","milk"],
    [395,"g","condensedmilk","sweet","leche condensada","condensed milk"],
    [360,"ml","evaporatedmilk","liquid","leche evaporada","evaporated milk"],
    [90,"g","creamcheese","enrich","queso crema","cream cheese"],
    [4,"","egg","set","huevos (para el flan)","eggs (for the flan)"],
    [1,"tsp","vanilla","aromatic","esencia de vainilla","vanilla extract"]],
 es:{n:"Chocoflan (pastel imposible)", b:"Pastel de chocolate y flan que intercambian lugares en el horno. Lo llaman pastel imposible.",
  st:["Cubre el fondo de un molde de rosca engrasado con la cajeta.",
      "Bate la mantequilla con el azúcar, añade el huevo del pastel y luego la harina, el cacao, el bicarbonato y el polvo de hornear alternando con la leche. Vierte sobre la cajeta.",
      "Licúa la leche condensada, la evaporada, el queso crema, los huevos del flan y la vainilla. Viértelo con cuidado sobre la masa.",
      "Tapa con papel de aluminio y hornea a baño María a 180 °C 75 minutos.",
      "Deja enfriar y refrigera 4 horas antes de desmoldar."],
  tp:["Vierte el flan sobre el dorso de una cuchara para no mezclar las capas.",
      "Desmolda en frío: caliente se rompe."],
  v:"chocoflan pastel imposible"},
 en:{n:"Chocoflan (Impossible Cake)", b:"Chocolate cake and flan that swap places in the oven. That's why it's called the impossible cake.",
  st:["Coat the base of a greased bundt tin with the cajeta.",
      "Beat the butter with the sugar, add the cake egg, then the flour, cocoa, bicarbonate and baking powder alternating with the milk. Pour over the cajeta.",
      "Blend the condensed milk, evaporated milk, cream cheese, flan eggs and vanilla. Pour it gently over the batter.",
      "Cover with foil and bake in a water bath at 180 °C for 75 minutes.",
      "Cool and chill 4 hours before turning out."],
  tp:["Pour the flan over the back of a spoon so the layers don't mix.",
      "Turn it out cold: warm, it breaks."],
  v:"mexican chocoflan"}},

{id:"bolo-de-rolo", c:"Brazil", r:"latin-america", m:"sweet", t:90, s:12,
 i:[[250,"g","butter","fat","mantequilla blanda","soft butter"],
    [250,"g","sugar","sweet","azúcar","sugar"],
    [5,"","egg","structure","huevos","eggs"],
    [250,"g","apflour","structure","harina de trigo","plain flour"],
    [400,"g","guavapaste","spread","pasta de guayaba (goiabada)","guava paste"],
    [100,"ml","water","liquid","agua","water"],
    [2,"tbsp","icingsugar","garnish","azúcar glas","icing sugar"]],
 es:{n:"Bolo de rolo", b:"Brazo de gitano de capas finísimas enrolladas con guayaba. Patrimonio de Pernambuco, en Brasil.",
  st:["Derrite la goiabada con el agua a fuego bajo hasta tener una crema untable. Deja enfriar.",
      "Bate la mantequilla con el azúcar 5 minutos, añade los huevos de uno en uno y luego la harina.",
      "Extiende 4 cucharadas de masa muy fina en una bandeja de 30 x 40 cm con papel y hornea a 200 °C 5 minutos.",
      "Vuelca sobre un paño con azúcar, unta con guayaba y enrolla. Repite con cada capa, enrollándola alrededor del rollo anterior.",
      "Deja enfriar y espolvorea con azúcar glas."],
  tp:["Las capas deben ser casi transparentes: es la marca de un buen bolo de rolo.",
      "Trabaja con las capas calientes para que no se rompan."],
  v:"bolo de rolo pernambucano"},
 en:{n:"Bolo de Rolo (Brazilian Guava Roll Cake)", b:"A roll cake of paper-thin layers wrapped around guava paste. A heritage cake of Pernambuco, Brazil.",
  st:["Melt the guava paste with the water on low into a spreadable cream. Cool.",
      "Beat the butter with the sugar for 5 minutes, add the eggs one at a time, then the flour.",
      "Spread 4 tablespoons of batter very thin on a lined 30 x 40 cm tray and bake at 200 °C for 5 minutes.",
      "Turn onto a sugared cloth, spread with guava and roll. Repeat with each layer, rolling it around the previous roll.",
      "Cool and dust with icing sugar."],
  tp:["The layers should be almost see-through: the mark of a good bolo de rolo.",
      "Work with the layers warm so they don't crack."],
  v:"brazilian bolo de rolo"}}
];
