module.exports = [
{id:"cazon-guisado", c:"Venezuela", r:"latin-america", m:"main", t:50, s:4,
 i:[[700,"g","whitefish","protein","cazón (o pescado blanco firme)","dogfish or firm white fish"],
    [1.5,"l","water","liquid","agua","water"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"tsp","achiote","aromatic","onoto (achiote) molido","ground annatto"],
    [1,"","onion","aromatic","cebolla","onion","picada fina","finely chopped"],
    [4,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [6,"","bellpepper","aromatic","ajíes dulces","sweet ají peppers","picados","chopped"],
    [2,"","tomato","aromatic","tomates","tomatoes","picados","chopped"],
    [1,"","citrus","acid","limón","lime"],
    [1,"handful","herb","garnish","cilantro","coriander","picado","chopped"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Cazón guisado", b:"Pescado desmenuzado y guisado con ají dulce, tomate y onoto. Relleno de empanadas margariteñas y plato de playa.",
  st:["Hierve el cazón en el agua con 1 cucharadita de sal 10 minutos. Escúrrelo, quítale la piel y desmenúzalo.",
      "Sofríe la cebolla, el ajo y el ají dulce en el aceite con el onoto 8 minutos.",
      "Añade el tomate y cocina 5 minutos. Incorpora el pescado, el resto de la sal y el jugo de limón y cocina 8 minutos, hasta que quede seco.",
      "Termina con el cilantro."],
  tp:["Debe quedar jugoso pero sin líquido si lo usas para rellenar.",
      "Sírvelo con arroz blanco."],
  v:"cazón guisado margariteño"},
 en:{n:"Cazón Guisado (Venezuelan Shredded Fish)", b:"Shredded fish stewed with sweet ají peppers, tomato and annatto. A Margarita empanada filling and beach meal.",
  st:["Boil the fish in the water with 1 teaspoon of salt for 10 minutes. Drain, remove the skin and flake it.",
      "Cook the onion, garlic and ají peppers in the oil with the annatto for 8 minutes.",
      "Add the tomato and cook 5 minutes. Stir in the fish, remaining salt and lime juice and cook 8 minutes, until dry.",
      "Finish with the coriander."],
  tp:["For fillings it should be moist but with no liquid.",
      "Serve with white rice."],
  v:"venezuelan stewed dogfish"}},

{id:"pastel-de-chucho", c:"Venezuela", r:"latin-america", m:"main", t:90, s:6,
 i:[[5,"","plantain","structure","plátanos bien maduros","very ripe plantains","en tajadas largas","in long slices"],
    [250,"ml","oil","fat","aceite","oil","para freír","for frying"],
    [700,"g","whitefish","protein","chucho (raya) o pescado blanco","ray or white fish"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [4,"","bellpepper","aromatic","ajíes dulces","sweet ají peppers","picados","chopped"],
    [2,"","tomato","aromatic","tomates","tomatoes","picados","chopped"],
    [1,"tsp","achiote","aromatic","onoto (achiote) molido","ground annatto"],
    [200,"g","queso","enrich","queso blanco duro rallado","grated hard white cheese"],
    [3,"","egg","binder","huevos","eggs","batidos","beaten"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Pastel de chucho", b:"Capas de tajadas de plátano maduro, pescado guisado y queso, horneadas. Plato de Semana Santa en Margarita.",
  st:["Fríe las tajadas en el aceite hasta dorar y escúrrelas.",
      "Hierve el pescado 10 minutos en agua con 1 cucharadita de sal y desmenúzalo.",
      "Sofríe la cebolla, el ajo, el ají dulce y el onoto en 2 cucharadas del aceite 8 minutos. Añade el tomate, el pescado y el resto de la sal y cocina 8 minutos.",
      "Calienta el horno a 180 °C. En una fuente, alterna capas de plátano, pescado y queso, terminando con plátano y queso.",
      "Vierte los huevos por encima y hornea 30 minutos."],
  tp:["Deja reposar 10 minutos antes de cortar.",
      "Los plátanos deben tener la piel casi negra."],
  v:"pastel de chucho margariteño"},
 en:{n:"Pastel de Chucho (Plantain and Fish Bake)", b:"Layers of ripe plantain, stewed fish and cheese, baked. A Holy Week dish from Margarita Island.",
  st:["Fry the plantain slices in the oil until golden and drain.",
      "Boil the fish for 10 minutes in water with 1 teaspoon of salt and flake it.",
      "Cook the onion, garlic, ají peppers and annatto in 2 tablespoons of the oil for 8 minutes. Add the tomato, fish and remaining salt and cook 8 minutes.",
      "Heat the oven to 180 °C. In a dish, layer plantain, fish and cheese, ending with plantain and cheese.",
      "Pour the eggs over and bake 30 minutes."],
  tp:["Rest 10 minutes before cutting.",
      "The plantain skins should be almost black."],
  v:"venezuelan ray pie"}},

{id:"polvorosas", c:"Venezuela", r:"latin-america", m:"cookie", t:40, s:24,
 i:[[300,"g","apflour","structure","harina de trigo","plain flour"],
    [150,"g","sugar","sweet","azúcar","sugar"],
    [180,"g","shortening","fat","grasa vegetal","vegetable shortening"],
    [0.5,"tsp","spice","aromatic","canela molida","ground cinnamon"],
    [1,"pinch","salt","salt","sal","salt"]],
 es:{n:"Polvorosas", b:"Galletas que se deshacen en la boca, hechas solo con harina, azúcar y grasa. Se venden en las panaderías de Venezuela.",
  st:["Calienta el horno a 170 °C.",
      "Mezcla la harina, el azúcar, la canela y la sal. Incorpora la grasa con las manos hasta formar una masa arenosa que se compacte.",
      "Forma bolitas de 3 cm, aplánalas un poco y colócalas en una bandeja.",
      "Hornea 15 minutos, sin que doren. Deja enfriar en la bandeja porque son frágiles en caliente."],
  tp:["Tostar la harina 5 minutos antes les da más sabor.",
      "Se guardan en lata hasta 2 semanas."],
  v:"polvorosas venezolanas"},
 en:{n:"Polvorosas (Venezuelan Crumble Cookies)", b:"Cookies that melt in the mouth, made with just flour, sugar and shortening. Sold in every Venezuelan bakery.",
  st:["Heat the oven to 170 °C.",
      "Mix the flour, sugar, cinnamon and salt. Work in the shortening by hand until sandy and it holds together.",
      "Roll 3 cm balls, flatten slightly and set on a tray.",
      "Bake 15 minutes without browning. Cool on the tray: they're fragile when hot."],
  tp:["Toasting the flour for 5 minutes first adds flavour.",
      "They keep in a tin for up to 2 weeks."],
  v:"venezuelan polvorosas"}},

{id:"catalinas", c:"Venezuela", r:"latin-america", m:"cookie", t:50, s:16,
 i:[[300,"g","brownsugar","sweet","papelón rallado (panela)","grated panela"],
    [150,"ml","water","liquid","agua","water"],
    [1,"tsp","spice","aromatic","clavo, canela y anís molidos","ground clove, cinnamon and aniseed"],
    [450,"g","apflour","structure","harina de trigo","plain flour"],
    [1,"tsp","bakingsoda","leaven","bicarbonato de sodio","baking soda"],
    [1,"pinch","salt","salt","sal","salt"]],
 es:{n:"Catalinas", b:"Galletas oscuras y blanditas de papelón y especias. Merienda de toda la vida.",
  st:["Disuelve el papelón en el agua con las especias a fuego bajo 8 minutos, hasta formar un melado. Deja entibiar.",
      "Mezcla la harina, el bicarbonato y la sal y añade el melado. Amasa hasta obtener una masa blanda.",
      "Calienta el horno a 180 °C. Estira a 1 cm y corta círculos de 8 cm.",
      "Hornea en bandeja enharinada 12 minutos."],
  tp:["Se ponen más blandas al día siguiente.",
      "Guárdalas en un recipiente cerrado."],
  v:"catalinas de papelón"},
 en:{n:"Catalinas (Venezuelan Panela Spice Cookies)", b:"Dark, soft cookies made with panela and spices. A lifelong afternoon snack.",
  st:["Dissolve the panela in the water with the spices over low heat for 8 minutes to make a syrup. Let it cool slightly.",
      "Mix the flour, baking soda and salt and add the syrup. Knead to a soft dough.",
      "Heat the oven to 180 °C. Roll to 1 cm and cut 8 cm rounds.",
      "Bake on a floured tray for 12 minutes."],
  tp:["They get softer the next day.",
      "Store in an airtight container."],
  v:"venezuelan catalinas"}},

{id:"besitos-de-coco", c:"Venezuela", r:"latin-america", m:"cookie", t:45, s:20,
 i:[[250,"g","desiccatedcoconut","structure","coco rallado seco","desiccated coconut"],
    [200,"g","brownsugar","sweet","papelón rallado (panela)","grated panela"],
    [120,"g","apflour","structure","harina de trigo","plain flour"],
    [60,"g","butter","fat","mantequilla","butter","derretida","melted"],
    [2,"","egg","binder","huevos","eggs"],
    [1,"tsp","spice","aromatic","jengibre y canela molidos","ground ginger and cinnamon"],
    [1,"pinch","salt","salt","sal","salt"]],
 es:{n:"Besitos de coco", b:"Bocaditos dorados de coco y papelón con un toque de jengibre. Dulce típico de las costas venezolanas.",
  st:["Calienta el horno a 180 °C.",
      "Mezcla todos los ingredientes hasta formar una masa pegajosa.",
      "Forma montoncitos de una cucharada sobre una bandeja con papel.",
      "Hornea 20 minutos, hasta que estén dorados por fuera."],
  tp:["Si la masa está muy suelta, refrigérala 15 minutos.",
      "Se conservan 1 semana en lata."],
  v:"besitos de coco venezolanos"},
 en:{n:"Besitos de Coco (Coconut Panela Kisses)", b:"Golden bites of coconut and panela with a touch of ginger. A sweet from Venezuela's coast.",
  st:["Heat the oven to 180 °C.",
      "Mix all the ingredients to a sticky dough.",
      "Drop tablespoon mounds onto a lined tray.",
      "Bake 20 minutes, until golden outside."],
  tp:["If the dough is too loose, chill it for 15 minutes.",
      "They keep 1 week in a tin."],
  v:"venezuelan coconut kisses"}},

{id:"cuajado-de-atun", c:"Venezuela", r:"latin-america", m:"main", t:60, s:6,
 i:[[3,"","plantain","structure","plátanos maduros","ripe plantains","en cubos","diced"],
    [4,"tbsp","oil","fat","aceite","oil"],
    [340,"g","tuna","protein","atún en lata","canned tuna","escurrido","drained"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [4,"","bellpepper","aromatic","ajíes dulces","sweet ají peppers","picados","chopped"],
    [1,"","tomato","aromatic","tomate","tomato","picado","chopped"],
    [6,"","egg","structure","huevos","eggs"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Cuajado de atún", b:"Tortilla gruesa de huevo con plátano maduro y atún guisado, cuajada al horno. Clásico de Semana Santa.",
  st:["Fríe el plátano en 2 cucharadas del aceite hasta dorar.",
      "Sofríe la cebolla, el ajo y el ají dulce en el resto del aceite 6 minutos, añade el tomate y el atún y cocina 5 minutos.",
      "Calienta el horno a 180 °C. Bate los huevos con la sal y mezcla con el plátano y el atún.",
      "Vierte en una fuente engrasada y hornea 25 minutos, hasta que cuaje."],
  tp:["Separar las claras y batirlas a punto de nieve lo hace más esponjoso.",
      "Se come tibio o frío."],
  v:"cuajado venezolano"},
 en:{n:"Cuajado de Atún (Plantain and Tuna Bake)", b:"A thick baked egg dish with ripe plantain and stewed tuna. A Holy Week classic.",
  st:["Fry the plantain in 2 tablespoons of the oil until golden.",
      "Cook the onion, garlic and ají peppers in the rest of the oil for 6 minutes, add the tomato and tuna and cook 5 minutes.",
      "Heat the oven to 180 °C. Beat the eggs with the salt and mix with the plantain and tuna.",
      "Pour into an oiled dish and bake 25 minutes, until set."],
  tp:["Whisking the whites separately to stiff peaks makes it fluffier.",
      "Eat it warm or cold."],
  v:"venezuelan cuajado"}},

{id:"fosforera", c:"Venezuela", r:"latin-america", m:"soup", t:60, s:6,
 i:[[500,"g","whitefish","protein","pescado blanco en trozos","white fish in chunks"],
    [300,"g","shrimp","protein","camarones","prawns"],
    [500,"g","clam","protein","almejas (chipichipi)","small clams","lavadas","scrubbed"],
    [250,"g","squid","protein","calamares","squid","en aros","in rings"],
    [2,"l","water","liquid","agua","water"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [4,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [6,"","bellpepper","aromatic","ajíes dulces","sweet ají peppers","picados","chopped"],
    [2,"","tomato","aromatic","tomates","tomatoes","picados","chopped"],
    [1,"","citrus","acid","limón","lime"],
    [1,"handful","herb","garnish","cilantro","coriander","picado","chopped"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Fosforera", b:"Sopa de mariscos y pescado con ají dulce, típica de la isla de Margarita. Famosa por reanimar después de una fiesta.",
  st:["Sofríe la cebolla, el ajo, el ají dulce y el tomate en el aceite 8 minutos.",
      "Añade el agua y la sal y hierve 15 minutos.",
      "Añade el pescado y el calamar y cuece 6 minutos. Añade las almejas y los camarones y cuece 4 minutos, hasta que se abran las almejas.",
      "Termina con el jugo de limón y el cilantro. Desecha las almejas que no se abran."],
  tp:["Lava las almejas en agua fría con sal para que suelten la arena.",
      "No la hiervas fuerte después de añadir los mariscos."],
  v:"fosforera margariteña"},
 en:{n:"Fosforera (Margarita Seafood Soup)", b:"A soup of shellfish and fish with sweet ají peppers from Margarita Island. Famous as a hangover cure.",
  st:["Cook the onion, garlic, ají peppers and tomato in the oil for 8 minutes.",
      "Add the water and salt and boil 15 minutes.",
      "Add the fish and squid and simmer 6 minutes. Add the clams and prawns and simmer 4 minutes, until the clams open.",
      "Finish with the lime juice and coriander. Discard any clams that stay shut."],
  tp:["Soak the clams in cold salted water so they release their sand.",
      "Don't boil hard once the seafood is in."],
  v:"venezuelan fosforera"}},

{id:"mojito-en-coco", c:"Venezuela", r:"latin-america", m:"main", t:40, s:4,
 i:[[600,"g","whitefish","protein","pescado blanco","white fish","desmenuzado crudo","raw, in small pieces"],
    [400,"ml","coconutmilk","liquid","leche de coco","coconut milk"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [4,"","bellpepper","aromatic","ajíes dulces","sweet ají peppers","picados","chopped"],
    [1,"","tomato","aromatic","tomate","tomato","picado","chopped"],
    [1,"","citrus","acid","limón","lime"],
    [1,"handful","herb","garnish","cilantro","coriander","picado","chopped"],
    [1.5,"tsp","salt","salt","sal","salt"]],
 es:{n:"Mojito en coco", b:"Pescado picado guisado en leche de coco con ají dulce. Plato de la costa oriental venezolana.",
  st:["Sazona el pescado con el jugo de limón y media cucharadita de sal.",
      "Sofríe la cebolla, el ajo y el ají dulce en el aceite 6 minutos. Añade el tomate y cocina 4 minutos.",
      "Añade la leche de coco y el resto de la sal y cuece 5 minutos.",
      "Añade el pescado y cocina 8 minutos, removiendo con cuidado, hasta que la salsa espese. Termina con el cilantro."],
  tp:["Sírvelo con arroz blanco.",
      "También sirve de relleno."],
  v:"mojito de pescado en coco"},
 en:{n:"Mojito en Coco (Venezuelan Fish in Coconut)", b:"Chopped fish stewed in coconut milk with sweet ají peppers. A dish from Venezuela's eastern coast.",
  st:["Season the fish with the lime juice and half a teaspoon of salt.",
      "Cook the onion, garlic and ají peppers in the oil for 6 minutes. Add the tomato and cook 4 minutes.",
      "Add the coconut milk and remaining salt and simmer 5 minutes.",
      "Add the fish and cook 8 minutes, stirring gently, until the sauce thickens. Finish with the coriander."],
  tp:["Serve with white rice.",
      "It's also used as a filling."],
  v:"venezuelan coconut fish"}}
];
