module.exports = [
{id:"pabellon-criollo", c:"Venezuela", r:"latin-america", m:"main", t:180, s:6,
 i:[[1,"kg","beef","protein","falda de res","beef flank"],
    [2,"l","water","liquid","agua","water"],
    [2.5,"tsp","salt","salt","sal","salt"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [2,"","onion","aromatic","cebollas","onions","picadas","chopped"],
    [2,"","bellpepper","aromatic","pimentones rojos","red bell peppers","picados","chopped"],
    [6,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [3,"","tomato","aromatic","tomates","tomatoes","picados","chopped"],
    [1,"tsp","spice","aromatic","comino molido","ground cumin"],
    [500,"g","legume","protein","caraotas negras (frijoles negros)","black beans","remojadas toda la noche","soaked overnight"],
    [300,"g","rice","structure","arroz blanco","white rice"],
    [3,"","plantain","sweet","plátanos maduros","ripe plantains","en tajadas","sliced lengthwise"]],
 es:{n:"Pabellón criollo", b:"El plato nacional de Venezuela: carne mechada, caraotas negras, arroz blanco y tajadas de plátano maduro.",
  st:["Cuece las caraotas escurridas en agua nueva 90 minutos, hasta que estén blandas. Deja 250 ml de su líquido.",
      "Cuece la carne con el agua y 1 cucharadita de sal 90 minutos, hasta que esté tierna. Deja enfriar y desmecha en hebras finas.",
      "Sofríe la cebolla, el pimentón y el ajo en 2 cucharadas de aceite 10 minutos. Divide en 2.",
      "A una mitad añade el tomate, el comino y la carne con 250 ml del líquido de la carne. Cuece 15 minutos hasta que se seque un poco.",
      "Añade la otra mitad del sofrito a las caraotas con 1 cucharadita de sal y cuece 20 minutos, hasta que espesen.",
      "Cuece el arroz con la sal restante. Fríe las tajadas de plátano en el resto del aceite hasta que estén doradas.",
      "Sirve todo junto en el plato: arroz, carne, caraotas y tajadas."],
  tp:["Desmecha la carne tibia: fría cuesta más y caliente quema.",
      "Las caraotas saben mejor hechas el día antes."],
  v:"pabellon criollo receta"},
 en:{n:"Pabellón Criollo", b:"Venezuela's national dish: shredded beef, black beans, white rice and fried sweet plantain.",
  st:["Cook the drained beans in fresh water for 90 minutes, until soft. Keep 250 ml of their liquid.",
      "Simmer the beef with the water and 1 teaspoon of salt for 90 minutes, until tender. Cool and shred into fine strands.",
      "Cook the onion, bell pepper and garlic in 2 tablespoons of oil for 10 minutes. Divide in 2.",
      "To one half add the tomato, cumin and beef with 250 ml of the beef liquid. Cook 15 minutes until slightly dry.",
      "Add the other half of the sofrito to the beans with 1 teaspoon of salt and cook 20 minutes, until thick.",
      "Cook the rice with the remaining salt. Fry the plantain slices in the rest of the oil until golden.",
      "Serve everything together on the plate: rice, beef, beans and plantain."],
  tp:["Shred the beef while warm: cold it's harder and hot it burns.",
      "The beans taste better made the day before."],
  v:"pabellon criollo recipe"}},

{id:"cachapas", c:"Venezuela", r:"latin-america", m:"breakfast", t:30, s:4,
 i:[[600,"g","corn","structure","granos de maíz tierno","sweet corn kernels","frescos o congelados","fresh or frozen"],
    [60,"g","cornmeal","structure","harina de maíz precocida","precooked cornmeal (masarepa)"],
    [2,"tbsp","sugar","sweet","azúcar","sugar"],
    [0.5,"tsp","salt","salt","sal","salt"],
    [60,"ml","milk","liquid","leche","milk"],
    [30,"g","butter","fat","mantequilla","butter","y más para servir","plus more to serve"],
    [300,"g","queso","protein","queso de mano o mozzarella fresca","queso de mano or fresh mozzarella","en tajadas","sliced"]],
 es:{n:"Cachapas", b:"Panqueques gruesos de maíz tierno, dulces y un poco rústicos, doblados sobre queso de mano con mantequilla.",
  st:["Licúa el maíz con la leche hasta que quede un puré con algo de textura.",
      "Mezcla con la harina, el azúcar y la sal. Reposa 10 minutos.",
      "Calienta un sartén o budare a fuego medio con un poco de mantequilla.",
      "Vierte un cucharón de mezcla y extiende a 15 centímetros. Cuece 4 minutos, hasta que los bordes se sequen, voltea y cuece 3 minutos más.",
      "Unta con mantequilla, pon el queso en la mitad y dobla."],
  tp:["Si se rompen al voltear, añade 1 cucharada más de harina de maíz precocida.",
      "El queso de mano es suave y salado; la mozzarella fresca es lo más parecido."],
  v:"cachapas receta"},
 en:{n:"Cachapas (Sweet Corn Pancakes)", b:"Thick, sweet, slightly rustic fresh corn pancakes folded over soft cheese with butter.",
  st:["Blend the corn with the milk into a purée with some texture.",
      "Mix with the cornmeal, sugar and salt. Rest 10 minutes.",
      "Heat a pan or griddle over medium heat with a little butter.",
      "Pour in a ladle of batter and spread to 15 centimetres. Cook 4 minutes, until the edges dry, flip and cook 3 minutes more.",
      "Butter it, put the cheese on one half and fold."],
  tp:["If they tear when flipped, add 1 more tablespoon of cornmeal.",
      "Queso de mano is soft and salty; fresh mozzarella is the closest match."],
  v:"cachapas recipe"}},

{id:"hallacas", c:"Venezuela", r:"latin-america", m:"main", t:360, s:20,
 i:[[500,"g","pork","protein","cerdo","pork","en cubos pequeños","in small cubes"],
    [500,"g","beef","protein","res","beef","en cubos pequeños","in small cubes"],
    [500,"g","chicken","protein","pollo sin hueso","boneless chicken","en cubos pequeños","in small cubes"],
    [3,"","onion","aromatic","cebollas","onions","picadas","chopped"],
    [2,"","bellpepper","aromatic","pimentones rojos","red bell peppers","picados","chopped"],
    [10,"","bellpepper","aromatic","ajíes dulces","sweet ají peppers","picados","chopped"],
    [8,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [6,"","scallion","aromatic","tallos de cebollín","green onion stalks","picados","chopped"],
    [3,"","tomato","aromatic","tomates","tomatoes","picados","chopped"],
    [250,"ml","winered","liquid","vino tinto","red wine"],
    [100,"g","jaggery","sweet","papelón rallado","grated papelón (unrefined cane sugar)"],
    [4,"tsp","salt","salt","sal","salt"],
    [1,"kg","cornmeal","structure","harina de maíz precocida","precooked cornmeal (masarepa)"],
    [1.2,"l","stock","liquid","caldo de pollo tibio","warm chicken stock"],
    [200,"ml","oil","fat","aceite coloreado con achiote","oil coloured with annatto"],
    [2,"tbsp","achiote","aromatic","semillas de onoto (achiote)","annatto seeds"],
    [100,"g","olives","garnish","aceitunas verdes sin hueso","pitted green olives"],
    [100,"g","driedfruit","garnish","pasas","raisins"],
    [2,"tbsp","capers","garnish","alcaparras","capers"],
    [1,"","bellpepper","garnish","pimentón rojo","red bell pepper","en tiras","in strips"],
    [20,"leaf","veg","serve","hojas de plátano","banana leaves","limpias, en cuadros de 30 cm","cleaned, in 30 cm squares"]],
 es:{n:"Hallacas", b:"El plato de Navidad venezolano: masa de maíz con onoto rellena de un guiso de tres carnes con vino y papelón, adornada con aceitunas, pasas y alcaparras, envuelta en hoja de plátano.",
  st:["Calienta el aceite con las semillas de onoto 3 minutos a fuego bajo hasta que se tiña de rojo. Cuela.",
      "Sofríe las cebollas, los pimentones, los ajíes, el ajo y el cebollín en 4 cucharadas del aceite rojo 10 minutos.",
      "Añade las tres carnes y dóralas 10 minutos. Añade el tomate, el vino, el papelón y 2 cucharaditas de sal. Cuece tapado 60 minutos, hasta que esté espeso. Enfría toda la noche.",
      "Amasa la harina con el caldo tibio, el resto de la sal y 120 ml del aceite rojo hasta que esté suave y no se pegue.",
      "Unta una hoja con aceite rojo. Extiende una bola de masa en una capa delgada de 20 centímetros.",
      "Pon 2 cucharadas de guiso en el centro con 1 aceituna, unas pasas, alcaparras y 1 tira de pimentón.",
      "Dobla la hoja para cerrar la masa sobre el relleno como un sobre, envuelve en otra hoja y amarra con pabilo en cruz.",
      "Hierve las hallacas en una olla grande de agua con sal 60 minutos. Escurre y sirve, o enfría y congela."],
  tp:["Es trabajo de familia: una persona extiende, otra rellena y otra amarra.",
      "Congeladas duran 3 meses; se hierven 30 minutos sin descongelar."],
  v:"hallacas venezolanas receta"},
 en:{n:"Hallacas (Venezuelan Christmas Tamales)", b:"Venezuela's Christmas dish: annatto corn dough filled with a three-meat stew with wine and papelón, topped with olives, raisins and capers, wrapped in banana leaves.",
  st:["Heat the oil with the annatto seeds for 3 minutes on low until it turns red. Strain.",
      "Cook the onions, bell peppers, ají peppers, garlic and green onion in 4 tablespoons of the red oil for 10 minutes.",
      "Add the three meats and brown 10 minutes. Add the tomato, wine, papelón and 2 teaspoons of salt. Cook covered 60 minutes, until thick. Chill overnight.",
      "Knead the cornmeal with the warm stock, the rest of the salt and 120 ml of the red oil until soft and not sticky.",
      "Brush a leaf with red oil. Spread a ball of dough into a thin 20 centimetre layer.",
      "Put 2 tablespoons of stew in the centre with 1 olive, a few raisins, capers and 1 strip of bell pepper.",
      "Fold the leaf to close the dough over the filling like an envelope, wrap in another leaf and tie with string in a cross.",
      "Boil the hallacas in a large pot of salted water for 60 minutes. Drain and serve, or cool and freeze."],
  tp:["It's a family job: one person spreads, one fills and one ties.",
      "Frozen they keep 3 months; boil 30 minutes from frozen."],
  v:"hallacas recipe"}},

{id:"tequenos", c:"Venezuela", r:"latin-america", m:"snack", t:60, s:8,
 i:[[300,"g","apflour","structure","harina de trigo","all-purpose flour"],
    [60,"g","butter","fat","mantequilla","butter","fría, en cubos","cold, cubed"],
    [1,"","egg","binder","huevo","egg"],
    [1,"tbsp","sugar","sweet","azúcar","sugar"],
    [0.5,"tsp","salt","salt","sal","salt"],
    [80,"ml","water","liquid","agua fría","cold water"],
    [400,"g","queso","protein","queso blanco duro o halloumi","firm white cheese or halloumi","en bastones de 1 cm","in 1 cm sticks"],
    [1,"l","oil","fat","aceite","oil","para freír","for frying"]],
 es:{n:"Tequeños", b:"Bastones de queso blanco envueltos en espiral con masa y fritos. El pasapalo de toda fiesta venezolana.",
  st:["Mezcla la harina, el azúcar y la sal. Frota la mantequilla hasta que parezca arena.",
      "Añade el huevo y el agua y amasa 5 minutos, hasta que esté lisa. Tapa y refrigera 30 minutos.",
      "Estira la masa muy delgada, de 2 milímetros, y corta tiras de 1 centímetro de ancho.",
      "Enrolla cada tira en espiral alrededor de un bastón de queso, solapando un poco y cubriendo las puntas.",
      "Fríe en aceite a 180 °C 3 minutos, hasta que estén dorados. Escurre y sirve calientes."],
  tp:["Cubre bien las puntas o el queso se sale al freír.",
      "Crudos se congelan en una capa y se fríen sin descongelar."],
  v:"tequeños venezolanos receta"},
 en:{n:"Tequeños (Cheese Sticks)", b:"Sticks of white cheese wrapped in a spiral of dough and fried. The party snack of every Venezuelan celebration.",
  st:["Mix the flour, sugar and salt. Rub in the butter until it looks like sand.",
      "Add the egg and water and knead 5 minutes, until smooth. Cover and chill 30 minutes.",
      "Roll the dough very thin, 2 millimetres, and cut strips 1 centimetre wide.",
      "Wind each strip in a spiral around a cheese stick, overlapping slightly and covering the ends.",
      "Fry in oil at 180 °C for 3 minutes, until golden. Drain and serve hot."],
  tp:["Cover the ends well or the cheese leaks out in the oil.",
      "Raw, they freeze in a single layer and fry from frozen."],
  v:"tequeños recipe"}},

{id:"asado-negro", c:"Venezuela", r:"latin-america", m:"main", t:180, s:6,
 i:[[1.5,"kg","beef","protein","muchacho redondo de res","beef eye of round","en una pieza","in one piece"],
    [4,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [2,"tsp","salt","salt","sal","salt"],
    [1,"tsp","pepper","aromatic","pimienta negra","black pepper"],
    [2,"tbsp","worcestershire","umami","salsa inglesa (Worcestershire)","Worcestershire sauce"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [150,"g","jaggery","caramel","papelón rallado","grated papelón (unrefined cane sugar)"],
    [2,"","onion","aromatic","cebollas","onions","picadas","chopped"],
    [1,"","bellpepper","aromatic","pimentón rojo","red bell pepper","picado","chopped"],
    [250,"ml","winered","liquid","vino tinto","red wine"],
    [500,"ml","water","liquid","agua","water"]],
 es:{n:"Asado negro", b:"Muchacho de res dorado en papelón caramelizado y cocido en vino hasta quedar negro por fuera y tierno por dentro. El asado de las fiestas caraqueñas.",
  st:["Unta la carne con el ajo, la sal, la pimienta y la salsa inglesa. Refrigera toda la noche.",
      "Calienta el aceite en una olla gruesa y derrite el papelón hasta que esté oscuro y humee, 3 minutos.",
      "Dora la carne en el caramelo 10 minutos, girándola, hasta que esté negra por todos lados.",
      "Añade la cebolla y el pimentón y sofríe 5 minutos. Añade el vino y el agua.",
      "Tapa y cuece a fuego bajo 2 horas y media, volteando cada 30 minutos.",
      "Saca la carne, licúa la salsa y redúcela hasta que espese. Rebana fino y sirve con la salsa."],
  tp:["El caramelo debe humear un poco pero no oler a quemado.",
      "Se sirve con arroz blanco y plátano maduro."],
  v:"asado negro venezolano receta"},
 en:{n:"Asado Negro (Venezuelan Black Roast)", b:"Beef eye of round browned in caramelised papelón and braised in wine until black outside and tender within. The roast of Caracas celebrations.",
  st:["Rub the beef with the garlic, salt, pepper and Worcestershire. Chill overnight.",
      "Heat the oil in a heavy pot and melt the papelón until dark and smoking, 3 minutes.",
      "Brown the beef in the caramel for 10 minutes, turning, until black all over.",
      "Add the onion and bell pepper and cook 5 minutes. Add the wine and water.",
      "Cover and cook on low for 2 and a half hours, turning every 30 minutes.",
      "Lift out the beef, blend the sauce and reduce until thick. Slice thinly and serve with the sauce."],
  tp:["The caramel should smoke a little but not smell burned.",
      "Serve with white rice and sweet plantain."],
  v:"asado negro recipe"}},

{id:"reina-pepiada", c:"Venezuela", r:"latin-america", m:"main", t:60, s:4,
 i:[[2,"","chicken","protein","pechugas de pollo","chicken breasts"],
    [1,"l","water","liquid","agua","water"],
    [1.5,"tsp","salt","salt","sal","salt"],
    [2,"","avocado","protein","aguacates maduros","ripe avocados"],
    [3,"tbsp","mayo","fat","mayonesa","mayonnaise"],
    [0.25,"","onion","aromatic","cebolla","onion","picada fina","finely chopped"],
    [1,"","citrus","acid","limón","lime","en jugo","juiced"],
    [1,"handful","herb","aromatic","cilantro","cilantro","picado","chopped"],
    [300,"g","cornmeal","structure","harina de maíz precocida","precooked cornmeal (masarepa)"],
    [375,"ml","water","liquid","agua tibia para la masa","warm water for the dough"]],
 es:{n:"Arepa reina pepiada", b:"Arepa rellena de pollo desmechado con aguacate y mayonesa. Nombrada por una reina de belleza venezolana.",
  st:["Cuece el pollo en el agua con 1 cucharadita de sal 20 minutos. Enfría y desmecha.",
      "Machaca los aguacates con la mayonesa, la cebolla, el limón y el cilantro. Mezcla con el pollo y prueba de sal.",
      "Amasa la harina con el agua tibia y el resto de la sal. Reposa 5 minutos.",
      "Forma 8 bolas y aplánalas a 1 centímetro de grueso.",
      "Cuécelas en un sartén o budare a fuego medio 6 minutos por lado, hasta que tengan costra y suenen huecas al tocarlas.",
      "Ábrelas por un lado y rellena con la mezcla."],
  tp:["El limón evita que el aguacate se oscurezca.",
      "Si la arepa suena hueca al darle golpecitos, está lista por dentro."],
  v:"reina pepiada receta"},
 en:{n:"Reina Pepiada Arepa", b:"An arepa filled with shredded chicken, avocado and mayonnaise. Named for a Venezuelan beauty queen.",
  st:["Poach the chicken in the water with 1 teaspoon of salt for 20 minutes. Cool and shred.",
      "Mash the avocados with the mayonnaise, onion, lime and cilantro. Mix with the chicken and taste for salt.",
      "Knead the cornmeal with the warm water and the rest of the salt. Rest 5 minutes.",
      "Shape 8 balls and flatten to 1 centimetre thick.",
      "Cook in a pan or griddle over medium heat for 6 minutes per side, until crusted and hollow-sounding when tapped.",
      "Slit them open along one side and fill with the mixture."],
  tp:["The lime keeps the avocado from browning.",
      "If the arepa sounds hollow when tapped, it's cooked inside."],
  v:"reina pepiada recipe"}},

{id:"perico", c:"Venezuela", r:"latin-america", m:"breakfast", t:15, s:2,
 i:[[4,"","egg","protein","huevos","eggs"],
    [1,"","tomato","aromatic","tomate","tomato","picado","chopped"],
    [0.5,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [2,"","bellpepper","aromatic","ajíes dulces o 1/4 de pimentón","sweet ají peppers or 1/4 bell pepper","picados","chopped"],
    [1,"tbsp","oil","fat","aceite","oil"],
    [0.5,"tsp","salt","salt","sal","salt"]],
 es:{n:"Perico venezolano", b:"Huevos revueltos con tomate, cebolla y ají dulce. El relleno de arepa de todas las mañanas.",
  st:["Calienta el aceite y sofríe la cebolla y el ají 4 minutos.",
      "Añade el tomate y cuece 3 minutos, hasta que suelte su jugo.",
      "Bate los huevos con la sal, viértelos y revuelve a fuego bajo hasta que cuajen suaves.",
      "Sirve solo o dentro de una arepa."],
  tp:["Fuego bajo al final: el perico debe quedar húmedo, no seco.",
      "Añade el tomate antes que el huevo para que no quede aguado."],
  v:"perico venezolano receta"},
 en:{n:"Venezuelan Perico (Scrambled Eggs)", b:"Eggs scrambled with tomato, onion and sweet ají pepper. The everyday morning arepa filling.",
  st:["Heat the oil and cook the onion and pepper for 4 minutes.",
      "Add the tomato and cook 3 minutes, until it releases its juice.",
      "Beat the eggs with the salt, pour them in and stir over low heat until softly set.",
      "Serve on its own or inside an arepa."],
  tp:["Low heat at the end: perico should be moist, not dry.",
      "Add the tomato before the egg so it isn't watery."],
  v:"venezuelan perico recipe"}},

{id:"quesillo", c:"Venezuela", r:"latin-america", m:"sweet", t:90, s:8, o:170,
 i:[[150,"g","sugar","caramel","azúcar","sugar","para el caramelo","for the caramel"],
    [3,"tbsp","water","liquid","agua","water"],
    [395,"g","condensedmilk","sweet","leche condensada","sweetened condensed milk"],
    [400,"ml","milk","liquid","leche","milk"],
    [5,"","egg","set","huevos","eggs"],
    [1,"tsp","vanilla","aromatic","extracto de vainilla","vanilla extract"]],
 es:{n:"Quesillo venezolano", b:"El flan de Venezuela: más denso y con agujeritos como un queso, sobre un caramelo oscuro.",
  st:["Derrite el azúcar con el agua en el molde de quesillo a fuego medio, sin mover, hasta que esté color ámbar oscuro. Gira el molde para cubrir el fondo y los lados.",
      "Calienta el horno a 170 °C.",
      "Licúa la leche condensada, la leche, los huevos y la vainilla 30 segundos. Vierte sobre el caramelo.",
      "Tapa el molde con aluminio y ponlo en una bandeja con agua caliente hasta la mitad.",
      "Hornea 60 minutos, hasta que al insertar un cuchillo salga limpio.",
      "Enfría y refrigera al menos 4 horas. Desmolda pasando un cuchillo por el borde y volteando sobre un plato."],
  tp:["Licuarlo es lo que crea los agujeritos que le dan el nombre.",
      "Si el caramelo se endurece antes de cubrir el molde, caliéntalo un momento."],
  v:"quesillo venezolano receta"},
 en:{n:"Venezuelan Quesillo (Flan)", b:"Venezuela's flan: denser, with little holes like a cheese, over a dark caramel.",
  st:["Melt the sugar with the water in the flan mould over medium heat, without stirring, until dark amber. Tilt the mould to coat the bottom and sides.",
      "Heat the oven to 170 °C.",
      "Blend the condensed milk, milk, eggs and vanilla for 30 seconds. Pour over the caramel.",
      "Cover the mould with foil and set it in a tray of hot water halfway up.",
      "Bake 60 minutes, until a knife comes out clean.",
      "Cool and chill at least 4 hours. Run a knife round the edge and turn out onto a plate."],
  tp:["Blending is what creates the little holes that give it its name.",
      "If the caramel hardens before coating the mould, warm it briefly."],
  v:"quesillo recipe"}},

{id:"bienmesabe", c:"Venezuela", r:"latin-america", m:"sweet", t:60, s:10,
 i:[[400,"ml","coconutcream","liquid","crema de coco","coconut cream"],
    [200,"g","sugar","sweet","azúcar","sugar"],
    [1,"","spice","aromatic","raja de canela","cinnamon stick"],
    [5,"","eggyolk","set","yemas de huevo","egg yolks"],
    [24,"","ladyfingers","structure","bizcochos de soletilla","ladyfingers"],
    [1,"tsp","spice","garnish","canela molida","ground cinnamon"]],
 es:{n:"Bienmesabe", b:"Capas de bizcocho empapadas en una crema espesa de coco y yemas, con canela. El postre de coco más querido de Venezuela.",
  st:["Calienta la crema de coco con el azúcar y la canela 10 minutos a fuego bajo, moviendo.",
      "Bate las yemas. Vierte encima un cucharón de la crema caliente batiendo, y luego regresa todo a la olla.",
      "Cuece a fuego bajo 8 minutos, moviendo sin parar, hasta que espese como natilla. No hiervas. Saca la canela.",
      "En un molde, pon una capa de bizcochos, cubre con crema y repite hasta terminar con crema.",
      "Espolvorea canela y refrigera 4 horas antes de servir."],
  tp:["Si hierve después de las yemas, se corta: fuego bajo y paciencia.",
      "Tradicionalmente se moja el bizcocho en vino dulce; aquí no lleva alcohol."],
  v:"bienmesabe venezolano receta"},
 en:{n:"Bienmesabe (Coconut Cream Trifle)", b:"Layers of sponge soaked in a thick coconut and egg-yolk custard, with cinnamon. Venezuela's favourite coconut dessert.",
  st:["Heat the coconut cream with the sugar and cinnamon for 10 minutes on low, stirring.",
      "Whisk the yolks. Pour in a ladle of the hot cream while whisking, then return everything to the pot.",
      "Cook on low for 8 minutes, stirring constantly, until thick like custard. Don't boil. Remove the cinnamon.",
      "In a dish, lay a layer of ladyfingers, cover with cream and repeat, ending with cream.",
      "Dust with cinnamon and chill 4 hours before serving."],
  tp:["If it boils after the yolks go in, it curdles: low heat and patience.",
      "Traditionally the sponge is soaked in sweet wine; this version has no alcohol."],
  v:"bienmesabe recipe"}},

{id:"pan-de-jamon", c:"Venezuela", r:"latin-america", m:"bread", t:180, s:10, o:180,
 i:[[500,"g","breadflour","structure","harina de trigo de fuerza","bread flour"],
    [7,"g","yeast","leaven","levadura seca","instant yeast"],
    [60,"g","sugar","sweet","azúcar","sugar"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"","egg","binder","huevo","egg"],
    [250,"ml","milk","liquid","leche tibia","warm milk"],
    [60,"g","butter","fat","mantequilla","butter","suave","soft"],
    [400,"g","ham","protein","jamón cocido en lonjas","sliced cooked ham"],
    [100,"g","olives","garnish","aceitunas verdes sin hueso","pitted green olives","en rodajas","sliced"],
    [80,"g","driedfruit","sweet","pasas","raisins"],
    [1,"","egg","glaze","huevo para barnizar","egg to glaze"]],
 es:{n:"Pan de jamón", b:"El pan de Navidad de Caracas: masa dulce enrollada con jamón, aceitunas y pasas, barnizada y dorada.",
  st:["Mezcla la harina, la levadura, el azúcar y la sal. Añade el huevo y la leche y amasa 5 minutos. Añade la mantequilla y amasa 8 minutos más.",
      "Tapa y deja crecer 60 minutos, hasta que doble.",
      "Divide en 2 y estira cada parte en un rectángulo de 30 por 40 centímetros.",
      "Cubre con el jamón, las aceitunas y las pasas, dejando 2 centímetros de borde. Enrolla desde el lado largo y sella.",
      "Pon en una bandeja con el cierre abajo, pincha la superficie con un tenedor y deja crecer 30 minutos. Calienta el horno a 180 °C.",
      "Barniza con el huevo batido y hornea 30 a 35 minutos, hasta que esté dorado y suene hueco por debajo."],
  tp:["Pincha el pan antes de hornear para que el vapor salga y no se abra.",
      "Frío o tibio, rebanado grueso, en la mesa de Navidad."],
  v:"pan de jamon venezolano receta"},
 en:{n:"Pan de Jamón (Venezuelan Ham Bread)", b:"Caracas's Christmas bread: sweet dough rolled with ham, olives and raisins, glazed and golden.",
  st:["Mix the flour, yeast, sugar and salt. Add the egg and milk and knead 5 minutes. Add the butter and knead 8 minutes more.",
      "Cover and let rise 60 minutes, until doubled.",
      "Divide in 2 and roll each piece into a 30 by 40 centimetre rectangle.",
      "Cover with the ham, olives and raisins, leaving a 2 centimetre border. Roll up from the long side and seal.",
      "Set seam-down on a tray, prick the top with a fork and let rise 30 minutes. Heat the oven to 180 °C.",
      "Brush with the beaten egg and bake 30 to 35 minutes, until golden and hollow-sounding underneath."],
  tp:["Prick the bread before baking so steam escapes and it doesn't split.",
      "Cold or warm, thickly sliced, on the Christmas table."],
  v:"pan de jamon recipe"}}
];
