module.exports = [
{id:"cachitos", c:"Venezuela", r:"latin-america", m:"bread", t:180, s:12, o:180,
 i:[[500,"g","breadflour","structure","harina de trigo de fuerza","bread flour"],
    [7,"g","yeast","leaven","levadura seca","dried yeast"],
    [60,"g","sugar","sweet","azúcar","sugar"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"","egg","enrich","huevo","egg"],
    [220,"ml","milk","liquid","leche tibia","warm milk"],
    [80,"g","butter","fat","mantequilla blanda","soft butter"],
    [300,"g","ham","protein","jamón cocido","cooked ham","picado fino","finely chopped"],
    [1,"","egg","glaze","huevo batido","beaten egg"]],
 es:{n:"Cachitos de jamón", b:"Panecillos dulces en forma de cuerno rellenos de jamón picado. El desayuno de panadería en Venezuela.",
  st:["Mezcla la harina, la levadura, el azúcar y la sal. Añade el huevo y la leche y amasa 10 minutos. Añade la mantequilla y amasa 5 minutos más.",
      "Tapa y deja crecer 1 hora, hasta que doble su tamaño.",
      "Divide en 2 y estira cada parte en un círculo de 35 cm. Corta 6 triángulos en cada círculo.",
      "Pon jamón en la base de cada triángulo y enrolla hacia la punta. Curva en forma de cuerno y deja crecer 40 minutos.",
      "Pinta con el huevo batido y hornea a 180 °C durante 20 minutos, hasta que estén dorados."],
  tp:["Pica el jamón muy fino para que se reparta bien al enrollar.",
      "Deja espacio entre ellos en la bandeja: crecen bastante en el horno."],
  v:"cachitos de jamón venezolanos receta"},
 en:{n:"Cachitos (Venezuelan Ham Rolls)", b:"Sweet crescent rolls filled with chopped ham. The bakery breakfast of Venezuela.",
  st:["Mix the flour, yeast, sugar and salt. Add the egg and milk and knead 10 minutes. Add the butter and knead 5 minutes more.",
      "Cover and rise 1 hour, until doubled.",
      "Divide in 2 and roll each into a 35 cm circle. Cut 6 triangles from each circle.",
      "Put ham at the wide end of each triangle and roll towards the tip. Curve into a crescent and rise 40 minutes.",
      "Brush with the beaten egg and bake at 180 °C for 20 minutes, until golden."],
  tp:["Chop the ham very fine so it spreads evenly as you roll.",
      "Leave space between them on the tray: they grow a lot in the oven."],
  v:"venezuelan cachitos recipe"}},

{id:"empanadas-venezolanas", c:"Venezuela", r:"latin-america", m:"snack", t:60, s:12,
 i:[[400,"g","masa","structure","harina de maíz precocida","pre-cooked corn flour"],
    [1,"tbsp","sugar","sweet","azúcar","sugar"],
    [1,"tsp","salt","salt","sal","salt"],
    [500,"ml","water","liquid","agua tibia","warm water"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","pimentón rojo","red bell pepper","picado","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [400,"g","beef","protein","carne molida de res","ground beef"],
    [1,"","tomato","sauce","tomate","tomato","picado","chopped"],
    [1,"l","oil","fat","aceite para freír","oil for frying"]],
 es:{n:"Empanadas venezolanas de carne", b:"Empanadas de masa de maíz, crujientes y doradas, rellenas de carne molida guisada. Se fríen al momento.",
  st:["Sofríe la cebolla, el pimentón y el ajo en 2 cucharadas de aceite 5 minutos. Añade la carne y el tomate, sala al gusto y cuece 15 minutos. Enfría.",
      "Mezcla la harina, el azúcar y la sal. Añade el agua y amasa hasta tener una masa suave. Deja 5 minutos.",
      "Haz 12 bolas y aplana cada una sobre un plástico hasta 3 mm.",
      "Pon relleno en una mitad, dobla con ayuda del plástico y corta el borde con un plato pequeño.",
      "Fríe a 180 °C durante 4 minutos, hasta que estén doradas."],
  tp:["El azúcar en la masa ayuda a que se doren.",
      "Si la masa se agrieta al doblar, le falta agua; añade una cucharada."],
  v:"empanadas venezolanas de carne molida"},
 en:{n:"Venezuelan Beef Empanadas", b:"Crisp golden corn-dough empanadas filled with stewed ground beef. Fried to order.",
  st:["Cook the onion, pepper and garlic in 2 tablespoons of oil for 5 minutes. Add the beef and tomato, salt to taste and cook 15 minutes. Cool.",
      "Mix the corn flour, sugar and salt. Add the water and knead to a soft dough. Leave 5 minutes.",
      "Make 12 balls and flatten each on a sheet of plastic to 3 mm.",
      "Put filling on one half, fold using the plastic and trim the edge with a small plate.",
      "Fry at 180 °C for 4 minutes, until golden."],
  tp:["The sugar in the dough helps them brown.",
      "If the dough cracks when folded it needs water; add a spoonful."],
  v:"venezuelan empanadas recipe"}},

{id:"pisca-andina", c:"Venezuela", r:"latin-america", m:"soup", t:35, s:4,
 i:[[1.2,"l","water","liquid","agua","water"],
    [500,"g","potato","structure","papas","potatoes","en dados","diced"],
    [4,"","scallion","aromatic","cebollín","scallions","picado","chopped"],
    [2,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"tbsp","butter","fat","mantequilla","butter"],
    [1,"handful","herb","aromatic","cilantro","cilantro","picado","chopped"],
    [2,"tsp","salt","salt","sal","salt"],
    [250,"ml","milk","enrich","leche","milk"],
    [4,"","egg","protein","huevos","eggs"],
    [100,"g","cheese","garnish","queso blanco","white fresh cheese","en dados","diced"]],
 es:{n:"Pisca andina", b:"Sopa de papa, cebollín y cilantro con huevo escalfado y queso. El desayuno de los Andes venezolanos.",
  st:["Sofríe el cebollín y el ajo en la mantequilla 3 minutos.",
      "Añade el agua, la papa y la sal y cuece 15 minutos, hasta que la papa esté tierna.",
      "Añade la leche y la mitad del cilantro y calienta sin que hierva fuerte.",
      "Casca los huevos en la sopa y escálfalos 4 minutos.",
      "Sirve cada plato con un huevo, el queso y el resto del cilantro."],
  tp:["Pon el queso en el plato y vierte la sopa caliente encima para que se ablande.",
      "Se acompaña con arepas."],
  v:"pisca andina receta"},
 en:{n:"Pisca Andina (Andean Potato and Egg Soup)", b:"Potato, scallion and cilantro soup with poached egg and cheese. Breakfast in the Venezuelan Andes.",
  st:["Cook the scallion and garlic in the butter for 3 minutes.",
      "Add the water, potato and salt and cook 15 minutes, until tender.",
      "Add the milk and half the cilantro and heat without a hard boil.",
      "Crack the eggs into the soup and poach 4 minutes.",
      "Serve each bowl with an egg, the cheese and the rest of the cilantro."],
  tp:["Put the cheese in the bowl and pour the hot soup over so it softens.",
      "It is eaten with arepas."],
  v:"pisca andina recipe"}},

{id:"polvorosa-de-pollo", c:"Venezuela", r:"latin-america", m:"main", t:120, s:8, o:180,
 i:[[400,"g","apflour","structure","harina de trigo","plain flour"],
    [1,"tsp","salt","salt","sal","salt"],
    [1,"tbsp","sugar","sweet","azúcar","sugar"],
    [200,"g","butter","fat","mantequilla fría","cold butter","en dados","diced"],
    [1,"","egg","binder","huevo","egg"],
    [60,"ml","water","liquid","agua fría","cold water"],
    [800,"g","chicken","protein","pollo cocido","cooked chicken","desmenuzado","shredded"],
    [2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","pimentón rojo","red bell pepper","picado","chopped"],
    [2,"","tomato","sauce","tomates","tomatoes","picados","chopped"],
    [60,"g","olives","umami","aceitunas verdes","green olives","picadas","chopped"],
    [40,"g","driedfruit","sweet","pasas","raisins"],
    [1,"","egg","glaze","huevo batido","beaten egg"]],
 es:{n:"Polvorosa de pollo", b:"Pastel de masa quebrada dulce-salada relleno de pollo guisado con aceitunas y pasas. Plato de fiesta caraqueño.",
  st:["Mezcla la harina, la sal y el azúcar. Frota la mantequilla hasta tener migas. Añade el huevo y el agua, junta la masa sin amasar y refrigera 30 minutos.",
      "Sofríe la cebolla y el pimentón en el aceite 5 minutos. Añade el tomate, el pollo, las aceitunas y las pasas. Sala al gusto y cuece 10 minutos, hasta que esté casi seco. Enfría.",
      "Estira dos tercios de la masa y forra un molde de 24 cm. Rellena con el pollo.",
      "Cubre con el resto de la masa, sella los bordes y pinta con el huevo batido.",
      "Hornea a 180 °C durante 45 minutos, hasta que esté dorada."],
  tp:["El relleno debe estar frío y casi seco o la masa se empapa.",
      "Se desmorona al cortarla, por eso se llama polvorosa."],
  v:"polvorosa de pollo venezolana"},
 en:{n:"Polvorosa de Pollo (Venezuelan Chicken Pie)", b:"A sweet-savoury crumbly pie filled with chicken stewed with olives and raisins. A Caracas party dish.",
  st:["Mix the flour, salt and sugar. Rub in the butter to crumbs. Add the egg and water, bring together without kneading and chill 30 minutes.",
      "Cook the onion and pepper in the oil for 5 minutes. Add the tomato, chicken, olives and raisins. Salt to taste and cook 10 minutes, until nearly dry. Cool.",
      "Roll out two thirds of the dough and line a 24 cm tin. Fill with the chicken.",
      "Cover with the rest of the dough, seal the edges and brush with the beaten egg.",
      "Bake at 180 °C for 45 minutes, until golden."],
  tp:["The filling must be cold and nearly dry or the pastry goes soggy.",
      "It crumbles when cut, which is where the name comes from."],
  v:"venezuelan chicken pie recipe"}},

{id:"golfeados", c:"Venezuela", r:"latin-america", m:"bread", t:180, s:12, o:180,
 i:[[500,"g","breadflour","structure","harina de trigo de fuerza","bread flour"],
    [7,"g","yeast","leaven","levadura seca","dried yeast"],
    [50,"g","sugar","sweet","azúcar","sugar"],
    [1,"tsp","salt","salt","sal","salt"],
    [2,"","egg","enrich","huevos","eggs"],
    [180,"ml","milk","liquid","leche tibia","warm milk"],
    [80,"g","butter","fat","mantequilla blanda","soft butter"],
    [250,"g","jaggery","sweet","papelón rallado","grated papelón (unrefined cane sugar)"],
    [200,"g","cheese","protein","queso blanco duro","hard white cheese","rallado","grated"],
    [1,"tbsp","spice","aromatic","anís en grano","aniseed"],
    [100,"ml","water","liquid","agua","water"]],
 es:{n:"Golfeados", b:"Espirales de pan con papelón, anís y queso blanco, bañados en melado. Dulce y salado a la vez.",
  st:["Mezcla la harina, la levadura, el azúcar y la sal. Añade los huevos y la leche y amasa 10 minutos. Añade la mitad de la mantequilla y amasa 5 minutos. Deja crecer 1 hora.",
      "Estira en un rectángulo de 30 x 40 cm y pinta con el resto de la mantequilla.",
      "Esparce 200 g del papelón, el queso y el anís. Enrolla por el lado largo y corta 12 rodajas.",
      "Colócalas en un molde engrasado, deja crecer 40 minutos y hornea a 180 °C durante 25 minutos.",
      "Cuece el resto del papelón con el agua 5 minutos y báñalos al salir del horno."],
  tp:["Sirve los golfeados tibios; el melado aún brilla.",
      "Si no encuentras papelón, usa panela o azúcar moreno oscuro."],
  v:"golfeados venezolanos receta"},
 en:{n:"Golfeados (Venezuelan Cheese and Papelón Rolls)", b:"Bread spirals with papelón, aniseed and white cheese, glazed with cane syrup. Sweet and salty at once.",
  st:["Mix the flour, yeast, sugar and salt. Add the eggs and milk and knead 10 minutes. Add half the butter and knead 5 minutes. Rise 1 hour.",
      "Roll into a 30 x 40 cm rectangle and brush with the rest of the butter.",
      "Scatter 200 g of the papelón, the cheese and the aniseed. Roll up from the long side and cut 12 slices.",
      "Place in a greased tin, rise 40 minutes and bake at 180 °C for 25 minutes.",
      "Simmer the rest of the papelón with the water for 5 minutes and glaze them as they leave the oven."],
  tp:["Serve them warm while the glaze still shines.",
      "If you can't find papelón, use panela or dark brown sugar."],
  v:"golfeados recipe"}},

{id:"chicha-venezolana", c:"Venezuela", r:"latin-america", m:"drink", t:50, s:6,
 i:[[150,"g","rice","structure","arroz blanco","white rice"],
    [1.2,"l","water","liquid","agua","water"],
    [500,"ml","milk","liquid","leche fría","cold milk"],
    [200,"g","condensedmilk","sweet","leche condensada","condensed milk"],
    [1,"tsp","spice","aromatic","canela molida","ground cinnamon"],
    [1,"handful","ice","structure","hielo","ice"]],
 es:{n:"Chicha venezolana", b:"Bebida espesa y dulce de arroz cocido con leche y canela. Se vende en la calle bien fría.",
  st:["Cuece el arroz en el agua 35 minutos, hasta que esté muy blando. Deja enfriar.",
      "Licúa el arroz con su agua, la leche y la leche condensada hasta que esté muy liso.",
      "Cuela si quieres una textura más fina.",
      "Refrigera al menos 1 hora.",
      "Sirve con hielo y la canela por encima."],
  tp:["Debe quedar espesa como un batido; aligera con leche si hace falta.",
      "Se guarda 2 días en la nevera. Remueve antes de servir."],
  v:"chicha venezolana receta"},
 en:{n:"Venezuelan Chicha (Rice Drink)", b:"A thick sweet drink of cooked rice with milk and cinnamon. Sold ice-cold on the street.",
  st:["Cook the rice in the water for 35 minutes, until very soft. Cool.",
      "Blend the rice and its water with the milk and condensed milk until very smooth.",
      "Strain for a finer texture if you like.",
      "Refrigerate at least 1 hour.",
      "Serve over ice with the cinnamon on top."],
  tp:["It should be thick like a milkshake; loosen with milk if needed.",
      "Keeps 2 days in the fridge. Stir before serving."],
  v:"venezuelan chicha recipe"}},

{id:"hervido-de-gallina", c:"Venezuela", r:"latin-america", m:"soup", t:120, s:8,
 i:[[1.5,"kg","chicken","protein","gallina o pollo en presas","boiling hen or chicken pieces"],
    [3,"l","water","liquid","agua","water"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [4,"","scallion","aromatic","cebollín","scallions","picado","chopped"],
    [1,"","bellpepper","aromatic","ají dulce o pimentón","sweet pepper","picado","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","machacado","crushed"],
    [2,"","corn","structure","mazorcas de maíz","corn cobs","en ruedas","in rounds"],
    [400,"g","cassava","structure","yuca","cassava","en trozos","in chunks"],
    [400,"g","veg","structure","ocumo o malanga","taro (ocumo)","en trozos","in chunks"],
    [300,"g","veg","structure","auyama","calabaza (West Indian pumpkin)","en trozos","in chunks"],
    [2,"","veg","structure","zanahorias","carrots","en rodajas","sliced"],
    [1,"bunch","herb","aromatic","cilantro","cilantro","picado","chopped"],
    [1,"tbsp","salt","salt","sal","salt"]],
 es:{n:"Hervido de gallina", b:"Sopa grande de gallina con verduras y tubérculos. El plato de domingo que reúne a la familia en Venezuela.",
  st:["Cuece la gallina en el agua con la sal 1 hora, quitando la espuma.",
      "Añade la cebolla, el cebollín, el ají, el ajo y la mitad del cilantro.",
      "Añade el maíz, la yuca y el ocumo y cuece 20 minutos.",
      "Añade la auyama y la zanahoria y cuece 20 minutos más, hasta que todo esté tierno.",
      "Termina con el resto del cilantro."],
  tp:["La gallina da más sabor que el pollo pero necesita más tiempo; con pollo, basta 30 minutos en el primer paso.",
      "Se sirve con arepa y aguacate."],
  v:"hervido de gallina venezolano"},
 en:{n:"Hervido de Gallina (Venezuelan Hen Soup)", b:"A big hen soup with vegetables and roots. The Sunday dish that brings the family together in Venezuela.",
  st:["Simmer the hen in the water with the salt for 1 hour, skimming.",
      "Add the onion, scallion, pepper, garlic and half the cilantro.",
      "Add the corn, cassava and taro and cook 20 minutes.",
      "Add the calabaza and carrot and cook 20 minutes more, until everything is tender.",
      "Finish with the rest of the cilantro."],
  tp:["Hen gives more flavour than chicken but needs longer; with chicken, 30 minutes is enough in the first step.",
      "It is served with arepa and avocado."],
  v:"venezuelan chicken soup recipe"}},

{id:"majarete", c:"Venezuela", r:"latin-america", m:"sweet", t:40, s:8,
 i:[[800,"ml","coconutmilk","liquid","leche de coco","coconut milk"],
    [100,"g","masa","structure","harina de maíz precocida","pre-cooked corn flour"],
    [200,"g","jaggery","sweet","papelón rallado","grated papelón (unrefined cane sugar)"],
    [1,"","spice","aromatic","rama de canela","cinnamon stick"],
    [4,"","spice","aromatic","clavos de olor","whole cloves"],
    [1,"pinch","salt","salt","sal","salt"],
    [1,"tsp","spice","garnish","canela molida","ground cinnamon"]],
 es:{n:"Majarete", b:"Pudín firme de coco, maíz y papelón con canela. Postre de Semana Santa en Venezuela.",
  st:["Mezcla la harina de maíz con 250 ml de la leche de coco hasta que no haya grumos.",
      "Calienta el resto de la leche de coco con el papelón, la canela, los clavos y la sal hasta que el papelón se disuelva. Saca las especias.",
      "Añade la mezcla de maíz, batiendo, y cuece 10 minutos a fuego bajo sin parar de remover, hasta que esté muy espeso.",
      "Vierte en un molde humedecido y deja enfriar. Refrigera 3 horas.",
      "Desmolda y espolvorea la canela molida."],
  tp:["Remueve siempre en el mismo sentido y llegando al fondo; se pega enseguida.",
      "Algunas familias lo hacen con maíz tierno licuado en lugar de harina."],
  v:"majarete venezolano receta"},
 en:{n:"Majarete (Coconut and Corn Pudding)", b:"A firm pudding of coconut, corn and papelón with cinnamon. A Venezuelan Holy Week dessert.",
  st:["Mix the corn flour with 250 ml of the coconut milk until smooth.",
      "Heat the rest of the coconut milk with the papelón, cinnamon, cloves and salt until the papelón dissolves. Remove the spices.",
      "Add the corn mixture, whisking, and cook 10 minutes on low, stirring constantly, until very thick.",
      "Pour into a rinsed mould and let cool. Refrigerate 3 hours.",
      "Turn out and dust with the ground cinnamon."],
  tp:["Stir in one direction, reaching the bottom; it catches at once.",
      "Some families make it with blended fresh corn instead of flour."],
  v:"majarete recipe"}},

{id:"dulce-de-lechosa", c:"Venezuela", r:"latin-america", m:"sweet", t:90, s:10,
 i:[[1,"kg","fruit","structure","lechosa (papaya) verde","green papaya","pelada, en tiras","peeled, in strips"],
    [1,"tsp","bakingsoda","structure","bicarbonato de sodio","baking soda"],
    [500,"g","jaggery","sweet","papelón rallado","grated papelón (unrefined cane sugar)"],
    [500,"ml","water","liquid","agua","water"],
    [2,"","spice","aromatic","ramas de canela","cinnamon sticks"],
    [6,"","spice","aromatic","clavos de olor","whole cloves"]],
 es:{n:"Dulce de lechosa", b:"Tiras de papaya verde cocidas en almíbar de papelón con canela y clavo. Dulce navideño de Venezuela.",
  st:["Remoja las tiras de lechosa en agua con el bicarbonato 1 hora. Enjuaga bien.",
      "Cuece el papelón con el agua, la canela y los clavos 10 minutos.",
      "Añade la lechosa y cuece a fuego bajo 60 minutos, hasta que esté brillante y translúcida y el almíbar espese.",
      "Deja enfriar en el almíbar.",
      "Guarda en frascos en la nevera."],
  tp:["El bicarbonato hace que la lechosa quede firme y no se deshaga.",
      "Dura 2 semanas en la nevera."],
  v:"dulce de lechosa receta"},
 en:{n:"Dulce de Lechosa (Candied Green Papaya)", b:"Strips of green papaya cooked in papelón syrup with cinnamon and clove. A Venezuelan Christmas sweet.",
  st:["Soak the papaya strips in water with the baking soda for 1 hour. Rinse well.",
      "Simmer the papelón with the water, cinnamon and cloves for 10 minutes.",
      "Add the papaya and cook on low for 60 minutes, until glossy and translucent and the syrup thickens.",
      "Let cool in the syrup.",
      "Store in jars in the fridge."],
  tp:["The baking soda keeps the papaya firm so it doesn't fall apart.",
      "Keeps 2 weeks in the fridge."],
  v:"candied green papaya recipe"}},

{id:"ensalada-de-gallina", c:"Venezuela", r:"latin-america", m:"side", t:45, s:8,
 i:[[800,"g","potato","structure","papas","potatoes","en dados de 1 cm","in 1 cm dice"],
    [2,"","veg","structure","zanahorias","carrots","en dados de 1 cm","in 1 cm dice"],
    [150,"g","legume","structure","guisantes","peas"],
    [500,"g","chicken","protein","pollo cocido","cooked chicken","desmenuzado","shredded"],
    [1,"","fruit","sweet","manzana verde","green apple","en dados","diced"],
    [200,"g","mayo","binder","mayonesa","mayonnaise"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Ensalada de gallina", b:"Ensalada de papa, zanahoria, guisantes y pollo con mayonesa y manzana. Acompaña la hallaca en Navidad.",
  st:["Cuece la papa y la zanahoria en agua con sal 10 minutos, hasta que estén tiernas pero firmes. Añade los guisantes el último minuto.",
      "Escurre y deja enfriar.",
      "Mezcla con el pollo y la manzana.",
      "Añade la mayonesa y la sal y mezcla con cuidado.",
      "Refrigera 1 hora antes de servir."],
  tp:["Enfría las verduras del todo antes de la mayonesa o se corta.",
      "La manzana da el toque dulce típico; no la quites."],
  v:"ensalada de gallina venezolana"},
 en:{n:"Ensalada de Gallina (Venezuelan Chicken Salad)", b:"A salad of potato, carrot, peas and chicken with mayonnaise and apple. Served with hallacas at Christmas.",
  st:["Boil the potato and carrot in salted water for 10 minutes, until tender but firm. Add the peas for the last minute.",
      "Drain and cool.",
      "Mix with the chicken and apple.",
      "Add the mayonnaise and salt and fold gently.",
      "Refrigerate 1 hour before serving."],
  tp:["Cool the vegetables completely before adding mayonnaise or it splits.",
      "The apple gives the typical sweet note; don't leave it out."],
  v:"venezuelan chicken salad recipe"}}
];
