module.exports = [
{id:"carne-mechada", c:"Venezuela", r:"latin-america", m:"main", t:150, s:6,
 i:[[1,"kg","beef","protein","falda de res","beef flank"],
    [2,"l","water","liquid","agua","water"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","pimentón rojo","red bell pepper","picado","chopped"],
    [4,"","bellpepper","aromatic","ajíes dulces","sweet ají peppers","picados","chopped"],
    [4,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [3,"","tomato","liquid","tomates","tomatoes","picados","chopped"],
    [1,"tsp","spice","aromatic","comino","cumin"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Carne mechada", b:"Carne de res deshilachada y guisada con pimentón, ají dulce y tomate. El corazón del pabellón criollo.",
  st:["Cuece la carne en el agua con 1 cucharadita de sal 90 minutos. Deja enfriar y deshiláchala. Guarda 300 ml del caldo.",
      "Sofríe la cebolla, los pimentones, los ajíes y el ajo en el aceite 8 minutos.",
      "Añade el tomate y el comino y cocina 8 minutos.",
      "Añade la carne, el caldo y el resto de la sal y cuece 20 minutos, hasta que se seque un poco."],
  tp:["Deshiláchala en tiras finas con dos tenedores.",
      "Se congela bien en porciones."],
  v:"carne mechada venezolana"},
 en:{n:"Carne Mechada (Venezuelan Shredded Beef)", b:"Shredded beef stewed with bell pepper, sweet ají and tomato. The heart of pabellón criollo.",
  st:["Simmer the beef in the water with 1 teaspoon of salt for 90 minutes. Cool and shred. Keep 300 ml of the broth.",
      "Cook the onion, peppers, ají and garlic in the oil for 8 minutes.",
      "Add the tomato and cumin and cook 8 minutes.",
      "Add the beef, broth and remaining salt and simmer 20 minutes, until slightly dry."],
  tp:["Shred into fine strands with two forks.",
      "It freezes well in portions."],
  v:"venezuelan shredded beef"}},

{id:"caraotas-negras", c:"Venezuela", r:"latin-america", m:"side", t:150, s:8,
 i:[[500,"g","legume","structure","caraotas negras secas","dried black beans"],
    [2.5,"l","water","liquid","agua","water"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [1,"","bellpepper","aromatic","pimentón rojo","red bell pepper","picado","chopped"],
    [4,"","bellpepper","aromatic","ajíes dulces","sweet ají peppers","picados","chopped"],
    [4,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [1,"tsp","spice","aromatic","comino","cumin"],
    [2,"tbsp","brownsugar","sweet","papelón rallado","grated papelón"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Caraotas negras", b:"Frijoles negros guisados con sofrito y un toque de papelón. Parte del pabellón y de todo desayuno venezolano.",
  st:["Remoja las caraotas 12 horas y escúrrelas.",
      "Cuécelas en el agua 90 minutos, hasta que estén tiernas.",
      "Sofríe la cebolla, los pimentones, los ajíes y el ajo en el aceite 8 minutos. Añade el comino.",
      "Añade el sofrito a las caraotas con el papelón y la sal y cuece 20 minutos, hasta que espesen."],
  tp:["El papelón no las hace dulces: equilibra el sabor.",
      "Machaca algunas contra la olla para espesarlas."],
  v:"caraotas negras venezolanas"},
 en:{n:"Caraotas Negras (Venezuelan Black Beans)", b:"Black beans stewed with sofrito and a touch of cane sugar. Part of pabellón and every Venezuelan breakfast.",
  st:["Soak the beans 12 hours and drain.",
      "Simmer them in the water for 90 minutes, until tender.",
      "Cook the onion, peppers, ají and garlic in the oil for 8 minutes. Add the cumin.",
      "Stir this into the beans with the papelón and salt and simmer 20 minutes, until thick."],
  tp:["The cane sugar doesn't make them sweet: it balances the flavour.",
      "Crush some against the pot to thicken them."],
  v:"venezuelan black beans"}},

{id:"chupe-andino", c:"Venezuela", r:"latin-america", m:"soup", t:60, s:6,
 i:[[2,"","chicken","protein","pechugas de pollo","chicken breasts"],
    [1.5,"l","water","liquid","agua","water"],
    [2,"tbsp","butter","fat","mantequilla","butter"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [4,"","potato","structure","papas","potatoes","en cubos","cubed"],
    [2,"","corn","structure","mazorcas","corn cobs","en rodajas","in rounds"],
    [500,"ml","milk","liquid","leche","milk"],
    [200,"g","queso","enrich","queso blanco suave","soft white cheese","en cubos","cubed"],
    [100,"ml","cream","enrich","crema de leche","single cream"],
    [1,"handful","herb","garnish","cilantro","coriander","picado","chopped"],
    [2,"tsp","salt","salt","sal","salt"]],
 es:{n:"Chupe andino", b:"Sopa cremosa de pollo, papa y maíz con leche y queso que se derrite. Calienta las noches frías de Mérida.",
  st:["Cuece el pollo en el agua con la sal 20 minutos. Desmenúzalo y guarda el caldo.",
      "Sofríe la cebolla y el ajo en la mantequilla 5 minutos.",
      "Añade el caldo, la papa y el maíz y cuece 20 minutos.",
      "Añade la leche y el pollo y calienta 5 minutos sin hervir.",
      "Apaga, añade el queso y la crema y termina con el cilantro."],
  tp:["No dejes hervir tras añadir la leche o se corta.",
      "El queso debe ablandarse, no derretirse del todo."],
  v:"chupe andino de pollo"},
 en:{n:"Chupe Andino (Venezuelan Andean Chicken Chowder)", b:"A creamy soup of chicken, potato and corn with milk and melting cheese. Warms cold nights in Mérida.",
  st:["Simmer the chicken in the water with the salt for 20 minutes. Shred it and keep the broth.",
      "Cook the onion and garlic in the butter for 5 minutes.",
      "Add the broth, potato and corn and simmer 20 minutes.",
      "Add the milk and chicken and heat 5 minutes without boiling.",
      "Turn off, add the cheese and cream and finish with the coriander."],
  tp:["Don't boil after adding the milk or it may split.",
      "The cheese should soften, not fully melt."],
  v:"venezuelan chupe andino"}},

{id:"guasacaca", c:"Venezuela", r:"latin-america", m:"sauce", t:15, s:8,
 i:[[2,"","avocado","structure","aguacates maduros","ripe avocados"],
    [1,"","bellpepper","aromatic","pimentón verde","green bell pepper","en trozos","in chunks"],
    [0.5,"","onion","aromatic","cebolla","onion"],
    [1,"clove","garlic","aromatic","ajo","garlic"],
    [1,"bunch","herb","aromatic","cilantro y perejil","coriander and parsley"],
    [60,"ml","oil","fat","aceite","oil"],
    [2,"tbsp","whitevinegar","acid","vinagre blanco","white vinegar"],
    [1,"tsp","salt","salt","sal","salt"]],
 es:{n:"Guasacaca", b:"Salsa verde de aguacate, pimentón y hierbas con vinagre. Acompaña la parrilla y las arepas en Venezuela.",
  st:["Licúa el pimentón, la cebolla, el ajo, las hierbas, el vinagre y la sal.",
      "Añade el aguacate y el aceite y licúa hasta que quede cremosa.",
      "Prueba y ajusta de sal y vinagre.",
      "Sirve el mismo día."],
  tp:["Tapa con film en contacto para que no se oscurezca.",
      "Debe quedar más líquida que el guacamole."],
  v:"guasacaca venezolana"},
 en:{n:"Guasacaca (Venezuelan Avocado Sauce)", b:"A green sauce of avocado, pepper and herbs with vinegar. Served with grilled meat and arepas in Venezuela.",
  st:["Blend the pepper, onion, garlic, herbs, vinegar and salt.",
      "Add the avocado and oil and blend until creamy.",
      "Taste and adjust the salt and vinegar.",
      "Serve the same day."],
  tp:["Press cling film onto the surface so it doesn't brown.",
      "It should be runnier than guacamole."],
  v:"venezuelan guasacaca"}},

{id:"sancocho-de-pescado-ve", c:"Venezuela", r:"latin-america", m:"soup", t:60, s:6,
 i:[[1,"kg","whitefish","protein","pescado blanco firme (mero o pargo)","firm white fish (grouper or snapper)","en rodajas","in steaks"],
    [2.5,"l","water","liquid","agua","water"],
    [3,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [4,"","bellpepper","aromatic","ajíes dulces","sweet ají peppers","picados","chopped"],
    [4,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [500,"g","cassava","structure","yuca","cassava","en trozos","in chunks"],
    [300,"g","veg","structure","ocumo","taro","en trozos","in chunks"],
    [1,"","plantain","structure","plátano verde","green plantain","en trozos","in chunks"],
    [2,"","corn","structure","mazorcas","corn cobs","en rodajas","in rounds"],
    [1,"bunch","herb","aromatic","cilantro","coriander","picado","chopped"],
    [3,"tsp","salt","salt","sal","salt"],
    [2,"","citrus","acid","limones","limes"]],
 es:{n:"Sancocho de pescado", b:"Sopa de pescado con yuca, ocumo, plátano y maíz. El almuerzo de playa en la costa venezolana.",
  st:["Sofríe la cebolla, los ajíes y el ajo en el aceite 6 minutos.",
      "Añade el agua, la yuca, el ocumo, el plátano, el maíz y la sal y cuece 30 minutos.",
      "Añade el pescado y cuece 10 minutos a fuego suave.",
      "Termina con el cilantro y sirve con limón."],
  tp:["No remuevas tras añadir el pescado para que no se rompa.",
      "Usa las cabezas del pescado para hacer el caldo si las tienes."],
  v:"sancocho de pescado venezolano"},
 en:{n:"Venezuelan Fish Sancocho", b:"Fish soup with cassava, taro, plantain and corn. Beach lunch on the Venezuelan coast.",
  st:["Cook the onion, ají and garlic in the oil for 6 minutes.",
      "Add the water, cassava, taro, plantain, corn and salt and simmer 30 minutes.",
      "Add the fish and cook 10 minutes on a gentle simmer.",
      "Finish with the coriander and serve with lime."],
  tp:["Don't stir once the fish is in so it doesn't break up.",
      "Use the fish heads for the broth if you have them."],
  v:"venezuelan fish sancocho"}},

{id:"pasticho", c:"Venezuela", r:"latin-america", m:"main", t:150, s:8,
 i:[[2,"tbsp","oil","fat","aceite","oil"],
    [1,"","onion","aromatic","cebolla","onion","picada","chopped"],
    [3,"clove","garlic","aromatic","ajo","garlic","picado","chopped"],
    [400,"g","beef","protein","carne molida de res","minced beef"],
    [200,"g","porkmince","protein","carne molida de cerdo","minced pork"],
    [150,"ml","winered","liquid","vino tinto","red wine"],
    [800,"g","tomato","liquid","tomate triturado","crushed tomatoes"],
    [1,"tsp","salt","salt","sal","salt"],
    [60,"g","butter","fat","mantequilla","butter"],
    [60,"g","apflour","thicken","harina de trigo","plain flour"],
    [750,"ml","milk","liquid","leche","milk"],
    [1,"pinch","spice","aromatic","nuez moscada","nutmeg"],
    [300,"g","eggpasta","structure","láminas de lasaña al huevo","egg lasagne sheets"],
    [200,"g","ham","protein","jamón cocido en lonjas","sliced cooked ham"],
    [250,"g","mozzarella","enrich","queso mozzarella","mozzarella","rallado","grated"],
    [80,"g","parmesan","garnish","queso parmesano rallado","grated parmesan"]],
 es:{n:"Pasticho", b:"La lasaña venezolana, con capas de jamón y queso además de la boloñesa y la bechamel. Plato de domingo y de Navidad.",
  st:["Sofríe la cebolla y el ajo en el aceite 5 minutos. Añade las carnes y dora 8 minutos. Añade el vino, el tomate y la sal y cuece 40 minutos.",
      "Derrite la mantequilla, añade la harina y cocina 2 minutos. Añade la leche batiendo y cuece 8 minutos hasta espesar. Añade la nuez moscada.",
      "En una fuente de 25 x 35 cm alterna capas de boloñesa, pasta, bechamel, jamón y mozzarella.",
      "Termina con bechamel y parmesano.",
      "Hornea a 180 °C 45 minutos. Deja reposar 20 minutos antes de cortar."],
  tp:["El reposo es clave para cortar porciones limpias.",
      "Queda aún mejor hecho el día anterior."],
  v:"pasticho venezolano"},
 en:{n:"Pasticho (Venezuelan Lasagne)", b:"Venezuela's lasagne, with layers of ham and cheese besides the bolognese and béchamel. A Sunday and Christmas dish.",
  st:["Cook the onion and garlic in the oil for 5 minutes. Add the meats and brown 8 minutes. Add the wine, tomato and salt and simmer 40 minutes.",
      "Melt the butter, add the flour and cook 2 minutes. Whisk in the milk and cook 8 minutes until thick. Add the nutmeg.",
      "In a 25 x 35 cm dish, layer bolognese, pasta, béchamel, ham and mozzarella.",
      "Finish with béchamel and parmesan.",
      "Bake at 180 °C for 45 minutes. Rest 20 minutes before cutting."],
  tp:["Resting is key for clean slices.",
      "It's even better made the day before."],
  v:"venezuelan pasticho"}},

{id:"bunuelos-de-yuca", c:"Venezuela", r:"latin-america", m:"sweet", t:60, s:20,
 i:[[500,"g","cassava","structure","yuca","cassava","pelada","peeled"],
    [100,"g","queso","enrich","queso blanco duro","hard white cheese","rallado","grated"],
    [1,"","egg","binder","huevo","egg"],
    [1,"tsp","spice","aromatic","anís en grano","aniseed"],
    [500,"ml","oil","fat","aceite para freír","oil for frying"],
    [300,"g","brownsugar","sweet","papelón","papelón (unrefined cane sugar)"],
    [300,"ml","water","liquid","agua","water"],
    [1,"piece","spice","aromatic","rama de canela","cinnamon stick"],
    [4,"piece","spice","aromatic","clavos de olor","cloves"]],
 es:{n:"Buñuelos de yuca", b:"Bolitas fritas de yuca con queso bañadas en melado de papelón. Dulce de Semana Santa en Venezuela.",
  st:["Cuece la yuca 25 minutos, retira las fibras y hazla puré.",
      "Mezcla con el queso, el huevo y el anís hasta tener una masa.",
      "Forma aros o bolitas y fríelos a 175 °C 4 minutos, hasta que estén dorados.",
      "Hierve el papelón con el agua, la canela y el clavo 15 minutos, hasta tener un melado.",
      "Baña los buñuelos con el melado tibio."],
  tp:["Humedece las manos para formar los buñuelos.",
      "El melado espesa al enfriar: caliéntalo antes de servir."],
  v:"buñuelos de yuca venezolanos"},
 en:{n:"Buñuelos de Yuca (Cassava Fritters in Syrup)", b:"Fried cassava and cheese fritters drenched in cane-sugar syrup. A Holy Week sweet in Venezuela.",
  st:["Boil the cassava 25 minutes, remove the fibres and mash.",
      "Mix with the cheese, egg and aniseed into a dough.",
      "Shape rings or balls and fry at 175 °C for 4 minutes, until golden.",
      "Boil the papelón with the water, cinnamon and cloves for 15 minutes into a syrup.",
      "Pour the warm syrup over the fritters."],
  tp:["Wet your hands to shape the fritters.",
      "The syrup thickens as it cools: warm it before serving."],
  v:"venezuelan cassava fritters"}},

{id:"conservas-de-coco", c:"Venezuela", r:"latin-america", m:"sweet", t:60, s:16,
 i:[[300,"g","desiccatedcoconut","structure","coco rallado","grated coconut"],
    [400,"g","brownsugar","sweet","papelón","papelón (unrefined cane sugar)"],
    [250,"ml","water","liquid","agua","water"],
    [1,"piece","spice","aromatic","rama de canela","cinnamon stick"],
    [1,"piece","spice","aromatic","trozo de jengibre","piece of ginger"]],
 es:{n:"Conservas de coco", b:"Dulce de coco rallado cocido en papelón con jengibre, cortado en cuadros. Se vende en las carreteras de Venezuela.",
  st:["Hierve el papelón con el agua, la canela y el jengibre 10 minutos. Retira las especias.",
      "Añade el coco y cuece 25 minutos a fuego medio, removiendo sin parar, hasta que se despegue de la olla.",
      "Extiende sobre una superficie engrasada o una hoja de plátano, de 2 cm de grosor.",
      "Deja enfriar y corta en cuadros."],
  tp:["Cuanto más cocines, más duras quedan.",
      "Guárdalas en un frasco cerrado."],
  v:"conservas de coco venezolanas"},
 en:{n:"Conservas de Coco (Coconut Cane Sugar Squares)", b:"Grated coconut cooked in cane sugar with ginger and cut into squares. Sold along Venezuela's roadsides.",
  st:["Boil the papelón with the water, cinnamon and ginger for 10 minutes. Remove the spices.",
      "Add the coconut and cook 25 minutes over medium heat, stirring constantly, until it pulls away from the pan.",
      "Spread 2 cm thick on a greased surface or a banana leaf.",
      "Cool and cut into squares."],
  tp:["The longer you cook, the harder they get.",
      "Store in a closed jar."],
  v:"venezuelan coconut squares"}},

{id:"batido-de-lechosa", c:"Venezuela", r:"latin-america", m:"drink", t:5, s:2,
 i:[[300,"g","fruit","structure","lechosa madura","ripe papaya","en trozos","in chunks"],
    [300,"ml","milk","liquid","leche fría","cold milk"],
    [2,"tbsp","sugar","sweet","azúcar","sugar"],
    [150,"g","ice","liquid","hielo","ice"]],
 es:{n:"Batido de lechosa", b:"Batido de papaya madura con leche. Se prepara en todas las areperas venezolanas.",
  st:["Pon la lechosa, la leche, el azúcar y el hielo en la licuadora.",
      "Licúa 1 minuto, hasta que esté espumoso.",
      "Sirve de inmediato."],
  tp:["Tómalo recién hecho: la papaya con leche amarga si reposa.",
      "Sin la leche, con agua, es el jugo de lechosa."],
  v:"batido de lechosa"},
 en:{n:"Batido de Lechosa (Papaya Milkshake)", b:"A ripe papaya and milk shake. Made in every Venezuelan arepa shop.",
  st:["Put the papaya, milk, sugar and ice in the blender.",
      "Blend 1 minute, until frothy.",
      "Serve at once."],
  tp:["Drink it fresh: papaya with milk turns bitter if left to stand.",
      "Made with water instead of milk, it's papaya juice."],
  v:"venezuelan papaya milkshake"}},

{id:"negro-en-camisa", c:"Venezuela", r:"latin-america", m:"sweet", t:120, s:8,
 i:[[150,"g","darkchocolate","aromatic","chocolate oscuro","dark chocolate"],
    [150,"g","butter","fat","mantequilla","butter"],
    [150,"g","sugar","sweet","azúcar","sugar"],
    [4,"","egg","structure","huevos","eggs"],
    [60,"g","breadcrumbs","structure","pan rallado","breadcrumbs"],
    [500,"ml","milk","liquid","leche","milk"],
    [3,"","eggyolk","set","yemas de huevo","egg yolks"],
    [80,"g","sugar","sweet","azúcar (segunda parte)","sugar (second part)"],
    [40,"g","cornstarch","thicken","maicena","cornflour"],
    [1,"tsp","vanilla","aromatic","esencia de vainilla","vanilla extract"]],
 es:{n:"Negro en camisa", b:"Pudín de chocolate al vapor cubierto con una camisa de crema pastelera. Postre caraqueño de antaño.",
  st:["Derrite el chocolate con la mantequilla. Bate los huevos con el azúcar hasta que blanqueen, añade el chocolate y el pan rallado.",
      "Vierte en un molde engrasado de 20 cm, tapa con aluminio y cuece a baño María en el horno a 180 °C 50 minutos. Deja enfriar y desmolda.",
      "Calienta la leche. Bate las yemas con el azúcar de la segunda parte y la maicena, añade la leche y cuece 5 minutos removiendo hasta espesar. Añade la vainilla.",
      "Cubre el pudín con la crema tibia y refrigera 2 horas."],
  tp:["Cubre la crema con film en contacto si no la usas enseguida.",
      "Sírvelo frío."],
  v:"negro en camisa venezolano"},
 en:{n:"Negro en Camisa (Chocolate Pudding in Custard)", b:"A steamed chocolate pudding dressed in a 'shirt' of pastry cream. An old-fashioned Caracas dessert.",
  st:["Melt the chocolate with the butter. Whisk the eggs with the sugar until pale, then add the chocolate and breadcrumbs.",
      "Pour into a greased 20 cm mould, cover with foil and bake in a water bath at 180 °C for 50 minutes. Cool and turn out.",
      "Heat the milk. Whisk the yolks with the second part of the sugar and the cornflour, add the milk and cook 5 minutes, stirring, until thick. Add the vanilla.",
      "Coat the pudding with the warm custard and chill 2 hours."],
  tp:["Press cling film onto the custard if not using it straight away.",
      "Serve it cold."],
  v:"venezuelan chocolate pudding custard"}}
];
